Data Formatting

In [31]:
## File Import

import csv;
import pandas as pd;

file = open('/Volumes/GoogleDrive/My Drive/Ambient - Ivan/03 Engineering/03 MVP/Data Processing/Formatted.csv');

type(file)

csvreader = csv.reader(file)

In [60]:
## Create List Object

# create a dataframe
df = pd.DataFrame(columns=['Date', 'Variable', 'Value'])

# display the column

print(type(df))
print(df)
#df
df1 = pd.DataFrame([[5, 6, 7]], columns=['Date', 'Variable', 'Value'])
df1

<class 'pandas.core.frame.DataFrame'>
Empty DataFrame
Columns: [Date, Variable, Value]
Index: []

   Date  Variable  Value
0     5         6      7

In [61]:
df2 = pd.DataFrame([[8, 9, 10]], columns=['Date', 'Variable', 'Value'])
df2

   Date  Variable  Value
0     8         9     10

In [62]:
df1.append(df2, ignore_index=True)

   Date  Variable  Value
0     5         6      7
1     8         9     10

In [88]:
# read file

df = pd.DataFrame(columns=['Date', 'Variable', 'Value'])

with open('/Volumes/GoogleDrive/My Drive/Ambient - Ivan/03 Engineering/03 MVP/Data Processing/Formatted.csv', newline='') as csvfile:
    loaded_csv = csv.reader(csvfile, delimiter=';')
    
    for row in loaded_csv:
        print(row)
        #print(type(row))
        #print(len(row))
        #print(row[0])
        #print(type(row[0]))
        #print(row[1])
        #print(type(row[1]))
        #print(row[2])
        #print(type(row[2]))
        
        #df = pd.DataFrame (row, columns = ['Entries'])
        
        #df_new = df.append(df)
        
        df = pd.DataFrame([[row[0], row[1], row[2]]], columns=['Date', 'Variable', 'Value'])
        #df.append(df1, ignore_index=True)
        #print(', '.join(row))

        
#print(loaded_csv)
        
#print(type(loaded_csv))

['2021-5-4 0:0:5', 'fKWhCounter', '3294.46313476563']
['2021-5-4 0:0:5', 'fActPhLevelMixTank1', '5.57359552383423']
['2021-5-4 0:0:5', 'fActEcLevelMixTank1', '2008.72827148438']
['2021-5-4 0:0:5', 'fActPhLevelMixTank2', '3.86846518516541']
['2021-5-4 0:0:5', 'fActEcLevelMixTank2', '1005.12713623047']
['2021-5-4 0:0:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:0:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:0:5', 'fActTempValMemo', '21']
['2021-5-4 0:0:5', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 0:0:5', 'fActCo2ValMemo', '923']
['2021-5-4 0:0:5', 'fActWaterLevelMixTank1', '282.461456298828']
['2021-5-4 0:0:5', 'fActWaterLevelMixTank2', '273.117614746094']
['2021-5-4 0:0:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:0:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:0:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:0:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:0:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:0:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:0:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:0:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:0:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:0:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:0:5', 'DoVa_Co2', '0']
['2021-5-4 0:0:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:0:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:0:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:0:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:0:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:1:5', 'fKWhCounter', '3294.56323242188']
['2021-5-4 0:1:5', 'fActPhLevelMixTank1', '5.56944465637207']
['2021-5-4 0:1:5', 'fActEcLevelMixTank1', '2006.89721679688']
['2021-5-4 0:1:5', 'fActPhLevelMixTank2', '3.86407065391541']
['2021-5-4 0:1:5', 'fActEcLevelMixTank2', '1023.74340820313']
['2021-5-4 0:1:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:1:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:1:5', 'fActTempValMemo', '20.8999996185303']
['2021-5-4 0:1:5', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 0:1:5', 'fActCo2ValMemo', '927']
['2021-5-4 0:1:5', 'fActWaterLevelMixTank1', '282.705932617188']
['2021-5-4 0:1:5', 'fActWaterLevelMixTank2', '273.552185058594']
['2021-5-4 0:1:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:1:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:1:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:1:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:1:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:1:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:1:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:1:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:1:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:1:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:1:5', 'DoVa_Co2', '0']
['2021-5-4 0:1:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:1:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:1:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:1:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:1:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:2:5', 'fKWhCounter', '3294.66333007813']
['2021-5-4 0:2:5', 'fActPhLevelMixTank1', '5.57261896133423']
['2021-5-4 0:2:5', 'fActEcLevelMixTank1', '2006.59204101563']
['2021-5-4 0:2:5', 'fActPhLevelMixTank2', '3.86797690391541']
['2021-5-4 0:2:5', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 0:2:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:2:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:2:5', 'fActTempValMemo', '20.7000007629395']
['2021-5-4 0:2:5', 'fActRhValMemo', '50']
['2021-5-4 0:2:5', 'fActCo2ValMemo', '923']
['2021-5-4 0:2:5', 'fActWaterLevelMixTank1', '283.222015380859']
['2021-5-4 0:2:5', 'fActWaterLevelMixTank2', '273.742340087891']
['2021-5-4 0:2:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:2:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:2:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:2:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:2:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:2:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:2:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:2:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:2:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:2:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:2:5', 'DoVa_Co2', '0']
['2021-5-4 0:2:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:2:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:2:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:2:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:2:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:3:5', 'fKWhCounter', '3294.66333007813']
['2021-5-4 0:3:5', 'fActPhLevelMixTank1', '5.57066583633423']
['2021-5-4 0:3:5', 'fActEcLevelMixTank1', '2004.76086425781']
['2021-5-4 0:3:5', 'fActPhLevelMixTank2', '3.86797690391541']
['2021-5-4 0:3:5', 'fActEcLevelMixTank2', '1025.57446289063']
['2021-5-4 0:3:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:3:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:3:5', 'fActTempValMemo', '20.5']
['2021-5-4 0:3:5', 'fActRhValMemo', '50']
['2021-5-4 0:3:5', 'fActCo2ValMemo', '921']
['2021-5-4 0:3:5', 'fActWaterLevelMixTank1', '281.945373535156']
['2021-5-4 0:3:5', 'fActWaterLevelMixTank2', '274.068298339844']
['2021-5-4 0:3:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:3:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:3:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:3:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:3:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:3:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:3:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:3:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:3:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:3:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:3:5', 'DoVa_Co2', '0']
['2021-5-4 0:3:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:3:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:3:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:3:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:3:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:4:5', 'fKWhCounter', '3294.76342773438']
['2021-5-4 0:4:5', 'fActPhLevelMixTank1', '5.57042169570923']
['2021-5-4 0:4:5', 'fActEcLevelMixTank1', '2006.59204101563']
['2021-5-4 0:4:5', 'fActPhLevelMixTank2', '3.86968588829041']
['2021-5-4 0:4:5', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 0:4:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:4:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:4:5', 'fActTempValMemo', '20.3999996185303']
['2021-5-4 0:4:5', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 0:4:5', 'fActCo2ValMemo', '921']
['2021-5-4 0:4:5', 'fActWaterLevelMixTank1', '282.081176757813']
['2021-5-4 0:4:5', 'fActWaterLevelMixTank2', '274.828826904297']
['2021-5-4 0:4:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:4:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:4:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:4:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:4:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:4:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:4:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:4:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:4:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:4:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:4:5', 'DoVa_Co2', '0']
['2021-5-4 0:4:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:4:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:4:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:4:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:4:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:5:5', 'fKWhCounter', '3294.86352539063']
['2021-5-4 0:5:5', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 0:5:5', 'fActEcLevelMixTank1', '2005.82897949219']
['2021-5-4 0:5:5', 'fActPhLevelMixTank2', '3.87041831016541']
['2021-5-4 0:5:5', 'fActEcLevelMixTank2', '1025.57446289063']
['2021-5-4 0:5:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:5:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:5:5', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 0:5:5', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 0:5:5', 'fActCo2ValMemo', '922']
['2021-5-4 0:5:5', 'fActWaterLevelMixTank1', '284.362823486328']
['2021-5-4 0:5:5', 'fActWaterLevelMixTank2', '274.883148193359']
['2021-5-4 0:5:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:5:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:5:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:5:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:5:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:5:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:5:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:5:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:5:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:5:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:5:5', 'DoVa_Co2', '0']
['2021-5-4 0:5:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:5:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:5:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:5:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_1_Fred', '0']

['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:5:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:6:5', 'fKWhCounter', '3294.86352539063']
['2021-5-4 0:6:5', 'fActPhLevelMixTank1', '5.57823419570923']
['2021-5-4 0:6:5', 'fActEcLevelMixTank1', '2008.880859375']
['2021-5-4 0:6:5', 'fActPhLevelMixTank2', '3.86504721641541']
['2021-5-4 0:6:5', 'fActEcLevelMixTank2', '1025.72705078125']
['2021-5-4 0:6:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:6:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:6:5', 'fActTempValMemo', '20']
['2021-5-4 0:6:5', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 0:6:5', 'fActCo2ValMemo', '922']
['2021-5-4 0:6:5', 'fActWaterLevelMixTank1', '285.693786621094']
['2021-5-4 0:6:5', 'fActWaterLevelMixTank2', '276.377075195313']
['2021-5-4 0:6:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:6:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:6:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:6:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:6:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:6:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:6:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:6:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:6:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:6:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:6:5', 'DoVa_Co2', '0']
['2021-5-4 0:6:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:6:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:6:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:6:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:6:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:7:5', 'fKWhCounter', '3294.96362304688']
['2021-5-4 0:7:5', 'fActPhLevelMixTank1', '5.58995342254639']
['2021-5-4 0:7:5', 'fActEcLevelMixTank1', '2009.94897460938']
['2021-5-4 0:7:5', 'fActPhLevelMixTank2', '3.87090659141541']
['2021-5-4 0:7:5', 'fActEcLevelMixTank2', '1024.50634765625']
['2021-5-4 0:7:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:7:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:7:5', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 0:7:5', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 0:7:5', 'fActCo2ValMemo', '919']
['2021-5-4 0:7:5', 'fActWaterLevelMixTank1', '285.394989013672']
['2021-5-4 0:7:5', 'fActWaterLevelMixTank2', '276.159790039063']
['2021-5-4 0:7:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:7:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:7:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:7:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:7:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:7:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:7:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:7:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:7:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:7:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:7:5', 'DoVa_Co2', '0']
['2021-5-4 0:7:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:7:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:7:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:7:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:7:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:8:5', 'fKWhCounter', '3294.96362304688']
['2021-5-4 0:8:5', 'fActPhLevelMixTank1', '5.58775615692139']
['2021-5-4 0:8:5', 'fActEcLevelMixTank1', '2007.0498046875']
['2021-5-4 0:8:5', 'fActPhLevelMixTank2', '3.86797690391541']
['2021-5-4 0:8:5', 'fActEcLevelMixTank2', '1022.82781982422']
['2021-5-4 0:8:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:8:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:8:5', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 0:8:5', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 0:8:5', 'fActCo2ValMemo', '920']
['2021-5-4 0:8:5', 'fActWaterLevelMixTank1', '284.064025878906']
['2021-5-4 0:8:5', 'fActWaterLevelMixTank2', '276.404235839844']
['2021-5-4 0:8:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:8:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:8:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:8:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:8:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:8:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:8:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:8:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:8:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:8:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:8:5', 'DoVa_Co2', '0']
['2021-5-4 0:8:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:8:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:8:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:8:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:8:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:9:5', 'fKWhCounter', '3295.06372070313']
['2021-5-4 0:9:5', 'fActPhLevelMixTank1', '5.59239482879639']
['2021-5-4 0:9:5', 'fActEcLevelMixTank1', '2009.18603515625']
['2021-5-4 0:9:5', 'fActPhLevelMixTank2', '3.87432479858398']
['2021-5-4 0:9:5', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 0:9:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:9:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:9:5', 'fActTempValMemo', '19.5']
['2021-5-4 0:9:5', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 0:9:5', 'fActCo2ValMemo', '920']
['2021-5-4 0:9:5', 'fActWaterLevelMixTank1', '284.770263671875']
['2021-5-4 0:9:5', 'fActWaterLevelMixTank2', '276.295593261719']
['2021-5-4 0:9:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:9:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:9:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:9:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:9:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:9:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:9:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:9:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:9:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:9:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:9:5', 'DoVa_Co2', '0']
['2021-5-4 0:9:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:9:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:9:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:9:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:9:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:10:5', 'fKWhCounter', '3295.06372070313']
['2021-5-4 0:10:5', 'fActPhLevelMixTank1', '5.59044170379639']
['2021-5-4 0:10:5', 'fActEcLevelMixTank1', '2007.35498046875']
['2021-5-4 0:10:5', 'fActPhLevelMixTank2', '3.87652206420898']
['2021-5-4 0:10:5', 'fActEcLevelMixTank2', '1025.11669921875']
['2021-5-4 0:10:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:10:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:10:5', 'fActTempValMemo', '19.2999992370605']
['2021-5-4 0:10:5', 'fActRhValMemo', '52.5']
['2021-5-4 0:10:5', 'fActCo2ValMemo', '920']
['2021-5-4 0:10:5', 'fActWaterLevelMixTank1', '286.454315185547']
['2021-5-4 0:10:5', 'fActWaterLevelMixTank2', '277.028991699219']
['2021-5-4 0:10:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:10:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:10:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:10:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:10:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:10:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:10:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:10:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:10:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:10:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:10:5', 'DoVa_Co2', '0']
['2021-5-4 0:10:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:10:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:10:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:10:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_2_Fred', '0']

['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:10:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:11:5', 'fKWhCounter', '3295.16381835938']
['2021-5-4 0:11:5', 'fActPhLevelMixTank1', '5.59776592254639']
['2021-5-4 0:11:5', 'fActEcLevelMixTank1', '2009.79638671875']
['2021-5-4 0:11:5', 'fActPhLevelMixTank2', '3.87066245079041']
['2021-5-4 0:11:5', 'fActEcLevelMixTank2', '1025.11669921875']
['2021-5-4 0:11:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:11:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:11:5', 'fActTempValMemo', '19.2000007629395']
['2021-5-4 0:11:5', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 0:11:5', 'fActCo2ValMemo', '921']
['2021-5-4 0:11:5', 'fActWaterLevelMixTank1', '286.454315185547']
['2021-5-4 0:11:5', 'fActWaterLevelMixTank2', '277.2734375']
['2021-5-4 0:11:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:11:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:11:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:11:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:11:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:11:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:11:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:11:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:11:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:11:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:11:5', 'DoVa_Co2', '0']
['2021-5-4 0:11:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:11:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:11:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:11:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:11:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:12:5', 'fKWhCounter', '3295.16381835938']
['2021-5-4 0:12:5', 'fActPhLevelMixTank1', '5.59874248504639']
['2021-5-4 0:12:5', 'fActEcLevelMixTank1', '2010.71203613281']
['2021-5-4 0:12:5', 'fActPhLevelMixTank2', '3.87554550170898']
['2021-5-4 0:12:5', 'fActEcLevelMixTank2', '1017.18194580078']
['2021-5-4 0:12:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:12:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:12:5', 'fActTempValMemo', '19.1000003814697']
['2021-5-4 0:12:5', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 0:12:5', 'fActCo2ValMemo', '916']
['2021-5-4 0:12:5', 'fActWaterLevelMixTank1', '286.264190673828']
['2021-5-4 0:12:5', 'fActWaterLevelMixTank2', '277.327758789063']
['2021-5-4 0:12:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:12:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:12:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:12:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:12:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:12:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:12:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:12:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:12:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:12:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:12:5', 'DoVa_Co2', '0']
['2021-5-4 0:12:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:12:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:12:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:12:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:12:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:13:5', 'fKWhCounter', '3295.26391601563']
['2021-5-4 0:13:5', 'fActPhLevelMixTank1', '5.59263896942139']
['2021-5-4 0:13:5', 'fActEcLevelMixTank1', '2011.01721191406']
['2021-5-4 0:13:5', 'fActPhLevelMixTank2', '3.87261581420898']
['2021-5-4 0:13:5', 'fActEcLevelMixTank2', '1023.89599609375']
['2021-5-4 0:13:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:13:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:13:5', 'fActTempValMemo', '18.8999996185303']
['2021-5-4 0:13:5', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 0:13:5', 'fActCo2ValMemo', '912']
['2021-5-4 0:13:5', 'fActWaterLevelMixTank1', '287.160552978516']
['2021-5-4 0:13:5', 'fActWaterLevelMixTank2', '277.952514648438']
['2021-5-4 0:13:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:13:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:13:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:13:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:13:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:13:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:13:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:13:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:13:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:13:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:13:5', 'DoVa_Co2', '0']
['2021-5-4 0:13:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:13:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:13:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:13:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:13:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:14:5', 'fKWhCounter', '3295.26391601563']
['2021-5-4 0:14:5', 'fActPhLevelMixTank1', '5.59556865692139']
['2021-5-4 0:14:5', 'fActEcLevelMixTank1', '2011.93273925781']
['2021-5-4 0:14:5', 'fActPhLevelMixTank2', '3.87481307983398']
['2021-5-4 0:14:5', 'fActEcLevelMixTank2', '1027.40563964844']
['2021-5-4 0:14:5', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:14:5', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:14:5', 'fActTempValMemo', '18.7000007629395']
['2021-5-4 0:14:5', 'fActRhValMemo', '53.2999992370605']
['2021-5-4 0:14:5', 'fActCo2ValMemo', '913']
['2021-5-4 0:14:5', 'fActWaterLevelMixTank1', '285.177703857422']
['2021-5-4 0:14:5', 'fActWaterLevelMixTank2', '277.762359619141']
['2021-5-4 0:14:5', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:14:5', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:14:5', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:14:5', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:14:5', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:14:5', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:14:5', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:14:5', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:14:5', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:14:5', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:14:5', 'DoVa_Co2', '0']
['2021-5-4 0:14:5', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:14:5', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:14:5', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:14:5', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:14:5', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:15:6', 'fKWhCounter', '3295.26391601563']
['2021-5-4 0:15:6', 'fActPhLevelMixTank1', '5.59337139129639']
['2021-5-4 0:15:6', 'fActEcLevelMixTank1', '2010.10168457031']
['2021-5-4 0:15:6', 'fActPhLevelMixTank2', '3.86944174766541']
['2021-5-4 0:15:6', 'fActEcLevelMixTank2', '1026.79528808594']
['2021-5-4 0:15:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:15:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:15:6', 'fActTempValMemo', '18.6000003814697']
['2021-5-4 0:15:6', 'fActRhValMemo', '53.2999992370605']
['2021-5-4 0:15:6', 'fActCo2ValMemo', '913']
['2021-5-4 0:15:6', 'fActWaterLevelMixTank1', '286.046875']
['2021-5-4 0:15:6', 'fActWaterLevelMixTank2', '278.495758056641']
['2021-5-4 0:15:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:15:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:15:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:15:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:15:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:15:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:15:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:15:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:15:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:15:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:15:6', 'DoVa_Co2', '0']
['2021-5-4 0:15:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:15:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:15:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:15:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']

['2021-5-4 0:15:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:15:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:16:6', 'fKWhCounter', '3295.36401367188']
['2021-5-4 0:16:6', 'fActPhLevelMixTank1', '5.60093975067139']
['2021-5-4 0:16:6', 'fActEcLevelMixTank1', '2008.11791992188']
['2021-5-4 0:16:6', 'fActPhLevelMixTank2', '3.86382651329041']
['2021-5-4 0:16:6', 'fActEcLevelMixTank2', '1025.57446289063']
['2021-5-4 0:16:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:16:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:16:6', 'fActTempValMemo', '18.3999996185303']
['2021-5-4 0:16:6', 'fActRhValMemo', '54.2999992370605']
['2021-5-4 0:16:6', 'fActCo2ValMemo', '909']
['2021-5-4 0:16:6', 'fActWaterLevelMixTank1', '288.002593994141']
['2021-5-4 0:16:6', 'fActWaterLevelMixTank2', '278.495758056641']
['2021-5-4 0:16:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:16:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:16:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:16:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:16:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:16:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:16:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:16:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:16:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:16:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:16:6', 'DoVa_Co2', '0']
['2021-5-4 0:16:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:16:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:16:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:16:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:16:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:17:6', 'fKWhCounter', '3295.36401367188']
['2021-5-4 0:17:6', 'fActPhLevelMixTank1', '5.59678936004639']
['2021-5-4 0:17:6', 'fActEcLevelMixTank1', '2010.10168457031']
['2021-5-4 0:17:6', 'fActPhLevelMixTank2', '3.87090659141541']
['2021-5-4 0:17:6', 'fActEcLevelMixTank2', '1025.421875']
['2021-5-4 0:17:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:17:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:17:6', 'fActTempValMemo', '18.2999992370605']
['2021-5-4 0:17:6', 'fActRhValMemo', '55.2999992370605']
['2021-5-4 0:17:6', 'fActCo2ValMemo', '908']
['2021-5-4 0:17:6', 'fActWaterLevelMixTank1', '286.725952148438']
['2021-5-4 0:17:6', 'fActWaterLevelMixTank2', '279.011840820313']
['2021-5-4 0:17:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:17:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:17:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:17:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:17:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:17:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:17:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:17:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:17:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:17:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:17:6', 'DoVa_Co2', '0']
['2021-5-4 0:17:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:17:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:17:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:17:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:17:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:18:6', 'fKWhCounter', '3295.36401367188']
['2021-5-4 0:18:6', 'fActPhLevelMixTank1', '5.59874248504639']
['2021-5-4 0:18:6', 'fActEcLevelMixTank1', '2009.79638671875']
['2021-5-4 0:18:6', 'fActPhLevelMixTank2', '3.87139511108398']
['2021-5-4 0:18:6', 'fActEcLevelMixTank2', '1026.79528808594']
['2021-5-4 0:18:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:18:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:18:6', 'fActTempValMemo', '18.2000007629395']
['2021-5-4 0:18:6', 'fActRhValMemo', '56']
['2021-5-4 0:18:6', 'fActCo2ValMemo', '908']
['2021-5-4 0:18:6', 'fActWaterLevelMixTank1', '288.192718505859']
['2021-5-4 0:18:6', 'fActWaterLevelMixTank2', '279.663726806641']
['2021-5-4 0:18:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:18:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:18:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:18:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:18:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:18:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:18:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:18:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:18:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:18:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:18:6', 'DoVa_Co2', '0']
['2021-5-4 0:18:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:18:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:18:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:18:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:18:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:19:6', 'fKWhCounter', '3295.46411132813']
['2021-5-4 0:19:6', 'fActPhLevelMixTank1', '5.59483623504639']
['2021-5-4 0:19:6', 'fActEcLevelMixTank1', '2011.32238769531']
['2021-5-4 0:19:6', 'fActPhLevelMixTank2', '3.86846518516541']
['2021-5-4 0:19:6', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 0:19:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:19:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:19:6', 'fActTempValMemo', '18.1000003814697']
['2021-5-4 0:19:6', 'fActRhValMemo', '56.7999992370605']
['2021-5-4 0:19:6', 'fActCo2ValMemo', '909']
['2021-5-4 0:19:6', 'fActWaterLevelMixTank1', '288.926086425781']
['2021-5-4 0:19:6', 'fActWaterLevelMixTank2', '279.745208740234']
['2021-5-4 0:19:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:19:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:19:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:19:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:19:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:19:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:19:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:19:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:19:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:19:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:19:6', 'DoVa_Co2', '0']
['2021-5-4 0:19:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:19:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:19:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:19:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:19:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:20:6', 'fKWhCounter', '3295.46411132813']
['2021-5-4 0:20:6', 'fActPhLevelMixTank1', '5.60093975067139']
['2021-5-4 0:20:6', 'fActEcLevelMixTank1', '2013.91638183594']
['2021-5-4 0:20:6', 'fActPhLevelMixTank2', '3.87456893920898']
['2021-5-4 0:20:6', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 0:20:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:20:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:20:6', 'fActTempValMemo', '18']
['2021-5-4 0:20:6', 'fActRhValMemo', '57.2999992370605']
['2021-5-4 0:20:6', 'fActCo2ValMemo', '909']
['2021-5-4 0:20:6', 'fActWaterLevelMixTank1', '289.089080810547']
['2021-5-4 0:20:6', 'fActWaterLevelMixTank2', '279.962524414063']
['2021-5-4 0:20:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:20:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:20:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:20:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:20:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:20:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:20:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:20:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:20:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:20:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:20:6', 'DoVa_Co2', '0']
['2021-5-4 0:20:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:20:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:20:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:20:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 0:20:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:20:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:21:6', 'fKWhCounter', '3295.46411132813']
['2021-5-4 0:21:6', 'fActPhLevelMixTank1', '5.59825420379639']
['2021-5-4 0:21:6', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 0:21:6', 'fActPhLevelMixTank2', '3.86797690391541']
['2021-5-4 0:21:6', 'fActEcLevelMixTank2', '1026.64270019531']
['2021-5-4 0:21:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:21:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:21:6', 'fActTempValMemo', '17.8999996185303']
['2021-5-4 0:21:6', 'fActRhValMemo', '57.5']
['2021-5-4 0:21:6', 'fActCo2ValMemo', '908']
['2021-5-4 0:21:6', 'fActWaterLevelMixTank1', '288.844604492188']
['2021-5-4 0:21:6', 'fActWaterLevelMixTank2', '279.582244873047']
['2021-5-4 0:21:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:21:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:21:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:21:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:21:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:21:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:21:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:21:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:21:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:21:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:21:6', 'DoVa_Co2', '0']
['2021-5-4 0:21:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:21:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:21:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:21:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:21:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:22:6', 'fKWhCounter', '3295.56420898438']
['2021-5-4 0:22:6', 'fActPhLevelMixTank1', '5.60606718063354']
['2021-5-4 0:22:6', 'fActEcLevelMixTank1', '2014.2216796875']
['2021-5-4 0:22:6', 'fActPhLevelMixTank2', '3.87066245079041']
['2021-5-4 0:22:6', 'fActEcLevelMixTank2', '1023.89599609375']
['2021-5-4 0:22:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:22:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:22:6', 'fActTempValMemo', '17.7999992370605']
['2021-5-4 0:22:6', 'fActRhValMemo', '57.7999992370605']
['2021-5-4 0:22:6', 'fActCo2ValMemo', '908']
['2021-5-4 0:22:6', 'fActWaterLevelMixTank1', '290.012603759766']
['2021-5-4 0:22:6', 'fActWaterLevelMixTank2', '280.804565429688']
['2021-5-4 0:22:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:22:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:22:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:22:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:22:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:22:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:22:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:22:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:22:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:22:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:22:6', 'DoVa_Co2', '0']
['2021-5-4 0:22:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:22:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:22:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:22:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:22:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:23:6', 'fKWhCounter', '3295.56420898438']
['2021-5-4 0:23:6', 'fActPhLevelMixTank1', '5.60631132125854']
['2021-5-4 0:23:6', 'fActEcLevelMixTank1', '2013.30603027344']
['2021-5-4 0:23:6', 'fActPhLevelMixTank2', '3.87383651733398']
['2021-5-4 0:23:6', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 0:23:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:23:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:23:6', 'fActTempValMemo', '17.6000003814697']
['2021-5-4 0:23:6', 'fActRhValMemo', '58.0999984741211']
['2021-5-4 0:23:6', 'fActCo2ValMemo', '908']
['2021-5-4 0:23:6', 'fActWaterLevelMixTank1', '288.219879150391']
['2021-5-4 0:23:6', 'fActWaterLevelMixTank2', '280.723052978516']
['2021-5-4 0:23:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:23:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:23:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:23:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:23:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:23:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:23:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:23:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:23:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:23:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:23:6', 'DoVa_Co2', '0']
['2021-5-4 0:23:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:23:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:23:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:23:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:23:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:24:6', 'fKWhCounter', '3295.56420898438']
['2021-5-4 0:24:6', 'fActPhLevelMixTank1', '5.60509061813354']
['2021-5-4 0:24:6', 'fActEcLevelMixTank1', '2012.84826660156']
['2021-5-4 0:24:6', 'fActPhLevelMixTank2', '3.87920784950256']
['2021-5-4 0:24:6', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 0:24:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:24:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:24:6', 'fActTempValMemo', '17.6000003814697']
['2021-5-4 0:24:6', 'fActRhValMemo', '58.0999984741211']
['2021-5-4 0:24:6', 'fActCo2ValMemo', '907']
['2021-5-4 0:24:6', 'fActWaterLevelMixTank1', '288.654479980469']
['2021-5-4 0:24:6', 'fActWaterLevelMixTank2', '280.505767822266']
['2021-5-4 0:24:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:24:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:24:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:24:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:24:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:24:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:24:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:24:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:24:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:24:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:24:6', 'DoVa_Co2', '0']
['2021-5-4 0:24:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:24:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:24:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:24:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:24:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:25:6', 'fKWhCounter', '3295.66430664063']
['2021-5-4 0:25:6', 'fActPhLevelMixTank1', '5.60924100875854']
['2021-5-4 0:25:6', 'fActEcLevelMixTank1', '2013.30603027344']
['2021-5-4 0:25:6', 'fActPhLevelMixTank2', '3.87261581420898']
['2021-5-4 0:25:6', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 0:25:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:25:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:25:6', 'fActTempValMemo', '17.3999996185303']
['2021-5-4 0:25:6', 'fActRhValMemo', '58.2000007629395']
['2021-5-4 0:25:6', 'fActCo2ValMemo', '905']
['2021-5-4 0:25:6', 'fActWaterLevelMixTank1', '290.392852783203']
['2021-5-4 0:25:6', 'fActWaterLevelMixTank2', '281.755249023438']
['2021-5-4 0:25:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:25:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:25:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:25:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:25:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:25:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:25:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:25:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:25:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:25:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:25:6', 'DoVa_Co2', '0']
['2021-5-4 0:25:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:25:6', 'DoVa_IrrigateLevel_4_MT1', '0']

['2021-5-4 0:25:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:25:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:25:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:26:6', 'fKWhCounter', '3295.66430664063']
['2021-5-4 0:26:6', 'fActPhLevelMixTank1', '5.60631132125854']
['2021-5-4 0:26:6', 'fActEcLevelMixTank1', '2013.30603027344']
['2021-5-4 0:26:6', 'fActPhLevelMixTank2', '3.87627792358398']
['2021-5-4 0:26:6', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 0:26:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:26:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:26:6', 'fActTempValMemo', '17.2999992370605']
['2021-5-4 0:26:6', 'fActRhValMemo', '58.2999992370605']
['2021-5-4 0:26:6', 'fActCo2ValMemo', '904']
['2021-5-4 0:26:6', 'fActWaterLevelMixTank1', '290.202728271484']
['2021-5-4 0:26:6', 'fActWaterLevelMixTank2', '281.347808837891']
['2021-5-4 0:26:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:26:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:26:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:26:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:26:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:26:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:26:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:26:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:26:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:26:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:26:6', 'DoVa_Co2', '0']
['2021-5-4 0:26:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:26:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:26:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:26:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:26:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:27:6', 'fKWhCounter', '3295.66430664063']
['2021-5-4 0:27:6', 'fActPhLevelMixTank1', '5.60728788375854']
['2021-5-4 0:27:6', 'fActEcLevelMixTank1', '2014.67944335938']
['2021-5-4 0:27:6', 'fActPhLevelMixTank2', '3.87823104858398']
['2021-5-4 0:27:6', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 0:27:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:27:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:27:6', 'fActTempValMemo', '17.2000007629395']
['2021-5-4 0:27:6', 'fActRhValMemo', '58.5999984741211']
['2021-5-4 0:27:6', 'fActCo2ValMemo', '904']
['2021-5-4 0:27:6', 'fActWaterLevelMixTank1', '291.044769287109']
['2021-5-4 0:27:6', 'fActWaterLevelMixTank2', '281.891052246094']
['2021-5-4 0:27:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:27:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:27:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:27:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:27:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:27:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:27:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:27:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:27:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:27:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:27:6', 'DoVa_Co2', '0']
['2021-5-4 0:27:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:27:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:27:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:27:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:27:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:28:6', 'fKWhCounter', '3295.76440429688']
['2021-5-4 0:28:6', 'fActPhLevelMixTank1', '5.61534452438354']
['2021-5-4 0:28:6', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 0:28:6', 'fActPhLevelMixTank2', '3.87945199012756']
['2021-5-4 0:28:6', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 0:28:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:28:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:28:6', 'fActTempValMemo', '17.1000003814697']
['2021-5-4 0:28:6', 'fActRhValMemo', '58.5999984741211']
['2021-5-4 0:28:6', 'fActCo2ValMemo', '904']
['2021-5-4 0:28:6', 'fActWaterLevelMixTank1', '289.387847900391']
['2021-5-4 0:28:6', 'fActWaterLevelMixTank2', '282.379974365234']
['2021-5-4 0:28:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:28:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:28:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:28:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:28:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:28:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:28:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:28:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:28:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:28:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:28:6', 'DoVa_Co2', '0']
['2021-5-4 0:28:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:28:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:28:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:28:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:28:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:29:6', 'fKWhCounter', '3295.76440429688']
['2021-5-4 0:29:6', 'fActPhLevelMixTank1', '5.60606718063354']
['2021-5-4 0:29:6', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 0:29:6', 'fActPhLevelMixTank2', '3.88042855262756']
['2021-5-4 0:29:6', 'fActEcLevelMixTank2', '1022.82781982422']
['2021-5-4 0:29:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:29:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:29:6', 'fActTempValMemo', '16.8999996185303']
['2021-5-4 0:29:6', 'fActRhValMemo', '58.7999992370605']
['2021-5-4 0:29:6', 'fActCo2ValMemo', '904']
['2021-5-4 0:29:6', 'fActWaterLevelMixTank1', '291.778137207031']
['2021-5-4 0:29:6', 'fActWaterLevelMixTank2', '283.059020996094']
['2021-5-4 0:29:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:29:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:29:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:29:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:29:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:29:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:29:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:29:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:29:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:29:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:29:6', 'DoVa_Co2', '0']
['2021-5-4 0:29:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:29:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:29:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:29:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:29:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:30:6', 'fKWhCounter', '3295.76440429688']
['2021-5-4 0:30:6', 'fActPhLevelMixTank1', '5.61265897750854']
['2021-5-4 0:30:6', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 0:30:6', 'fActPhLevelMixTank2', '3.87749862670898']
['2021-5-4 0:30:6', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 0:30:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:30:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:30:6', 'fActTempValMemo', '16.7999992370605']
['2021-5-4 0:30:6', 'fActRhValMemo', '59']
['2021-5-4 0:30:6', 'fActCo2ValMemo', '900']

['2021-5-4 0:30:6', 'fActWaterLevelMixTank1', '291.805297851563']
['2021-5-4 0:30:6', 'fActWaterLevelMixTank2', '283.167663574219']
['2021-5-4 0:30:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:30:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:30:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:30:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:30:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:30:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:30:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:30:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:30:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:30:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:30:6', 'DoVa_Co2', '0']
['2021-5-4 0:30:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:30:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:30:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:30:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:30:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:31:6', 'fKWhCounter', '3295.86450195313']
['2021-5-4 0:31:6', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 0:31:6', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 0:31:6', 'fActPhLevelMixTank2', '3.88140511512756']
['2021-5-4 0:31:6', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 0:31:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:31:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:31:6', 'fActTempValMemo', '16.7000007629395']
['2021-5-4 0:31:6', 'fActRhValMemo', '59.0999984741211']
['2021-5-4 0:31:6', 'fActCo2ValMemo', '898']
['2021-5-4 0:31:6', 'fActWaterLevelMixTank1', '292.076934814453']
['2021-5-4 0:31:6', 'fActWaterLevelMixTank2', '283.004699707031']
['2021-5-4 0:31:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:31:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:31:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:31:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:31:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:31:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:31:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:31:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:31:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:31:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:31:6', 'DoVa_Co2', '0']
['2021-5-4 0:31:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:31:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:31:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:31:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:31:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:32:6', 'fKWhCounter', '3295.86450195313']
['2021-5-4 0:32:6', 'fActPhLevelMixTank1', '5.60997343063354']
['2021-5-4 0:32:6', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 0:32:6', 'fActPhLevelMixTank2', '3.87896370887756']
['2021-5-4 0:32:6', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 0:32:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:32:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:32:6', 'fActTempValMemo', '16.6000003814697']
['2021-5-4 0:32:6', 'fActRhValMemo', '59.0999984741211']
['2021-5-4 0:32:6', 'fActCo2ValMemo', '898']
['2021-5-4 0:32:6', 'fActWaterLevelMixTank1', '292.810333251953']
['2021-5-4 0:32:6', 'fActWaterLevelMixTank2', '282.787414550781']
['2021-5-4 0:32:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:32:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:32:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:32:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:32:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:32:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:32:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:32:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:32:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:32:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:32:6', 'DoVa_Co2', '0']
['2021-5-4 0:32:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:32:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:32:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:32:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:32:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:33:6', 'fKWhCounter', '3295.86450195313']
['2021-5-4 0:33:6', 'fActPhLevelMixTank1', '5.61314725875854']
['2021-5-4 0:33:6', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 0:33:6', 'fActPhLevelMixTank2', '3.88311409950256']
['2021-5-4 0:33:6', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 0:33:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:33:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:33:6', 'fActTempValMemo', '16.5']
['2021-5-4 0:33:6', 'fActRhValMemo', '59.2999992370605']
['2021-5-4 0:33:6', 'fActCo2ValMemo', '896']
['2021-5-4 0:33:6', 'fActWaterLevelMixTank1', '292.212738037109']
['2021-5-4 0:33:6', 'fActWaterLevelMixTank2', '283.249176025391']
['2021-5-4 0:33:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:33:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:33:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:33:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:33:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:33:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:33:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:33:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:33:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:33:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:33:6', 'DoVa_Co2', '0']
['2021-5-4 0:33:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:33:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:33:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:33:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:33:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:34:6', 'fKWhCounter', '3295.96459960938']
['2021-5-4 0:34:6', 'fActPhLevelMixTank1', '5.6187629699707']
['2021-5-4 0:34:6', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 0:34:6', 'fActPhLevelMixTank2', '3.88042855262756']
['2021-5-4 0:34:6', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 0:34:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:34:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:34:6', 'fActTempValMemo', '16.3999996185303']
['2021-5-4 0:34:6', 'fActRhValMemo', '59.2999992370605']
['2021-5-4 0:34:6', 'fActCo2ValMemo', '894']
['2021-5-4 0:34:6', 'fActWaterLevelMixTank1', '292.620178222656']
['2021-5-4 0:34:6', 'fActWaterLevelMixTank2', '283.982543945313']
['2021-5-4 0:34:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:34:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:34:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:34:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:34:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:34:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:34:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:34:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:34:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:34:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:34:6', 'DoVa_Co2', '0']
['2021-5-4 0:34:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:34:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:34:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:34:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 0:34:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:34:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:35:6', 'fKWhCounter', '3295.96459960938']
['2021-5-4 0:35:6', 'fActPhLevelMixTank1', '5.61192655563354']
['2021-5-4 0:35:6', 'fActEcLevelMixTank1', '2016.35791015625']
['2021-5-4 0:35:6', 'fActPhLevelMixTank2', '3.88311409950256']
['2021-5-4 0:35:6', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 0:35:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:35:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:35:6', 'fActTempValMemo', '16.2999992370605']
['2021-5-4 0:35:6', 'fActRhValMemo', '59.4000015258789']
['2021-5-4 0:35:6', 'fActCo2ValMemo', '894']
['2021-5-4 0:35:6', 'fActWaterLevelMixTank1', '292.728820800781']
['2021-5-4 0:35:6', 'fActWaterLevelMixTank2', '284.417144775391']
['2021-5-4 0:35:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:35:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:35:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:35:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:35:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:35:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:35:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:35:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:35:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:35:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:35:6', 'DoVa_Co2', '0']
['2021-5-4 0:35:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:35:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:35:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:35:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:35:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:36:6', 'fKWhCounter', '3295.96459960938']
['2021-5-4 0:36:6', 'fActPhLevelMixTank1', '5.61363554000854']
['2021-5-4 0:36:6', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 0:36:6', 'fActPhLevelMixTank2', '3.88189339637756']
['2021-5-4 0:36:6', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 0:36:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:36:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:36:6', 'fActTempValMemo', '16.2000007629395']
['2021-5-4 0:36:6', 'fActRhValMemo', '59.7000007629395']
['2021-5-4 0:36:6', 'fActCo2ValMemo', '894']
['2021-5-4 0:36:6', 'fActWaterLevelMixTank1', '292.837493896484']
['2021-5-4 0:36:6', 'fActWaterLevelMixTank2', '284.906066894531']
['2021-5-4 0:36:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:36:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:36:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:36:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:36:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:36:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:36:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:36:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:36:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:36:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:36:6', 'DoVa_Co2', '0']
['2021-5-4 0:36:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:36:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:36:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:36:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:36:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:37:6', 'fKWhCounter', '3296.06469726563']
['2021-5-4 0:37:6', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 0:37:6', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 0:37:6', 'fActPhLevelMixTank2', '3.88238167762756']
['2021-5-4 0:37:6', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 0:37:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:37:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:37:6', 'fActTempValMemo', '16']
['2021-5-4 0:37:6', 'fActRhValMemo', '59.7000007629395']
['2021-5-4 0:37:6', 'fActCo2ValMemo', '892']
['2021-5-4 0:37:6', 'fActWaterLevelMixTank1', '293.244903564453']
['2021-5-4 0:37:6', 'fActWaterLevelMixTank2', '284.743103027344']
['2021-5-4 0:37:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:37:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:37:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:37:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:37:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:37:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:37:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:37:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:37:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:37:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:37:6', 'DoVa_Co2', '0']
['2021-5-4 0:37:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:37:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:37:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:37:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:37:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:38:6', 'fKWhCounter', '3296.06469726563']
['2021-5-4 0:38:6', 'fActPhLevelMixTank1', '5.6177864074707']
['2021-5-4 0:38:6', 'fActEcLevelMixTank1', '2003.54016113281']
['2021-5-4 0:38:6', 'fActPhLevelMixTank2', '3.87994027137756']
['2021-5-4 0:38:6', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 0:38:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:38:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:38:6', 'fActTempValMemo', '15.8999996185303']
['2021-5-4 0:38:6', 'fActRhValMemo', '59.7000007629395']
['2021-5-4 0:38:6', 'fActCo2ValMemo', '891']
['2021-5-4 0:38:6', 'fActWaterLevelMixTank1', '293.027618408203']
['2021-5-4 0:38:6', 'fActWaterLevelMixTank2', '285.367828369141']
['2021-5-4 0:38:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:38:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:38:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:38:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:38:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:38:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:38:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:38:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:38:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:38:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:38:6', 'DoVa_Co2', '0']
['2021-5-4 0:38:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:38:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:38:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:38:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:38:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:39:6', 'fKWhCounter', '3296.06469726563']
['2021-5-4 0:39:6', 'fActPhLevelMixTank1', '5.6197395324707']
['2021-5-4 0:39:6', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 0:39:6', 'fActPhLevelMixTank2', '3.88482308387756']
['2021-5-4 0:39:6', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 0:39:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:39:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:39:6', 'fActTempValMemo', '15.8000001907349']
['2021-5-4 0:39:6', 'fActRhValMemo', '59.5999984741211']
['2021-5-4 0:39:6', 'fActCo2ValMemo', '888']
['2021-5-4 0:39:6', 'fActWaterLevelMixTank1', '293.407897949219']
['2021-5-4 0:39:6', 'fActWaterLevelMixTank2', '285.340667724609']
['2021-5-4 0:39:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:39:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:39:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:39:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:39:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:39:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:39:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:39:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:39:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:39:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:39:6', 'DoVa_Co2', '0']
['2021-5-4 0:39:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:39:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:39:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:39:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:39:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:40:6', 'fKWhCounter', '3296.16479492188']
['2021-5-4 0:40:6', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 0:40:6', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 0:40:6', 'fActPhLevelMixTank2', '3.88457894325256']
['2021-5-4 0:40:6', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 0:40:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:40:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:40:6', 'fActTempValMemo', '15.6999998092651']
['2021-5-4 0:40:6', 'fActRhValMemo', '59.7000007629395']
['2021-5-4 0:40:6', 'fActCo2ValMemo', '889']
['2021-5-4 0:40:6', 'fActWaterLevelMixTank1', '294.032623291016']
['2021-5-4 0:40:6', 'fActWaterLevelMixTank2', '285.775268554688']
['2021-5-4 0:40:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:40:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:40:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:40:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:40:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:40:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:40:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:40:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:40:6', 'DoVa_IrrigateLevel_1_MT2', '0']

['2021-5-4 0:40:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:40:6', 'DoVa_Co2', '0']
['2021-5-4 0:40:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:40:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:40:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:40:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:40:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:41:6', 'fKWhCounter', '3296.16479492188']
['2021-5-4 0:41:6', 'fActPhLevelMixTank1', '5.6194953918457']
['2021-5-4 0:41:6', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 0:41:6', 'fActPhLevelMixTank2', '3.87994027137756']
['2021-5-4 0:41:6', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 0:41:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:41:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:41:6', 'fActTempValMemo', '15.6000003814697']
['2021-5-4 0:41:6', 'fActRhValMemo', '59.9000015258789']
['2021-5-4 0:41:6', 'fActCo2ValMemo', '888']
['2021-5-4 0:41:6', 'fActWaterLevelMixTank1', '291.941131591797']
['2021-5-4 0:41:6', 'fActWaterLevelMixTank2', '285.422149658203']
['2021-5-4 0:41:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:41:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:41:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:41:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:41:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:41:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:41:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:41:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:41:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:41:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:41:6', 'DoVa_Co2', '0']
['2021-5-4 0:41:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:41:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:41:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:41:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:41:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:42:6', 'fKWhCounter', '3296.16479492188']
['2021-5-4 0:42:6', 'fActPhLevelMixTank1', '5.6207160949707']
['2021-5-4 0:42:6', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 0:42:6', 'fActPhLevelMixTank2', '3.88555550575256']
['2021-5-4 0:42:6', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 0:42:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:42:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:42:6', 'fActTempValMemo', '15.5']
['2021-5-4 0:42:6', 'fActRhValMemo', '60']
['2021-5-4 0:42:6', 'fActCo2ValMemo', '887']
['2021-5-4 0:42:6', 'fActWaterLevelMixTank1', '293.760986328125']
['2021-5-4 0:42:6', 'fActWaterLevelMixTank2', '285.748107910156']
['2021-5-4 0:42:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:42:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:42:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:42:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:42:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:42:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:42:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:42:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:42:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:42:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:42:6', 'DoVa_Co2', '0']
['2021-5-4 0:42:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:42:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:42:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:42:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:42:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:43:6', 'fKWhCounter', '3296.26489257813']
['2021-5-4 0:43:6', 'fActPhLevelMixTank1', '5.6187629699707']
['2021-5-4 0:43:6', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 0:43:6', 'fActPhLevelMixTank2', '3.88384652137756']
['2021-5-4 0:43:6', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 0:43:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:43:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:43:6', 'fActTempValMemo', '15.3999996185303']
['2021-5-4 0:43:6', 'fActRhValMemo', '60']
['2021-5-4 0:43:6', 'fActCo2ValMemo', '891']
['2021-5-4 0:43:6', 'fActWaterLevelMixTank1', '294.766021728516']
['2021-5-4 0:43:6', 'fActWaterLevelMixTank2', '286.318511962891']
['2021-5-4 0:43:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:43:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:43:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:43:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:43:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:43:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:43:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:43:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:43:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:43:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:43:6', 'DoVa_Co2', '0']
['2021-5-4 0:43:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:43:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:43:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:43:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:43:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:44:6', 'fKWhCounter', '3296.26489257813']
['2021-5-4 0:44:6', 'fActPhLevelMixTank1', '5.6202278137207']
['2021-5-4 0:44:6', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 0:44:6', 'fActPhLevelMixTank2', '3.88018441200256']
['2021-5-4 0:44:6', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 0:44:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:44:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:44:6', 'fActTempValMemo', '15.3000001907349']
['2021-5-4 0:44:6', 'fActRhValMemo', '60.0999984741211']
['2021-5-4 0:44:6', 'fActCo2ValMemo', '889']
['2021-5-4 0:44:6', 'fActWaterLevelMixTank1', '294.684509277344']
['2021-5-4 0:44:6', 'fActWaterLevelMixTank2', '286.7802734375']
['2021-5-4 0:44:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:44:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:44:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:44:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:44:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:44:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:44:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:44:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:44:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:44:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:44:6', 'DoVa_Co2', '0']
['2021-5-4 0:44:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:44:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:44:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:44:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:44:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:45:6', 'fKWhCounter', '3296.26489257813']
['2021-5-4 0:45:6', 'fActPhLevelMixTank1', '5.6265754699707']
['2021-5-4 0:45:6', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 0:45:6', 'fActPhLevelMixTank2', '3.88286995887756']
['2021-5-4 0:45:6', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 0:45:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:45:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:45:6', 'fActTempValMemo', '15.1999998092651']
['2021-5-4 0:45:6', 'fActRhValMemo', '60.2000007629395']
['2021-5-4 0:45:6', 'fActCo2ValMemo', '888']
['2021-5-4 0:45:6', 'fActWaterLevelMixTank1', '293.326416015625']
['2021-5-4 0:45:6', 'fActWaterLevelMixTank2', '287.214874267578']
['2021-5-4 0:45:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:45:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:45:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:45:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:45:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:45:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:45:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:45:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:45:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:45:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:45:6', 'DoVa_Co2', '0']
['2021-5-4 0:45:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:45:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:45:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:45:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_1_Blue', '0']

['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:45:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:46:6', 'fKWhCounter', '3296.26489257813']
['2021-5-4 0:46:6', 'fActPhLevelMixTank1', '5.6253547668457']
['2021-5-4 0:46:6', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 0:46:6', 'fActPhLevelMixTank2', '3.88238167762756']
['2021-5-4 0:46:6', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 0:46:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:46:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:46:6', 'fActTempValMemo', '15.1000003814697']
['2021-5-4 0:46:6', 'fActRhValMemo', '60.2000007629395']
['2021-5-4 0:46:6', 'fActCo2ValMemo', '886']
['2021-5-4 0:46:6', 'fActWaterLevelMixTank1', '295.037628173828']
['2021-5-4 0:46:6', 'fActWaterLevelMixTank2', '287.269195556641']
['2021-5-4 0:46:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:46:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:46:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:46:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:46:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:46:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:46:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:46:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:46:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:46:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:46:6', 'DoVa_Co2', '0']
['2021-5-4 0:46:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:46:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:46:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:46:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:46:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:47:6', 'fKWhCounter', '3296.36499023438']
['2021-5-4 0:47:6', 'fActPhLevelMixTank1', '5.6226692199707']
['2021-5-4 0:47:6', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 0:47:6', 'fActPhLevelMixTank2', '3.88311409950256']
['2021-5-4 0:47:6', 'fActEcLevelMixTank2', '1024.96411132813']
['2021-5-4 0:47:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:47:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:47:6', 'fActTempValMemo', '15']
['2021-5-4 0:47:6', 'fActRhValMemo', '62.5']
['2021-5-4 0:47:6', 'fActCo2ValMemo', '883']
['2021-5-4 0:47:6', 'fActWaterLevelMixTank1', '295.037628173828']
['2021-5-4 0:47:6', 'fActWaterLevelMixTank2', '287.350677490234']
['2021-5-4 0:47:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:47:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:47:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:47:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:47:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:47:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:47:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:47:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:47:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:47:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:47:6', 'DoVa_Co2', '0']
['2021-5-4 0:47:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:47:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:47:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:47:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:47:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:48:6', 'fKWhCounter', '3296.36499023438']
['2021-5-4 0:48:6', 'fActPhLevelMixTank1', '5.6241340637207']
['2021-5-4 0:48:6', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 0:48:6', 'fActPhLevelMixTank2', '3.89263582229614']
['2021-5-4 0:48:6', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 0:48:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:48:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:48:6', 'fActTempValMemo', '15']
['2021-5-4 0:48:6', 'fActRhValMemo', '63.9000015258789']
['2021-5-4 0:48:6', 'fActCo2ValMemo', '881']
['2021-5-4 0:48:6', 'fActWaterLevelMixTank1', '295.173431396484']
['2021-5-4 0:48:6', 'fActWaterLevelMixTank2', '288.056915283203']
['2021-5-4 0:48:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:48:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:48:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:48:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:48:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:48:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:48:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:48:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:48:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:48:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:48:6', 'DoVa_Co2', '0']
['2021-5-4 0:48:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:48:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:48:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:48:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:48:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:49:6', 'fKWhCounter', '3296.36499023438']
['2021-5-4 0:49:6', 'fActPhLevelMixTank1', '5.6292610168457']
['2021-5-4 0:49:6', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 0:49:6', 'fActPhLevelMixTank2', '3.89263582229614']
['2021-5-4 0:49:6', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 0:49:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:49:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:49:6', 'fActTempValMemo', '15']
['2021-5-4 0:49:6', 'fActRhValMemo', '65.0999984741211']
['2021-5-4 0:49:6', 'fActCo2ValMemo', '879']
['2021-5-4 0:49:6', 'fActWaterLevelMixTank1', '294.820343017578']
['2021-5-4 0:49:6', 'fActWaterLevelMixTank2', '288.89892578125']
['2021-5-4 0:49:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:49:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:49:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:49:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:49:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:49:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:49:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:49:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:49:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:49:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:49:6', 'DoVa_Co2', '0']
['2021-5-4 0:49:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:49:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:49:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:49:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:49:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:50:6', 'fKWhCounter', '3296.46508789063']
['2021-5-4 0:50:6', 'fActPhLevelMixTank1', '5.55723762512207']
['2021-5-4 0:50:6', 'fActEcLevelMixTank1', '2013.45861816406']
['2021-5-4 0:50:6', 'fActPhLevelMixTank2', '3.79912710189819']
['2021-5-4 0:50:6', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 0:50:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:50:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:50:6', 'fActTempValMemo', '14.8999996185303']
['2021-5-4 0:50:6', 'fActRhValMemo', '66']
['2021-5-4 0:50:6', 'fActCo2ValMemo', '879']
['2021-5-4 0:50:6', 'fActWaterLevelMixTank1', '288.301361083984']
['2021-5-4 0:50:6', 'fActWaterLevelMixTank2', '297.835357666016']
['2021-5-4 0:50:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:50:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:50:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:50:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:50:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:50:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:50:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:50:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:50:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:50:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:50:6', 'DoVa_Co2', '0']
['2021-5-4 0:50:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:50:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:50:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:50:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_3_Blue', '0']

['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:50:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:51:6', 'fKWhCounter', '3296.46508789063']
['2021-5-4 0:51:6', 'fActPhLevelMixTank1', '5.54869222640991']
['2021-5-4 0:51:6', 'fActEcLevelMixTank1', '2012.39050292969']
['2021-5-4 0:51:6', 'fActPhLevelMixTank2', '3.81353187561035']
['2021-5-4 0:51:6', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 0:51:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:51:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:51:6', 'fActTempValMemo', '14.8999996185303']
['2021-5-4 0:51:6', 'fActRhValMemo', '65']
['2021-5-4 0:51:6', 'fActCo2ValMemo', '877']
['2021-5-4 0:51:6', 'fActWaterLevelMixTank1', '284.851745605469']
['2021-5-4 0:51:6', 'fActWaterLevelMixTank2', '288.274200439453']
['2021-5-4 0:51:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:51:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:51:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:51:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:51:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:51:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:51:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:51:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:51:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:51:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:51:6', 'DoVa_Co2', '0']
['2021-5-4 0:51:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:51:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:51:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:51:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:51:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:52:6', 'fKWhCounter', '3296.56518554688']
['2021-5-4 0:52:6', 'fActPhLevelMixTank1', '5.55504035949707']
['2021-5-4 0:52:6', 'fActEcLevelMixTank1', '2014.52685546875']
['2021-5-4 0:52:6', 'fActPhLevelMixTank2', '3.81719422340393']
['2021-5-4 0:52:6', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 0:52:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:52:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:52:6', 'fActTempValMemo', '14.8000001907349']
['2021-5-4 0:52:6', 'fActRhValMemo', '62.7999992370605']
['2021-5-4 0:52:6', 'fActCo2ValMemo', '876']
['2021-5-4 0:52:6', 'fActWaterLevelMixTank1', '282.624420166016']
['2021-5-4 0:52:6', 'fActWaterLevelMixTank2', '284.688781738281']
['2021-5-4 0:52:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:52:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:52:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:52:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:52:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:52:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:52:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:52:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:52:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:52:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:52:6', 'DoVa_Co2', '0']
['2021-5-4 0:52:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:52:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:52:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:52:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:52:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:53:6', 'fKWhCounter', '3296.66528320313']
['2021-5-4 0:53:6', 'fActPhLevelMixTank1', '5.55699348449707']
['2021-5-4 0:53:6', 'fActEcLevelMixTank1', '2013.30603027344']
['2021-5-4 0:53:6', 'fActPhLevelMixTank2', '3.82232117652893']
['2021-5-4 0:53:6', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 0:53:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:53:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:53:6', 'fActTempValMemo', '14.8000001907349']
['2021-5-4 0:53:6', 'fActRhValMemo', '62.2000007629395']
['2021-5-4 0:53:6', 'fActCo2ValMemo', '874']
['2021-5-4 0:53:6', 'fActWaterLevelMixTank1', '283.357818603516']
['2021-5-4 0:53:6', 'fActWaterLevelMixTank2', '263.420623779297']
['2021-5-4 0:53:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:53:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:53:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:53:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:53:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:53:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:53:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:53:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:53:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:53:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:53:6', 'DoVa_Co2', '0']
['2021-5-4 0:53:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:53:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:53:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:53:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:53:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:54:6', 'fKWhCounter', '3296.76538085938']
['2021-5-4 0:54:6', 'fActPhLevelMixTank1', '5.55504035949707']
['2021-5-4 0:54:6', 'fActEcLevelMixTank1', '2015.28979492188']
['2021-5-4 0:54:6', 'fActPhLevelMixTank2', '3.81841492652893']
['2021-5-4 0:54:6', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 0:54:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:54:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:54:6', 'fActTempValMemo', '14.8000001907349']
['2021-5-4 0:54:6', 'fActRhValMemo', '61.7000007629395']
['2021-5-4 0:54:6', 'fActCo2ValMemo', '871']
['2021-5-4 0:54:6', 'fActWaterLevelMixTank1', '280.424285888672']
['2021-5-4 0:54:6', 'fActWaterLevelMixTank2', '282.434295654297']
['2021-5-4 0:54:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:54:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:54:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:54:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:54:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:54:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:54:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:54:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:54:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:54:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:54:6', 'DoVa_Co2', '0']
['2021-5-4 0:54:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:54:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:54:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:54:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:54:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:55:6', 'fKWhCounter', '3296.76538085938']
['2021-5-4 0:55:6', 'fActPhLevelMixTank1', '5.56895637512207']
['2021-5-4 0:55:6', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 0:55:6', 'fActPhLevelMixTank2', '3.86309385299683']
['2021-5-4 0:55:6', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 0:55:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:55:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:55:6', 'fActTempValMemo', '14.8000001907349']
['2021-5-4 0:55:6', 'fActRhValMemo', '61.5999984741211']
['2021-5-4 0:55:6', 'fActCo2ValMemo', '868']
['2021-5-4 0:55:6', 'fActWaterLevelMixTank1', '280.179809570313']
['2021-5-4 0:55:6', 'fActWaterLevelMixTank2', '277.354919433594']
['2021-5-4 0:55:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:55:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:55:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:55:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:55:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:55:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:55:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:55:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:55:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:55:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:55:6', 'DoVa_Co2', '0']
['2021-5-4 0:55:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:55:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:55:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:55:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']

['2021-5-4 0:55:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:55:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:56:6', 'fKWhCounter', '3296.76538085938']
['2021-5-4 0:56:6', 'fActPhLevelMixTank1', '5.56993293762207']
['2021-5-4 0:56:6', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 0:56:6', 'fActPhLevelMixTank2', '3.86138486862183']
['2021-5-4 0:56:6', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 0:56:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:56:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:56:6', 'fActTempValMemo', '14.6999998092651']
['2021-5-4 0:56:6', 'fActRhValMemo', '61.0999984741211']
['2021-5-4 0:56:6', 'fActCo2ValMemo', '866']
['2021-5-4 0:56:6', 'fActWaterLevelMixTank1', '279.989685058594']
['2021-5-4 0:56:6', 'fActWaterLevelMixTank2', '277.952514648438']
['2021-5-4 0:56:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:56:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:56:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:56:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:56:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:56:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:56:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:56:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:56:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:56:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:56:6', 'DoVa_Co2', '0']
['2021-5-4 0:56:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:56:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:56:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:56:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:56:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:57:6', 'fKWhCounter', '3296.86547851563']
['2021-5-4 0:57:6', 'fActPhLevelMixTank1', '5.57408380508423']
['2021-5-4 0:57:6', 'fActEcLevelMixTank1', '2012.23791503906']
['2021-5-4 0:57:6', 'fActPhLevelMixTank2', '3.85747861862183']
['2021-5-4 0:57:6', 'fActEcLevelMixTank2', '1026.64270019531']
['2021-5-4 0:57:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:57:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:57:6', 'fActTempValMemo', '14.6000003814697']
['2021-5-4 0:57:6', 'fActRhValMemo', '61.4000015258789']
['2021-5-4 0:57:6', 'fActCo2ValMemo', '864']
['2021-5-4 0:57:6', 'fActWaterLevelMixTank1', '279.582244873047']
['2021-5-4 0:57:6', 'fActWaterLevelMixTank2', '278.278442382813']
['2021-5-4 0:57:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:57:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:57:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:57:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:57:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:57:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:57:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:57:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:57:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:57:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:57:6', 'DoVa_Co2', '0']
['2021-5-4 0:57:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:57:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:57:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:57:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:57:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:58:7', 'fKWhCounter', '3296.86547851563']
['2021-5-4 0:58:7', 'fActPhLevelMixTank1', '5.56651496887207']
['2021-5-4 0:58:7', 'fActEcLevelMixTank1', '2013.45861816406']
['2021-5-4 0:58:7', 'fActPhLevelMixTank2', '3.85821104049683']
['2021-5-4 0:58:7', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 0:58:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:58:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:58:7', 'fActTempValMemo', '14.6000003814697']
['2021-5-4 0:58:7', 'fActRhValMemo', '65.0999984741211']
['2021-5-4 0:58:7', 'fActCo2ValMemo', '865']
['2021-5-4 0:58:7', 'fActWaterLevelMixTank1', '280.750213623047']
['2021-5-4 0:58:7', 'fActWaterLevelMixTank2', '278.821685791016']
['2021-5-4 0:58:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:58:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:58:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:58:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:58:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:58:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:58:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:58:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:58:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:58:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:58:7', 'DoVa_Co2', '0']
['2021-5-4 0:58:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:58:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:58:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:58:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:58:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 0:59:6', 'fKWhCounter', '3296.96557617188']
['2021-5-4 0:59:6', 'fActPhLevelMixTank1', '5.57139825820923']
['2021-5-4 0:59:6', 'fActEcLevelMixTank1', '2010.40686035156']
['2021-5-4 0:59:6', 'fActPhLevelMixTank2', '3.85430455207825']
['2021-5-4 0:59:6', 'fActEcLevelMixTank2', '1026.94787597656']
['2021-5-4 0:59:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 0:59:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 0:59:6', 'fActTempValMemo', '14.6000003814697']
['2021-5-4 0:59:6', 'fActRhValMemo', '67.5999984741211']
['2021-5-4 0:59:6', 'fActCo2ValMemo', '864']
['2021-5-4 0:59:6', 'fActWaterLevelMixTank1', '280.804565429688']
['2021-5-4 0:59:6', 'fActWaterLevelMixTank2', '278.794525146484']
['2021-5-4 0:59:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 0:59:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 0:59:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 0:59:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 0:59:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 0:59:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 0:59:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 0:59:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 0:59:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 0:59:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 0:59:6', 'DoVa_Co2', '0']
['2021-5-4 0:59:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 0:59:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 0:59:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 0:59:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 0:59:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:0:6', 'fKWhCounter', '3296.96557617188']
['2021-5-4 1:0:6', 'fActPhLevelMixTank1', '5.55894660949707']
['2021-5-4 1:0:6', 'fActEcLevelMixTank1', '2014.67944335938']
['2021-5-4 1:0:6', 'fActPhLevelMixTank2', '3.81109046936035']
['2021-5-4 1:0:6', 'fActEcLevelMixTank2', '1026.64270019531']
['2021-5-4 1:0:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:0:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:0:6', 'fActTempValMemo', '14.5']
['2021-5-4 1:0:6', 'fActRhValMemo', '69']
['2021-5-4 1:0:6', 'fActCo2ValMemo', '862']
['2021-5-4 1:0:6', 'fActWaterLevelMixTank1', '281.103332519531']
['2021-5-4 1:0:6', 'fActWaterLevelMixTank2', '270.102569580078']
['2021-5-4 1:0:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:0:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:0:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:0:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:0:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:0:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:0:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:0:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:0:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:0:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:0:6', 'DoVa_Co2', '0']
['2021-5-4 1:0:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:0:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:0:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:0:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_1_Red', '0']

['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:0:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:1:6', 'fKWhCounter', '3297.16577148438']
['2021-5-4 1:1:6', 'fActPhLevelMixTank1', '5.56309700012207']
['2021-5-4 1:1:6', 'fActEcLevelMixTank1', '2013.61120605469']
['2021-5-4 1:1:6', 'fActPhLevelMixTank2', '3.81670594215393']
['2021-5-4 1:1:6', 'fActEcLevelMixTank2', '1025.421875']
['2021-5-4 1:1:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:1:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:1:6', 'fActTempValMemo', '14.6999998092651']
['2021-5-4 1:1:6', 'fActRhValMemo', '68.5999984741211']
['2021-5-4 1:1:6', 'fActCo2ValMemo', '862']
['2021-5-4 1:1:6', 'fActWaterLevelMixTank1', '279.337799072266']
['2021-5-4 1:1:6', 'fActWaterLevelMixTank2', '253.995300292969']
['2021-5-4 1:1:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:1:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:1:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:1:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:1:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:1:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:1:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:1:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:1:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:1:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:1:6', 'DoVa_Co2', '0']
['2021-5-4 1:1:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:1:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:1:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:1:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:1:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:2:6', 'fKWhCounter', '3297.36596679688']
['2021-5-4 1:2:6', 'fActPhLevelMixTank1', '5.56456184387207']
['2021-5-4 1:2:6', 'fActEcLevelMixTank1', '2013.00085449219']
['2021-5-4 1:2:6', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 1:2:6', 'fActEcLevelMixTank2', '1026.18493652344']
['2021-5-4 1:2:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:2:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:2:6', 'fActTempValMemo', '14.6999998092651']
['2021-5-4 1:2:6', 'fActRhValMemo', '66.5999984741211']
['2021-5-4 1:2:6', 'fActCo2ValMemo', '860']
['2021-5-4 1:2:6', 'fActWaterLevelMixTank1', '281.456451416016']
['2021-5-4 1:2:6', 'fActWaterLevelMixTank2', '264.615783691406']
['2021-5-4 1:2:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:2:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:2:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:2:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:2:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:2:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:2:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:2:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:2:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:2:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:2:6', 'DoVa_Co2', '0']
['2021-5-4 1:2:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:2:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:2:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:2:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:2:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:3:6', 'fKWhCounter', '3297.56616210938']
['2021-5-4 1:3:6', 'fActPhLevelMixTank1', '5.56407356262207']
['2021-5-4 1:3:6', 'fActEcLevelMixTank1', '2014.06909179688']
['2021-5-4 1:3:6', 'fActPhLevelMixTank2', '3.82696008682251']
['2021-5-4 1:3:6', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 1:3:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:3:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:3:6', 'fActTempValMemo', '14.8000001907349']
['2021-5-4 1:3:6', 'fActRhValMemo', '65.0999984741211']
['2021-5-4 1:3:6', 'fActCo2ValMemo', '860']
['2021-5-4 1:3:6', 'fActWaterLevelMixTank1', '279.989685058594']
['2021-5-4 1:3:6', 'fActWaterLevelMixTank2', '273.796661376953']
['2021-5-4 1:3:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:3:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:3:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:3:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:3:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:3:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:3:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:3:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:3:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:3:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:3:6', 'DoVa_Co2', '0']
['2021-5-4 1:3:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:3:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:3:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:3:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:3:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:4:6', 'fKWhCounter', '3297.76635742188']
['2021-5-4 1:4:6', 'fActPhLevelMixTank1', '5.56505012512207']
['2021-5-4 1:4:6', 'fActEcLevelMixTank1', '2013.45861816406']
['2021-5-4 1:4:6', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 1:4:6', 'fActEcLevelMixTank2', '1026.18493652344']
['2021-5-4 1:4:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:4:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:4:6', 'fActTempValMemo', '14.8000001907349']
['2021-5-4 1:4:6', 'fActRhValMemo', '63.5']
['2021-5-4 1:4:6', 'fActCo2ValMemo', '858']
['2021-5-4 1:4:6', 'fActWaterLevelMixTank1', '278.332763671875']
['2021-5-4 1:4:6', 'fActWaterLevelMixTank2', '260.948852539063']
['2021-5-4 1:4:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:4:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:4:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:4:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:4:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:4:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:4:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:4:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:4:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:4:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:4:6', 'DoVa_Co2', '0']
['2021-5-4 1:4:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:4:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:4:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:4:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:4:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']

['2021-5-4 1:5:6', 'fKWhCounter', '3297.86645507813']
['2021-5-4 1:5:6', 'fActPhLevelMixTank1', '5.57310724258423']
['2021-5-4 1:5:6', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 1:5:6', 'fActPhLevelMixTank2', '3.86895346641541']
['2021-5-4 1:5:6', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 1:5:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:5:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:5:6', 'fActTempValMemo', '14.8000001907349']
['2021-5-4 1:5:6', 'fActRhValMemo', '60.2000007629395']
['2021-5-4 1:5:6', 'fActCo2ValMemo', '856']
['2021-5-4 1:5:6', 'fActWaterLevelMixTank1', '277.599395751953']
['2021-5-4 1:5:6', 'fActWaterLevelMixTank2', '274.367065429688']
['2021-5-4 1:5:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:5:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:5:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:5:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:5:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:5:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:5:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:5:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:5:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:5:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:5:6', 'DoVa_Co2', '0']
['2021-5-4 1:5:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:5:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:5:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:5:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:5:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:6:7', 'fKWhCounter', '3297.96655273438']
['2021-5-4 1:6:7', 'fActPhLevelMixTank1', '5.57164239883423']
['2021-5-4 1:6:7', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 1:6:7', 'fActPhLevelMixTank2', '3.86504721641541']
['2021-5-4 1:6:7', 'fActEcLevelMixTank2', '1027.55822753906']
['2021-5-4 1:6:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:6:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:6:7', 'fActTempValMemo', '14.8999996185303']
['2021-5-4 1:6:7', 'fActRhValMemo', '58.0999984741211']
['2021-5-4 1:6:7', 'fActCo2ValMemo', '857']
['2021-5-4 1:6:7', 'fActWaterLevelMixTank1', '276.10546875']
['2021-5-4 1:6:7', 'fActWaterLevelMixTank2', '275.344909667969']
['2021-5-4 1:6:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:6:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:6:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:6:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:6:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:6:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:6:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:6:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:6:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:6:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:6:7', 'DoVa_Co2', '0']
['2021-5-4 1:6:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:6:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:6:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:6:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:6:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:7:6', 'fKWhCounter', '3298.16674804688']
['2021-5-4 1:7:6', 'fActPhLevelMixTank1', '5.56895637512207']
['2021-5-4 1:7:6', 'fActEcLevelMixTank1', '2015.28979492188']
['2021-5-4 1:7:6', 'fActPhLevelMixTank2', '3.85772275924683']
['2021-5-4 1:7:6', 'fActEcLevelMixTank2', '1026.33752441406']
['2021-5-4 1:7:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:7:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:7:6', 'fActTempValMemo', '15']
['2021-5-4 1:7:6', 'fActRhValMemo', '57.7000007629395']
['2021-5-4 1:7:6', 'fActCo2ValMemo', '857']
['2021-5-4 1:7:6', 'fActWaterLevelMixTank1', '277.871002197266']
['2021-5-4 1:7:6', 'fActWaterLevelMixTank2', '274.530059814453']
['2021-5-4 1:7:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:7:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:7:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:7:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:7:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:7:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:7:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:7:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:7:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:7:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:7:6', 'DoVa_Co2', '0']
['2021-5-4 1:7:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:7:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:7:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:7:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:7:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:8:7', 'fKWhCounter', '3298.26684570313']
['2021-5-4 1:8:7', 'fActPhLevelMixTank1', '5.57139825820923']
['2021-5-4 1:8:7', 'fActEcLevelMixTank1', '2011.93273925781']
['2021-5-4 1:8:7', 'fActPhLevelMixTank2', '3.86187314987183']
['2021-5-4 1:8:7', 'fActEcLevelMixTank2', '1022.06488037109']
['2021-5-4 1:8:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:8:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:8:7', 'fActTempValMemo', '15']
['2021-5-4 1:8:7', 'fActRhValMemo', '58.4000015258789']
['2021-5-4 1:8:7', 'fActCo2ValMemo', '857']
['2021-5-4 1:8:7', 'fActWaterLevelMixTank1', '277.789520263672']
['2021-5-4 1:8:7', 'fActWaterLevelMixTank2', '275.263427734375']
['2021-5-4 1:8:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:8:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:8:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:8:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:8:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:8:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:8:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:8:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:8:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:8:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:8:7', 'DoVa_Co2', '0']
['2021-5-4 1:8:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:8:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:8:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:8:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:8:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:9:6', 'fKWhCounter', '3298.46704101563']
['2021-5-4 1:9:6', 'fActPhLevelMixTank1', '5.57823419570923']
['2021-5-4 1:9:6', 'fActEcLevelMixTank1', '2007.0498046875']
['2021-5-4 1:9:6', 'fActPhLevelMixTank2', '3.85381627082825']
['2021-5-4 1:9:6', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 1:9:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:9:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:9:6', 'fActTempValMemo', '15.1000003814697']
['2021-5-4 1:9:6', 'fActRhValMemo', '59.0999984741211']
['2021-5-4 1:9:6', 'fActCo2ValMemo', '857']
['2021-5-4 1:9:6', 'fActWaterLevelMixTank1', '277.898193359375']
['2021-5-4 1:9:6', 'fActWaterLevelMixTank2', '275.236267089844']
['2021-5-4 1:9:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:9:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:9:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:9:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:9:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:9:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:9:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:9:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:9:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:9:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:9:6', 'DoVa_Co2', '0']
['2021-5-4 1:9:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:9:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:9:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:9:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_3_White', '0']

['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:9:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:10:7', 'fKWhCounter', '3298.56713867188']
['2021-5-4 1:10:7', 'fActPhLevelMixTank1', '5.57237482070923']
['2021-5-4 1:10:7', 'fActEcLevelMixTank1', '2004.60827636719']
['2021-5-4 1:10:7', 'fActPhLevelMixTank2', '3.85259556770325']
['2021-5-4 1:10:7', 'fActEcLevelMixTank2', '1020.84411621094']
['2021-5-4 1:10:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:10:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:10:7', 'fActTempValMemo', '15.3000001907349']
['2021-5-4 1:10:7', 'fActRhValMemo', '59.0999984741211']
['2021-5-4 1:10:7', 'fActCo2ValMemo', '856']
['2021-5-4 1:10:7', 'fActWaterLevelMixTank1', '277.191955566406']
['2021-5-4 1:10:7', 'fActWaterLevelMixTank2', '275.589385986328']
['2021-5-4 1:10:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:10:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:10:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:10:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:10:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:10:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:10:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:10:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:10:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:10:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:10:7', 'DoVa_Co2', '0']
['2021-5-4 1:10:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:10:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:10:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:10:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:10:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:11:6', 'fKWhCounter', '3298.66723632813']
['2021-5-4 1:11:6', 'fActPhLevelMixTank1', '5.57823419570923']
['2021-5-4 1:11:6', 'fActEcLevelMixTank1', '2003.84533691406']
['2021-5-4 1:11:6', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 1:11:6', 'fActEcLevelMixTank2', '1022.52264404297']
['2021-5-4 1:11:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:11:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:11:6', 'fActTempValMemo', '15.3999996185303']
['2021-5-4 1:11:6', 'fActRhValMemo', '59.5']
['2021-5-4 1:11:6', 'fActCo2ValMemo', '856']
['2021-5-4 1:11:6', 'fActWaterLevelMixTank1', '277.979675292969']
['2021-5-4 1:11:6', 'fActWaterLevelMixTank2', '276.920318603516']
['2021-5-4 1:11:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:11:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:11:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:11:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:11:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:11:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:11:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:11:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:11:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:11:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:11:6', 'DoVa_Co2', '0']
['2021-5-4 1:11:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:11:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:11:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:11:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:11:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:12:7', 'fKWhCounter', '3298.86743164063']
['2021-5-4 1:12:7', 'fActPhLevelMixTank1', '5.57237482070923']
['2021-5-4 1:12:7', 'fActEcLevelMixTank1', '2008.11791992188']
['2021-5-4 1:12:7', 'fActPhLevelMixTank2', '3.85283970832825']
['2021-5-4 1:12:7', 'fActEcLevelMixTank2', '1022.52264404297']
['2021-5-4 1:12:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:12:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:12:7', 'fActTempValMemo', '15.5']
['2021-5-4 1:12:7', 'fActRhValMemo', '59.5999984741211']
['2021-5-4 1:12:7', 'fActCo2ValMemo', '852']
['2021-5-4 1:12:7', 'fActWaterLevelMixTank1', '279.799530029297']
['2021-5-4 1:12:7', 'fActWaterLevelMixTank2', '277.219116210938']
['2021-5-4 1:12:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:12:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:12:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:12:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:12:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:12:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:12:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:12:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:12:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:12:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:12:7', 'DoVa_Co2', '0']
['2021-5-4 1:12:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:12:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:12:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:12:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:12:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:13:6', 'fKWhCounter', '3298.96752929688']
['2021-5-4 1:13:6', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 1:13:6', 'fActEcLevelMixTank1', '2005.06604003906']
['2021-5-4 1:13:6', 'fActPhLevelMixTank2', '3.85283970832825']
['2021-5-4 1:13:6', 'fActEcLevelMixTank2', '1022.21746826172']
['2021-5-4 1:13:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:13:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:13:6', 'fActTempValMemo', '15.6000003814697']
['2021-5-4 1:13:6', 'fActRhValMemo', '59.2000007629395']
['2021-5-4 1:13:6', 'fActCo2ValMemo', '848']
['2021-5-4 1:13:6', 'fActWaterLevelMixTank1', '279.663726806641']
['2021-5-4 1:13:6', 'fActWaterLevelMixTank2', '277.354919433594']
['2021-5-4 1:13:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:13:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:13:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:13:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:13:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:13:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:13:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:13:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:13:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:13:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:13:6', 'DoVa_Co2', '0']
['2021-5-4 1:13:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:13:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:13:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:13:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:13:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:14:6', 'fKWhCounter', '3299.06762695313']
['2021-5-4 1:14:6', 'fActPhLevelMixTank1', '5.57628107070923']
['2021-5-4 1:14:6', 'fActEcLevelMixTank1', '2007.50756835938']
['2021-5-4 1:14:6', 'fActPhLevelMixTank2', '3.85747861862183']
['2021-5-4 1:14:6', 'fActEcLevelMixTank2', '1024.96411132813']
['2021-5-4 1:14:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:14:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:14:6', 'fActTempValMemo', '15.6999998092651']
['2021-5-4 1:14:6', 'fActRhValMemo', '59.5']
['2021-5-4 1:14:6', 'fActCo2ValMemo', '847']
['2021-5-4 1:14:6', 'fActWaterLevelMixTank1', '281.211975097656']
['2021-5-4 1:14:6', 'fActWaterLevelMixTank2', '277.762359619141']
['2021-5-4 1:14:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:14:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:14:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:14:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:14:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:14:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:14:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:14:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:14:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:14:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:14:6', 'DoVa_Co2', '0']
['2021-5-4 1:14:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:14:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:14:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:14:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:14:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:15:6', 'fKWhCounter', '3299.26782226563']
['2021-5-4 1:15:6', 'fActPhLevelMixTank1', '5.57994318008423']
['2021-5-4 1:15:6', 'fActEcLevelMixTank1', '2003.99792480469']
['2021-5-4 1:15:6', 'fActPhLevelMixTank2', '3.85161900520325']
['2021-5-4 1:15:6', 'fActEcLevelMixTank2', '1022.52264404297']
['2021-5-4 1:15:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:15:6', 'fTaktCounterLowerLevel', '0']

['2021-5-4 1:15:6', 'fActTempValMemo', '15.8999996185303']
['2021-5-4 1:15:6', 'fActRhValMemo', '59.2000007629395']
['2021-5-4 1:15:6', 'fActCo2ValMemo', '845']
['2021-5-4 1:15:6', 'fActWaterLevelMixTank1', '281.021850585938']
['2021-5-4 1:15:6', 'fActWaterLevelMixTank2', '277.762359619141']
['2021-5-4 1:15:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:15:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:15:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:15:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:15:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:15:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:15:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:15:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:15:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:15:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:15:6', 'DoVa_Co2', '0']
['2021-5-4 1:15:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:15:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:15:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:15:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:15:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:16:7', 'fKWhCounter', '3299.36791992188']
['2021-5-4 1:16:7', 'fActPhLevelMixTank1', '5.57530450820923']
['2021-5-4 1:16:7', 'fActEcLevelMixTank1', '2002.62463378906']
['2021-5-4 1:16:7', 'fActPhLevelMixTank2', '3.85283970832825']
['2021-5-4 1:16:7', 'fActEcLevelMixTank2', '1022.21746826172']
['2021-5-4 1:16:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:16:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:16:7', 'fActTempValMemo', '16']
['2021-5-4 1:16:7', 'fActRhValMemo', '59.2999992370605']
['2021-5-4 1:16:7', 'fActCo2ValMemo', '844']
['2021-5-4 1:16:7', 'fActWaterLevelMixTank1', '281.374969482422']
['2021-5-4 1:16:7', 'fActWaterLevelMixTank2', '278.794525146484']
['2021-5-4 1:16:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:16:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:16:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:16:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:16:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:16:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:16:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:16:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:16:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:16:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:16:7', 'DoVa_Co2', '0']
['2021-5-4 1:16:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:16:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:16:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:16:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:16:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:17:6', 'fKWhCounter', '3299.46801757813']
['2021-5-4 1:17:6', 'fActPhLevelMixTank1', '5.57823419570923']
['2021-5-4 1:17:6', 'fActEcLevelMixTank1', '2005.98156738281']
['2021-5-4 1:17:6', 'fActPhLevelMixTank2', '3.85576963424683']
['2021-5-4 1:17:6', 'fActEcLevelMixTank2', '1022.21746826172']
['2021-5-4 1:17:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:17:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:17:6', 'fActTempValMemo', '16.1000003814697']
['2021-5-4 1:17:6', 'fActRhValMemo', '59.0999984741211']
['2021-5-4 1:17:6', 'fActCo2ValMemo', '840']
['2021-5-4 1:17:6', 'fActWaterLevelMixTank1', '281.565093994141']
['2021-5-4 1:17:6', 'fActWaterLevelMixTank2', '278.088317871094']
['2021-5-4 1:17:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:17:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:17:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:17:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:17:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:17:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:17:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:17:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:17:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:17:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:17:6', 'DoVa_Co2', '0']
['2021-5-4 1:17:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:17:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:17:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:17:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:17:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:18:7', 'fKWhCounter', '3299.66821289063']
['2021-5-4 1:18:7', 'fActPhLevelMixTank1', '5.58433771133423']
['2021-5-4 1:18:7', 'fActEcLevelMixTank1', '2006.59204101563']
['2021-5-4 1:18:7', 'fActPhLevelMixTank2', '3.85894346237183']
['2021-5-4 1:18:7', 'fActEcLevelMixTank2', '1020.99670410156']
['2021-5-4 1:18:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:18:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:18:7', 'fActTempValMemo', '16.2000007629395']
['2021-5-4 1:18:7', 'fActRhValMemo', '57.7000007629395']
['2021-5-4 1:18:7', 'fActCo2ValMemo', '834']
['2021-5-4 1:18:7', 'fActWaterLevelMixTank1', '281.972534179688']
['2021-5-4 1:18:7', 'fActWaterLevelMixTank2', '278.305603027344']
['2021-5-4 1:18:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:18:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:18:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:18:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:18:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:18:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:18:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:18:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:18:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:18:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:18:7', 'DoVa_Co2', '0']
['2021-5-4 1:18:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:18:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:18:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:18:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:18:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:19:6', 'fKWhCounter', '3299.86840820313']
['2021-5-4 1:19:6', 'fActPhLevelMixTank1', '5.58384943008423']
['2021-5-4 1:19:6', 'fActEcLevelMixTank1', '2006.89721679688']
['2021-5-4 1:19:6', 'fActPhLevelMixTank2', '3.85235142707825']
['2021-5-4 1:19:6', 'fActEcLevelMixTank2', '1024.04858398438']
['2021-5-4 1:19:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:19:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:19:6', 'fActTempValMemo', '16.2999992370605']
['2021-5-4 1:19:6', 'fActRhValMemo', '54.7000007629395']
['2021-5-4 1:19:6', 'fActCo2ValMemo', '830']
['2021-5-4 1:19:6', 'fActWaterLevelMixTank1', '282.379974365234']
['2021-5-4 1:19:6', 'fActWaterLevelMixTank2', '278.604400634766']
['2021-5-4 1:19:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:19:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:19:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:19:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:19:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:19:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:19:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:19:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:19:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:19:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:19:6', 'DoVa_Co2', '0']
['2021-5-4 1:19:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:19:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:19:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:19:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:19:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:20:7', 'fKWhCounter', '3299.96850585938']
['2021-5-4 1:20:7', 'fActPhLevelMixTank1', '5.58970928192139']
['2021-5-4 1:20:7', 'fActEcLevelMixTank1', '2007.50756835938']
['2021-5-4 1:20:7', 'fActPhLevelMixTank2', '3.85283970832825']
['2021-5-4 1:20:7', 'fActEcLevelMixTank2', '1048.92114257813']
['2021-5-4 1:20:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:20:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:20:7', 'fActTempValMemo', '16.2999992370605']
['2021-5-4 1:20:7', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 1:20:7', 'fActCo2ValMemo', '829']
['2021-5-4 1:20:7', 'fActWaterLevelMixTank1', '282.108337402344']
['2021-5-4 1:20:7', 'fActWaterLevelMixTank2', '279.663726806641']
['2021-5-4 1:20:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:20:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:20:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:20:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:20:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:20:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:20:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:20:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:20:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:20:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:20:7', 'DoVa_Co2', '0']
['2021-5-4 1:20:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:20:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:20:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:20:7', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:20:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:21:6', 'fKWhCounter', '3300.06860351563']
['2021-5-4 1:21:6', 'fActPhLevelMixTank1', '5.58702373504639']
['2021-5-4 1:21:6', 'fActEcLevelMixTank1', '2006.439453125']
['2021-5-4 1:21:6', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 1:21:6', 'fActEcLevelMixTank2', '1023.28564453125']
['2021-5-4 1:21:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:21:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:21:6', 'fActTempValMemo', '16.3999996185303']
['2021-5-4 1:21:6', 'fActRhValMemo', '55.9000015258789']
['2021-5-4 1:21:6', 'fActCo2ValMemo', '829']
['2021-5-4 1:21:6', 'fActWaterLevelMixTank1', '281.728057861328']
['2021-5-4 1:21:6', 'fActWaterLevelMixTank2', '279.853881835938']
['2021-5-4 1:21:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:21:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:21:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:21:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:21:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:21:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:21:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:21:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:21:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:21:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:21:6', 'DoVa_Co2', '0']
['2021-5-4 1:21:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:21:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:21:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:21:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:21:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:22:6', 'fKWhCounter', '3300.26879882813']
['2021-5-4 1:22:6', 'fActPhLevelMixTank1', '5.58653545379639']
['2021-5-4 1:22:6', 'fActEcLevelMixTank1', '2011.01721191406']
['2021-5-4 1:22:6', 'fActPhLevelMixTank2', '3.86089658737183']
['2021-5-4 1:22:6', 'fActEcLevelMixTank2', '1024.04858398438']
['2021-5-4 1:22:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:22:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:22:6', 'fActTempValMemo', '16.3999996185303']
['2021-5-4 1:22:6', 'fActRhValMemo', '58.9000015258789']
['2021-5-4 1:22:6', 'fActCo2ValMemo', '829']
['2021-5-4 1:22:6', 'fActWaterLevelMixTank1', '281.782409667969']
['2021-5-4 1:22:6', 'fActWaterLevelMixTank2', '279.555084228516']
['2021-5-4 1:22:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:22:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:22:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:22:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:22:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:22:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:22:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:22:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:22:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:22:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:22:6', 'DoVa_Co2', '0']
['2021-5-4 1:22:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:22:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:22:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:22:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:22:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:23:6', 'fKWhCounter', '3300.36889648438']
['2021-5-4 1:23:6', 'fActPhLevelMixTank1', '5.59434795379639']
['2021-5-4 1:23:6', 'fActEcLevelMixTank1', '2012.39050292969']
['2021-5-4 1:23:6', 'fActPhLevelMixTank2', '3.85576963424683']
['2021-5-4 1:23:6', 'fActEcLevelMixTank2', '1024.50634765625']
['2021-5-4 1:23:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:23:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:23:6', 'fActTempValMemo', '16.3999996185303']
['2021-5-4 1:23:6', 'fActRhValMemo', '60.9000015258789']
['2021-5-4 1:23:6', 'fActCo2ValMemo', '830']
['2021-5-4 1:23:6', 'fActWaterLevelMixTank1', '283.493621826172']
['2021-5-4 1:23:6', 'fActWaterLevelMixTank2', '279.772369384766']
['2021-5-4 1:23:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:23:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:23:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:23:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:23:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:23:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:23:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:23:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:23:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:23:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:23:6', 'DoVa_Co2', '0']
['2021-5-4 1:23:6', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:23:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:23:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:23:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:23:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:24:7', 'fKWhCounter', '3300.46899414063']
['2021-5-4 1:24:7', 'fActPhLevelMixTank1', '5.59166240692139']
['2021-5-4 1:24:7', 'fActEcLevelMixTank1', '2011.62756347656']
['2021-5-4 1:24:7', 'fActPhLevelMixTank2', '3.85454869270325']
['2021-5-4 1:24:7', 'fActEcLevelMixTank2', '1024.50634765625']
['2021-5-4 1:24:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:24:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:24:7', 'fActTempValMemo', '16.3999996185303']
['2021-5-4 1:24:7', 'fActRhValMemo', '62']
['2021-5-4 1:24:7', 'fActCo2ValMemo', '829']
['2021-5-4 1:24:7', 'fActWaterLevelMixTank1', '283.846740722656']
['2021-5-4 1:24:7', 'fActWaterLevelMixTank2', '280.071166992188']
['2021-5-4 1:24:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:24:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:24:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:24:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:24:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:24:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:24:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:24:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:24:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:24:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:24:7', 'DoVa_Co2', '0']
['2021-5-4 1:24:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:24:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:24:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:24:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:24:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:25:6', 'fKWhCounter', '3300.56909179688']
['2021-5-4 1:25:6', 'fActPhLevelMixTank1', '5.59874248504639']
['2021-5-4 1:25:6', 'fActEcLevelMixTank1', '2011.32238769531']
['2021-5-4 1:25:6', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 1:25:6', 'fActEcLevelMixTank2', '1027.40563964844']
['2021-5-4 1:25:6', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:25:6', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:25:6', 'fActTempValMemo', '16.3999996185303']
['2021-5-4 1:25:6', 'fActRhValMemo', '62.7999992370605']
['2021-5-4 1:25:6', 'fActCo2ValMemo', '830']
['2021-5-4 1:25:6', 'fActWaterLevelMixTank1', '284.688781738281']
['2021-5-4 1:25:6', 'fActWaterLevelMixTank2', '280.913208007813']
['2021-5-4 1:25:6', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:25:6', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:25:6', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:25:6', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:25:6', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:25:6', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:25:6', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:25:6', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:25:6', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:25:6', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:25:6', 'DoVa_Co2', '0']
['2021-5-4 1:25:6', 'DoVa_IrrigateLevel_3_MT1', '0']

['2021-5-4 1:25:6', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:25:6', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:25:6', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:25:6', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:26:7', 'fKWhCounter', '3300.76928710938']
['2021-5-4 1:26:7', 'fActPhLevelMixTank1', '5.59947490692139']
['2021-5-4 1:26:7', 'fActEcLevelMixTank1', '2011.01721191406']
['2021-5-4 1:26:7', 'fActPhLevelMixTank2', '3.86309385299683']
['2021-5-4 1:26:7', 'fActEcLevelMixTank2', '1027.40563964844']
['2021-5-4 1:26:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:26:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:26:7', 'fActTempValMemo', '16.5']
['2021-5-4 1:26:7', 'fActRhValMemo', '63.2999992370605']
['2021-5-4 1:26:7', 'fActCo2ValMemo', '827']
['2021-5-4 1:26:7', 'fActWaterLevelMixTank1', '284.389984130859']
['2021-5-4 1:26:7', 'fActWaterLevelMixTank2', '280.098327636719']
['2021-5-4 1:26:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:26:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:26:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:26:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:26:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:26:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:26:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:26:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:26:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:26:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:26:7', 'DoVa_Co2', '0']
['2021-5-4 1:26:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:26:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:26:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:26:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:26:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:27:7', 'fKWhCounter', '3300.86938476563']
['2021-5-4 1:27:7', 'fActPhLevelMixTank1', '5.60338163375854']
['2021-5-4 1:27:7', 'fActEcLevelMixTank1', '2010.40686035156']
['2021-5-4 1:27:7', 'fActPhLevelMixTank2', '3.86187314987183']
['2021-5-4 1:27:7', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 1:27:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:27:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:27:7', 'fActTempValMemo', '16.5']
['2021-5-4 1:27:7', 'fActRhValMemo', '63.5999984741211']
['2021-5-4 1:27:7', 'fActCo2ValMemo', '829']
['2021-5-4 1:27:7', 'fActWaterLevelMixTank1', '284.552947998047']
['2021-5-4 1:27:7', 'fActWaterLevelMixTank2', '280.206970214844']
['2021-5-4 1:27:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:27:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:27:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:27:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:27:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:27:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:27:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:27:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:27:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:27:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:27:7', 'DoVa_Co2', '0']
['2021-5-4 1:27:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:27:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:27:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:27:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:27:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:28:7', 'fKWhCounter', '3300.96948242188']
['2021-5-4 1:28:7', 'fActPhLevelMixTank1', '5.61094999313354']
['2021-5-4 1:28:7', 'fActEcLevelMixTank1', '2010.71203613281']
['2021-5-4 1:28:7', 'fActPhLevelMixTank2', '3.85992002487183']
['2021-5-4 1:28:7', 'fActEcLevelMixTank2', '1027.40563964844']
['2021-5-4 1:28:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:28:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:28:7', 'fActTempValMemo', '16.6000003814697']
['2021-5-4 1:28:7', 'fActRhValMemo', '63.7999992370605']
['2021-5-4 1:28:7', 'fActCo2ValMemo', '830']
['2021-5-4 1:28:7', 'fActWaterLevelMixTank1', '285.340667724609']
['2021-5-4 1:28:7', 'fActWaterLevelMixTank2', '280.695892333984']
['2021-5-4 1:28:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:28:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:28:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:28:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:28:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:28:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:28:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:28:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:28:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:28:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:28:7', 'DoVa_Co2', '0']
['2021-5-4 1:28:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:28:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:28:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:28:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:28:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:29:7', 'fKWhCounter', '3301.16967773438']
['2021-5-4 1:29:7', 'fActPhLevelMixTank1', '5.61070585250854']
['2021-5-4 1:29:7', 'fActEcLevelMixTank1', '2014.83203125']
['2021-5-4 1:29:7', 'fActPhLevelMixTank2', '3.86138486862183']
['2021-5-4 1:29:7', 'fActEcLevelMixTank2', '1025.72705078125']
['2021-5-4 1:29:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:29:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:29:7', 'fActTempValMemo', '16.6000003814697']
['2021-5-4 1:29:7', 'fActRhValMemo', '64.0999984741211']
['2021-5-4 1:29:7', 'fActCo2ValMemo', '829']
['2021-5-4 1:29:7', 'fActWaterLevelMixTank1', '283.738098144531']
['2021-5-4 1:29:7', 'fActWaterLevelMixTank2', '281.374969482422']
['2021-5-4 1:29:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:29:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:29:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:29:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:29:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:29:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:29:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:29:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:29:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:29:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:29:7', 'DoVa_Co2', '0']
['2021-5-4 1:29:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:29:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:29:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:29:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:29:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:30:7', 'fKWhCounter', '3301.26977539063']
['2021-5-4 1:30:7', 'fActPhLevelMixTank1', '5.61217069625854']
['2021-5-4 1:30:7', 'fActEcLevelMixTank1', '2016.51049804688']
['2021-5-4 1:30:7', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 1:30:7', 'fActEcLevelMixTank2', '1026.03234863281']
['2021-5-4 1:30:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:30:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:30:7', 'fActTempValMemo', '16.7000007629395']
['2021-5-4 1:30:7', 'fActRhValMemo', '64.1999969482422']
['2021-5-4 1:30:7', 'fActCo2ValMemo', '826']
['2021-5-4 1:30:7', 'fActWaterLevelMixTank1', '285.6123046875']
['2021-5-4 1:30:7', 'fActWaterLevelMixTank2', '281.537933349609']
['2021-5-4 1:30:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:30:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:30:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:30:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:30:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:30:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:30:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:30:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:30:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:30:7', 'DoVa_IrrigateLevel_2_MT2', '0']

['2021-5-4 1:30:7', 'DoVa_Co2', '0']
['2021-5-4 1:30:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:30:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:30:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:30:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:30:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:31:7', 'fKWhCounter', '3301.36987304688']
['2021-5-4 1:31:7', 'fActPhLevelMixTank1', '5.61534452438354']
['2021-5-4 1:31:7', 'fActEcLevelMixTank1', '2016.51049804688']
['2021-5-4 1:31:7', 'fActPhLevelMixTank2', '3.87139511108398']
['2021-5-4 1:31:7', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 1:31:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:31:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:31:7', 'fActTempValMemo', '16.7000007629395']
['2021-5-4 1:31:7', 'fActRhValMemo', '64.3000030517578']
['2021-5-4 1:31:7', 'fActCo2ValMemo', '824']
['2021-5-4 1:31:7', 'fActWaterLevelMixTank1', '285.014709472656']
['2021-5-4 1:31:7', 'fActWaterLevelMixTank2', '281.836730957031']
['2021-5-4 1:31:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:31:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:31:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:31:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:31:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:31:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:31:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:31:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:31:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:31:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:31:7', 'DoVa_Co2', '0']
['2021-5-4 1:31:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:31:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:31:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:31:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:31:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:32:7', 'fKWhCounter', '3301.46997070313']
['2021-5-4 1:32:7', 'fActPhLevelMixTank1', '5.61168241500854']
['2021-5-4 1:32:7', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 1:32:7', 'fActPhLevelMixTank2', '3.87139511108398']
['2021-5-4 1:32:7', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 1:32:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:32:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:32:7', 'fActTempValMemo', '16.7999992370605']
['2021-5-4 1:32:7', 'fActRhValMemo', '64.3000030517578']
['2021-5-4 1:32:7', 'fActCo2ValMemo', '822']
['2021-5-4 1:32:7', 'fActWaterLevelMixTank1', '286.264190673828']
['2021-5-4 1:32:7', 'fActWaterLevelMixTank2', '281.673736572266']
['2021-5-4 1:32:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:32:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:32:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:32:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:32:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:32:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:32:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:32:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:32:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:32:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:32:7', 'DoVa_Co2', '0']
['2021-5-4 1:32:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:32:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:32:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:32:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:32:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:33:7', 'fKWhCounter', '3301.67016601563']
['2021-5-4 1:33:7', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 1:33:7', 'fActEcLevelMixTank1', '2015.4423828125']
['2021-5-4 1:33:7', 'fActPhLevelMixTank2', '3.87041831016541']
['2021-5-4 1:33:7', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 1:33:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:33:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:33:7', 'fActTempValMemo', '16.8999996185303']
['2021-5-4 1:33:7', 'fActRhValMemo', '64.1999969482422']
['2021-5-4 1:33:7', 'fActCo2ValMemo', '819']
['2021-5-4 1:33:7', 'fActWaterLevelMixTank1', '285.476470947266']
['2021-5-4 1:33:7', 'fActWaterLevelMixTank2', '282.081176757813']
['2021-5-4 1:33:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:33:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:33:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:33:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:33:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:33:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:33:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:33:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:33:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:33:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:33:7', 'DoVa_Co2', '0']
['2021-5-4 1:33:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:33:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:33:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:33:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:33:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:34:7', 'fKWhCounter', '3301.77026367188']
['2021-5-4 1:34:7', 'fActPhLevelMixTank1', '5.61387968063354']
['2021-5-4 1:34:7', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 1:34:7', 'fActPhLevelMixTank2', '3.87359237670898']
['2021-5-4 1:34:7', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 1:34:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:34:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:34:7', 'fActTempValMemo', '16.8999996185303']
['2021-5-4 1:34:7', 'fActRhValMemo', '64.0999984741211']
['2021-5-4 1:34:7', 'fActCo2ValMemo', '821']
['2021-5-4 1:34:7', 'fActWaterLevelMixTank1', '285.530792236328']
['2021-5-4 1:34:7', 'fActWaterLevelMixTank2', '283.004699707031']
['2021-5-4 1:34:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:34:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:34:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:34:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:34:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:34:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:34:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:34:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:34:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:34:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:34:7', 'DoVa_Co2', '0']
['2021-5-4 1:34:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:34:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:34:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:34:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:34:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:35:7', 'fKWhCounter', '3301.87036132813']
['2021-5-4 1:35:7', 'fActPhLevelMixTank1', '5.6194953918457']
['2021-5-4 1:35:7', 'fActEcLevelMixTank1', '2016.96826171875']

['2021-5-4 1:35:7', 'fActPhLevelMixTank2', '3.87237167358398']
['2021-5-4 1:35:7', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 1:35:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:35:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:35:7', 'fActTempValMemo', '17']
['2021-5-4 1:35:7', 'fActRhValMemo', '64.1999969482422']
['2021-5-4 1:35:7', 'fActCo2ValMemo', '821']
['2021-5-4 1:35:7', 'fActWaterLevelMixTank1', '286.155548095703']
['2021-5-4 1:35:7', 'fActWaterLevelMixTank2', '282.407135009766']
['2021-5-4 1:35:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:35:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:35:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:35:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:35:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:35:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:35:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:35:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:35:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:35:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:35:7', 'DoVa_Co2', '0']
['2021-5-4 1:35:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:35:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:35:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:35:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:35:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:36:7', 'fKWhCounter', '3302.07055664063']
['2021-5-4 1:36:7', 'fActPhLevelMixTank1', '5.61558866500854']
['2021-5-4 1:36:7', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 1:36:7', 'fActPhLevelMixTank2', '3.86968588829041']
['2021-5-4 1:36:7', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 1:36:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:36:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:36:7', 'fActTempValMemo', '17.1000003814697']
['2021-5-4 1:36:7', 'fActRhValMemo', '63.9000015258789']
['2021-5-4 1:36:7', 'fActCo2ValMemo', '822']
['2021-5-4 1:36:7', 'fActWaterLevelMixTank1', '287.73095703125']
['2021-5-4 1:36:7', 'fActWaterLevelMixTank2', '283.520782470703']
['2021-5-4 1:36:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:36:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:36:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:36:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:36:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:36:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:36:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:36:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:36:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:36:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:36:7', 'DoVa_Co2', '0']
['2021-5-4 1:36:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:36:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:36:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:36:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:36:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:37:7', 'fKWhCounter', '3302.17065429688']
['2021-5-4 1:37:7', 'fActPhLevelMixTank1', '5.61094999313354']
['2021-5-4 1:37:7', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 1:37:7', 'fActPhLevelMixTank2', '3.87237167358398']
['2021-5-4 1:37:7', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 1:37:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:37:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:37:7', 'fActTempValMemo', '17.1000003814697']
['2021-5-4 1:37:7', 'fActRhValMemo', '64.0999984741211']
['2021-5-4 1:37:7', 'fActCo2ValMemo', '823']
['2021-5-4 1:37:7', 'fActWaterLevelMixTank1', '288.219879150391']
['2021-5-4 1:37:7', 'fActWaterLevelMixTank2', '283.873901367188']
['2021-5-4 1:37:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:37:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:37:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:37:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:37:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:37:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:37:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:37:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:37:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:37:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:37:7', 'DoVa_Co2', '0']
['2021-5-4 1:37:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:37:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:37:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:37:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:37:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:38:7', 'fKWhCounter', '3302.27075195313']
['2021-5-4 1:38:7', 'fActPhLevelMixTank1', '5.61461210250854']
['2021-5-4 1:38:7', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 1:38:7', 'fActPhLevelMixTank2', '3.87432479858398']
['2021-5-4 1:38:7', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 1:38:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:38:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:38:7', 'fActTempValMemo', '17.2000007629395']
['2021-5-4 1:38:7', 'fActRhValMemo', '63.7999992370605']
['2021-5-4 1:38:7', 'fActCo2ValMemo', '819']
['2021-5-4 1:38:7', 'fActWaterLevelMixTank1', '288.111236572266']
['2021-5-4 1:38:7', 'fActWaterLevelMixTank2', '283.575103759766']
['2021-5-4 1:38:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:38:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:38:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:38:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:38:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:38:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:38:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:38:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:38:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:38:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:38:7', 'DoVa_Co2', '0']
['2021-5-4 1:38:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:38:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:38:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:38:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:38:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:39:7', 'fKWhCounter', '3302.37084960938']
['2021-5-4 1:39:7', 'fActPhLevelMixTank1', '5.61363554000854']
['2021-5-4 1:39:7', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 1:39:7', 'fActPhLevelMixTank2', '3.87920784950256']
['2021-5-4 1:39:7', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 1:39:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:39:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:39:7', 'fActTempValMemo', '17.2000007629395']
['2021-5-4 1:39:7', 'fActRhValMemo', '63.7000007629395']
['2021-5-4 1:39:7', 'fActCo2ValMemo', '823']
['2021-5-4 1:39:7', 'fActWaterLevelMixTank1', '289.143402099609']
['2021-5-4 1:39:7', 'fActWaterLevelMixTank2', '283.955383300781']
['2021-5-4 1:39:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:39:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:39:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:39:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:39:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:39:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:39:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:39:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:39:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:39:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:39:7', 'DoVa_Co2', '0']
['2021-5-4 1:39:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:39:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:39:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:39:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_2_Red', '0']

['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:39:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:40:7', 'fKWhCounter', '3302.57104492188']
['2021-5-4 1:40:7', 'fActPhLevelMixTank1', '5.6197395324707']
['2021-5-4 1:40:7', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 1:40:7', 'fActPhLevelMixTank2', '3.88018441200256']
['2021-5-4 1:40:7', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 1:40:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:40:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:40:7', 'fActTempValMemo', '17.2999992370605']
['2021-5-4 1:40:7', 'fActRhValMemo', '63.7999992370605']
['2021-5-4 1:40:7', 'fActCo2ValMemo', '817']
['2021-5-4 1:40:7', 'fActWaterLevelMixTank1', '287.921081542969']
['2021-5-4 1:40:7', 'fActWaterLevelMixTank2', '284.009704589844']
['2021-5-4 1:40:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:40:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:40:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:40:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:40:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:40:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:40:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:40:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:40:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:40:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:40:7', 'DoVa_Co2', '0']
['2021-5-4 1:40:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:40:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:40:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:40:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:40:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:41:7', 'fKWhCounter', '3302.67114257813']
['2021-5-4 1:41:7', 'fActPhLevelMixTank1', '5.6253547668457']
['2021-5-4 1:41:7', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 1:41:7', 'fActPhLevelMixTank2', '3.87798690795898']
['2021-5-4 1:41:7', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 1:41:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:41:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:41:7', 'fActTempValMemo', '17.3999996185303']
['2021-5-4 1:41:7', 'fActRhValMemo', '63.4000015258789']
['2021-5-4 1:41:7', 'fActCo2ValMemo', '817']
['2021-5-4 1:41:7', 'fActWaterLevelMixTank1', '287.079071044922']
['2021-5-4 1:41:7', 'fActWaterLevelMixTank2', '284.172698974609']
['2021-5-4 1:41:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:41:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:41:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:41:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:41:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:41:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:41:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:41:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:41:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:41:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:41:7', 'DoVa_Co2', '0']
['2021-5-4 1:41:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:41:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:41:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:41:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:41:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:42:7', 'fKWhCounter', '3302.77124023438']
['2021-5-4 1:42:7', 'fActPhLevelMixTank1', '5.6202278137207']
['2021-5-4 1:42:7', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 1:42:7', 'fActPhLevelMixTank2', '3.88409066200256']
['2021-5-4 1:42:7', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 1:42:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:42:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:42:7', 'fActTempValMemo', '17.3999996185303']
['2021-5-4 1:42:7', 'fActRhValMemo', '63.2000007629395']
['2021-5-4 1:42:7', 'fActCo2ValMemo', '818']
['2021-5-4 1:42:7', 'fActWaterLevelMixTank1', '288.654479980469']
['2021-5-4 1:42:7', 'fActWaterLevelMixTank2', '284.064025878906']
['2021-5-4 1:42:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:42:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:42:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:42:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:42:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:42:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:42:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:42:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:42:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:42:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:42:7', 'DoVa_Co2', '0']
['2021-5-4 1:42:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:42:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:42:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:42:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:42:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:43:7', 'fKWhCounter', '3302.87133789063']
['2021-5-4 1:43:7', 'fActPhLevelMixTank1', '5.6243782043457']
['2021-5-4 1:43:7', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 1:43:7', 'fActPhLevelMixTank2', '3.88335824012756']
['2021-5-4 1:43:7', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 1:43:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:43:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:43:7', 'fActTempValMemo', '17.5']
['2021-5-4 1:43:7', 'fActRhValMemo', '62.9000015258789']
['2021-5-4 1:43:7', 'fActCo2ValMemo', '814']
['2021-5-4 1:43:7', 'fActWaterLevelMixTank1', '287.350677490234']
['2021-5-4 1:43:7', 'fActWaterLevelMixTank2', '284.172698974609']
['2021-5-4 1:43:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:43:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:43:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:43:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:43:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:43:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:43:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:43:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:43:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:43:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:43:7', 'DoVa_Co2', '0']
['2021-5-4 1:43:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:43:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:43:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:43:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']

['2021-5-4 1:43:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:43:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:44:7', 'fKWhCounter', '3303.07153320313']
['2021-5-4 1:44:7', 'fActPhLevelMixTank1', '5.6299934387207']
['2021-5-4 1:44:7', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 1:44:7', 'fActPhLevelMixTank2', '3.88384652137756']
['2021-5-4 1:44:7', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 1:44:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:44:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:44:7', 'fActTempValMemo', '17.6000003814697']
['2021-5-4 1:44:7', 'fActRhValMemo', '62.7999992370605']
['2021-5-4 1:44:7', 'fActCo2ValMemo', '815']
['2021-5-4 1:44:7', 'fActWaterLevelMixTank1', '288.926086425781']
['2021-5-4 1:44:7', 'fActWaterLevelMixTank2', '284.580108642578']
['2021-5-4 1:44:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:44:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:44:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:44:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:44:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:44:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:44:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:44:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:44:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:44:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:44:7', 'DoVa_Co2', '0']
['2021-5-4 1:44:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:44:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:44:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:44:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:44:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:45:7', 'fKWhCounter', '3303.17163085938']
['2021-5-4 1:45:7', 'fActPhLevelMixTank1', '5.6260871887207']
['2021-5-4 1:45:7', 'fActEcLevelMixTank1', '2051.60668945313']
['2021-5-4 1:45:7', 'fActPhLevelMixTank2', '3.88018441200256']
['2021-5-4 1:45:7', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 1:45:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:45:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:45:7', 'fActTempValMemo', '17.6000003814697']
['2021-5-4 1:45:7', 'fActRhValMemo', '62.5999984741211']
['2021-5-4 1:45:7', 'fActCo2ValMemo', '815']
['2021-5-4 1:45:7', 'fActWaterLevelMixTank1', '289.170562744141']
['2021-5-4 1:45:7', 'fActWaterLevelMixTank2', '284.525787353516']
['2021-5-4 1:45:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:45:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:45:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:45:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:45:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:45:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:45:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:45:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:45:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:45:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:45:7', 'DoVa_Co2', '0']
['2021-5-4 1:45:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:45:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:45:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:45:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:45:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:46:7', 'fKWhCounter', '3303.27172851563']
['2021-5-4 1:46:7', 'fActPhLevelMixTank1', '5.63316774368286']
['2021-5-4 1:46:7', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 1:46:7', 'fActPhLevelMixTank2', '3.88555550575256']
['2021-5-4 1:46:7', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 1:46:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:46:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:46:7', 'fActTempValMemo', '17.7000007629395']
['2021-5-4 1:46:7', 'fActRhValMemo', '62.5999984741211']
['2021-5-4 1:46:7', 'fActCo2ValMemo', '816']
['2021-5-4 1:46:7', 'fActWaterLevelMixTank1', '288.953277587891']
['2021-5-4 1:46:7', 'fActWaterLevelMixTank2', '284.851745605469']
['2021-5-4 1:46:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:46:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:46:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:46:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:46:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:46:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:46:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:46:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:46:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:46:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:46:7', 'DoVa_Co2', '0']
['2021-5-4 1:46:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:46:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:46:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:46:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:46:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:47:7', 'fKWhCounter', '3303.37182617188']
['2021-5-4 1:47:7', 'fActPhLevelMixTank1', '5.6302375793457']
['2021-5-4 1:47:7', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 1:47:7', 'fActPhLevelMixTank2', '3.88750886917114']
['2021-5-4 1:47:7', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 1:47:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:47:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:47:7', 'fActTempValMemo', '17.7999992370605']
['2021-5-4 1:47:7', 'fActRhValMemo', '62.2999992370605']
['2021-5-4 1:47:7', 'fActCo2ValMemo', '814']
['2021-5-4 1:47:7', 'fActWaterLevelMixTank1', '288.111236572266']
['2021-5-4 1:47:7', 'fActWaterLevelMixTank2', '284.906066894531']
['2021-5-4 1:47:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:47:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:47:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:47:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:47:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:47:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:47:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:47:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:47:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:47:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:47:7', 'DoVa_Co2', '0']
['2021-5-4 1:47:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:47:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:47:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:47:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:47:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:48:7', 'fKWhCounter', '3303.57202148438']
['2021-5-4 1:48:7', 'fActPhLevelMixTank1', '5.6282844543457']
['2021-5-4 1:48:7', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 1:48:7', 'fActPhLevelMixTank2', '3.88653206825256']
['2021-5-4 1:48:7', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 1:48:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:48:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:48:7', 'fActTempValMemo', '17.7999992370605']
['2021-5-4 1:48:7', 'fActRhValMemo', '61.9000015258789']
['2021-5-4 1:48:7', 'fActCo2ValMemo', '816']
['2021-5-4 1:48:7', 'fActWaterLevelMixTank1', '289.578002929688']
['2021-5-4 1:48:7', 'fActWaterLevelMixTank2', '284.254180908203']
['2021-5-4 1:48:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:48:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:48:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:48:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:48:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:48:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:48:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:48:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:48:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:48:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:48:7', 'DoVa_Co2', '0']
['2021-5-4 1:48:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:48:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:48:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:48:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:48:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:49:7', 'fKWhCounter', '3303.67211914063']
['2021-5-4 1:49:7', 'fActPhLevelMixTank1', '5.63585329055786']
['2021-5-4 1:49:7', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 1:49:7', 'fActPhLevelMixTank2', '3.88409066200256']
['2021-5-4 1:49:7', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 1:49:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:49:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:49:7', 'fActTempValMemo', '17.8999996185303']
['2021-5-4 1:49:7', 'fActRhValMemo', '61.5999984741211']
['2021-5-4 1:49:7', 'fActCo2ValMemo', '815']
['2021-5-4 1:49:7', 'fActWaterLevelMixTank1', '290.094085693359']
['2021-5-4 1:49:7', 'fActWaterLevelMixTank2', '285.856750488281']
['2021-5-4 1:49:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:49:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:49:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:49:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:49:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:49:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:49:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:49:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:49:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:49:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:49:7', 'DoVa_Co2', '0']
['2021-5-4 1:49:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:49:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:49:7', 'DoVa_IrrigateLevel_3_MT2', '0']

['2021-5-4 1:49:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:49:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:50:7', 'fKWhCounter', '3303.77221679688']
['2021-5-4 1:50:7', 'fActPhLevelMixTank1', '5.63316774368286']
['2021-5-4 1:50:7', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 1:50:7', 'fActPhLevelMixTank2', '3.88653206825256']
['2021-5-4 1:50:7', 'fActEcLevelMixTank2', '1038.544921875']
['2021-5-4 1:50:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:50:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:50:7', 'fActTempValMemo', '17.8999996185303']
['2021-5-4 1:50:7', 'fActRhValMemo', '61.2000007629395']
['2021-5-4 1:50:7', 'fActCo2ValMemo', '814']
['2021-5-4 1:50:7', 'fActWaterLevelMixTank1', '290.392852783203']
['2021-5-4 1:50:7', 'fActWaterLevelMixTank2', '285.041870117188']
['2021-5-4 1:50:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:50:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:50:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:50:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:50:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:50:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:50:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:50:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:50:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:50:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:50:7', 'DoVa_Co2', '0']
['2021-5-4 1:50:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:50:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:50:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:50:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:50:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:51:7', 'fKWhCounter', '3303.97241210938']
['2021-5-4 1:51:7', 'fActPhLevelMixTank1', '5.63853883743286']
['2021-5-4 1:51:7', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 1:51:7', 'fActPhLevelMixTank2', '3.88897371292114']
['2021-5-4 1:51:7', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 1:51:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:51:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:51:7', 'fActTempValMemo', '18']
['2021-5-4 1:51:7', 'fActRhValMemo', '60.9000015258789']
['2021-5-4 1:51:7', 'fActCo2ValMemo', '812']
['2021-5-4 1:51:7', 'fActWaterLevelMixTank1', '290.392852783203']
['2021-5-4 1:51:7', 'fActWaterLevelMixTank2', '286.318511962891']
['2021-5-4 1:51:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:51:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:51:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:51:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:51:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:51:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:51:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:51:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:51:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:51:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:51:7', 'DoVa_Co2', '0']
['2021-5-4 1:51:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:51:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:51:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:51:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:51:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:52:7', 'fKWhCounter', '3304.07250976563']
['2021-5-4 1:52:7', 'fActPhLevelMixTank1', '5.64000368118286']
['2021-5-4 1:52:7', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 1:52:7', 'fActPhLevelMixTank2', '3.88995027542114']
['2021-5-4 1:52:7', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 1:52:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:52:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:52:7', 'fActTempValMemo', '18']
['2021-5-4 1:52:7', 'fActRhValMemo', '60.5']
['2021-5-4 1:52:7', 'fActCo2ValMemo', '810']
['2021-5-4 1:52:7', 'fActWaterLevelMixTank1', '290.936126708984']
['2021-5-4 1:52:7', 'fActWaterLevelMixTank2', '286.590148925781']
['2021-5-4 1:52:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:52:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:52:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:52:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:52:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:52:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:52:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:52:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:52:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:52:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:52:7', 'DoVa_Co2', '0']
['2021-5-4 1:52:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:52:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:52:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:52:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:52:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:53:7', 'fKWhCounter', '3304.17260742188']
['2021-5-4 1:53:7', 'fActPhLevelMixTank1', '5.64171266555786']
['2021-5-4 1:53:7', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 1:53:7', 'fActPhLevelMixTank2', '3.88311409950256']
['2021-5-4 1:53:7', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 1:53:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:53:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:53:7', 'fActTempValMemo', '18']
['2021-5-4 1:53:7', 'fActRhValMemo', '60.0999984741211']
['2021-5-4 1:53:7', 'fActCo2ValMemo', '809']
['2021-5-4 1:53:7', 'fActWaterLevelMixTank1', '290.420043945313']
['2021-5-4 1:53:7', 'fActWaterLevelMixTank2', '285.639465332031']
['2021-5-4 1:53:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:53:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:53:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:53:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:53:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:53:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:53:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:53:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:53:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:53:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:53:7', 'DoVa_Co2', '0']
['2021-5-4 1:53:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:53:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:53:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:53:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:53:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:54:7', 'fKWhCounter', '3304.27270507813']
['2021-5-4 1:54:7', 'fActPhLevelMixTank1', '5.64806032180786']
['2021-5-4 1:54:7', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 1:54:7', 'fActPhLevelMixTank2', '3.88946199417114']
['2021-5-4 1:54:7', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 1:54:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:54:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:54:7', 'fActTempValMemo', '18.1000003814697']
['2021-5-4 1:54:7', 'fActRhValMemo', '59.5999984741211']
['2021-5-4 1:54:7', 'fActCo2ValMemo', '811']
['2021-5-4 1:54:7', 'fActWaterLevelMixTank1', '290.936126708984']
['2021-5-4 1:54:7', 'fActWaterLevelMixTank2', '285.802429199219']
['2021-5-4 1:54:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:54:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:54:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:54:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:54:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:54:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:54:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:54:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:54:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:54:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:54:7', 'DoVa_Co2', '0']
['2021-5-4 1:54:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:54:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:54:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:54:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']

['2021-5-4 1:54:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:54:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:55:7', 'fKWhCounter', '3304.47290039063']
['2021-5-4 1:55:7', 'fActPhLevelMixTank1', '5.64293336868286']
['2021-5-4 1:55:7', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 1:55:7', 'fActPhLevelMixTank2', '3.89165925979614']
['2021-5-4 1:55:7', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 1:55:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:55:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:55:7', 'fActTempValMemo', '18.2000007629395']
['2021-5-4 1:55:7', 'fActRhValMemo', '59.2999992370605']
['2021-5-4 1:55:7', 'fActCo2ValMemo', '813']
['2021-5-4 1:55:7', 'fActWaterLevelMixTank1', '289.795288085938']
['2021-5-4 1:55:7', 'fActWaterLevelMixTank2', '286.101226806641']
['2021-5-4 1:55:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:55:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:55:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:55:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:55:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:55:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:55:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:55:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:55:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:55:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:55:7', 'DoVa_Co2', '0']
['2021-5-4 1:55:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:55:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:55:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:55:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:55:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:56:7', 'fKWhCounter', '3304.57299804688']
['2021-5-4 1:56:7', 'fActPhLevelMixTank1', '5.65294361114502']
['2021-5-4 1:56:7', 'fActEcLevelMixTank1', '2034.21130371094']
['2021-5-4 1:56:7', 'fActPhLevelMixTank2', '3.88579964637756']
['2021-5-4 1:56:7', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 1:56:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:56:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:56:7', 'fActTempValMemo', '18.2000007629395']
['2021-5-4 1:56:7', 'fActRhValMemo', '59']
['2021-5-4 1:56:7', 'fActCo2ValMemo', '812']
['2021-5-4 1:56:7', 'fActWaterLevelMixTank1', '291.452209472656']
['2021-5-4 1:56:7', 'fActWaterLevelMixTank2', '286.590148925781']
['2021-5-4 1:56:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:56:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:56:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:56:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:56:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:56:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:56:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:56:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:56:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:56:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:56:7', 'DoVa_Co2', '0']
['2021-5-4 1:56:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:56:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:56:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:56:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:56:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:57:7', 'fKWhCounter', '3304.67309570313']
['2021-5-4 1:57:7', 'fActPhLevelMixTank1', '5.64830446243286']
['2021-5-4 1:57:7', 'fActEcLevelMixTank1', '2033.29565429688']
['2021-5-4 1:57:7', 'fActPhLevelMixTank2', '3.88579964637756']
['2021-5-4 1:57:7', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 1:57:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:57:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:57:7', 'fActTempValMemo', '18.2000007629395']
['2021-5-4 1:57:7', 'fActRhValMemo', '58.9000015258789']
['2021-5-4 1:57:7', 'fActCo2ValMemo', '810']
['2021-5-4 1:57:7', 'fActWaterLevelMixTank1', '291.234893798828']
['2021-5-4 1:57:7', 'fActWaterLevelMixTank2', '287.024719238281']
['2021-5-4 1:57:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:57:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:57:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:57:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:57:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:57:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:57:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:57:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:57:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:57:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:57:7', 'DoVa_Co2', '0']
['2021-5-4 1:57:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:57:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:57:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:57:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:57:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:58:7', 'fKWhCounter', '3304.77319335938']
['2021-5-4 1:58:7', 'fActPhLevelMixTank1', '5.65050220489502']
['2021-5-4 1:58:7', 'fActEcLevelMixTank1', '2031.0068359375']
['2021-5-4 1:58:7', 'fActPhLevelMixTank2', '3.88848543167114']
['2021-5-4 1:58:7', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 1:58:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:58:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:58:7', 'fActTempValMemo', '18.2999992370605']
['2021-5-4 1:58:7', 'fActRhValMemo', '58.7000007629395']
['2021-5-4 1:58:7', 'fActCo2ValMemo', '805']
['2021-5-4 1:58:7', 'fActWaterLevelMixTank1', '290.284210205078']
['2021-5-4 1:58:7', 'fActWaterLevelMixTank2', '286.291351318359']
['2021-5-4 1:58:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:58:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:58:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:58:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:58:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:58:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:58:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:58:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:58:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:58:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:58:7', 'DoVa_Co2', '0']
['2021-5-4 1:58:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:58:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:58:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:58:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:58:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 1:59:7', 'fKWhCounter', '3304.97338867188']
['2021-5-4 1:59:7', 'fActPhLevelMixTank1', '5.65099048614502']
['2021-5-4 1:59:7', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 1:59:7', 'fActPhLevelMixTank2', '3.89068269729614']
['2021-5-4 1:59:7', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 1:59:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 1:59:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 1:59:7', 'fActTempValMemo', '18.2999992370605']
['2021-5-4 1:59:7', 'fActRhValMemo', '58.5']
['2021-5-4 1:59:7', 'fActCo2ValMemo', '805']
['2021-5-4 1:59:7', 'fActWaterLevelMixTank1', '291.588012695313']
['2021-5-4 1:59:7', 'fActWaterLevelMixTank2', '286.834594726563']
['2021-5-4 1:59:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 1:59:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 1:59:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 1:59:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 1:59:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 1:59:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 1:59:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 1:59:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 1:59:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 1:59:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 1:59:7', 'DoVa_Co2', '0']
['2021-5-4 1:59:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 1:59:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 1:59:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 1:59:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 1:59:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:0:7', 'fKWhCounter', '3305.07348632813']
['2021-5-4 2:0:7', 'fActPhLevelMixTank1', '5.65416431427002']

['2021-5-4 2:0:7', 'fActEcLevelMixTank1', '2031.46459960938']
['2021-5-4 2:0:7', 'fActPhLevelMixTank2', '3.88653206825256']
['2021-5-4 2:0:7', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 2:0:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:0:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:0:7', 'fActTempValMemo', '18.2999992370605']
['2021-5-4 2:0:7', 'fActRhValMemo', '58.2000007629395']
['2021-5-4 2:0:7', 'fActCo2ValMemo', '804']
['2021-5-4 2:0:7', 'fActWaterLevelMixTank1', '291.452209472656']
['2021-5-4 2:0:7', 'fActWaterLevelMixTank2', '286.698791503906']
['2021-5-4 2:0:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:0:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:0:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:0:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:0:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:0:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:0:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:0:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:0:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:0:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:0:7', 'DoVa_Co2', '0']
['2021-5-4 2:0:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:0:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:0:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:0:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:0:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:1:7', 'fKWhCounter', '3305.17358398438']
['2021-5-4 2:1:7', 'fActPhLevelMixTank1', '5.65782642364502']
['2021-5-4 2:1:7', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 2:1:7', 'fActPhLevelMixTank2', '3.88848543167114']
['2021-5-4 2:1:7', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 2:1:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:1:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:1:7', 'fActTempValMemo', '18.3999996185303']
['2021-5-4 2:1:7', 'fActRhValMemo', '58.0999984741211']
['2021-5-4 2:1:7', 'fActCo2ValMemo', '804']
['2021-5-4 2:1:7', 'fActWaterLevelMixTank1', '292.076934814453']
['2021-5-4 2:1:7', 'fActWaterLevelMixTank2', '287.214874267578']
['2021-5-4 2:1:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:1:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:1:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:1:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:1:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:1:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:1:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:1:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:1:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:1:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:1:7', 'DoVa_Co2', '0']
['2021-5-4 2:1:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:1:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:1:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:1:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:1:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:2:7', 'fKWhCounter', '3305.37377929688']
['2021-5-4 2:2:7', 'fActPhLevelMixTank1', '5.65831470489502']
['2021-5-4 2:2:7', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 2:2:7', 'fActPhLevelMixTank2', '3.89336824417114']
['2021-5-4 2:2:7', 'fActEcLevelMixTank2', '1039.30786132813']
['2021-5-4 2:2:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:2:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:2:7', 'fActTempValMemo', '18.5']
['2021-5-4 2:2:7', 'fActRhValMemo', '58']
['2021-5-4 2:2:7', 'fActCo2ValMemo', '801']
['2021-5-4 2:2:7', 'fActWaterLevelMixTank1', '292.565856933594']
['2021-5-4 2:2:7', 'fActWaterLevelMixTank2', '287.486480712891']
['2021-5-4 2:2:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:2:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:2:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:2:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:2:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:2:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:2:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:2:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:2:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:2:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:2:7', 'DoVa_Co2', '0']
['2021-5-4 2:2:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:2:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:2:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:2:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:2:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:3:7', 'fKWhCounter', '3305.47387695313']
['2021-5-4 2:3:7', 'fActPhLevelMixTank1', '5.65831470489502']
['2021-5-4 2:3:7', 'fActEcLevelMixTank1', '2032.38012695313']
['2021-5-4 2:3:7', 'fActPhLevelMixTank2', '3.89410066604614']
['2021-5-4 2:3:7', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 2:3:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:3:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:3:7', 'fActTempValMemo', '18.5']
['2021-5-4 2:3:7', 'fActRhValMemo', '57.9000015258789']
['2021-5-4 2:3:7', 'fActCo2ValMemo', '797']
['2021-5-4 2:3:7', 'fActWaterLevelMixTank1', '292.946136474609']
['2021-5-4 2:3:7', 'fActWaterLevelMixTank2', '287.893920898438']
['2021-5-4 2:3:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:3:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:3:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:3:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:3:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:3:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:3:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:3:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:3:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:3:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:3:7', 'DoVa_Co2', '0']
['2021-5-4 2:3:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:3:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:3:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:3:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:3:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:4:7', 'fKWhCounter', '3305.57397460938']
['2021-5-4 2:4:7', 'fActPhLevelMixTank1', '5.65587329864502']
['2021-5-4 2:4:7', 'fActEcLevelMixTank1', '2035.43200683594']
['2021-5-4 2:4:7', 'fActPhLevelMixTank2', '3.88970613479614']
['2021-5-4 2:4:7', 'fActEcLevelMixTank2', '1038.69750976563']
['2021-5-4 2:4:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:4:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:4:7', 'fActTempValMemo', '18.5']
['2021-5-4 2:4:7', 'fActRhValMemo', '57.7999992370605']
['2021-5-4 2:4:7', 'fActCo2ValMemo', '798']
['2021-5-4 2:4:7', 'fActWaterLevelMixTank1', '292.321411132813']
['2021-5-4 2:4:7', 'fActWaterLevelMixTank2', '274.095458984375']
['2021-5-4 2:4:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:4:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:4:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:4:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:4:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:4:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:4:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:4:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:4:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:4:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:4:7', 'DoVa_Co2', '0']
['2021-5-4 2:4:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:4:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:4:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:4:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']

['2021-5-4 2:4:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:4:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:5:7', 'fKWhCounter', '3305.77416992188']
['2021-5-4 2:5:7', 'fActPhLevelMixTank1', '5.56675910949707']
['2021-5-4 2:5:7', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 2:5:7', 'fActPhLevelMixTank2', '3.81109046936035']
['2021-5-4 2:5:7', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 2:5:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:5:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:5:7', 'fActTempValMemo', '18.6000003814697']
['2021-5-4 2:5:7', 'fActRhValMemo', '57.9000015258789']
['2021-5-4 2:5:7', 'fActCo2ValMemo', '799']
['2021-5-4 2:5:7', 'fActWaterLevelMixTank1', '285.09619140625']
['2021-5-4 2:5:7', 'fActWaterLevelMixTank2', '271.650848388672']
['2021-5-4 2:5:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:5:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:5:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:5:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:5:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:5:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:5:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:5:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:5:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:5:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:5:7', 'DoVa_Co2', '0']
['2021-5-4 2:5:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:5:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:5:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:5:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:5:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:6:7', 'fKWhCounter', '3305.87426757813']
['2021-5-4 2:6:7', 'fActPhLevelMixTank1', '5.56773567199707']
['2021-5-4 2:6:7', 'fActEcLevelMixTank1', '2014.2216796875']
['2021-5-4 2:6:7', 'fActPhLevelMixTank2', '3.82403016090393']
['2021-5-4 2:6:7', 'fActEcLevelMixTank2', '1026.94787597656']
['2021-5-4 2:6:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:6:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:6:7', 'fActTempValMemo', '18.6000003814697']
['2021-5-4 2:6:7', 'fActRhValMemo', '58.0999984741211']
['2021-5-4 2:6:7', 'fActCo2ValMemo', '797']
['2021-5-4 2:6:7', 'fActWaterLevelMixTank1', '281.130493164063']
['2021-5-4 2:6:7', 'fActWaterLevelMixTank2', '256.249786376953']
['2021-5-4 2:6:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:6:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:6:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:6:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:6:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:6:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:6:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:6:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:6:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:6:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:6:7', 'DoVa_Co2', '0']
['2021-5-4 2:6:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:6:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:6:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:6:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:6:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:7:7', 'fKWhCounter', '3306.07446289063']
['2021-5-4 2:7:7', 'fActPhLevelMixTank1', '5.57042169570923']
['2021-5-4 2:7:7', 'fActEcLevelMixTank1', '2014.67944335938']
['2021-5-4 2:7:7', 'fActPhLevelMixTank2', '3.81939148902893']
['2021-5-4 2:7:7', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 2:7:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:7:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:7:7', 'fActTempValMemo', '18.7000007629395']
['2021-5-4 2:7:7', 'fActRhValMemo', '57.9000015258789']
['2021-5-4 2:7:7', 'fActCo2ValMemo', '798']
['2021-5-4 2:7:7', 'fActWaterLevelMixTank1', '276.051147460938']
['2021-5-4 2:7:7', 'fActWaterLevelMixTank2', '264.316986083984']
['2021-5-4 2:7:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:7:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:7:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:7:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:7:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:7:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:7:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:7:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:7:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:7:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:7:7', 'DoVa_Co2', '0']
['2021-5-4 2:7:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:7:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:7:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:7:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:7:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:8:7', 'fKWhCounter', '3306.17456054688']
['2021-5-4 2:8:7', 'fActPhLevelMixTank1', '5.57237482070923']
['2021-5-4 2:8:7', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 2:8:7', 'fActPhLevelMixTank2', '3.82671594619751']
['2021-5-4 2:8:7', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 2:8:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:8:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:8:7', 'fActTempValMemo', '18.7000007629395']
['2021-5-4 2:8:7', 'fActRhValMemo', '58']
['2021-5-4 2:8:7', 'fActCo2ValMemo', '800']
['2021-5-4 2:8:7', 'fActWaterLevelMixTank1', '274.910308837891']
['2021-5-4 2:8:7', 'fActWaterLevelMixTank2', '273.226257324219']
['2021-5-4 2:8:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:8:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:8:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:8:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:8:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:8:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:8:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:8:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:8:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:8:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:8:7', 'DoVa_Co2', '0']
['2021-5-4 2:8:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:8:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:8:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:8:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:8:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:9:7', 'fKWhCounter', '3306.37475585938']
['2021-5-4 2:9:7', 'fActPhLevelMixTank1', '5.56773567199707']
['2021-5-4 2:9:7', 'fActEcLevelMixTank1', '2014.52685546875']
['2021-5-4 2:9:7', 'fActPhLevelMixTank2', '3.83111047744751']
['2021-5-4 2:9:7', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 2:9:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:9:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:9:7', 'fActTempValMemo', '18.7999992370605']
['2021-5-4 2:9:7', 'fActRhValMemo', '57.7999992370605']
['2021-5-4 2:9:7', 'fActCo2ValMemo', '796']
['2021-5-4 2:9:7', 'fActWaterLevelMixTank1', '277.680877685547']
['2021-5-4 2:9:7', 'fActWaterLevelMixTank2', '256.711547851563']
['2021-5-4 2:9:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:9:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:9:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:9:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:9:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:9:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:9:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:9:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:9:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:9:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:9:7', 'DoVa_Co2', '0']
['2021-5-4 2:9:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:9:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:9:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:9:7', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:9:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:10:7', 'fKWhCounter', '3306.47485351563']
['2021-5-4 2:10:7', 'fActPhLevelMixTank1', '5.57701349258423']
['2021-5-4 2:10:7', 'fActEcLevelMixTank1', '2017.8837890625']
['2021-5-4 2:10:7', 'fActPhLevelMixTank2', '3.86602377891541']
['2021-5-4 2:10:7', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 2:10:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:10:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:10:7', 'fActTempValMemo', '18.7999992370605']
['2021-5-4 2:10:7', 'fActRhValMemo', '57.4000015258789']
['2021-5-4 2:10:7', 'fActCo2ValMemo', '793']
['2021-5-4 2:10:7', 'fActWaterLevelMixTank1', '275.779510498047']
['2021-5-4 2:10:7', 'fActWaterLevelMixTank2', '276.920318603516']
['2021-5-4 2:10:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:10:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:10:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:10:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:10:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:10:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:10:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:10:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:10:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:10:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:10:7', 'DoVa_Co2', '0']
['2021-5-4 2:10:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:10:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:10:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:10:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:10:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:11:7', 'fKWhCounter', '3306.67504882813']
['2021-5-4 2:11:7', 'fActPhLevelMixTank1', '5.57628107070923']
['2021-5-4 2:11:7', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 2:11:7', 'fActPhLevelMixTank2', '3.86968588829041']
['2021-5-4 2:11:7', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 2:11:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:11:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:11:7', 'fActTempValMemo', '18.8999996185303']
['2021-5-4 2:11:7', 'fActRhValMemo', '57.5']
['2021-5-4 2:11:7', 'fActCo2ValMemo', '790']
['2021-5-4 2:11:7', 'fActWaterLevelMixTank1', '273.959625244141']
['2021-5-4 2:11:7', 'fActWaterLevelMixTank2', '276.730194091797']
['2021-5-4 2:11:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:11:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:11:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:11:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:11:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:11:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:11:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:11:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:11:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:11:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:11:7', 'DoVa_Co2', '0']
['2021-5-4 2:11:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:11:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:11:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:11:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:11:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:12:7', 'fKWhCounter', '3306.77514648438']
['2021-5-4 2:12:7', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 2:12:7', 'fActEcLevelMixTank1', '2016.35791015625']
['2021-5-4 2:12:7', 'fActPhLevelMixTank2', '3.86748862266541']
['2021-5-4 2:12:7', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 2:12:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:12:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:12:7', 'fActTempValMemo', '18.8999996185303']
['2021-5-4 2:12:7', 'fActRhValMemo', '57.4000015258789']
['2021-5-4 2:12:7', 'fActCo2ValMemo', '794']
['2021-5-4 2:12:7', 'fActWaterLevelMixTank1', '273.796661376953']
['2021-5-4 2:12:7', 'fActWaterLevelMixTank2', '275.969665527344']
['2021-5-4 2:12:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:12:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:12:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:12:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:12:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:12:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:12:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:12:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:12:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:12:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:12:7', 'DoVa_Co2', '0']
['2021-5-4 2:12:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:12:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:12:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:12:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:12:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:13:7', 'fKWhCounter', '3306.87524414063']
['2021-5-4 2:13:7', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 2:13:7', 'fActEcLevelMixTank1', '2015.90014648438']
['2021-5-4 2:13:7', 'fActPhLevelMixTank2', '3.85918760299683']
['2021-5-4 2:13:7', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 2:13:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:13:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:13:7', 'fActTempValMemo', '19']
['2021-5-4 2:13:7', 'fActRhValMemo', '57.0999984741211']
['2021-5-4 2:13:7', 'fActCo2ValMemo', '791']
['2021-5-4 2:13:7', 'fActWaterLevelMixTank1', '275.290588378906']
['2021-5-4 2:13:7', 'fActWaterLevelMixTank2', '276.703033447266']
['2021-5-4 2:13:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:13:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:13:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:13:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:13:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:13:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:13:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:13:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:13:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:13:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:13:7', 'DoVa_Co2', '0']
['2021-5-4 2:13:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:13:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:13:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:13:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:13:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:14:7', 'fKWhCounter', '3306.97534179688']
['2021-5-4 2:14:7', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 2:14:7', 'fActEcLevelMixTank1', '2011.93273925781']
['2021-5-4 2:14:7', 'fActPhLevelMixTank2', '3.86236143112183']
['2021-5-4 2:14:7', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 2:14:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:14:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:14:7', 'fActTempValMemo', '19']
['2021-5-4 2:14:7', 'fActRhValMemo', '57']

['2021-5-4 2:14:7', 'fActCo2ValMemo', '789']
['2021-5-4 2:14:7', 'fActWaterLevelMixTank1', '276.159790039063']
['2021-5-4 2:14:7', 'fActWaterLevelMixTank2', '276.32275390625']
['2021-5-4 2:14:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:14:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:14:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:14:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:14:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:14:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:14:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:14:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:14:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:14:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:14:7', 'DoVa_Co2', '0']
['2021-5-4 2:14:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:14:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:14:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:14:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:14:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:15:7', 'fKWhCounter', '3307.17553710938']
['2021-5-4 2:15:7', 'fActPhLevelMixTank1', '5.57652521133423']
['2021-5-4 2:15:7', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 2:15:7', 'fActPhLevelMixTank2', '3.85894346237183']
['2021-5-4 2:15:7', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 2:15:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:15:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:15:7', 'fActTempValMemo', '19']
['2021-5-4 2:15:7', 'fActRhValMemo', '56.9000015258789']
['2021-5-4 2:15:7', 'fActCo2ValMemo', '788']
['2021-5-4 2:15:7', 'fActWaterLevelMixTank1', '277.028991699219']
['2021-5-4 2:15:7', 'fActWaterLevelMixTank2', '276.811676025391']
['2021-5-4 2:15:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:15:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:15:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:15:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:15:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:15:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:15:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:15:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:15:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:15:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:15:7', 'DoVa_Co2', '0']
['2021-5-4 2:15:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:15:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:15:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:15:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:15:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:16:7', 'fKWhCounter', '3307.27563476563']
['2021-5-4 2:16:7', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 2:16:7', 'fActEcLevelMixTank1', '2014.2216796875']
['2021-5-4 2:16:7', 'fActPhLevelMixTank2', '3.85747861862183']
['2021-5-4 2:16:7', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 2:16:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:16:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:16:7', 'fActTempValMemo', '19.1000003814697']
['2021-5-4 2:16:7', 'fActRhValMemo', '56.7999992370605']
['2021-5-4 2:16:7', 'fActCo2ValMemo', '788']
['2021-5-4 2:16:7', 'fActWaterLevelMixTank1', '277.463592529297']
['2021-5-4 2:16:7', 'fActWaterLevelMixTank2', '277.545074462891']
['2021-5-4 2:16:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:16:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:16:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:16:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:16:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:16:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:16:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:16:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:16:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:16:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:16:7', 'DoVa_Co2', '0']
['2021-5-4 2:16:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:16:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:16:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:16:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:16:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:17:7', 'fKWhCounter', '3307.37573242188']
['2021-5-4 2:17:7', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 2:17:7', 'fActEcLevelMixTank1', '2013.00085449219']
['2021-5-4 2:17:7', 'fActPhLevelMixTank2', '3.85992002487183']
['2021-5-4 2:17:7', 'fActEcLevelMixTank2', '1025.72705078125']
['2021-5-4 2:17:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:17:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:17:7', 'fActTempValMemo', '19.1000003814697']
['2021-5-4 2:17:7', 'fActRhValMemo', '56.9000015258789']
['2021-5-4 2:17:7', 'fActCo2ValMemo', '789']
['2021-5-4 2:17:7', 'fActWaterLevelMixTank1', '277.762359619141']
['2021-5-4 2:17:7', 'fActWaterLevelMixTank2', '277.843841552734']
['2021-5-4 2:17:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:17:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:17:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:17:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:17:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:17:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:17:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:17:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:17:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:17:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:17:7', 'DoVa_Co2', '0']
['2021-5-4 2:17:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:17:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:17:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:17:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:17:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:18:7', 'fKWhCounter', '3307.47583007813']
['2021-5-4 2:18:7', 'fActPhLevelMixTank1', '5.58311700820923']
['2021-5-4 2:18:7', 'fActEcLevelMixTank1', '2011.93273925781']
['2021-5-4 2:18:7', 'fActPhLevelMixTank2', '3.85723447799683']
['2021-5-4 2:18:7', 'fActEcLevelMixTank2', '1026.33752441406']
['2021-5-4 2:18:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:18:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:18:7', 'fActTempValMemo', '19.2000007629395']
['2021-5-4 2:18:7', 'fActRhValMemo', '56.7999992370605']
['2021-5-4 2:18:7', 'fActCo2ValMemo', '785']
['2021-5-4 2:18:7', 'fActWaterLevelMixTank1', '276.214111328125']
['2021-5-4 2:18:7', 'fActWaterLevelMixTank2', '277.572235107422']
['2021-5-4 2:18:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:18:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:18:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:18:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:18:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:18:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:18:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:18:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:18:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:18:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:18:7', 'DoVa_Co2', '0']
['2021-5-4 2:18:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:18:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:18:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:18:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_4_Red', '0']

['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:18:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:19:7', 'fKWhCounter', '3307.67602539063']
['2021-5-4 2:19:7', 'fActPhLevelMixTank1', '5.58409357070923']
['2021-5-4 2:19:7', 'fActEcLevelMixTank1', '2009.18603515625']
['2021-5-4 2:19:7', 'fActPhLevelMixTank2', '3.86089658737183']
['2021-5-4 2:19:7', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 2:19:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:19:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:19:7', 'fActTempValMemo', '19.2000007629395']
['2021-5-4 2:19:7', 'fActRhValMemo', '56.7999992370605']
['2021-5-4 2:19:7', 'fActCo2ValMemo', '787']
['2021-5-4 2:19:7', 'fActWaterLevelMixTank1', '278.251281738281']
['2021-5-4 2:19:7', 'fActWaterLevelMixTank2', '277.409271240234']
['2021-5-4 2:19:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:19:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:19:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:19:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:19:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:19:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:19:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:19:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:19:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:19:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:19:7', 'DoVa_Co2', '0']
['2021-5-4 2:19:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:19:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:19:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:19:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:19:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:20:7', 'fKWhCounter', '3307.77612304688']
['2021-5-4 2:20:7', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 2:20:7', 'fActEcLevelMixTank1', '2010.10168457031']
['2021-5-4 2:20:7', 'fActPhLevelMixTank2', '3.85674619674683']
['2021-5-4 2:20:7', 'fActEcLevelMixTank2', '1024.04858398438']
['2021-5-4 2:20:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:20:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:20:7', 'fActTempValMemo', '19.2000007629395']
['2021-5-4 2:20:7', 'fActRhValMemo', '56.5999984741211']
['2021-5-4 2:20:7', 'fActCo2ValMemo', '788']
['2021-5-4 2:20:7', 'fActWaterLevelMixTank1', '278.876037597656']
['2021-5-4 2:20:7', 'fActWaterLevelMixTank2', '277.979675292969']
['2021-5-4 2:20:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:20:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:20:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:20:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:20:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:20:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:20:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:20:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:20:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:20:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:20:7', 'DoVa_Co2', '0']
['2021-5-4 2:20:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:20:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:20:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:20:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:20:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:21:7', 'fKWhCounter', '3307.87622070313']
['2021-5-4 2:21:7', 'fActPhLevelMixTank1', '5.57945489883423']
['2021-5-4 2:21:7', 'fActEcLevelMixTank1', '2015.28979492188']
['2021-5-4 2:21:7', 'fActPhLevelMixTank2', '3.85332798957825']
['2021-5-4 2:21:7', 'fActEcLevelMixTank2', '1025.57446289063']
['2021-5-4 2:21:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:21:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:21:7', 'fActTempValMemo', '19.2999992370605']
['2021-5-4 2:21:7', 'fActRhValMemo', '56.5999984741211']
['2021-5-4 2:21:7', 'fActCo2ValMemo', '788']
['2021-5-4 2:21:7', 'fActWaterLevelMixTank1', '278.95751953125']
['2021-5-4 2:21:7', 'fActWaterLevelMixTank2', '277.871002197266']
['2021-5-4 2:21:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:21:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:21:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:21:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:21:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:21:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:21:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:21:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:21:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:21:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:21:7', 'DoVa_Co2', '0']
['2021-5-4 2:21:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:21:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:21:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:21:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:21:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:22:7', 'fKWhCounter', '3308.07641601563']
['2021-5-4 2:22:7', 'fActPhLevelMixTank1', '5.58580255508423']
['2021-5-4 2:22:7', 'fActEcLevelMixTank1', '2012.54309082031']
['2021-5-4 2:22:7', 'fActPhLevelMixTank2', '3.86114072799683']
['2021-5-4 2:22:7', 'fActEcLevelMixTank2', '1026.03234863281']
['2021-5-4 2:22:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:22:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:22:7', 'fActTempValMemo', '19.2999992370605']
['2021-5-4 2:22:7', 'fActRhValMemo', '56.4000015258789']
['2021-5-4 2:22:7', 'fActCo2ValMemo', '791']
['2021-5-4 2:22:7', 'fActWaterLevelMixTank1', '278.251281738281']
['2021-5-4 2:22:7', 'fActWaterLevelMixTank2', '278.685882568359']
['2021-5-4 2:22:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:22:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:22:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:22:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:22:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:22:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:22:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:22:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:22:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:22:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:22:7', 'DoVa_Co2', '0']
['2021-5-4 2:22:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:22:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:22:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:22:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:22:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:23:7', 'fKWhCounter', '3308.17651367188']
['2021-5-4 2:23:7', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 2:23:7', 'fActEcLevelMixTank1', '2012.54309082031']
['2021-5-4 2:23:7', 'fActPhLevelMixTank2', '3.86016416549683']
['2021-5-4 2:23:7', 'fActEcLevelMixTank2', '1025.421875']
['2021-5-4 2:23:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:23:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:23:7', 'fActTempValMemo', '19.3999996185303']
['2021-5-4 2:23:7', 'fActRhValMemo', '56.2000007629395']
['2021-5-4 2:23:7', 'fActCo2ValMemo', '790']
['2021-5-4 2:23:7', 'fActWaterLevelMixTank1', '279.908203125']
['2021-5-4 2:23:7', 'fActWaterLevelMixTank2', '279.256286621094']
['2021-5-4 2:23:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:23:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:23:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:23:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:23:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:23:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:23:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:23:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:23:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:23:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:23:7', 'DoVa_Co2', '0']
['2021-5-4 2:23:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:23:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:23:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:23:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:23:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:24:8', 'fKWhCounter', '3308.27661132813']
['2021-5-4 2:24:8', 'fActPhLevelMixTank1', '5.57896661758423']
['2021-5-4 2:24:8', 'fActEcLevelMixTank1', '2012.54309082031']
['2021-5-4 2:24:8', 'fActPhLevelMixTank2', '3.86309385299683']
['2021-5-4 2:24:8', 'fActEcLevelMixTank2', '1025.72705078125']
['2021-5-4 2:24:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:24:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:24:8', 'fActTempValMemo', '19.3999996185303']
['2021-5-4 2:24:8', 'fActRhValMemo', '56.4000015258789']
['2021-5-4 2:24:8', 'fActCo2ValMemo', '790']
['2021-5-4 2:24:8', 'fActWaterLevelMixTank1', '280.587249755859']

['2021-5-4 2:24:8', 'fActWaterLevelMixTank2', '279.066162109375']
['2021-5-4 2:24:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:24:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:24:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:24:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:24:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:24:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:24:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:24:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:24:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:24:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:24:8', 'DoVa_Co2', '0']
['2021-5-4 2:24:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:24:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:24:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:24:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:24:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:25:7', 'fKWhCounter', '3308.37670898438']
['2021-5-4 2:25:7', 'fActPhLevelMixTank1', '5.59141826629639']
['2021-5-4 2:25:7', 'fActEcLevelMixTank1', '2012.54309082031']
['2021-5-4 2:25:7', 'fActPhLevelMixTank2', '3.86284971237183']
['2021-5-4 2:25:7', 'fActEcLevelMixTank2', '1025.72705078125']
['2021-5-4 2:25:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:25:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:25:7', 'fActTempValMemo', '19.5']
['2021-5-4 2:25:7', 'fActRhValMemo', '56.2999992370605']
['2021-5-4 2:25:7', 'fActCo2ValMemo', '786']
['2021-5-4 2:25:7', 'fActWaterLevelMixTank1', '280.994689941406']
['2021-5-4 2:25:7', 'fActWaterLevelMixTank2', '279.201965332031']
['2021-5-4 2:25:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:25:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:25:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:25:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:25:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:25:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:25:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:25:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:25:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:25:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:25:7', 'DoVa_Co2', '0']
['2021-5-4 2:25:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:25:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:25:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:25:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:25:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:26:7', 'fKWhCounter', '3308.57690429688']
['2021-5-4 2:26:7', 'fActPhLevelMixTank1', '5.59752178192139']
['2021-5-4 2:26:7', 'fActEcLevelMixTank1', '2007.96533203125']
['2021-5-4 2:26:7', 'fActPhLevelMixTank2', '3.86309385299683']
['2021-5-4 2:26:7', 'fActEcLevelMixTank2', '1024.04858398438']
['2021-5-4 2:26:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:26:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:26:7', 'fActTempValMemo', '19.5']
['2021-5-4 2:26:7', 'fActRhValMemo', '56.5']
['2021-5-4 2:26:7', 'fActCo2ValMemo', '786']
['2021-5-4 2:26:7', 'fActWaterLevelMixTank1', '280.614410400391']
['2021-5-4 2:26:7', 'fActWaterLevelMixTank2', '279.473602294922']
['2021-5-4 2:26:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:26:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:26:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:26:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:26:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:26:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:26:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:26:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:26:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:26:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:26:7', 'DoVa_Co2', '0']
['2021-5-4 2:26:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:26:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:26:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:26:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:26:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:27:7', 'fKWhCounter', '3308.67700195313']
['2021-5-4 2:27:7', 'fActPhLevelMixTank1', '5.59825420379639']
['2021-5-4 2:27:7', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 2:27:7', 'fActPhLevelMixTank2', '3.86407065391541']
['2021-5-4 2:27:7', 'fActEcLevelMixTank2', '1026.03234863281']
['2021-5-4 2:27:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:27:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:27:7', 'fActTempValMemo', '19.5']
['2021-5-4 2:27:7', 'fActRhValMemo', '56.7000007629395']
['2021-5-4 2:27:7', 'fActCo2ValMemo', '784']
['2021-5-4 2:27:7', 'fActWaterLevelMixTank1', '281.537933349609']
['2021-5-4 2:27:7', 'fActWaterLevelMixTank2', '280.424285888672']
['2021-5-4 2:27:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:27:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:27:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:27:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:27:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:27:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:27:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:27:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:27:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:27:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:27:7', 'DoVa_Co2', '0']
['2021-5-4 2:27:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:27:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:27:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:27:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:27:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:28:7', 'fKWhCounter', '3308.77709960938']
['2021-5-4 2:28:7', 'fActPhLevelMixTank1', '5.59825420379639']
['2021-5-4 2:28:7', 'fActEcLevelMixTank1', '2016.35791015625']
['2021-5-4 2:28:7', 'fActPhLevelMixTank2', '3.86138486862183']
['2021-5-4 2:28:7', 'fActEcLevelMixTank2', '1025.421875']
['2021-5-4 2:28:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:28:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:28:7', 'fActTempValMemo', '19.5']
['2021-5-4 2:28:7', 'fActRhValMemo', '56.5999984741211']
['2021-5-4 2:28:7', 'fActCo2ValMemo', '782']
['2021-5-4 2:28:7', 'fActWaterLevelMixTank1', '281.619415283203']
['2021-5-4 2:28:7', 'fActWaterLevelMixTank2', '279.853881835938']
['2021-5-4 2:28:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:28:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:28:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:28:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:28:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:28:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:28:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:28:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:28:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:28:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:28:7', 'DoVa_Co2', '0']
['2021-5-4 2:28:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:28:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:28:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:28:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:28:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:29:7', 'fKWhCounter', '3308.87719726563']
['2021-5-4 2:29:7', 'fActPhLevelMixTank1', '5.60411405563354']
['2021-5-4 2:29:7', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 2:29:7', 'fActPhLevelMixTank2', '3.86870932579041']
['2021-5-4 2:29:7', 'fActEcLevelMixTank2', '1027.40563964844']
['2021-5-4 2:29:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:29:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:29:7', 'fActTempValMemo', '19.5']
['2021-5-4 2:29:7', 'fActRhValMemo', '56.5999984741211']
['2021-5-4 2:29:7', 'fActCo2ValMemo', '783']
['2021-5-4 2:29:7', 'fActWaterLevelMixTank1', '281.320648193359']
['2021-5-4 2:29:7', 'fActWaterLevelMixTank2', '280.505767822266']

['2021-5-4 2:29:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:29:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:29:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:29:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:29:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:29:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:29:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:29:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:29:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:29:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:29:7', 'DoVa_Co2', '0']
['2021-5-4 2:29:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:29:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:29:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:29:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:29:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:30:7', 'fKWhCounter', '3309.07739257813']
['2021-5-4 2:30:7', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 2:30:7', 'fActEcLevelMixTank1', '2014.83203125']
['2021-5-4 2:30:7', 'fActPhLevelMixTank2', '3.87139511108398']
['2021-5-4 2:30:7', 'fActEcLevelMixTank2', '1026.64270019531']
['2021-5-4 2:30:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:30:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:30:7', 'fActTempValMemo', '19.5']
['2021-5-4 2:30:7', 'fActRhValMemo', '56.5999984741211']
['2021-5-4 2:30:7', 'fActCo2ValMemo', '785']
['2021-5-4 2:30:7', 'fActWaterLevelMixTank1', '282.189819335938']
['2021-5-4 2:30:7', 'fActWaterLevelMixTank2', '280.614410400391']
['2021-5-4 2:30:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:30:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:30:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:30:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:30:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:30:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:30:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:30:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:30:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:30:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:30:7', 'DoVa_Co2', '0']
['2021-5-4 2:30:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:30:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:30:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:30:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:30:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:31:7', 'fKWhCounter', '3309.17749023438']
['2021-5-4 2:31:7', 'fActPhLevelMixTank1', '5.60386991500854']
['2021-5-4 2:31:7', 'fActEcLevelMixTank1', '2013.00085449219']
['2021-5-4 2:31:7', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 2:31:7', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 2:31:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:31:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:31:7', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 2:31:7', 'fActRhValMemo', '56.4000015258789']
['2021-5-4 2:31:7', 'fActCo2ValMemo', '786']
['2021-5-4 2:31:7', 'fActWaterLevelMixTank1', '282.678741455078']
['2021-5-4 2:31:7', 'fActWaterLevelMixTank2', '281.239135742188']
['2021-5-4 2:31:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:31:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:31:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:31:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:31:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:31:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:31:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:31:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:31:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:31:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:31:7', 'DoVa_Co2', '0']
['2021-5-4 2:31:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:31:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:31:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:31:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:31:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:32:7', 'fKWhCounter', '3309.27758789063']
['2021-5-4 2:32:7', 'fActPhLevelMixTank1', '5.60924100875854']
['2021-5-4 2:32:7', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 2:32:7', 'fActPhLevelMixTank2', '3.86773276329041']
['2021-5-4 2:32:7', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 2:32:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:32:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:32:7', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 2:32:7', 'fActRhValMemo', '56.5']
['2021-5-4 2:32:7', 'fActCo2ValMemo', '787']
['2021-5-4 2:32:7', 'fActWaterLevelMixTank1', '281.945373535156']
['2021-5-4 2:32:7', 'fActWaterLevelMixTank2', '280.831726074219']
['2021-5-4 2:32:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:32:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:32:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:32:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:32:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:32:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:32:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:32:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:32:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:32:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:32:7', 'DoVa_Co2', '0']
['2021-5-4 2:32:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:32:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:32:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:32:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:32:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:33:7', 'fKWhCounter', '3309.47778320313']
['2021-5-4 2:33:7', 'fActPhLevelMixTank1', '5.60899686813354']
['2021-5-4 2:33:7', 'fActEcLevelMixTank1', '2013.45861816406']
['2021-5-4 2:33:7', 'fActPhLevelMixTank2', '3.86773276329041']
['2021-5-4 2:33:7', 'fActEcLevelMixTank2', '1027.40563964844']
['2021-5-4 2:33:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:33:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:33:7', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 2:33:7', 'fActRhValMemo', '56.4000015258789']
['2021-5-4 2:33:7', 'fActCo2ValMemo', '787']
['2021-5-4 2:33:7', 'fActWaterLevelMixTank1', '282.733093261719']
['2021-5-4 2:33:7', 'fActWaterLevelMixTank2', '280.831726074219']
['2021-5-4 2:33:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:33:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:33:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:33:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:33:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:33:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:33:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:33:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:33:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:33:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:33:7', 'DoVa_Co2', '0']
['2021-5-4 2:33:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:33:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:33:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:33:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:33:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:34:7', 'fKWhCounter', '3309.57788085938']
['2021-5-4 2:34:7', 'fActPhLevelMixTank1', '5.6194953918457']
['2021-5-4 2:34:7', 'fActEcLevelMixTank1', '2015.4423828125']
['2021-5-4 2:34:7', 'fActPhLevelMixTank2', '3.87334823608398']
['2021-5-4 2:34:7', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 2:34:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:34:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:34:7', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 2:34:7', 'fActRhValMemo', '56.0999984741211']
['2021-5-4 2:34:7', 'fActCo2ValMemo', '786']
['2021-5-4 2:34:7', 'fActWaterLevelMixTank1', '282.271331787109']
['2021-5-4 2:34:7', 'fActWaterLevelMixTank2', '281.320648193359']
['2021-5-4 2:34:7', 'DoPu_AddAcidMixTank_1', '0']

['2021-5-4 2:34:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:34:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:34:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:34:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:34:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:34:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:34:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:34:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:34:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:34:7', 'DoVa_Co2', '0']
['2021-5-4 2:34:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:34:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:34:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:34:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:34:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:35:7', 'fKWhCounter', '3309.67797851563']
['2021-5-4 2:35:7', 'fActPhLevelMixTank1', '5.6231575012207']
['2021-5-4 2:35:7', 'fActEcLevelMixTank1', '2013.91638183594']
['2021-5-4 2:35:7', 'fActPhLevelMixTank2', '3.87261581420898']
['2021-5-4 2:35:7', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 2:35:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:35:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:35:7', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 2:35:7', 'fActRhValMemo', '56.2000007629395']
['2021-5-4 2:35:7', 'fActCo2ValMemo', '788']
['2021-5-4 2:35:7', 'fActWaterLevelMixTank1', '283.602264404297']
['2021-5-4 2:35:7', 'fActWaterLevelMixTank2', '282.189819335938']
['2021-5-4 2:35:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:35:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:35:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:35:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:35:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:35:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:35:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:35:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:35:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:35:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:35:7', 'DoVa_Co2', '0']
['2021-5-4 2:35:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:35:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:35:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:35:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:35:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:36:8', 'fKWhCounter', '3309.77807617188']
['2021-5-4 2:36:8', 'fActPhLevelMixTank1', '5.6197395324707']
['2021-5-4 2:36:8', 'fActEcLevelMixTank1', '2011.16979980469']
['2021-5-4 2:36:8', 'fActPhLevelMixTank2', '3.87334823608398']
['2021-5-4 2:36:8', 'fActEcLevelMixTank2', '1024.35375976563']
['2021-5-4 2:36:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:36:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:36:8', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 2:36:8', 'fActRhValMemo', '56.2000007629395']
['2021-5-4 2:36:8', 'fActCo2ValMemo', '788']
['2021-5-4 2:36:8', 'fActWaterLevelMixTank1', '283.819580078125']
['2021-5-4 2:36:8', 'fActWaterLevelMixTank2', '281.537933349609']
['2021-5-4 2:36:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:36:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:36:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:36:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:36:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:36:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:36:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:36:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:36:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:36:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:36:8', 'DoVa_Co2', '0']
['2021-5-4 2:36:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:36:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:36:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:36:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:36:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:37:7', 'fKWhCounter', '3309.97827148438']
['2021-5-4 2:37:7', 'fActPhLevelMixTank1', '5.6212043762207']
['2021-5-4 2:37:7', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 2:37:7', 'fActPhLevelMixTank2', '3.87627792358398']
['2021-5-4 2:37:7', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 2:37:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:37:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:37:7', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 2:37:7', 'fActRhValMemo', '56']
['2021-5-4 2:37:7', 'fActCo2ValMemo', '787']
['2021-5-4 2:37:7', 'fActWaterLevelMixTank1', '284.389984130859']
['2021-5-4 2:37:7', 'fActWaterLevelMixTank2', '282.108337402344']
['2021-5-4 2:37:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:37:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:37:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:37:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:37:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:37:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:37:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:37:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:37:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:37:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:37:7', 'DoVa_Co2', '0']
['2021-5-4 2:37:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:37:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:37:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:37:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:37:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:38:8', 'fKWhCounter', '3310.07836914063']
['2021-5-4 2:38:8', 'fActPhLevelMixTank1', '5.6255989074707']
['2021-5-4 2:38:8', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 2:38:8', 'fActPhLevelMixTank2', '3.87481307983398']
['2021-5-4 2:38:8', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 2:38:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:38:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:38:8', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 2:38:8', 'fActRhValMemo', '56.0999984741211']
['2021-5-4 2:38:8', 'fActCo2ValMemo', '782']
['2021-5-4 2:38:8', 'fActWaterLevelMixTank1', '284.227020263672']
['2021-5-4 2:38:8', 'fActWaterLevelMixTank2', '282.488616943359']
['2021-5-4 2:38:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:38:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:38:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:38:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:38:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:38:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:38:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:38:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:38:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:38:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:38:8', 'DoVa_Co2', '0']
['2021-5-4 2:38:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:38:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:38:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:38:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:38:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']

['2021-5-4 2:38:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:39:8', 'fKWhCounter', '3310.17846679688']
['2021-5-4 2:39:8', 'fActPhLevelMixTank1', '5.6236457824707']
['2021-5-4 2:39:8', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 2:39:8', 'fActPhLevelMixTank2', '3.87920784950256']
['2021-5-4 2:39:8', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 2:39:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:39:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:39:8', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 2:39:8', 'fActRhValMemo', '55.7999992370605']
['2021-5-4 2:39:8', 'fActCo2ValMemo', '779']
['2021-5-4 2:39:8', 'fActWaterLevelMixTank1', '285.014709472656']
['2021-5-4 2:39:8', 'fActWaterLevelMixTank2', '282.705932617188']
['2021-5-4 2:39:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:39:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:39:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:39:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:39:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:39:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:39:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:39:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:39:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:39:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:39:8', 'DoVa_Co2', '0']
['2021-5-4 2:39:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:39:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:39:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:39:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:39:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:40:8', 'fKWhCounter', '3310.37866210938']
['2021-5-4 2:40:8', 'fActPhLevelMixTank1', '5.6321907043457']
['2021-5-4 2:40:8', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 2:40:8', 'fActPhLevelMixTank2', '3.87554550170898']
['2021-5-4 2:40:8', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 2:40:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:40:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:40:8', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 2:40:8', 'fActRhValMemo', '54.4000015258789']
['2021-5-4 2:40:8', 'fActCo2ValMemo', '777']
['2021-5-4 2:40:8', 'fActWaterLevelMixTank1', '285.177703857422']
['2021-5-4 2:40:8', 'fActWaterLevelMixTank2', '282.896057128906']
['2021-5-4 2:40:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:40:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:40:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:40:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:40:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:40:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:40:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:40:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:40:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:40:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:40:8', 'DoVa_Co2', '0']
['2021-5-4 2:40:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:40:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:40:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:40:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:40:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:41:7', 'fKWhCounter', '3310.47875976563']
['2021-5-4 2:41:7', 'fActPhLevelMixTank1', '5.6321907043457']
['2021-5-4 2:41:7', 'fActEcLevelMixTank1', '2017.2734375']
['2021-5-4 2:41:7', 'fActPhLevelMixTank2', '3.87920784950256']
['2021-5-4 2:41:7', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 2:41:7', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:41:7', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:41:7', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 2:41:7', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 2:41:7', 'fActCo2ValMemo', '775']
['2021-5-4 2:41:7', 'fActWaterLevelMixTank1', '284.851745605469']
['2021-5-4 2:41:7', 'fActWaterLevelMixTank2', '283.330657958984']
['2021-5-4 2:41:7', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:41:7', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:41:7', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:41:7', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:41:7', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:41:7', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:41:7', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:41:7', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:41:7', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:41:7', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:41:7', 'DoVa_Co2', '0']
['2021-5-4 2:41:7', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:41:7', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:41:7', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:41:7', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:41:7', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:42:8', 'fKWhCounter', '3310.67895507813']
['2021-5-4 2:42:8', 'fActPhLevelMixTank1', '5.63463258743286']
['2021-5-4 2:42:8', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 2:42:8', 'fActPhLevelMixTank2', '3.87530136108398']
['2021-5-4 2:42:8', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 2:42:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:42:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:42:8', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 2:42:8', 'fActRhValMemo', '52']
['2021-5-4 2:42:8', 'fActCo2ValMemo', '776']
['2021-5-4 2:42:8', 'fActWaterLevelMixTank1', '285.6123046875']
['2021-5-4 2:42:8', 'fActWaterLevelMixTank2', '283.031860351563']
['2021-5-4 2:42:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:42:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:42:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:42:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:42:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:42:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:42:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:42:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:42:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:42:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:42:8', 'DoVa_Co2', '0']
['2021-5-4 2:42:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:42:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:42:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:42:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:42:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:43:8', 'fKWhCounter', '3310.77905273438']
['2021-5-4 2:43:8', 'fActPhLevelMixTank1', '5.6326789855957']
['2021-5-4 2:43:8', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 2:43:8', 'fActPhLevelMixTank2', '3.87383651733398']
['2021-5-4 2:43:8', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 2:43:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:43:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:43:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 2:43:8', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 2:43:8', 'fActCo2ValMemo', '777']
['2021-5-4 2:43:8', 'fActWaterLevelMixTank1', '285.938232421875']
['2021-5-4 2:43:8', 'fActWaterLevelMixTank2', '283.167663574219']
['2021-5-4 2:43:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:43:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:43:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:43:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:43:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:43:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:43:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:43:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:43:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:43:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:43:8', 'DoVa_Co2', '0']
['2021-5-4 2:43:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:43:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:43:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:43:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_4_Fred', '0']

['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:43:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:44:8', 'fKWhCounter', '3310.97924804688']
['2021-5-4 2:44:8', 'fActPhLevelMixTank1', '5.63707399368286']
['2021-5-4 2:44:8', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 2:44:8', 'fActPhLevelMixTank2', '3.87652206420898']
['2021-5-4 2:44:8', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 2:44:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:44:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:44:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 2:44:8', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 2:44:8', 'fActCo2ValMemo', '777']
['2021-5-4 2:44:8', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 2:44:8', 'fActWaterLevelMixTank2', '283.683776855469']
['2021-5-4 2:44:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:44:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:44:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:44:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:44:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:44:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:44:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:44:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:44:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:44:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:44:8', 'DoVa_Co2', '0']
['2021-5-4 2:44:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:44:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:44:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:44:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:44:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:45:8', 'fKWhCounter', '3311.07934570313']
['2021-5-4 2:45:8', 'fActPhLevelMixTank1', '5.63463258743286']
['2021-5-4 2:45:8', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 2:45:8', 'fActPhLevelMixTank2', '3.88042855262756']
['2021-5-4 2:45:8', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 2:45:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:45:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:45:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 2:45:8', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 2:45:8', 'fActCo2ValMemo', '780']
['2021-5-4 2:45:8', 'fActWaterLevelMixTank1', '286.155548095703']
['2021-5-4 2:45:8', 'fActWaterLevelMixTank2', '283.167663574219']
['2021-5-4 2:45:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:45:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:45:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:45:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:45:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:45:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:45:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:45:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:45:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:45:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:45:8', 'DoVa_Co2', '0']
['2021-5-4 2:45:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:45:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:45:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:45:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:45:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:46:8', 'fKWhCounter', '3311.27954101563']
['2021-5-4 2:46:8', 'fActPhLevelMixTank1', '5.63951539993286']
['2021-5-4 2:46:8', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 2:46:8', 'fActPhLevelMixTank2', '3.87261581420898']
['2021-5-4 2:46:8', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 2:46:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:46:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:46:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 2:46:8', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 2:46:8', 'fActCo2ValMemo', '779']
['2021-5-4 2:46:8', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 2:46:8', 'fActWaterLevelMixTank2', '283.357818603516']
['2021-5-4 2:46:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:46:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:46:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:46:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:46:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:46:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:46:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:46:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:46:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:46:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:46:8', 'DoVa_Co2', '0']
['2021-5-4 2:46:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:46:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:46:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:46:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:46:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:47:8', 'fKWhCounter', '3311.37963867188']
['2021-5-4 2:47:8', 'fActPhLevelMixTank1', '5.64293336868286']
['2021-5-4 2:47:8', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 2:47:8', 'fActPhLevelMixTank2', '3.87554550170898']
['2021-5-4 2:47:8', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 2:47:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:47:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:47:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:47:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 2:47:8', 'fActCo2ValMemo', '775']
['2021-5-4 2:47:8', 'fActWaterLevelMixTank1', '285.503631591797']
['2021-5-4 2:47:8', 'fActWaterLevelMixTank2', '283.955383300781']
['2021-5-4 2:47:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:47:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:47:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:47:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:47:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:47:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:47:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:47:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:47:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:47:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:47:8', 'DoVa_Co2', '0']
['2021-5-4 2:47:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:47:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:47:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:47:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:47:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:48:8', 'fKWhCounter', '3311.47973632813']
['2021-5-4 2:48:8', 'fActPhLevelMixTank1', '5.63878297805786']
['2021-5-4 2:48:8', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 2:48:8', 'fActPhLevelMixTank2', '3.88091683387756']
['2021-5-4 2:48:8', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 2:48:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:48:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:48:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:48:8', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 2:48:8', 'fActCo2ValMemo', '774']
['2021-5-4 2:48:8', 'fActWaterLevelMixTank1', '286.888916015625']
['2021-5-4 2:48:8', 'fActWaterLevelMixTank2', '283.901062011719']
['2021-5-4 2:48:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:48:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:48:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:48:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:48:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:48:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:48:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:48:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:48:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:48:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:48:8', 'DoVa_Co2', '0']
['2021-5-4 2:48:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:48:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:48:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:48:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:48:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:49:8', 'fKWhCounter', '3311.67993164063']
['2021-5-4 2:49:8', 'fActPhLevelMixTank1', '5.64903736114502']
['2021-5-4 2:49:8', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 2:49:8', 'fActPhLevelMixTank2', '3.87749862670898']
['2021-5-4 2:49:8', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 2:49:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:49:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:49:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:49:8', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 2:49:8', 'fActCo2ValMemo', '775']

['2021-5-4 2:49:8', 'fActWaterLevelMixTank1', '286.101226806641']
['2021-5-4 2:49:8', 'fActWaterLevelMixTank2', '284.851745605469']
['2021-5-4 2:49:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:49:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:49:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:49:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:49:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:49:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:49:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:49:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:49:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:49:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:49:8', 'DoVa_Co2', '0']
['2021-5-4 2:49:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:49:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:49:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:49:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:49:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:50:8', 'fKWhCounter', '3311.78002929688']
['2021-5-4 2:50:8', 'fActPhLevelMixTank1', '5.65050220489502']
['2021-5-4 2:50:8', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 2:50:8', 'fActPhLevelMixTank2', '3.87896370887756']
['2021-5-4 2:50:8', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 2:50:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:50:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:50:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:50:8', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 2:50:8', 'fActCo2ValMemo', '774']
['2021-5-4 2:50:8', 'fActWaterLevelMixTank1', '287.269195556641']
['2021-5-4 2:50:8', 'fActWaterLevelMixTank2', '284.743103027344']
['2021-5-4 2:50:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:50:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:50:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:50:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:50:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:50:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:50:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:50:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:50:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:50:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:50:8', 'DoVa_Co2', '0']
['2021-5-4 2:50:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:50:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:50:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:50:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:50:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:51:8', 'fKWhCounter', '3311.98022460938']
['2021-5-4 2:51:8', 'fActPhLevelMixTank1', '5.64561891555786']
['2021-5-4 2:51:8', 'fActEcLevelMixTank1', '2004.76086425781']
['2021-5-4 2:51:8', 'fActPhLevelMixTank2', '3.87530136108398']
['2021-5-4 2:51:8', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 2:51:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:51:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:51:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:51:8', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 2:51:8', 'fActCo2ValMemo', '773']
['2021-5-4 2:51:8', 'fActWaterLevelMixTank1', '287.785278320313']
['2021-5-4 2:51:8', 'fActWaterLevelMixTank2', '284.933227539063']
['2021-5-4 2:51:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:51:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:51:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:51:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:51:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:51:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:51:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:51:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:51:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:51:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:51:8', 'DoVa_Co2', '0']
['2021-5-4 2:51:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:51:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:51:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:51:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:51:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:52:8', 'fKWhCounter', '3312.08032226563']
['2021-5-4 2:52:8', 'fActPhLevelMixTank1', '5.64439821243286']
['2021-5-4 2:52:8', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 2:52:8', 'fActPhLevelMixTank2', '3.87359237670898']
['2021-5-4 2:52:8', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 2:52:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:52:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:52:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:52:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 2:52:8', 'fActCo2ValMemo', '774']
['2021-5-4 2:52:8', 'fActWaterLevelMixTank1', '287.9482421875']
['2021-5-4 2:52:8', 'fActWaterLevelMixTank2', '285.313507080078']
['2021-5-4 2:52:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:52:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:52:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:52:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:52:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:52:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:52:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:52:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:52:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:52:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:52:8', 'DoVa_Co2', '0']
['2021-5-4 2:52:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:52:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:52:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:52:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:52:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:53:8', 'fKWhCounter', '3312.18041992188']
['2021-5-4 2:53:8', 'fActPhLevelMixTank1', '5.65782642364502']
['2021-5-4 2:53:8', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 2:53:8', 'fActPhLevelMixTank2', '3.87652206420898']
['2021-5-4 2:53:8', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 2:53:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:53:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:53:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:53:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 2:53:8', 'fActCo2ValMemo', '771']
['2021-5-4 2:53:8', 'fActWaterLevelMixTank1', '287.73095703125']
['2021-5-4 2:53:8', 'fActWaterLevelMixTank2', '285.367828369141']
['2021-5-4 2:53:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:53:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:53:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:53:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:53:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:53:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:53:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:53:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:53:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:53:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:53:8', 'DoVa_Co2', '0']
['2021-5-4 2:53:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:53:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:53:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:53:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:53:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:54:8', 'fKWhCounter', '3312.38061523438']
['2021-5-4 2:54:8', 'fActPhLevelMixTank1', '5.65538501739502']
['2021-5-4 2:54:8', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 2:54:8', 'fActPhLevelMixTank2', '3.88506722450256']
['2021-5-4 2:54:8', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 2:54:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:54:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:54:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:54:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 2:54:8', 'fActCo2ValMemo', '769']
['2021-5-4 2:54:8', 'fActWaterLevelMixTank1', '286.7802734375']
['2021-5-4 2:54:8', 'fActWaterLevelMixTank2', '285.693786621094']
['2021-5-4 2:54:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:54:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:54:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:54:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:54:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:54:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:54:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:54:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:54:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:54:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:54:8', 'DoVa_Co2', '0']
['2021-5-4 2:54:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:54:8', 'DoVa_IrrigateLevel_4_MT1', '0']

['2021-5-4 2:54:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:54:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:54:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:55:8', 'fKWhCounter', '3312.48071289063']
['2021-5-4 2:55:8', 'fActPhLevelMixTank1', '5.65318775177002']
['2021-5-4 2:55:8', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 2:55:8', 'fActPhLevelMixTank2', '3.88409066200256']
['2021-5-4 2:55:8', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 2:55:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:55:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:55:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:55:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 2:55:8', 'fActCo2ValMemo', '774']
['2021-5-4 2:55:8', 'fActWaterLevelMixTank1', '288.572998046875']
['2021-5-4 2:55:8', 'fActWaterLevelMixTank2', '285.965393066406']
['2021-5-4 2:55:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:55:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:55:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:55:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:55:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:55:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:55:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:55:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:55:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:55:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:55:8', 'DoVa_Co2', '0']
['2021-5-4 2:55:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:55:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:55:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:55:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:55:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:56:8', 'fKWhCounter', '3312.58081054688']
['2021-5-4 2:56:8', 'fActPhLevelMixTank1', '5.66368579864502']
['2021-5-4 2:56:8', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 2:56:8', 'fActPhLevelMixTank2', '3.87945199012756']
['2021-5-4 2:56:8', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 2:56:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:56:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:56:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:56:8', 'fActRhValMemo', '52']
['2021-5-4 2:56:8', 'fActCo2ValMemo', '773']
['2021-5-4 2:56:8', 'fActWaterLevelMixTank1', '288.192718505859']
['2021-5-4 2:56:8', 'fActWaterLevelMixTank2', '285.938232421875']
['2021-5-4 2:56:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:56:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:56:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:56:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:56:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:56:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:56:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:56:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:56:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:56:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:56:8', 'DoVa_Co2', '0']
['2021-5-4 2:56:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:56:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:56:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:56:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:56:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:57:8', 'fKWhCounter', '3312.78100585938']
['2021-5-4 2:57:8', 'fActPhLevelMixTank1', '5.66661596298218']
['2021-5-4 2:57:8', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 2:57:8', 'fActPhLevelMixTank2', '3.87798690795898']
['2021-5-4 2:57:8', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 2:57:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:57:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:57:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:57:8', 'fActRhValMemo', '52']
['2021-5-4 2:57:8', 'fActCo2ValMemo', '771']
['2021-5-4 2:57:8', 'fActWaterLevelMixTank1', '287.812438964844']
['2021-5-4 2:57:8', 'fActWaterLevelMixTank2', '286.209869384766']
['2021-5-4 2:57:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:57:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:57:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:57:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:57:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:57:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:57:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:57:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:57:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:57:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:57:8', 'DoVa_Co2', '0']
['2021-5-4 2:57:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:57:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:57:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:57:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:57:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:58:8', 'fKWhCounter', '3312.88110351563']
['2021-5-4 2:58:8', 'fActPhLevelMixTank1', '5.66588354110718']
['2021-5-4 2:58:8', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 2:58:8', 'fActPhLevelMixTank2', '3.88702058792114']
['2021-5-4 2:58:8', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 2:58:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:58:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:58:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:58:8', 'fActRhValMemo', '52']
['2021-5-4 2:58:8', 'fActCo2ValMemo', '770']
['2021-5-4 2:58:8', 'fActWaterLevelMixTank1', '289.333526611328']
['2021-5-4 2:58:8', 'fActWaterLevelMixTank2', '286.644470214844']
['2021-5-4 2:58:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:58:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:58:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:58:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:58:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:58:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:58:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:58:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:58:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:58:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:58:8', 'DoVa_Co2', '0']
['2021-5-4 2:58:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:58:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:58:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:58:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:58:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 2:59:8', 'fKWhCounter', '3313.08129882813']
['2021-5-4 2:59:8', 'fActPhLevelMixTank1', '5.66246509552002']
['2021-5-4 2:59:8', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 2:59:8', 'fActPhLevelMixTank2', '3.88311409950256']
['2021-5-4 2:59:8', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 2:59:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 2:59:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 2:59:8', 'fActTempValMemo', '19.5']
['2021-5-4 2:59:8', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 2:59:8', 'fActCo2ValMemo', '768']
['2021-5-4 2:59:8', 'fActWaterLevelMixTank1', '289.143402099609']
['2021-5-4 2:59:8', 'fActWaterLevelMixTank2', '287.486480712891']
['2021-5-4 2:59:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 2:59:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 2:59:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 2:59:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 2:59:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 2:59:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 2:59:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 2:59:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 2:59:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 2:59:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 2:59:8', 'DoVa_Co2', '0']

['2021-5-4 2:59:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 2:59:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 2:59:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 2:59:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 2:59:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:0:8', 'fKWhCounter', '3313.18139648438']
['2021-5-4 3:0:8', 'fActPhLevelMixTank1', '5.66759252548218']
['2021-5-4 3:0:8', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 3:0:8', 'fActPhLevelMixTank2', '3.88702058792114']
['2021-5-4 3:0:8', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 3:0:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:0:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:0:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:0:8', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 3:0:8', 'fActCo2ValMemo', '768']
['2021-5-4 3:0:8', 'fActWaterLevelMixTank1', '288.953277587891']
['2021-5-4 3:0:8', 'fActWaterLevelMixTank2', '286.99755859375']
['2021-5-4 3:0:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:0:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:0:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:0:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:0:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:0:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:0:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:0:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:0:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:0:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:0:8', 'DoVa_Co2', '0']
['2021-5-4 3:0:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:0:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:0:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:0:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:0:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:1:8', 'fKWhCounter', '3313.28149414063']
['2021-5-4 3:1:8', 'fActPhLevelMixTank1', '5.67809057235718']
['2021-5-4 3:1:8', 'fActEcLevelMixTank1', '2028.56530761719']
['2021-5-4 3:1:8', 'fActPhLevelMixTank2', '3.88677644729614']
['2021-5-4 3:1:8', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 3:1:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:1:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:1:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:1:8', 'fActRhValMemo', '52.5']
['2021-5-4 3:1:8', 'fActCo2ValMemo', '764']
['2021-5-4 3:1:8', 'fActWaterLevelMixTank1', '289.605163574219']
['2021-5-4 3:1:8', 'fActWaterLevelMixTank2', '286.807434082031']
['2021-5-4 3:1:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:1:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:1:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:1:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:1:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:1:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:1:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:1:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:1:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:1:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:1:8', 'DoVa_Co2', '0']
['2021-5-4 3:1:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:1:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:1:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:1:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:1:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:2:8', 'fKWhCounter', '3313.48168945313']
['2021-5-4 3:2:8', 'fActPhLevelMixTank1', '5.67052221298218']
['2021-5-4 3:2:8', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 3:2:8', 'fActPhLevelMixTank2', '3.88872957229614']
['2021-5-4 3:2:8', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 3:2:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:2:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:2:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:2:8', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 3:2:8', 'fActCo2ValMemo', '766']
['2021-5-4 3:2:8', 'fActWaterLevelMixTank1', '290.392852783203']
['2021-5-4 3:2:8', 'fActWaterLevelMixTank2', '287.649475097656']
['2021-5-4 3:2:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:2:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:2:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:2:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:2:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:2:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:2:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:2:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:2:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:2:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:2:8', 'DoVa_Co2', '0']
['2021-5-4 3:2:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:2:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:2:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:2:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:2:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:3:8', 'fKWhCounter', '3313.58178710938']
['2021-5-4 3:3:8', 'fActPhLevelMixTank1', '5.67516088485718']
['2021-5-4 3:3:8', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 3:3:8', 'fActPhLevelMixTank2', '3.88946199417114']
['2021-5-4 3:3:8', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 3:3:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:3:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:3:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:3:8', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 3:3:8', 'fActCo2ValMemo', '765']
['2021-5-4 3:3:8', 'fActWaterLevelMixTank1', '289.768127441406']
['2021-5-4 3:3:8', 'fActWaterLevelMixTank2', '287.350677490234']
['2021-5-4 3:3:8', 'DoPu_AddAcidMixTank_1', '0']

['2021-5-4 3:3:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:3:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:3:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:3:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:3:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:3:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:3:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:3:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:3:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:3:8', 'DoVa_Co2', '0']
['2021-5-4 3:3:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:3:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:3:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:3:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:3:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:4:8', 'fKWhCounter', '3313.78198242188']
['2021-5-4 3:4:8', 'fActPhLevelMixTank1', '5.67247533798218']
['2021-5-4 3:4:8', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 3:4:8', 'fActPhLevelMixTank2', '3.88799715042114']
['2021-5-4 3:4:8', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 3:4:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:4:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:4:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:4:8', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 3:4:8', 'fActCo2ValMemo', '767']
['2021-5-4 3:4:8', 'fActWaterLevelMixTank1', '289.985443115234']
['2021-5-4 3:4:8', 'fActWaterLevelMixTank2', '287.432159423828']
['2021-5-4 3:4:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:4:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:4:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:4:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:4:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:4:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:4:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:4:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:4:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:4:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:4:8', 'DoVa_Co2', '0']
['2021-5-4 3:4:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:4:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:4:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:4:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:4:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:5:8', 'fKWhCounter', '3313.88208007813']
['2021-5-4 3:5:8', 'fActPhLevelMixTank1', '5.67931127548218']
['2021-5-4 3:5:8', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 3:5:8', 'fActPhLevelMixTank2', '3.88872957229614']
['2021-5-4 3:5:8', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 3:5:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:5:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:5:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:5:8', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 3:5:8', 'fActCo2ValMemo', '766']
['2021-5-4 3:5:8', 'fActWaterLevelMixTank1', '290.5830078125']
['2021-5-4 3:5:8', 'fActWaterLevelMixTank2', '287.839599609375']
['2021-5-4 3:5:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:5:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:5:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:5:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:5:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:5:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:5:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:5:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:5:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:5:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:5:8', 'DoVa_Co2', '0']
['2021-5-4 3:5:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:5:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:5:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:5:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:5:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:6:8', 'fKWhCounter', '3313.98217773438']
['2021-5-4 3:6:8', 'fActPhLevelMixTank1', '5.67809057235718']
['2021-5-4 3:6:8', 'fActEcLevelMixTank1', '2031.0068359375']
['2021-5-4 3:6:8', 'fActPhLevelMixTank2', '3.89068269729614']
['2021-5-4 3:6:8', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 3:6:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:6:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:6:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:6:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:6:8', 'fActCo2ValMemo', '764']
['2021-5-4 3:6:8', 'fActWaterLevelMixTank1', '289.496520996094']
['2021-5-4 3:6:8', 'fActWaterLevelMixTank2', '288.111236572266']
['2021-5-4 3:6:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:6:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:6:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:6:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:6:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:6:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:6:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:6:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:6:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:6:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:6:8', 'DoVa_Co2', '0']
['2021-5-4 3:6:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:6:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:6:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:6:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:6:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:7:8', 'fKWhCounter', '3314.18237304688']
['2021-5-4 3:7:8', 'fActPhLevelMixTank1', '5.67613744735718']
['2021-5-4 3:7:8', 'fActEcLevelMixTank1', '2032.38012695313']
['2021-5-4 3:7:8', 'fActPhLevelMixTank2', '3.88970613479614']
['2021-5-4 3:7:8', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 3:7:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:7:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:7:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:7:8', 'fActRhValMemo', '53']
['2021-5-4 3:7:8', 'fActCo2ValMemo', '762']
['2021-5-4 3:7:8', 'fActWaterLevelMixTank1', '291.017608642578']
['2021-5-4 3:7:8', 'fActWaterLevelMixTank2', '288.382843017578']
['2021-5-4 3:7:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:7:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:7:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:7:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:7:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:7:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:7:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:7:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:7:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:7:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:7:8', 'DoVa_Co2', '0']
['2021-5-4 3:7:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:7:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:7:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:7:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']

['2021-5-4 3:7:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:7:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:8:8', 'fKWhCounter', '3314.28247070313']
['2021-5-4 3:8:8', 'fActPhLevelMixTank1', '5.67540502548218']
['2021-5-4 3:8:8', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 3:8:8', 'fActPhLevelMixTank2', '3.89068269729614']
['2021-5-4 3:8:8', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 3:8:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:8:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:8:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:8:8', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 3:8:8', 'fActCo2ValMemo', '761']
['2021-5-4 3:8:8', 'fActWaterLevelMixTank1', '291.044769287109']
['2021-5-4 3:8:8', 'fActWaterLevelMixTank2', '288.111236572266']
['2021-5-4 3:8:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:8:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:8:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:8:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:8:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:8:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:8:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:8:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:8:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:8:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:8:8', 'DoVa_Co2', '0']
['2021-5-4 3:8:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:8:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:8:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:8:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:8:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:9:8', 'fKWhCounter', '3314.48266601563']
['2021-5-4 3:9:8', 'fActPhLevelMixTank1', '5.68492698669434']
['2021-5-4 3:9:8', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 3:9:8', 'fActPhLevelMixTank2', '3.88995027542114']
['2021-5-4 3:9:8', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 3:9:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:9:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:9:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:9:8', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 3:9:8', 'fActCo2ValMemo', '762']
['2021-5-4 3:9:8', 'fActWaterLevelMixTank1', '285.748107910156']
['2021-5-4 3:9:8', 'fActWaterLevelMixTank2', '313.263580322266']
['2021-5-4 3:9:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:9:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:9:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:9:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:9:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:9:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:9:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:9:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:9:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:9:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:9:8', 'DoVa_Co2', '0']
['2021-5-4 3:9:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:9:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:9:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:9:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:9:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:10:8', 'fKWhCounter', '3314.58276367188']
['2021-5-4 3:10:8', 'fActPhLevelMixTank1', '5.56993293762207']
['2021-5-4 3:10:8', 'fActEcLevelMixTank1', '2010.10168457031']
['2021-5-4 3:10:8', 'fActPhLevelMixTank2', '3.79863882064819']
['2021-5-4 3:10:8', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 3:10:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:10:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:10:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:10:8', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 3:10:8', 'fActCo2ValMemo', '761']
['2021-5-4 3:10:8', 'fActWaterLevelMixTank1', '285.340667724609']
['2021-5-4 3:10:8', 'fActWaterLevelMixTank2', '281.945373535156']
['2021-5-4 3:10:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:10:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:10:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:10:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:10:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:10:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:10:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:10:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:10:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:10:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:10:8', 'DoVa_Co2', '0']
['2021-5-4 3:10:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:10:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:10:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:10:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:10:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:11:8', 'fKWhCounter', '3314.78295898438']
['2021-5-4 3:11:8', 'fActPhLevelMixTank1', '5.56797981262207']
['2021-5-4 3:11:8', 'fActEcLevelMixTank1', '2011.16979980469']
['2021-5-4 3:11:8', 'fActPhLevelMixTank2', '3.81402015686035']
['2021-5-4 3:11:8', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 3:11:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:11:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:11:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:11:8', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 3:11:8', 'fActCo2ValMemo', '757']
['2021-5-4 3:11:8', 'fActWaterLevelMixTank1', '277.816680908203']
['2021-5-4 3:11:8', 'fActWaterLevelMixTank2', '292.593017578125']
['2021-5-4 3:11:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:11:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:11:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:11:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:11:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:11:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:11:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:11:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:11:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:11:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:11:8', 'DoVa_Co2', '0']
['2021-5-4 3:11:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:11:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:11:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:11:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:11:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:12:8', 'fKWhCounter', '3314.98315429688']
['2021-5-4 3:12:8', 'fActPhLevelMixTank1', '5.56407356262207']
['2021-5-4 3:12:8', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 3:12:8', 'fActPhLevelMixTank2', '3.81524085998535']
['2021-5-4 3:12:8', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 3:12:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:12:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:12:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:12:8', 'fActRhValMemo', '53']
['2021-5-4 3:12:8', 'fActCo2ValMemo', '755']
['2021-5-4 3:12:8', 'fActWaterLevelMixTank1', '281.483612060547']
['2021-5-4 3:12:8', 'fActWaterLevelMixTank2', '271.379211425781']
['2021-5-4 3:12:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:12:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:12:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:12:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:12:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:12:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:12:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:12:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:12:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:12:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:12:8', 'DoVa_Co2', '0']
['2021-5-4 3:12:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:12:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:12:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:12:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']

['2021-5-4 3:12:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:12:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:13:8', 'fKWhCounter', '3315.18334960938']
['2021-5-4 3:13:8', 'fActPhLevelMixTank1', '5.56871223449707']
['2021-5-4 3:13:8', 'fActEcLevelMixTank1', '2015.28979492188']
['2021-5-4 3:13:8', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 3:13:8', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 3:13:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:13:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:13:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:13:8', 'fActRhValMemo', '53']
['2021-5-4 3:13:8', 'fActCo2ValMemo', '752']
['2021-5-4 3:13:8', 'fActWaterLevelMixTank1', '273.715179443359']
['2021-5-4 3:13:8', 'fActWaterLevelMixTank2', '276.186950683594']
['2021-5-4 3:13:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:13:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:13:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:13:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:13:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:13:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:13:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:13:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:13:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:13:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:13:8', 'DoVa_Co2', '0']
['2021-5-4 3:13:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:13:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:13:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:13:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:13:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:14:8', 'fKWhCounter', '3315.28344726563']
['2021-5-4 3:14:8', 'fActPhLevelMixTank1', '5.56968879699707']
['2021-5-4 3:14:8', 'fActEcLevelMixTank1', '2014.52685546875']
['2021-5-4 3:14:8', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 3:14:8', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 3:14:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:14:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:14:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:14:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:14:8', 'fActCo2ValMemo', '753']
['2021-5-4 3:14:8', 'fActWaterLevelMixTank1', '278.088317871094']
['2021-5-4 3:14:8', 'fActWaterLevelMixTank2', '274.747344970703']
['2021-5-4 3:14:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:14:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:14:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:14:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:14:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:14:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:14:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:14:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:14:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:14:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:14:8', 'DoVa_Co2', '0']
['2021-5-4 3:14:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:14:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:14:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:14:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:14:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:15:8', 'fKWhCounter', '3315.48364257813']
['2021-5-4 3:15:8', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 3:15:8', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 3:15:8', 'fActPhLevelMixTank2', '3.85747861862183']
['2021-5-4 3:15:8', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 3:15:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:15:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:15:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:15:8', 'fActRhValMemo', '53.0999984741211']
['2021-5-4 3:15:8', 'fActCo2ValMemo', '752']
['2021-5-4 3:15:8', 'fActWaterLevelMixTank1', '275.399230957031']
['2021-5-4 3:15:8', 'fActWaterLevelMixTank2', '278.414276123047']
['2021-5-4 3:15:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:15:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:15:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:15:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:15:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:15:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:15:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:15:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:15:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:15:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:15:8', 'DoVa_Co2', '0']
['2021-5-4 3:15:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:15:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:15:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:15:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:15:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:16:8', 'fKWhCounter', '3315.58374023438']
['2021-5-4 3:16:8', 'fActPhLevelMixTank1', '5.57628107070923']
['2021-5-4 3:16:8', 'fActEcLevelMixTank1', '2016.51049804688']
['2021-5-4 3:16:8', 'fActPhLevelMixTank2', '3.85430455207825']
['2021-5-4 3:16:8', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 3:16:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:16:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:16:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:16:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:16:8', 'fActCo2ValMemo', '753']
['2021-5-4 3:16:8', 'fActWaterLevelMixTank1', '275.100463867188']
['2021-5-4 3:16:8', 'fActWaterLevelMixTank2', '278.061157226563']
['2021-5-4 3:16:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:16:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:16:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:16:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:16:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:16:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:16:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:16:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:16:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:16:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:16:8', 'DoVa_Co2', '0']
['2021-5-4 3:16:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:16:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:16:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:16:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:16:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:17:8', 'fKWhCounter', '3315.78393554688']
['2021-5-4 3:17:8', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 3:17:8', 'fActEcLevelMixTank1', '2015.4423828125']
['2021-5-4 3:17:8', 'fActPhLevelMixTank2', '3.85259556770325']
['2021-5-4 3:17:8', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 3:17:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:17:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:17:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:17:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:17:8', 'fActCo2ValMemo', '754']
['2021-5-4 3:17:8', 'fActWaterLevelMixTank1', '273.171936035156']
['2021-5-4 3:17:8', 'fActWaterLevelMixTank2', '277.789520263672']
['2021-5-4 3:17:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:17:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:17:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:17:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:17:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:17:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:17:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:17:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:17:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:17:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:17:8', 'DoVa_Co2', '0']
['2021-5-4 3:17:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:17:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:17:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:17:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:17:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:18:8', 'fKWhCounter', '3315.88403320313']
['2021-5-4 3:18:8', 'fActPhLevelMixTank1', '5.57530450820923']
['2021-5-4 3:18:8', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 3:18:8', 'fActPhLevelMixTank2', '3.85283970832825']
['2021-5-4 3:18:8', 'fActEcLevelMixTank2', '1027.55822753906']
['2021-5-4 3:18:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:18:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:18:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:18:8', 'fActRhValMemo', '53']
['2021-5-4 3:18:8', 'fActCo2ValMemo', '755']
['2021-5-4 3:18:8', 'fActWaterLevelMixTank1', '273.823822021484']
['2021-5-4 3:18:8', 'fActWaterLevelMixTank2', '277.789520263672']
['2021-5-4 3:18:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:18:8', 'DoPu_AddEcAMixTank_1', '0']

['2021-5-4 3:18:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:18:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:18:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:18:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:18:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:18:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:18:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:18:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:18:8', 'DoVa_Co2', '0']
['2021-5-4 3:18:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:18:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:18:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:18:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:18:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:19:8', 'fKWhCounter', '3315.98413085938']
['2021-5-4 3:19:8', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 3:19:8', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 3:19:8', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 3:19:8', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 3:19:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:19:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:19:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:19:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:19:8', 'fActCo2ValMemo', '756']
['2021-5-4 3:19:8', 'fActWaterLevelMixTank1', '275.399230957031']
['2021-5-4 3:19:8', 'fActWaterLevelMixTank2', '278.631561279297']
['2021-5-4 3:19:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:19:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:19:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:19:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:19:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:19:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:19:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:19:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:19:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:19:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:19:8', 'DoVa_Co2', '0']
['2021-5-4 3:19:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:19:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:19:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:19:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:19:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:20:8', 'fKWhCounter', '3316.18432617188']
['2021-5-4 3:20:8', 'fActPhLevelMixTank1', '5.57945489883423']
['2021-5-4 3:20:8', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 3:20:8', 'fActPhLevelMixTank2', '3.85186314582825']
['2021-5-4 3:20:8', 'fActEcLevelMixTank2', '1026.94787597656']
['2021-5-4 3:20:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:20:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:20:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:20:8', 'fActRhValMemo', '53']
['2021-5-4 3:20:8', 'fActCo2ValMemo', '755']
['2021-5-4 3:20:8', 'fActWaterLevelMixTank1', '275.698028564453']
['2021-5-4 3:20:8', 'fActWaterLevelMixTank2', '278.305603027344']
['2021-5-4 3:20:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:20:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:20:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:20:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:20:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:20:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:20:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:20:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:20:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:20:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:20:8', 'DoVa_Co2', '0']
['2021-5-4 3:20:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:20:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:20:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:20:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:20:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:21:8', 'fKWhCounter', '3316.28442382813']
['2021-5-4 3:21:8', 'fActPhLevelMixTank1', '5.58409357070923']
['2021-5-4 3:21:8', 'fActEcLevelMixTank1', '2012.84826660156']
['2021-5-4 3:21:8', 'fActPhLevelMixTank2', '3.85064244270325']
['2021-5-4 3:21:8', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 3:21:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:21:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:21:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:21:8', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 3:21:8', 'fActCo2ValMemo', '753']
['2021-5-4 3:21:8', 'fActWaterLevelMixTank1', '275.888153076172']
['2021-5-4 3:21:8', 'fActWaterLevelMixTank2', '277.898193359375']
['2021-5-4 3:21:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:21:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:21:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:21:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:21:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:21:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:21:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:21:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:21:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:21:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:21:8', 'DoVa_Co2', '0']
['2021-5-4 3:21:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:21:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:21:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:21:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:21:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:22:8', 'fKWhCounter', '3316.48461914063']
['2021-5-4 3:22:8', 'fActPhLevelMixTank1', '5.57652521133423']
['2021-5-4 3:22:8', 'fActEcLevelMixTank1', '2012.54309082031']
['2021-5-4 3:22:8', 'fActPhLevelMixTank2', '3.84478282928467']
['2021-5-4 3:22:8', 'fActEcLevelMixTank2', '1026.79528808594']
['2021-5-4 3:22:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:22:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:22:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:22:8', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 3:22:8', 'fActCo2ValMemo', '751']
['2021-5-4 3:22:8', 'fActWaterLevelMixTank1', '276.404235839844']
['2021-5-4 3:22:8', 'fActWaterLevelMixTank2', '278.387115478516']
['2021-5-4 3:22:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:22:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:22:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:22:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:22:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:22:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:22:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:22:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:22:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:22:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:22:8', 'DoVa_Co2', '0']
['2021-5-4 3:22:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:22:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:22:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:22:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:22:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:23:8', 'fKWhCounter', '3316.58471679688']
['2021-5-4 3:23:8', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 3:23:8', 'fActEcLevelMixTank1', '2008.880859375']
['2021-5-4 3:23:8', 'fActPhLevelMixTank2', '3.85186314582825']
['2021-5-4 3:23:8', 'fActEcLevelMixTank2', '1025.72705078125']
['2021-5-4 3:23:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:23:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:23:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:23:8', 'fActRhValMemo', '53']
['2021-5-4 3:23:8', 'fActCo2ValMemo', '751']
['2021-5-4 3:23:8', 'fActWaterLevelMixTank1', '275.480743408203']
['2021-5-4 3:23:8', 'fActWaterLevelMixTank2', '279.147644042969']
['2021-5-4 3:23:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:23:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:23:8', 'DoPu_AddEcBMixTank_1', '0']

['2021-5-4 3:23:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:23:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:23:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:23:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:23:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:23:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:23:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:23:8', 'DoVa_Co2', '0']
['2021-5-4 3:23:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:23:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:23:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:23:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:23:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:24:8', 'fKWhCounter', '3316.68481445313']
['2021-5-4 3:24:8', 'fActPhLevelMixTank1', '5.58433771133423']
['2021-5-4 3:24:8', 'fActEcLevelMixTank1', '2008.880859375']
['2021-5-4 3:24:8', 'fActPhLevelMixTank2', '3.84624767303467']
['2021-5-4 3:24:8', 'fActEcLevelMixTank2', '1025.11669921875']
['2021-5-4 3:24:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:24:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:24:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:24:8', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 3:24:8', 'fActCo2ValMemo', '750']
['2021-5-4 3:24:8', 'fActWaterLevelMixTank1', '276.023986816406']
['2021-5-4 3:24:8', 'fActWaterLevelMixTank2', '279.256286621094']
['2021-5-4 3:24:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:24:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:24:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:24:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:24:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:24:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:24:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:24:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:24:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:24:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:24:8', 'DoVa_Co2', '0']
['2021-5-4 3:24:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:24:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:24:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:24:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:24:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:25:8', 'fKWhCounter', '3316.88500976563']
['2021-5-4 3:25:8', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 3:25:8', 'fActEcLevelMixTank1', '2012.23791503906']
['2021-5-4 3:25:8', 'fActPhLevelMixTank2', '3.84624767303467']
['2021-5-4 3:25:8', 'fActEcLevelMixTank2', '1025.421875']
['2021-5-4 3:25:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:25:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:25:8', 'fActTempValMemo', '19.5']
['2021-5-4 3:25:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:25:8', 'fActCo2ValMemo', '749']
['2021-5-4 3:25:8', 'fActWaterLevelMixTank1', '278.115478515625']
['2021-5-4 3:25:8', 'fActWaterLevelMixTank2', '279.555084228516']
['2021-5-4 3:25:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:25:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:25:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:25:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:25:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:25:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:25:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:25:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:25:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:25:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:25:8', 'DoVa_Co2', '0']
['2021-5-4 3:25:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:25:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:25:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:25:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:25:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:26:8', 'fKWhCounter', '3316.98510742188']
['2021-5-4 3:26:8', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 3:26:8', 'fActEcLevelMixTank1', '2016.51049804688']
['2021-5-4 3:26:8', 'fActPhLevelMixTank2', '3.85332798957825']
['2021-5-4 3:26:8', 'fActEcLevelMixTank2', '1026.79528808594']
['2021-5-4 3:26:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:26:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:26:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:26:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:26:8', 'fActCo2ValMemo', '753']
['2021-5-4 3:26:8', 'fActWaterLevelMixTank1', '277.789520263672']
['2021-5-4 3:26:8', 'fActWaterLevelMixTank2', '279.962524414063']
['2021-5-4 3:26:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:26:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:26:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:26:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:26:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:26:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:26:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:26:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:26:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:26:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:26:8', 'DoVa_Co2', '0']
['2021-5-4 3:26:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:26:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:26:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:26:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:26:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:27:8', 'fKWhCounter', '3317.18530273438']
['2021-5-4 3:27:8', 'fActPhLevelMixTank1', '5.57994318008423']
['2021-5-4 3:27:8', 'fActEcLevelMixTank1', '2012.23791503906']
['2021-5-4 3:27:8', 'fActPhLevelMixTank2', '3.84917759895325']
['2021-5-4 3:27:8', 'fActEcLevelMixTank2', '1023.13305664063']
['2021-5-4 3:27:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:27:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:27:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:27:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:27:8', 'fActCo2ValMemo', '761']
['2021-5-4 3:27:8', 'fActWaterLevelMixTank1', '277.925354003906']
['2021-5-4 3:27:8', 'fActWaterLevelMixTank2', '279.908203125']
['2021-5-4 3:27:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:27:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:27:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:27:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:27:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:27:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:27:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:27:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:27:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:27:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:27:8', 'DoVa_Co2', '0']
['2021-5-4 3:27:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:27:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:27:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:27:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:27:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:28:8', 'fKWhCounter', '3317.28540039063']
['2021-5-4 3:28:8', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 3:28:8', 'fActEcLevelMixTank1', '2012.23791503906']
['2021-5-4 3:28:8', 'fActPhLevelMixTank2', '3.85161900520325']
['2021-5-4 3:28:8', 'fActEcLevelMixTank2', '1026.94787597656']
['2021-5-4 3:28:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:28:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:28:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:28:8', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 3:28:8', 'fActCo2ValMemo', '773']
['2021-5-4 3:28:8', 'fActWaterLevelMixTank1', '277.191955566406']
['2021-5-4 3:28:8', 'fActWaterLevelMixTank2', '280.288452148438']
['2021-5-4 3:28:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:28:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:28:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:28:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:28:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:28:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:28:8', 'DoVa_IrrigateLevel_1_MT1', '0']

['2021-5-4 3:28:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:28:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:28:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:28:8', 'DoVa_Co2', '0']
['2021-5-4 3:28:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:28:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:28:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:28:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:28:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:29:8', 'fKWhCounter', '3317.38549804688']
['2021-5-4 3:29:8', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 3:29:8', 'fActEcLevelMixTank1', '2010.10168457031']
['2021-5-4 3:29:8', 'fActPhLevelMixTank2', '3.85357213020325']
['2021-5-4 3:29:8', 'fActEcLevelMixTank2', '1026.64270019531']
['2021-5-4 3:29:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:29:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:29:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:29:8', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 3:29:8', 'fActCo2ValMemo', '783']
['2021-5-4 3:29:8', 'fActWaterLevelMixTank1', '277.708038330078']
['2021-5-4 3:29:8', 'fActWaterLevelMixTank2', '280.614410400391']
['2021-5-4 3:29:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:29:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:29:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:29:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:29:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:29:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:29:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:29:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:29:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:29:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:29:8', 'DoVa_Co2', '0']
['2021-5-4 3:29:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:29:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:29:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:29:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:29:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:30:8', 'fKWhCounter', '3317.58569335938']
['2021-5-4 3:30:8', 'fActPhLevelMixTank1', '5.58995342254639']
['2021-5-4 3:30:8', 'fActEcLevelMixTank1', '2011.01721191406']
['2021-5-4 3:30:8', 'fActPhLevelMixTank2', '3.85674619674683']
['2021-5-4 3:30:8', 'fActEcLevelMixTank2', '1025.421875']
['2021-5-4 3:30:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:30:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:30:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:30:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:30:8', 'fActCo2ValMemo', '793']
['2021-5-4 3:30:8', 'fActWaterLevelMixTank1', '279.853881835938']
['2021-5-4 3:30:8', 'fActWaterLevelMixTank2', '280.804565429688']
['2021-5-4 3:30:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:30:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:30:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:30:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:30:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:30:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:30:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:30:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:30:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:30:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:30:8', 'DoVa_Co2', '0']
['2021-5-4 3:30:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:30:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:30:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:30:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:30:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:31:8', 'fKWhCounter', '3317.68579101563']
['2021-5-4 3:31:8', 'fActPhLevelMixTank1', '5.59288311004639']
['2021-5-4 3:31:8', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 3:31:8', 'fActPhLevelMixTank2', '3.85650205612183']
['2021-5-4 3:31:8', 'fActEcLevelMixTank2', '1024.04858398438']
['2021-5-4 3:31:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:31:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:31:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:31:8', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 3:31:8', 'fActCo2ValMemo', '807']
['2021-5-4 3:31:8', 'fActWaterLevelMixTank1', '280.315643310547']
['2021-5-4 3:31:8', 'fActWaterLevelMixTank2', '280.587249755859']
['2021-5-4 3:31:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:31:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:31:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:31:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:31:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:31:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:31:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:31:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:31:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:31:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:31:8', 'DoVa_Co2', '0']
['2021-5-4 3:31:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:31:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:31:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:31:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:31:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:32:8', 'fKWhCounter', '3317.88598632813']
['2021-5-4 3:32:8', 'fActPhLevelMixTank1', '5.59654521942139']
['2021-5-4 3:32:8', 'fActEcLevelMixTank1', '2015.4423828125']
['2021-5-4 3:32:8', 'fActPhLevelMixTank2', '3.85137486457825']
['2021-5-4 3:32:8', 'fActEcLevelMixTank2', '1026.18493652344']
['2021-5-4 3:32:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:32:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:32:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:32:8', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 3:32:8', 'fActCo2ValMemo', '815']
['2021-5-4 3:32:8', 'fActWaterLevelMixTank1', '280.016845703125']
['2021-5-4 3:32:8', 'fActWaterLevelMixTank2', '281.021850585938']
['2021-5-4 3:32:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:32:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:32:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:32:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:32:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:32:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:32:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:32:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:32:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:32:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:32:8', 'DoVa_Co2', '0']
['2021-5-4 3:32:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:32:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:32:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:32:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:32:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:33:8', 'fKWhCounter', '3317.98608398438']
['2021-5-4 3:33:8', 'fActPhLevelMixTank1', '5.60020732879639']
['2021-5-4 3:33:8', 'fActEcLevelMixTank1', '2011.32238769531']
['2021-5-4 3:33:8', 'fActPhLevelMixTank2', '3.85723447799683']
['2021-5-4 3:33:8', 'fActEcLevelMixTank2', '1026.33752441406']
['2021-5-4 3:33:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:33:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:33:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 3:33:8', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 3:33:8', 'fActCo2ValMemo', '825']
['2021-5-4 3:33:8', 'fActWaterLevelMixTank1', '279.555084228516']
['2021-5-4 3:33:8', 'fActWaterLevelMixTank2', '281.836730957031']
['2021-5-4 3:33:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:33:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:33:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:33:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:33:8', 'DoPu_AddEcAMixTank_2', '0']

['2021-5-4 3:33:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:33:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:33:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:33:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:33:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:33:8', 'DoVa_Co2', '0']
['2021-5-4 3:33:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:33:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:33:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:33:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:33:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:34:8', 'fKWhCounter', '3318.08618164063']
['2021-5-4 3:34:8', 'fActPhLevelMixTank1', '5.59678936004639']
['2021-5-4 3:34:8', 'fActEcLevelMixTank1', '2015.28979492188']
['2021-5-4 3:34:8', 'fActPhLevelMixTank2', '3.85918760299683']
['2021-5-4 3:34:8', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 3:34:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:34:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:34:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:34:8', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 3:34:8', 'fActCo2ValMemo', '834']
['2021-5-4 3:34:8', 'fActWaterLevelMixTank1', '281.103332519531']
['2021-5-4 3:34:8', 'fActWaterLevelMixTank2', '282.081176757813']
['2021-5-4 3:34:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:34:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:34:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:34:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:34:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:34:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:34:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:34:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:34:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:34:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:34:8', 'DoVa_Co2', '0']
['2021-5-4 3:34:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:34:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:34:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:34:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:34:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:35:8', 'fKWhCounter', '3318.28637695313']
['2021-5-4 3:35:8', 'fActPhLevelMixTank1', '5.60045146942139']
['2021-5-4 3:35:8', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 3:35:8', 'fActPhLevelMixTank2', '3.85674619674683']
['2021-5-4 3:35:8', 'fActEcLevelMixTank2', '1027.55822753906']
['2021-5-4 3:35:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:35:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:35:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:35:8', 'fActRhValMemo', '53']
['2021-5-4 3:35:8', 'fActCo2ValMemo', '844']
['2021-5-4 3:35:8', 'fActWaterLevelMixTank1', '281.537933349609']
['2021-5-4 3:35:8', 'fActWaterLevelMixTank2', '282.379974365234']
['2021-5-4 3:35:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:35:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:35:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:35:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:35:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:35:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:35:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:35:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:35:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:35:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:35:8', 'DoVa_Co2', '0']
['2021-5-4 3:35:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:35:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:35:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:35:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:35:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:36:8', 'fKWhCounter', '3318.38647460938']
['2021-5-4 3:36:8', 'fActPhLevelMixTank1', '5.60118389129639']
['2021-5-4 3:36:8', 'fActEcLevelMixTank1', '2012.54309082031']
['2021-5-4 3:36:8', 'fActPhLevelMixTank2', '3.85723447799683']
['2021-5-4 3:36:8', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 3:36:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:36:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:36:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:36:8', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 3:36:8', 'fActCo2ValMemo', '851']
['2021-5-4 3:36:8', 'fActWaterLevelMixTank1', '280.940368652344']
['2021-5-4 3:36:8', 'fActWaterLevelMixTank2', '282.271331787109']
['2021-5-4 3:36:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:36:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:36:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:36:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:36:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:36:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:36:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:36:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:36:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:36:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:36:8', 'DoVa_Co2', '0']
['2021-5-4 3:36:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:36:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:36:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:36:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:36:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:37:8', 'fKWhCounter', '3318.58666992188']
['2021-5-4 3:37:8', 'fActPhLevelMixTank1', '5.60631132125854']
['2021-5-4 3:37:8', 'fActEcLevelMixTank1', '2014.52685546875']
['2021-5-4 3:37:8', 'fActPhLevelMixTank2', '3.86382651329041']
['2021-5-4 3:37:8', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 3:37:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:37:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:37:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:37:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:37:8', 'fActCo2ValMemo', '857']
['2021-5-4 3:37:8', 'fActWaterLevelMixTank1', '281.863891601563']
['2021-5-4 3:37:8', 'fActWaterLevelMixTank2', '282.271331787109']
['2021-5-4 3:37:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:37:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:37:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:37:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:37:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:37:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:37:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:37:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:37:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:37:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:37:8', 'DoVa_Co2', '0']
['2021-5-4 3:37:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:37:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:37:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:37:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:37:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']

['2021-5-4 3:37:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:38:8', 'fKWhCounter', '3318.68676757813']
['2021-5-4 3:38:8', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 3:38:8', 'fActEcLevelMixTank1', '2011.16979980469']
['2021-5-4 3:38:8', 'fActPhLevelMixTank2', '3.86382651329041']
['2021-5-4 3:38:8', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 3:38:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:38:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:38:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 3:38:8', 'fActRhValMemo', '53']
['2021-5-4 3:38:8', 'fActCo2ValMemo', '861']
['2021-5-4 3:38:8', 'fActWaterLevelMixTank1', '282.189819335938']
['2021-5-4 3:38:8', 'fActWaterLevelMixTank2', '283.004699707031']
['2021-5-4 3:38:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:38:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:38:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:38:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:38:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:38:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:38:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:38:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:38:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:38:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:38:8', 'DoVa_Co2', '0']
['2021-5-4 3:38:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:38:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:38:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:38:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:38:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:39:8', 'fKWhCounter', '3318.78686523438']
['2021-5-4 3:39:8', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 3:39:8', 'fActEcLevelMixTank1', '2013.00085449219']
['2021-5-4 3:39:8', 'fActPhLevelMixTank2', '3.85894346237183']
['2021-5-4 3:39:8', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 3:39:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:39:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:39:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 3:39:8', 'fActRhValMemo', '53.0999984741211']
['2021-5-4 3:39:8', 'fActCo2ValMemo', '863']
['2021-5-4 3:39:8', 'fActWaterLevelMixTank1', '281.347808837891']
['2021-5-4 3:39:8', 'fActWaterLevelMixTank2', '282.950378417969']
['2021-5-4 3:39:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:39:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:39:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:39:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:39:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:39:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:39:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:39:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:39:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:39:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:39:8', 'DoVa_Co2', '0']
['2021-5-4 3:39:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:39:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:39:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:39:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:39:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:40:8', 'fKWhCounter', '3318.98706054688']
['2021-5-4 3:40:8', 'fActPhLevelMixTank1', '5.61534452438354']
['2021-5-4 3:40:8', 'fActEcLevelMixTank1', '2014.2216796875']
['2021-5-4 3:40:8', 'fActPhLevelMixTank2', '3.86333823204041']
['2021-5-4 3:40:8', 'fActEcLevelMixTank2', '1027.40563964844']
['2021-5-4 3:40:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:40:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:40:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:40:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:40:8', 'fActCo2ValMemo', '865']
['2021-5-4 3:40:8', 'fActWaterLevelMixTank1', '282.570098876953']
['2021-5-4 3:40:8', 'fActWaterLevelMixTank2', '283.412139892578']
['2021-5-4 3:40:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:40:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:40:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:40:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:40:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:40:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:40:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:40:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:40:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:40:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:40:8', 'DoVa_Co2', '0']
['2021-5-4 3:40:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:40:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:40:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:40:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:40:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:41:8', 'fKWhCounter', '3319.08715820313']
['2021-5-4 3:41:8', 'fActPhLevelMixTank1', '5.60631132125854']
['2021-5-4 3:41:8', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 3:41:8', 'fActPhLevelMixTank2', '3.86529135704041']
['2021-5-4 3:41:8', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 3:41:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:41:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:41:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 3:41:8', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 3:41:8', 'fActCo2ValMemo', '865']
['2021-5-4 3:41:8', 'fActWaterLevelMixTank1', '283.303497314453']
['2021-5-4 3:41:8', 'fActWaterLevelMixTank2', '283.276336669922']
['2021-5-4 3:41:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:41:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:41:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:41:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:41:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:41:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:41:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:41:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:41:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:41:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:41:8', 'DoVa_Co2', '0']
['2021-5-4 3:41:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:41:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:41:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:41:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:41:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:42:8', 'fKWhCounter', '3319.28735351563']
['2021-5-4 3:42:8', 'fActPhLevelMixTank1', '5.61192655563354']
['2021-5-4 3:42:8', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 3:42:8', 'fActPhLevelMixTank2', '3.86846518516541']
['2021-5-4 3:42:8', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 3:42:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:42:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:42:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 3:42:8', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 3:42:8', 'fActCo2ValMemo', '865']
['2021-5-4 3:42:8', 'fActWaterLevelMixTank1', '283.412139892578']
['2021-5-4 3:42:8', 'fActWaterLevelMixTank2', '283.765258789063']
['2021-5-4 3:42:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:42:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:42:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:42:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:42:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:42:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:42:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:42:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:42:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:42:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:42:8', 'DoVa_Co2', '0']
['2021-5-4 3:42:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:42:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:42:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:42:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_3_Red', '0']

['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:42:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:43:8', 'fKWhCounter', '3319.38745117188']
['2021-5-4 3:43:8', 'fActPhLevelMixTank1', '5.60997343063354']
['2021-5-4 3:43:8', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 3:43:8', 'fActPhLevelMixTank2', '3.86333823204041']
['2021-5-4 3:43:8', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 3:43:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:43:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:43:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 3:43:8', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 3:43:8', 'fActCo2ValMemo', '865']
['2021-5-4 3:43:8', 'fActWaterLevelMixTank1', '283.846740722656']
['2021-5-4 3:43:8', 'fActWaterLevelMixTank2', '283.765258789063']
['2021-5-4 3:43:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:43:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:43:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:43:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:43:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:43:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:43:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:43:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:43:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:43:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:43:8', 'DoVa_Co2', '0']
['2021-5-4 3:43:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:43:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:43:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:43:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:43:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:44:8', 'fKWhCounter', '3319.48754882813']
['2021-5-4 3:44:8', 'fActPhLevelMixTank1', '5.61363554000854']
['2021-5-4 3:44:8', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 3:44:8', 'fActPhLevelMixTank2', '3.86309385299683']
['2021-5-4 3:44:8', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 3:44:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:44:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:44:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 3:44:8', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 3:44:8', 'fActCo2ValMemo', '866']
['2021-5-4 3:44:8', 'fActWaterLevelMixTank1', '282.407135009766']
['2021-5-4 3:44:8', 'fActWaterLevelMixTank2', '283.873901367188']
['2021-5-4 3:44:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:44:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:44:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:44:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:44:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:44:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:44:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:44:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:44:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:44:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:44:8', 'DoVa_Co2', '0']
['2021-5-4 3:44:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:44:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:44:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:44:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:44:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:45:8', 'fKWhCounter', '3319.68774414063']
['2021-5-4 3:45:8', 'fActPhLevelMixTank1', '5.60679960250854']
['2021-5-4 3:45:8', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 3:45:8', 'fActPhLevelMixTank2', '3.86480307579041']
['2021-5-4 3:45:8', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 3:45:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:45:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:45:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 3:45:8', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 3:45:8', 'fActCo2ValMemo', '865']
['2021-5-4 3:45:8', 'fActWaterLevelMixTank1', '284.389984130859']
['2021-5-4 3:45:8', 'fActWaterLevelMixTank2', '284.498626708984']
['2021-5-4 3:45:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:45:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:45:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:45:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:45:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:45:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:45:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:45:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:45:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:45:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:45:8', 'DoVa_Co2', '0']
['2021-5-4 3:45:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:45:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:45:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:45:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:45:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:46:8', 'fKWhCounter', '3319.78784179688']
['2021-5-4 3:46:8', 'fActPhLevelMixTank1', '5.60679960250854']
['2021-5-4 3:46:8', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 3:46:8', 'fActPhLevelMixTank2', '3.86846518516541']
['2021-5-4 3:46:8', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 3:46:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:46:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:46:8', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 3:46:8', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 3:46:8', 'fActCo2ValMemo', '864']
['2021-5-4 3:46:8', 'fActWaterLevelMixTank1', '284.66162109375']
['2021-5-4 3:46:8', 'fActWaterLevelMixTank2', '284.172698974609']
['2021-5-4 3:46:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:46:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:46:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:46:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:46:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:46:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:46:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:46:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:46:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:46:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:46:8', 'DoVa_Co2', '0']
['2021-5-4 3:46:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:46:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:46:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:46:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:46:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:47:8', 'fKWhCounter', '3319.98803710938']
['2021-5-4 3:47:8', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 3:47:8', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 3:47:8', 'fActPhLevelMixTank2', '3.87041831016541']
['2021-5-4 3:47:8', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 3:47:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:47:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:47:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:47:8', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 3:47:8', 'fActCo2ValMemo', '863']
['2021-5-4 3:47:8', 'fActWaterLevelMixTank1', '284.851745605469']
['2021-5-4 3:47:8', 'fActWaterLevelMixTank2', '285.041870117188']
['2021-5-4 3:47:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:47:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:47:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:47:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:47:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:47:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:47:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:47:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:47:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:47:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:47:8', 'DoVa_Co2', '0']
['2021-5-4 3:47:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:47:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:47:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:47:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_3_Blue', '0']

['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:47:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:48:8', 'fKWhCounter', '3320.08813476563']
['2021-5-4 3:48:8', 'fActPhLevelMixTank1', '5.60972929000854']
['2021-5-4 3:48:8', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 3:48:8', 'fActPhLevelMixTank2', '3.86431479454041']
['2021-5-4 3:48:8', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 3:48:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:48:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:48:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:48:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 3:48:8', 'fActCo2ValMemo', '865']
['2021-5-4 3:48:8', 'fActWaterLevelMixTank1', '285.585144042969']
['2021-5-4 3:48:8', 'fActWaterLevelMixTank2', '285.123382568359']
['2021-5-4 3:48:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:48:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:48:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:48:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:48:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:48:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:48:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:48:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:48:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:48:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:48:8', 'DoVa_Co2', '0']
['2021-5-4 3:48:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:48:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:48:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:48:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:48:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:49:8', 'fKWhCounter', '3320.18823242188']
['2021-5-4 3:49:8', 'fActPhLevelMixTank1', '5.6175422668457']
['2021-5-4 3:49:8', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 3:49:8', 'fActPhLevelMixTank2', '3.86480307579041']
['2021-5-4 3:49:8', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 3:49:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:49:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:49:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:49:8', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 3:49:8', 'fActCo2ValMemo', '863']
['2021-5-4 3:49:8', 'fActWaterLevelMixTank1', '286.237030029297']
['2021-5-4 3:49:8', 'fActWaterLevelMixTank2', '285.313507080078']
['2021-5-4 3:49:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:49:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:49:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:49:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:49:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:49:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:49:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:49:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:49:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:49:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:49:8', 'DoVa_Co2', '0']
['2021-5-4 3:49:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:49:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:49:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:49:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:49:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:50:8', 'fKWhCounter', '3320.38842773438']
['2021-5-4 3:50:8', 'fActPhLevelMixTank1', '5.6202278137207']
['2021-5-4 3:50:8', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 3:50:8', 'fActPhLevelMixTank2', '3.86968588829041']
['2021-5-4 3:50:8', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 3:50:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:50:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:50:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:50:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 3:50:8', 'fActCo2ValMemo', '860']
['2021-5-4 3:50:8', 'fActWaterLevelMixTank1', '284.851745605469']
['2021-5-4 3:50:8', 'fActWaterLevelMixTank2', '286.101226806641']
['2021-5-4 3:50:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:50:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:50:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:50:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:50:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:50:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:50:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:50:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:50:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:50:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:50:8', 'DoVa_Co2', '0']
['2021-5-4 3:50:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:50:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:50:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:50:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:50:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:51:8', 'fKWhCounter', '3320.48852539063']
['2021-5-4 3:51:8', 'fActPhLevelMixTank1', '5.61632108688354']
['2021-5-4 3:51:8', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 3:51:8', 'fActPhLevelMixTank2', '3.86602377891541']
['2021-5-4 3:51:8', 'fActEcLevelMixTank2', '1026.18493652344']
['2021-5-4 3:51:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:51:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:51:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:51:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 3:51:8', 'fActCo2ValMemo', '861']
['2021-5-4 3:51:8', 'fActWaterLevelMixTank1', '286.725952148438']
['2021-5-4 3:51:8', 'fActWaterLevelMixTank2', '285.992553710938']
['2021-5-4 3:51:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:51:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:51:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:51:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:51:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:51:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:51:8', 'DoVa_IrrigateLevel_1_MT1', '0']

['2021-5-4 3:51:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:51:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:51:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:51:8', 'DoVa_Co2', '0']
['2021-5-4 3:51:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:51:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:51:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:51:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:51:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:52:8', 'fKWhCounter', '3320.58862304688']
['2021-5-4 3:52:8', 'fActPhLevelMixTank1', '5.6212043762207']
['2021-5-4 3:52:8', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 3:52:8', 'fActPhLevelMixTank2', '3.87066245079041']
['2021-5-4 3:52:8', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 3:52:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:52:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:52:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:52:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 3:52:8', 'fActCo2ValMemo', '859']
['2021-5-4 3:52:8', 'fActWaterLevelMixTank1', '286.7802734375']
['2021-5-4 3:52:8', 'fActWaterLevelMixTank2', '286.101226806641']
['2021-5-4 3:52:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:52:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:52:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:52:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:52:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:52:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:52:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:52:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:52:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:52:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:52:8', 'DoVa_Co2', '0']
['2021-5-4 3:52:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:52:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:52:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:52:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:52:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:53:8', 'fKWhCounter', '3320.78881835938']
['2021-5-4 3:53:8', 'fActPhLevelMixTank1', '5.6204719543457']
['2021-5-4 3:53:8', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 3:53:8', 'fActPhLevelMixTank2', '3.87066245079041']
['2021-5-4 3:53:8', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 3:53:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:53:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:53:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:53:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 3:53:8', 'fActCo2ValMemo', '857']
['2021-5-4 3:53:8', 'fActWaterLevelMixTank1', '286.7802734375']
['2021-5-4 3:53:8', 'fActWaterLevelMixTank2', '286.481475830078']
['2021-5-4 3:53:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:53:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:53:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:53:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:53:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:53:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:53:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:53:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:53:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:53:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:53:8', 'DoVa_Co2', '0']
['2021-5-4 3:53:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:53:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:53:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:53:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:53:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:54:8', 'fKWhCounter', '3320.88891601563']
['2021-5-4 3:54:8', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 3:54:8', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 3:54:8', 'fActPhLevelMixTank2', '3.87725448608398']
['2021-5-4 3:54:8', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 3:54:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:54:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:54:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:54:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 3:54:8', 'fActCo2ValMemo', '854']
['2021-5-4 3:54:8', 'fActWaterLevelMixTank1', '287.106231689453']
['2021-5-4 3:54:8', 'fActWaterLevelMixTank2', '286.698791503906']
['2021-5-4 3:54:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:54:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:54:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:54:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:54:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:54:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:54:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:54:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:54:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:54:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:54:8', 'DoVa_Co2', '0']
['2021-5-4 3:54:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:54:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:54:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:54:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:54:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:55:8', 'fKWhCounter', '3321.08911132813']
['2021-5-4 3:55:8', 'fActPhLevelMixTank1', '5.6221809387207']
['2021-5-4 3:55:8', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 3:55:8', 'fActPhLevelMixTank2', '3.87701034545898']
['2021-5-4 3:55:8', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 3:55:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:55:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:55:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:55:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 3:55:8', 'fActCo2ValMemo', '856']
['2021-5-4 3:55:8', 'fActWaterLevelMixTank1', '287.079071044922']
['2021-5-4 3:55:8', 'fActWaterLevelMixTank2', '286.617309570313']
['2021-5-4 3:55:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:55:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:55:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:55:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:55:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:55:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:55:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:55:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:55:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:55:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:55:8', 'DoVa_Co2', '0']
['2021-5-4 3:55:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:55:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:55:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:55:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_2_Fred', '0']

['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:55:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:56:9', 'fKWhCounter', '3321.18920898438']
['2021-5-4 3:56:9', 'fActPhLevelMixTank1', '5.61558866500854']
['2021-5-4 3:56:9', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 3:56:9', 'fActPhLevelMixTank2', '3.87823104858398']
['2021-5-4 3:56:9', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 3:56:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:56:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:56:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:56:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 3:56:9', 'fActCo2ValMemo', '856']
['2021-5-4 3:56:9', 'fActWaterLevelMixTank1', '287.839599609375']
['2021-5-4 3:56:9', 'fActWaterLevelMixTank2', '286.644470214844']
['2021-5-4 3:56:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:56:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:56:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:56:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:56:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:56:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:56:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:56:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:56:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:56:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:56:9', 'DoVa_Co2', '0']
['2021-5-4 3:56:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:56:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:56:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:56:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:56:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:57:8', 'fKWhCounter', '3321.28930664063']
['2021-5-4 3:57:8', 'fActPhLevelMixTank1', '5.6182746887207']
['2021-5-4 3:57:8', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 3:57:8', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 3:57:8', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 3:57:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:57:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:57:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:57:8', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 3:57:8', 'fActCo2ValMemo', '852']
['2021-5-4 3:57:8', 'fActWaterLevelMixTank1', '287.459320068359']
['2021-5-4 3:57:8', 'fActWaterLevelMixTank2', '287.269195556641']
['2021-5-4 3:57:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:57:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:57:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:57:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:57:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:57:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:57:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:57:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:57:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:57:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:57:9', 'DoVa_Co2', '0']
['2021-5-4 3:57:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:57:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:57:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:57:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:57:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:58:8', 'fKWhCounter', '3321.48950195313']
['2021-5-4 3:58:8', 'fActPhLevelMixTank1', '5.6251106262207']
['2021-5-4 3:58:8', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 3:58:8', 'fActPhLevelMixTank2', '3.87334823608398']
['2021-5-4 3:58:8', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 3:58:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:58:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:58:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:58:8', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 3:58:8', 'fActCo2ValMemo', '850']
['2021-5-4 3:58:8', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 3:58:8', 'fActWaterLevelMixTank2', '286.943237304688']
['2021-5-4 3:58:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:58:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:58:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:58:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:58:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:58:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:58:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:58:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:58:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:58:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:58:8', 'DoVa_Co2', '0']
['2021-5-4 3:58:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:58:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:58:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:58:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:58:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 3:59:8', 'fKWhCounter', '3321.58959960938']
['2021-5-4 3:59:8', 'fActPhLevelMixTank1', '5.6226692199707']
['2021-5-4 3:59:8', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 3:59:8', 'fActPhLevelMixTank2', '3.87456893920898']
['2021-5-4 3:59:8', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 3:59:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 3:59:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 3:59:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 3:59:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 3:59:8', 'fActCo2ValMemo', '852']
['2021-5-4 3:59:8', 'fActWaterLevelMixTank1', '288.247039794922']
['2021-5-4 3:59:8', 'fActWaterLevelMixTank2', '287.567993164063']
['2021-5-4 3:59:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 3:59:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 3:59:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 3:59:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 3:59:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 3:59:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 3:59:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 3:59:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 3:59:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 3:59:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 3:59:8', 'DoVa_Co2', '0']
['2021-5-4 3:59:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 3:59:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 3:59:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 3:59:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 3:59:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 3:59:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:0:8', 'fKWhCounter', '3321.78979492188']
['2021-5-4 4:0:8', 'fActPhLevelMixTank1', '5.6275520324707']
['2021-5-4 4:0:8', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 4:0:8', 'fActPhLevelMixTank2', '3.88213753700256']
['2021-5-4 4:0:8', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 4:0:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:0:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:0:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:0:8', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 4:0:8', 'fActCo2ValMemo', '854']
['2021-5-4 4:0:8', 'fActWaterLevelMixTank1', '288.138397216797']
['2021-5-4 4:0:8', 'fActWaterLevelMixTank2', '288.192718505859']
['2021-5-4 4:0:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:0:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:0:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:0:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:0:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:0:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:0:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:0:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:0:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:0:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:0:8', 'DoVa_Co2', '0']
['2021-5-4 4:0:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:0:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:0:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:0:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:0:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:1:9', 'fKWhCounter', '3321.88989257813']
['2021-5-4 4:1:9', 'fActPhLevelMixTank1', '5.6321907043457']
['2021-5-4 4:1:9', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 4:1:9', 'fActPhLevelMixTank2', '3.88140511512756']
['2021-5-4 4:1:9', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 4:1:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:1:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:1:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:1:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 4:1:9', 'fActCo2ValMemo', '853']
['2021-5-4 4:1:9', 'fActWaterLevelMixTank1', '287.187713623047']
['2021-5-4 4:1:9', 'fActWaterLevelMixTank2', '287.893920898438']
['2021-5-4 4:1:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:1:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:1:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:1:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:1:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:1:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:1:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:1:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:1:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:1:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:1:9', 'DoVa_Co2', '0']
['2021-5-4 4:1:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:1:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:1:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:1:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:1:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:2:8', 'fKWhCounter', '3321.98999023438']
['2021-5-4 4:2:8', 'fActPhLevelMixTank1', '5.63365602493286']
['2021-5-4 4:2:8', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 4:2:8', 'fActPhLevelMixTank2', '3.87896370887756']
['2021-5-4 4:2:8', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 4:2:8', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:2:8', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:2:8', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:2:8', 'fActRhValMemo', '52']
['2021-5-4 4:2:8', 'fActCo2ValMemo', '850']
['2021-5-4 4:2:8', 'fActWaterLevelMixTank1', '287.921081542969']
['2021-5-4 4:2:8', 'fActWaterLevelMixTank2', '288.165557861328']
['2021-5-4 4:2:8', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:2:8', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:2:8', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:2:8', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:2:8', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:2:8', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:2:8', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:2:8', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:2:8', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:2:8', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:2:8', 'DoVa_Co2', '0']
['2021-5-4 4:2:8', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:2:8', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:2:8', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:2:8', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:2:8', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:3:9', 'fKWhCounter', '3322.19018554688']
['2021-5-4 4:3:9', 'fActPhLevelMixTank1', '5.63585329055786']
['2021-5-4 4:3:9', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 4:3:9', 'fActPhLevelMixTank2', '3.87383651733398']
['2021-5-4 4:3:9', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 4:3:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:3:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:3:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:3:9', 'fActRhValMemo', '52']
['2021-5-4 4:3:9', 'fActCo2ValMemo', '848']
['2021-5-4 4:3:9', 'fActWaterLevelMixTank1', '289.496520996094']
['2021-5-4 4:3:9', 'fActWaterLevelMixTank2', '288.817443847656']
['2021-5-4 4:3:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:3:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:3:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:3:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:3:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:3:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:3:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:3:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:3:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:3:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:3:9', 'DoVa_Co2', '0']
['2021-5-4 4:3:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:3:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:3:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:3:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:3:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:4:9', 'fKWhCounter', '3322.29028320313']
['2021-5-4 4:4:9', 'fActPhLevelMixTank1', '5.63585329055786']
['2021-5-4 4:4:9', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 4:4:9', 'fActPhLevelMixTank2', '3.87481307983398']
['2021-5-4 4:4:9', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 4:4:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:4:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:4:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:4:9', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 4:4:9', 'fActCo2ValMemo', '847']
['2021-5-4 4:4:9', 'fActWaterLevelMixTank1', '289.061920166016']
['2021-5-4 4:4:9', 'fActWaterLevelMixTank2', '288.708801269531']
['2021-5-4 4:4:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:4:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:4:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:4:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:4:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:4:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:4:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:4:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:4:9', 'DoVa_IrrigateLevel_1_MT2', '0']

['2021-5-4 4:4:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:4:9', 'DoVa_Co2', '0']
['2021-5-4 4:4:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:4:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:4:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:4:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:4:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:5:9', 'fKWhCounter', '3322.39038085938']
['2021-5-4 4:5:9', 'fActPhLevelMixTank1', '5.63756227493286']
['2021-5-4 4:5:9', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 4:5:9', 'fActPhLevelMixTank2', '3.87749862670898']
['2021-5-4 4:5:9', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 4:5:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:5:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:5:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:5:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 4:5:9', 'fActCo2ValMemo', '847']
['2021-5-4 4:5:9', 'fActWaterLevelMixTank1', '289.034759521484']
['2021-5-4 4:5:9', 'fActWaterLevelMixTank2', '288.600158691406']
['2021-5-4 4:5:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:5:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:5:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:5:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:5:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:5:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:5:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:5:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:5:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:5:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:5:9', 'DoVa_Co2', '0']
['2021-5-4 4:5:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:5:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:5:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:5:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:5:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:6:9', 'fKWhCounter', '3322.59057617188']
['2021-5-4 4:6:9', 'fActPhLevelMixTank1', '5.64390993118286']
['2021-5-4 4:6:9', 'fActEcLevelMixTank1', '2028.87048339844']
['2021-5-4 4:6:9', 'fActPhLevelMixTank2', '3.88506722450256']
['2021-5-4 4:6:9', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 4:6:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:6:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:6:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:6:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 4:6:9', 'fActCo2ValMemo', '843']
['2021-5-4 4:6:9', 'fActWaterLevelMixTank1', '288.410003662109']
['2021-5-4 4:6:9', 'fActWaterLevelMixTank2', '289.034759521484']
['2021-5-4 4:6:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:6:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:6:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:6:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:6:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:6:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:6:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:6:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:6:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:6:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:6:9', 'DoVa_Co2', '0']
['2021-5-4 4:6:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:6:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:6:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:6:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:6:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:7:9', 'fKWhCounter', '3322.69067382813']
['2021-5-4 4:7:9', 'fActPhLevelMixTank1', '5.64806032180786']
['2021-5-4 4:7:9', 'fActEcLevelMixTank1', '2028.87048339844']
['2021-5-4 4:7:9', 'fActPhLevelMixTank2', '3.87920784950256']
['2021-5-4 4:7:9', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 4:7:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:7:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:7:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:7:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 4:7:9', 'fActCo2ValMemo', '845']
['2021-5-4 4:7:9', 'fActWaterLevelMixTank1', '289.061920166016']
['2021-5-4 4:7:9', 'fActWaterLevelMixTank2', '289.143402099609']
['2021-5-4 4:7:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:7:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:7:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:7:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:7:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:7:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:7:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:7:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:7:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:7:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:7:9', 'DoVa_Co2', '0']
['2021-5-4 4:7:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:7:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:7:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:7:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:7:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:8:9', 'fKWhCounter', '3322.89086914063']
['2021-5-4 4:8:9', 'fActPhLevelMixTank1', '5.65025806427002']
['2021-5-4 4:8:9', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 4:8:9', 'fActPhLevelMixTank2', '3.87701034545898']
['2021-5-4 4:8:9', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 4:8:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:8:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:8:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:8:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 4:8:9', 'fActCo2ValMemo', '845']
['2021-5-4 4:8:9', 'fActWaterLevelMixTank1', '290.121246337891']
['2021-5-4 4:8:9', 'fActWaterLevelMixTank2', '289.659484863281']
['2021-5-4 4:8:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:8:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:8:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:8:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:8:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:8:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:8:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:8:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:8:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:8:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:8:9', 'DoVa_Co2', '0']
['2021-5-4 4:8:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:8:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:8:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:8:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:8:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:9:9', 'fKWhCounter', '3322.99096679688']
['2021-5-4 4:9:9', 'fActPhLevelMixTank1', '5.65196704864502']
['2021-5-4 4:9:9', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 4:9:9', 'fActPhLevelMixTank2', '3.87896370887756']
['2021-5-4 4:9:9', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 4:9:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:9:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:9:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:9:9', 'fActRhValMemo', '52']
['2021-5-4 4:9:9', 'fActCo2ValMemo', '846']
['2021-5-4 4:9:9', 'fActWaterLevelMixTank1', '289.550842285156']
['2021-5-4 4:9:9', 'fActWaterLevelMixTank2', '290.066925048828']
['2021-5-4 4:9:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:9:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:9:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:9:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:9:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:9:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:9:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:9:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:9:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:9:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:9:9', 'DoVa_Co2', '0']
['2021-5-4 4:9:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:9:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:9:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:9:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_1_White', '0']

['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:9:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:10:9', 'fKWhCounter', '3323.09106445313']
['2021-5-4 4:10:9', 'fActPhLevelMixTank1', '5.65538501739502']
['2021-5-4 4:10:9', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 4:10:9', 'fActPhLevelMixTank2', '3.88506722450256']
['2021-5-4 4:10:9', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 4:10:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:10:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:10:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:10:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 4:10:9', 'fActCo2ValMemo', '848']
['2021-5-4 4:10:9', 'fActWaterLevelMixTank1', '290.745971679688']
['2021-5-4 4:10:9', 'fActWaterLevelMixTank2', '289.63232421875']
['2021-5-4 4:10:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:10:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:10:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:10:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:10:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:10:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:10:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:10:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:10:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:10:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:10:9', 'DoVa_Co2', '0']
['2021-5-4 4:10:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:10:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:10:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:10:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:10:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:11:9', 'fKWhCounter', '3323.29125976563']
['2021-5-4 4:11:9', 'fActPhLevelMixTank1', '5.65782642364502']
['2021-5-4 4:11:9', 'fActEcLevelMixTank1', '2029.78601074219']
['2021-5-4 4:11:9', 'fActPhLevelMixTank2', '3.88799715042114']
['2021-5-4 4:11:9', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 4:11:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:11:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:11:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:11:9', 'fActRhValMemo', '52']
['2021-5-4 4:11:9', 'fActCo2ValMemo', '845']
['2021-5-4 4:11:9', 'fActWaterLevelMixTank1', '289.795288085938']
['2021-5-4 4:11:9', 'fActWaterLevelMixTank2', '290.311370849609']
['2021-5-4 4:11:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:11:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:11:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:11:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:11:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:11:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:11:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:11:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:11:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:11:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:11:9', 'DoVa_Co2', '0']
['2021-5-4 4:11:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:11:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:11:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:11:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:11:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:12:9', 'fKWhCounter', '3323.39135742188']
['2021-5-4 4:12:9', 'fActPhLevelMixTank1', '5.65709400177002']
['2021-5-4 4:12:9', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 4:12:9', 'fActPhLevelMixTank2', '3.88677644729614']
['2021-5-4 4:12:9', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 4:12:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:12:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:12:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:12:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 4:12:9', 'fActCo2ValMemo', '844']
['2021-5-4 4:12:9', 'fActWaterLevelMixTank1', '290.963287353516']
['2021-5-4 4:12:9', 'fActWaterLevelMixTank2', '290.637329101563']
['2021-5-4 4:12:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:12:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:12:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:12:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:12:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:12:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:12:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:12:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:12:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:12:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:12:9', 'DoVa_Co2', '0']
['2021-5-4 4:12:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:12:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:12:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:12:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:12:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:13:9', 'fKWhCounter', '3323.59155273438']
['2021-5-4 4:13:9', 'fActPhLevelMixTank1', '5.66344165802002']
['2021-5-4 4:13:9', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 4:13:9', 'fActPhLevelMixTank2', '3.88409066200256']
['2021-5-4 4:13:9', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 4:13:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:13:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:13:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:13:9', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 4:13:9', 'fActCo2ValMemo', '844']
['2021-5-4 4:13:9', 'fActWaterLevelMixTank1', '290.854614257813']
['2021-5-4 4:13:9', 'fActWaterLevelMixTank2', '290.908966064453']
['2021-5-4 4:13:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:13:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:13:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:13:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:13:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:13:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:13:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:13:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:13:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:13:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:13:9', 'DoVa_Co2', '0']
['2021-5-4 4:13:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:13:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:13:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:13:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:13:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:14:9', 'fKWhCounter', '3323.69165039063']
['2021-5-4 4:14:9', 'fActPhLevelMixTank1', '5.65904712677002']
['2021-5-4 4:14:9', 'fActEcLevelMixTank1', '2037.72082519531']
['2021-5-4 4:14:9', 'fActPhLevelMixTank2', '3.88189339637756']
['2021-5-4 4:14:9', 'fActEcLevelMixTank2', '1038.544921875']
['2021-5-4 4:14:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:14:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:14:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:14:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 4:14:9', 'fActCo2ValMemo', '844']
['2021-5-4 4:14:9', 'fActWaterLevelMixTank1', '292.185577392578']
['2021-5-4 4:14:9', 'fActWaterLevelMixTank2', '267.54931640625']
['2021-5-4 4:14:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:14:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:14:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:14:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:14:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:14:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:14:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:14:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:14:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:14:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:14:9', 'DoVa_Co2', '0']
['2021-5-4 4:14:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:14:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:14:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:14:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_3_Red', '0']

['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:14:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:15:9', 'fKWhCounter', '3323.89184570313']
['2021-5-4 4:15:9', 'fActPhLevelMixTank1', '5.56846809387207']
['2021-5-4 4:15:9', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 4:15:9', 'fActPhLevelMixTank2', '3.79351186752319']
['2021-5-4 4:15:9', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 4:15:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:15:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:15:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:15:9', 'fActRhValMemo', '52']
['2021-5-4 4:15:9', 'fActCo2ValMemo', '844']
['2021-5-4 4:15:9', 'fActWaterLevelMixTank1', '278.658721923828']
['2021-5-4 4:15:9', 'fActWaterLevelMixTank2', '302.20849609375']
['2021-5-4 4:15:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:15:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:15:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:15:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:15:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:15:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:15:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:15:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:15:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:15:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:15:9', 'DoVa_Co2', '0']
['2021-5-4 4:15:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:15:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:15:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:15:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:15:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:16:9', 'fKWhCounter', '3323.99194335938']
['2021-5-4 4:16:9', 'fActPhLevelMixTank1', '5.56895637512207']
['2021-5-4 4:16:9', 'fActEcLevelMixTank1', '2014.52685546875']
['2021-5-4 4:16:9', 'fActPhLevelMixTank2', '3.80523085594177']
['2021-5-4 4:16:9', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 4:16:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:16:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:16:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:16:9', 'fActRhValMemo', '52']
['2021-5-4 4:16:9', 'fActCo2ValMemo', '843']
['2021-5-4 4:16:9', 'fActWaterLevelMixTank1', '277.979675292969']
['2021-5-4 4:16:9', 'fActWaterLevelMixTank2', '294.195587158203']
['2021-5-4 4:16:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:16:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:16:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:16:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:16:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:16:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:16:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:16:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:16:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:16:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:16:9', 'DoVa_Co2', '0']
['2021-5-4 4:16:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:16:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:16:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:16:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:16:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:17:9', 'fKWhCounter', '3324.19213867188']
['2021-5-4 4:17:9', 'fActPhLevelMixTank1', '5.56578254699707']
['2021-5-4 4:17:9', 'fActEcLevelMixTank1', '2012.39050292969']
['2021-5-4 4:17:9', 'fActPhLevelMixTank2', '3.80523085594177']
['2021-5-4 4:17:9', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 4:17:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:17:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:17:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:17:9', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 4:17:9', 'fActCo2ValMemo', '844']
['2021-5-4 4:17:9', 'fActWaterLevelMixTank1', '279.555084228516']
['2021-5-4 4:17:9', 'fActWaterLevelMixTank2', '293.380737304688']
['2021-5-4 4:17:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:17:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:17:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:17:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:17:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:17:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:17:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:17:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:17:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:17:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:17:9', 'DoVa_Co2', '0']
['2021-5-4 4:17:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:17:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:17:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:17:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:17:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:18:9', 'fKWhCounter', '3324.39233398438']
['2021-5-4 4:18:9', 'fActPhLevelMixTank1', '5.56993293762207']
['2021-5-4 4:18:9', 'fActEcLevelMixTank1', '2011.78015136719']
['2021-5-4 4:18:9', 'fActPhLevelMixTank2', '3.81084632873535']
['2021-5-4 4:18:9', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 4:18:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:18:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:18:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:18:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 4:18:9', 'fActCo2ValMemo', '843']
['2021-5-4 4:18:9', 'fActWaterLevelMixTank1', '275.15478515625']
['2021-5-4 4:18:9', 'fActWaterLevelMixTank2', '286.535797119141']
['2021-5-4 4:18:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:18:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:18:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:18:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:18:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:18:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:18:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:18:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:18:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:18:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:18:9', 'DoVa_Co2', '0']
['2021-5-4 4:18:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:18:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:18:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:18:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:18:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:19:9', 'fKWhCounter', '3324.49243164063']
['2021-5-4 4:19:9', 'fActPhLevelMixTank1', '5.57164239883423']
['2021-5-4 4:19:9', 'fActEcLevelMixTank1', '2012.39050292969']
['2021-5-4 4:19:9', 'fActPhLevelMixTank2', '3.81646180152893']
['2021-5-4 4:19:9', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 4:19:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:19:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:19:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:19:9', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 4:19:9', 'fActCo2ValMemo', '845']
['2021-5-4 4:19:9', 'fActWaterLevelMixTank1', '278.22412109375']
['2021-5-4 4:19:9', 'fActWaterLevelMixTank2', '284.118347167969']
['2021-5-4 4:19:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:19:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:19:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:19:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:19:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:19:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:19:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:19:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:19:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:19:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:19:9', 'DoVa_Co2', '0']
['2021-5-4 4:19:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:19:9', 'DoVa_IrrigateLevel_4_MT1', '0']

['2021-5-4 4:19:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:19:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:19:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:20:9', 'fKWhCounter', '3324.69262695313']
['2021-5-4 4:20:9', 'fActPhLevelMixTank1', '5.58018732070923']
['2021-5-4 4:20:9', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 4:20:9', 'fActPhLevelMixTank2', '3.84917759895325']
['2021-5-4 4:20:9', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 4:20:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:20:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:20:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:20:9', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 4:20:9', 'fActCo2ValMemo', '843']
['2021-5-4 4:20:9', 'fActWaterLevelMixTank1', '275.942474365234']
['2021-5-4 4:20:9', 'fActWaterLevelMixTank2', '280.315643310547']
['2021-5-4 4:20:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:20:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:20:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:20:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:20:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:20:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:20:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:20:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:20:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:20:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:20:9', 'DoVa_Co2', '0']
['2021-5-4 4:20:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:20:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:20:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:20:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:20:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:21:9', 'fKWhCounter', '3324.79272460938']
['2021-5-4 4:21:9', 'fActPhLevelMixTank1', '5.58433771133423']
['2021-5-4 4:21:9', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 4:21:9', 'fActPhLevelMixTank2', '3.85039830207825']
['2021-5-4 4:21:9', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 4:21:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:21:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:21:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:21:9', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 4:21:9', 'fActCo2ValMemo', '840']
['2021-5-4 4:21:9', 'fActWaterLevelMixTank1', '276.458587646484']
['2021-5-4 4:21:9', 'fActWaterLevelMixTank2', '280.206970214844']
['2021-5-4 4:21:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:21:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:21:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:21:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:21:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:21:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:21:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:21:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:21:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:21:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:21:9', 'DoVa_Co2', '0']
['2021-5-4 4:21:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:21:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:21:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:21:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:21:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:22:9', 'fKWhCounter', '3324.99291992188']
['2021-5-4 4:22:9', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 4:22:9', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 4:22:9', 'fActPhLevelMixTank2', '3.84600353240967']
['2021-5-4 4:22:9', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 4:22:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:22:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:22:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:22:9', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 4:22:9', 'fActCo2ValMemo', '842']
['2021-5-4 4:22:9', 'fActWaterLevelMixTank1', '274.258422851563']
['2021-5-4 4:22:9', 'fActWaterLevelMixTank2', '280.369964599609']
['2021-5-4 4:22:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:22:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:22:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:22:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:22:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:22:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:22:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:22:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:22:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:22:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:22:9', 'DoVa_Co2', '0']
['2021-5-4 4:22:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:22:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:22:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:22:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:22:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:23:9', 'fKWhCounter', '3325.09301757813']
['2021-5-4 4:23:9', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 4:23:9', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 4:23:9', 'fActPhLevelMixTank2', '3.84820103645325']
['2021-5-4 4:23:9', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 4:23:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:23:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:23:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:23:9', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 4:23:9', 'fActCo2ValMemo', '838']
['2021-5-4 4:23:9', 'fActWaterLevelMixTank1', '275.480743408203']
['2021-5-4 4:23:9', 'fActWaterLevelMixTank2', '280.044006347656']
['2021-5-4 4:23:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:23:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:23:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:23:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:23:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:23:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:23:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:23:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:23:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:23:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:23:9', 'DoVa_Co2', '0']
['2021-5-4 4:23:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:23:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:23:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:23:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:23:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:24:9', 'fKWhCounter', '3325.19311523438']
['2021-5-4 4:24:9', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 4:24:9', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 4:24:9', 'fActPhLevelMixTank2', '3.84307384490967']
['2021-5-4 4:24:9', 'fActEcLevelMixTank2', '1027.55822753906']
['2021-5-4 4:24:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:24:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:24:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:24:9', 'fActRhValMemo', '52.5']
['2021-5-4 4:24:9', 'fActCo2ValMemo', '837']
['2021-5-4 4:24:9', 'fActWaterLevelMixTank1', '275.3720703125']
['2021-5-4 4:24:9', 'fActWaterLevelMixTank2', '280.532928466797']
['2021-5-4 4:24:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:24:9', 'DoPu_AddEcAMixTank_1', '0']

['2021-5-4 4:24:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:24:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:24:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:24:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:24:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:24:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:24:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:24:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:24:9', 'DoVa_Co2', '0']
['2021-5-4 4:24:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:24:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:24:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:24:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:24:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:25:9', 'fKWhCounter', '3325.39331054688']
['2021-5-4 4:25:9', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 4:25:9', 'fActEcLevelMixTank1', '2015.90014648438']
['2021-5-4 4:25:9', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 4:25:9', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 4:25:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:25:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:25:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:25:9', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 4:25:9', 'fActCo2ValMemo', '836']
['2021-5-4 4:25:9', 'fActWaterLevelMixTank1', '276.567230224609']
['2021-5-4 4:25:9', 'fActWaterLevelMixTank2', '281.239135742188']
['2021-5-4 4:25:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:25:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:25:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:25:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:25:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:25:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:25:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:25:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:25:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:25:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:25:9', 'DoVa_Co2', '0']
['2021-5-4 4:25:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:25:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:25:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:25:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:25:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:26:9', 'fKWhCounter', '3325.49340820313']
['2021-5-4 4:26:9', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 4:26:9', 'fActEcLevelMixTank1', '2014.2216796875']
['2021-5-4 4:26:9', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 4:26:9', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 4:26:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:26:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:26:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:26:9', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 4:26:9', 'fActCo2ValMemo', '834']
['2021-5-4 4:26:9', 'fActWaterLevelMixTank1', '277.164794921875']
['2021-5-4 4:26:9', 'fActWaterLevelMixTank2', '280.750213623047']
['2021-5-4 4:26:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:26:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:26:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:26:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:26:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:26:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:26:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:26:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:26:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:26:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:26:9', 'DoVa_Co2', '0']
['2021-5-4 4:26:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:26:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:26:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:26:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:26:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:27:9', 'fKWhCounter', '3325.69360351563']
['2021-5-4 4:27:9', 'fActPhLevelMixTank1', '5.58409357070923']
['2021-5-4 4:27:9', 'fActEcLevelMixTank1', '2013.30603027344']
['2021-5-4 4:27:9', 'fActPhLevelMixTank2', '3.84331798553467']
['2021-5-4 4:27:9', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 4:27:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:27:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:27:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:27:9', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 4:27:9', 'fActCo2ValMemo', '833']
['2021-5-4 4:27:9', 'fActWaterLevelMixTank1', '277.517913818359']
['2021-5-4 4:27:9', 'fActWaterLevelMixTank2', '280.804565429688']
['2021-5-4 4:27:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:27:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:27:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:27:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:27:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:27:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:27:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:27:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:27:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:27:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:27:9', 'DoVa_Co2', '0']
['2021-5-4 4:27:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:27:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:27:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:27:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:27:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:28:9', 'fKWhCounter', '3325.79370117188']
['2021-5-4 4:28:9', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 4:28:9', 'fActEcLevelMixTank1', '2013.61120605469']
['2021-5-4 4:28:9', 'fActPhLevelMixTank2', '3.84527111053467']
['2021-5-4 4:28:9', 'fActEcLevelMixTank2', '1026.64270019531']
['2021-5-4 4:28:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:28:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:28:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:28:9', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 4:28:9', 'fActCo2ValMemo', '828']
['2021-5-4 4:28:9', 'fActWaterLevelMixTank1', '277.626556396484']
['2021-5-4 4:28:9', 'fActWaterLevelMixTank2', '281.646575927734']
['2021-5-4 4:28:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:28:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:28:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:28:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:28:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:28:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:28:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:28:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:28:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:28:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:28:9', 'DoVa_Co2', '0']
['2021-5-4 4:28:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:28:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:28:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:28:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']

['2021-5-4 4:28:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:28:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:29:9', 'fKWhCounter', '3325.89379882813']
['2021-5-4 4:29:9', 'fActPhLevelMixTank1', '5.58433771133423']
['2021-5-4 4:29:9', 'fActEcLevelMixTank1', '2017.8837890625']
['2021-5-4 4:29:9', 'fActPhLevelMixTank2', '3.84038829803467']
['2021-5-4 4:29:9', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 4:29:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:29:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:29:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:29:9', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 4:29:9', 'fActCo2ValMemo', '826']
['2021-5-4 4:29:9', 'fActWaterLevelMixTank1', '278.22412109375']
['2021-5-4 4:29:9', 'fActWaterLevelMixTank2', '282.189819335938']
['2021-5-4 4:29:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:29:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:29:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:29:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:29:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:29:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:29:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:29:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:29:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:29:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:29:9', 'DoVa_Co2', '0']
['2021-5-4 4:29:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:29:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:29:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:29:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:29:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:30:9', 'fKWhCounter', '3326.09399414063']
['2021-5-4 4:30:9', 'fActPhLevelMixTank1', '5.58409357070923']
['2021-5-4 4:30:9', 'fActEcLevelMixTank1', '2013.91638183594']
['2021-5-4 4:30:9', 'fActPhLevelMixTank2', '3.84527111053467']
['2021-5-4 4:30:9', 'fActEcLevelMixTank2', '1018.55523681641']
['2021-5-4 4:30:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:30:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:30:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:30:9', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 4:30:9', 'fActCo2ValMemo', '825']
['2021-5-4 4:30:9', 'fActWaterLevelMixTank1', '278.387115478516']
['2021-5-4 4:30:9', 'fActWaterLevelMixTank2', '281.836730957031']
['2021-5-4 4:30:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:30:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:30:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:30:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:30:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:30:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:30:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:30:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:30:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:30:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:30:9', 'DoVa_Co2', '0']
['2021-5-4 4:30:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:30:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:30:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:30:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:30:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:31:9', 'fKWhCounter', '3326.19409179688']
['2021-5-4 4:31:9', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 4:31:9', 'fActEcLevelMixTank1', '2012.54309082031']
['2021-5-4 4:31:9', 'fActPhLevelMixTank2', '3.84429454803467']
['2021-5-4 4:31:9', 'fActEcLevelMixTank2', '1026.79528808594']
['2021-5-4 4:31:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:31:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:31:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:31:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 4:31:9', 'fActCo2ValMemo', '824']
['2021-5-4 4:31:9', 'fActWaterLevelMixTank1', '278.604400634766']
['2021-5-4 4:31:9', 'fActWaterLevelMixTank2', '282.298492431641']
['2021-5-4 4:31:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:31:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:31:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:31:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:31:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:31:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:31:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:31:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:31:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:31:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:31:9', 'DoVa_Co2', '0']
['2021-5-4 4:31:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:31:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:31:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:31:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:31:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:32:9', 'fKWhCounter', '3326.29418945313']
['2021-5-4 4:32:9', 'fActPhLevelMixTank1', '5.58702373504639']
['2021-5-4 4:32:9', 'fActEcLevelMixTank1', '2013.61120605469']
['2021-5-4 4:32:9', 'fActPhLevelMixTank2', '3.84771275520325']
['2021-5-4 4:32:9', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 4:32:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:32:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:32:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:32:9', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 4:32:9', 'fActCo2ValMemo', '825']
['2021-5-4 4:32:9', 'fActWaterLevelMixTank1', '276.947509765625']
['2021-5-4 4:32:9', 'fActWaterLevelMixTank2', '282.379974365234']
['2021-5-4 4:32:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:32:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:32:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:32:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:32:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:32:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:32:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:32:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:32:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:32:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:32:9', 'DoVa_Co2', '0']
['2021-5-4 4:32:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:32:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:32:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:32:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:32:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']

['2021-5-4 4:33:9', 'fKWhCounter', '3326.49438476563']
['2021-5-4 4:33:9', 'fActPhLevelMixTank1', '5.59044170379639']
['2021-5-4 4:33:9', 'fActEcLevelMixTank1', '2012.39050292969']
['2021-5-4 4:33:9', 'fActPhLevelMixTank2', '3.85186314582825']
['2021-5-4 4:33:9', 'fActEcLevelMixTank2', '1026.64270019531']
['2021-5-4 4:33:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:33:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:33:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:33:9', 'fActRhValMemo', '52']
['2021-5-4 4:33:9', 'fActCo2ValMemo', '828']
['2021-5-4 4:33:9', 'fActWaterLevelMixTank1', '277.137634277344']
['2021-5-4 4:33:9', 'fActWaterLevelMixTank2', '282.705932617188']
['2021-5-4 4:33:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:33:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:33:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:33:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:33:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:33:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:33:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:33:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:33:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:33:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:33:9', 'DoVa_Co2', '0']
['2021-5-4 4:33:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:33:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:33:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:33:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:33:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:34:9', 'fKWhCounter', '3326.59448242188']
['2021-5-4 4:34:9', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 4:34:9', 'fActEcLevelMixTank1', '2011.93273925781']
['2021-5-4 4:34:9', 'fActPhLevelMixTank2', '3.85186314582825']
['2021-5-4 4:34:9', 'fActEcLevelMixTank2', '1027.55822753906']
['2021-5-4 4:34:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:34:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:34:9', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 4:34:9', 'fActRhValMemo', '52']
['2021-5-4 4:34:9', 'fActCo2ValMemo', '827']
['2021-5-4 4:34:9', 'fActWaterLevelMixTank1', '279.582244873047']
['2021-5-4 4:34:9', 'fActWaterLevelMixTank2', '282.624420166016']
['2021-5-4 4:34:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:34:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:34:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:34:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:34:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:34:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:34:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:34:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:34:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:34:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:34:9', 'DoVa_Co2', '0']
['2021-5-4 4:34:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:34:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:34:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:34:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:34:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:35:9', 'fKWhCounter', '3326.79467773438']
['2021-5-4 4:35:9', 'fActPhLevelMixTank1', '5.58995342254639']
['2021-5-4 4:35:9', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 4:35:9', 'fActPhLevelMixTank2', '3.84868931770325']
['2021-5-4 4:35:9', 'fActEcLevelMixTank2', '1026.03234863281']
['2021-5-4 4:35:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:35:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:35:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:35:9', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 4:35:9', 'fActCo2ValMemo', '829']
['2021-5-4 4:35:9', 'fActWaterLevelMixTank1', '278.251281738281']
['2021-5-4 4:35:9', 'fActWaterLevelMixTank2', '283.059020996094']
['2021-5-4 4:35:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:35:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:35:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:35:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:35:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:35:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:35:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:35:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:35:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:35:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:35:9', 'DoVa_Co2', '0']
['2021-5-4 4:35:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:35:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:35:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:35:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:35:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:36:9', 'fKWhCounter', '3326.89477539063']
['2021-5-4 4:36:9', 'fActPhLevelMixTank1', '5.59459209442139']
['2021-5-4 4:36:9', 'fActEcLevelMixTank1', '2014.06909179688']
['2021-5-4 4:36:9', 'fActPhLevelMixTank2', '3.84502696990967']
['2021-5-4 4:36:9', 'fActEcLevelMixTank2', '1025.57446289063']
['2021-5-4 4:36:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:36:9', 'fTaktCounterLowerLevel', '0']

['2021-5-4 4:36:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:36:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 4:36:9', 'fActCo2ValMemo', '831']
['2021-5-4 4:36:9', 'fActWaterLevelMixTank1', '278.115478515625']
['2021-5-4 4:36:9', 'fActWaterLevelMixTank2', '282.814575195313']
['2021-5-4 4:36:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:36:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:36:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:36:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:36:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:36:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:36:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:36:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:36:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:36:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:36:9', 'DoVa_Co2', '0']
['2021-5-4 4:36:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:36:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:36:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:36:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:36:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:37:9', 'fKWhCounter', '3326.99487304688']
['2021-5-4 4:37:9', 'fActPhLevelMixTank1', '5.59385967254639']
['2021-5-4 4:37:9', 'fActEcLevelMixTank1', '2011.62756347656']
['2021-5-4 4:37:9', 'fActPhLevelMixTank2', '3.84771275520325']
['2021-5-4 4:37:9', 'fActEcLevelMixTank2', '1024.35375976563']
['2021-5-4 4:37:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:37:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:37:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:37:9', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 4:37:9', 'fActCo2ValMemo', '832']
['2021-5-4 4:37:9', 'fActWaterLevelMixTank1', '279.989685058594']
['2021-5-4 4:37:9', 'fActWaterLevelMixTank2', '283.575103759766']
['2021-5-4 4:37:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:37:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:37:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:37:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:37:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:37:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:37:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:37:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:37:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:37:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:37:9', 'DoVa_Co2', '0']
['2021-5-4 4:37:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:37:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:37:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:37:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:37:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:38:9', 'fKWhCounter', '3327.19506835938']
['2021-5-4 4:38:9', 'fActPhLevelMixTank1', '5.59923076629639']
['2021-5-4 4:38:9', 'fActEcLevelMixTank1', '2013.91638183594']
['2021-5-4 4:38:9', 'fActPhLevelMixTank2', '3.85088658332825']
['2021-5-4 4:38:9', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 4:38:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:38:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:38:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:38:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 4:38:9', 'fActCo2ValMemo', '830']
['2021-5-4 4:38:9', 'fActWaterLevelMixTank1', '280.641571044922']
['2021-5-4 4:38:9', 'fActWaterLevelMixTank2', '283.547943115234']
['2021-5-4 4:38:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:38:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:38:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:38:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:38:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:38:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:38:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:38:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:38:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:38:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:38:9', 'DoVa_Co2', '0']
['2021-5-4 4:38:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:38:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:38:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:38:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:38:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:39:9', 'fKWhCounter', '3327.29516601563']
['2021-5-4 4:39:9', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 4:39:9', 'fActEcLevelMixTank1', '2015.28979492188']
['2021-5-4 4:39:9', 'fActPhLevelMixTank2', '3.85479283332825']
['2021-5-4 4:39:9', 'fActEcLevelMixTank2', '1026.33752441406']
['2021-5-4 4:39:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:39:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:39:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:39:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 4:39:9', 'fActCo2ValMemo', '827']
['2021-5-4 4:39:9', 'fActWaterLevelMixTank1', '279.582244873047']
['2021-5-4 4:39:9', 'fActWaterLevelMixTank2', '283.955383300781']
['2021-5-4 4:39:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:39:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:39:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:39:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:39:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:39:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:39:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:39:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:39:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:39:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:39:9', 'DoVa_Co2', '0']
['2021-5-4 4:39:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:39:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:39:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:39:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:39:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:40:9', 'fKWhCounter', '3327.49536132813']
['2021-5-4 4:40:9', 'fActPhLevelMixTank1', '5.60826444625854']
['2021-5-4 4:40:9', 'fActEcLevelMixTank1', '2013.45861816406']
['2021-5-4 4:40:9', 'fActPhLevelMixTank2', '3.85552549362183']
['2021-5-4 4:40:9', 'fActEcLevelMixTank2', '1025.57446289063']
['2021-5-4 4:40:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:40:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:40:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:40:9', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 4:40:9', 'fActCo2ValMemo', '827']
['2021-5-4 4:40:9', 'fActWaterLevelMixTank1', '281.320648193359']
['2021-5-4 4:40:9', 'fActWaterLevelMixTank2', '283.683776855469']
['2021-5-4 4:40:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:40:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:40:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:40:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:40:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:40:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:40:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:40:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:40:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:40:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:40:9', 'DoVa_Co2', '0']
['2021-5-4 4:40:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:40:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:40:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:40:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_2_Blue', '0']

['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:40:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:41:9', 'fKWhCounter', '3327.59545898438']
['2021-5-4 4:41:9', 'fActPhLevelMixTank1', '5.60533475875854']
['2021-5-4 4:41:9', 'fActEcLevelMixTank1', '2011.78015136719']
['2021-5-4 4:41:9', 'fActPhLevelMixTank2', '3.85821104049683']
['2021-5-4 4:41:9', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 4:41:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:41:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:41:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:41:9', 'fActRhValMemo', '52']
['2021-5-4 4:41:9', 'fActCo2ValMemo', '827']
['2021-5-4 4:41:9', 'fActWaterLevelMixTank1', '280.940368652344']
['2021-5-4 4:41:9', 'fActWaterLevelMixTank2', '283.873901367188']
['2021-5-4 4:41:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:41:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:41:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:41:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:41:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:41:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:41:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:41:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:41:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:41:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:41:9', 'DoVa_Co2', '0']
['2021-5-4 4:41:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:41:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:41:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:41:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:41:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:42:9', 'fKWhCounter', '3327.69555664063']
['2021-5-4 4:42:9', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 4:42:9', 'fActEcLevelMixTank1', '2014.2216796875']
['2021-5-4 4:42:9', 'fActPhLevelMixTank2', '3.85772275924683']
['2021-5-4 4:42:9', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 4:42:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:42:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:42:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:42:9', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 4:42:9', 'fActCo2ValMemo', '829']
['2021-5-4 4:42:9', 'fActWaterLevelMixTank1', '280.750213623047']
['2021-5-4 4:42:9', 'fActWaterLevelMixTank2', '284.824584960938']
['2021-5-4 4:42:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:42:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:42:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:42:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:42:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:42:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:42:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:42:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:42:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:42:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:42:9', 'DoVa_Co2', '0']
['2021-5-4 4:42:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:42:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:42:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:42:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:42:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:43:9', 'fKWhCounter', '3327.89575195313']
['2021-5-4 4:43:9', 'fActPhLevelMixTank1', '5.61168241500854']
['2021-5-4 4:43:9', 'fActEcLevelMixTank1', '2014.2216796875']
['2021-5-4 4:43:9', 'fActPhLevelMixTank2', '3.85259556770325']
['2021-5-4 4:43:9', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 4:43:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:43:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:43:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:43:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 4:43:9', 'fActCo2ValMemo', '828']
['2021-5-4 4:43:9', 'fActWaterLevelMixTank1', '282.570098876953']
['2021-5-4 4:43:9', 'fActWaterLevelMixTank2', '285.204864501953']
['2021-5-4 4:43:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:43:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:43:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:43:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:43:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:43:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:43:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:43:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:43:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:43:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:43:9', 'DoVa_Co2', '0']
['2021-5-4 4:43:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:43:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:43:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:43:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:43:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:44:9', 'fKWhCounter', '3327.99584960938']
['2021-5-4 4:44:9', 'fActPhLevelMixTank1', '5.61192655563354']
['2021-5-4 4:44:9', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 4:44:9', 'fActPhLevelMixTank2', '3.85772275924683']
['2021-5-4 4:44:9', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 4:44:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:44:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:44:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:44:9', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 4:44:9', 'fActCo2ValMemo', '828']
['2021-5-4 4:44:9', 'fActWaterLevelMixTank1', '282.108337402344']
['2021-5-4 4:44:9', 'fActWaterLevelMixTank2', '285.530792236328']
['2021-5-4 4:44:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:44:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:44:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:44:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:44:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:44:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:44:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:44:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:44:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:44:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:44:9', 'DoVa_Co2', '0']
['2021-5-4 4:44:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:44:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:44:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:44:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:44:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:45:9', 'fKWhCounter', '3328.09594726563']
['2021-5-4 4:45:9', 'fActPhLevelMixTank1', '5.60972929000854']
['2021-5-4 4:45:9', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 4:45:9', 'fActPhLevelMixTank2', '3.85479283332825']
['2021-5-4 4:45:9', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 4:45:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:45:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:45:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:45:9', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 4:45:9', 'fActCo2ValMemo', '827']
['2021-5-4 4:45:9', 'fActWaterLevelMixTank1', '282.787414550781']
['2021-5-4 4:45:9', 'fActWaterLevelMixTank2', '285.150543212891']
['2021-5-4 4:45:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:45:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:45:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:45:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:45:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:45:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:45:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:45:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:45:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:45:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:45:9', 'DoVa_Co2', '0']
['2021-5-4 4:45:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:45:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:45:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:45:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_3_White', '0']

['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:45:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:46:9', 'fKWhCounter', '3328.29614257813']
['2021-5-4 4:46:9', 'fActPhLevelMixTank1', '5.61485624313354']
['2021-5-4 4:46:9', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 4:46:9', 'fActPhLevelMixTank2', '3.86089658737183']
['2021-5-4 4:46:9', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 4:46:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:46:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:46:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:46:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 4:46:9', 'fActCo2ValMemo', '825']
['2021-5-4 4:46:9', 'fActWaterLevelMixTank1', '283.330657958984']
['2021-5-4 4:46:9', 'fActWaterLevelMixTank2', '285.856750488281']
['2021-5-4 4:46:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:46:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:46:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:46:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:46:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:46:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:46:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:46:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:46:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:46:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:46:9', 'DoVa_Co2', '0']
['2021-5-4 4:46:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:46:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:46:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:46:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:46:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:47:9', 'fKWhCounter', '3328.39624023438']
['2021-5-4 4:47:9', 'fActPhLevelMixTank1', '5.6175422668457']
['2021-5-4 4:47:9', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 4:47:9', 'fActPhLevelMixTank2', '3.86431479454041']
['2021-5-4 4:47:9', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 4:47:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:47:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:47:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:47:9', 'fActRhValMemo', '52']
['2021-5-4 4:47:9', 'fActCo2ValMemo', '822']
['2021-5-4 4:47:9', 'fActWaterLevelMixTank1', '282.488616943359']
['2021-5-4 4:47:9', 'fActWaterLevelMixTank2', '285.449310302734']
['2021-5-4 4:47:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:47:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:47:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:47:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:47:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:47:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:47:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:47:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:47:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:47:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:47:9', 'DoVa_Co2', '0']
['2021-5-4 4:47:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:47:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:47:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:47:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:47:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:48:9', 'fKWhCounter', '3328.59643554688']
['2021-5-4 4:48:9', 'fActPhLevelMixTank1', '5.6212043762207']
['2021-5-4 4:48:9', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 4:48:9', 'fActPhLevelMixTank2', '3.86138486862183']
['2021-5-4 4:48:9', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 4:48:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:48:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:48:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:48:9', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 4:48:9', 'fActCo2ValMemo', '821']
['2021-5-4 4:48:9', 'fActWaterLevelMixTank1', '283.031860351563']
['2021-5-4 4:48:9', 'fActWaterLevelMixTank2', '285.693786621094']
['2021-5-4 4:48:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:48:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:48:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:48:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:48:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:48:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:48:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:48:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:48:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:48:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:48:9', 'DoVa_Co2', '0']
['2021-5-4 4:48:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:48:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:48:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:48:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:48:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:49:9', 'fKWhCounter', '3328.69653320313']
['2021-5-4 4:49:9', 'fActPhLevelMixTank1', '5.6214485168457']
['2021-5-4 4:49:9', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 4:49:9', 'fActPhLevelMixTank2', '3.86480307579041']
['2021-5-4 4:49:9', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 4:49:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:49:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:49:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:49:9', 'fActRhValMemo', '51.5']
['2021-5-4 4:49:9', 'fActCo2ValMemo', '819']
['2021-5-4 4:49:9', 'fActWaterLevelMixTank1', '284.471466064453']
['2021-5-4 4:49:9', 'fActWaterLevelMixTank2', '286.155548095703']
['2021-5-4 4:49:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:49:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:49:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:49:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:49:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:49:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:49:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:49:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:49:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:49:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:49:9', 'DoVa_Co2', '0']
['2021-5-4 4:49:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:49:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:49:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:49:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:49:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:50:9', 'fKWhCounter', '3328.79663085938']
['2021-5-4 4:50:9', 'fActPhLevelMixTank1', '5.63414430618286']
['2021-5-4 4:50:9', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 4:50:9', 'fActPhLevelMixTank2', '3.86382651329041']
['2021-5-4 4:50:9', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 4:50:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:50:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:50:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 4:50:9', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 4:50:9', 'fActCo2ValMemo', '819']
['2021-5-4 4:50:9', 'fActWaterLevelMixTank1', '285.09619140625']
['2021-5-4 4:50:9', 'fActWaterLevelMixTank2', '286.943237304688']
['2021-5-4 4:50:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:50:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:50:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:50:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:50:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:50:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:50:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:50:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:50:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:50:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:50:9', 'DoVa_Co2', '0']
['2021-5-4 4:50:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:50:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:50:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:50:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_2_Blue', '0']

['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:50:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:51:9', 'fKWhCounter', '3328.99682617188']
['2021-5-4 4:51:9', 'fActPhLevelMixTank1', '5.6319465637207']
['2021-5-4 4:51:9', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 4:51:9', 'fActPhLevelMixTank2', '3.86431479454041']
['2021-5-4 4:51:9', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 4:51:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:51:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:51:9', 'fActTempValMemo', '19.5']
['2021-5-4 4:51:9', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 4:51:9', 'fActCo2ValMemo', '820']
['2021-5-4 4:51:9', 'fActWaterLevelMixTank1', '284.987548828125']
['2021-5-4 4:51:9', 'fActWaterLevelMixTank2', '287.024719238281']
['2021-5-4 4:51:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:51:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:51:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:51:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:51:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:51:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:51:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:51:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:51:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:51:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:51:9', 'DoVa_Co2', '0']
['2021-5-4 4:51:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:51:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:51:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:51:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:51:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:52:9', 'fKWhCounter', '3329.09692382813']
['2021-5-4 4:52:9', 'fActPhLevelMixTank1', '5.63390016555786']
['2021-5-4 4:52:9', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 4:52:9', 'fActPhLevelMixTank2', '3.85821104049683']
['2021-5-4 4:52:9', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 4:52:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:52:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:52:9', 'fActTempValMemo', '19.5']
['2021-5-4 4:52:9', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 4:52:9', 'fActCo2ValMemo', '825']
['2021-5-4 4:52:9', 'fActWaterLevelMixTank1', '285.530792236328']
['2021-5-4 4:52:9', 'fActWaterLevelMixTank2', '287.106231689453']
['2021-5-4 4:52:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:52:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:52:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:52:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:52:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:52:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:52:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:52:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:52:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:52:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:52:9', 'DoVa_Co2', '0']
['2021-5-4 4:52:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:52:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:52:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:52:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:52:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:53:9', 'fKWhCounter', '3329.19702148438']
['2021-5-4 4:53:9', 'fActPhLevelMixTank1', '5.6302375793457']
['2021-5-4 4:53:9', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 4:53:9', 'fActPhLevelMixTank2', '3.85674619674683']
['2021-5-4 4:53:9', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 4:53:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:53:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:53:9', 'fActTempValMemo', '19.5']
['2021-5-4 4:53:9', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 4:53:9', 'fActCo2ValMemo', '824']
['2021-5-4 4:53:9', 'fActWaterLevelMixTank1', '285.585144042969']
['2021-5-4 4:53:9', 'fActWaterLevelMixTank2', '287.540832519531']
['2021-5-4 4:53:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:53:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:53:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:53:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:53:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:53:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:53:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:53:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:53:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:53:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:53:9', 'DoVa_Co2', '0']
['2021-5-4 4:53:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:53:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:53:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:53:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:53:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:54:9', 'fKWhCounter', '3329.39721679688']
['2021-5-4 4:54:9', 'fActPhLevelMixTank1', '5.63292360305786']
['2021-5-4 4:54:9', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 4:54:9', 'fActPhLevelMixTank2', '3.86236143112183']
['2021-5-4 4:54:9', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 4:54:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:54:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:54:9', 'fActTempValMemo', '19.5']
['2021-5-4 4:54:9', 'fActRhValMemo', '52']
['2021-5-4 4:54:9', 'fActCo2ValMemo', '822']
['2021-5-4 4:54:9', 'fActWaterLevelMixTank1', '286.209869384766']
['2021-5-4 4:54:9', 'fActWaterLevelMixTank2', '288.084075927734']
['2021-5-4 4:54:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:54:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:54:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:54:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:54:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:54:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:54:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:54:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:54:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:54:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:54:9', 'DoVa_Co2', '0']
['2021-5-4 4:54:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:54:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:54:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:54:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:54:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:55:9', 'fKWhCounter', '3329.49731445313']
['2021-5-4 4:55:9', 'fActPhLevelMixTank1', '5.63756227493286']
['2021-5-4 4:55:9', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 4:55:9', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 4:55:9', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 4:55:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:55:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:55:9', 'fActTempValMemo', '19.5']
['2021-5-4 4:55:9', 'fActRhValMemo', '52']
['2021-5-4 4:55:9', 'fActCo2ValMemo', '822']
['2021-5-4 4:55:9', 'fActWaterLevelMixTank1', '286.7802734375']
['2021-5-4 4:55:9', 'fActWaterLevelMixTank2', '287.975402832031']
['2021-5-4 4:55:9', 'DoPu_AddAcidMixTank_1', '0']

['2021-5-4 4:55:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:55:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:55:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:55:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:55:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:55:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:55:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:55:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:55:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:55:9', 'DoVa_Co2', '0']
['2021-5-4 4:55:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:55:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:55:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:55:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:55:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:56:9', 'fKWhCounter', '3329.69750976563']
['2021-5-4 4:56:9', 'fActPhLevelMixTank1', '5.64049196243286']
['2021-5-4 4:56:9', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 4:56:9', 'fActPhLevelMixTank2', '3.86480307579041']
['2021-5-4 4:56:9', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 4:56:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:56:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:56:9', 'fActTempValMemo', '19.5']
['2021-5-4 4:56:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 4:56:9', 'fActCo2ValMemo', '818']
['2021-5-4 4:56:9', 'fActWaterLevelMixTank1', '286.725952148438']
['2021-5-4 4:56:9', 'fActWaterLevelMixTank2', '288.627319335938']
['2021-5-4 4:56:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:56:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:56:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:56:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:56:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:56:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:56:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:56:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:56:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:56:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:56:9', 'DoVa_Co2', '0']
['2021-5-4 4:56:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:56:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:56:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:56:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:56:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:57:9', 'fKWhCounter', '3329.79760742188']
['2021-5-4 4:57:9', 'fActPhLevelMixTank1', '5.64268922805786']
['2021-5-4 4:57:9', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 4:57:9', 'fActPhLevelMixTank2', '3.86626791954041']
['2021-5-4 4:57:9', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 4:57:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:57:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:57:9', 'fActTempValMemo', '19.5']
['2021-5-4 4:57:9', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 4:57:9', 'fActCo2ValMemo', '818']
['2021-5-4 4:57:9', 'fActWaterLevelMixTank1', '286.372833251953']
['2021-5-4 4:57:9', 'fActWaterLevelMixTank2', '288.491516113281']
['2021-5-4 4:57:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:57:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:57:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:57:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:57:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:57:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:57:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:57:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:57:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:57:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:57:9', 'DoVa_Co2', '0']
['2021-5-4 4:57:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:57:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:57:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:57:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:57:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:58:9', 'fKWhCounter', '3329.89770507813']
['2021-5-4 4:58:9', 'fActPhLevelMixTank1', '5.64098024368286']
['2021-5-4 4:58:9', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 4:58:9', 'fActPhLevelMixTank2', '3.86700034141541']
['2021-5-4 4:58:9', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 4:58:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:58:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:58:9', 'fActTempValMemo', '19.5']
['2021-5-4 4:58:9', 'fActRhValMemo', '52']
['2021-5-4 4:58:9', 'fActCo2ValMemo', '819']
['2021-5-4 4:58:9', 'fActWaterLevelMixTank1', '286.644470214844']
['2021-5-4 4:58:9', 'fActWaterLevelMixTank2', '288.491516113281']
['2021-5-4 4:58:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:58:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:58:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:58:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:58:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:58:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:58:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:58:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:58:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:58:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:58:9', 'DoVa_Co2', '0']
['2021-5-4 4:58:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:58:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:58:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:58:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:58:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 4:59:9', 'fKWhCounter', '3330.09790039063']
['2021-5-4 4:59:9', 'fActPhLevelMixTank1', '5.64293336868286']
['2021-5-4 4:59:9', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 4:59:9', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 4:59:9', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 4:59:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 4:59:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 4:59:9', 'fActTempValMemo', '19.5']
['2021-5-4 4:59:9', 'fActRhValMemo', '52']
['2021-5-4 4:59:9', 'fActCo2ValMemo', '816']
['2021-5-4 4:59:9', 'fActWaterLevelMixTank1', '287.187713623047']
['2021-5-4 4:59:9', 'fActWaterLevelMixTank2', '289.061920166016']
['2021-5-4 4:59:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 4:59:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 4:59:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 4:59:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 4:59:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 4:59:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 4:59:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 4:59:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 4:59:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 4:59:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 4:59:9', 'DoVa_Co2', '0']
['2021-5-4 4:59:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 4:59:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 4:59:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 4:59:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 4:59:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:0:9', 'fKWhCounter', '3330.19799804688']
['2021-5-4 5:0:9', 'fActPhLevelMixTank1', '5.64830446243286']
['2021-5-4 5:0:9', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 5:0:9', 'fActPhLevelMixTank2', '3.86968588829041']
['2021-5-4 5:0:9', 'fActEcLevelMixTank2', '1053.34631347656']
['2021-5-4 5:0:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:0:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:0:9', 'fActTempValMemo', '19.5']
['2021-5-4 5:0:9', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 5:0:9', 'fActCo2ValMemo', '812']
['2021-5-4 5:0:9', 'fActWaterLevelMixTank1', '286.237030029297']
['2021-5-4 5:0:9', 'fActWaterLevelMixTank2', '289.007598876953']
['2021-5-4 5:0:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:0:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:0:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:0:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:0:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:0:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:0:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:0:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:0:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:0:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:0:9', 'DoVa_Co2', '0']
['2021-5-4 5:0:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:0:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:0:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:0:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_1_Red', '0']

['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:0:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:1:9', 'fKWhCounter', '3330.29809570313']
['2021-5-4 5:1:9', 'fActPhLevelMixTank1', '5.63975954055786']
['2021-5-4 5:1:9', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 5:1:9', 'fActPhLevelMixTank2', '3.87432479858398']
['2021-5-4 5:1:9', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 5:1:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:1:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:1:9', 'fActTempValMemo', '19.5']
['2021-5-4 5:1:9', 'fActRhValMemo', '52']
['2021-5-4 5:1:9', 'fActCo2ValMemo', '811']
['2021-5-4 5:1:9', 'fActWaterLevelMixTank1', '288.572998046875']
['2021-5-4 5:1:9', 'fActWaterLevelMixTank2', '289.849609375']
['2021-5-4 5:1:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:1:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:1:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:1:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:1:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:1:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:1:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:1:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:1:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:1:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:1:9', 'DoVa_Co2', '0']
['2021-5-4 5:1:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:1:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:1:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:1:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:1:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:2:9', 'fKWhCounter', '3330.49829101563']
['2021-5-4 5:2:9', 'fActPhLevelMixTank1', '5.64708375930786']
['2021-5-4 5:2:9', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 5:2:9', 'fActPhLevelMixTank2', '3.86944174766541']
['2021-5-4 5:2:9', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 5:2:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:2:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:2:9', 'fActTempValMemo', '19.5']
['2021-5-4 5:2:9', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:2:9', 'fActCo2ValMemo', '812']
['2021-5-4 5:2:9', 'fActWaterLevelMixTank1', '287.079071044922']
['2021-5-4 5:2:9', 'fActWaterLevelMixTank2', '290.257049560547']
['2021-5-4 5:2:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:2:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:2:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:2:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:2:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:2:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:2:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:2:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:2:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:2:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:2:9', 'DoVa_Co2', '0']
['2021-5-4 5:2:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:2:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:2:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:2:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:2:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:3:9', 'fKWhCounter', '3330.59838867188']
['2021-5-4 5:3:9', 'fActPhLevelMixTank1', '5.64757204055786']
['2021-5-4 5:3:9', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 5:3:9', 'fActPhLevelMixTank2', '3.86944174766541']
['2021-5-4 5:3:9', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 5:3:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:3:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:3:9', 'fActTempValMemo', '19.5']
['2021-5-4 5:3:9', 'fActRhValMemo', '52']
['2021-5-4 5:3:9', 'fActCo2ValMemo', '812']
['2021-5-4 5:3:9', 'fActWaterLevelMixTank1', '288.926086425781']
['2021-5-4 5:3:9', 'fActWaterLevelMixTank2', '290.528686523438']
['2021-5-4 5:3:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:3:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:3:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:3:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:3:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:3:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:3:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:3:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:3:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:3:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:3:9', 'DoVa_Co2', '0']
['2021-5-4 5:3:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:3:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:3:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:3:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:3:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:4:9', 'fKWhCounter', '3330.79858398438']
['2021-5-4 5:4:9', 'fActPhLevelMixTank1', '5.65196704864502']
['2021-5-4 5:4:9', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 5:4:9', 'fActPhLevelMixTank2', '3.87334823608398']
['2021-5-4 5:4:9', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 5:4:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:4:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:4:9', 'fActTempValMemo', '19.5']
['2021-5-4 5:4:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 5:4:9', 'fActCo2ValMemo', '808']
['2021-5-4 5:4:9', 'fActWaterLevelMixTank1', '289.061920166016']
['2021-5-4 5:4:9', 'fActWaterLevelMixTank2', '290.365692138672']
['2021-5-4 5:4:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:4:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:4:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:4:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:4:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:4:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:4:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:4:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:4:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:4:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:4:9', 'DoVa_Co2', '0']
['2021-5-4 5:4:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:4:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:4:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:4:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:4:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:5:9', 'fKWhCounter', '3330.89868164063']
['2021-5-4 5:5:9', 'fActPhLevelMixTank1', '5.64610719680786']
['2021-5-4 5:5:9', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 5:5:9', 'fActPhLevelMixTank2', '3.86944174766541']
['2021-5-4 5:5:9', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 5:5:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:5:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:5:9', 'fActTempValMemo', '19.5']
['2021-5-4 5:5:9', 'fActRhValMemo', '52']
['2021-5-4 5:5:9', 'fActCo2ValMemo', '808']
['2021-5-4 5:5:9', 'fActWaterLevelMixTank1', '289.605163574219']
['2021-5-4 5:5:9', 'fActWaterLevelMixTank2', '290.420043945313']
['2021-5-4 5:5:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:5:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:5:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:5:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:5:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:5:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:5:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:5:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:5:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:5:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:5:9', 'DoVa_Co2', '0']
['2021-5-4 5:5:9', 'DoVa_IrrigateLevel_3_MT1', '0']

['2021-5-4 5:5:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:5:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:5:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:5:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:6:9', 'fKWhCounter', '3330.99877929688']
['2021-5-4 5:6:9', 'fActPhLevelMixTank1', '5.64903736114502']
['2021-5-4 5:6:9', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 5:6:9', 'fActPhLevelMixTank2', '3.87285995483398']
['2021-5-4 5:6:9', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 5:6:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:6:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:6:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:6:9', 'fActRhValMemo', '52.5']
['2021-5-4 5:6:9', 'fActCo2ValMemo', '807']
['2021-5-4 5:6:9', 'fActWaterLevelMixTank1', '289.496520996094']
['2021-5-4 5:6:9', 'fActWaterLevelMixTank2', '291.153411865234']
['2021-5-4 5:6:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:6:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:6:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:6:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:6:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:6:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:6:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:6:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:6:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:6:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:6:9', 'DoVa_Co2', '0']
['2021-5-4 5:6:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:6:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:6:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:6:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:6:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:7:9', 'fKWhCounter', '3331.19897460938']
['2021-5-4 5:7:9', 'fActPhLevelMixTank1', '5.64732789993286']
['2021-5-4 5:7:9', 'fActEcLevelMixTank1', '2029.48083496094']
['2021-5-4 5:7:9', 'fActPhLevelMixTank2', '3.88018441200256']
['2021-5-4 5:7:9', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 5:7:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:7:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:7:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:7:9', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 5:7:9', 'fActCo2ValMemo', '805']
['2021-5-4 5:7:9', 'fActWaterLevelMixTank1', '289.876770019531']
['2021-5-4 5:7:9', 'fActWaterLevelMixTank2', '291.234893798828']
['2021-5-4 5:7:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:7:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:7:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:7:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:7:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:7:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:7:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:7:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:7:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:7:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:7:9', 'DoVa_Co2', '0']
['2021-5-4 5:7:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:7:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:7:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:7:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:7:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:8:9', 'fKWhCounter', '3331.29907226563']
['2021-5-4 5:8:9', 'fActPhLevelMixTank1', '5.65807056427002']
['2021-5-4 5:8:9', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 5:8:9', 'fActPhLevelMixTank2', '3.87749862670898']
['2021-5-4 5:8:9', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 5:8:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:8:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:8:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:8:9', 'fActRhValMemo', '52.5']
['2021-5-4 5:8:9', 'fActCo2ValMemo', '804']
['2021-5-4 5:8:9', 'fActWaterLevelMixTank1', '289.822448730469']
['2021-5-4 5:8:9', 'fActWaterLevelMixTank2', '291.207733154297']
['2021-5-4 5:8:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:8:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:8:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:8:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:8:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:8:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:8:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:8:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:8:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:8:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:8:9', 'DoVa_Co2', '0']
['2021-5-4 5:8:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:8:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:8:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:8:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:8:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:9:9', 'fKWhCounter', '3331.49926757813']
['2021-5-4 5:9:9', 'fActPhLevelMixTank1', '5.65807056427002']
['2021-5-4 5:9:9', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 5:9:9', 'fActPhLevelMixTank2', '3.87896370887756']
['2021-5-4 5:9:9', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 5:9:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:9:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:9:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:9:9', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:9:9', 'fActCo2ValMemo', '802']
['2021-5-4 5:9:9', 'fActWaterLevelMixTank1', '290.718811035156']
['2021-5-4 5:9:9', 'fActWaterLevelMixTank2', '291.7509765625']
['2021-5-4 5:9:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:9:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:9:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:9:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:9:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:9:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:9:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:9:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:9:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:9:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:9:9', 'DoVa_Co2', '0']
['2021-5-4 5:9:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:9:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:9:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:9:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:9:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:10:9', 'fKWhCounter', '3331.59936523438']
['2021-5-4 5:10:9', 'fActPhLevelMixTank1', '5.66270923614502']
['2021-5-4 5:10:9', 'fActEcLevelMixTank1', '2028.87048339844']
['2021-5-4 5:10:9', 'fActPhLevelMixTank2', '3.87847518920898']
['2021-5-4 5:10:9', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 5:10:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:10:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:10:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:10:9', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:10:9', 'fActCo2ValMemo', '803']
['2021-5-4 5:10:9', 'fActWaterLevelMixTank1', '289.197723388672']
['2021-5-4 5:10:9', 'fActWaterLevelMixTank2', '292.267059326172']
['2021-5-4 5:10:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:10:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:10:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:10:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:10:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:10:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:10:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:10:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:10:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:10:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:10:9', 'DoVa_Co2', '0']
['2021-5-4 5:10:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:10:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:10:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:10:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_1_Fred', '0']

['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:10:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:11:9', 'fKWhCounter', '3331.69946289063']
['2021-5-4 5:11:9', 'fActPhLevelMixTank1', '5.66734838485718']
['2021-5-4 5:11:9', 'fActEcLevelMixTank1', '2031.46459960938']
['2021-5-4 5:11:9', 'fActPhLevelMixTank2', '3.88238167762756']
['2021-5-4 5:11:9', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 5:11:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:11:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:11:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:11:9', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:11:9', 'fActCo2ValMemo', '805']
['2021-5-4 5:11:9', 'fActWaterLevelMixTank1', '290.718811035156']
['2021-5-4 5:11:9', 'fActWaterLevelMixTank2', '292.212738037109']
['2021-5-4 5:11:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:11:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:11:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:11:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:11:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:11:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:11:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:11:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:11:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:11:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:11:9', 'DoVa_Co2', '0']
['2021-5-4 5:11:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:11:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:11:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:11:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:11:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:12:9', 'fKWhCounter', '3331.89965820313']
['2021-5-4 5:12:9', 'fActPhLevelMixTank1', '5.66588354110718']
['2021-5-4 5:12:9', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 5:12:9', 'fActPhLevelMixTank2', '3.87945199012756']
['2021-5-4 5:12:9', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 5:12:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:12:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:12:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:12:9', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 5:12:9', 'fActCo2ValMemo', '806']
['2021-5-4 5:12:9', 'fActWaterLevelMixTank1', '291.017608642578']
['2021-5-4 5:12:9', 'fActWaterLevelMixTank2', '292.891815185547']
['2021-5-4 5:12:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:12:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:12:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:12:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:12:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:12:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:12:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:12:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:12:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:12:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:12:9', 'DoVa_Co2', '0']
['2021-5-4 5:12:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:12:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:12:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:12:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:12:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:13:9', 'fKWhCounter', '3331.99975585938']
['2021-5-4 5:13:9', 'fActPhLevelMixTank1', '5.67125463485718']
['2021-5-4 5:13:9', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 5:13:9', 'fActPhLevelMixTank2', '3.87823104858398']
['2021-5-4 5:13:9', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 5:13:9', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:13:9', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:13:9', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:13:9', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:13:9', 'fActCo2ValMemo', '803']
['2021-5-4 5:13:9', 'fActWaterLevelMixTank1', '290.963287353516']
['2021-5-4 5:13:9', 'fActWaterLevelMixTank2', '292.837493896484']
['2021-5-4 5:13:9', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:13:9', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:13:9', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:13:9', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:13:9', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:13:9', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:13:9', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:13:9', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:13:9', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:13:9', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:13:9', 'DoVa_Co2', '0']
['2021-5-4 5:13:9', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:13:9', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:13:9', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:13:9', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:13:9', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:14:10', 'fKWhCounter', '3332.19995117188']
['2021-5-4 5:14:10', 'fActPhLevelMixTank1', '5.67027807235718']
['2021-5-4 5:14:10', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 5:14:10', 'fActPhLevelMixTank2', '3.87701034545898']
['2021-5-4 5:14:10', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 5:14:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:14:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:14:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:14:10', 'fActRhValMemo', '52.5']
['2021-5-4 5:14:10', 'fActCo2ValMemo', '803']
['2021-5-4 5:14:10', 'fActWaterLevelMixTank1', '291.669494628906']
['2021-5-4 5:14:10', 'fActWaterLevelMixTank2', '292.783142089844']
['2021-5-4 5:14:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:14:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:14:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:14:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:14:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:14:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:14:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:14:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:14:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:14:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:14:10', 'DoVa_Co2', '0']
['2021-5-4 5:14:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:14:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:14:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:14:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:14:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:15:10', 'fKWhCounter', '3332.30004882813']
['2021-5-4 5:15:10', 'fActPhLevelMixTank1', '5.66930150985718']
['2021-5-4 5:15:10', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 5:15:10', 'fActPhLevelMixTank2', '3.87920784950256']
['2021-5-4 5:15:10', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 5:15:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:15:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:15:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:15:10', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 5:15:10', 'fActCo2ValMemo', '800']
['2021-5-4 5:15:10', 'fActWaterLevelMixTank1', '292.212738037109']
['2021-5-4 5:15:10', 'fActWaterLevelMixTank2', '293.244903564453']
['2021-5-4 5:15:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:15:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:15:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:15:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:15:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:15:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:15:10', 'DoVa_IrrigateLevel_1_MT1', '0']

['2021-5-4 5:15:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:15:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:15:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:15:10', 'DoVa_Co2', '0']
['2021-5-4 5:15:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:15:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:15:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:15:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:15:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:16:10', 'fKWhCounter', '3332.40014648438']
['2021-5-4 5:16:10', 'fActPhLevelMixTank1', '5.67369604110718']
['2021-5-4 5:16:10', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 5:16:10', 'fActPhLevelMixTank2', '3.87847518920898']
['2021-5-4 5:16:10', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 5:16:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:16:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:16:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:16:10', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:16:10', 'fActCo2ValMemo', '799']
['2021-5-4 5:16:10', 'fActWaterLevelMixTank1', '291.370727539063']
['2021-5-4 5:16:10', 'fActWaterLevelMixTank2', '293.679504394531']
['2021-5-4 5:16:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:16:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:16:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:16:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:16:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:16:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:16:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:16:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:16:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:16:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:16:10', 'DoVa_Co2', '0']
['2021-5-4 5:16:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:16:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:16:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:16:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:16:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:17:10', 'fKWhCounter', '3332.60034179688']
['2021-5-4 5:17:10', 'fActPhLevelMixTank1', '5.67784643173218']
['2021-5-4 5:17:10', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 5:17:10', 'fActPhLevelMixTank2', '3.88384652137756']
['2021-5-4 5:17:10', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 5:17:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:17:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:17:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:17:10', 'fActRhValMemo', '52']
['2021-5-4 5:17:10', 'fActCo2ValMemo', '798']
['2021-5-4 5:17:10', 'fActWaterLevelMixTank1', '292.212738037109']
['2021-5-4 5:17:10', 'fActWaterLevelMixTank2', '294.114105224609']
['2021-5-4 5:17:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:17:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:17:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:17:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:17:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:17:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:17:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:17:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:17:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:17:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:17:10', 'DoVa_Co2', '0']
['2021-5-4 5:17:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:17:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:17:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:17:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:17:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:18:10', 'fKWhCounter', '3332.70043945313']
['2021-5-4 5:18:10', 'fActPhLevelMixTank1', '5.67418432235718']
['2021-5-4 5:18:10', 'fActEcLevelMixTank1', '2028.87048339844']
['2021-5-4 5:18:10', 'fActPhLevelMixTank2', '3.87945199012756']
['2021-5-4 5:18:10', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 5:18:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:18:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:18:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:18:10', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 5:18:10', 'fActCo2ValMemo', '799']
['2021-5-4 5:18:10', 'fActWaterLevelMixTank1', '292.430053710938']
['2021-5-4 5:18:10', 'fActWaterLevelMixTank2', '294.956146240234']
['2021-5-4 5:18:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:18:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:18:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:18:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:18:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:18:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:18:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:18:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:18:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:18:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:18:10', 'DoVa_Co2', '0']
['2021-5-4 5:18:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:18:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:18:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:18:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:18:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:19:10', 'fKWhCounter', '3332.90063476563']
['2021-5-4 5:19:10', 'fActPhLevelMixTank1', '5.66368579864502']
['2021-5-4 5:19:10', 'fActEcLevelMixTank1', '2052.67504882813']
['2021-5-4 5:19:10', 'fActPhLevelMixTank2', '3.86480307579041']
['2021-5-4 5:19:10', 'fActEcLevelMixTank2', '1047.24267578125']
['2021-5-4 5:19:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:19:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:19:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:19:10', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:19:10', 'fActCo2ValMemo', '797']
['2021-5-4 5:19:10', 'fActWaterLevelMixTank1', '288.980438232422']
['2021-5-4 5:19:10', 'fActWaterLevelMixTank2', '302.289978027344']
['2021-5-4 5:19:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:19:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:19:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:19:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:19:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:19:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:19:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:19:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:19:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:19:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:19:10', 'DoVa_Co2', '0']
['2021-5-4 5:19:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:19:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:19:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:19:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:19:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:20:10', 'fKWhCounter', '3333.00073242188']
['2021-5-4 5:20:10', 'fActPhLevelMixTank1', '5.56309700012207']
['2021-5-4 5:20:10', 'fActEcLevelMixTank1', '2017.8837890625']
['2021-5-4 5:20:10', 'fActPhLevelMixTank2', '3.79839468002319']
['2021-5-4 5:20:10', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 5:20:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:20:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:20:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:20:10', 'fActRhValMemo', '52']
['2021-5-4 5:20:10', 'fActCo2ValMemo', '799']
['2021-5-4 5:20:10', 'fActWaterLevelMixTank1', '288.029754638672']
['2021-5-4 5:20:10', 'fActWaterLevelMixTank2', '294.820343017578']
['2021-5-4 5:20:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:20:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:20:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:20:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:20:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:20:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:20:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:20:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:20:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:20:10', 'DoVa_IrrigateLevel_2_MT2', '0']

['2021-5-4 5:20:10', 'DoVa_Co2', '0']
['2021-5-4 5:20:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:20:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:20:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:20:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:20:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:21:10', 'fKWhCounter', '3333.20092773438']
['2021-5-4 5:21:10', 'fActPhLevelMixTank1', '5.57066583633423']
['2021-5-4 5:21:10', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 5:21:10', 'fActPhLevelMixTank2', '3.80059194564819']
['2021-5-4 5:21:10', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 5:21:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:21:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:21:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:21:10', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:21:10', 'fActCo2ValMemo', '798']
['2021-5-4 5:21:10', 'fActWaterLevelMixTank1', '280.288452148438']
['2021-5-4 5:21:10', 'fActWaterLevelMixTank2', '306.201354980469']
['2021-5-4 5:21:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:21:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:21:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:21:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:21:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:21:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:21:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:21:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:21:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:21:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:21:10', 'DoVa_Co2', '0']
['2021-5-4 5:21:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:21:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:21:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:21:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:21:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:22:10', 'fKWhCounter', '3333.40112304688']
['2021-5-4 5:22:10', 'fActPhLevelMixTank1', '5.57139825820923']
['2021-5-4 5:22:10', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 5:22:10', 'fActPhLevelMixTank2', '3.80962562561035']
['2021-5-4 5:22:10', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 5:22:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:22:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:22:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 5:22:10', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 5:22:10', 'fActCo2ValMemo', '798']
['2021-5-4 5:22:10', 'fActWaterLevelMixTank1', '279.392120361328']
['2021-5-4 5:22:10', 'fActWaterLevelMixTank2', '298.052642822266']
['2021-5-4 5:22:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:22:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:22:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:22:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:22:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:22:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:22:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:22:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:22:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:22:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:22:10', 'DoVa_Co2', '0']
['2021-5-4 5:22:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:22:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:22:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:22:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:22:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:23:10', 'fKWhCounter', '3333.50122070313']
['2021-5-4 5:23:10', 'fActPhLevelMixTank1', '5.56797981262207']
['2021-5-4 5:23:10', 'fActEcLevelMixTank1', '2016.51049804688']
['2021-5-4 5:23:10', 'fActPhLevelMixTank2', '3.80620741844177']
['2021-5-4 5:23:10', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 5:23:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:23:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:23:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:23:10', 'fActRhValMemo', '52.5']
['2021-5-4 5:23:10', 'fActCo2ValMemo', '798']
['2021-5-4 5:23:10', 'fActWaterLevelMixTank1', '280.913208007813']
['2021-5-4 5:23:10', 'fActWaterLevelMixTank2', '300.605926513672']
['2021-5-4 5:23:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:23:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:23:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:23:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:23:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:23:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:23:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:23:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:23:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:23:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:23:10', 'DoVa_Co2', '0']
['2021-5-4 5:23:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:23:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:23:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:23:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:23:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:24:10', 'fKWhCounter', '3333.70141601563']
['2021-5-4 5:24:10', 'fActPhLevelMixTank1', '5.57237482070923']
['2021-5-4 5:24:10', 'fActEcLevelMixTank1', '2014.52685546875']
['2021-5-4 5:24:10', 'fActPhLevelMixTank2', '3.81255531311035']
['2021-5-4 5:24:10', 'fActEcLevelMixTank2', '1050.29455566406']
['2021-5-4 5:24:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:24:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:24:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:24:10', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 5:24:10', 'fActCo2ValMemo', '796']
['2021-5-4 5:24:10', 'fActWaterLevelMixTank1', '277.382080078125']
['2021-5-4 5:24:10', 'fActWaterLevelMixTank2', '287.160552978516']
['2021-5-4 5:24:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:24:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:24:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:24:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:24:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:24:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:24:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:24:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:24:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:24:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:24:10', 'DoVa_Co2', '0']
['2021-5-4 5:24:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:24:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:24:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:24:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_2_White', '0']

['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:24:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:25:10', 'fKWhCounter', '3333.90161132813']
['2021-5-4 5:25:10', 'fActPhLevelMixTank1', '5.57701349258423']
['2021-5-4 5:25:10', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 5:25:10', 'fActPhLevelMixTank2', '3.85137486457825']
['2021-5-4 5:25:10', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 5:25:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:25:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:25:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:25:10', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 5:25:10', 'fActCo2ValMemo', '798']
['2021-5-4 5:25:10', 'fActWaterLevelMixTank1', '278.522918701172']
['2021-5-4 5:25:10', 'fActWaterLevelMixTank2', '285.639465332031']
['2021-5-4 5:25:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:25:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:25:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:25:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:25:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:25:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:25:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:25:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:25:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:25:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:25:10', 'DoVa_Co2', '0']
['2021-5-4 5:25:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:25:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:25:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:25:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:25:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:26:10', 'fKWhCounter', '3334.00170898438']
['2021-5-4 5:26:10', 'fActPhLevelMixTank1', '5.57896661758423']
['2021-5-4 5:26:10', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 5:26:10', 'fActPhLevelMixTank2', '3.84673595428467']
['2021-5-4 5:26:10', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 5:26:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:26:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:26:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:26:10', 'fActRhValMemo', '52.5']
['2021-5-4 5:26:10', 'fActCo2ValMemo', '797']
['2021-5-4 5:26:10', 'fActWaterLevelMixTank1', '277.762359619141']
['2021-5-4 5:26:10', 'fActWaterLevelMixTank2', '284.797424316406']
['2021-5-4 5:26:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:26:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:26:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:26:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:26:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:26:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:26:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:26:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:26:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:26:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:26:10', 'DoVa_Co2', '0']
['2021-5-4 5:26:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:26:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:26:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:26:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:26:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:27:10', 'fKWhCounter', '3334.10180664063']
['2021-5-4 5:27:10', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 5:27:10', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 5:27:10', 'fActPhLevelMixTank2', '3.84185314178467']
['2021-5-4 5:27:10', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 5:27:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:27:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:27:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:27:10', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 5:27:10', 'fActCo2ValMemo', '794']
['2021-5-4 5:27:10', 'fActWaterLevelMixTank1', '278.332763671875']
['2021-5-4 5:27:10', 'fActWaterLevelMixTank2', '284.960388183594']
['2021-5-4 5:27:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:27:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:27:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:27:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:27:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:27:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:27:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:27:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:27:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:27:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:27:10', 'DoVa_Co2', '0']
['2021-5-4 5:27:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:27:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:27:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:27:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:27:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:28:10', 'fKWhCounter', '3334.30200195313']
['2021-5-4 5:28:10', 'fActPhLevelMixTank1', '5.57457208633423']
['2021-5-4 5:28:10', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 5:28:10', 'fActPhLevelMixTank2', '3.84234142303467']
['2021-5-4 5:28:10', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 5:28:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:28:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:28:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:28:10', 'fActRhValMemo', '52.5']
['2021-5-4 5:28:10', 'fActCo2ValMemo', '793']
['2021-5-4 5:28:10', 'fActWaterLevelMixTank1', '278.115478515625']
['2021-5-4 5:28:10', 'fActWaterLevelMixTank2', '285.09619140625']
['2021-5-4 5:28:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:28:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:28:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:28:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:28:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:28:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:28:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:28:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:28:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:28:10', 'DoVa_IrrigateLevel_2_MT2', '0']

['2021-5-4 5:28:10', 'DoVa_Co2', '0']
['2021-5-4 5:28:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:28:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:28:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:28:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:28:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:29:10', 'fKWhCounter', '3334.40209960938']
['2021-5-4 5:29:10', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 5:29:10', 'fActEcLevelMixTank1', '2017.2734375']
['2021-5-4 5:29:10', 'fActPhLevelMixTank2', '3.83867907524109']
['2021-5-4 5:29:10', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 5:29:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:29:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:29:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:29:10', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 5:29:10', 'fActCo2ValMemo', '793']
['2021-5-4 5:29:10', 'fActWaterLevelMixTank1', '278.414276123047']
['2021-5-4 5:29:10', 'fActWaterLevelMixTank2', '285.150543212891']
['2021-5-4 5:29:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:29:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:29:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:29:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:29:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:29:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:29:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:29:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:29:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:29:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:29:10', 'DoVa_Co2', '0']
['2021-5-4 5:29:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:29:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:29:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:29:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:29:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:30:10', 'fKWhCounter', '3334.60229492188']
['2021-5-4 5:30:10', 'fActPhLevelMixTank1', '5.57408380508423']
['2021-5-4 5:30:10', 'fActEcLevelMixTank1', '2015.90014648438']
['2021-5-4 5:30:10', 'fActPhLevelMixTank2', '3.83819079399109']
['2021-5-4 5:30:10', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 5:30:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:30:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:30:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:30:10', 'fActRhValMemo', '52.5']
['2021-5-4 5:30:10', 'fActCo2ValMemo', '792']
['2021-5-4 5:30:10', 'fActWaterLevelMixTank1', '279.392120361328']
['2021-5-4 5:30:10', 'fActWaterLevelMixTank2', '286.155548095703']
['2021-5-4 5:30:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:30:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:30:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:30:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:30:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:30:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:30:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:30:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:30:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:30:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:30:10', 'DoVa_Co2', '0']
['2021-5-4 5:30:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:30:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:30:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:30:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:30:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:31:10', 'fKWhCounter', '3334.70239257813']
['2021-5-4 5:31:10', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 5:31:10', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 5:31:10', 'fActPhLevelMixTank2', '3.83745837211609']
['2021-5-4 5:31:10', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 5:31:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:31:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:31:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:31:10', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 5:31:10', 'fActCo2ValMemo', '792']
['2021-5-4 5:31:10', 'fActWaterLevelMixTank1', '278.658721923828']
['2021-5-4 5:31:10', 'fActWaterLevelMixTank2', '286.264190673828']
['2021-5-4 5:31:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:31:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:31:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:31:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:31:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:31:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:31:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:31:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:31:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:31:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:31:10', 'DoVa_Co2', '0']
['2021-5-4 5:31:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:31:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:31:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:31:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:31:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:32:10', 'fKWhCounter', '3334.80249023438']
['2021-5-4 5:32:10', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 5:32:10', 'fActEcLevelMixTank1', '2014.67944335938']
['2021-5-4 5:32:10', 'fActPhLevelMixTank2', '3.83843493461609']
['2021-5-4 5:32:10', 'fActEcLevelMixTank2', '1027.40563964844']
['2021-5-4 5:32:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:32:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:32:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:32:10', 'fActRhValMemo', '52.5']
['2021-5-4 5:32:10', 'fActCo2ValMemo', '793']
['2021-5-4 5:32:10', 'fActWaterLevelMixTank1', '280.016845703125']
['2021-5-4 5:32:10', 'fActWaterLevelMixTank2', '286.291351318359']
['2021-5-4 5:32:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:32:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:32:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:32:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:32:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:32:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:32:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:32:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:32:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:32:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:32:10', 'DoVa_Co2', '0']
['2021-5-4 5:32:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:32:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:32:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:32:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:32:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:33:10', 'fKWhCounter', '3335.00268554688']
['2021-5-4 5:33:10', 'fActPhLevelMixTank1', '5.58238458633423']
['2021-5-4 5:33:10', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 5:33:10', 'fActPhLevelMixTank2', '3.84136486053467']
['2021-5-4 5:33:10', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 5:33:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:33:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:33:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:33:10', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:33:10', 'fActCo2ValMemo', '792']
['2021-5-4 5:33:10', 'fActWaterLevelMixTank1', '281.021850585938']

['2021-5-4 5:33:10', 'fActWaterLevelMixTank2', '286.427154541016']
['2021-5-4 5:33:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:33:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:33:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:33:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:33:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:33:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:33:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:33:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:33:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:33:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:33:10', 'DoVa_Co2', '0']
['2021-5-4 5:33:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:33:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:33:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:33:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:33:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:34:10', 'fKWhCounter', '3335.10278320313']
['2021-5-4 5:34:10', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 5:34:10', 'fActEcLevelMixTank1', '2015.28979492188']
['2021-5-4 5:34:10', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 5:34:10', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 5:34:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:34:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:34:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:34:10', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 5:34:10', 'fActCo2ValMemo', '790']
['2021-5-4 5:34:10', 'fActWaterLevelMixTank1', '281.130493164063']
['2021-5-4 5:34:10', 'fActWaterLevelMixTank2', '286.943237304688']
['2021-5-4 5:34:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:34:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:34:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:34:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:34:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:34:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:34:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:34:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:34:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:34:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:34:10', 'DoVa_Co2', '0']
['2021-5-4 5:34:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:34:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:34:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:34:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:34:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:35:10', 'fKWhCounter', '3335.30297851563']
['2021-5-4 5:35:10', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 5:35:10', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 5:35:10', 'fActPhLevelMixTank2', '3.84014415740967']
['2021-5-4 5:35:10', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 5:35:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:35:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:35:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:35:10', 'fActRhValMemo', '52.5']
['2021-5-4 5:35:10', 'fActCo2ValMemo', '789']
['2021-5-4 5:35:10', 'fActWaterLevelMixTank1', '280.397125244141']
['2021-5-4 5:35:10', 'fActWaterLevelMixTank2', '287.839599609375']
['2021-5-4 5:35:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:35:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:35:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:35:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:35:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:35:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:35:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:35:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:35:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:35:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:35:10', 'DoVa_Co2', '0']
['2021-5-4 5:35:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:35:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:35:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:35:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:35:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:36:10', 'fKWhCounter', '3335.40307617188']
['2021-5-4 5:36:10', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 5:36:10', 'fActEcLevelMixTank1', '2014.06909179688']
['2021-5-4 5:36:10', 'fActPhLevelMixTank2', '3.83916735649109']
['2021-5-4 5:36:10', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 5:36:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:36:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:36:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:36:10', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 5:36:10', 'fActCo2ValMemo', '788']
['2021-5-4 5:36:10', 'fActWaterLevelMixTank1', '282.162658691406']
['2021-5-4 5:36:10', 'fActWaterLevelMixTank2', '287.242034912109']
['2021-5-4 5:36:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:36:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:36:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:36:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:36:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:36:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:36:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:36:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:36:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:36:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:36:10', 'DoVa_Co2', '0']
['2021-5-4 5:36:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:36:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:36:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:36:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:36:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:37:10', 'fKWhCounter', '3335.50317382813']
['2021-5-4 5:37:10', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 5:37:10', 'fActEcLevelMixTank1', '2010.40686035156']
['2021-5-4 5:37:10', 'fActPhLevelMixTank2', '3.84380626678467']
['2021-5-4 5:37:10', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 5:37:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:37:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:37:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:37:10', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 5:37:10', 'fActCo2ValMemo', '787']
['2021-5-4 5:37:10', 'fActWaterLevelMixTank1', '282.352813720703']
['2021-5-4 5:37:10', 'fActWaterLevelMixTank2', '288.084075927734']
['2021-5-4 5:37:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:37:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:37:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:37:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:37:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:37:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:37:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:37:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:37:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:37:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:37:10', 'DoVa_Co2', '0']
['2021-5-4 5:37:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:37:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:37:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:37:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_2_Fred', '0']

['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:37:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:38:10', 'fKWhCounter', '3335.70336914063']
['2021-5-4 5:38:10', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 5:38:10', 'fActEcLevelMixTank1', '2013.45861816406']
['2021-5-4 5:38:10', 'fActPhLevelMixTank2', '3.84795689582825']
['2021-5-4 5:38:10', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 5:38:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:38:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:38:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:38:10', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 5:38:10', 'fActCo2ValMemo', '789']
['2021-5-4 5:38:10', 'fActWaterLevelMixTank1', '282.054016113281']
['2021-5-4 5:38:10', 'fActWaterLevelMixTank2', '287.9482421875']
['2021-5-4 5:38:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:38:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:38:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:38:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:38:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:38:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:38:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:38:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:38:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:38:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:38:10', 'DoVa_Co2', '0']
['2021-5-4 5:38:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:38:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:38:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:38:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:38:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:39:10', 'fKWhCounter', '3335.80346679688']
['2021-5-4 5:39:10', 'fActPhLevelMixTank1', '5.58384943008423']
['2021-5-4 5:39:10', 'fActEcLevelMixTank1', '2015.90014648438']
['2021-5-4 5:39:10', 'fActPhLevelMixTank2', '3.85064244270325']
['2021-5-4 5:39:10', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 5:39:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:39:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:39:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:39:10', 'fActRhValMemo', '53']
['2021-5-4 5:39:10', 'fActCo2ValMemo', '787']
['2021-5-4 5:39:10', 'fActWaterLevelMixTank1', '281.782409667969']
['2021-5-4 5:39:10', 'fActWaterLevelMixTank2', '288.056915283203']
['2021-5-4 5:39:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:39:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:39:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:39:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:39:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:39:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:39:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:39:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:39:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:39:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:39:10', 'DoVa_Co2', '0']
['2021-5-4 5:39:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:39:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:39:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:39:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:39:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:40:10', 'fKWhCounter', '3336.00366210938']
['2021-5-4 5:40:10', 'fActPhLevelMixTank1', '5.58775615692139']
['2021-5-4 5:40:10', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 5:40:10', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 5:40:10', 'fActEcLevelMixTank2', '1027.55822753906']
['2021-5-4 5:40:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:40:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:40:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:40:10', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 5:40:10', 'fActCo2ValMemo', '788']
['2021-5-4 5:40:10', 'fActWaterLevelMixTank1', '283.439300537109']
['2021-5-4 5:40:10', 'fActWaterLevelMixTank2', '288.491516113281']
['2021-5-4 5:40:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:40:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:40:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:40:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:40:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:40:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:40:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:40:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:40:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:40:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:40:10', 'DoVa_Co2', '0']
['2021-5-4 5:40:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:40:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:40:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:40:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:40:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:41:10', 'fKWhCounter', '3336.10375976563']
['2021-5-4 5:41:10', 'fActPhLevelMixTank1', '5.59532451629639']
['2021-5-4 5:41:10', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 5:41:10', 'fActPhLevelMixTank2', '3.85283970832825']
['2021-5-4 5:41:10', 'fActEcLevelMixTank2', '1026.03234863281']
['2021-5-4 5:41:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:41:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:41:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:41:10', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 5:41:10', 'fActCo2ValMemo', '784']
['2021-5-4 5:41:10', 'fActWaterLevelMixTank1', '282.189819335938']
['2021-5-4 5:41:10', 'fActWaterLevelMixTank2', '288.382843017578']
['2021-5-4 5:41:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:41:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:41:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:41:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:41:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:41:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:41:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:41:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:41:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:41:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:41:10', 'DoVa_Co2', '0']
['2021-5-4 5:41:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:41:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:41:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:41:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:41:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:42:10', 'fKWhCounter', '3336.20385742188']
['2021-5-4 5:42:10', 'fActPhLevelMixTank1', '5.60093975067139']
['2021-5-4 5:42:10', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 5:42:10', 'fActPhLevelMixTank2', '3.85357213020325']
['2021-5-4 5:42:10', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 5:42:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:42:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:42:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:42:10', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 5:42:10', 'fActCo2ValMemo', '782']
['2021-5-4 5:42:10', 'fActWaterLevelMixTank1', '283.955383300781']
['2021-5-4 5:42:10', 'fActWaterLevelMixTank2', '288.518676757813']
['2021-5-4 5:42:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:42:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:42:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:42:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:42:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:42:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:42:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:42:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:42:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:42:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:42:10', 'DoVa_Co2', '0']
['2021-5-4 5:42:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:42:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:42:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:42:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_1_White', '0']

['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:42:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:43:10', 'fKWhCounter', '3336.40405273438']
['2021-5-4 5:43:10', 'fActPhLevelMixTank1', '5.60533475875854']
['2021-5-4 5:43:10', 'fActEcLevelMixTank1', '2014.83203125']
['2021-5-4 5:43:10', 'fActPhLevelMixTank2', '3.85235142707825']
['2021-5-4 5:43:10', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 5:43:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:43:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:43:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:43:10', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 5:43:10', 'fActCo2ValMemo', '780']
['2021-5-4 5:43:10', 'fActWaterLevelMixTank1', '284.064025878906']
['2021-5-4 5:43:10', 'fActWaterLevelMixTank2', '288.926086425781']
['2021-5-4 5:43:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:43:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:43:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:43:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:43:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:43:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:43:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:43:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:43:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:43:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:43:10', 'DoVa_Co2', '0']
['2021-5-4 5:43:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:43:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:43:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:43:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:43:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:44:10', 'fKWhCounter', '3336.50415039063']
['2021-5-4 5:44:10', 'fActPhLevelMixTank1', '5.60338163375854']
['2021-5-4 5:44:10', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 5:44:10', 'fActPhLevelMixTank2', '3.85845518112183']
['2021-5-4 5:44:10', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 5:44:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:44:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:44:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:44:10', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 5:44:10', 'fActCo2ValMemo', '780']
['2021-5-4 5:44:10', 'fActWaterLevelMixTank1', '283.92822265625']
['2021-5-4 5:44:10', 'fActWaterLevelMixTank2', '289.034759521484']
['2021-5-4 5:44:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:44:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:44:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:44:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:44:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:44:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:44:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:44:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:44:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:44:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:44:10', 'DoVa_Co2', '0']
['2021-5-4 5:44:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:44:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:44:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:44:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:44:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:45:10', 'fKWhCounter', '3336.70434570313']
['2021-5-4 5:45:10', 'fActPhLevelMixTank1', '5.60386991500854']
['2021-5-4 5:45:10', 'fActEcLevelMixTank1', '2014.83203125']
['2021-5-4 5:45:10', 'fActPhLevelMixTank2', '3.85454869270325']
['2021-5-4 5:45:10', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 5:45:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:45:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:45:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:45:10', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 5:45:10', 'fActCo2ValMemo', '782']
['2021-5-4 5:45:10', 'fActWaterLevelMixTank1', '284.118347167969']
['2021-5-4 5:45:10', 'fActWaterLevelMixTank2', '288.817443847656']
['2021-5-4 5:45:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:45:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:45:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:45:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:45:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:45:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:45:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:45:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:45:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:45:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:45:10', 'DoVa_Co2', '0']
['2021-5-4 5:45:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:45:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:45:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:45:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:45:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:46:10', 'fKWhCounter', '3336.80444335938']
['2021-5-4 5:46:10', 'fActPhLevelMixTank1', '5.60484647750854']
['2021-5-4 5:46:10', 'fActEcLevelMixTank1', '2013.45861816406']
['2021-5-4 5:46:10', 'fActPhLevelMixTank2', '3.85235142707825']
['2021-5-4 5:46:10', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 5:46:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:46:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:46:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:46:10', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 5:46:10', 'fActCo2ValMemo', '780']
['2021-5-4 5:46:10', 'fActWaterLevelMixTank1', '283.222015380859']
['2021-5-4 5:46:10', 'fActWaterLevelMixTank2', '289.252044677734']
['2021-5-4 5:46:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:46:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:46:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:46:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:46:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:46:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:46:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:46:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:46:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:46:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:46:10', 'DoVa_Co2', '0']
['2021-5-4 5:46:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:46:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:46:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:46:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:46:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:47:10', 'fKWhCounter', '3336.90454101563']
['2021-5-4 5:47:10', 'fActPhLevelMixTank1', '5.60509061813354']
['2021-5-4 5:47:10', 'fActEcLevelMixTank1', '2013.00085449219']

['2021-5-4 5:47:10', 'fActPhLevelMixTank2', '3.85747861862183']
['2021-5-4 5:47:10', 'fActEcLevelMixTank2', '1027.40563964844']
['2021-5-4 5:47:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:47:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:47:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:47:10', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 5:47:10', 'fActCo2ValMemo', '781']
['2021-5-4 5:47:10', 'fActWaterLevelMixTank1', '285.014709472656']
['2021-5-4 5:47:10', 'fActWaterLevelMixTank2', '289.360687255859']
['2021-5-4 5:47:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:47:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:47:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:47:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:47:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:47:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:47:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:47:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:47:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:47:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:47:10', 'DoVa_Co2', '0']
['2021-5-4 5:47:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:47:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:47:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:47:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:47:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:48:10', 'fKWhCounter', '3337.10473632813']
['2021-5-4 5:48:10', 'fActPhLevelMixTank1', '5.60972929000854']
['2021-5-4 5:48:10', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 5:48:10', 'fActPhLevelMixTank2', '3.85479283332825']
['2021-5-4 5:48:10', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 5:48:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:48:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:48:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:48:10', 'fActRhValMemo', '52']
['2021-5-4 5:48:10', 'fActCo2ValMemo', '780']
['2021-5-4 5:48:10', 'fActWaterLevelMixTank1', '285.232025146484']
['2021-5-4 5:48:10', 'fActWaterLevelMixTank2', '289.849609375']
['2021-5-4 5:48:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:48:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:48:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:48:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:48:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:48:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:48:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:48:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:48:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:48:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:48:10', 'DoVa_Co2', '0']
['2021-5-4 5:48:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:48:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:48:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:48:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:48:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:49:10', 'fKWhCounter', '3337.20483398438']
['2021-5-4 5:49:10', 'fActPhLevelMixTank1', '5.60679960250854']
['2021-5-4 5:49:10', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 5:49:10', 'fActPhLevelMixTank2', '3.85235142707825']
['2021-5-4 5:49:10', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 5:49:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:49:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:49:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:49:10', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 5:49:10', 'fActCo2ValMemo', '781']
['2021-5-4 5:49:10', 'fActWaterLevelMixTank1', '284.87890625']
['2021-5-4 5:49:10', 'fActWaterLevelMixTank2', '290.528686523438']
['2021-5-4 5:49:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:49:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:49:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:49:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:49:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:49:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:49:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:49:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:49:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:49:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:49:10', 'DoVa_Co2', '0']
['2021-5-4 5:49:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:49:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:49:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:49:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:49:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:50:10', 'fKWhCounter', '3337.40502929688']
['2021-5-4 5:50:10', 'fActPhLevelMixTank1', '5.61534452438354']
['2021-5-4 5:50:10', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 5:50:10', 'fActPhLevelMixTank2', '3.86114072799683']
['2021-5-4 5:50:10', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 5:50:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:50:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:50:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:50:10', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 5:50:10', 'fActCo2ValMemo', '779']
['2021-5-4 5:50:10', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 5:50:10', 'fActWaterLevelMixTank2', '290.990447998047']
['2021-5-4 5:50:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:50:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:50:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:50:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:50:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:50:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:50:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:50:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:50:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:50:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:50:10', 'DoVa_Co2', '0']
['2021-5-4 5:50:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:50:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:50:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:50:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:50:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:51:10', 'fKWhCounter', '3337.50512695313']
['2021-5-4 5:51:10', 'fActPhLevelMixTank1', '5.61217069625854']
['2021-5-4 5:51:10', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 5:51:10', 'fActPhLevelMixTank2', '3.85552549362183']
['2021-5-4 5:51:10', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 5:51:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:51:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:51:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:51:10', 'fActRhValMemo', '52']
['2021-5-4 5:51:10', 'fActCo2ValMemo', '777']
['2021-5-4 5:51:10', 'fActWaterLevelMixTank1', '285.286346435547']
['2021-5-4 5:51:10', 'fActWaterLevelMixTank2', '290.827453613281']
['2021-5-4 5:51:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:51:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:51:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:51:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:51:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:51:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:51:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:51:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:51:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:51:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:51:10', 'DoVa_Co2', '0']
['2021-5-4 5:51:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:51:10', 'DoVa_IrrigateLevel_4_MT1', '0']

['2021-5-4 5:51:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:51:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:51:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:52:10', 'fKWhCounter', '3337.60522460938']
['2021-5-4 5:52:10', 'fActPhLevelMixTank1', '5.61632108688354']
['2021-5-4 5:52:10', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 5:52:10', 'fActPhLevelMixTank2', '3.85528111457825']
['2021-5-4 5:52:10', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 5:52:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:52:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:52:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:52:10', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 5:52:10', 'fActCo2ValMemo', '775']
['2021-5-4 5:52:10', 'fActWaterLevelMixTank1', '285.911071777344']
['2021-5-4 5:52:10', 'fActWaterLevelMixTank2', '291.262054443359']
['2021-5-4 5:52:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:52:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:52:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:52:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:52:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:52:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:52:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:52:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:52:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:52:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:52:10', 'DoVa_Co2', '0']
['2021-5-4 5:52:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:52:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:52:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:52:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:52:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:53:10', 'fKWhCounter', '3337.80541992188']
['2021-5-4 5:53:10', 'fActPhLevelMixTank1', '5.61094999313354']
['2021-5-4 5:53:10', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 5:53:10', 'fActPhLevelMixTank2', '3.86089658737183']
['2021-5-4 5:53:10', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 5:53:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:53:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:53:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:53:10', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 5:53:10', 'fActCo2ValMemo', '773']
['2021-5-4 5:53:10', 'fActWaterLevelMixTank1', '286.725952148438']
['2021-5-4 5:53:10', 'fActWaterLevelMixTank2', '291.262054443359']
['2021-5-4 5:53:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:53:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:53:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:53:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:53:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:53:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:53:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:53:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:53:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:53:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:53:10', 'DoVa_Co2', '0']
['2021-5-4 5:53:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:53:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:53:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:53:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:53:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:54:10', 'fKWhCounter', '3337.90551757813']
['2021-5-4 5:54:10', 'fActPhLevelMixTank1', '5.61363554000854']
['2021-5-4 5:54:10', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 5:54:10', 'fActPhLevelMixTank2', '3.85650205612183']
['2021-5-4 5:54:10', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 5:54:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:54:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:54:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:54:10', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 5:54:10', 'fActCo2ValMemo', '773']
['2021-5-4 5:54:10', 'fActWaterLevelMixTank1', '286.99755859375']
['2021-5-4 5:54:10', 'fActWaterLevelMixTank2', '291.859649658203']
['2021-5-4 5:54:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:54:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:54:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:54:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:54:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:54:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:54:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:54:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:54:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:54:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:54:10', 'DoVa_Co2', '0']
['2021-5-4 5:54:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:54:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:54:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:54:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:54:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:55:10', 'fKWhCounter', '3338.00561523438']
['2021-5-4 5:55:10', 'fActPhLevelMixTank1', '5.61387968063354']
['2021-5-4 5:55:10', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 5:55:10', 'fActPhLevelMixTank2', '3.85845518112183']
['2021-5-4 5:55:10', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 5:55:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:55:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:55:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:55:10', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 5:55:10', 'fActCo2ValMemo', '773']
['2021-5-4 5:55:10', 'fActWaterLevelMixTank1', '287.350677490234']
['2021-5-4 5:55:10', 'fActWaterLevelMixTank2', '291.968292236328']
['2021-5-4 5:55:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:55:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:55:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:55:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:55:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:55:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:55:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:55:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:55:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:55:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:55:10', 'DoVa_Co2', '0']
['2021-5-4 5:55:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:55:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:55:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:55:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:55:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:56:10', 'fKWhCounter', '3338.20581054688']
['2021-5-4 5:56:10', 'fActPhLevelMixTank1', '5.6243782043457']
['2021-5-4 5:56:10', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 5:56:10', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 5:56:10', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 5:56:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:56:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:56:10', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 5:56:10', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 5:56:10', 'fActCo2ValMemo', '772']
['2021-5-4 5:56:10', 'fActWaterLevelMixTank1', '286.7802734375']
['2021-5-4 5:56:10', 'fActWaterLevelMixTank2', '292.267059326172']
['2021-5-4 5:56:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:56:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:56:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:56:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:56:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:56:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:56:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:56:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:56:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:56:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:56:10', 'DoVa_Co2', '0']
['2021-5-4 5:56:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:56:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:56:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:56:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 5:56:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:56:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:57:10', 'fKWhCounter', '3338.30590820313']
['2021-5-4 5:57:10', 'fActPhLevelMixTank1', '5.6273078918457']
['2021-5-4 5:57:10', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 5:57:10', 'fActPhLevelMixTank2', '3.85747861862183']
['2021-5-4 5:57:10', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 5:57:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:57:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:57:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:57:10', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 5:57:10', 'fActCo2ValMemo', '773']
['2021-5-4 5:57:10', 'fActWaterLevelMixTank1', '287.513671875']
['2021-5-4 5:57:10', 'fActWaterLevelMixTank2', '292.511535644531']
['2021-5-4 5:57:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:57:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:57:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:57:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:57:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:57:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:57:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:57:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:57:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:57:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:57:10', 'DoVa_Co2', '0']
['2021-5-4 5:57:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:57:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:57:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:57:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:57:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:58:10', 'fKWhCounter', '3338.50610351563']
['2021-5-4 5:58:10', 'fActPhLevelMixTank1', '5.6290168762207']
['2021-5-4 5:58:10', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 5:58:10', 'fActPhLevelMixTank2', '3.85845518112183']
['2021-5-4 5:58:10', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 5:58:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:58:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:58:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:58:10', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 5:58:10', 'fActCo2ValMemo', '770']
['2021-5-4 5:58:10', 'fActWaterLevelMixTank1', '287.921081542969']
['2021-5-4 5:58:10', 'fActWaterLevelMixTank2', '291.859649658203']
['2021-5-4 5:58:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:58:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:58:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:58:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:58:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:58:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:58:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:58:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:58:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:58:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:58:10', 'DoVa_Co2', '0']
['2021-5-4 5:58:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:58:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:58:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:58:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:58:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 5:59:10', 'fKWhCounter', '3338.60620117188']
['2021-5-4 5:59:10', 'fActPhLevelMixTank1', '5.63292360305786']
['2021-5-4 5:59:10', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 5:59:10', 'fActPhLevelMixTank2', '3.86114072799683']
['2021-5-4 5:59:10', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 5:59:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 5:59:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 5:59:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 5:59:10', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 5:59:10', 'fActCo2ValMemo', '768']
['2021-5-4 5:59:10', 'fActWaterLevelMixTank1', '286.943237304688']
['2021-5-4 5:59:10', 'fActWaterLevelMixTank2', '292.484375']
['2021-5-4 5:59:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 5:59:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 5:59:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 5:59:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 5:59:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 5:59:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 5:59:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 5:59:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 5:59:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 5:59:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 5:59:10', 'DoVa_Co2', '0']
['2021-5-4 5:59:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 5:59:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 5:59:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 5:59:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 5:59:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:0:10', 'fKWhCounter', '3338.70629882813']
['2021-5-4 6:0:10', 'fActPhLevelMixTank1', '5.63512086868286']
['2021-5-4 6:0:10', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 6:0:10', 'fActPhLevelMixTank2', '3.86333823204041']
['2021-5-4 6:0:10', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 6:0:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:0:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:0:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:0:10', 'fActRhValMemo', '51.5']
['2021-5-4 6:0:10', 'fActCo2ValMemo', '768']
['2021-5-4 6:0:10', 'fActWaterLevelMixTank1', '288.763122558594']
['2021-5-4 6:0:10', 'fActWaterLevelMixTank2', '292.538696289063']
['2021-5-4 6:0:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:0:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:0:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:0:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:0:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:0:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:0:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:0:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:0:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:0:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:0:10', 'DoVa_Co2', '0']
['2021-5-4 6:0:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:0:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:0:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:0:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:0:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:1:10', 'fKWhCounter', '3338.90649414063']
['2021-5-4 6:1:10', 'fActPhLevelMixTank1', '5.6265754699707']
['2021-5-4 6:1:10', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 6:1:10', 'fActPhLevelMixTank2', '3.86040830612183']
['2021-5-4 6:1:10', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 6:1:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:1:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:1:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:1:10', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 6:1:10', 'fActCo2ValMemo', '766']
['2021-5-4 6:1:10', 'fActWaterLevelMixTank1', '288.545837402344']
['2021-5-4 6:1:10', 'fActWaterLevelMixTank2', '293.244903564453']
['2021-5-4 6:1:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:1:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:1:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:1:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:1:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:1:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:1:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:1:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:1:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:1:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:1:10', 'DoVa_Co2', '0']
['2021-5-4 6:1:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:1:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:1:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:1:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:1:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:2:10', 'fKWhCounter', '3339.00659179688']
['2021-5-4 6:2:10', 'fActPhLevelMixTank1', '5.6253547668457']
['2021-5-4 6:2:10', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 6:2:10', 'fActPhLevelMixTank2', '3.86333823204041']
['2021-5-4 6:2:10', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 6:2:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:2:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:2:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:2:10', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:2:10', 'fActCo2ValMemo', '763']
['2021-5-4 6:2:10', 'fActWaterLevelMixTank1', '288.926086425781']
['2021-5-4 6:2:10', 'fActWaterLevelMixTank2', '293.163421630859']
['2021-5-4 6:2:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:2:10', 'DoPu_AddEcAMixTank_1', '0']

['2021-5-4 6:2:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:2:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:2:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:2:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:2:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:2:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:2:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:2:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:2:10', 'DoVa_Co2', '0']
['2021-5-4 6:2:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:2:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:2:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:2:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:2:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:3:10', 'fKWhCounter', '3339.10668945313']
['2021-5-4 6:3:10', 'fActPhLevelMixTank1', '5.6319465637207']
['2021-5-4 6:3:10', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 6:3:10', 'fActPhLevelMixTank2', '3.86870932579041']
['2021-5-4 6:3:10', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 6:3:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:3:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:3:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:3:10', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:3:10', 'fActCo2ValMemo', '759']
['2021-5-4 6:3:10', 'fActWaterLevelMixTank1', '287.921081542969']
['2021-5-4 6:3:10', 'fActWaterLevelMixTank2', '293.353576660156']
['2021-5-4 6:3:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:3:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:3:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:3:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:3:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:3:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:3:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:3:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:3:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:3:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:3:10', 'DoVa_Co2', '0']
['2021-5-4 6:3:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:3:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:3:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:3:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:3:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:4:10', 'fKWhCounter', '3339.30688476563']
['2021-5-4 6:4:10', 'fActPhLevelMixTank1', '5.64146852493286']
['2021-5-4 6:4:10', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 6:4:10', 'fActPhLevelMixTank2', '3.86211729049683']
['2021-5-4 6:4:10', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 6:4:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:4:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:4:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:4:10', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 6:4:10', 'fActCo2ValMemo', '758']
['2021-5-4 6:4:10', 'fActWaterLevelMixTank1', '289.143402099609']
['2021-5-4 6:4:10', 'fActWaterLevelMixTank2', '293.679504394531']
['2021-5-4 6:4:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:4:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:4:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:4:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:4:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:4:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:4:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:4:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:4:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:4:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:4:10', 'DoVa_Co2', '0']
['2021-5-4 6:4:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:4:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:4:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:4:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:4:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:5:10', 'fKWhCounter', '3339.40698242188']
['2021-5-4 6:5:10', 'fActPhLevelMixTank1', '5.64195680618286']
['2021-5-4 6:5:10', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 6:5:10', 'fActPhLevelMixTank2', '3.86480307579041']
['2021-5-4 6:5:10', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 6:5:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:5:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:5:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:5:10', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 6:5:10', 'fActCo2ValMemo', '755']
['2021-5-4 6:5:10', 'fActWaterLevelMixTank1', '289.550842285156']
['2021-5-4 6:5:10', 'fActWaterLevelMixTank2', '293.679504394531']
['2021-5-4 6:5:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:5:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:5:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:5:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:5:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:5:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:5:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:5:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:5:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:5:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:5:10', 'DoVa_Co2', '0']
['2021-5-4 6:5:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:5:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:5:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:5:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:5:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:6:10', 'fKWhCounter', '3339.60717773438']
['2021-5-4 6:6:10', 'fActPhLevelMixTank1', '5.64390993118286']
['2021-5-4 6:6:10', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 6:6:10', 'fActPhLevelMixTank2', '3.86870932579041']
['2021-5-4 6:6:10', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 6:6:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:6:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:6:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:6:10', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 6:6:10', 'fActCo2ValMemo', '758']
['2021-5-4 6:6:10', 'fActWaterLevelMixTank1', '289.170562744141']
['2021-5-4 6:6:10', 'fActWaterLevelMixTank2', '293.788177490234']
['2021-5-4 6:6:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:6:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:6:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:6:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:6:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:6:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:6:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:6:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:6:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:6:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:6:10', 'DoVa_Co2', '0']
['2021-5-4 6:6:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:6:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:6:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:6:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:6:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:7:10', 'fKWhCounter', '3339.70727539063']
['2021-5-4 6:7:10', 'fActPhLevelMixTank1', '5.63951539993286']
['2021-5-4 6:7:10', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 6:7:10', 'fActPhLevelMixTank2', '3.86675620079041']
['2021-5-4 6:7:10', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 6:7:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:7:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:7:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:7:10', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:7:10', 'fActCo2ValMemo', '760']
['2021-5-4 6:7:10', 'fActWaterLevelMixTank1', '290.202728271484']
['2021-5-4 6:7:10', 'fActWaterLevelMixTank2', '294.304260253906']
['2021-5-4 6:7:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:7:10', 'DoPu_AddEcAMixTank_1', '0']

['2021-5-4 6:7:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:7:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:7:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:7:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:7:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:7:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:7:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:7:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:7:10', 'DoVa_Co2', '0']
['2021-5-4 6:7:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:7:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:7:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:7:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:7:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:8:10', 'fKWhCounter', '3339.80737304688']
['2021-5-4 6:8:10', 'fActPhLevelMixTank1', '5.64244508743286']
['2021-5-4 6:8:10', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 6:8:10', 'fActPhLevelMixTank2', '3.87041831016541']
['2021-5-4 6:8:10', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 6:8:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:8:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:8:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:8:10', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:8:10', 'fActCo2ValMemo', '760']
['2021-5-4 6:8:10', 'fActWaterLevelMixTank1', '291.017608642578']
['2021-5-4 6:8:10', 'fActWaterLevelMixTank2', '294.793182373047']
['2021-5-4 6:8:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:8:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:8:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:8:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:8:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:8:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:8:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:8:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:8:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:8:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:8:10', 'DoVa_Co2', '0']
['2021-5-4 6:8:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:8:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:8:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:8:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:8:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:9:10', 'fKWhCounter', '3340.00756835938']
['2021-5-4 6:9:10', 'fActPhLevelMixTank1', '5.64854907989502']
['2021-5-4 6:9:10', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 6:9:10', 'fActPhLevelMixTank2', '3.86577963829041']
['2021-5-4 6:9:10', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 6:9:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:9:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:9:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:9:10', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:9:10', 'fActCo2ValMemo', '758']
['2021-5-4 6:9:10', 'fActWaterLevelMixTank1', '290.691650390625']
['2021-5-4 6:9:10', 'fActWaterLevelMixTank2', '294.956146240234']
['2021-5-4 6:9:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:9:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:9:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:9:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:9:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:9:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:9:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:9:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:9:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:9:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:9:10', 'DoVa_Co2', '0']
['2021-5-4 6:9:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:9:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:9:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:9:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:9:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:10:10', 'fKWhCounter', '3340.10766601563']
['2021-5-4 6:10:10', 'fActPhLevelMixTank1', '5.64928150177002']
['2021-5-4 6:10:10', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 6:10:10', 'fActPhLevelMixTank2', '3.87139511108398']
['2021-5-4 6:10:10', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 6:10:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:10:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:10:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:10:10', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 6:10:10', 'fActCo2ValMemo', '756']
['2021-5-4 6:10:10', 'fActWaterLevelMixTank1', '290.854614257813']
['2021-5-4 6:10:10', 'fActWaterLevelMixTank2', '294.711669921875']
['2021-5-4 6:10:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:10:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:10:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:10:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:10:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:10:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:10:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:10:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:10:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:10:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:10:10', 'DoVa_Co2', '0']
['2021-5-4 6:10:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:10:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:10:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:10:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:10:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:11:10', 'fKWhCounter', '3340.20776367188']
['2021-5-4 6:11:10', 'fActPhLevelMixTank1', '5.65514087677002']
['2021-5-4 6:11:10', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 6:11:10', 'fActPhLevelMixTank2', '3.87261581420898']
['2021-5-4 6:11:10', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 6:11:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:11:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:11:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:11:10', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 6:11:10', 'fActCo2ValMemo', '756']
['2021-5-4 6:11:10', 'fActWaterLevelMixTank1', '289.958282470703']
['2021-5-4 6:11:10', 'fActWaterLevelMixTank2', '295.173431396484']
['2021-5-4 6:11:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:11:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:11:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:11:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:11:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:11:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:11:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:11:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:11:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:11:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:11:10', 'DoVa_Co2', '0']
['2021-5-4 6:11:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:11:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:11:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:11:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:11:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:12:10', 'fKWhCounter', '3340.40795898438']
['2021-5-4 6:12:10', 'fActPhLevelMixTank1', '5.65416431427002']
['2021-5-4 6:12:10', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 6:12:10', 'fActPhLevelMixTank2', '3.87432479858398']
['2021-5-4 6:12:10', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 6:12:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:12:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:12:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:12:10', 'fActRhValMemo', '51.7999992370605']

['2021-5-4 6:12:10', 'fActCo2ValMemo', '758']
['2021-5-4 6:12:10', 'fActWaterLevelMixTank1', '291.316375732422']
['2021-5-4 6:12:10', 'fActWaterLevelMixTank2', '295.064788818359']
['2021-5-4 6:12:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:12:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:12:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:12:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:12:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:12:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:12:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:12:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:12:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:12:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:12:10', 'DoVa_Co2', '0']
['2021-5-4 6:12:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:12:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:12:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:12:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:12:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:13:10', 'fKWhCounter', '3340.50805664063']
['2021-5-4 6:13:10', 'fActPhLevelMixTank1', '5.65733814239502']
['2021-5-4 6:13:10', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 6:13:10', 'fActPhLevelMixTank2', '3.87041831016541']
['2021-5-4 6:13:10', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 6:13:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:13:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:13:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:13:10', 'fActRhValMemo', '51.5']
['2021-5-4 6:13:10', 'fActCo2ValMemo', '757']
['2021-5-4 6:13:10', 'fActWaterLevelMixTank1', '290.80029296875']
['2021-5-4 6:13:10', 'fActWaterLevelMixTank2', '295.146270751953']
['2021-5-4 6:13:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:13:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:13:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:13:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:13:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:13:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:13:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:13:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:13:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:13:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:13:10', 'DoVa_Co2', '0']
['2021-5-4 6:13:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:13:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:13:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:13:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:13:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:14:10', 'fKWhCounter', '3340.70825195313']
['2021-5-4 6:14:10', 'fActPhLevelMixTank1', '5.65489673614502']
['2021-5-4 6:14:10', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 6:14:10', 'fActPhLevelMixTank2', '3.87285995483398']
['2021-5-4 6:14:10', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 6:14:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:14:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:14:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:14:10', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 6:14:10', 'fActCo2ValMemo', '758']
['2021-5-4 6:14:10', 'fActWaterLevelMixTank1', '291.425048828125']
['2021-5-4 6:14:10', 'fActWaterLevelMixTank2', '295.580871582031']
['2021-5-4 6:14:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:14:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:14:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:14:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:14:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:14:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:14:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:14:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:14:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:14:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:14:10', 'DoVa_Co2', '0']
['2021-5-4 6:14:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:14:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:14:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:14:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:14:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:15:10', 'fKWhCounter', '3340.80834960938']
['2021-5-4 6:15:10', 'fActPhLevelMixTank1', '5.65782642364502']
['2021-5-4 6:15:10', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 6:15:10', 'fActPhLevelMixTank2', '3.87359237670898']
['2021-5-4 6:15:10', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 6:15:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:15:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:15:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:15:10', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 6:15:10', 'fActCo2ValMemo', '755']
['2021-5-4 6:15:10', 'fActWaterLevelMixTank1', '290.420043945313']
['2021-5-4 6:15:10', 'fActWaterLevelMixTank2', '295.852508544922']
['2021-5-4 6:15:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:15:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:15:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:15:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:15:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:15:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:15:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:15:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:15:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:15:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:15:10', 'DoVa_Co2', '0']
['2021-5-4 6:15:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:15:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:15:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:15:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:15:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:16:10', 'fKWhCounter', '3340.90844726563']
['2021-5-4 6:16:10', 'fActPhLevelMixTank1', '5.66051197052002']
['2021-5-4 6:16:10', 'fActEcLevelMixTank1', '2031.76977539063']
['2021-5-4 6:16:10', 'fActPhLevelMixTank2', '3.87383651733398']
['2021-5-4 6:16:10', 'fActEcLevelMixTank2', '1042.81750488281']
['2021-5-4 6:16:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:16:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:16:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:16:10', 'fActRhValMemo', '51.5']
['2021-5-4 6:16:10', 'fActCo2ValMemo', '752']
['2021-5-4 6:16:10', 'fActWaterLevelMixTank1', '292.430053710938']
['2021-5-4 6:16:10', 'fActWaterLevelMixTank2', '296.911834716797']
['2021-5-4 6:16:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:16:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:16:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:16:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:16:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:16:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:16:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:16:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:16:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:16:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:16:10', 'DoVa_Co2', '0']
['2021-5-4 6:16:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:16:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:16:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:16:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:16:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:17:10', 'fKWhCounter', '3341.10864257813']
['2021-5-4 6:17:10', 'fActPhLevelMixTank1', '5.66197681427002']
['2021-5-4 6:17:10', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 6:17:10', 'fActPhLevelMixTank2', '3.87359237670898']
['2021-5-4 6:17:10', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 6:17:10', 'fTaktCounterUpperLevel', '0']

['2021-5-4 6:17:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:17:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:17:10', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:17:10', 'fActCo2ValMemo', '752']
['2021-5-4 6:17:10', 'fActWaterLevelMixTank1', '292.484375']
['2021-5-4 6:17:10', 'fActWaterLevelMixTank2', '296.748870849609']
['2021-5-4 6:17:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:17:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:17:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:17:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:17:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:17:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:17:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:17:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:17:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:17:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:17:10', 'DoVa_Co2', '0']
['2021-5-4 6:17:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:17:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:17:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:17:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:17:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:18:10', 'fKWhCounter', '3341.20874023438']
['2021-5-4 6:18:10', 'fActPhLevelMixTank1', '5.66734838485718']
['2021-5-4 6:18:10', 'fActEcLevelMixTank1', '2031.92236328125']
['2021-5-4 6:18:10', 'fActPhLevelMixTank2', '3.87652206420898']
['2021-5-4 6:18:10', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 6:18:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:18:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:18:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:18:10', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 6:18:10', 'fActCo2ValMemo', '753']
['2021-5-4 6:18:10', 'fActWaterLevelMixTank1', '292.810333251953']
['2021-5-4 6:18:10', 'fActWaterLevelMixTank2', '296.911834716797']
['2021-5-4 6:18:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:18:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:18:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:18:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:18:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:18:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:18:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:18:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:18:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:18:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:18:10', 'DoVa_Co2', '0']
['2021-5-4 6:18:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:18:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:18:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:18:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:18:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:19:10', 'fKWhCounter', '3341.30883789063']
['2021-5-4 6:19:10', 'fActPhLevelMixTank1', '5.66930150985718']
['2021-5-4 6:19:10', 'fActEcLevelMixTank1', '2031.46459960938']
['2021-5-4 6:19:10', 'fActPhLevelMixTank2', '3.87652206420898']
['2021-5-4 6:19:10', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 6:19:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:19:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:19:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:19:10', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:19:10', 'fActCo2ValMemo', '750']
['2021-5-4 6:19:10', 'fActWaterLevelMixTank1', '292.484375']
['2021-5-4 6:19:10', 'fActWaterLevelMixTank2', '297.047637939453']
['2021-5-4 6:19:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:19:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:19:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:19:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:19:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:19:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:19:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:19:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:19:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:19:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:19:10', 'DoVa_Co2', '0']
['2021-5-4 6:19:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:19:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:19:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:19:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:19:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:20:10', 'fKWhCounter', '3341.50903320313']
['2021-5-4 6:20:10', 'fActPhLevelMixTank1', '5.66856908798218']
['2021-5-4 6:20:10', 'fActEcLevelMixTank1', '2029.78601074219']
['2021-5-4 6:20:10', 'fActPhLevelMixTank2', '3.87432479858398']
['2021-5-4 6:20:10', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 6:20:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:20:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:20:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:20:10', 'fActRhValMemo', '51.5']
['2021-5-4 6:20:10', 'fActCo2ValMemo', '750']
['2021-5-4 6:20:10', 'fActWaterLevelMixTank1', '292.565856933594']
['2021-5-4 6:20:10', 'fActWaterLevelMixTank2', '296.911834716797']
['2021-5-4 6:20:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:20:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:20:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:20:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:20:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:20:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:20:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:20:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:20:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:20:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:20:10', 'DoVa_Co2', '0']
['2021-5-4 6:20:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:20:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:20:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:20:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:20:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:21:10', 'fKWhCounter', '3341.60913085938']
['2021-5-4 6:21:10', 'fActPhLevelMixTank1', '5.66783666610718']
['2021-5-4 6:21:10', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 6:21:10', 'fActPhLevelMixTank2', '3.87896370887756']
['2021-5-4 6:21:10', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 6:21:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:21:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:21:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:21:10', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 6:21:10', 'fActCo2ValMemo', '752']
['2021-5-4 6:21:10', 'fActWaterLevelMixTank1', '292.185577392578']
['2021-5-4 6:21:10', 'fActWaterLevelMixTank2', '296.857513427734']
['2021-5-4 6:21:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:21:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:21:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:21:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:21:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:21:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:21:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:21:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:21:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:21:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:21:10', 'DoVa_Co2', '0']
['2021-5-4 6:21:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:21:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:21:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:21:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:21:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:22:10', 'fKWhCounter', '3341.80932617188']

['2021-5-4 6:22:10', 'fActPhLevelMixTank1', '5.67076635360718']
['2021-5-4 6:22:10', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 6:22:10', 'fActPhLevelMixTank2', '3.87749862670898']
['2021-5-4 6:22:10', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 6:22:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:22:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:22:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:22:10', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:22:10', 'fActCo2ValMemo', '753']
['2021-5-4 6:22:10', 'fActWaterLevelMixTank1', '292.620178222656']
['2021-5-4 6:22:10', 'fActWaterLevelMixTank2', '296.993316650391']
['2021-5-4 6:22:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:22:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:22:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:22:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:22:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:22:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:22:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:22:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:22:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:22:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:22:10', 'DoVa_Co2', '0']
['2021-5-4 6:22:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:22:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:22:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:22:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:22:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:23:11', 'fKWhCounter', '3341.90942382813']
['2021-5-4 6:23:11', 'fActPhLevelMixTank1', '5.67369604110718']
['2021-5-4 6:23:11', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 6:23:11', 'fActPhLevelMixTank2', '3.87432479858398']
['2021-5-4 6:23:11', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 6:23:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:23:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:23:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:23:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:23:11', 'fActCo2ValMemo', '765']
['2021-5-4 6:23:11', 'fActWaterLevelMixTank1', '293.462219238281']
['2021-5-4 6:23:11', 'fActWaterLevelMixTank2', '297.455078125']
['2021-5-4 6:23:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:23:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:23:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:23:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:23:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:23:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:23:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:23:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:23:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:23:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:23:11', 'DoVa_Co2', '0']
['2021-5-4 6:23:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:23:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:23:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:23:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:23:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:24:10', 'fKWhCounter', '3342.00952148438']
['2021-5-4 6:24:10', 'fActPhLevelMixTank1', '5.65392017364502']
['2021-5-4 6:24:10', 'fActEcLevelMixTank1', '2064.11938476563']
['2021-5-4 6:24:10', 'fActPhLevelMixTank2', '3.84795689582825']
['2021-5-4 6:24:10', 'fActEcLevelMixTank2', '1051.82043457031']
['2021-5-4 6:24:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:24:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:24:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:24:10', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:24:10', 'fActCo2ValMemo', '777']
['2021-5-4 6:24:10', 'fActWaterLevelMixTank1', '289.360687255859']
['2021-5-4 6:24:10', 'fActWaterLevelMixTank2', '313.861145019531']
['2021-5-4 6:24:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:24:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:24:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:24:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:24:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:24:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:24:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:24:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:24:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:24:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:24:11', 'DoVa_Co2', '0']
['2021-5-4 6:24:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:24:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:24:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:24:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:24:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:25:10', 'fKWhCounter', '3342.20971679688']
['2021-5-4 6:25:10', 'fActPhLevelMixTank1', '5.56675910949707']
['2021-5-4 6:25:10', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 6:25:10', 'fActPhLevelMixTank2', '3.79204678535461']
['2021-5-4 6:25:10', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 6:25:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:25:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:25:10', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:25:10', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 6:25:10', 'fActCo2ValMemo', '789']
['2021-5-4 6:25:10', 'fActWaterLevelMixTank1', '286.888916015625']
['2021-5-4 6:25:10', 'fActWaterLevelMixTank2', '308.591644287109']
['2021-5-4 6:25:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:25:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:25:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:25:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:25:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:25:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:25:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:25:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:25:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:25:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:25:10', 'DoVa_Co2', '0']
['2021-5-4 6:25:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:25:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:25:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:25:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:25:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:26:10', 'fKWhCounter', '3342.40991210938']
['2021-5-4 6:26:10', 'fActPhLevelMixTank1', '5.56651496887207']
['2021-5-4 6:26:10', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 6:26:10', 'fActPhLevelMixTank2', '3.79473257064819']
['2021-5-4 6:26:10', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 6:26:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:26:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:26:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:26:10', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 6:26:10', 'fActCo2ValMemo', '801']
['2021-5-4 6:26:10', 'fActWaterLevelMixTank1', '280.478607177734']
['2021-5-4 6:26:10', 'fActWaterLevelMixTank2', '265.484985351563']
['2021-5-4 6:26:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:26:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:26:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:26:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:26:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:26:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:26:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:26:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:26:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:26:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:26:10', 'DoVa_Co2', '0']
['2021-5-4 6:26:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:26:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:26:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:26:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_3_Red', '0']

['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:26:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:27:11', 'fKWhCounter', '3342.51000976563']
['2021-5-4 6:27:11', 'fActPhLevelMixTank1', '5.56700325012207']
['2021-5-4 6:27:11', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 6:27:11', 'fActPhLevelMixTank2', '3.80449843406677']
['2021-5-4 6:27:11', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 6:27:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:27:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:27:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:27:11', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 6:27:11', 'fActCo2ValMemo', '812']
['2021-5-4 6:27:11', 'fActWaterLevelMixTank1', '279.690887451172']
['2021-5-4 6:27:11', 'fActWaterLevelMixTank2', '275.3720703125']
['2021-5-4 6:27:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:27:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:27:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:27:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:27:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:27:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:27:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:27:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:27:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:27:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:27:11', 'DoVa_Co2', '0']
['2021-5-4 6:27:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:27:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:27:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:27:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:27:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:28:10', 'fKWhCounter', '3342.71020507813']
['2021-5-4 6:28:10', 'fActPhLevelMixTank1', '5.57042169570923']
['2021-5-4 6:28:10', 'fActEcLevelMixTank1', '2017.12084960938']
['2021-5-4 6:28:10', 'fActPhLevelMixTank2', '3.80425429344177']
['2021-5-4 6:28:10', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 6:28:10', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:28:10', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:28:10', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:28:10', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 6:28:10', 'fActCo2ValMemo', '821']
['2021-5-4 6:28:10', 'fActWaterLevelMixTank1', '277.979675292969']
['2021-5-4 6:28:10', 'fActWaterLevelMixTank2', '285.476470947266']
['2021-5-4 6:28:10', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:28:10', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:28:10', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:28:10', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:28:10', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:28:10', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:28:10', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:28:10', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:28:10', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:28:10', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:28:10', 'DoVa_Co2', '0']
['2021-5-4 6:28:10', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:28:10', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:28:10', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:28:10', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:28:10', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:29:11', 'fKWhCounter', '3342.91040039063']
['2021-5-4 6:29:11', 'fActPhLevelMixTank1', '5.56944465637207']
['2021-5-4 6:29:11', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 6:29:11', 'fActPhLevelMixTank2', '3.80401015281677']
['2021-5-4 6:29:11', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 6:29:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:29:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:29:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:29:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 6:29:11', 'fActCo2ValMemo', '828']
['2021-5-4 6:29:11', 'fActWaterLevelMixTank1', '279.066162109375']
['2021-5-4 6:29:11', 'fActWaterLevelMixTank2', '286.291351318359']
['2021-5-4 6:29:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:29:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:29:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:29:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:29:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:29:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:29:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:29:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:29:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:29:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:29:11', 'DoVa_Co2', '0']
['2021-5-4 6:29:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:29:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:29:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:29:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:29:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:30:11', 'fKWhCounter', '3343.01049804688']
['2021-5-4 6:30:11', 'fActPhLevelMixTank1', '5.57359552383423']
['2021-5-4 6:30:11', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 6:30:11', 'fActPhLevelMixTank2', '3.84991002082825']
['2021-5-4 6:30:11', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 6:30:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:30:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:30:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:30:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:30:11', 'fActCo2ValMemo', '835']
['2021-5-4 6:30:11', 'fActWaterLevelMixTank1', '277.898193359375']
['2021-5-4 6:30:11', 'fActWaterLevelMixTank2', '287.459320068359']
['2021-5-4 6:30:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:30:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:30:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:30:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:30:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:30:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:30:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:30:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:30:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:30:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:30:11', 'DoVa_Co2', '0']
['2021-5-4 6:30:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:30:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:30:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:30:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:30:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:31:11', 'fKWhCounter', '3343.21069335938']
['2021-5-4 6:31:11', 'fActPhLevelMixTank1', '5.57823419570923']
['2021-5-4 6:31:11', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 6:31:11', 'fActPhLevelMixTank2', '3.84575939178467']
['2021-5-4 6:31:11', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 6:31:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:31:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:31:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:31:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:31:11', 'fActCo2ValMemo', '839']
['2021-5-4 6:31:11', 'fActWaterLevelMixTank1', '276.268432617188']
['2021-5-4 6:31:11', 'fActWaterLevelMixTank2', '287.758117675781']
['2021-5-4 6:31:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:31:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:31:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:31:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:31:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:31:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:31:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:31:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:31:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:31:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:31:11', 'DoVa_Co2', '0']
['2021-5-4 6:31:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:31:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:31:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:31:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_4_Fred', '0']

['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:31:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:32:11', 'fKWhCounter', '3343.31079101563']
['2021-5-4 6:32:11', 'fActPhLevelMixTank1', '5.57896661758423']
['2021-5-4 6:32:11', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 6:32:11', 'fActPhLevelMixTank2', '3.83965563774109']
['2021-5-4 6:32:11', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 6:32:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:32:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:32:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:32:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:32:11', 'fActCo2ValMemo', '842']
['2021-5-4 6:32:11', 'fActWaterLevelMixTank1', '277.626556396484']
['2021-5-4 6:32:11', 'fActWaterLevelMixTank2', '287.377838134766']
['2021-5-4 6:32:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:32:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:32:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:32:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:32:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:32:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:32:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:32:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:32:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:32:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:32:11', 'DoVa_Co2', '0']
['2021-5-4 6:32:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:32:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:32:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:32:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:32:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:33:11', 'fKWhCounter', '3343.41088867188']
['2021-5-4 6:33:11', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 6:33:11', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 6:33:11', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 6:33:11', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 6:33:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:33:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:33:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:33:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:33:11', 'fActCo2ValMemo', '843']
['2021-5-4 6:33:11', 'fActWaterLevelMixTank1', '277.409271240234']
['2021-5-4 6:33:11', 'fActWaterLevelMixTank2', '287.106231689453']
['2021-5-4 6:33:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:33:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:33:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:33:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:33:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:33:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:33:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:33:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:33:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:33:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:33:11', 'DoVa_Co2', '0']
['2021-5-4 6:33:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:33:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:33:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:33:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:33:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:34:11', 'fKWhCounter', '3343.61108398438']
['2021-5-4 6:34:11', 'fActPhLevelMixTank1', '5.58433771133423']
['2021-5-4 6:34:11', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 6:34:11', 'fActPhLevelMixTank2', '3.83819079399109']
['2021-5-4 6:34:11', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 6:34:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:34:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:34:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:34:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:34:11', 'fActCo2ValMemo', '845']
['2021-5-4 6:34:11', 'fActWaterLevelMixTank1', '276.540069580078']
['2021-5-4 6:34:11', 'fActWaterLevelMixTank2', '288.002593994141']
['2021-5-4 6:34:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:34:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:34:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:34:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:34:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:34:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:34:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:34:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:34:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:34:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:34:11', 'DoVa_Co2', '0']
['2021-5-4 6:34:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:34:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:34:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:34:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:34:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:35:11', 'fKWhCounter', '3343.71118164063']
['2021-5-4 6:35:11', 'fActPhLevelMixTank1', '5.58287286758423']
['2021-5-4 6:35:11', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 6:35:11', 'fActPhLevelMixTank2', '3.83428454399109']
['2021-5-4 6:35:11', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 6:35:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:35:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:35:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:35:11', 'fActRhValMemo', '51.5']
['2021-5-4 6:35:11', 'fActCo2ValMemo', '846']
['2021-5-4 6:35:11', 'fActWaterLevelMixTank1', '278.088317871094']
['2021-5-4 6:35:11', 'fActWaterLevelMixTank2', '287.242034912109']
['2021-5-4 6:35:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:35:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:35:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:35:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:35:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:35:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:35:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:35:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:35:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:35:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:35:11', 'DoVa_Co2', '0']
['2021-5-4 6:35:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:35:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:35:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:35:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:35:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:36:11', 'fKWhCounter', '3343.91137695313']
['2021-5-4 6:36:11', 'fActPhLevelMixTank1', '5.57603693008423']
['2021-5-4 6:36:11', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 6:36:11', 'fActPhLevelMixTank2', '3.84014415740967']
['2021-5-4 6:36:11', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 6:36:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:36:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:36:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:36:11', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 6:36:11', 'fActCo2ValMemo', '848']
['2021-5-4 6:36:11', 'fActWaterLevelMixTank1', '278.658721923828']
['2021-5-4 6:36:11', 'fActWaterLevelMixTank2', '287.486480712891']
['2021-5-4 6:36:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:36:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:36:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:36:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:36:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:36:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:36:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:36:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:36:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:36:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:36:11', 'DoVa_Co2', '0']
['2021-5-4 6:36:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:36:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:36:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:36:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_4_Fred', '0']

['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:36:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:37:11', 'fKWhCounter', '3344.01147460938']
['2021-5-4 6:37:11', 'fActPhLevelMixTank1', '5.57896661758423']
['2021-5-4 6:37:11', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 6:37:11', 'fActPhLevelMixTank2', '3.83648180961609']
['2021-5-4 6:37:11', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 6:37:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:37:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:37:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:37:11', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 6:37:11', 'fActCo2ValMemo', '849']
['2021-5-4 6:37:11', 'fActWaterLevelMixTank1', '278.604400634766']
['2021-5-4 6:37:11', 'fActWaterLevelMixTank2', '287.676635742188']
['2021-5-4 6:37:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:37:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:37:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:37:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:37:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:37:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:37:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:37:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:37:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:37:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:37:11', 'DoVa_Co2', '0']
['2021-5-4 6:37:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:37:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:37:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:37:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:37:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:38:11', 'fKWhCounter', '3344.11157226563']
['2021-5-4 6:38:11', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 6:38:11', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 6:38:11', 'fActPhLevelMixTank2', '3.83550524711609']
['2021-5-4 6:38:11', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 6:38:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:38:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:38:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:38:11', 'fActRhValMemo', '51.5']
['2021-5-4 6:38:11', 'fActCo2ValMemo', '853']
['2021-5-4 6:38:11', 'fActWaterLevelMixTank1', '279.256286621094']
['2021-5-4 6:38:11', 'fActWaterLevelMixTank2', '288.301361083984']
['2021-5-4 6:38:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:38:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:38:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:38:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:38:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:38:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:38:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:38:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:38:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:38:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:38:11', 'DoVa_Co2', '0']
['2021-5-4 6:38:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:38:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:38:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:38:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:38:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:39:11', 'fKWhCounter', '3344.31176757813']
['2021-5-4 6:39:11', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 6:39:11', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 6:39:11', 'fActPhLevelMixTank2', '3.83452868461609']
['2021-5-4 6:39:11', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 6:39:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:39:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:39:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:39:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:39:11', 'fActCo2ValMemo', '855']
['2021-5-4 6:39:11', 'fActWaterLevelMixTank1', '278.930358886719']
['2021-5-4 6:39:11', 'fActWaterLevelMixTank2', '288.600158691406']
['2021-5-4 6:39:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:39:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:39:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:39:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:39:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:39:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:39:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:39:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:39:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:39:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:39:11', 'DoVa_Co2', '0']
['2021-5-4 6:39:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:39:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:39:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:39:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:39:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:40:11', 'fKWhCounter', '3344.41186523438']
['2021-5-4 6:40:11', 'fActPhLevelMixTank1', '5.58238458633423']
['2021-5-4 6:40:11', 'fActEcLevelMixTank1', '2011.62756347656']
['2021-5-4 6:40:11', 'fActPhLevelMixTank2', '3.83574938774109']
['2021-5-4 6:40:11', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 6:40:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:40:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:40:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:40:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:40:11', 'fActCo2ValMemo', '856']
['2021-5-4 6:40:11', 'fActWaterLevelMixTank1', '280.804565429688']
['2021-5-4 6:40:11', 'fActWaterLevelMixTank2', '288.926086425781']
['2021-5-4 6:40:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:40:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:40:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:40:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:40:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:40:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:40:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:40:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:40:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:40:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:40:11', 'DoVa_Co2', '0']
['2021-5-4 6:40:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:40:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:40:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:40:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:40:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:41:11', 'fKWhCounter', '3344.51196289063']
['2021-5-4 6:41:11', 'fActPhLevelMixTank1', '5.58677959442139']
['2021-5-4 6:41:11', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 6:41:11', 'fActPhLevelMixTank2', '3.83770251274109']
['2021-5-4 6:41:11', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 6:41:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:41:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:41:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:41:11', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 6:41:11', 'fActCo2ValMemo', '854']
['2021-5-4 6:41:11', 'fActWaterLevelMixTank1', '281.049011230469']
['2021-5-4 6:41:11', 'fActWaterLevelMixTank2', '289.63232421875']
['2021-5-4 6:41:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:41:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:41:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:41:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:41:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:41:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:41:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:41:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:41:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:41:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:41:11', 'DoVa_Co2', '0']
['2021-5-4 6:41:11', 'DoVa_IrrigateLevel_3_MT1', '0']

['2021-5-4 6:41:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:41:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:41:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:41:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:42:11', 'fKWhCounter', '3344.71215820313']
['2021-5-4 6:42:11', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 6:42:11', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 6:42:11', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 6:42:11', 'fActEcLevelMixTank2', '1026.18493652344']
['2021-5-4 6:42:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:42:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:42:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:42:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:42:11', 'fActCo2ValMemo', '855']
['2021-5-4 6:42:11', 'fActWaterLevelMixTank1', '281.537933349609']
['2021-5-4 6:42:11', 'fActWaterLevelMixTank2', '289.360687255859']
['2021-5-4 6:42:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:42:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:42:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:42:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:42:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:42:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:42:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:42:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:42:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:42:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:42:11', 'DoVa_Co2', '0']
['2021-5-4 6:42:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:42:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:42:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:42:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:42:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:43:11', 'fKWhCounter', '3344.81225585938']
['2021-5-4 6:43:11', 'fActPhLevelMixTank1', '5.58555841445923']
['2021-5-4 6:43:11', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 6:43:11', 'fActPhLevelMixTank2', '3.83916735649109']
['2021-5-4 6:43:11', 'fActEcLevelMixTank2', '1026.18493652344']
['2021-5-4 6:43:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:43:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:43:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:43:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 6:43:11', 'fActCo2ValMemo', '855']
['2021-5-4 6:43:11', 'fActWaterLevelMixTank1', '281.673736572266']
['2021-5-4 6:43:11', 'fActWaterLevelMixTank2', '290.094085693359']
['2021-5-4 6:43:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:43:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:43:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:43:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:43:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:43:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:43:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:43:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:43:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:43:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:43:11', 'DoVa_Co2', '0']
['2021-5-4 6:43:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:43:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:43:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:43:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:43:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:44:11', 'fKWhCounter', '3344.91235351563']
['2021-5-4 6:44:11', 'fActPhLevelMixTank1', '5.58555841445923']
['2021-5-4 6:44:11', 'fActEcLevelMixTank1', '2015.90014648438']
['2021-5-4 6:44:11', 'fActPhLevelMixTank2', '3.83941149711609']
['2021-5-4 6:44:11', 'fActEcLevelMixTank2', '1027.25305175781']
['2021-5-4 6:44:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:44:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:44:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:44:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:44:11', 'fActCo2ValMemo', '855']
['2021-5-4 6:44:11', 'fActWaterLevelMixTank1', '282.189819335938']
['2021-5-4 6:44:11', 'fActWaterLevelMixTank2', '290.012603759766']
['2021-5-4 6:44:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:44:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:44:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:44:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:44:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:44:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:44:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:44:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:44:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:44:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:44:11', 'DoVa_Co2', '0']
['2021-5-4 6:44:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:44:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:44:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:44:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:44:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:45:11', 'fKWhCounter', '3345.11254882813']
['2021-5-4 6:45:11', 'fActPhLevelMixTank1', '5.58848857879639']
['2021-5-4 6:45:11', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 6:45:11', 'fActPhLevelMixTank2', '3.83941149711609']
['2021-5-4 6:45:11', 'fActEcLevelMixTank2', '1025.72705078125']
['2021-5-4 6:45:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:45:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:45:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:45:11', 'fActRhValMemo', '51.5']
['2021-5-4 6:45:11', 'fActCo2ValMemo', '853']
['2021-5-4 6:45:11', 'fActWaterLevelMixTank1', '283.113342285156']
['2021-5-4 6:45:11', 'fActWaterLevelMixTank2', '290.827453613281']
['2021-5-4 6:45:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:45:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:45:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:45:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:45:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:45:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:45:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:45:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:45:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:45:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:45:11', 'DoVa_Co2', '0']
['2021-5-4 6:45:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:45:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:45:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:45:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:45:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:46:11', 'fKWhCounter', '3345.21264648438']
['2021-5-4 6:46:11', 'fActPhLevelMixTank1', '5.59166240692139']
['2021-5-4 6:46:11', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 6:46:11', 'fActPhLevelMixTank2', '3.84112071990967']
['2021-5-4 6:46:11', 'fActEcLevelMixTank2', '1024.50634765625']
['2021-5-4 6:46:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:46:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:46:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:46:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 6:46:11', 'fActCo2ValMemo', '853']
['2021-5-4 6:46:11', 'fActWaterLevelMixTank1', '282.733093261719']
['2021-5-4 6:46:11', 'fActWaterLevelMixTank2', '290.528686523438']
['2021-5-4 6:46:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:46:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:46:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:46:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:46:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:46:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:46:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:46:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:46:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:46:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:46:11', 'DoVa_Co2', '0']
['2021-5-4 6:46:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:46:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:46:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:46:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_1_White', '0']

['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:46:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:47:11', 'fKWhCounter', '3345.41284179688']
['2021-5-4 6:47:11', 'fActPhLevelMixTank1', '5.60045146942139']
['2021-5-4 6:47:11', 'fActEcLevelMixTank1', '2013.61120605469']
['2021-5-4 6:47:11', 'fActPhLevelMixTank2', '3.84112071990967']
['2021-5-4 6:47:11', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 6:47:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:47:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:47:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 6:47:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 6:47:11', 'fActCo2ValMemo', '849']
['2021-5-4 6:47:11', 'fActWaterLevelMixTank1', '281.266326904297']
['2021-5-4 6:47:11', 'fActWaterLevelMixTank2', '290.908966064453']
['2021-5-4 6:47:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:47:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:47:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:47:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:47:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:47:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:47:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:47:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:47:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:47:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:47:11', 'DoVa_Co2', '0']
['2021-5-4 6:47:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:47:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:47:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:47:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:47:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:48:11', 'fKWhCounter', '3345.51293945313']
['2021-5-4 6:48:11', 'fActPhLevelMixTank1', '5.60386991500854']
['2021-5-4 6:48:11', 'fActEcLevelMixTank1', '2014.67944335938']
['2021-5-4 6:48:11', 'fActPhLevelMixTank2', '3.84380626678467']
['2021-5-4 6:48:11', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 6:48:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:48:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:48:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:48:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:48:11', 'fActCo2ValMemo', '848']
['2021-5-4 6:48:11', 'fActWaterLevelMixTank1', '283.194854736328']
['2021-5-4 6:48:11', 'fActWaterLevelMixTank2', '290.80029296875']
['2021-5-4 6:48:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:48:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:48:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:48:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:48:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:48:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:48:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:48:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:48:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:48:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:48:11', 'DoVa_Co2', '0']
['2021-5-4 6:48:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:48:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:48:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:48:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:48:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:49:11', 'fKWhCounter', '3345.61303710938']
['2021-5-4 6:49:11', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 6:49:11', 'fActEcLevelMixTank1', '2015.4423828125']
['2021-5-4 6:49:11', 'fActPhLevelMixTank2', '3.84575939178467']
['2021-5-4 6:49:11', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 6:49:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:49:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:49:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:49:11', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 6:49:11', 'fActCo2ValMemo', '849']
['2021-5-4 6:49:11', 'fActWaterLevelMixTank1', '283.004699707031']
['2021-5-4 6:49:11', 'fActWaterLevelMixTank2', '290.990447998047']
['2021-5-4 6:49:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:49:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:49:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:49:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:49:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:49:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:49:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:49:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:49:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:49:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:49:11', 'DoVa_Co2', '0']
['2021-5-4 6:49:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:49:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:49:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:49:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:49:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:50:11', 'fKWhCounter', '3345.81323242188']
['2021-5-4 6:50:11', 'fActPhLevelMixTank1', '5.60606718063354']
['2021-5-4 6:50:11', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 6:50:11', 'fActPhLevelMixTank2', '3.84405040740967']
['2021-5-4 6:50:11', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 6:50:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:50:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:50:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:50:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:50:11', 'fActCo2ValMemo', '847']
['2021-5-4 6:50:11', 'fActWaterLevelMixTank1', '284.281341552734']
['2021-5-4 6:50:11', 'fActWaterLevelMixTank2', '291.262054443359']
['2021-5-4 6:50:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:50:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:50:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:50:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:50:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:50:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:50:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:50:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:50:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:50:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:50:11', 'DoVa_Co2', '0']
['2021-5-4 6:50:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:50:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:50:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:50:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:50:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:51:11', 'fKWhCounter', '3345.91333007813']
['2021-5-4 6:51:11', 'fActPhLevelMixTank1', '5.60777616500854']
['2021-5-4 6:51:11', 'fActEcLevelMixTank1', '2013.00085449219']
['2021-5-4 6:51:11', 'fActPhLevelMixTank2', '3.84527111053467']
['2021-5-4 6:51:11', 'fActEcLevelMixTank2', '1026.33752441406']
['2021-5-4 6:51:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:51:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:51:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:51:11', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 6:51:11', 'fActCo2ValMemo', '846']
['2021-5-4 6:51:11', 'fActWaterLevelMixTank1', '283.520782470703']
['2021-5-4 6:51:11', 'fActWaterLevelMixTank2', '291.234893798828']
['2021-5-4 6:51:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:51:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:51:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:51:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:51:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:51:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:51:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:51:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:51:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:51:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:51:11', 'DoVa_Co2', '0']
['2021-5-4 6:51:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:51:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:51:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:51:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_1_Blue', '0']

['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:51:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:52:11', 'fKWhCounter', '3346.11352539063']
['2021-5-4 6:52:11', 'fActPhLevelMixTank1', '5.60899686813354']
['2021-5-4 6:52:11', 'fActEcLevelMixTank1', '2017.8837890625']
['2021-5-4 6:52:11', 'fActPhLevelMixTank2', '3.85088658332825']
['2021-5-4 6:52:11', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 6:52:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:52:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:52:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:52:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:52:11', 'fActCo2ValMemo', '843']
['2021-5-4 6:52:11', 'fActWaterLevelMixTank1', '284.498626708984']
['2021-5-4 6:52:11', 'fActWaterLevelMixTank2', '292.049774169922']
['2021-5-4 6:52:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:52:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:52:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:52:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:52:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:52:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:52:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:52:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:52:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:52:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:52:11', 'DoVa_Co2', '0']
['2021-5-4 6:52:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:52:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:52:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:52:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:52:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:53:11', 'fKWhCounter', '3346.21362304688']
['2021-5-4 6:53:11', 'fActPhLevelMixTank1', '5.61168241500854']
['2021-5-4 6:53:11', 'fActEcLevelMixTank1', '2016.35791015625']
['2021-5-4 6:53:11', 'fActPhLevelMixTank2', '3.84722423553467']
['2021-5-4 6:53:11', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 6:53:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:53:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:53:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:53:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:53:11', 'fActCo2ValMemo', '848']
['2021-5-4 6:53:11', 'fActWaterLevelMixTank1', '284.987548828125']
['2021-5-4 6:53:11', 'fActWaterLevelMixTank2', '291.832458496094']
['2021-5-4 6:53:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:53:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:53:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:53:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:53:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:53:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:53:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:53:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:53:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:53:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:53:11', 'DoVa_Co2', '0']
['2021-5-4 6:53:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:53:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:53:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:53:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:53:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:54:11', 'fKWhCounter', '3346.31372070313']
['2021-5-4 6:54:11', 'fActPhLevelMixTank1', '5.60924100875854']
['2021-5-4 6:54:11', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 6:54:11', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 6:54:11', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 6:54:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:54:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:54:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:54:11', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 6:54:11', 'fActCo2ValMemo', '847']
['2021-5-4 6:54:11', 'fActWaterLevelMixTank1', '285.476470947266']
['2021-5-4 6:54:11', 'fActWaterLevelMixTank2', '292.321411132813']
['2021-5-4 6:54:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:54:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:54:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:54:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:54:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:54:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:54:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:54:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:54:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:54:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:54:11', 'DoVa_Co2', '0']
['2021-5-4 6:54:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:54:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:54:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:54:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:54:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:55:11', 'fKWhCounter', '3346.51391601563']
['2021-5-4 6:55:11', 'fActPhLevelMixTank1', '5.61387968063354']
['2021-5-4 6:55:11', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 6:55:11', 'fActPhLevelMixTank2', '3.85454869270325']
['2021-5-4 6:55:11', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 6:55:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:55:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:55:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:55:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 6:55:11', 'fActCo2ValMemo', '847']
['2021-5-4 6:55:11', 'fActWaterLevelMixTank1', '285.313507080078']
['2021-5-4 6:55:11', 'fActWaterLevelMixTank2', '292.70166015625']
['2021-5-4 6:55:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:55:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:55:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:55:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:55:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:55:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:55:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:55:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:55:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:55:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:55:11', 'DoVa_Co2', '0']
['2021-5-4 6:55:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:55:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:55:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:55:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:55:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:56:11', 'fKWhCounter', '3346.61401367188']
['2021-5-4 6:56:11', 'fActPhLevelMixTank1', '5.60899686813354']
['2021-5-4 6:56:11', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 6:56:11', 'fActPhLevelMixTank2', '3.85650205612183']
['2021-5-4 6:56:11', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 6:56:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:56:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:56:11', 'fActTempValMemo', '19.5']
['2021-5-4 6:56:11', 'fActRhValMemo', '52']
['2021-5-4 6:56:11', 'fActCo2ValMemo', '845']
['2021-5-4 6:56:11', 'fActWaterLevelMixTank1', '285.069030761719']
['2021-5-4 6:56:11', 'fActWaterLevelMixTank2', '292.484375']
['2021-5-4 6:56:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:56:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:56:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:56:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:56:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:56:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:56:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:56:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:56:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:56:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:56:11', 'DoVa_Co2', '0']
['2021-5-4 6:56:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:56:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:56:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:56:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']

['2021-5-4 6:56:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:56:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:57:11', 'fKWhCounter', '3346.71411132813']
['2021-5-4 6:57:11', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 6:57:11', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 6:57:11', 'fActPhLevelMixTank2', '3.85332798957825']
['2021-5-4 6:57:11', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 6:57:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:57:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:57:11', 'fActTempValMemo', '19.5']
['2021-5-4 6:57:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 6:57:11', 'fActCo2ValMemo', '848']
['2021-5-4 6:57:11', 'fActWaterLevelMixTank1', '285.938232421875']
['2021-5-4 6:57:11', 'fActWaterLevelMixTank2', '292.918975830078']
['2021-5-4 6:57:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:57:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:57:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:57:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:57:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:57:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:57:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:57:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:57:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:57:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:57:11', 'DoVa_Co2', '0']
['2021-5-4 6:57:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:57:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:57:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:57:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:57:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:58:11', 'fKWhCounter', '3346.91430664063']
['2021-5-4 6:58:11', 'fActPhLevelMixTank1', '5.61314725875854']
['2021-5-4 6:58:11', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 6:58:11', 'fActPhLevelMixTank2', '3.85576963424683']
['2021-5-4 6:58:11', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 6:58:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:58:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:58:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:58:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 6:58:11', 'fActCo2ValMemo', '848']
['2021-5-4 6:58:11', 'fActWaterLevelMixTank1', '286.725952148438']
['2021-5-4 6:58:11', 'fActWaterLevelMixTank2', '293.380737304688']
['2021-5-4 6:58:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:58:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:58:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:58:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:58:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:58:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:58:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:58:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:58:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:58:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:58:11', 'DoVa_Co2', '0']
['2021-5-4 6:58:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:58:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:58:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:58:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:58:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 6:59:11', 'fKWhCounter', '3347.01440429688']
['2021-5-4 6:59:11', 'fActPhLevelMixTank1', '5.61070585250854']
['2021-5-4 6:59:11', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 6:59:11', 'fActPhLevelMixTank2', '3.85894346237183']
['2021-5-4 6:59:11', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 6:59:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 6:59:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 6:59:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 6:59:11', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 6:59:11', 'fActCo2ValMemo', '844']
['2021-5-4 6:59:11', 'fActWaterLevelMixTank1', '286.888916015625']
['2021-5-4 6:59:11', 'fActWaterLevelMixTank2', '293.380737304688']
['2021-5-4 6:59:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 6:59:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 6:59:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 6:59:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 6:59:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 6:59:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 6:59:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 6:59:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 6:59:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 6:59:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 6:59:11', 'DoVa_Co2', '0']
['2021-5-4 6:59:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 6:59:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 6:59:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 6:59:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 6:59:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:0:11', 'fKWhCounter', '3347.21459960938']
['2021-5-4 7:0:11', 'fActPhLevelMixTank1', '5.61387968063354']
['2021-5-4 7:0:11', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 7:0:11', 'fActPhLevelMixTank2', '3.85576963424683']
['2021-5-4 7:0:11', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 7:0:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:0:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:0:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:0:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 7:0:11', 'fActCo2ValMemo', '843']
['2021-5-4 7:0:11', 'fActWaterLevelMixTank1', '285.938232421875']
['2021-5-4 7:0:11', 'fActWaterLevelMixTank2', '293.788177490234']
['2021-5-4 7:0:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:0:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:0:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:0:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:0:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:0:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:0:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:0:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:0:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:0:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:0:11', 'DoVa_Co2', '0']
['2021-5-4 7:0:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:0:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:0:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:0:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:0:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:1:11', 'fKWhCounter', '3347.31469726563']
['2021-5-4 7:1:11', 'fActPhLevelMixTank1', '5.61192655563354']
['2021-5-4 7:1:11', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 7:1:11', 'fActPhLevelMixTank2', '3.85992002487183']
['2021-5-4 7:1:11', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 7:1:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:1:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:1:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:1:11', 'fActRhValMemo', '51.5']
['2021-5-4 7:1:11', 'fActCo2ValMemo', '842']
['2021-5-4 7:1:11', 'fActWaterLevelMixTank1', '286.590148925781']
['2021-5-4 7:1:11', 'fActWaterLevelMixTank2', '293.625183105469']
['2021-5-4 7:1:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:1:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:1:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:1:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:1:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:1:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:1:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:1:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:1:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:1:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:1:11', 'DoVa_Co2', '0']
['2021-5-4 7:1:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:1:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:1:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:1:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:1:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:2:11', 'fKWhCounter', '3347.41479492188']
['2021-5-4 7:2:11', 'fActPhLevelMixTank1', '5.61314725875854']
['2021-5-4 7:2:11', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 7:2:11', 'fActPhLevelMixTank2', '3.86284971237183']
['2021-5-4 7:2:11', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 7:2:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:2:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:2:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:2:11', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 7:2:11', 'fActCo2ValMemo', '839']
['2021-5-4 7:2:11', 'fActWaterLevelMixTank1', '286.725952148438']
['2021-5-4 7:2:11', 'fActWaterLevelMixTank2', '293.543701171875']
['2021-5-4 7:2:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:2:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:2:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:2:11', 'DoPu_AddAcidMixTank_2', '0']

['2021-5-4 7:2:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:2:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:2:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:2:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:2:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:2:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:2:11', 'DoVa_Co2', '0']
['2021-5-4 7:2:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:2:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:2:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:2:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:2:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:3:11', 'fKWhCounter', '3347.61499023438']
['2021-5-4 7:3:11', 'fActPhLevelMixTank1', '5.6185188293457']
['2021-5-4 7:3:11', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 7:3:11', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 7:3:11', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 7:3:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:3:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:3:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:3:11', 'fActRhValMemo', '51.5']
['2021-5-4 7:3:11', 'fActCo2ValMemo', '839']
['2021-5-4 7:3:11', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 7:3:11', 'fActWaterLevelMixTank2', '293.489379882813']
['2021-5-4 7:3:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:3:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:3:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:3:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:3:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:3:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:3:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:3:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:3:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:3:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:3:11', 'DoVa_Co2', '0']
['2021-5-4 7:3:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:3:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:3:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:3:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:3:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:4:11', 'fKWhCounter', '3347.71508789063']
['2021-5-4 7:4:11', 'fActPhLevelMixTank1', '5.6236457824707']
['2021-5-4 7:4:11', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 7:4:11', 'fActPhLevelMixTank2', '3.86138486862183']
['2021-5-4 7:4:11', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 7:4:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:4:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:4:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:4:11', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 7:4:11', 'fActCo2ValMemo', '837']
['2021-5-4 7:4:11', 'fActWaterLevelMixTank1', '286.943237304688']
['2021-5-4 7:4:11', 'fActWaterLevelMixTank2', '293.951141357422']
['2021-5-4 7:4:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:4:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:4:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:4:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:4:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:4:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:4:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:4:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:4:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:4:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:4:11', 'DoVa_Co2', '0']
['2021-5-4 7:4:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:4:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:4:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:4:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:4:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:5:11', 'fKWhCounter', '3347.81518554688']
['2021-5-4 7:5:11', 'fActPhLevelMixTank1', '5.6216926574707']
['2021-5-4 7:5:11', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 7:5:11', 'fActPhLevelMixTank2', '3.86431479454041']
['2021-5-4 7:5:11', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 7:5:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:5:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:5:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:5:11', 'fActRhValMemo', '51.5']
['2021-5-4 7:5:11', 'fActCo2ValMemo', '835']
['2021-5-4 7:5:11', 'fActWaterLevelMixTank1', '287.079071044922']
['2021-5-4 7:5:11', 'fActWaterLevelMixTank2', '293.896820068359']
['2021-5-4 7:5:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:5:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:5:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:5:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:5:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:5:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:5:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:5:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:5:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:5:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:5:11', 'DoVa_Co2', '0']
['2021-5-4 7:5:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:5:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:5:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:5:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:5:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:6:11', 'fKWhCounter', '3348.01538085938']
['2021-5-4 7:6:11', 'fActPhLevelMixTank1', '5.6265754699707']
['2021-5-4 7:6:11', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 7:6:11', 'fActPhLevelMixTank2', '3.86187314987183']
['2021-5-4 7:6:11', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 7:6:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:6:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:6:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:6:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:6:11', 'fActCo2ValMemo', '833']
['2021-5-4 7:6:11', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 7:6:11', 'fActWaterLevelMixTank2', '294.467224121094']
['2021-5-4 7:6:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:6:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:6:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:6:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:6:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:6:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:6:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:6:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:6:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:6:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:6:11', 'DoVa_Co2', '0']
['2021-5-4 7:6:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:6:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:6:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:6:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:6:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:7:11', 'fKWhCounter', '3348.11547851563']
['2021-5-4 7:7:11', 'fActPhLevelMixTank1', '5.6273078918457']
['2021-5-4 7:7:11', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 7:7:11', 'fActPhLevelMixTank2', '3.86138486862183']
['2021-5-4 7:7:11', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 7:7:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:7:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:7:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:7:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:7:11', 'fActCo2ValMemo', '839']
['2021-5-4 7:7:11', 'fActWaterLevelMixTank1', '286.888916015625']
['2021-5-4 7:7:11', 'fActWaterLevelMixTank2', '294.114105224609']
['2021-5-4 7:7:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:7:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:7:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:7:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:7:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:7:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:7:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:7:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:7:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:7:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:7:11', 'DoVa_Co2', '0']
['2021-5-4 7:7:11', 'DoVa_IrrigateLevel_3_MT1', '0']

['2021-5-4 7:7:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:7:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:7:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:7:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:8:11', 'fKWhCounter', '3348.31567382813']
['2021-5-4 7:8:11', 'fActPhLevelMixTank1', '5.6312141418457']
['2021-5-4 7:8:11', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 7:8:11', 'fActPhLevelMixTank2', '3.86431479454041']
['2021-5-4 7:8:11', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 7:8:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:8:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:8:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:8:11', 'fActRhValMemo', '51.5']
['2021-5-4 7:8:11', 'fActCo2ValMemo', '837']
['2021-5-4 7:8:11', 'fActWaterLevelMixTank1', '287.486480712891']
['2021-5-4 7:8:11', 'fActWaterLevelMixTank2', '294.304260253906']
['2021-5-4 7:8:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:8:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:8:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:8:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:8:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:8:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:8:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:8:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:8:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:8:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:8:11', 'DoVa_Co2', '0']
['2021-5-4 7:8:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:8:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:8:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:8:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:8:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:9:11', 'fKWhCounter', '3348.41577148438']
['2021-5-4 7:9:11', 'fActPhLevelMixTank1', '5.63487672805786']
['2021-5-4 7:9:11', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 7:9:11', 'fActPhLevelMixTank2', '3.86211729049683']
['2021-5-4 7:9:11', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 7:9:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:9:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:9:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:9:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 7:9:11', 'fActCo2ValMemo', '840']
['2021-5-4 7:9:11', 'fActWaterLevelMixTank1', '287.622314453125']
['2021-5-4 7:9:11', 'fActWaterLevelMixTank2', '294.3857421875']
['2021-5-4 7:9:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:9:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:9:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:9:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:9:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:9:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:9:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:9:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:9:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:9:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:9:11', 'DoVa_Co2', '0']
['2021-5-4 7:9:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:9:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:9:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:9:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:9:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:10:11', 'fKWhCounter', '3348.51586914063']
['2021-5-4 7:10:11', 'fActPhLevelMixTank1', '5.63390016555786']
['2021-5-4 7:10:11', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 7:10:11', 'fActPhLevelMixTank2', '3.86431479454041']
['2021-5-4 7:10:11', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 7:10:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:10:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:10:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:10:11', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 7:10:11', 'fActCo2ValMemo', '839']
['2021-5-4 7:10:11', 'fActWaterLevelMixTank1', '287.839599609375']
['2021-5-4 7:10:11', 'fActWaterLevelMixTank2', '294.222747802734']
['2021-5-4 7:10:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:10:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:10:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:10:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:10:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:10:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:10:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:10:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:10:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:10:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:10:11', 'DoVa_Co2', '0']
['2021-5-4 7:10:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:10:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:10:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:10:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:10:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:11:11', 'fKWhCounter', '3348.71606445313']
['2021-5-4 7:11:11', 'fActPhLevelMixTank1', '5.63853883743286']
['2021-5-4 7:11:11', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 7:11:11', 'fActPhLevelMixTank2', '3.86968588829041']
['2021-5-4 7:11:11', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 7:11:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:11:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:11:11', 'fActTempValMemo', '19.5']
['2021-5-4 7:11:11', 'fActRhValMemo', '51.5']
['2021-5-4 7:11:11', 'fActCo2ValMemo', '841']
['2021-5-4 7:11:11', 'fActWaterLevelMixTank1', '288.301361083984']
['2021-5-4 7:11:11', 'fActWaterLevelMixTank2', '295.064788818359']
['2021-5-4 7:11:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:11:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:11:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:11:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:11:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:11:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:11:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:11:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:11:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:11:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:11:11', 'DoVa_Co2', '0']
['2021-5-4 7:11:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:11:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:11:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:11:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:11:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:12:11', 'fKWhCounter', '3348.81616210938']
['2021-5-4 7:12:11', 'fActPhLevelMixTank1', '5.64049196243286']
['2021-5-4 7:12:11', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 7:12:11', 'fActPhLevelMixTank2', '3.87041831016541']
['2021-5-4 7:12:11', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 7:12:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:12:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:12:11', 'fActTempValMemo', '19.5']
['2021-5-4 7:12:11', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 7:12:11', 'fActCo2ValMemo', '843']
['2021-5-4 7:12:11', 'fActWaterLevelMixTank1', '288.355682373047']
['2021-5-4 7:12:11', 'fActWaterLevelMixTank2', '295.119110107422']
['2021-5-4 7:12:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:12:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:12:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:12:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:12:11', 'DoPu_AddEcAMixTank_2', '0']

['2021-5-4 7:12:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:12:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:12:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:12:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:12:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:12:11', 'DoVa_Co2', '0']
['2021-5-4 7:12:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:12:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:12:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:12:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:12:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:13:11', 'fKWhCounter', '3348.91625976563']
['2021-5-4 7:13:11', 'fActPhLevelMixTank1', '5.64293336868286']
['2021-5-4 7:13:11', 'fActEcLevelMixTank1', '2029.48083496094']
['2021-5-4 7:13:11', 'fActPhLevelMixTank2', '3.86870932579041']
['2021-5-4 7:13:11', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 7:13:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:13:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:13:11', 'fActTempValMemo', '19.5']
['2021-5-4 7:13:11', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 7:13:11', 'fActCo2ValMemo', '840']
['2021-5-4 7:13:11', 'fActWaterLevelMixTank1', '288.627319335938']
['2021-5-4 7:13:11', 'fActWaterLevelMixTank2', '295.119110107422']
['2021-5-4 7:13:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:13:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:13:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:13:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:13:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:13:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:13:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:13:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:13:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:13:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:13:11', 'DoVa_Co2', '0']
['2021-5-4 7:13:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:13:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:13:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:13:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:13:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:14:11', 'fKWhCounter', '3349.11645507813']
['2021-5-4 7:14:11', 'fActPhLevelMixTank1', '5.64366579055786']
['2021-5-4 7:14:11', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 7:14:11', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 7:14:11', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 7:14:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:14:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:14:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:14:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:14:11', 'fActCo2ValMemo', '839']
['2021-5-4 7:14:11', 'fActWaterLevelMixTank1', '288.871765136719']
['2021-5-4 7:14:11', 'fActWaterLevelMixTank2', '295.33642578125']
['2021-5-4 7:14:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:14:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:14:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:14:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:14:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:14:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:14:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:14:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:14:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:14:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:14:11', 'DoVa_Co2', '0']
['2021-5-4 7:14:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:14:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:14:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:14:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:14:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:15:11', 'fKWhCounter', '3349.21655273438']
['2021-5-4 7:15:11', 'fActPhLevelMixTank1', '5.64244508743286']
['2021-5-4 7:15:11', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 7:15:11', 'fActPhLevelMixTank2', '3.87090659141541']
['2021-5-4 7:15:11', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 7:15:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:15:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:15:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:15:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:15:11', 'fActCo2ValMemo', '837']
['2021-5-4 7:15:11', 'fActWaterLevelMixTank1', '289.061920166016']
['2021-5-4 7:15:11', 'fActWaterLevelMixTank2', '296.015472412109']
['2021-5-4 7:15:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:15:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:15:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:15:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:15:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:15:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:15:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:15:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:15:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:15:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:15:11', 'DoVa_Co2', '0']
['2021-5-4 7:15:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:15:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:15:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:15:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:15:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:16:11', 'fKWhCounter', '3349.41674804688']
['2021-5-4 7:16:11', 'fActPhLevelMixTank1', '5.64366579055786']
['2021-5-4 7:16:11', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 7:16:11', 'fActPhLevelMixTank2', '3.86993002891541']
['2021-5-4 7:16:11', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 7:16:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:16:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:16:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:16:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:16:11', 'fActCo2ValMemo', '834']
['2021-5-4 7:16:11', 'fActWaterLevelMixTank1', '288.654479980469']
['2021-5-4 7:16:11', 'fActWaterLevelMixTank2', '295.580871582031']
['2021-5-4 7:16:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:16:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:16:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:16:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:16:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:16:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:16:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:16:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:16:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:16:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:16:11', 'DoVa_Co2', '0']
['2021-5-4 7:16:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:16:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:16:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:16:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_4_Red', '0']

['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:16:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:17:11', 'fKWhCounter', '3349.51684570313']
['2021-5-4 7:17:11', 'fActPhLevelMixTank1', '5.64806032180786']
['2021-5-4 7:17:11', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 7:17:11', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 7:17:11', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 7:17:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:17:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:17:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:17:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:17:11', 'fActCo2ValMemo', '827']
['2021-5-4 7:17:11', 'fActWaterLevelMixTank1', '289.170562744141']
['2021-5-4 7:17:11', 'fActWaterLevelMixTank2', '296.287109375']
['2021-5-4 7:17:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:17:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:17:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:17:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:17:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:17:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:17:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:17:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:17:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:17:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:17:11', 'DoVa_Co2', '0']
['2021-5-4 7:17:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:17:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:17:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:17:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:17:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:18:11', 'fKWhCounter', '3349.61694335938']
['2021-5-4 7:18:11', 'fActPhLevelMixTank1', '5.65147876739502']
['2021-5-4 7:18:11', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 7:18:11', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 7:18:11', 'fActEcLevelMixTank2', '1038.544921875']
['2021-5-4 7:18:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:18:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:18:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:18:11', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 7:18:11', 'fActCo2ValMemo', '828']
['2021-5-4 7:18:11', 'fActWaterLevelMixTank1', '289.795288085938']
['2021-5-4 7:18:11', 'fActWaterLevelMixTank2', '296.395751953125']
['2021-5-4 7:18:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:18:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:18:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:18:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:18:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:18:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:18:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:18:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:18:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:18:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:18:11', 'DoVa_Co2', '0']
['2021-5-4 7:18:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:18:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:18:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:18:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:18:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:19:11', 'fKWhCounter', '3349.81713867188']
['2021-5-4 7:19:11', 'fActPhLevelMixTank1', '5.65343189239502']
['2021-5-4 7:19:11', 'fActEcLevelMixTank1', '2030.24389648438']
['2021-5-4 7:19:11', 'fActPhLevelMixTank2', '3.86846518516541']
['2021-5-4 7:19:11', 'fActEcLevelMixTank2', '1051.82043457031']
['2021-5-4 7:19:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:19:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:19:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:19:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:19:11', 'fActCo2ValMemo', '829']
['2021-5-4 7:19:11', 'fActWaterLevelMixTank1', '290.311370849609']
['2021-5-4 7:19:11', 'fActWaterLevelMixTank2', '296.721710205078']
['2021-5-4 7:19:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:19:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:19:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:19:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:19:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:19:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:19:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:19:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:19:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:19:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:19:11', 'DoVa_Co2', '0']
['2021-5-4 7:19:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:19:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:19:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:19:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:19:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:20:11', 'fKWhCounter', '3349.91723632813']
['2021-5-4 7:20:11', 'fActPhLevelMixTank1', '5.65636157989502']
['2021-5-4 7:20:11', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 7:20:11', 'fActPhLevelMixTank2', '3.87285995483398']
['2021-5-4 7:20:11', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 7:20:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:20:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:20:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 7:20:11', 'fActRhValMemo', '51.5']
['2021-5-4 7:20:11', 'fActCo2ValMemo', '830']
['2021-5-4 7:20:11', 'fActWaterLevelMixTank1', '289.903930664063']
['2021-5-4 7:20:11', 'fActWaterLevelMixTank2', '296.803192138672']
['2021-5-4 7:20:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:20:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:20:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:20:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:20:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:20:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:20:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:20:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:20:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:20:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:20:11', 'DoVa_Co2', '0']
['2021-5-4 7:20:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:20:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:20:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:20:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:20:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:21:11', 'fKWhCounter', '3350.01733398438']
['2021-5-4 7:21:11', 'fActPhLevelMixTank1', '5.65684986114502']
['2021-5-4 7:21:11', 'fActEcLevelMixTank1', '2028.56530761719']
['2021-5-4 7:21:11', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 7:21:11', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 7:21:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:21:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:21:11', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 7:21:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:21:11', 'fActCo2ValMemo', '830']
['2021-5-4 7:21:11', 'fActWaterLevelMixTank1', '290.691650390625']
['2021-5-4 7:21:11', 'fActWaterLevelMixTank2', '297.346435546875']
['2021-5-4 7:21:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:21:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:21:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:21:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:21:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:21:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:21:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:21:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:21:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:21:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:21:11', 'DoVa_Co2', '0']
['2021-5-4 7:21:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:21:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:21:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:21:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_3_Red', '0']

['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:21:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:22:11', 'fKWhCounter', '3350.21752929688']
['2021-5-4 7:22:11', 'fActPhLevelMixTank1', '5.66100025177002']
['2021-5-4 7:22:11', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 7:22:11', 'fActPhLevelMixTank2', '3.86773276329041']
['2021-5-4 7:22:11', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 7:22:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:22:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:22:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:22:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:22:11', 'fActCo2ValMemo', '826']
['2021-5-4 7:22:11', 'fActWaterLevelMixTank1', '290.420043945313']
['2021-5-4 7:22:11', 'fActWaterLevelMixTank2', '296.640197753906']
['2021-5-4 7:22:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:22:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:22:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:22:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:22:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:22:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:22:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:22:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:22:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:22:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:22:11', 'DoVa_Co2', '0']
['2021-5-4 7:22:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:22:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:22:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:22:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:22:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:23:11', 'fKWhCounter', '3350.31762695313']
['2021-5-4 7:23:11', 'fActPhLevelMixTank1', '5.66075611114502']
['2021-5-4 7:23:11', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 7:23:11', 'fActPhLevelMixTank2', '3.86846518516541']
['2021-5-4 7:23:11', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 7:23:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:23:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:23:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:23:11', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 7:23:11', 'fActCo2ValMemo', '824']
['2021-5-4 7:23:11', 'fActWaterLevelMixTank1', '289.713806152344']
['2021-5-4 7:23:11', 'fActWaterLevelMixTank2', '296.830352783203']
['2021-5-4 7:23:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:23:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:23:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:23:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:23:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:23:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:23:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:23:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:23:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:23:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:23:11', 'DoVa_Co2', '0']
['2021-5-4 7:23:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:23:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:23:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:23:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:23:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:24:11', 'fKWhCounter', '3350.51782226563']
['2021-5-4 7:24:11', 'fActPhLevelMixTank1', '5.66783666610718']
['2021-5-4 7:24:11', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 7:24:11', 'fActPhLevelMixTank2', '3.87530136108398']
['2021-5-4 7:24:11', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 7:24:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:24:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:24:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:24:11', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 7:24:11', 'fActCo2ValMemo', '823']
['2021-5-4 7:24:11', 'fActWaterLevelMixTank1', '290.80029296875']
['2021-5-4 7:24:11', 'fActWaterLevelMixTank2', '297.536560058594']
['2021-5-4 7:24:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:24:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:24:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:24:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:24:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:24:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:24:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:24:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:24:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:24:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:24:11', 'DoVa_Co2', '0']
['2021-5-4 7:24:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:24:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:24:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:24:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:24:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:25:11', 'fKWhCounter', '3350.61791992188']
['2021-5-4 7:25:11', 'fActPhLevelMixTank1', '5.67052221298218']
['2021-5-4 7:25:11', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 7:25:11', 'fActPhLevelMixTank2', '3.86993002891541']
['2021-5-4 7:25:11', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 7:25:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:25:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:25:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:25:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 7:25:11', 'fActCo2ValMemo', '824']
['2021-5-4 7:25:11', 'fActWaterLevelMixTank1', '290.854614257813']
['2021-5-4 7:25:11', 'fActWaterLevelMixTank2', '297.672393798828']
['2021-5-4 7:25:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:25:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:25:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:25:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:25:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:25:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:25:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:25:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:25:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:25:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:25:11', 'DoVa_Co2', '0']
['2021-5-4 7:25:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:25:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:25:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:25:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:25:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:26:11', 'fKWhCounter', '3350.71801757813']
['2021-5-4 7:26:11', 'fActPhLevelMixTank1', '5.67149877548218']
['2021-5-4 7:26:11', 'fActEcLevelMixTank1', '2031.76977539063']
['2021-5-4 7:26:11', 'fActPhLevelMixTank2', '3.87481307983398']
['2021-5-4 7:26:11', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 7:26:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:26:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:26:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:26:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 7:26:11', 'fActCo2ValMemo', '821']
['2021-5-4 7:26:11', 'fActWaterLevelMixTank1', '291.126251220703']
['2021-5-4 7:26:11', 'fActWaterLevelMixTank2', '297.645233154297']
['2021-5-4 7:26:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:26:11', 'DoPu_AddEcAMixTank_1', '0']

['2021-5-4 7:26:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:26:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:26:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:26:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:26:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:26:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:26:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:26:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:26:11', 'DoVa_Co2', '0']
['2021-5-4 7:26:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:26:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:26:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:26:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:26:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:27:11', 'fKWhCounter', '3350.91821289063']
['2021-5-4 7:27:11', 'fActPhLevelMixTank1', '5.67442846298218']
['2021-5-4 7:27:11', 'fActEcLevelMixTank1', '2033.60083007813']
['2021-5-4 7:27:11', 'fActPhLevelMixTank2', '3.87261581420898']
['2021-5-4 7:27:11', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 7:27:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:27:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:27:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:27:11', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 7:27:11', 'fActCo2ValMemo', '820']
['2021-5-4 7:27:11', 'fActWaterLevelMixTank1', '290.936126708984']
['2021-5-4 7:27:11', 'fActWaterLevelMixTank2', '298.052642822266']
['2021-5-4 7:27:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:27:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:27:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:27:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:27:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:27:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:27:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:27:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:27:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:27:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:27:11', 'DoVa_Co2', '0']
['2021-5-4 7:27:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:27:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:27:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:27:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:27:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:28:11', 'fKWhCounter', '3351.01831054688']
['2021-5-4 7:28:11', 'fActPhLevelMixTank1', '5.67638158798218']
['2021-5-4 7:28:11', 'fActEcLevelMixTank1', '2034.36389160156']
['2021-5-4 7:28:11', 'fActPhLevelMixTank2', '3.86968588829041']
['2021-5-4 7:28:11', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 7:28:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:28:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:28:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:28:11', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 7:28:11', 'fActCo2ValMemo', '818']
['2021-5-4 7:28:11', 'fActWaterLevelMixTank1', '291.071929931641']
['2021-5-4 7:28:11', 'fActWaterLevelMixTank2', '298.079803466797']
['2021-5-4 7:28:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:28:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:28:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:28:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:28:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:28:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:28:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:28:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:28:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:28:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:28:11', 'DoVa_Co2', '0']
['2021-5-4 7:28:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:28:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:28:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:28:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:28:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:29:11', 'fKWhCounter', '3351.21850585938']
['2021-5-4 7:29:11', 'fActPhLevelMixTank1', '5.64635133743286']
['2021-5-4 7:29:11', 'fActEcLevelMixTank1', '2070.5283203125']
['2021-5-4 7:29:11', 'fActPhLevelMixTank2', '3.83428454399109']
['2021-5-4 7:29:11', 'fActEcLevelMixTank2', '1056.85595703125']
['2021-5-4 7:29:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:29:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:29:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:29:11', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 7:29:11', 'fActCo2ValMemo', '818']
['2021-5-4 7:29:11', 'fActWaterLevelMixTank1', '293.516540527344']
['2021-5-4 7:29:11', 'fActWaterLevelMixTank2', '303.37646484375']
['2021-5-4 7:29:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:29:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:29:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:29:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:29:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:29:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:29:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:29:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:29:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:29:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:29:11', 'DoVa_Co2', '0']
['2021-5-4 7:29:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:29:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:29:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:29:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:29:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:30:11', 'fKWhCounter', '3351.31860351563']
['2021-5-4 7:30:11', 'fActPhLevelMixTank1', '5.56944465637207']
['2021-5-4 7:30:11', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 7:30:11', 'fActPhLevelMixTank2', '3.78814053535461']
['2021-5-4 7:30:11', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 7:30:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:30:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:30:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:30:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:30:11', 'fActCo2ValMemo', '818']
['2021-5-4 7:30:11', 'fActWaterLevelMixTank1', '284.552947998047']
['2021-5-4 7:30:11', 'fActWaterLevelMixTank2', '322.743255615234']
['2021-5-4 7:30:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:30:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:30:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:30:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:30:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:30:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:30:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:30:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:30:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:30:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:30:11', 'DoVa_Co2', '0']
['2021-5-4 7:30:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:30:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:30:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:30:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:30:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:31:11', 'fKWhCounter', '3351.51879882813']
['2021-5-4 7:31:11', 'fActPhLevelMixTank1', '5.56651496887207']
['2021-5-4 7:31:11', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 7:31:11', 'fActPhLevelMixTank2', '3.79107022285461']
['2021-5-4 7:31:11', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 7:31:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:31:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:31:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:31:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 7:31:11', 'fActCo2ValMemo', '815']
['2021-5-4 7:31:11', 'fActWaterLevelMixTank1', '275.480743408203']
['2021-5-4 7:31:11', 'fActWaterLevelMixTank2', '315.219268798828']
['2021-5-4 7:31:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:31:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:31:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:31:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:31:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:31:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:31:11', 'DoVa_IrrigateLevel_1_MT1', '0']

['2021-5-4 7:31:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:31:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:31:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:31:11', 'DoVa_Co2', '0']
['2021-5-4 7:31:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:31:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:31:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:31:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:31:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:32:11', 'fKWhCounter', '3351.71899414063']
['2021-5-4 7:32:11', 'fActPhLevelMixTank1', '5.56944465637207']
['2021-5-4 7:32:11', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 7:32:11', 'fActPhLevelMixTank2', '3.79375600814819']
['2021-5-4 7:32:11', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 7:32:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:32:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:32:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:32:11', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:32:11', 'fActCo2ValMemo', '813']
['2021-5-4 7:32:11', 'fActWaterLevelMixTank1', '279.881042480469']
['2021-5-4 7:32:11', 'fActWaterLevelMixTank2', '288.056915283203']
['2021-5-4 7:32:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:32:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:32:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:32:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:32:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:32:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:32:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:32:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:32:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:32:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:32:11', 'DoVa_Co2', '0']
['2021-5-4 7:32:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:32:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:32:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:32:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:32:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:33:11', 'fKWhCounter', '3351.81909179688']
['2021-5-4 7:33:11', 'fActPhLevelMixTank1', '5.56797981262207']
['2021-5-4 7:33:11', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 7:33:11', 'fActPhLevelMixTank2', '3.79863882064819']
['2021-5-4 7:33:11', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 7:33:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:33:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:33:11', 'fActTempValMemo', '19.5']
['2021-5-4 7:33:11', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 7:33:11', 'fActCo2ValMemo', '815']
['2021-5-4 7:33:11', 'fActWaterLevelMixTank1', '279.799530029297']
['2021-5-4 7:33:11', 'fActWaterLevelMixTank2', '311.878295898438']
['2021-5-4 7:33:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:33:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:33:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:33:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:33:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:33:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:33:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:33:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:33:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:33:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:33:11', 'DoVa_Co2', '0']
['2021-5-4 7:33:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:33:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:33:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:33:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:33:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:34:11', 'fKWhCounter', '3352.01928710938']
['2021-5-4 7:34:11', 'fActPhLevelMixTank1', '5.56895637512207']
['2021-5-4 7:34:11', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 7:34:11', 'fActPhLevelMixTank2', '3.80596327781677']
['2021-5-4 7:34:11', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 7:34:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:34:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:34:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:34:11', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 7:34:11', 'fActCo2ValMemo', '813']
['2021-5-4 7:34:11', 'fActWaterLevelMixTank1', '278.22412109375']
['2021-5-4 7:34:11', 'fActWaterLevelMixTank2', '289.333526611328']
['2021-5-4 7:34:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:34:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:34:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:34:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:34:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:34:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:34:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:34:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:34:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:34:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:34:11', 'DoVa_Co2', '0']
['2021-5-4 7:34:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:34:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:34:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:34:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:34:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:35:11', 'fKWhCounter', '3352.11938476563']
['2021-5-4 7:35:11', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 7:35:11', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 7:35:11', 'fActPhLevelMixTank2', '3.83623766899109']
['2021-5-4 7:35:11', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 7:35:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:35:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:35:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:35:11', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 7:35:11', 'fActCo2ValMemo', '814']
['2021-5-4 7:35:11', 'fActWaterLevelMixTank1', '277.191955566406']
['2021-5-4 7:35:11', 'fActWaterLevelMixTank2', '288.518676757813']
['2021-5-4 7:35:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:35:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:35:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:35:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:35:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:35:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:35:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:35:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:35:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:35:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:35:11', 'DoVa_Co2', '0']
['2021-5-4 7:35:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:35:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:35:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:35:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:35:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:36:11', 'fKWhCounter', '3352.31958007813']
['2021-5-4 7:36:11', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 7:36:11', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 7:36:11', 'fActPhLevelMixTank2', '3.83721423149109']
['2021-5-4 7:36:11', 'fActEcLevelMixTank2', '1059.14489746094']
['2021-5-4 7:36:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:36:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:36:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:36:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:36:11', 'fActCo2ValMemo', '814']
['2021-5-4 7:36:11', 'fActWaterLevelMixTank1', '276.431396484375']
['2021-5-4 7:36:11', 'fActWaterLevelMixTank2', '288.165557861328']
['2021-5-4 7:36:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:36:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:36:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:36:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:36:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:36:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:36:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:36:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:36:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:36:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:36:11', 'DoVa_Co2', '0']
['2021-5-4 7:36:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:36:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:36:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:36:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_2_Blue', '0']

['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:36:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:37:11', 'fKWhCounter', '3352.41967773438']
['2021-5-4 7:37:11', 'fActPhLevelMixTank1', '5.57701349258423']
['2021-5-4 7:37:11', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 7:37:11', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 7:37:11', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 7:37:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:37:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:37:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:37:11', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:37:11', 'fActCo2ValMemo', '813']
['2021-5-4 7:37:11', 'fActWaterLevelMixTank1', '276.730194091797']
['2021-5-4 7:37:11', 'fActWaterLevelMixTank2', '288.328521728516']
['2021-5-4 7:37:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:37:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:37:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:37:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:37:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:37:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:37:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:37:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:37:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:37:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:37:11', 'DoVa_Co2', '0']
['2021-5-4 7:37:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:37:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:37:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:37:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:37:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:38:11', 'fKWhCounter', '3352.61987304688']
['2021-5-4 7:38:11', 'fActPhLevelMixTank1', '5.57725763320923']
['2021-5-4 7:38:11', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 7:38:11', 'fActPhLevelMixTank2', '3.83281970024109']
['2021-5-4 7:38:11', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 7:38:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:38:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:38:11', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:38:11', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 7:38:11', 'fActCo2ValMemo', '814']
['2021-5-4 7:38:11', 'fActWaterLevelMixTank1', '276.784515380859']
['2021-5-4 7:38:11', 'fActWaterLevelMixTank2', '288.491516113281']
['2021-5-4 7:38:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:38:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:38:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:38:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:38:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:38:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:38:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:38:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:38:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:38:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:38:11', 'DoVa_Co2', '0']
['2021-5-4 7:38:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:38:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:38:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:38:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:38:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:39:12', 'fKWhCounter', '3352.71997070313']
['2021-5-4 7:39:12', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 7:39:12', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 7:39:12', 'fActPhLevelMixTank2', '3.83452868461609']
['2021-5-4 7:39:12', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 7:39:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:39:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:39:12', 'fActTempValMemo', '19.5']
['2021-5-4 7:39:12', 'fActRhValMemo', '52']
['2021-5-4 7:39:12', 'fActCo2ValMemo', '811']
['2021-5-4 7:39:12', 'fActWaterLevelMixTank1', '277.137634277344']
['2021-5-4 7:39:12', 'fActWaterLevelMixTank2', '288.953277587891']
['2021-5-4 7:39:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:39:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:39:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:39:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:39:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:39:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:39:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:39:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:39:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:39:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:39:12', 'DoVa_Co2', '0']
['2021-5-4 7:39:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:39:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:39:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:39:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:39:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:40:11', 'fKWhCounter', '3352.82006835938']
['2021-5-4 7:40:11', 'fActPhLevelMixTank1', '5.57725763320923']
['2021-5-4 7:40:11', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 7:40:11', 'fActPhLevelMixTank2', '3.83086633682251']
['2021-5-4 7:40:11', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 7:40:11', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:40:11', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:40:11', 'fActTempValMemo', '19.5']
['2021-5-4 7:40:11', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 7:40:11', 'fActCo2ValMemo', '812']
['2021-5-4 7:40:11', 'fActWaterLevelMixTank1', '277.898193359375']
['2021-5-4 7:40:11', 'fActWaterLevelMixTank2', '289.578002929688']
['2021-5-4 7:40:11', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:40:11', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:40:11', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:40:11', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:40:11', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:40:11', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:40:11', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:40:11', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:40:11', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:40:11', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:40:11', 'DoVa_Co2', '0']
['2021-5-4 7:40:11', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:40:11', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:40:11', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:40:11', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:40:11', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:41:12', 'fKWhCounter', '3353.02026367188']
['2021-5-4 7:41:12', 'fActPhLevelMixTank1', '5.57725763320923']
['2021-5-4 7:41:12', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 7:41:12', 'fActPhLevelMixTank2', '3.83184289932251']
['2021-5-4 7:41:12', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 7:41:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:41:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:41:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:41:12', 'fActRhValMemo', '52']
['2021-5-4 7:41:12', 'fActCo2ValMemo', '814']
['2021-5-4 7:41:12', 'fActWaterLevelMixTank1', '278.22412109375']
['2021-5-4 7:41:12', 'fActWaterLevelMixTank2', '289.333526611328']
['2021-5-4 7:41:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:41:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:41:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:41:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:41:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:41:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:41:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:41:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:41:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:41:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:41:12', 'DoVa_Co2', '0']
['2021-5-4 7:41:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:41:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:41:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:41:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 7:41:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:41:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:42:12', 'fKWhCounter', '3353.12036132813']
['2021-5-4 7:42:12', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 7:42:12', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 7:42:12', 'fActPhLevelMixTank2', '3.83648180961609']
['2021-5-4 7:42:12', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 7:42:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:42:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:42:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:42:12', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 7:42:12', 'fActCo2ValMemo', '810']
['2021-5-4 7:42:12', 'fActWaterLevelMixTank1', '278.550079345703']
['2021-5-4 7:42:12', 'fActWaterLevelMixTank2', '288.817443847656']
['2021-5-4 7:42:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:42:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:42:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:42:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:42:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:42:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:42:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:42:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:42:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:42:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:42:12', 'DoVa_Co2', '0']
['2021-5-4 7:42:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:42:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:42:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:42:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:42:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:43:12', 'fKWhCounter', '3353.22045898438']
['2021-5-4 7:43:12', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 7:43:12', 'fActEcLevelMixTank1', '2017.12084960938']
['2021-5-4 7:43:12', 'fActPhLevelMixTank2', '3.83111047744751']
['2021-5-4 7:43:12', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 7:43:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:43:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:43:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:43:12', 'fActRhValMemo', '52']
['2021-5-4 7:43:12', 'fActCo2ValMemo', '810']
['2021-5-4 7:43:12', 'fActWaterLevelMixTank1', '278.631561279297']
['2021-5-4 7:43:12', 'fActWaterLevelMixTank2', '289.523681640625']
['2021-5-4 7:43:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:43:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:43:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:43:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:43:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:43:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:43:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:43:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:43:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:43:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:43:12', 'DoVa_Co2', '0']
['2021-5-4 7:43:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:43:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:43:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:43:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:43:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:44:12', 'fKWhCounter', '3353.42065429688']
['2021-5-4 7:44:12', 'fActPhLevelMixTank1', '5.58238458633423']
['2021-5-4 7:44:12', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 7:44:12', 'fActPhLevelMixTank2', '3.83281970024109']
['2021-5-4 7:44:12', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 7:44:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:44:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:44:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:44:12', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:44:12', 'fActCo2ValMemo', '808']
['2021-5-4 7:44:12', 'fActWaterLevelMixTank1', '279.853881835938']
['2021-5-4 7:44:12', 'fActWaterLevelMixTank2', '290.80029296875']
['2021-5-4 7:44:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:44:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:44:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:44:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:44:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:44:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:44:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:44:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:44:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:44:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:44:12', 'DoVa_Co2', '0']
['2021-5-4 7:44:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:44:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:44:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:44:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:44:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:45:12', 'fKWhCounter', '3353.52075195313']
['2021-5-4 7:45:12', 'fActPhLevelMixTank1', '5.58018732070923']
['2021-5-4 7:45:12', 'fActEcLevelMixTank1', '2013.00085449219']
['2021-5-4 7:45:12', 'fActPhLevelMixTank2', '3.83648180961609']
['2021-5-4 7:45:12', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 7:45:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:45:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:45:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:45:12', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:45:12', 'fActCo2ValMemo', '806']
['2021-5-4 7:45:12', 'fActWaterLevelMixTank1', '280.261291503906']
['2021-5-4 7:45:12', 'fActWaterLevelMixTank2', '290.691650390625']
['2021-5-4 7:45:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:45:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:45:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:45:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:45:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:45:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:45:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:45:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:45:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:45:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:45:12', 'DoVa_Co2', '0']
['2021-5-4 7:45:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:45:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:45:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:45:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:45:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:46:12', 'fKWhCounter', '3353.72094726563']
['2021-5-4 7:46:12', 'fActPhLevelMixTank1', '5.58311700820923']
['2021-5-4 7:46:12', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 7:46:12', 'fActPhLevelMixTank2', '3.83770251274109']
['2021-5-4 7:46:12', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 7:46:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:46:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:46:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:46:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:46:12', 'fActCo2ValMemo', '804']
['2021-5-4 7:46:12', 'fActWaterLevelMixTank1', '279.120483398438']
['2021-5-4 7:46:12', 'fActWaterLevelMixTank2', '291.479370117188']
['2021-5-4 7:46:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:46:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:46:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:46:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:46:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:46:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:46:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:46:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:46:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:46:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:46:12', 'DoVa_Co2', '0']
['2021-5-4 7:46:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:46:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:46:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:46:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_3_White', '0']

['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:46:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:47:12', 'fKWhCounter', '3353.82104492188']
['2021-5-4 7:47:12', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 7:47:12', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 7:47:12', 'fActPhLevelMixTank2', '3.83574938774109']
['2021-5-4 7:47:12', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 7:47:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:47:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:47:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:47:12', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:47:12', 'fActCo2ValMemo', '803']
['2021-5-4 7:47:12', 'fActWaterLevelMixTank1', '280.85888671875']
['2021-5-4 7:47:12', 'fActWaterLevelMixTank2', '291.832458496094']
['2021-5-4 7:47:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:47:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:47:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:47:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:47:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:47:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:47:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:47:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:47:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:47:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:47:12', 'DoVa_Co2', '0']
['2021-5-4 7:47:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:47:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:47:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:47:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:47:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:48:12', 'fKWhCounter', '3353.92114257813']
['2021-5-4 7:48:12', 'fActPhLevelMixTank1', '5.58311700820923']
['2021-5-4 7:48:12', 'fActEcLevelMixTank1', '2017.2734375']
['2021-5-4 7:48:12', 'fActPhLevelMixTank2', '3.83916735649109']
['2021-5-4 7:48:12', 'fActEcLevelMixTank2', '1027.55822753906']
['2021-5-4 7:48:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:48:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:48:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:48:12', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 7:48:12', 'fActCo2ValMemo', '800']
['2021-5-4 7:48:12', 'fActWaterLevelMixTank1', '279.853881835938']
['2021-5-4 7:48:12', 'fActWaterLevelMixTank2', '292.104095458984']
['2021-5-4 7:48:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:48:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:48:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:48:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:48:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:48:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:48:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:48:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:48:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:48:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:48:12', 'DoVa_Co2', '0']
['2021-5-4 7:48:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:48:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:48:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:48:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:48:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:49:12', 'fKWhCounter', '3354.12133789063']
['2021-5-4 7:49:12', 'fActPhLevelMixTank1', '5.58311700820923']
['2021-5-4 7:49:12', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 7:49:12', 'fActPhLevelMixTank2', '3.84185314178467']
['2021-5-4 7:49:12', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 7:49:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:49:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:49:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:49:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:49:12', 'fActCo2ValMemo', '798']
['2021-5-4 7:49:12', 'fActWaterLevelMixTank1', '280.587249755859']
['2021-5-4 7:49:12', 'fActWaterLevelMixTank2', '292.076934814453']
['2021-5-4 7:49:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:49:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:49:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:49:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:49:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:49:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:49:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:49:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:49:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:49:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:49:12', 'DoVa_Co2', '0']
['2021-5-4 7:49:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:49:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:49:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:49:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:49:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:50:12', 'fKWhCounter', '3354.22143554688']
['2021-5-4 7:50:12', 'fActPhLevelMixTank1', '5.58995342254639']
['2021-5-4 7:50:12', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 7:50:12', 'fActPhLevelMixTank2', '3.83770251274109']
['2021-5-4 7:50:12', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 7:50:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:50:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:50:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:50:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:50:12', 'fActCo2ValMemo', '798']
['2021-5-4 7:50:12', 'fActWaterLevelMixTank1', '281.456451416016']
['2021-5-4 7:50:12', 'fActWaterLevelMixTank2', '291.859649658203']
['2021-5-4 7:50:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:50:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:50:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:50:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:50:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:50:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:50:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:50:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:50:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:50:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:50:12', 'DoVa_Co2', '0']

['2021-5-4 7:50:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:50:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:50:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:50:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:50:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:51:12', 'fKWhCounter', '3354.32153320313']
['2021-5-4 7:51:12', 'fActPhLevelMixTank1', '5.59581279754639']
['2021-5-4 7:51:12', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 7:51:12', 'fActPhLevelMixTank2', '3.84209728240967']
['2021-5-4 7:51:12', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 7:51:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:51:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:51:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:51:12', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 7:51:12', 'fActCo2ValMemo', '796']
['2021-5-4 7:51:12', 'fActWaterLevelMixTank1', '282.814575195313']
['2021-5-4 7:51:12', 'fActWaterLevelMixTank2', '292.511535644531']
['2021-5-4 7:51:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:51:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:51:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:51:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:51:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:51:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:51:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:51:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:51:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:51:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:51:12', 'DoVa_Co2', '0']
['2021-5-4 7:51:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:51:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:51:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:51:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:51:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:52:12', 'fKWhCounter', '3354.52172851563']
['2021-5-4 7:52:12', 'fActPhLevelMixTank1', '5.59947490692139']
['2021-5-4 7:52:12', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 7:52:12', 'fActPhLevelMixTank2', '3.84575939178467']
['2021-5-4 7:52:12', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 7:52:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:52:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:52:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:52:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:52:12', 'fActCo2ValMemo', '794']
['2021-5-4 7:52:12', 'fActWaterLevelMixTank1', '281.619415283203']
['2021-5-4 7:52:12', 'fActWaterLevelMixTank2', '292.810333251953']
['2021-5-4 7:52:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:52:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:52:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:52:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:52:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:52:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:52:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:52:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:52:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:52:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:52:12', 'DoVa_Co2', '0']
['2021-5-4 7:52:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:52:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:52:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:52:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:52:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:53:12', 'fKWhCounter', '3354.62182617188']
['2021-5-4 7:53:12', 'fActPhLevelMixTank1', '5.60142803192139']
['2021-5-4 7:53:12', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 7:53:12', 'fActPhLevelMixTank2', '3.84112071990967']
['2021-5-4 7:53:12', 'fActEcLevelMixTank2', '1028.47375488281']
['2021-5-4 7:53:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:53:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:53:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:53:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:53:12', 'fActCo2ValMemo', '796']
['2021-5-4 7:53:12', 'fActWaterLevelMixTank1', '282.162658691406']
['2021-5-4 7:53:12', 'fActWaterLevelMixTank2', '292.728820800781']
['2021-5-4 7:53:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:53:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:53:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:53:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:53:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:53:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:53:12', 'DoVa_IrrigateLevel_1_MT1', '0']

['2021-5-4 7:53:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:53:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:53:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:53:12', 'DoVa_Co2', '0']
['2021-5-4 7:53:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:53:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:53:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:53:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:53:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:54:12', 'fKWhCounter', '3354.82202148438']
['2021-5-4 7:54:12', 'fActPhLevelMixTank1', '5.60411405563354']
['2021-5-4 7:54:12', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 7:54:12', 'fActPhLevelMixTank2', '3.84429454803467']
['2021-5-4 7:54:12', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 7:54:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:54:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:54:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:54:12', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 7:54:12', 'fActCo2ValMemo', '796']
['2021-5-4 7:54:12', 'fActWaterLevelMixTank1', '283.113342285156']
['2021-5-4 7:54:12', 'fActWaterLevelMixTank2', '293.027618408203']
['2021-5-4 7:54:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:54:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:54:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:54:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:54:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:54:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:54:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:54:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:54:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:54:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:54:12', 'DoVa_Co2', '0']
['2021-5-4 7:54:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:54:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:54:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:54:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:54:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:55:12', 'fKWhCounter', '3354.92211914063']
['2021-5-4 7:55:12', 'fActPhLevelMixTank1', '5.60484647750854']
['2021-5-4 7:55:12', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 7:55:12', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 7:55:12', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 7:55:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:55:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:55:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:55:12', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 7:55:12', 'fActCo2ValMemo', '794']
['2021-5-4 7:55:12', 'fActWaterLevelMixTank1', '283.520782470703']
['2021-5-4 7:55:12', 'fActWaterLevelMixTank2', '293.326416015625']
['2021-5-4 7:55:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:55:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:55:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:55:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:55:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:55:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:55:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:55:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:55:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:55:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:55:12', 'DoVa_Co2', '0']
['2021-5-4 7:55:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:55:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:55:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:55:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:55:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:56:12', 'fKWhCounter', '3355.02221679688']
['2021-5-4 7:56:12', 'fActPhLevelMixTank1', '5.61168241500854']
['2021-5-4 7:56:12', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 7:56:12', 'fActPhLevelMixTank2', '3.84478282928467']
['2021-5-4 7:56:12', 'fActEcLevelMixTank2', '1026.18493652344']
['2021-5-4 7:56:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:56:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:56:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:56:12', 'fActRhValMemo', '52']
['2021-5-4 7:56:12', 'fActCo2ValMemo', '793']
['2021-5-4 7:56:12', 'fActWaterLevelMixTank1', '284.281341552734']
['2021-5-4 7:56:12', 'fActWaterLevelMixTank2', '293.896820068359']
['2021-5-4 7:56:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:56:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:56:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:56:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:56:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:56:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:56:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:56:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:56:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:56:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:56:12', 'DoVa_Co2', '0']
['2021-5-4 7:56:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:56:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:56:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:56:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:56:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:57:12', 'fKWhCounter', '3355.22241210938']
['2021-5-4 7:57:12', 'fActPhLevelMixTank1', '5.61070585250854']
['2021-5-4 7:57:12', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 7:57:12', 'fActPhLevelMixTank2', '3.84820103645325']
['2021-5-4 7:57:12', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 7:57:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:57:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:57:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:57:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:57:12', 'fActCo2ValMemo', '791']
['2021-5-4 7:57:12', 'fActWaterLevelMixTank1', '284.145538330078']
['2021-5-4 7:57:12', 'fActWaterLevelMixTank2', '293.869659423828']
['2021-5-4 7:57:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:57:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:57:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:57:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:57:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:57:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:57:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:57:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:57:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:57:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:57:12', 'DoVa_Co2', '0']
['2021-5-4 7:57:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:57:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:57:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:57:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:57:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:58:12', 'fKWhCounter', '3355.32250976563']
['2021-5-4 7:58:12', 'fActPhLevelMixTank1', '5.61485624313354']
['2021-5-4 7:58:12', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 7:58:12', 'fActPhLevelMixTank2', '3.85039830207825']
['2021-5-4 7:58:12', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 7:58:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:58:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:58:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 7:58:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 7:58:12', 'fActCo2ValMemo', '792']
['2021-5-4 7:58:12', 'fActWaterLevelMixTank1', '284.362823486328']
['2021-5-4 7:58:12', 'fActWaterLevelMixTank2', '294.956146240234']
['2021-5-4 7:58:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:58:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:58:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:58:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:58:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:58:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:58:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:58:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:58:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:58:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:58:12', 'DoVa_Co2', '0']
['2021-5-4 7:58:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:58:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:58:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:58:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_1_White', '0']

['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:58:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 7:59:12', 'fKWhCounter', '3355.52270507813']
['2021-5-4 7:59:12', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 7:59:12', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 7:59:12', 'fActPhLevelMixTank2', '3.85186314582825']
['2021-5-4 7:59:12', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 7:59:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 7:59:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 7:59:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 7:59:12', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 7:59:12', 'fActCo2ValMemo', '790']
['2021-5-4 7:59:12', 'fActWaterLevelMixTank1', '284.960388183594']
['2021-5-4 7:59:12', 'fActWaterLevelMixTank2', '294.222747802734']
['2021-5-4 7:59:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 7:59:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 7:59:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 7:59:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 7:59:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 7:59:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 7:59:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 7:59:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 7:59:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 7:59:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 7:59:12', 'DoVa_Co2', '0']
['2021-5-4 7:59:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 7:59:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 7:59:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 7:59:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 7:59:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:0:12', 'fKWhCounter', '3355.62280273438']
['2021-5-4 8:0:12', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 8:0:12', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 8:0:12', 'fActPhLevelMixTank2', '3.84966588020325']
['2021-5-4 8:0:12', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 8:0:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:0:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:0:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:0:12', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 8:0:12', 'fActCo2ValMemo', '790']
['2021-5-4 8:0:12', 'fActWaterLevelMixTank1', '285.6123046875']
['2021-5-4 8:0:12', 'fActWaterLevelMixTank2', '294.494384765625']
['2021-5-4 8:0:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:0:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:0:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:0:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:0:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:0:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:0:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:0:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:0:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:0:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:0:12', 'DoVa_Co2', '0']
['2021-5-4 8:0:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:0:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:0:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:0:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:0:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:1:12', 'fKWhCounter', '3355.72290039063']
['2021-5-4 8:1:12', 'fActPhLevelMixTank1', '5.61192655563354']
['2021-5-4 8:1:12', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 8:1:12', 'fActPhLevelMixTank2', '3.85454869270325']
['2021-5-4 8:1:12', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 8:1:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:1:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:1:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:1:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:1:12', 'fActCo2ValMemo', '794']
['2021-5-4 8:1:12', 'fActWaterLevelMixTank1', '285.476470947266']
['2021-5-4 8:1:12', 'fActWaterLevelMixTank2', '295.010467529297']
['2021-5-4 8:1:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:1:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:1:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:1:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:1:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:1:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:1:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:1:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:1:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:1:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:1:12', 'DoVa_Co2', '0']
['2021-5-4 8:1:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:1:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:1:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:1:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:1:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:2:12', 'fKWhCounter', '3355.92309570313']
['2021-5-4 8:2:12', 'fActPhLevelMixTank1', '5.60972929000854']
['2021-5-4 8:2:12', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 8:2:12', 'fActPhLevelMixTank2', '3.85454869270325']
['2021-5-4 8:2:12', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 8:2:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:2:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:2:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:2:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:2:12', 'fActCo2ValMemo', '791']
['2021-5-4 8:2:12', 'fActWaterLevelMixTank1', '285.965393066406']
['2021-5-4 8:2:12', 'fActWaterLevelMixTank2', '295.445068359375']
['2021-5-4 8:2:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:2:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:2:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:2:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:2:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:2:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:2:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:2:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:2:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:2:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:2:12', 'DoVa_Co2', '0']
['2021-5-4 8:2:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:2:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:2:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:2:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:2:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:3:12', 'fKWhCounter', '3356.02319335938']
['2021-5-4 8:3:12', 'fActPhLevelMixTank1', '5.61387968063354']
['2021-5-4 8:3:12', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 8:3:12', 'fActPhLevelMixTank2', '3.85161900520325']
['2021-5-4 8:3:12', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 8:3:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:3:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:3:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:3:12', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 8:3:12', 'fActCo2ValMemo', '793']
['2021-5-4 8:3:12', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 8:3:12', 'fActWaterLevelMixTank2', '295.906829833984']
['2021-5-4 8:3:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:3:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:3:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:3:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:3:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:3:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:3:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:3:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:3:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:3:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:3:12', 'DoVa_Co2', '0']
['2021-5-4 8:3:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:3:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:3:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:3:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 8:3:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:3:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:4:12', 'fKWhCounter', '3356.22338867188']
['2021-5-4 8:4:12', 'fActPhLevelMixTank1', '5.6231575012207']
['2021-5-4 8:4:12', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 8:4:12', 'fActPhLevelMixTank2', '3.85674619674683']
['2021-5-4 8:4:12', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 8:4:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:4:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:4:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:4:12', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 8:4:12', 'fActCo2ValMemo', '794']
['2021-5-4 8:4:12', 'fActWaterLevelMixTank1', '286.671630859375']
['2021-5-4 8:4:12', 'fActWaterLevelMixTank2', '295.988311767578']
['2021-5-4 8:4:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:4:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:4:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:4:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:4:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:4:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:4:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:4:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:4:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:4:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:4:12', 'DoVa_Co2', '0']
['2021-5-4 8:4:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:4:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:4:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:4:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:4:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:5:12', 'fKWhCounter', '3356.32348632813']
['2021-5-4 8:5:12', 'fActPhLevelMixTank1', '5.6204719543457']
['2021-5-4 8:5:12', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 8:5:12', 'fActPhLevelMixTank2', '3.85723447799683']
['2021-5-4 8:5:12', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 8:5:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:5:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:5:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:5:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:5:12', 'fActCo2ValMemo', '793']
['2021-5-4 8:5:12', 'fActWaterLevelMixTank1', '286.590148925781']
['2021-5-4 8:5:12', 'fActWaterLevelMixTank2', '295.988311767578']
['2021-5-4 8:5:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:5:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:5:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:5:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:5:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:5:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:5:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:5:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:5:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:5:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:5:12', 'DoVa_Co2', '0']
['2021-5-4 8:5:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:5:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:5:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:5:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:5:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:6:12', 'fKWhCounter', '3356.42358398438']
['2021-5-4 8:6:12', 'fActPhLevelMixTank1', '5.6192512512207']
['2021-5-4 8:6:12', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 8:6:12', 'fActPhLevelMixTank2', '3.85430455207825']
['2021-5-4 8:6:12', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 8:6:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:6:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:6:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:6:12', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 8:6:12', 'fActCo2ValMemo', '788']
['2021-5-4 8:6:12', 'fActWaterLevelMixTank1', '286.970397949219']
['2021-5-4 8:6:12', 'fActWaterLevelMixTank2', '296.151275634766']
['2021-5-4 8:6:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:6:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:6:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:6:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:6:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:6:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:6:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:6:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:6:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:6:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:6:12', 'DoVa_Co2', '0']
['2021-5-4 8:6:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:6:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:6:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:6:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']

['2021-5-4 8:6:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:6:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:7:12', 'fKWhCounter', '3356.62377929688']
['2021-5-4 8:7:12', 'fActPhLevelMixTank1', '5.6187629699707']
['2021-5-4 8:7:12', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 8:7:12', 'fActPhLevelMixTank2', '3.85723447799683']
['2021-5-4 8:7:12', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 8:7:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:7:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:7:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:7:12', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 8:7:12', 'fActCo2ValMemo', '786']
['2021-5-4 8:7:12', 'fActWaterLevelMixTank1', '287.812438964844']
['2021-5-4 8:7:12', 'fActWaterLevelMixTank2', '296.422912597656']
['2021-5-4 8:7:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:7:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:7:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:7:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:7:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:7:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:7:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:7:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:7:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:7:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:7:12', 'DoVa_Co2', '0']
['2021-5-4 8:7:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:7:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:7:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:7:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:7:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:8:12', 'fKWhCounter', '3356.72387695313']
['2021-5-4 8:8:12', 'fActPhLevelMixTank1', '5.6234016418457']
['2021-5-4 8:8:12', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 8:8:12', 'fActPhLevelMixTank2', '3.85918760299683']
['2021-5-4 8:8:12', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 8:8:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:8:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:8:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:8:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:8:12', 'fActCo2ValMemo', '783']
['2021-5-4 8:8:12', 'fActWaterLevelMixTank1', '287.567993164063']
['2021-5-4 8:8:12', 'fActWaterLevelMixTank2', '296.721710205078']
['2021-5-4 8:8:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:8:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:8:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:8:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:8:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:8:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:8:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:8:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:8:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:8:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:8:12', 'DoVa_Co2', '0']
['2021-5-4 8:8:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:8:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:8:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:8:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:8:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:9:12', 'fKWhCounter', '3356.82397460938']
['2021-5-4 8:9:12', 'fActPhLevelMixTank1', '5.6251106262207']
['2021-5-4 8:9:12', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 8:9:12', 'fActPhLevelMixTank2', '3.85723447799683']
['2021-5-4 8:9:12', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 8:9:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:9:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:9:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:9:12', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 8:9:12', 'fActCo2ValMemo', '781']
['2021-5-4 8:9:12', 'fActWaterLevelMixTank1', '287.73095703125']
['2021-5-4 8:9:12', 'fActWaterLevelMixTank2', '297.590881347656']
['2021-5-4 8:9:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:9:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:9:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:9:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:9:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:9:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:9:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:9:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:9:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:9:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:9:12', 'DoVa_Co2', '0']
['2021-5-4 8:9:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:9:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:9:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:9:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:9:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:10:12', 'fKWhCounter', '3357.02416992188']
['2021-5-4 8:10:12', 'fActPhLevelMixTank1', '5.63512086868286']
['2021-5-4 8:10:12', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 8:10:12', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 8:10:12', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 8:10:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:10:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:10:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:10:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:10:12', 'fActCo2ValMemo', '780']
['2021-5-4 8:10:12', 'fActWaterLevelMixTank1', '288.437164306641']
['2021-5-4 8:10:12', 'fActWaterLevelMixTank2', '297.427917480469']
['2021-5-4 8:10:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:10:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:10:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:10:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:10:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:10:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:10:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:10:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:10:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:10:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:10:12', 'DoVa_Co2', '0']
['2021-5-4 8:10:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:10:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:10:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:10:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:10:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:11:12', 'fKWhCounter', '3357.12426757813']
['2021-5-4 8:11:12', 'fActPhLevelMixTank1', '5.63707399368286']
['2021-5-4 8:11:12', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 8:11:12', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 8:11:12', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 8:11:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:11:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:11:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:11:12', 'fActRhValMemo', '51.5']
['2021-5-4 8:11:12', 'fActCo2ValMemo', '781']
['2021-5-4 8:11:12', 'fActWaterLevelMixTank1', '288.763122558594']
['2021-5-4 8:11:12', 'fActWaterLevelMixTank2', '298.052642822266']
['2021-5-4 8:11:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:11:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:11:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:11:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:11:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:11:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:11:12', 'DoVa_IrrigateLevel_1_MT1', '0']

['2021-5-4 8:11:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:11:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:11:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:11:12', 'DoVa_Co2', '0']
['2021-5-4 8:11:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:11:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:11:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:11:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:11:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:12:12', 'fKWhCounter', '3357.32446289063']
['2021-5-4 8:12:12', 'fActPhLevelMixTank1', '5.6299934387207']
['2021-5-4 8:12:12', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 8:12:12', 'fActPhLevelMixTank2', '3.85650205612183']
['2021-5-4 8:12:12', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 8:12:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:12:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:12:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:12:12', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 8:12:12', 'fActCo2ValMemo', '784']
['2021-5-4 8:12:12', 'fActWaterLevelMixTank1', '288.871765136719']
['2021-5-4 8:12:12', 'fActWaterLevelMixTank2', '298.052642822266']
['2021-5-4 8:12:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:12:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:12:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:12:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:12:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:12:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:12:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:12:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:12:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:12:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:12:12', 'DoVa_Co2', '0']
['2021-5-4 8:12:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:12:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:12:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:12:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:12:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:13:12', 'fKWhCounter', '3357.42456054688']
['2021-5-4 8:13:12', 'fActPhLevelMixTank1', '5.63463258743286']
['2021-5-4 8:13:12', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 8:13:12', 'fActPhLevelMixTank2', '3.86016416549683']
['2021-5-4 8:13:12', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 8:13:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:13:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:13:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:13:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:13:12', 'fActCo2ValMemo', '783']
['2021-5-4 8:13:12', 'fActWaterLevelMixTank1', '289.333526611328']
['2021-5-4 8:13:12', 'fActWaterLevelMixTank2', '298.079803466797']
['2021-5-4 8:13:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:13:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:13:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:13:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:13:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:13:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:13:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:13:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:13:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:13:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:13:12', 'DoVa_Co2', '0']
['2021-5-4 8:13:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:13:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:13:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:13:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:13:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:14:12', 'fKWhCounter', '3357.52465820313']
['2021-5-4 8:14:12', 'fActPhLevelMixTank1', '5.63463258743286']
['2021-5-4 8:14:12', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 8:14:12', 'fActPhLevelMixTank2', '3.86333823204041']
['2021-5-4 8:14:12', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 8:14:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:14:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:14:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:14:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:14:12', 'fActCo2ValMemo', '783']
['2021-5-4 8:14:12', 'fActWaterLevelMixTank1', '289.659484863281']
['2021-5-4 8:14:12', 'fActWaterLevelMixTank2', '298.541564941406']
['2021-5-4 8:14:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:14:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:14:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:14:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:14:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:14:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:14:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:14:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:14:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:14:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:14:12', 'DoVa_Co2', '0']
['2021-5-4 8:14:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:14:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:14:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:14:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:14:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:15:12', 'fKWhCounter', '3357.72485351563']
['2021-5-4 8:15:12', 'fActPhLevelMixTank1', '5.64000368118286']
['2021-5-4 8:15:12', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 8:15:12', 'fActPhLevelMixTank2', '3.86016416549683']
['2021-5-4 8:15:12', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 8:15:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:15:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:15:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:15:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:15:12', 'fActCo2ValMemo', '782']
['2021-5-4 8:15:12', 'fActWaterLevelMixTank1', '289.252044677734']
['2021-5-4 8:15:12', 'fActWaterLevelMixTank2', '298.297119140625']
['2021-5-4 8:15:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:15:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:15:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:15:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:15:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:15:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:15:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:15:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:15:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:15:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:15:12', 'DoVa_Co2', '0']
['2021-5-4 8:15:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:15:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:15:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:15:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_2_Fred', '0']

['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:15:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:16:12', 'fKWhCounter', '3357.82495117188']
['2021-5-4 8:16:12', 'fActPhLevelMixTank1', '5.64806032180786']
['2021-5-4 8:16:12', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 8:16:12', 'fActPhLevelMixTank2', '3.86480307579041']
['2021-5-4 8:16:12', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 8:16:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:16:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:16:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:16:12', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 8:16:12', 'fActCo2ValMemo', '777']
['2021-5-4 8:16:12', 'fActWaterLevelMixTank1', '290.012603759766']
['2021-5-4 8:16:12', 'fActWaterLevelMixTank2', '299.274963378906']
['2021-5-4 8:16:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:16:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:16:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:16:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:16:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:16:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:16:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:16:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:16:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:16:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:16:12', 'DoVa_Co2', '0']
['2021-5-4 8:16:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:16:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:16:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:16:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:16:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:17:12', 'fKWhCounter', '3358.02514648438']
['2021-5-4 8:17:12', 'fActPhLevelMixTank1', '5.65025806427002']
['2021-5-4 8:17:12', 'fActEcLevelMixTank1', '2028.87048339844']
['2021-5-4 8:17:12', 'fActPhLevelMixTank2', '3.86504721641541']
['2021-5-4 8:17:12', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 8:17:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:17:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:17:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:17:12', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 8:17:12', 'fActCo2ValMemo', '775']
['2021-5-4 8:17:12', 'fActWaterLevelMixTank1', '290.229888916016']
['2021-5-4 8:17:12', 'fActWaterLevelMixTank2', '299.166320800781']
['2021-5-4 8:17:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:17:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:17:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:17:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:17:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:17:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:17:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:17:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:17:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:17:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:17:12', 'DoVa_Co2', '0']
['2021-5-4 8:17:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:17:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:17:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:17:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:17:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:18:12', 'fKWhCounter', '3358.12524414063']
['2021-5-4 8:18:12', 'fActPhLevelMixTank1', '5.65099048614502']
['2021-5-4 8:18:12', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 8:18:12', 'fActPhLevelMixTank2', '3.86480307579041']
['2021-5-4 8:18:12', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 8:18:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:18:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:18:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:18:12', 'fActRhValMemo', '52']
['2021-5-4 8:18:12', 'fActCo2ValMemo', '777']
['2021-5-4 8:18:12', 'fActWaterLevelMixTank1', '291.234893798828']
['2021-5-4 8:18:12', 'fActWaterLevelMixTank2', '299.628082275391']
['2021-5-4 8:18:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:18:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:18:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:18:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:18:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:18:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:18:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:18:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:18:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:18:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:18:12', 'DoVa_Co2', '0']
['2021-5-4 8:18:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:18:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:18:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:18:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:18:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:19:12', 'fKWhCounter', '3358.22534179688']
['2021-5-4 8:19:12', 'fActPhLevelMixTank1', '5.64635133743286']
['2021-5-4 8:19:12', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 8:19:12', 'fActPhLevelMixTank2', '3.86602377891541']
['2021-5-4 8:19:12', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 8:19:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:19:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:19:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:19:12', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 8:19:12', 'fActCo2ValMemo', '779']
['2021-5-4 8:19:12', 'fActWaterLevelMixTank1', '290.311370849609']
['2021-5-4 8:19:12', 'fActWaterLevelMixTank2', '299.437927246094']
['2021-5-4 8:19:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:19:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:19:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:19:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:19:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:19:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:19:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:19:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:19:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:19:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:19:12', 'DoVa_Co2', '0']
['2021-5-4 8:19:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:19:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:19:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:19:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:19:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:20:12', 'fKWhCounter', '3358.42553710938']
['2021-5-4 8:20:12', 'fActPhLevelMixTank1', '5.65025806427002']
['2021-5-4 8:20:12', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 8:20:12', 'fActPhLevelMixTank2', '3.87041831016541']
['2021-5-4 8:20:12', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 8:20:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:20:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:20:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:20:12', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 8:20:12', 'fActCo2ValMemo', '777']
['2021-5-4 8:20:12', 'fActWaterLevelMixTank1', '291.153411865234']
['2021-5-4 8:20:12', 'fActWaterLevelMixTank2', '299.899688720703']
['2021-5-4 8:20:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:20:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:20:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:20:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:20:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:20:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:20:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:20:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:20:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:20:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:20:12', 'DoVa_Co2', '0']
['2021-5-4 8:20:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:20:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:20:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:20:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_2_Blue', '0']

['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:20:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:21:12', 'fKWhCounter', '3358.52563476563']
['2021-5-4 8:21:12', 'fActPhLevelMixTank1', '5.65416431427002']
['2021-5-4 8:21:12', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 8:21:12', 'fActPhLevelMixTank2', '3.86870932579041']
['2021-5-4 8:21:12', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 8:21:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:21:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:21:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:21:12', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 8:21:12', 'fActCo2ValMemo', '776']
['2021-5-4 8:21:12', 'fActWaterLevelMixTank1', '291.370727539063']
['2021-5-4 8:21:12', 'fActWaterLevelMixTank2', '300.279968261719']
['2021-5-4 8:21:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:21:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:21:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:21:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:21:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:21:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:21:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:21:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:21:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:21:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:21:12', 'DoVa_Co2', '0']
['2021-5-4 8:21:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:21:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:21:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:21:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:21:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:22:12', 'fKWhCounter', '3358.62573242188']
['2021-5-4 8:22:12', 'fActPhLevelMixTank1', '5.66197681427002']
['2021-5-4 8:22:12', 'fActEcLevelMixTank1', '2031.46459960938']
['2021-5-4 8:22:12', 'fActPhLevelMixTank2', '3.86895346641541']
['2021-5-4 8:22:12', 'fActEcLevelMixTank2', '1038.544921875']
['2021-5-4 8:22:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:22:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:22:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:22:12', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 8:22:12', 'fActCo2ValMemo', '775']
['2021-5-4 8:22:12', 'fActWaterLevelMixTank1', '289.768127441406']
['2021-5-4 8:22:12', 'fActWaterLevelMixTank2', '300.578765869141']
['2021-5-4 8:22:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:22:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:22:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:22:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:22:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:22:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:22:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:22:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:22:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:22:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:22:12', 'DoVa_Co2', '0']
['2021-5-4 8:22:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:22:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:22:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:22:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:22:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:23:13', 'fKWhCounter', '3358.82592773438']
['2021-5-4 8:23:13', 'fActPhLevelMixTank1', '5.66197681427002']
['2021-5-4 8:23:13', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 8:23:13', 'fActPhLevelMixTank2', '3.86309385299683']
['2021-5-4 8:23:13', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 8:23:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:23:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:23:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:23:13', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 8:23:13', 'fActCo2ValMemo', '772']
['2021-5-4 8:23:13', 'fActWaterLevelMixTank1', '291.316375732422']
['2021-5-4 8:23:13', 'fActWaterLevelMixTank2', '300.388610839844']
['2021-5-4 8:23:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:23:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:23:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:23:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:23:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:23:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:23:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:23:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:23:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:23:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:23:13', 'DoVa_Co2', '0']
['2021-5-4 8:23:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:23:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:23:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:23:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_4_Red', '0']

['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:23:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:24:12', 'fKWhCounter', '3358.92602539063']
['2021-5-4 8:24:12', 'fActPhLevelMixTank1', '5.66734838485718']
['2021-5-4 8:24:12', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 8:24:12', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 8:24:12', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 8:24:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:24:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:24:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:24:12', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 8:24:12', 'fActCo2ValMemo', '773']
['2021-5-4 8:24:12', 'fActWaterLevelMixTank1', '291.180572509766']
['2021-5-4 8:24:12', 'fActWaterLevelMixTank2', '300.415771484375']
['2021-5-4 8:24:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:24:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:24:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:24:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:24:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:24:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:24:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:24:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:24:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:24:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:24:12', 'DoVa_Co2', '0']
['2021-5-4 8:24:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:24:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:24:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:24:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:24:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:25:12', 'fKWhCounter', '3359.12622070313']
['2021-5-4 8:25:12', 'fActPhLevelMixTank1', '5.66392993927002']
['2021-5-4 8:25:12', 'fActEcLevelMixTank1', '2028.87048339844']
['2021-5-4 8:25:12', 'fActPhLevelMixTank2', '3.86846518516541']
['2021-5-4 8:25:12', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 8:25:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:25:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:25:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:25:12', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 8:25:12', 'fActCo2ValMemo', '775']
['2021-5-4 8:25:12', 'fActWaterLevelMixTank1', '291.071929931641']
['2021-5-4 8:25:12', 'fActWaterLevelMixTank2', '301.312133789063']
['2021-5-4 8:25:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:25:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:25:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:25:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:25:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:25:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:25:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:25:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:25:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:25:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:25:12', 'DoVa_Co2', '0']
['2021-5-4 8:25:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:25:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:25:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:25:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:25:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:26:12', 'fKWhCounter', '3359.22631835938']
['2021-5-4 8:26:12', 'fActPhLevelMixTank1', '5.66588354110718']
['2021-5-4 8:26:12', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 8:26:12', 'fActPhLevelMixTank2', '3.87383651733398']
['2021-5-4 8:26:12', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 8:26:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:26:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:26:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:26:12', 'fActRhValMemo', '51.5']
['2021-5-4 8:26:12', 'fActCo2ValMemo', '775']
['2021-5-4 8:26:12', 'fActWaterLevelMixTank1', '291.995452880859']
['2021-5-4 8:26:12', 'fActWaterLevelMixTank2', '301.203491210938']
['2021-5-4 8:26:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:26:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:26:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:26:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:26:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:26:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:26:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:26:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:26:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:26:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:26:12', 'DoVa_Co2', '0']
['2021-5-4 8:26:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:26:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:26:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:26:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:26:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:27:13', 'fKWhCounter', '3359.32641601563']
['2021-5-4 8:27:13', 'fActPhLevelMixTank1', '5.66783666610718']
['2021-5-4 8:27:13', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 8:27:13', 'fActPhLevelMixTank2', '3.87359237670898']
['2021-5-4 8:27:13', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 8:27:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:27:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:27:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:27:13', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 8:27:13', 'fActCo2ValMemo', '774']
['2021-5-4 8:27:13', 'fActWaterLevelMixTank1', '292.511535644531']
['2021-5-4 8:27:13', 'fActWaterLevelMixTank2', '301.801055908203']
['2021-5-4 8:27:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:27:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:27:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:27:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:27:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:27:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:27:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:27:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:27:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:27:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:27:13', 'DoVa_Co2', '0']
['2021-5-4 8:27:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:27:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:27:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:27:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:27:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:28:12', 'fKWhCounter', '3359.52661132813']
['2021-5-4 8:28:12', 'fActPhLevelMixTank1', '5.66759252548218']
['2021-5-4 8:28:12', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 8:28:12', 'fActPhLevelMixTank2', '3.87041831016541']
['2021-5-4 8:28:12', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 8:28:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:28:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:28:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:28:12', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 8:28:12', 'fActCo2ValMemo', '772']
['2021-5-4 8:28:12', 'fActWaterLevelMixTank1', '292.837493896484']
['2021-5-4 8:28:12', 'fActWaterLevelMixTank2', '301.583770751953']
['2021-5-4 8:28:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:28:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:28:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:28:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:28:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:28:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:28:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:28:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:28:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:28:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:28:12', 'DoVa_Co2', '0']
['2021-5-4 8:28:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:28:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:28:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:28:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']

['2021-5-4 8:28:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:28:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:29:13', 'fKWhCounter', '3359.62670898438']
['2021-5-4 8:29:13', 'fActPhLevelMixTank1', '5.67442846298218']
['2021-5-4 8:29:13', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 8:29:13', 'fActPhLevelMixTank2', '3.86797690391541']
['2021-5-4 8:29:13', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 8:29:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:29:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:29:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:29:13', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 8:29:13', 'fActCo2ValMemo', '771']
['2021-5-4 8:29:13', 'fActWaterLevelMixTank1', '293.190582275391']
['2021-5-4 8:29:13', 'fActWaterLevelMixTank2', '302.20849609375']
['2021-5-4 8:29:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:29:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:29:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:29:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:29:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:29:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:29:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:29:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:29:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:29:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:29:13', 'DoVa_Co2', '0']
['2021-5-4 8:29:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:29:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:29:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:29:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:29:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:30:12', 'fKWhCounter', '3359.82690429688']
['2021-5-4 8:30:12', 'fActPhLevelMixTank1', '5.67369604110718']
['2021-5-4 8:30:12', 'fActEcLevelMixTank1', '2032.53271484375']
['2021-5-4 8:30:12', 'fActPhLevelMixTank2', '3.87749862670898']
['2021-5-4 8:30:12', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 8:30:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:30:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:30:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:30:12', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 8:30:12', 'fActCo2ValMemo', '770']
['2021-5-4 8:30:12', 'fActWaterLevelMixTank1', '293.516540527344']
['2021-5-4 8:30:12', 'fActWaterLevelMixTank2', '302.806060791016']
['2021-5-4 8:30:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:30:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:30:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:30:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:30:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:30:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:30:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:30:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:30:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:30:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:30:12', 'DoVa_Co2', '0']
['2021-5-4 8:30:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:30:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:30:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:30:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:30:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:31:13', 'fKWhCounter', '3359.92700195313']
['2021-5-4 8:31:13', 'fActPhLevelMixTank1', '5.67149877548218']
['2021-5-4 8:31:13', 'fActEcLevelMixTank1', '2032.68530273438']
['2021-5-4 8:31:13', 'fActPhLevelMixTank2', '3.87554550170898']
['2021-5-4 8:31:13', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 8:31:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:31:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:31:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:31:13', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 8:31:13', 'fActCo2ValMemo', '773']
['2021-5-4 8:31:13', 'fActWaterLevelMixTank1', '292.620178222656']
['2021-5-4 8:31:13', 'fActWaterLevelMixTank2', '302.588775634766']
['2021-5-4 8:31:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:31:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:31:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:31:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:31:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:31:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:31:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:31:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:31:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:31:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:31:13', 'DoVa_Co2', '0']
['2021-5-4 8:31:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:31:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:31:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:31:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:31:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:32:12', 'fKWhCounter', '3360.02709960938']
['2021-5-4 8:32:12', 'fActPhLevelMixTank1', '5.67882299423218']
['2021-5-4 8:32:12', 'fActEcLevelMixTank1', '2034.97424316406']
['2021-5-4 8:32:12', 'fActPhLevelMixTank2', '3.87994027137756']
['2021-5-4 8:32:12', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 8:32:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:32:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:32:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:32:12', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 8:32:12', 'fActCo2ValMemo', '774']
['2021-5-4 8:32:12', 'fActWaterLevelMixTank1', '293.951141357422']
['2021-5-4 8:32:12', 'fActWaterLevelMixTank2', '303.023376464844']
['2021-5-4 8:32:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:32:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:32:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:32:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:32:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:32:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:32:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:32:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:32:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:32:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:32:12', 'DoVa_Co2', '0']
['2021-5-4 8:32:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:32:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:32:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:32:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:32:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:33:13', 'fKWhCounter', '3360.22729492188']
['2021-5-4 8:33:13', 'fActPhLevelMixTank1', '5.68297386169434']
['2021-5-4 8:33:13', 'fActEcLevelMixTank1', '2034.82165527344']
['2021-5-4 8:33:13', 'fActPhLevelMixTank2', '3.87920784950256']
['2021-5-4 8:33:13', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 8:33:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:33:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:33:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:33:13', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 8:33:13', 'fActCo2ValMemo', '771']
['2021-5-4 8:33:13', 'fActWaterLevelMixTank1', '293.923980712891']
['2021-5-4 8:33:13', 'fActWaterLevelMixTank2', '302.751739501953']
['2021-5-4 8:33:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:33:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:33:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:33:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:33:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:33:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:33:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:33:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:33:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:33:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:33:13', 'DoVa_Co2', '0']
['2021-5-4 8:33:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:33:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:33:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:33:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:33:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:34:12', 'fKWhCounter', '3360.32739257813']
['2021-5-4 8:34:12', 'fActPhLevelMixTank1', '5.63951539993286']
['2021-5-4 8:34:12', 'fActEcLevelMixTank1', '2079.53125']
['2021-5-4 8:34:12', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 8:34:12', 'fActEcLevelMixTank2', '1058.07678222656']
['2021-5-4 8:34:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:34:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:34:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:34:12', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 8:34:12', 'fActCo2ValMemo', '772']
['2021-5-4 8:34:12', 'fActWaterLevelMixTank1', '295.743865966797']
['2021-5-4 8:34:12', 'fActWaterLevelMixTank2', '284.525787353516']
['2021-5-4 8:34:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:34:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:34:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:34:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:34:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:34:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:34:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:34:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:34:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:34:12', 'DoVa_IrrigateLevel_2_MT2', '0']

['2021-5-4 8:34:12', 'DoVa_Co2', '0']
['2021-5-4 8:34:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:34:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:34:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:34:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:34:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:35:13', 'fKWhCounter', '3360.52758789063']
['2021-5-4 8:35:13', 'fActPhLevelMixTank1', '5.57310724258423']
['2021-5-4 8:35:13', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 8:35:13', 'fActPhLevelMixTank2', '3.77959537506104']
['2021-5-4 8:35:13', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 8:35:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:35:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:35:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:35:13', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 8:35:13', 'fActCo2ValMemo', '766']
['2021-5-4 8:35:13', 'fActWaterLevelMixTank1', '284.960388183594']
['2021-5-4 8:35:13', 'fActWaterLevelMixTank2', '316.387268066406']
['2021-5-4 8:35:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:35:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:35:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:35:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:35:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:35:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:35:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:35:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:35:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:35:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:35:13', 'DoVa_Co2', '0']
['2021-5-4 8:35:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:35:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:35:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:35:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:35:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:36:12', 'fKWhCounter', '3360.62768554688']
['2021-5-4 8:36:12', 'fActPhLevelMixTank1', '5.56675910949707']
['2021-5-4 8:36:12', 'fActEcLevelMixTank1', '2014.67944335938']
['2021-5-4 8:36:12', 'fActPhLevelMixTank2', '3.78740811347961']
['2021-5-4 8:36:12', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 8:36:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:36:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:36:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:36:12', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 8:36:12', 'fActCo2ValMemo', '767']
['2021-5-4 8:36:12', 'fActWaterLevelMixTank1', '281.863891601563']
['2021-5-4 8:36:12', 'fActWaterLevelMixTank2', '308.890441894531']
['2021-5-4 8:36:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:36:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:36:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:36:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:36:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:36:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:36:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:36:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:36:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:36:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:36:12', 'DoVa_Co2', '0']
['2021-5-4 8:36:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:36:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:36:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:36:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:36:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:37:13', 'fKWhCounter', '3360.82788085938']
['2021-5-4 8:37:13', 'fActPhLevelMixTank1', '5.56553840637207']
['2021-5-4 8:37:13', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 8:37:13', 'fActPhLevelMixTank2', '3.79815053939819']
['2021-5-4 8:37:13', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 8:37:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:37:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:37:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:37:13', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 8:37:13', 'fActCo2ValMemo', '766']
['2021-5-4 8:37:13', 'fActWaterLevelMixTank1', '275.15478515625']
['2021-5-4 8:37:13', 'fActWaterLevelMixTank2', '312.475860595703']
['2021-5-4 8:37:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:37:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:37:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:37:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:37:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:37:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:37:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:37:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:37:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:37:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:37:13', 'DoVa_Co2', '0']
['2021-5-4 8:37:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:37:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:37:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:37:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:37:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:38:12', 'fKWhCounter', '3361.02807617188']
['2021-5-4 8:38:12', 'fActPhLevelMixTank1', '5.56749153137207']
['2021-5-4 8:38:12', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 8:38:12', 'fActPhLevelMixTank2', '3.79473257064819']
['2021-5-4 8:38:12', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 8:38:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:38:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:38:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:38:12', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 8:38:12', 'fActCo2ValMemo', '763']
['2021-5-4 8:38:12', 'fActWaterLevelMixTank1', '279.147644042969']
['2021-5-4 8:38:12', 'fActWaterLevelMixTank2', '309.325042724609']
['2021-5-4 8:38:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:38:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:38:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:38:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:38:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:38:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:38:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:38:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:38:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:38:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:38:12', 'DoVa_Co2', '0']
['2021-5-4 8:38:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:38:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:38:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:38:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:38:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:39:12', 'fKWhCounter', '3361.22827148438']
['2021-5-4 8:39:12', 'fActPhLevelMixTank1', '5.57530450820923']
['2021-5-4 8:39:12', 'fActEcLevelMixTank1', '2017.12084960938']
['2021-5-4 8:39:12', 'fActPhLevelMixTank2', '3.81060218811035']
['2021-5-4 8:39:12', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 8:39:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:39:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:39:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:39:12', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 8:39:12', 'fActCo2ValMemo', '764']
['2021-5-4 8:39:12', 'fActWaterLevelMixTank1', '280.424285888672']
['2021-5-4 8:39:12', 'fActWaterLevelMixTank2', '293.625183105469']
['2021-5-4 8:39:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:39:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:39:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:39:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:39:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:39:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:39:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:39:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:39:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:39:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:39:12', 'DoVa_Co2', '0']
['2021-5-4 8:39:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:39:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:39:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:39:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_2_Red', '0']

['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:39:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:40:12', 'fKWhCounter', '3361.32836914063']
['2021-5-4 8:40:12', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 8:40:12', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 8:40:12', 'fActPhLevelMixTank2', '3.84380626678467']
['2021-5-4 8:40:12', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 8:40:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:40:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:40:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:40:12', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 8:40:12', 'fActCo2ValMemo', '758']
['2021-5-4 8:40:12', 'fActWaterLevelMixTank1', '279.039001464844']
['2021-5-4 8:40:12', 'fActWaterLevelMixTank2', '293.625183105469']
['2021-5-4 8:40:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:40:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:40:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:40:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:40:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:40:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:40:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:40:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:40:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:40:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:40:12', 'DoVa_Co2', '0']
['2021-5-4 8:40:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:40:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:40:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:40:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:40:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:41:12', 'fKWhCounter', '3361.42846679688']
['2021-5-4 8:41:12', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 8:41:12', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 8:41:12', 'fActPhLevelMixTank2', '3.83770251274109']
['2021-5-4 8:41:12', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 8:41:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:41:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:41:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:41:12', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 8:41:12', 'fActCo2ValMemo', '758']
['2021-5-4 8:41:12', 'fActWaterLevelMixTank1', '278.522918701172']
['2021-5-4 8:41:12', 'fActWaterLevelMixTank2', '293.109100341797']
['2021-5-4 8:41:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:41:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:41:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:41:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:41:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:41:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:41:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:41:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:41:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:41:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:41:12', 'DoVa_Co2', '0']
['2021-5-4 8:41:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:41:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:41:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:41:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:41:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:42:12', 'fKWhCounter', '3361.62866210938']
['2021-5-4 8:42:12', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 8:42:12', 'fActEcLevelMixTank1', '2031.0068359375']
['2021-5-4 8:42:12', 'fActPhLevelMixTank2', '3.83159875869751']
['2021-5-4 8:42:12', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 8:42:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:42:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:42:12', 'fActTempValMemo', '19.6000003814697']
['2021-5-4 8:42:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:42:12', 'fActCo2ValMemo', '758']
['2021-5-4 8:42:12', 'fActWaterLevelMixTank1', '277.762359619141']
['2021-5-4 8:42:12', 'fActWaterLevelMixTank2', '293.217742919922']
['2021-5-4 8:42:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:42:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:42:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:42:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:42:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:42:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:42:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:42:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:42:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:42:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:42:12', 'DoVa_Co2', '0']
['2021-5-4 8:42:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:42:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:42:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:42:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:42:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:43:13', 'fKWhCounter', '3361.72875976563']
['2021-5-4 8:43:13', 'fActPhLevelMixTank1', '5.57896661758423']
['2021-5-4 8:43:13', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 8:43:13', 'fActPhLevelMixTank2', '3.83745837211609']
['2021-5-4 8:43:13', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 8:43:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:43:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:43:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:43:13', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:43:13', 'fActCo2ValMemo', '757']
['2021-5-4 8:43:13', 'fActWaterLevelMixTank1', '277.898193359375']
['2021-5-4 8:43:13', 'fActWaterLevelMixTank2', '293.43505859375']
['2021-5-4 8:43:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:43:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:43:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:43:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:43:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:43:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:43:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:43:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:43:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:43:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:43:13', 'DoVa_Co2', '0']
['2021-5-4 8:43:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:43:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:43:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:43:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:43:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:44:12', 'fKWhCounter', '3361.92895507813']
['2021-5-4 8:44:12', 'fActPhLevelMixTank1', '5.57945489883423']
['2021-5-4 8:44:12', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 8:44:12', 'fActPhLevelMixTank2', '3.83428454399109']
['2021-5-4 8:44:12', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 8:44:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:44:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:44:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:44:12', 'fActRhValMemo', '51.5']
['2021-5-4 8:44:12', 'fActCo2ValMemo', '757']
['2021-5-4 8:44:12', 'fActWaterLevelMixTank1', '279.690887451172']
['2021-5-4 8:44:12', 'fActWaterLevelMixTank2', '294.195587158203']
['2021-5-4 8:44:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:44:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:44:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:44:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:44:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:44:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:44:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:44:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:44:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:44:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:44:12', 'DoVa_Co2', '0']
['2021-5-4 8:44:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:44:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:44:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:44:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_2_White', '0']

['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:44:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:45:13', 'fKWhCounter', '3362.02905273438']
['2021-5-4 8:45:13', 'fActPhLevelMixTank1', '5.58555841445923']
['2021-5-4 8:45:13', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 8:45:13', 'fActPhLevelMixTank2', '3.83623766899109']
['2021-5-4 8:45:13', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 8:45:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:45:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:45:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:45:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 8:45:13', 'fActCo2ValMemo', '758']
['2021-5-4 8:45:13', 'fActWaterLevelMixTank1', '279.989685058594']
['2021-5-4 8:45:13', 'fActWaterLevelMixTank2', '293.733825683594']
['2021-5-4 8:45:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:45:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:45:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:45:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:45:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:45:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:45:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:45:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:45:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:45:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:45:13', 'DoVa_Co2', '0']
['2021-5-4 8:45:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:45:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:45:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:45:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:45:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:46:12', 'fKWhCounter', '3362.12915039063']
['2021-5-4 8:46:12', 'fActPhLevelMixTank1', '5.58384943008423']
['2021-5-4 8:46:12', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 8:46:12', 'fActPhLevelMixTank2', '3.83550524711609']
['2021-5-4 8:46:12', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 8:46:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:46:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:46:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:46:12', 'fActRhValMemo', '52']
['2021-5-4 8:46:12', 'fActCo2ValMemo', '756']
['2021-5-4 8:46:12', 'fActWaterLevelMixTank1', '280.913208007813']
['2021-5-4 8:46:12', 'fActWaterLevelMixTank2', '294.195587158203']
['2021-5-4 8:46:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:46:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:46:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:46:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:46:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:46:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:46:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:46:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:46:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:46:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:46:12', 'DoVa_Co2', '0']
['2021-5-4 8:46:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:46:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:46:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:46:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:46:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:47:13', 'fKWhCounter', '3362.32934570313']
['2021-5-4 8:47:13', 'fActPhLevelMixTank1', '5.57994318008423']
['2021-5-4 8:47:13', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 8:47:13', 'fActPhLevelMixTank2', '3.83379626274109']
['2021-5-4 8:47:13', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 8:47:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:47:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:47:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:47:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 8:47:13', 'fActCo2ValMemo', '756']
['2021-5-4 8:47:13', 'fActWaterLevelMixTank1', '280.994689941406']
['2021-5-4 8:47:13', 'fActWaterLevelMixTank2', '294.168426513672']
['2021-5-4 8:47:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:47:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:47:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:47:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:47:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:47:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:47:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:47:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:47:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:47:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:47:13', 'DoVa_Co2', '0']
['2021-5-4 8:47:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:47:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:47:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:47:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:47:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:48:12', 'fKWhCounter', '3362.42944335938']
['2021-5-4 8:48:12', 'fActPhLevelMixTank1', '5.57750177383423']
['2021-5-4 8:48:12', 'fActEcLevelMixTank1', '2014.83203125']
['2021-5-4 8:48:12', 'fActPhLevelMixTank2', '3.82891321182251']
['2021-5-4 8:48:12', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 8:48:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:48:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:48:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:48:12', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 8:48:12', 'fActCo2ValMemo', '753']
['2021-5-4 8:48:12', 'fActWaterLevelMixTank1', '281.429290771484']
['2021-5-4 8:48:12', 'fActWaterLevelMixTank2', '294.195587158203']
['2021-5-4 8:48:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:48:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:48:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:48:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:48:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:48:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:48:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:48:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:48:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:48:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:48:12', 'DoVa_Co2', '0']
['2021-5-4 8:48:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:48:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:48:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:48:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:48:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:49:13', 'fKWhCounter', '3362.52954101563']
['2021-5-4 8:49:13', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 8:49:13', 'fActEcLevelMixTank1', '2010.71203613281']
['2021-5-4 8:49:13', 'fActPhLevelMixTank2', '3.83526110649109']
['2021-5-4 8:49:13', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 8:49:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:49:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:49:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:49:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 8:49:13', 'fActCo2ValMemo', '750']
['2021-5-4 8:49:13', 'fActWaterLevelMixTank1', '281.673736572266']
['2021-5-4 8:49:13', 'fActWaterLevelMixTank2', '295.771026611328']
['2021-5-4 8:49:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:49:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:49:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:49:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:49:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:49:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:49:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:49:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:49:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:49:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:49:13', 'DoVa_Co2', '1']
['2021-5-4 8:49:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:49:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:49:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:49:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_2_White', '0']

['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:49:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:50:12', 'fKWhCounter', '3362.72973632813']
['2021-5-4 8:50:12', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 8:50:12', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 8:50:12', 'fActPhLevelMixTank2', '3.83477282524109']
['2021-5-4 8:50:12', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 8:50:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:50:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:50:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:50:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:50:12', 'fActCo2ValMemo', '750']
['2021-5-4 8:50:12', 'fActWaterLevelMixTank1', '281.891052246094']
['2021-5-4 8:50:12', 'fActWaterLevelMixTank2', '295.5537109375']
['2021-5-4 8:50:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:50:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:50:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:50:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:50:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:50:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:50:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:50:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:50:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:50:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:50:12', 'DoVa_Co2', '0']
['2021-5-4 8:50:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:50:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:50:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:50:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:50:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:51:13', 'fKWhCounter', '3362.82983398438']
['2021-5-4 8:51:13', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 8:51:13', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 8:51:13', 'fActPhLevelMixTank2', '3.83257555961609']
['2021-5-4 8:51:13', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 8:51:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:51:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:51:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:51:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 8:51:13', 'fActCo2ValMemo', '754']
['2021-5-4 8:51:13', 'fActWaterLevelMixTank1', '282.9775390625']
['2021-5-4 8:51:13', 'fActWaterLevelMixTank2', '295.961151123047']
['2021-5-4 8:51:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:51:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:51:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:51:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:51:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:51:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:51:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:51:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:51:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:51:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:51:13', 'DoVa_Co2', '0']
['2021-5-4 8:51:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:51:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:51:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:51:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:51:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:52:12', 'fKWhCounter', '3363.03002929688']
['2021-5-4 8:52:12', 'fActPhLevelMixTank1', '5.58604717254639']
['2021-5-4 8:52:12', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 8:52:12', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 8:52:12', 'fActEcLevelMixTank2', '1026.03234863281']
['2021-5-4 8:52:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:52:12', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:52:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:52:12', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:52:12', 'fActCo2ValMemo', '761']
['2021-5-4 8:52:12', 'fActWaterLevelMixTank1', '283.357818603516']
['2021-5-4 8:52:12', 'fActWaterLevelMixTank2', '296.368591308594']
['2021-5-4 8:52:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:52:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:52:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:52:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:52:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:52:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:52:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:52:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:52:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:52:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:52:12', 'DoVa_Co2', '0']
['2021-5-4 8:52:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:52:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:52:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:52:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:52:12', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:53:13', 'fKWhCounter', '3363.13012695313']
['2021-5-4 8:53:13', 'fActPhLevelMixTank1', '5.58238458633423']
['2021-5-4 8:53:13', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 8:53:13', 'fActPhLevelMixTank2', '3.83819079399109']
['2021-5-4 8:53:13', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 8:53:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:53:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:53:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 8:53:13', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 8:53:13', 'fActCo2ValMemo', '773']
['2021-5-4 8:53:13', 'fActWaterLevelMixTank1', '283.819580078125']
['2021-5-4 8:53:13', 'fActWaterLevelMixTank2', '296.178466796875']
['2021-5-4 8:53:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:53:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:53:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:53:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:53:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:53:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:53:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:53:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:53:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:53:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:53:13', 'DoVa_Co2', '0']
['2021-5-4 8:53:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:53:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:53:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:53:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:53:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:54:12', 'fKWhCounter', '3363.23022460938']
['2021-5-4 8:54:12', 'fActPhLevelMixTank1', '5.58653545379639']
['2021-5-4 8:54:12', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 8:54:12', 'fActPhLevelMixTank2', '3.83916735649109']
['2021-5-4 8:54:12', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 8:54:12', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:54:12', 'fTaktCounterLowerLevel', '0']

['2021-5-4 8:54:12', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:54:12', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 8:54:12', 'fActCo2ValMemo', '784']
['2021-5-4 8:54:12', 'fActWaterLevelMixTank1', '284.036865234375']
['2021-5-4 8:54:12', 'fActWaterLevelMixTank2', '296.748870849609']
['2021-5-4 8:54:12', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:54:12', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:54:12', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:54:12', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:54:12', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:54:12', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:54:12', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:54:12', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:54:12', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:54:12', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:54:12', 'DoVa_Co2', '0']
['2021-5-4 8:54:12', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:54:12', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:54:12', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:54:12', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:54:12', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:54:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:55:13', 'fKWhCounter', '3363.43041992188']
['2021-5-4 8:55:13', 'fActPhLevelMixTank1', '5.58897686004639']
['2021-5-4 8:55:13', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 8:55:13', 'fActPhLevelMixTank2', '3.83648180961609']
['2021-5-4 8:55:13', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 8:55:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:55:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:55:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:55:13', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:55:13', 'fActCo2ValMemo', '796']
['2021-5-4 8:55:13', 'fActWaterLevelMixTank1', '284.987548828125']
['2021-5-4 8:55:13', 'fActWaterLevelMixTank2', '297.455078125']
['2021-5-4 8:55:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:55:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:55:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:55:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:55:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:55:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:55:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:55:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:55:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:55:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:55:13', 'DoVa_Co2', '0']
['2021-5-4 8:55:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:55:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:55:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:55:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:55:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:56:13', 'fKWhCounter', '3363.53051757813']
['2021-5-4 8:56:13', 'fActPhLevelMixTank1', '5.59092998504639']
['2021-5-4 8:56:13', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 8:56:13', 'fActPhLevelMixTank2', '3.83379626274109']
['2021-5-4 8:56:13', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 8:56:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:56:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:56:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:56:13', 'fActRhValMemo', '52']
['2021-5-4 8:56:13', 'fActCo2ValMemo', '810']
['2021-5-4 8:56:13', 'fActWaterLevelMixTank1', '284.715942382813']
['2021-5-4 8:56:13', 'fActWaterLevelMixTank2', '297.156311035156']
['2021-5-4 8:56:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:56:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:56:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:56:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:56:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:56:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:56:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:56:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:56:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:56:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:56:13', 'DoVa_Co2', '0']
['2021-5-4 8:56:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:56:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:56:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:56:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:56:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:57:13', 'fKWhCounter', '3363.73071289063']
['2021-5-4 8:57:13', 'fActPhLevelMixTank1', '5.60606718063354']
['2021-5-4 8:57:13', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 8:57:13', 'fActPhLevelMixTank2', '3.84234142303467']
['2021-5-4 8:57:13', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 8:57:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:57:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:57:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:57:13', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 8:57:13', 'fActCo2ValMemo', '820']
['2021-5-4 8:57:13', 'fActWaterLevelMixTank1', '283.031860351563']
['2021-5-4 8:57:13', 'fActWaterLevelMixTank2', '297.699554443359']
['2021-5-4 8:57:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:57:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:57:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:57:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:57:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:57:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:57:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:57:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:57:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:57:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:57:13', 'DoVa_Co2', '0']
['2021-5-4 8:57:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:57:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:57:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:57:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:57:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:58:13', 'fKWhCounter', '3363.83081054688']
['2021-5-4 8:58:13', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 8:58:13', 'fActEcLevelMixTank1', '2015.90014648438']
['2021-5-4 8:58:13', 'fActPhLevelMixTank2', '3.83843493461609']
['2021-5-4 8:58:13', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 8:58:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:58:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:58:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 8:58:13', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 8:58:13', 'fActCo2ValMemo', '829']
['2021-5-4 8:58:13', 'fActWaterLevelMixTank1', '285.340667724609']
['2021-5-4 8:58:13', 'fActWaterLevelMixTank2', '297.536560058594']
['2021-5-4 8:58:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:58:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:58:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:58:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:58:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:58:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:58:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:58:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:58:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:58:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:58:13', 'DoVa_Co2', '0']
['2021-5-4 8:58:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:58:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:58:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:58:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_1_White', '0']

['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:58:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 8:59:13', 'fKWhCounter', '3363.93090820313']
['2021-5-4 8:59:13', 'fActPhLevelMixTank1', '5.60338163375854']
['2021-5-4 8:59:13', 'fActEcLevelMixTank1', '2015.4423828125']
['2021-5-4 8:59:13', 'fActPhLevelMixTank2', '3.84478282928467']
['2021-5-4 8:59:13', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 8:59:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 8:59:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 8:59:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 8:59:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 8:59:13', 'fActCo2ValMemo', '839']
['2021-5-4 8:59:13', 'fActWaterLevelMixTank1', '284.715942382813']
['2021-5-4 8:59:13', 'fActWaterLevelMixTank2', '298.079803466797']
['2021-5-4 8:59:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 8:59:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 8:59:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 8:59:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 8:59:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 8:59:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 8:59:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 8:59:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 8:59:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 8:59:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 8:59:13', 'DoVa_Co2', '0']
['2021-5-4 8:59:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 8:59:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 8:59:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 8:59:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 8:59:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:0:13', 'fKWhCounter', '3364.13110351563']
['2021-5-4 9:0:13', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 9:0:13', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 9:0:13', 'fActPhLevelMixTank2', '3.84673595428467']
['2021-5-4 9:0:13', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 9:0:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:0:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:0:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:0:13', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 9:0:13', 'fActCo2ValMemo', '843']
['2021-5-4 9:0:13', 'fActWaterLevelMixTank1', '284.471466064453']
['2021-5-4 9:0:13', 'fActWaterLevelMixTank2', '298.052642822266']
['2021-5-4 9:0:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:0:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:0:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:0:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:0:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:0:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:0:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:0:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:0:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:0:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:0:13', 'DoVa_Co2', '0']
['2021-5-4 9:0:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:0:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:0:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:0:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:0:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:1:13', 'fKWhCounter', '3364.23120117188']
['2021-5-4 9:1:13', 'fActPhLevelMixTank1', '5.60582304000854']
['2021-5-4 9:1:13', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 9:1:13', 'fActPhLevelMixTank2', '3.84282970428467']
['2021-5-4 9:1:13', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 9:1:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:1:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:1:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:1:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:1:13', 'fActCo2ValMemo', '848']
['2021-5-4 9:1:13', 'fActWaterLevelMixTank1', '285.965393066406']
['2021-5-4 9:1:13', 'fActWaterLevelMixTank2', '297.835357666016']
['2021-5-4 9:1:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:1:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:1:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:1:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:1:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:1:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:1:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:1:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:1:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:1:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:1:13', 'DoVa_Co2', '0']
['2021-5-4 9:1:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:1:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:1:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:1:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:1:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:2:13', 'fKWhCounter', '3364.43139648438']
['2021-5-4 9:2:13', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 9:2:13', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 9:2:13', 'fActPhLevelMixTank2', '3.84014415740967']
['2021-5-4 9:2:13', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 9:2:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:2:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:2:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:2:13', 'fActRhValMemo', '51.5']
['2021-5-4 9:2:13', 'fActCo2ValMemo', '856']
['2021-5-4 9:2:13', 'fActWaterLevelMixTank1', '286.590148925781']
['2021-5-4 9:2:13', 'fActWaterLevelMixTank2', '298.704559326172']
['2021-5-4 9:2:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:2:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:2:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:2:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:2:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:2:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:2:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:2:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:2:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:2:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:2:13', 'DoVa_Co2', '0']
['2021-5-4 9:2:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:2:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:2:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:2:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:2:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:3:13', 'fKWhCounter', '3364.53149414063']
['2021-5-4 9:3:13', 'fActPhLevelMixTank1', '5.60582304000854']
['2021-5-4 9:3:13', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 9:3:13', 'fActPhLevelMixTank2', '3.83941149711609']
['2021-5-4 9:3:13', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 9:3:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:3:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:3:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:3:13', 'fActRhValMemo', '51.5']
['2021-5-4 9:3:13', 'fActCo2ValMemo', '857']
['2021-5-4 9:3:13', 'fActWaterLevelMixTank1', '285.748107910156']
['2021-5-4 9:3:13', 'fActWaterLevelMixTank2', '298.595916748047']
['2021-5-4 9:3:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:3:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:3:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:3:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:3:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:3:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:3:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:3:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:3:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:3:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:3:13', 'DoVa_Co2', '0']
['2021-5-4 9:3:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:3:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:3:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:3:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']

['2021-5-4 9:3:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:3:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:4:13', 'fKWhCounter', '3364.63159179688']
['2021-5-4 9:4:13', 'fActPhLevelMixTank1', '5.61290311813354']
['2021-5-4 9:4:13', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 9:4:13', 'fActPhLevelMixTank2', '3.84624767303467']
['2021-5-4 9:4:13', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 9:4:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:4:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:4:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:4:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:4:13', 'fActCo2ValMemo', '856']
['2021-5-4 9:4:13', 'fActWaterLevelMixTank1', '285.965393066406']
['2021-5-4 9:4:13', 'fActWaterLevelMixTank2', '298.731719970703']
['2021-5-4 9:4:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:4:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:4:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:4:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:4:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:4:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:4:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:4:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:4:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:4:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:4:13', 'DoVa_Co2', '0']
['2021-5-4 9:4:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:4:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:4:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:4:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:4:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:5:13', 'fKWhCounter', '3364.83178710938']
['2021-5-4 9:5:13', 'fActPhLevelMixTank1', '5.60875272750854']
['2021-5-4 9:5:13', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 9:5:13', 'fActPhLevelMixTank2', '3.84722423553467']
['2021-5-4 9:5:13', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 9:5:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:5:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:5:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:5:13', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 9:5:13', 'fActCo2ValMemo', '858']
['2021-5-4 9:5:13', 'fActWaterLevelMixTank1', '286.56298828125']
['2021-5-4 9:5:13', 'fActWaterLevelMixTank2', '298.894683837891']
['2021-5-4 9:5:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:5:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:5:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:5:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:5:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:5:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:5:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:5:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:5:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:5:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:5:13', 'DoVa_Co2', '0']
['2021-5-4 9:5:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:5:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:5:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:5:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:5:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:6:13', 'fKWhCounter', '3364.93188476563']
['2021-5-4 9:6:13', 'fActPhLevelMixTank1', '5.60802030563354']
['2021-5-4 9:6:13', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 9:6:13', 'fActPhLevelMixTank2', '3.85259556770325']
['2021-5-4 9:6:13', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 9:6:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:6:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:6:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:6:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:6:13', 'fActCo2ValMemo', '860']
['2021-5-4 9:6:13', 'fActWaterLevelMixTank1', '287.459320068359']
['2021-5-4 9:6:13', 'fActWaterLevelMixTank2', '299.628082275391']
['2021-5-4 9:6:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:6:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:6:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:6:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:6:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:6:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:6:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:6:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:6:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:6:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:6:13', 'DoVa_Co2', '0']
['2021-5-4 9:6:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:6:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:6:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:6:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:6:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:7:13', 'fKWhCounter', '3365.13208007813']
['2021-5-4 9:7:13', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 9:7:13', 'fActEcLevelMixTank1', '2017.12084960938']
['2021-5-4 9:7:13', 'fActPhLevelMixTank2', '3.85064244270325']
['2021-5-4 9:7:13', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 9:7:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:7:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:7:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:7:13', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 9:7:13', 'fActCo2ValMemo', '858']
['2021-5-4 9:7:13', 'fActWaterLevelMixTank1', '287.567993164063']
['2021-5-4 9:7:13', 'fActWaterLevelMixTank2', '299.247802734375']
['2021-5-4 9:7:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:7:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:7:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:7:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:7:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:7:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:7:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:7:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:7:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:7:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:7:13', 'DoVa_Co2', '0']
['2021-5-4 9:7:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:7:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:7:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:7:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:7:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:8:13', 'fKWhCounter', '3365.23217773438']
['2021-5-4 9:8:13', 'fActPhLevelMixTank1', '5.61363554000854']
['2021-5-4 9:8:13', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 9:8:13', 'fActPhLevelMixTank2', '3.84966588020325']
['2021-5-4 9:8:13', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 9:8:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:8:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:8:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:8:13', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 9:8:13', 'fActCo2ValMemo', '859']
['2021-5-4 9:8:13', 'fActWaterLevelMixTank1', '286.345672607422']
['2021-5-4 9:8:13', 'fActWaterLevelMixTank2', '300.198486328125']
['2021-5-4 9:8:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:8:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:8:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:8:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:8:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:8:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:8:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:8:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:8:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:8:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:8:13', 'DoVa_Co2', '0']
['2021-5-4 9:8:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:8:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:8:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:8:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:8:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:9:13', 'fKWhCounter', '3365.33227539063']
['2021-5-4 9:9:13', 'fActPhLevelMixTank1', '5.61558866500854']
['2021-5-4 9:9:13', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 9:9:13', 'fActPhLevelMixTank2', '3.85430455207825']
['2021-5-4 9:9:13', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 9:9:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:9:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:9:13', 'fActTempValMemo', '19.7000007629395']
['2021-5-4 9:9:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:9:13', 'fActCo2ValMemo', '857']
['2021-5-4 9:9:13', 'fActWaterLevelMixTank1', '286.834594726563']
['2021-5-4 9:9:13', 'fActWaterLevelMixTank2', '300.415771484375']
['2021-5-4 9:9:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:9:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:9:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:9:13', 'DoPu_AddAcidMixTank_2', '0']

['2021-5-4 9:9:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:9:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:9:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:9:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:9:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:9:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:9:13', 'DoVa_Co2', '0']
['2021-5-4 9:9:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:9:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:9:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:9:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:9:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:10:13', 'fKWhCounter', '3365.53247070313']
['2021-5-4 9:10:13', 'fActPhLevelMixTank1', '5.61632108688354']
['2021-5-4 9:10:13', 'fActEcLevelMixTank1', '2004.76086425781']
['2021-5-4 9:10:13', 'fActPhLevelMixTank2', '3.85430455207825']
['2021-5-4 9:10:13', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 9:10:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:10:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:10:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:10:13', 'fActRhValMemo', '51.5']
['2021-5-4 9:10:13', 'fActCo2ValMemo', '855']
['2021-5-4 9:10:13', 'fActWaterLevelMixTank1', '288.084075927734']
['2021-5-4 9:10:13', 'fActWaterLevelMixTank2', '300.850372314453']
['2021-5-4 9:10:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:10:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:10:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:10:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:10:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:10:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:10:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:10:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:10:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:10:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:10:13', 'DoVa_Co2', '0']
['2021-5-4 9:10:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:10:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:10:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:10:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:10:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:11:13', 'fKWhCounter', '3365.63256835938']
['2021-5-4 9:11:13', 'fActPhLevelMixTank1', '5.61558866500854']
['2021-5-4 9:11:13', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 9:11:13', 'fActPhLevelMixTank2', '3.85528111457825']
['2021-5-4 9:11:13', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 9:11:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:11:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:11:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:11:13', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 9:11:13', 'fActCo2ValMemo', '858']
['2021-5-4 9:11:13', 'fActWaterLevelMixTank1', '286.943237304688']
['2021-5-4 9:11:13', 'fActWaterLevelMixTank2', '300.605926513672']
['2021-5-4 9:11:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:11:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:11:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:11:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:11:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:11:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:11:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:11:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:11:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:11:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:11:13', 'DoVa_Co2', '0']
['2021-5-4 9:11:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:11:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:11:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:11:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:11:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:12:13', 'fKWhCounter', '3365.73266601563']
['2021-5-4 9:12:13', 'fActPhLevelMixTank1', '5.6226692199707']
['2021-5-4 9:12:13', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 9:12:13', 'fActPhLevelMixTank2', '3.85650205612183']
['2021-5-4 9:12:13', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 9:12:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:12:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:12:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:12:13', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 9:12:13', 'fActCo2ValMemo', '859']
['2021-5-4 9:12:13', 'fActWaterLevelMixTank1', '288.708801269531']
['2021-5-4 9:12:13', 'fActWaterLevelMixTank2', '300.388610839844']
['2021-5-4 9:12:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:12:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:12:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:12:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:12:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:12:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:12:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:12:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:12:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:12:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:12:13', 'DoVa_Co2', '0']
['2021-5-4 9:12:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:12:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:12:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:12:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:12:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:13:13', 'fKWhCounter', '3365.93286132813']
['2021-5-4 9:13:13', 'fActPhLevelMixTank1', '5.6246223449707']
['2021-5-4 9:13:13', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 9:13:13', 'fActPhLevelMixTank2', '3.85723447799683']
['2021-5-4 9:13:13', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 9:13:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:13:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:13:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:13:13', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 9:13:13', 'fActCo2ValMemo', '860']
['2021-5-4 9:13:13', 'fActWaterLevelMixTank1', '289.034759521484']
['2021-5-4 9:13:13', 'fActWaterLevelMixTank2', '300.850372314453']
['2021-5-4 9:13:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:13:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:13:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:13:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:13:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:13:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:13:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:13:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:13:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:13:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:13:13', 'DoVa_Co2', '0']
['2021-5-4 9:13:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:13:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:13:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:13:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:13:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:14:13', 'fKWhCounter', '3366.03295898438']
['2021-5-4 9:14:13', 'fActPhLevelMixTank1', '5.6280403137207']
['2021-5-4 9:14:13', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 9:14:13', 'fActPhLevelMixTank2', '3.85674619674683']
['2021-5-4 9:14:13', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 9:14:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:14:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:14:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:14:13', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 9:14:13', 'fActCo2ValMemo', '860']
['2021-5-4 9:14:13', 'fActWaterLevelMixTank1', '287.676635742188']
['2021-5-4 9:14:13', 'fActWaterLevelMixTank2', '301.230651855469']
['2021-5-4 9:14:13', 'DoPu_AddAcidMixTank_1', '0']

['2021-5-4 9:14:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:14:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:14:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:14:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:14:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:14:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:14:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:14:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:14:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:14:13', 'DoVa_Co2', '0']
['2021-5-4 9:14:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:14:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:14:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:14:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:14:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:15:13', 'fKWhCounter', '3366.23315429688']
['2021-5-4 9:15:13', 'fActPhLevelMixTank1', '5.6290168762207']
['2021-5-4 9:15:13', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 9:15:13', 'fActPhLevelMixTank2', '3.85357213020325']
['2021-5-4 9:15:13', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 9:15:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:15:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:15:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:15:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 9:15:13', 'fActCo2ValMemo', '860']
['2021-5-4 9:15:13', 'fActWaterLevelMixTank1', '289.903930664063']
['2021-5-4 9:15:13', 'fActWaterLevelMixTank2', '301.556610107422']
['2021-5-4 9:15:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:15:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:15:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:15:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:15:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:15:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:15:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:15:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:15:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:15:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:15:13', 'DoVa_Co2', '0']
['2021-5-4 9:15:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:15:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:15:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:15:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:15:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:16:13', 'fKWhCounter', '3366.33325195313']
['2021-5-4 9:16:13', 'fActPhLevelMixTank1', '5.6319465637207']
['2021-5-4 9:16:13', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 9:16:13', 'fActPhLevelMixTank2', '3.85235142707825']
['2021-5-4 9:16:13', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 9:16:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:16:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:16:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:16:13', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 9:16:13', 'fActCo2ValMemo', '858']
['2021-5-4 9:16:13', 'fActWaterLevelMixTank1', '289.958282470703']
['2021-5-4 9:16:13', 'fActWaterLevelMixTank2', '302.588775634766']
['2021-5-4 9:16:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:16:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:16:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:16:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:16:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:16:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:16:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:16:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:16:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:16:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:16:13', 'DoVa_Co2', '0']
['2021-5-4 9:16:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:16:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:16:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:16:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:16:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:17:13', 'fKWhCounter', '3366.43334960938']
['2021-5-4 9:17:13', 'fActPhLevelMixTank1', '5.6270637512207']
['2021-5-4 9:17:13', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 9:17:13', 'fActPhLevelMixTank2', '3.85576963424683']
['2021-5-4 9:17:13', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 9:17:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:17:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:17:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:17:13', 'fActRhValMemo', '51.5']
['2021-5-4 9:17:13', 'fActCo2ValMemo', '855']
['2021-5-4 9:17:13', 'fActWaterLevelMixTank1', '290.094085693359']
['2021-5-4 9:17:13', 'fActWaterLevelMixTank2', '302.398620605469']
['2021-5-4 9:17:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:17:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:17:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:17:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:17:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:17:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:17:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:17:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:17:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:17:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:17:13', 'DoVa_Co2', '0']
['2021-5-4 9:17:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:17:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:17:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:17:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:17:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:18:13', 'fKWhCounter', '3366.63354492188']
['2021-5-4 9:18:13', 'fActPhLevelMixTank1', '5.6309700012207']
['2021-5-4 9:18:13', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 9:18:13', 'fActPhLevelMixTank2', '3.85821104049683']
['2021-5-4 9:18:13', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 9:18:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:18:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:18:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:18:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:18:13', 'fActCo2ValMemo', '855']
['2021-5-4 9:18:13', 'fActWaterLevelMixTank1', '290.311370849609']
['2021-5-4 9:18:13', 'fActWaterLevelMixTank2', '302.072692871094']
['2021-5-4 9:18:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:18:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:18:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:18:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:18:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:18:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:18:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:18:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:18:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:18:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:18:13', 'DoVa_Co2', '0']
['2021-5-4 9:18:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:18:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:18:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:18:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:18:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:19:13', 'fKWhCounter', '3366.73364257813']
['2021-5-4 9:19:13', 'fActPhLevelMixTank1', '5.63756227493286']
['2021-5-4 9:19:13', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 9:19:13', 'fActPhLevelMixTank2', '3.85772275924683']
['2021-5-4 9:19:13', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 9:19:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:19:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:19:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:19:13', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 9:19:13', 'fActCo2ValMemo', '854']
['2021-5-4 9:19:13', 'fActWaterLevelMixTank1', '289.768127441406']
['2021-5-4 9:19:13', 'fActWaterLevelMixTank2', '302.099853515625']

['2021-5-4 9:19:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:19:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:19:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:19:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:19:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:19:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:19:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:19:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:19:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:19:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:19:13', 'DoVa_Co2', '0']
['2021-5-4 9:19:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:19:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:19:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:19:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:19:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:20:13', 'fKWhCounter', '3366.93383789063']
['2021-5-4 9:20:13', 'fActPhLevelMixTank1', '5.63487672805786']
['2021-5-4 9:20:13', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 9:20:13', 'fActPhLevelMixTank2', '3.85918760299683']
['2021-5-4 9:20:13', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 9:20:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:20:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:20:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:20:13', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 9:20:13', 'fActCo2ValMemo', '850']
['2021-5-4 9:20:13', 'fActWaterLevelMixTank1', '289.252044677734']
['2021-5-4 9:20:13', 'fActWaterLevelMixTank2', '302.480133056641']
['2021-5-4 9:20:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:20:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:20:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:20:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:20:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:20:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:20:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:20:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:20:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:20:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:20:13', 'DoVa_Co2', '0']
['2021-5-4 9:20:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:20:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:20:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:20:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:20:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:21:13', 'fKWhCounter', '3367.03393554688']
['2021-5-4 9:21:13', 'fActPhLevelMixTank1', '5.63902711868286']
['2021-5-4 9:21:13', 'fActEcLevelMixTank1', '2028.56530761719']
['2021-5-4 9:21:13', 'fActPhLevelMixTank2', '3.85992002487183']
['2021-5-4 9:21:13', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 9:21:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:21:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:21:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:21:13', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 9:21:13', 'fActCo2ValMemo', '848']
['2021-5-4 9:21:13', 'fActWaterLevelMixTank1', '291.071929931641']
['2021-5-4 9:21:13', 'fActWaterLevelMixTank2', '302.751739501953']
['2021-5-4 9:21:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:21:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:21:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:21:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:21:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:21:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:21:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:21:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:21:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:21:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:21:13', 'DoVa_Co2', '0']
['2021-5-4 9:21:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:21:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:21:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:21:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:21:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:22:13', 'fKWhCounter', '3367.13403320313']
['2021-5-4 9:22:13', 'fActPhLevelMixTank1', '5.64073610305786']
['2021-5-4 9:22:13', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 9:22:13', 'fActPhLevelMixTank2', '3.85821104049683']
['2021-5-4 9:22:13', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 9:22:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:22:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:22:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:22:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 9:22:13', 'fActCo2ValMemo', '849']
['2021-5-4 9:22:13', 'fActWaterLevelMixTank1', '291.370727539063']
['2021-5-4 9:22:13', 'fActWaterLevelMixTank2', '303.485137939453']
['2021-5-4 9:22:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:22:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:22:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:22:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:22:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:22:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:22:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:22:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:22:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:22:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:22:13', 'DoVa_Co2', '0']
['2021-5-4 9:22:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:22:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:22:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:22:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:22:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:23:13', 'fKWhCounter', '3367.33422851563']
['2021-5-4 9:23:13', 'fActPhLevelMixTank1', '5.64244508743286']
['2021-5-4 9:23:13', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 9:23:13', 'fActPhLevelMixTank2', '3.85918760299683']
['2021-5-4 9:23:13', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 9:23:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:23:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:23:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:23:13', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 9:23:13', 'fActCo2ValMemo', '851']
['2021-5-4 9:23:13', 'fActWaterLevelMixTank1', '291.696655273438']
['2021-5-4 9:23:13', 'fActWaterLevelMixTank2', '303.457977294922']
['2021-5-4 9:23:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:23:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:23:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:23:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:23:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:23:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:23:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:23:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:23:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:23:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:23:13', 'DoVa_Co2', '0']
['2021-5-4 9:23:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:23:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:23:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:23:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']

['2021-5-4 9:23:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:23:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:24:13', 'fKWhCounter', '3367.43432617188']
['2021-5-4 9:24:13', 'fActPhLevelMixTank1', '5.64513063430786']
['2021-5-4 9:24:13', 'fActEcLevelMixTank1', '2029.48083496094']
['2021-5-4 9:24:13', 'fActPhLevelMixTank2', '3.86284971237183']
['2021-5-4 9:24:13', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 9:24:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:24:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:24:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:24:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 9:24:13', 'fActCo2ValMemo', '852']
['2021-5-4 9:24:13', 'fActWaterLevelMixTank1', '290.094085693359']
['2021-5-4 9:24:13', 'fActWaterLevelMixTank2', '303.430816650391']
['2021-5-4 9:24:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:24:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:24:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:24:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:24:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:24:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:24:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:24:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:24:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:24:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:24:13', 'DoVa_Co2', '0']
['2021-5-4 9:24:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:24:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:24:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:24:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:24:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:25:13', 'fKWhCounter', '3367.63452148438']
['2021-5-4 9:25:13', 'fActPhLevelMixTank1', '5.63975954055786']
['2021-5-4 9:25:13', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 9:25:13', 'fActPhLevelMixTank2', '3.85650205612183']
['2021-5-4 9:25:13', 'fActEcLevelMixTank2', '1038.544921875']
['2021-5-4 9:25:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:25:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:25:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:25:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:25:13', 'fActCo2ValMemo', '851']
['2021-5-4 9:25:13', 'fActWaterLevelMixTank1', '291.859649658203']
['2021-5-4 9:25:13', 'fActWaterLevelMixTank2', '303.783905029297']
['2021-5-4 9:25:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:25:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:25:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:25:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:25:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:25:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:25:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:25:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:25:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:25:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:25:13', 'DoVa_Co2', '0']
['2021-5-4 9:25:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:25:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:25:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:25:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:25:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:26:13', 'fKWhCounter', '3367.73461914063']
['2021-5-4 9:26:13', 'fActPhLevelMixTank1', '5.64268922805786']
['2021-5-4 9:26:13', 'fActEcLevelMixTank1', '2030.24389648438']
['2021-5-4 9:26:13', 'fActPhLevelMixTank2', '3.86333823204041']
['2021-5-4 9:26:13', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 9:26:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:26:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:26:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:26:13', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 9:26:13', 'fActCo2ValMemo', '849']
['2021-5-4 9:26:13', 'fActWaterLevelMixTank1', '290.691650390625']
['2021-5-4 9:26:13', 'fActWaterLevelMixTank2', '304.10986328125']
['2021-5-4 9:26:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:26:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:26:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:26:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:26:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:26:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:26:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:26:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:26:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:26:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:26:13', 'DoVa_Co2', '0']
['2021-5-4 9:26:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:26:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:26:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:26:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:26:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:27:13', 'fKWhCounter', '3367.83471679688']
['2021-5-4 9:27:13', 'fActPhLevelMixTank1', '5.64342164993286']
['2021-5-4 9:27:13', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 9:27:13', 'fActPhLevelMixTank2', '3.86407065391541']
['2021-5-4 9:27:13', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 9:27:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:27:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:27:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:27:13', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 9:27:13', 'fActCo2ValMemo', '848']
['2021-5-4 9:27:13', 'fActWaterLevelMixTank1', '292.104095458984']
['2021-5-4 9:27:13', 'fActWaterLevelMixTank2', '304.082702636719']
['2021-5-4 9:27:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:27:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:27:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:27:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:27:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:27:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:27:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:27:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:27:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:27:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:27:13', 'DoVa_Co2', '0']
['2021-5-4 9:27:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:27:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:27:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:27:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:27:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:28:13', 'fKWhCounter', '3368.03491210938']
['2021-5-4 9:28:13', 'fActPhLevelMixTank1', '5.64537477493286']
['2021-5-4 9:28:13', 'fActEcLevelMixTank1', '2029.48083496094']
['2021-5-4 9:28:13', 'fActPhLevelMixTank2', '3.86504721641541']
['2021-5-4 9:28:13', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 9:28:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:28:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:28:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:28:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:28:13', 'fActCo2ValMemo', '847']
['2021-5-4 9:28:13', 'fActWaterLevelMixTank1', '291.886810302734']
['2021-5-4 9:28:13', 'fActWaterLevelMixTank2', '304.299987792969']
['2021-5-4 9:28:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:28:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:28:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:28:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:28:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:28:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:28:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:28:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:28:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:28:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:28:13', 'DoVa_Co2', '0']
['2021-5-4 9:28:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:28:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:28:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:28:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_1_Blue', '0']

['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:28:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:29:13', 'fKWhCounter', '3368.13500976563']
['2021-5-4 9:29:13', 'fActPhLevelMixTank1', '5.64830446243286']
['2021-5-4 9:29:13', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 9:29:13', 'fActPhLevelMixTank2', '3.86748862266541']
['2021-5-4 9:29:13', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 9:29:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:29:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:29:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:29:13', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 9:29:13', 'fActCo2ValMemo', '844']
['2021-5-4 9:29:13', 'fActWaterLevelMixTank1', '291.968292236328']
['2021-5-4 9:29:13', 'fActWaterLevelMixTank2', '304.191345214844']
['2021-5-4 9:29:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:29:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:29:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:29:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:29:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:29:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:29:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:29:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:29:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:29:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:29:13', 'DoVa_Co2', '0']
['2021-5-4 9:29:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:29:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:29:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:29:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:29:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:30:13', 'fKWhCounter', '3368.33520507813']
['2021-5-4 9:30:13', 'fActPhLevelMixTank1', '5.65684986114502']
['2021-5-4 9:30:13', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 9:30:13', 'fActPhLevelMixTank2', '3.86504721641541']
['2021-5-4 9:30:13', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 9:30:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:30:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:30:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:30:13', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 9:30:13', 'fActCo2ValMemo', '845']
['2021-5-4 9:30:13', 'fActWaterLevelMixTank1', '292.565856933594']
['2021-5-4 9:30:13', 'fActWaterLevelMixTank2', '304.84326171875']
['2021-5-4 9:30:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:30:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:30:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:30:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:30:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:30:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:30:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:30:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:30:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:30:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:30:13', 'DoVa_Co2', '0']
['2021-5-4 9:30:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:30:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:30:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:30:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:30:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:31:13', 'fKWhCounter', '3368.43530273438']
['2021-5-4 9:31:13', 'fActPhLevelMixTank1', '5.65489673614502']
['2021-5-4 9:31:13', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 9:31:13', 'fActPhLevelMixTank2', '3.85894346237183']
['2021-5-4 9:31:13', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 9:31:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:31:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:31:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:31:13', 'fActRhValMemo', '51.5']
['2021-5-4 9:31:13', 'fActCo2ValMemo', '849']
['2021-5-4 9:31:13', 'fActWaterLevelMixTank1', '291.017608642578']
['2021-5-4 9:31:13', 'fActWaterLevelMixTank2', '304.680267333984']
['2021-5-4 9:31:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:31:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:31:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:31:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:31:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:31:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:31:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:31:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:31:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:31:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:31:13', 'DoVa_Co2', '0']
['2021-5-4 9:31:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:31:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:31:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:31:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:31:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:32:13', 'fKWhCounter', '3368.53540039063']
['2021-5-4 9:32:13', 'fActPhLevelMixTank1', '5.66100025177002']
['2021-5-4 9:32:13', 'fActEcLevelMixTank1', '2031.92236328125']
['2021-5-4 9:32:13', 'fActPhLevelMixTank2', '3.86748862266541']
['2021-5-4 9:32:13', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 9:32:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:32:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:32:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:32:13', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 9:32:13', 'fActCo2ValMemo', '851']
['2021-5-4 9:32:13', 'fActWaterLevelMixTank1', '293.027618408203']
['2021-5-4 9:32:13', 'fActWaterLevelMixTank2', '304.299987792969']
['2021-5-4 9:32:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:32:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:32:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:32:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:32:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:32:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:32:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:32:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:32:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:32:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:32:13', 'DoVa_Co2', '0']
['2021-5-4 9:32:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:32:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:32:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:32:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:32:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:33:13', 'fKWhCounter', '3368.73559570313']
['2021-5-4 9:33:13', 'fActPhLevelMixTank1', '5.66563940048218']
['2021-5-4 9:33:13', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 9:33:13', 'fActPhLevelMixTank2', '3.86333823204041']
['2021-5-4 9:33:13', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 9:33:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:33:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:33:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:33:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 9:33:13', 'fActCo2ValMemo', '845']
['2021-5-4 9:33:13', 'fActWaterLevelMixTank1', '291.071929931641']
['2021-5-4 9:33:13', 'fActWaterLevelMixTank2', '304.517303466797']
['2021-5-4 9:33:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:33:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:33:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:33:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:33:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:33:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:33:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:33:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:33:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:33:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:33:13', 'DoVa_Co2', '0']
['2021-5-4 9:33:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:33:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:33:13', 'DoVa_IrrigateLevel_3_MT2', '0']

['2021-5-4 9:33:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:33:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:34:13', 'fKWhCounter', '3368.83569335938']
['2021-5-4 9:34:13', 'fActPhLevelMixTank1', '5.66148853302002']
['2021-5-4 9:34:13', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 9:34:13', 'fActPhLevelMixTank2', '3.86773276329041']
['2021-5-4 9:34:13', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 9:34:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:34:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:34:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:34:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 9:34:13', 'fActCo2ValMemo', '845']
['2021-5-4 9:34:13', 'fActWaterLevelMixTank1', '293.217742919922']
['2021-5-4 9:34:13', 'fActWaterLevelMixTank2', '305.413665771484']
['2021-5-4 9:34:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:34:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:34:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:34:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:34:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:34:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:34:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:34:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:34:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:34:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:34:13', 'DoVa_Co2', '0']
['2021-5-4 9:34:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:34:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:34:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:34:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:34:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:35:13', 'fKWhCounter', '3369.03588867188']
['2021-5-4 9:35:13', 'fActPhLevelMixTank1', '5.66466283798218']
['2021-5-4 9:35:13', 'fActEcLevelMixTank1', '2033.90600585938']
['2021-5-4 9:35:13', 'fActPhLevelMixTank2', '3.86114072799683']
['2021-5-4 9:35:13', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 9:35:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:35:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:35:13', 'fActTempValMemo', '20']
['2021-5-4 9:35:13', 'fActRhValMemo', '51.5']
['2021-5-4 9:35:13', 'fActCo2ValMemo', '845']
['2021-5-4 9:35:13', 'fActWaterLevelMixTank1', '293.733825683594']
['2021-5-4 9:35:13', 'fActWaterLevelMixTank2', '305.060546875']
['2021-5-4 9:35:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:35:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:35:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:35:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:35:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:35:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:35:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:35:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:35:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:35:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:35:13', 'DoVa_Co2', '0']
['2021-5-4 9:35:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:35:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:35:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:35:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:35:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:36:13', 'fKWhCounter', '3369.13598632813']
['2021-5-4 9:36:13', 'fActPhLevelMixTank1', '5.66881322860718']
['2021-5-4 9:36:13', 'fActEcLevelMixTank1', '2034.97424316406']
['2021-5-4 9:36:13', 'fActPhLevelMixTank2', '3.87163925170898']
['2021-5-4 9:36:13', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 9:36:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:36:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:36:13', 'fActTempValMemo', '20']
['2021-5-4 9:36:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:36:13', 'fActCo2ValMemo', '845']
['2021-5-4 9:36:13', 'fActWaterLevelMixTank1', '291.7509765625']
['2021-5-4 9:36:13', 'fActWaterLevelMixTank2', '305.142028808594']
['2021-5-4 9:36:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:36:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:36:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:36:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:36:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:36:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:36:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:36:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:36:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:36:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:36:13', 'DoVa_Co2', '0']
['2021-5-4 9:36:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:36:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:36:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:36:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:36:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:37:13', 'fKWhCounter', '3369.23608398438']
['2021-5-4 9:37:13', 'fActPhLevelMixTank1', '5.66344165802002']
['2021-5-4 9:37:13', 'fActEcLevelMixTank1', '2036.04235839844']
['2021-5-4 9:37:13', 'fActPhLevelMixTank2', '3.86846518516541']
['2021-5-4 9:37:13', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 9:37:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:37:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:37:13', 'fActTempValMemo', '20']
['2021-5-4 9:37:13', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 9:37:13', 'fActCo2ValMemo', '842']
['2021-5-4 9:37:13', 'fActWaterLevelMixTank1', '293.815338134766']
['2021-5-4 9:37:13', 'fActWaterLevelMixTank2', '305.766754150391']
['2021-5-4 9:37:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:37:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:37:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:37:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:37:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:37:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:37:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:37:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:37:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:37:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:37:13', 'DoVa_Co2', '0']
['2021-5-4 9:37:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:37:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:37:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:37:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:37:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:38:13', 'fKWhCounter', '3369.43627929688']
['2021-5-4 9:38:13', 'fActPhLevelMixTank1', '5.66563940048218']
['2021-5-4 9:38:13', 'fActEcLevelMixTank1', '2033.90600585938']
['2021-5-4 9:38:13', 'fActPhLevelMixTank2', '3.87041831016541']
['2021-5-4 9:38:13', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 9:38:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:38:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:38:13', 'fActTempValMemo', '20']
['2021-5-4 9:38:13', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 9:38:13', 'fActCo2ValMemo', '841']
['2021-5-4 9:38:13', 'fActWaterLevelMixTank1', '294.032623291016']
['2021-5-4 9:38:13', 'fActWaterLevelMixTank2', '305.956909179688']
['2021-5-4 9:38:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:38:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:38:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:38:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:38:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:38:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:38:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:38:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:38:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:38:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:38:13', 'DoVa_Co2', '0']
['2021-5-4 9:38:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:38:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:38:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:38:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 9:38:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:38:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:39:13', 'fKWhCounter', '3369.53637695313']
['2021-5-4 9:39:13', 'fActPhLevelMixTank1', '5.6214485168457']
['2021-5-4 9:39:13', 'fActEcLevelMixTank1', '2077.39501953125']
['2021-5-4 9:39:13', 'fActPhLevelMixTank2', '3.81109046936035']
['2021-5-4 9:39:13', 'fActEcLevelMixTank2', '1056.70336914063']
['2021-5-4 9:39:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:39:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:39:13', 'fActTempValMemo', '20']
['2021-5-4 9:39:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:39:13', 'fActCo2ValMemo', '839']
['2021-5-4 9:39:13', 'fActWaterLevelMixTank1', '300.551605224609']
['2021-5-4 9:39:13', 'fActWaterLevelMixTank2', '290.474365234375']
['2021-5-4 9:39:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:39:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:39:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:39:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:39:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:39:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:39:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:39:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:39:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:39:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:39:13', 'DoVa_Co2', '0']
['2021-5-4 9:39:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:39:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:39:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:39:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:39:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:40:13', 'fKWhCounter', '3369.73657226563']
['2021-5-4 9:40:13', 'fActPhLevelMixTank1', '5.57310724258423']
['2021-5-4 9:40:13', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 9:40:13', 'fActPhLevelMixTank2', '3.77788639068604']
['2021-5-4 9:40:13', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 9:40:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:40:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:40:13', 'fActTempValMemo', '20']
['2021-5-4 9:40:13', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 9:40:13', 'fActCo2ValMemo', '836']
['2021-5-4 9:40:13', 'fActWaterLevelMixTank1', '287.513671875']
['2021-5-4 9:40:13', 'fActWaterLevelMixTank2', '314.730346679688']
['2021-5-4 9:40:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:40:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:40:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:40:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:40:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:40:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:40:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:40:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:40:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:40:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:40:13', 'DoVa_Co2', '0']
['2021-5-4 9:40:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:40:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:40:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:40:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:40:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:41:13', 'fKWhCounter', '3369.93676757813']
['2021-5-4 9:41:13', 'fActPhLevelMixTank1', '5.57139825820923']
['2021-5-4 9:41:13', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 9:41:13', 'fActPhLevelMixTank2', '3.78496646881104']
['2021-5-4 9:41:13', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 9:41:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:41:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:41:13', 'fActTempValMemo', '20']
['2021-5-4 9:41:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:41:13', 'fActCo2ValMemo', '834']
['2021-5-4 9:41:13', 'fActWaterLevelMixTank1', '288.953277587891']
['2021-5-4 9:41:13', 'fActWaterLevelMixTank2', '279.527923583984']
['2021-5-4 9:41:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:41:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:41:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:41:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:41:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:41:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:41:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:41:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:41:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:41:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:41:13', 'DoVa_Co2', '0']
['2021-5-4 9:41:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:41:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:41:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:41:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:41:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:42:13', 'fKWhCounter', '3370.03686523438']
['2021-5-4 9:42:13', 'fActPhLevelMixTank1', '5.56480598449707']
['2021-5-4 9:42:13', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 9:42:13', 'fActPhLevelMixTank2', '3.78691983222961']
['2021-5-4 9:42:13', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 9:42:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:42:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:42:13', 'fActTempValMemo', '20']
['2021-5-4 9:42:13', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 9:42:13', 'fActCo2ValMemo', '832']
['2021-5-4 9:42:13', 'fActWaterLevelMixTank1', '282.624420166016']
['2021-5-4 9:42:13', 'fActWaterLevelMixTank2', '287.866760253906']
['2021-5-4 9:42:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:42:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:42:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:42:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:42:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:42:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:42:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:42:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:42:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:42:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:42:13', 'DoVa_Co2', '0']
['2021-5-4 9:42:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:42:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:42:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:42:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:42:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:43:13', 'fKWhCounter', '3370.23706054688']
['2021-5-4 9:43:13', 'fActPhLevelMixTank1', '5.56382942199707']
['2021-5-4 9:43:13', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 9:43:13', 'fActPhLevelMixTank2', '3.78911709785461']
['2021-5-4 9:43:13', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 9:43:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:43:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:43:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:43:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:43:13', 'fActCo2ValMemo', '833']
['2021-5-4 9:43:13', 'fActWaterLevelMixTank1', '279.853881835938']
['2021-5-4 9:43:13', 'fActWaterLevelMixTank2', '300.117004394531']
['2021-5-4 9:43:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:43:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:43:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:43:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:43:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:43:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:43:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:43:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:43:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:43:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:43:13', 'DoVa_Co2', '0']
['2021-5-4 9:43:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:43:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:43:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:43:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:43:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']

['2021-5-4 9:44:13', 'fKWhCounter', '3370.43725585938']
['2021-5-4 9:44:13', 'fActPhLevelMixTank1', '5.56773567199707']
['2021-5-4 9:44:13', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 9:44:13', 'fActPhLevelMixTank2', '3.80596327781677']
['2021-5-4 9:44:13', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 9:44:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:44:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:44:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:44:13', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 9:44:13', 'fActCo2ValMemo', '831']
['2021-5-4 9:44:13', 'fActWaterLevelMixTank1', '280.12548828125']
['2021-5-4 9:44:13', 'fActWaterLevelMixTank2', '296.287109375']
['2021-5-4 9:44:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:44:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:44:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:44:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:44:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:44:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:44:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:44:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:44:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:44:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:44:13', 'DoVa_Co2', '0']
['2021-5-4 9:44:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:44:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:44:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:44:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:44:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:45:13', 'fKWhCounter', '3370.53735351563']
['2021-5-4 9:45:13', 'fActPhLevelMixTank1', '5.58238458633423']
['2021-5-4 9:45:13', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 9:45:13', 'fActPhLevelMixTank2', '3.82988977432251']
['2021-5-4 9:45:13', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 9:45:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:45:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:45:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:45:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 9:45:13', 'fActCo2ValMemo', '830']
['2021-5-4 9:45:13', 'fActWaterLevelMixTank1', '278.088317871094']
['2021-5-4 9:45:13', 'fActWaterLevelMixTank2', '296.395751953125']
['2021-5-4 9:45:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:45:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:45:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:45:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:45:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:45:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:45:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:45:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:45:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:45:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:45:13', 'DoVa_Co2', '0']
['2021-5-4 9:45:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:45:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:45:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:45:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:45:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:46:13', 'fKWhCounter', '3370.63745117188']
['2021-5-4 9:46:13', 'fActPhLevelMixTank1', '5.58311700820923']
['2021-5-4 9:46:13', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 9:46:13', 'fActPhLevelMixTank2', '3.83184289932251']
['2021-5-4 9:46:13', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 9:46:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:46:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:46:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:46:13', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 9:46:13', 'fActCo2ValMemo', '830']
['2021-5-4 9:46:13', 'fActWaterLevelMixTank1', '279.1748046875']
['2021-5-4 9:46:13', 'fActWaterLevelMixTank2', '296.531555175781']
['2021-5-4 9:46:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:46:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:46:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:46:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:46:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:46:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:46:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:46:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:46:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:46:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:46:13', 'DoVa_Co2', '0']
['2021-5-4 9:46:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:46:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:46:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:46:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:46:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:47:13', 'fKWhCounter', '3370.83764648438']
['2021-5-4 9:47:13', 'fActPhLevelMixTank1', '5.57652521133423']
['2021-5-4 9:47:13', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 9:47:13', 'fActPhLevelMixTank2', '3.83745837211609']
['2021-5-4 9:47:13', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 9:47:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:47:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:47:13', 'fActTempValMemo', '19.7999992370605']
['2021-5-4 9:47:13', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 9:47:13', 'fActCo2ValMemo', '829']
['2021-5-4 9:47:13', 'fActWaterLevelMixTank1', '279.473602294922']
['2021-5-4 9:47:13', 'fActWaterLevelMixTank2', '296.613037109375']
['2021-5-4 9:47:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:47:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:47:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:47:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:47:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:47:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:47:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:47:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:47:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:47:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:47:13', 'DoVa_Co2', '0']
['2021-5-4 9:47:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:47:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:47:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:47:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:47:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:48:13', 'fKWhCounter', '3370.93774414063']
['2021-5-4 9:48:13', 'fActPhLevelMixTank1', '5.58287286758423']
['2021-5-4 9:48:13', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 9:48:13', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 9:48:13', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 9:48:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:48:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:48:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:48:13', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 9:48:13', 'fActCo2ValMemo', '830']
['2021-5-4 9:48:13', 'fActWaterLevelMixTank1', '278.414276123047']
['2021-5-4 9:48:13', 'fActWaterLevelMixTank2', '295.852508544922']
['2021-5-4 9:48:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:48:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:48:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:48:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:48:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:48:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:48:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:48:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:48:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:48:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:48:13', 'DoVa_Co2', '0']
['2021-5-4 9:48:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:48:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:48:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:48:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']

['2021-5-4 9:48:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:48:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:49:13', 'fKWhCounter', '3371.13793945313']
['2021-5-4 9:49:13', 'fActPhLevelMixTank1', '5.58702373504639']
['2021-5-4 9:49:13', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 9:49:13', 'fActPhLevelMixTank2', '3.83355212211609']
['2021-5-4 9:49:13', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 9:49:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:49:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:49:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:49:13', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 9:49:13', 'fActCo2ValMemo', '831']
['2021-5-4 9:49:13', 'fActWaterLevelMixTank1', '279.011840820313']
['2021-5-4 9:49:13', 'fActWaterLevelMixTank2', '296.477233886719']
['2021-5-4 9:49:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:49:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:49:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:49:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:49:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:49:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:49:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:49:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:49:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:49:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:49:13', 'DoVa_Co2', '0']
['2021-5-4 9:49:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:49:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:49:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:49:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:49:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:50:13', 'fKWhCounter', '3371.23803710938']
['2021-5-4 9:50:13', 'fActPhLevelMixTank1', '5.58604717254639']
['2021-5-4 9:50:13', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 9:50:13', 'fActPhLevelMixTank2', '3.82598352432251']
['2021-5-4 9:50:13', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 9:50:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:50:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:50:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:50:13', 'fActRhValMemo', '52']
['2021-5-4 9:50:13', 'fActCo2ValMemo', '833']
['2021-5-4 9:50:13', 'fActWaterLevelMixTank1', '279.392120361328']
['2021-5-4 9:50:13', 'fActWaterLevelMixTank2', '297.264953613281']
['2021-5-4 9:50:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:50:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:50:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:50:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:50:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:50:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:50:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:50:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:50:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:50:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:50:13', 'DoVa_Co2', '0']
['2021-5-4 9:50:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:50:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:50:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:50:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:50:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:51:13', 'fKWhCounter', '3371.43823242188']
['2021-5-4 9:51:13', 'fActPhLevelMixTank1', '5.58946514129639']
['2021-5-4 9:51:13', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 9:51:13', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 9:51:13', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 9:51:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:51:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:51:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:51:13', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 9:51:13', 'fActCo2ValMemo', '835']
['2021-5-4 9:51:13', 'fActWaterLevelMixTank1', '279.555084228516']
['2021-5-4 9:51:13', 'fActWaterLevelMixTank2', '296.857513427734']
['2021-5-4 9:51:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:51:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:51:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:51:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:51:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:51:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:51:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:51:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:51:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:51:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:51:13', 'DoVa_Co2', '0']
['2021-5-4 9:51:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:51:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:51:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:51:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:51:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:52:13', 'fKWhCounter', '3371.53833007813']
['2021-5-4 9:52:13', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 9:52:13', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 9:52:13', 'fActPhLevelMixTank2', '3.82866907119751']
['2021-5-4 9:52:13', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 9:52:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:52:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:52:13', 'fActTempValMemo', '19.8999996185303']
['2021-5-4 9:52:13', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 9:52:13', 'fActCo2ValMemo', '835']
['2021-5-4 9:52:13', 'fActWaterLevelMixTank1', '281.130493164063']
['2021-5-4 9:52:13', 'fActWaterLevelMixTank2', '297.482238769531']
['2021-5-4 9:52:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:52:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:52:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:52:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:52:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:52:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:52:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:52:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:52:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:52:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:52:13', 'DoVa_Co2', '0']
['2021-5-4 9:52:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:52:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:52:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:52:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:52:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:53:13', 'fKWhCounter', '3371.63842773438']
['2021-5-4 9:53:13', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 9:53:13', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 9:53:13', 'fActPhLevelMixTank2', '3.82696008682251']
['2021-5-4 9:53:13', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 9:53:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:53:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:53:13', 'fActTempValMemo', '20']
['2021-5-4 9:53:13', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 9:53:13', 'fActCo2ValMemo', '835']
['2021-5-4 9:53:13', 'fActWaterLevelMixTank1', '280.288452148438']
['2021-5-4 9:53:13', 'fActWaterLevelMixTank2', '297.944000244141']
['2021-5-4 9:53:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:53:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:53:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:53:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:53:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:53:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:53:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:53:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:53:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:53:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:53:13', 'DoVa_Co2', '0']
['2021-5-4 9:53:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:53:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:53:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:53:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_2_Fred', '0']

['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:53:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:54:13', 'fKWhCounter', '3371.83862304688']
['2021-5-4 9:54:13', 'fActPhLevelMixTank1', '5.57799005508423']
['2021-5-4 9:54:13', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 9:54:13', 'fActPhLevelMixTank2', '3.82403016090393']
['2021-5-4 9:54:13', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 9:54:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:54:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:54:13', 'fActTempValMemo', '20']
['2021-5-4 9:54:13', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 9:54:13', 'fActCo2ValMemo', '834']
['2021-5-4 9:54:13', 'fActWaterLevelMixTank1', '282.515777587891']
['2021-5-4 9:54:13', 'fActWaterLevelMixTank2', '298.378601074219']
['2021-5-4 9:54:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:54:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:54:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:54:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:54:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:54:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:54:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:54:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:54:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:54:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:54:13', 'DoVa_Co2', '0']
['2021-5-4 9:54:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:54:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:54:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:54:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:54:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:55:13', 'fKWhCounter', '3371.93872070313']
['2021-5-4 9:55:13', 'fActPhLevelMixTank1', '5.58751201629639']
['2021-5-4 9:55:13', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 9:55:13', 'fActPhLevelMixTank2', '3.82769250869751']
['2021-5-4 9:55:13', 'fActEcLevelMixTank2', '1028.62634277344']
['2021-5-4 9:55:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:55:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:55:13', 'fActTempValMemo', '20']
['2021-5-4 9:55:13', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 9:55:13', 'fActCo2ValMemo', '832']
['2021-5-4 9:55:13', 'fActWaterLevelMixTank1', '283.031860351563']
['2021-5-4 9:55:13', 'fActWaterLevelMixTank2', '298.949005126953']
['2021-5-4 9:55:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:55:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:55:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:55:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:55:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:55:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:55:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:55:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:55:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:55:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:55:13', 'DoVa_Co2', '0']
['2021-5-4 9:55:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:55:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:55:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:55:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:55:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:56:13', 'fKWhCounter', '3372.13891601563']
['2021-5-4 9:56:13', 'fActPhLevelMixTank1', '5.58970928192139']
['2021-5-4 9:56:13', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 9:56:13', 'fActPhLevelMixTank2', '3.82769250869751']
['2021-5-4 9:56:13', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 9:56:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:56:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:56:13', 'fActTempValMemo', '20']
['2021-5-4 9:56:13', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 9:56:13', 'fActCo2ValMemo', '833']
['2021-5-4 9:56:13', 'fActWaterLevelMixTank1', '283.357818603516']
['2021-5-4 9:56:13', 'fActWaterLevelMixTank2', '298.813201904297']
['2021-5-4 9:56:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:56:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:56:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:56:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:56:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:56:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:56:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:56:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:56:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:56:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:56:13', 'DoVa_Co2', '0']
['2021-5-4 9:56:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:56:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:56:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:56:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:56:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:57:13', 'fKWhCounter', '3372.23901367188']
['2021-5-4 9:57:13', 'fActPhLevelMixTank1', '5.59141826629639']
['2021-5-4 9:57:13', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 9:57:13', 'fActPhLevelMixTank2', '3.82720422744751']
['2021-5-4 9:57:13', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 9:57:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:57:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:57:13', 'fActTempValMemo', '20']
['2021-5-4 9:57:13', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 9:57:13', 'fActCo2ValMemo', '830']
['2021-5-4 9:57:13', 'fActWaterLevelMixTank1', '282.787414550781']
['2021-5-4 9:57:13', 'fActWaterLevelMixTank2', '299.030487060547']
['2021-5-4 9:57:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:57:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:57:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:57:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:57:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:57:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:57:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:57:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:57:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:57:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:57:13', 'DoVa_Co2', '0']
['2021-5-4 9:57:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:57:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:57:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:57:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:57:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:58:13', 'fKWhCounter', '3372.33911132813']
['2021-5-4 9:58:13', 'fActPhLevelMixTank1', '5.58873271942139']
['2021-5-4 9:58:13', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 9:58:13', 'fActPhLevelMixTank2', '3.82866907119751']
['2021-5-4 9:58:13', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 9:58:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:58:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:58:13', 'fActTempValMemo', '20']
['2021-5-4 9:58:13', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 9:58:13', 'fActCo2ValMemo', '829']
['2021-5-4 9:58:13', 'fActWaterLevelMixTank1', '283.194854736328']

['2021-5-4 9:58:13', 'fActWaterLevelMixTank2', '298.677398681641']
['2021-5-4 9:58:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:58:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:58:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:58:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:58:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:58:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:58:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:58:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:58:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:58:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:58:13', 'DoVa_Co2', '0']
['2021-5-4 9:58:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:58:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:58:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:58:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:58:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 9:59:13', 'fKWhCounter', '3372.53930664063']
['2021-5-4 9:59:13', 'fActPhLevelMixTank1', '5.59044170379639']
['2021-5-4 9:59:13', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 9:59:13', 'fActPhLevelMixTank2', '3.83477282524109']
['2021-5-4 9:59:13', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 9:59:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 9:59:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 9:59:13', 'fActTempValMemo', '20']
['2021-5-4 9:59:13', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 9:59:13', 'fActCo2ValMemo', '827']
['2021-5-4 9:59:13', 'fActWaterLevelMixTank1', '282.733093261719']
['2021-5-4 9:59:13', 'fActWaterLevelMixTank2', '299.791046142578']
['2021-5-4 9:59:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 9:59:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 9:59:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 9:59:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 9:59:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 9:59:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 9:59:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 9:59:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 9:59:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 9:59:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 9:59:13', 'DoVa_Co2', '0']
['2021-5-4 9:59:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 9:59:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 9:59:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 9:59:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 9:59:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:0:13', 'fKWhCounter', '3372.63940429688']
['2021-5-4 10:0:13', 'fActPhLevelMixTank1', '5.59678936004639']
['2021-5-4 10:0:13', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 10:0:13', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 10:0:13', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 10:0:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:0:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:0:13', 'fActTempValMemo', '20']
['2021-5-4 10:0:13', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 10:0:13', 'fActCo2ValMemo', '826']
['2021-5-4 10:0:13', 'fActWaterLevelMixTank1', '284.118347167969']
['2021-5-4 10:0:13', 'fActWaterLevelMixTank2', '299.899688720703']
['2021-5-4 10:0:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:0:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:0:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:0:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:0:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:0:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:0:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:0:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:0:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:0:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:0:13', 'DoVa_Co2', '0']
['2021-5-4 10:0:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:0:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:0:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:0:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:0:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:1:14', 'fKWhCounter', '3372.83959960938']
['2021-5-4 10:1:14', 'fActPhLevelMixTank1', '5.59825420379639']
['2021-5-4 10:1:14', 'fActEcLevelMixTank1', '2016.51049804688']
['2021-5-4 10:1:14', 'fActPhLevelMixTank2', '3.83819079399109']
['2021-5-4 10:1:14', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 10:1:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:1:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:1:14', 'fActTempValMemo', '20']
['2021-5-4 10:1:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:1:14', 'fActCo2ValMemo', '824']
['2021-5-4 10:1:14', 'fActWaterLevelMixTank1', '284.498626708984']
['2021-5-4 10:1:14', 'fActWaterLevelMixTank2', '299.763885498047']
['2021-5-4 10:1:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:1:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:1:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:1:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:1:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:1:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:1:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:1:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:1:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:1:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:1:14', 'DoVa_Co2', '0']
['2021-5-4 10:1:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:1:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:1:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:1:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:1:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:2:13', 'fKWhCounter', '3372.93969726563']
['2021-5-4 10:2:13', 'fActPhLevelMixTank1', '5.60289335250854']
['2021-5-4 10:2:13', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 10:2:13', 'fActPhLevelMixTank2', '3.84112071990967']
['2021-5-4 10:2:13', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 10:2:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:2:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:2:13', 'fActTempValMemo', '20']
['2021-5-4 10:2:13', 'fActRhValMemo', '52']
['2021-5-4 10:2:13', 'fActCo2ValMemo', '825']
['2021-5-4 10:2:13', 'fActWaterLevelMixTank1', '284.688781738281']
['2021-5-4 10:2:13', 'fActWaterLevelMixTank2', '300.279968261719']
['2021-5-4 10:2:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:2:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:2:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:2:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:2:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:2:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:2:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:2:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:2:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:2:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:2:13', 'DoVa_Co2', '0']
['2021-5-4 10:2:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:2:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:2:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:2:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:2:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:3:13', 'fKWhCounter', '3373.03979492188']
['2021-5-4 10:3:13', 'fActPhLevelMixTank1', '5.60606718063354']
['2021-5-4 10:3:13', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 10:3:13', 'fActPhLevelMixTank2', '3.83941149711609']
['2021-5-4 10:3:13', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 10:3:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:3:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:3:13', 'fActTempValMemo', '20']
['2021-5-4 10:3:13', 'fActRhValMemo', '51.5']
['2021-5-4 10:3:13', 'fActCo2ValMemo', '821']
['2021-5-4 10:3:13', 'fActWaterLevelMixTank1', '285.123382568359']
['2021-5-4 10:3:13', 'fActWaterLevelMixTank2', '300.415771484375']
['2021-5-4 10:3:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:3:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:3:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:3:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:3:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:3:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:3:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:3:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:3:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:3:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:3:13', 'DoVa_Co2', '0']

['2021-5-4 10:3:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:3:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:3:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:3:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:3:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:4:13', 'fKWhCounter', '3373.23999023438']
['2021-5-4 10:4:13', 'fActPhLevelMixTank1', '5.60093975067139']
['2021-5-4 10:4:13', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 10:4:13', 'fActPhLevelMixTank2', '3.83941149711609']
['2021-5-4 10:4:13', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 10:4:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:4:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:4:13', 'fActTempValMemo', '20']
['2021-5-4 10:4:13', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 10:4:13', 'fActCo2ValMemo', '821']
['2021-5-4 10:4:13', 'fActWaterLevelMixTank1', '285.422149658203']
['2021-5-4 10:4:13', 'fActWaterLevelMixTank2', '300.633087158203']
['2021-5-4 10:4:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:4:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:4:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:4:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:4:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:4:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:4:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:4:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:4:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:4:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:4:13', 'DoVa_Co2', '0']
['2021-5-4 10:4:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:4:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:4:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:4:13', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:4:13', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:5:14', 'fKWhCounter', '3373.34008789063']
['2021-5-4 10:5:14', 'fActPhLevelMixTank1', '5.60972929000854']
['2021-5-4 10:5:14', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 10:5:14', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 10:5:14', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 10:5:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:5:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:5:14', 'fActTempValMemo', '20']
['2021-5-4 10:5:14', 'fActRhValMemo', '51.5']
['2021-5-4 10:5:14', 'fActCo2ValMemo', '818']
['2021-5-4 10:5:14', 'fActWaterLevelMixTank1', '285.938232421875']
['2021-5-4 10:5:14', 'fActWaterLevelMixTank2', '301.230651855469']
['2021-5-4 10:5:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:5:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:5:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:5:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:5:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:5:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:5:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:5:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:5:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:5:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:5:14', 'DoVa_Co2', '0']
['2021-5-4 10:5:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:5:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:5:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:5:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:5:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:6:14', 'fKWhCounter', '3373.54028320313']
['2021-5-4 10:6:14', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 10:6:14', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 10:6:14', 'fActPhLevelMixTank2', '3.84527111053467']
['2021-5-4 10:6:14', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 10:6:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:6:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:6:14', 'fActTempValMemo', '20']
['2021-5-4 10:6:14', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 10:6:14', 'fActCo2ValMemo', '817']
['2021-5-4 10:6:14', 'fActWaterLevelMixTank1', '284.580108642578']
['2021-5-4 10:6:14', 'fActWaterLevelMixTank2', '301.203491210938']
['2021-5-4 10:6:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:6:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:6:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:6:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:6:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:6:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:6:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:6:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:6:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:6:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:6:14', 'DoVa_Co2', '0']
['2021-5-4 10:6:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:6:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:6:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:6:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:6:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:7:13', 'fKWhCounter', '3373.64038085938']
['2021-5-4 10:7:13', 'fActPhLevelMixTank1', '5.61485624313354']
['2021-5-4 10:7:13', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 10:7:13', 'fActPhLevelMixTank2', '3.84527111053467']
['2021-5-4 10:7:13', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 10:7:13', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:7:13', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:7:13', 'fActTempValMemo', '20']
['2021-5-4 10:7:13', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 10:7:13', 'fActCo2ValMemo', '814']
['2021-5-4 10:7:13', 'fActWaterLevelMixTank1', '284.66162109375']
['2021-5-4 10:7:13', 'fActWaterLevelMixTank2', '300.687408447266']
['2021-5-4 10:7:13', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:7:13', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:7:13', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:7:13', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:7:13', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:7:13', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:7:13', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:7:13', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:7:13', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:7:13', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:7:13', 'DoVa_Co2', '0']
['2021-5-4 10:7:13', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:7:13', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:7:13', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:7:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:7:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:8:14', 'fKWhCounter', '3373.84057617188']
['2021-5-4 10:8:14', 'fActPhLevelMixTank1', '5.61558866500854']
['2021-5-4 10:8:14', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 10:8:14', 'fActPhLevelMixTank2', '3.84331798553467']
['2021-5-4 10:8:14', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 10:8:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:8:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:8:14', 'fActTempValMemo', '20']
['2021-5-4 10:8:14', 'fActRhValMemo', '52']
['2021-5-4 10:8:14', 'fActCo2ValMemo', '813']
['2021-5-4 10:8:14', 'fActWaterLevelMixTank1', '285.123382568359']
['2021-5-4 10:8:14', 'fActWaterLevelMixTank2', '301.692413330078']
['2021-5-4 10:8:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:8:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:8:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:8:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:8:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:8:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:8:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:8:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:8:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:8:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:8:14', 'DoVa_Co2', '0']
['2021-5-4 10:8:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:8:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:8:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:8:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_4_Fred', '0']

['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:8:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:9:14', 'fKWhCounter', '3373.94067382813']
['2021-5-4 10:9:14', 'fActPhLevelMixTank1', '5.61412382125854']
['2021-5-4 10:9:14', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 10:9:14', 'fActPhLevelMixTank2', '3.84234142303467']
['2021-5-4 10:9:14', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 10:9:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:9:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:9:14', 'fActTempValMemo', '20']
['2021-5-4 10:9:14', 'fActRhValMemo', '52']
['2021-5-4 10:9:14', 'fActCo2ValMemo', '810']
['2021-5-4 10:9:14', 'fActWaterLevelMixTank1', '286.644470214844']
['2021-5-4 10:9:14', 'fActWaterLevelMixTank2', '301.583770751953']
['2021-5-4 10:9:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:9:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:9:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:9:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:9:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:9:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:9:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:9:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:9:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:9:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:9:14', 'DoVa_Co2', '0']
['2021-5-4 10:9:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:9:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:9:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:9:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:9:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:10:14', 'fKWhCounter', '3374.04077148438']
['2021-5-4 10:10:14', 'fActPhLevelMixTank1', '5.61021757125854']
['2021-5-4 10:10:14', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 10:10:14', 'fActPhLevelMixTank2', '3.84991002082825']
['2021-5-4 10:10:14', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 10:10:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:10:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:10:14', 'fActTempValMemo', '20']
['2021-5-4 10:10:14', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 10:10:14', 'fActCo2ValMemo', '812']
['2021-5-4 10:10:14', 'fActWaterLevelMixTank1', '285.530792236328']
['2021-5-4 10:10:14', 'fActWaterLevelMixTank2', '301.556610107422']
['2021-5-4 10:10:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:10:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:10:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:10:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:10:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:10:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:10:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:10:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:10:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:10:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:10:14', 'DoVa_Co2', '0']
['2021-5-4 10:10:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:10:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:10:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:10:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:10:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:11:14', 'fKWhCounter', '3374.24096679688']
['2021-5-4 10:11:14', 'fActPhLevelMixTank1', '5.61290311813354']
['2021-5-4 10:11:14', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 10:11:14', 'fActPhLevelMixTank2', '3.84868931770325']
['2021-5-4 10:11:14', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 10:11:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:11:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:11:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:11:14', 'fActRhValMemo', '52']
['2021-5-4 10:11:14', 'fActCo2ValMemo', '812']
['2021-5-4 10:11:14', 'fActWaterLevelMixTank1', '286.970397949219']
['2021-5-4 10:11:14', 'fActWaterLevelMixTank2', '301.9912109375']
['2021-5-4 10:11:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:11:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:11:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:11:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:11:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:11:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:11:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:11:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:11:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:11:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:11:14', 'DoVa_Co2', '0']
['2021-5-4 10:11:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:11:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:11:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:11:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:11:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:12:14', 'fKWhCounter', '3374.34106445313']
['2021-5-4 10:12:14', 'fActPhLevelMixTank1', '5.61217069625854']
['2021-5-4 10:12:14', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 10:12:14', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 10:12:14', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 10:12:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:12:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:12:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:12:14', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 10:12:14', 'fActCo2ValMemo', '814']
['2021-5-4 10:12:14', 'fActWaterLevelMixTank1', '287.269195556641']
['2021-5-4 10:12:14', 'fActWaterLevelMixTank2', '302.398620605469']
['2021-5-4 10:12:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:12:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:12:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:12:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:12:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:12:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:12:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:12:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:12:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:12:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:12:14', 'DoVa_Co2', '0']
['2021-5-4 10:12:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:12:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:12:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:12:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:12:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:13:14', 'fKWhCounter', '3374.54125976563']
['2021-5-4 10:13:14', 'fActPhLevelMixTank1', '5.61192655563354']
['2021-5-4 10:13:14', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 10:13:14', 'fActPhLevelMixTank2', '3.85088658332825']
['2021-5-4 10:13:14', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 10:13:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:13:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:13:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:13:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:13:14', 'fActCo2ValMemo', '815']
['2021-5-4 10:13:14', 'fActWaterLevelMixTank1', '286.590148925781']
['2021-5-4 10:13:14', 'fActWaterLevelMixTank2', '302.425811767578']
['2021-5-4 10:13:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:13:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:13:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:13:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:13:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:13:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:13:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:13:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:13:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:13:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:13:14', 'DoVa_Co2', '0']
['2021-5-4 10:13:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:13:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:13:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:13:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:13:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:14:14', 'fKWhCounter', '3374.64135742188']
['2021-5-4 10:14:14', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 10:14:14', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 10:14:14', 'fActPhLevelMixTank2', '3.85161900520325']
['2021-5-4 10:14:14', 'fActEcLevelMixTank2', '1032.59375']

['2021-5-4 10:14:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:14:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:14:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:14:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:14:14', 'fActCo2ValMemo', '813']
['2021-5-4 10:14:14', 'fActWaterLevelMixTank1', '287.486480712891']
['2021-5-4 10:14:14', 'fActWaterLevelMixTank2', '302.20849609375']
['2021-5-4 10:14:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:14:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:14:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:14:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:14:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:14:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:14:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:14:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:14:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:14:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:14:14', 'DoVa_Co2', '0']
['2021-5-4 10:14:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:14:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:14:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:14:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:14:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:15:14', 'fKWhCounter', '3374.74145507813']
['2021-5-4 10:15:14', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 10:15:14', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 10:15:14', 'fActPhLevelMixTank2', '3.85161900520325']
['2021-5-4 10:15:14', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 10:15:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:15:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:15:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:15:14', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 10:15:14', 'fActCo2ValMemo', '818']
['2021-5-4 10:15:14', 'fActWaterLevelMixTank1', '288.029754638672']
['2021-5-4 10:15:14', 'fActWaterLevelMixTank2', '302.996215820313']
['2021-5-4 10:15:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:15:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:15:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:15:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:15:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:15:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:15:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:15:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:15:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:15:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:15:14', 'DoVa_Co2', '0']
['2021-5-4 10:15:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:15:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:15:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:15:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:15:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:16:14', 'fKWhCounter', '3374.94165039063']
['2021-5-4 10:16:14', 'fActPhLevelMixTank1', '5.6204719543457']
['2021-5-4 10:16:14', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 10:16:14', 'fActPhLevelMixTank2', '3.84868931770325']
['2021-5-4 10:16:14', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 10:16:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:16:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:16:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:16:14', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 10:16:14', 'fActCo2ValMemo', '814']
['2021-5-4 10:16:14', 'fActWaterLevelMixTank1', '288.545837402344']
['2021-5-4 10:16:14', 'fActWaterLevelMixTank2', '303.322143554688']
['2021-5-4 10:16:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:16:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:16:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:16:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:16:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:16:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:16:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:16:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:16:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:16:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:16:14', 'DoVa_Co2', '0']
['2021-5-4 10:16:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:16:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:16:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:16:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:16:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:17:14', 'fKWhCounter', '3375.04174804688']
['2021-5-4 10:17:14', 'fActPhLevelMixTank1', '5.6194953918457']
['2021-5-4 10:17:14', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 10:17:14', 'fActPhLevelMixTank2', '3.85161900520325']
['2021-5-4 10:17:14', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 10:17:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:17:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:17:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:17:14', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 10:17:14', 'fActCo2ValMemo', '811']
['2021-5-4 10:17:14', 'fActWaterLevelMixTank1', '288.138397216797']
['2021-5-4 10:17:14', 'fActWaterLevelMixTank2', '303.457977294922']
['2021-5-4 10:17:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:17:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:17:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:17:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:17:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:17:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:17:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:17:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:17:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:17:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:17:14', 'DoVa_Co2', '0']
['2021-5-4 10:17:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:17:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:17:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:17:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:17:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:18:14', 'fKWhCounter', '3375.24194335938']
['2021-5-4 10:18:14', 'fActPhLevelMixTank1', '5.6197395324707']
['2021-5-4 10:18:14', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 10:18:14', 'fActPhLevelMixTank2', '3.85430455207825']
['2021-5-4 10:18:14', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 10:18:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:18:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:18:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:18:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:18:14', 'fActCo2ValMemo', '811']
['2021-5-4 10:18:14', 'fActWaterLevelMixTank1', '288.654479980469']
['2021-5-4 10:18:14', 'fActWaterLevelMixTank2', '303.485137939453']
['2021-5-4 10:18:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:18:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:18:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:18:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:18:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:18:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:18:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:18:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:18:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:18:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:18:14', 'DoVa_Co2', '0']
['2021-5-4 10:18:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:18:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:18:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:18:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:18:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:19:14', 'fKWhCounter', '3375.34204101563']
['2021-5-4 10:19:14', 'fActPhLevelMixTank1', '5.61290311813354']
['2021-5-4 10:19:14', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 10:19:14', 'fActPhLevelMixTank2', '3.84698009490967']
['2021-5-4 10:19:14', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 10:19:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:19:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:19:14', 'fActTempValMemo', '20.1000003814697']

['2021-5-4 10:19:14', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 10:19:14', 'fActCo2ValMemo', '813']
['2021-5-4 10:19:14', 'fActWaterLevelMixTank1', '287.676635742188']
['2021-5-4 10:19:14', 'fActWaterLevelMixTank2', '303.322143554688']
['2021-5-4 10:19:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:19:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:19:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:19:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:19:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:19:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:19:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:19:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:19:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:19:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:19:14', 'DoVa_Co2', '0']
['2021-5-4 10:19:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:19:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:19:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:19:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:19:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:20:14', 'fKWhCounter', '3375.54223632813']
['2021-5-4 10:20:14', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 10:20:14', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 10:20:14', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 10:20:14', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 10:20:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:20:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:20:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:20:14', 'fActRhValMemo', '52']
['2021-5-4 10:20:14', 'fActCo2ValMemo', '810']
['2021-5-4 10:20:14', 'fActWaterLevelMixTank1', '289.034759521484']
['2021-5-4 10:20:14', 'fActWaterLevelMixTank2', '303.593780517578']
['2021-5-4 10:20:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:20:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:20:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:20:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:20:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:20:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:20:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:20:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:20:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:20:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:20:14', 'DoVa_Co2', '0']
['2021-5-4 10:20:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:20:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:20:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:20:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:20:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:21:14', 'fKWhCounter', '3375.64233398438']
['2021-5-4 10:21:14', 'fActPhLevelMixTank1', '5.6251106262207']
['2021-5-4 10:21:14', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 10:21:14', 'fActPhLevelMixTank2', '3.85430455207825']
['2021-5-4 10:21:14', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 10:21:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:21:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:21:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:21:14', 'fActRhValMemo', '52']
['2021-5-4 10:21:14', 'fActCo2ValMemo', '810']
['2021-5-4 10:21:14', 'fActWaterLevelMixTank1', '289.034759521484']
['2021-5-4 10:21:14', 'fActWaterLevelMixTank2', '303.566619873047']
['2021-5-4 10:21:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:21:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:21:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:21:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:21:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:21:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:21:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:21:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:21:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:21:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:21:14', 'DoVa_Co2', '0']
['2021-5-4 10:21:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:21:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:21:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:21:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:21:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:22:14', 'fKWhCounter', '3375.74243164063']
['2021-5-4 10:22:14', 'fActPhLevelMixTank1', '5.6265754699707']
['2021-5-4 10:22:14', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 10:22:14', 'fActPhLevelMixTank2', '3.85625791549683']
['2021-5-4 10:22:14', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 10:22:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:22:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:22:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:22:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:22:14', 'fActCo2ValMemo', '806']
['2021-5-4 10:22:14', 'fActWaterLevelMixTank1', '287.513671875']
['2021-5-4 10:22:14', 'fActWaterLevelMixTank2', '303.485137939453']
['2021-5-4 10:22:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:22:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:22:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:22:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:22:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:22:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:22:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:22:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:22:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:22:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:22:14', 'DoVa_Co2', '0']
['2021-5-4 10:22:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:22:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:22:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:22:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:22:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:23:14', 'fKWhCounter', '3375.94262695313']
['2021-5-4 10:23:14', 'fActPhLevelMixTank1', '5.6187629699707']
['2021-5-4 10:23:14', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 10:23:14', 'fActPhLevelMixTank2', '3.84917759895325']
['2021-5-4 10:23:14', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 10:23:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:23:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:23:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:23:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:23:14', 'fActCo2ValMemo', '802']
['2021-5-4 10:23:14', 'fActWaterLevelMixTank1', '288.817443847656']
['2021-5-4 10:23:14', 'fActWaterLevelMixTank2', '303.566619873047']
['2021-5-4 10:23:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:23:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:23:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:23:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:23:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:23:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:23:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:23:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:23:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:23:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:23:14', 'DoVa_Co2', '0']
['2021-5-4 10:23:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:23:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:23:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:23:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:23:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:24:14', 'fKWhCounter', '3376.04272460938']
['2021-5-4 10:24:14', 'fActPhLevelMixTank1', '5.6241340637207']
['2021-5-4 10:24:14', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 10:24:14', 'fActPhLevelMixTank2', '3.85283970832825']
['2021-5-4 10:24:14', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 10:24:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:24:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:24:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:24:14', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 10:24:14', 'fActCo2ValMemo', '801']

['2021-5-4 10:24:14', 'fActWaterLevelMixTank1', '289.469360351563']
['2021-5-4 10:24:14', 'fActWaterLevelMixTank2', '304.408660888672']
['2021-5-4 10:24:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:24:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:24:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:24:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:24:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:24:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:24:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:24:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:24:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:24:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:24:14', 'DoVa_Co2', '0']
['2021-5-4 10:24:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:24:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:24:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:24:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:24:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:25:14', 'fKWhCounter', '3376.24291992188']
['2021-5-4 10:25:14', 'fActPhLevelMixTank1', '5.63463258743286']
['2021-5-4 10:25:14', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 10:25:14', 'fActPhLevelMixTank2', '3.85332798957825']
['2021-5-4 10:25:14', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 10:25:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:25:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:25:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:25:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:25:14', 'fActCo2ValMemo', '799']
['2021-5-4 10:25:14', 'fActWaterLevelMixTank1', '287.459320068359']
['2021-5-4 10:25:14', 'fActWaterLevelMixTank2', '304.001220703125']
['2021-5-4 10:25:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:25:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:25:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:25:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:25:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:25:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:25:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:25:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:25:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:25:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:25:14', 'DoVa_Co2', '0']
['2021-5-4 10:25:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:25:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:25:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:25:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:25:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:26:14', 'fKWhCounter', '3376.34301757813']
['2021-5-4 10:26:14', 'fActPhLevelMixTank1', '5.63390016555786']
['2021-5-4 10:26:14', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 10:26:14', 'fActPhLevelMixTank2', '3.85039830207825']
['2021-5-4 10:26:14', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 10:26:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:26:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:26:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:26:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:26:14', 'fActCo2ValMemo', '800']
['2021-5-4 10:26:14', 'fActWaterLevelMixTank1', '289.578002929688']
['2021-5-4 10:26:14', 'fActWaterLevelMixTank2', '304.381500244141']
['2021-5-4 10:26:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:26:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:26:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:26:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:26:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:26:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:26:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:26:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:26:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:26:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:26:14', 'DoVa_Co2', '0']
['2021-5-4 10:26:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:26:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:26:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:26:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:26:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:27:14', 'fKWhCounter', '3376.44311523438']
['2021-5-4 10:27:14', 'fActPhLevelMixTank1', '5.63805055618286']
['2021-5-4 10:27:14', 'fActEcLevelMixTank1', '2031.92236328125']
['2021-5-4 10:27:14', 'fActPhLevelMixTank2', '3.84991002082825']
['2021-5-4 10:27:14', 'fActEcLevelMixTank2', '1038.544921875']
['2021-5-4 10:27:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:27:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:27:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:27:14', 'fActRhValMemo', '52']
['2021-5-4 10:27:14', 'fActCo2ValMemo', '801']
['2021-5-4 10:27:14', 'fActWaterLevelMixTank1', '290.202728271484']
['2021-5-4 10:27:14', 'fActWaterLevelMixTank2', '304.517303466797']
['2021-5-4 10:27:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:27:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:27:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:27:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:27:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:27:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:27:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:27:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:27:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:27:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:27:14', 'DoVa_Co2', '0']
['2021-5-4 10:27:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:27:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:27:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:27:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:27:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:28:14', 'fKWhCounter', '3376.64331054688']
['2021-5-4 10:28:14', 'fActPhLevelMixTank1', '5.63756227493286']
['2021-5-4 10:28:14', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 10:28:14', 'fActPhLevelMixTank2', '3.84966588020325']
['2021-5-4 10:28:14', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 10:28:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:28:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:28:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:28:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:28:14', 'fActCo2ValMemo', '803']
['2021-5-4 10:28:14', 'fActWaterLevelMixTank1', '290.610168457031']
['2021-5-4 10:28:14', 'fActWaterLevelMixTank2', '304.571624755859']
['2021-5-4 10:28:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:28:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:28:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:28:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:28:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:28:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:28:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:28:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:28:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:28:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:28:14', 'DoVa_Co2', '0']
['2021-5-4 10:28:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:28:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:28:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:28:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:28:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:29:14', 'fKWhCounter', '3376.74340820313']
['2021-5-4 10:29:14', 'fActPhLevelMixTank1', '5.63902711868286']

['2021-5-4 10:29:14', 'fActEcLevelMixTank1', '2031.46459960938']
['2021-5-4 10:29:14', 'fActPhLevelMixTank2', '3.85479283332825']
['2021-5-4 10:29:14', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 10:29:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:29:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:29:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:29:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:29:14', 'fActCo2ValMemo', '803']
['2021-5-4 10:29:14', 'fActWaterLevelMixTank1', '290.094085693359']
['2021-5-4 10:29:14', 'fActWaterLevelMixTank2', '304.381500244141']
['2021-5-4 10:29:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:29:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:29:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:29:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:29:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:29:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:29:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:29:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:29:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:29:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:29:14', 'DoVa_Co2', '0']
['2021-5-4 10:29:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:29:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:29:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:29:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:29:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:30:14', 'fKWhCounter', '3376.94360351563']
['2021-5-4 10:30:14', 'fActPhLevelMixTank1', '5.64537477493286']
['2021-5-4 10:30:14', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 10:30:14', 'fActPhLevelMixTank2', '3.85332798957825']
['2021-5-4 10:30:14', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 10:30:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:30:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:30:14', 'fActTempValMemo', '20.1000003814697']
['2021-5-4 10:30:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:30:14', 'fActCo2ValMemo', '805']
['2021-5-4 10:30:14', 'fActWaterLevelMixTank1', '290.610168457031']
['2021-5-4 10:30:14', 'fActWaterLevelMixTank2', '305.250671386719']
['2021-5-4 10:30:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:30:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:30:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:30:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:30:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:30:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:30:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:30:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:30:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:30:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:30:14', 'DoVa_Co2', '0']
['2021-5-4 10:30:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:30:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:30:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:30:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:30:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:31:14', 'fKWhCounter', '3377.04370117188']
['2021-5-4 10:31:14', 'fActPhLevelMixTank1', '5.64561891555786']
['2021-5-4 10:31:14', 'fActEcLevelMixTank1', '2028.87048339844']
['2021-5-4 10:31:14', 'fActPhLevelMixTank2', '3.85894346237183']
['2021-5-4 10:31:14', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 10:31:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:31:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:31:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:31:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:31:14', 'fActCo2ValMemo', '805']
['2021-5-4 10:31:14', 'fActWaterLevelMixTank1', '290.202728271484']
['2021-5-4 10:31:14', 'fActWaterLevelMixTank2', '304.680267333984']
['2021-5-4 10:31:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:31:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:31:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:31:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:31:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:31:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:31:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:31:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:31:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:31:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:31:14', 'DoVa_Co2', '0']
['2021-5-4 10:31:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:31:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:31:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:31:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:31:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:32:14', 'fKWhCounter', '3377.14379882813']
['2021-5-4 10:32:14', 'fActPhLevelMixTank1', '5.64806032180786']
['2021-5-4 10:32:14', 'fActEcLevelMixTank1', '2028.56530761719']
['2021-5-4 10:32:14', 'fActPhLevelMixTank2', '3.86114072799683']
['2021-5-4 10:32:14', 'fActEcLevelMixTank2', '1040.3759765625']
['2021-5-4 10:32:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:32:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:32:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:32:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:32:14', 'fActCo2ValMemo', '802']
['2021-5-4 10:32:14', 'fActWaterLevelMixTank1', '290.229888916016']
['2021-5-4 10:32:14', 'fActWaterLevelMixTank2', '305.223510742188']
['2021-5-4 10:32:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:32:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:32:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:32:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:32:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:32:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:32:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:32:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:32:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:32:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:32:14', 'DoVa_Co2', '0']
['2021-5-4 10:32:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:32:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:32:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:32:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:32:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:33:14', 'fKWhCounter', '3377.34399414063']
['2021-5-4 10:33:14', 'fActPhLevelMixTank1', '5.64806032180786']
['2021-5-4 10:33:14', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 10:33:14', 'fActPhLevelMixTank2', '3.86211729049683']
['2021-5-4 10:33:14', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 10:33:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:33:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:33:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:33:14', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 10:33:14', 'fActCo2ValMemo', '801']
['2021-5-4 10:33:14', 'fActWaterLevelMixTank1', '290.311370849609']
['2021-5-4 10:33:14', 'fActWaterLevelMixTank2', '305.169189453125']
['2021-5-4 10:33:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:33:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:33:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:33:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:33:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:33:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:33:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:33:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:33:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:33:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:33:14', 'DoVa_Co2', '0']
['2021-5-4 10:33:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:33:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:33:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:33:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']

['2021-5-4 10:33:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:33:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:34:14', 'fKWhCounter', '3377.44409179688']
['2021-5-4 10:34:14', 'fActPhLevelMixTank1', '5.65001392364502']
['2021-5-4 10:34:14', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 10:34:14', 'fActPhLevelMixTank2', '3.85992002487183']
['2021-5-4 10:34:14', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 10:34:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:34:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:34:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:34:14', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 10:34:14', 'fActCo2ValMemo', '800']
['2021-5-4 10:34:14', 'fActWaterLevelMixTank1', '290.066925048828']
['2021-5-4 10:34:14', 'fActWaterLevelMixTank2', '306.255676269531']
['2021-5-4 10:34:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:34:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:34:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:34:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:34:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:34:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:34:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:34:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:34:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:34:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:34:14', 'DoVa_Co2', '0']
['2021-5-4 10:34:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:34:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:34:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:34:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:34:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:35:14', 'fKWhCounter', '3377.64428710938']
['2021-5-4 10:35:14', 'fActPhLevelMixTank1', '5.66197681427002']
['2021-5-4 10:35:14', 'fActEcLevelMixTank1', '2029.48083496094']
['2021-5-4 10:35:14', 'fActPhLevelMixTank2', '3.86236143112183']
['2021-5-4 10:35:14', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 10:35:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:35:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:35:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:35:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:35:14', 'fActCo2ValMemo', '798']
['2021-5-4 10:35:14', 'fActWaterLevelMixTank1', '290.392852783203']
['2021-5-4 10:35:14', 'fActWaterLevelMixTank2', '305.685272216797']
['2021-5-4 10:35:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:35:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:35:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:35:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:35:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:35:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:35:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:35:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:35:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:35:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:35:14', 'DoVa_Co2', '0']
['2021-5-4 10:35:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:35:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:35:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:35:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:35:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:36:14', 'fKWhCounter', '3377.74438476563']
['2021-5-4 10:36:14', 'fActPhLevelMixTank1', '5.66173267364502']
['2021-5-4 10:36:14', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 10:36:14', 'fActPhLevelMixTank2', '3.86431479454041']
['2021-5-4 10:36:14', 'fActEcLevelMixTank2', '1040.22338867188']
['2021-5-4 10:36:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:36:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:36:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:36:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 10:36:14', 'fActCo2ValMemo', '795']
['2021-5-4 10:36:14', 'fActWaterLevelMixTank1', '291.560852050781']
['2021-5-4 10:36:14', 'fActWaterLevelMixTank2', '306.119873046875']
['2021-5-4 10:36:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:36:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:36:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:36:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:36:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:36:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:36:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:36:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:36:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:36:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:36:14', 'DoVa_Co2', '0']
['2021-5-4 10:36:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:36:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:36:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:36:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:36:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:37:14', 'fKWhCounter', '3377.94458007813']
['2021-5-4 10:37:14', 'fActPhLevelMixTank1', '5.66466283798218']
['2021-5-4 10:37:14', 'fActEcLevelMixTank1', '2032.53271484375']
['2021-5-4 10:37:14', 'fActPhLevelMixTank2', '3.86480307579041']
['2021-5-4 10:37:14', 'fActEcLevelMixTank2', '1039.00268554688']
['2021-5-4 10:37:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:37:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:37:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:37:14', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 10:37:14', 'fActCo2ValMemo', '794']
['2021-5-4 10:37:14', 'fActWaterLevelMixTank1', '290.963287353516']
['2021-5-4 10:37:14', 'fActWaterLevelMixTank2', '306.092712402344']
['2021-5-4 10:37:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:37:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:37:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:37:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:37:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:37:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:37:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:37:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:37:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:37:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:37:14', 'DoVa_Co2', '0']
['2021-5-4 10:37:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:37:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:37:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:37:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:37:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:38:14', 'fKWhCounter', '3378.04467773438']
['2021-5-4 10:38:14', 'fActPhLevelMixTank1', '5.65880298614502']
['2021-5-4 10:38:14', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 10:38:14', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 10:38:14', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 10:38:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:38:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:38:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:38:14', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 10:38:14', 'fActCo2ValMemo', '792']
['2021-5-4 10:38:14', 'fActWaterLevelMixTank1', '292.212738037109']
['2021-5-4 10:38:14', 'fActWaterLevelMixTank2', '306.527313232422']
['2021-5-4 10:38:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:38:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:38:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:38:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:38:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:38:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:38:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:38:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:38:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:38:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:38:14', 'DoVa_Co2', '0']
['2021-5-4 10:38:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:38:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:38:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:38:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:38:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:39:14', 'fKWhCounter', '3378.14477539063']
['2021-5-4 10:39:14', 'fActPhLevelMixTank1', '5.66490697860718']
['2021-5-4 10:39:14', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 10:39:14', 'fActPhLevelMixTank2', '3.86284971237183']
['2021-5-4 10:39:14', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 10:39:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:39:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:39:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:39:14', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 10:39:14', 'fActCo2ValMemo', '790']
['2021-5-4 10:39:14', 'fActWaterLevelMixTank1', '292.158416748047']
['2021-5-4 10:39:14', 'fActWaterLevelMixTank2', '306.310028076172']
['2021-5-4 10:39:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:39:14', 'DoPu_AddEcAMixTank_1', '0']

['2021-5-4 10:39:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:39:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:39:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:39:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:39:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:39:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:39:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:39:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:39:14', 'DoVa_Co2', '0']
['2021-5-4 10:39:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:39:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:39:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:39:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:39:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:40:14', 'fKWhCounter', '3378.34497070313']
['2021-5-4 10:40:14', 'fActPhLevelMixTank1', '5.66734838485718']
['2021-5-4 10:40:14', 'fActEcLevelMixTank1', '2032.99047851563']
['2021-5-4 10:40:14', 'fActPhLevelMixTank2', '3.86602377891541']
['2021-5-4 10:40:14', 'fActEcLevelMixTank2', '1039.00268554688']
['2021-5-4 10:40:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:40:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:40:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:40:14', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 10:40:14', 'fActCo2ValMemo', '790']
['2021-5-4 10:40:14', 'fActWaterLevelMixTank1', '292.321411132813']
['2021-5-4 10:40:14', 'fActWaterLevelMixTank2', '306.9619140625']
['2021-5-4 10:40:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:40:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:40:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:40:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:40:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:40:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:40:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:40:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:40:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:40:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:40:14', 'DoVa_Co2', '0']
['2021-5-4 10:40:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:40:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:40:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:40:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:40:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:41:14', 'fKWhCounter', '3378.44506835938']
['2021-5-4 10:41:14', 'fActPhLevelMixTank1', '5.66978979110718']
['2021-5-4 10:41:14', 'fActEcLevelMixTank1', '2036.04235839844']
['2021-5-4 10:41:14', 'fActPhLevelMixTank2', '3.86626791954041']
['2021-5-4 10:41:14', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 10:41:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:41:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:41:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:41:14', 'fActRhValMemo', '51.5']
['2021-5-4 10:41:14', 'fActCo2ValMemo', '791']
['2021-5-4 10:41:14', 'fActWaterLevelMixTank1', '292.321411132813']
['2021-5-4 10:41:14', 'fActWaterLevelMixTank2', '306.907592773438']
['2021-5-4 10:41:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:41:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:41:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:41:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:41:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:41:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:41:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:41:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:41:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:41:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:41:14', 'DoVa_Co2', '0']
['2021-5-4 10:41:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:41:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:41:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:41:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:41:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:42:14', 'fKWhCounter', '3378.64526367188']
['2021-5-4 10:42:14', 'fActPhLevelMixTank1', '5.66344165802002']
['2021-5-4 10:42:14', 'fActEcLevelMixTank1', '2033.14306640625']
['2021-5-4 10:42:14', 'fActPhLevelMixTank2', '3.86040830612183']
['2021-5-4 10:42:14', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 10:42:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:42:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:42:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:42:14', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 10:42:14', 'fActCo2ValMemo', '789']
['2021-5-4 10:42:14', 'fActWaterLevelMixTank1', '292.402893066406']
['2021-5-4 10:42:14', 'fActWaterLevelMixTank2', '306.744598388672']
['2021-5-4 10:42:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:42:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:42:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:42:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:42:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:42:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:42:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:42:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:42:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:42:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:42:14', 'DoVa_Co2', '0']
['2021-5-4 10:42:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:42:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:42:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:42:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:42:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:43:14', 'fKWhCounter', '3378.74536132813']
['2021-5-4 10:43:14', 'fActPhLevelMixTank1', '5.66466283798218']
['2021-5-4 10:43:14', 'fActEcLevelMixTank1', '2036.65270996094']
['2021-5-4 10:43:14', 'fActPhLevelMixTank2', '3.86114072799683']
['2021-5-4 10:43:14', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 10:43:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:43:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:43:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:43:14', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 10:43:14', 'fActCo2ValMemo', '788']
['2021-5-4 10:43:14', 'fActWaterLevelMixTank1', '292.375732421875']
['2021-5-4 10:43:14', 'fActWaterLevelMixTank2', '307.233520507813']
['2021-5-4 10:43:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:43:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:43:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:43:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:43:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:43:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:43:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:43:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:43:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:43:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:43:14', 'DoVa_Co2', '0']
['2021-5-4 10:43:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:43:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:43:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:43:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:43:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:44:14', 'fKWhCounter', '3378.84545898438']
['2021-5-4 10:44:14', 'fActPhLevelMixTank1', '5.61461210250854']
['2021-5-4 10:44:14', 'fActEcLevelMixTank1', '2071.44384765625']
['2021-5-4 10:44:14', 'fActPhLevelMixTank2', '3.79912710189819']
['2021-5-4 10:44:14', 'fActEcLevelMixTank2', '1054.56713867188']
['2021-5-4 10:44:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:44:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:44:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:44:14', 'fActRhValMemo', '51']
['2021-5-4 10:44:14', 'fActCo2ValMemo', '790']
['2021-5-4 10:44:14', 'fActWaterLevelMixTank1', '295.119110107422']
['2021-5-4 10:44:14', 'fActWaterLevelMixTank2', '321.738250732422']
['2021-5-4 10:44:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:44:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:44:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:44:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:44:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:44:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:44:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:44:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:44:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:44:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:44:14', 'DoVa_Co2', '0']
['2021-5-4 10:44:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:44:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:44:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:44:14', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:44:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:45:14', 'fKWhCounter', '3379.04565429688']
['2021-5-4 10:45:14', 'fActPhLevelMixTank1', '5.56602668762207']
['2021-5-4 10:45:14', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 10:45:14', 'fActPhLevelMixTank2', '3.77446818351746']
['2021-5-4 10:45:14', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 10:45:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:45:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:45:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:45:14', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 10:45:14', 'fActCo2ValMemo', '792']
['2021-5-4 10:45:14', 'fActWaterLevelMixTank1', '286.481475830078']
['2021-5-4 10:45:14', 'fActWaterLevelMixTank2', '319.701049804688']
['2021-5-4 10:45:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:45:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:45:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:45:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:45:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:45:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:45:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:45:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:45:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:45:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:45:14', 'DoVa_Co2', '0']
['2021-5-4 10:45:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:45:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:45:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:45:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:45:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:46:14', 'fKWhCounter', '3379.24584960938']
['2021-5-4 10:46:14', 'fActPhLevelMixTank1', '5.56871223449707']
['2021-5-4 10:46:14', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 10:46:14', 'fActPhLevelMixTank2', '3.77935123443604']
['2021-5-4 10:46:14', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 10:46:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:46:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:46:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:46:14', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 10:46:14', 'fActCo2ValMemo', '790']
['2021-5-4 10:46:14', 'fActWaterLevelMixTank1', '277.083312988281']
['2021-5-4 10:46:14', 'fActWaterLevelMixTank2', '304.951904296875']
['2021-5-4 10:46:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:46:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:46:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:46:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:46:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:46:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:46:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:46:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:46:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:46:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:46:14', 'DoVa_Co2', '0']
['2021-5-4 10:46:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:46:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:46:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:46:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:46:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:47:14', 'fKWhCounter', '3379.44604492188']
['2021-5-4 10:47:14', 'fActPhLevelMixTank1', '5.56895637512207']
['2021-5-4 10:47:14', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 10:47:14', 'fActPhLevelMixTank2', '3.78301334381104']
['2021-5-4 10:47:14', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 10:47:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:47:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:47:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:47:14', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 10:47:14', 'fActCo2ValMemo', '790']
['2021-5-4 10:47:14', 'fActWaterLevelMixTank1', '285.422149658203']
['2021-5-4 10:47:14', 'fActWaterLevelMixTank2', '284.172698974609']
['2021-5-4 10:47:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:47:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:47:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:47:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:47:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:47:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:47:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:47:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:47:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:47:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:47:14', 'DoVa_Co2', '0']
['2021-5-4 10:47:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:47:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:47:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:47:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:47:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:48:14', 'fKWhCounter', '3379.54614257813']
['2021-5-4 10:48:14', 'fActPhLevelMixTank1', '5.56651496887207']
['2021-5-4 10:48:14', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 10:48:14', 'fActPhLevelMixTank2', '3.78496646881104']
['2021-5-4 10:48:14', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 10:48:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:48:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:48:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:48:14', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 10:48:14', 'fActCo2ValMemo', '789']
['2021-5-4 10:48:14', 'fActWaterLevelMixTank1', '278.0068359375']
['2021-5-4 10:48:14', 'fActWaterLevelMixTank2', '317.147796630859']
['2021-5-4 10:48:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:48:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:48:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:48:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:48:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:48:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:48:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:48:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:48:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:48:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:48:14', 'DoVa_Co2', '0']
['2021-5-4 10:48:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:48:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:48:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:48:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:48:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:49:14', 'fKWhCounter', '3379.74633789063']
['2021-5-4 10:49:14', 'fActPhLevelMixTank1', '5.56993293762207']
['2021-5-4 10:49:14', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 10:49:14', 'fActPhLevelMixTank2', '3.80401015281677']
['2021-5-4 10:49:14', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 10:49:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:49:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:49:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:49:14', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 10:49:14', 'fActCo2ValMemo', '787']
['2021-5-4 10:49:14', 'fActWaterLevelMixTank1', '277.898193359375']
['2021-5-4 10:49:14', 'fActWaterLevelMixTank2', '298.1884765625']
['2021-5-4 10:49:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:49:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:49:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:49:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:49:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:49:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:49:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:49:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:49:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:49:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:49:14', 'DoVa_Co2', '0']
['2021-5-4 10:49:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:49:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:49:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:49:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_3_Red', '0']

['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:49:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:50:14', 'fKWhCounter', '3379.84643554688']
['2021-5-4 10:50:14', 'fActPhLevelMixTank1', '5.58043146133423']
['2021-5-4 10:50:14', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 10:50:14', 'fActPhLevelMixTank2', '3.83648180961609']
['2021-5-4 10:50:14', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 10:50:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:50:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:50:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 10:50:14', 'fActRhValMemo', '51.5']
['2021-5-4 10:50:14', 'fActCo2ValMemo', '789']
['2021-5-4 10:50:14', 'fActWaterLevelMixTank1', '278.387115478516']
['2021-5-4 10:50:14', 'fActWaterLevelMixTank2', '297.645233154297']
['2021-5-4 10:50:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:50:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:50:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:50:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:50:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:50:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:50:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:50:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:50:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:50:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:50:14', 'DoVa_Co2', '0']
['2021-5-4 10:50:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:50:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:50:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:50:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:50:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:51:14', 'fKWhCounter', '3380.04663085938']
['2021-5-4 10:51:14', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 10:51:14', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 10:51:14', 'fActPhLevelMixTank2', '3.82891321182251']
['2021-5-4 10:51:14', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 10:51:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:51:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:51:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:51:14', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 10:51:14', 'fActCo2ValMemo', '785']
['2021-5-4 10:51:14', 'fActWaterLevelMixTank1', '277.789520263672']
['2021-5-4 10:51:14', 'fActWaterLevelMixTank2', '297.455078125']
['2021-5-4 10:51:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:51:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:51:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:51:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:51:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:51:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:51:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:51:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:51:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:51:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:51:14', 'DoVa_Co2', '0']
['2021-5-4 10:51:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:51:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:51:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:51:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:51:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:52:14', 'fKWhCounter', '3380.14672851563']
['2021-5-4 10:52:14', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 10:52:14', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 10:52:14', 'fActPhLevelMixTank2', '3.83379626274109']
['2021-5-4 10:52:14', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 10:52:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:52:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:52:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:52:14', 'fActRhValMemo', '51.5']
['2021-5-4 10:52:14', 'fActCo2ValMemo', '783']
['2021-5-4 10:52:14', 'fActWaterLevelMixTank1', '277.925354003906']
['2021-5-4 10:52:14', 'fActWaterLevelMixTank2', '297.699554443359']
['2021-5-4 10:52:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:52:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:52:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:52:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:52:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:52:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:52:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:52:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:52:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:52:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:52:14', 'DoVa_Co2', '0']
['2021-5-4 10:52:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:52:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:52:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:52:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:52:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:53:14', 'fKWhCounter', '3380.34692382813']
['2021-5-4 10:53:14', 'fActPhLevelMixTank1', '5.58043146133423']
['2021-5-4 10:53:14', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 10:53:14', 'fActPhLevelMixTank2', '3.82964563369751']
['2021-5-4 10:53:14', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 10:53:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:53:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:53:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:53:14', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 10:53:14', 'fActCo2ValMemo', '783']
['2021-5-4 10:53:14', 'fActWaterLevelMixTank1', '276.947509765625']
['2021-5-4 10:53:14', 'fActWaterLevelMixTank2', '297.455078125']
['2021-5-4 10:53:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:53:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:53:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:53:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:53:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:53:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:53:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:53:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:53:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:53:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:53:14', 'DoVa_Co2', '0']
['2021-5-4 10:53:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:53:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:53:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:53:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:53:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:54:14', 'fKWhCounter', '3380.44702148438']
['2021-5-4 10:54:14', 'fActPhLevelMixTank1', '5.58287286758423']
['2021-5-4 10:54:14', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 10:54:14', 'fActPhLevelMixTank2', '3.82598352432251']
['2021-5-4 10:54:14', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 10:54:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:54:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:54:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:54:14', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 10:54:14', 'fActCo2ValMemo', '779']
['2021-5-4 10:54:14', 'fActWaterLevelMixTank1', '278.631561279297']
['2021-5-4 10:54:14', 'fActWaterLevelMixTank2', '297.129119873047']
['2021-5-4 10:54:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:54:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:54:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:54:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:54:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:54:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:54:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:54:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:54:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:54:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:54:14', 'DoVa_Co2', '0']
['2021-5-4 10:54:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:54:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:54:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:54:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_3_White', '0']

['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:54:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:55:14', 'fKWhCounter', '3380.54711914063']
['2021-5-4 10:55:14', 'fActPhLevelMixTank1', '5.57994318008423']
['2021-5-4 10:55:14', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 10:55:14', 'fActPhLevelMixTank2', '3.82696008682251']
['2021-5-4 10:55:14', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 10:55:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:55:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:55:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:55:14', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 10:55:14', 'fActCo2ValMemo', '779']
['2021-5-4 10:55:14', 'fActWaterLevelMixTank1', '278.196960449219']
['2021-5-4 10:55:14', 'fActWaterLevelMixTank2', '297.427917480469']
['2021-5-4 10:55:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:55:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:55:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:55:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:55:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:55:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:55:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:55:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:55:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:55:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:55:14', 'DoVa_Co2', '0']
['2021-5-4 10:55:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:55:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:55:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:55:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:55:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:56:14', 'fKWhCounter', '3380.74731445313']
['2021-5-4 10:56:14', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 10:56:14', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 10:56:14', 'fActPhLevelMixTank2', '3.82866907119751']
['2021-5-4 10:56:14', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 10:56:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:56:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:56:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:56:14', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 10:56:14', 'fActCo2ValMemo', '780']
['2021-5-4 10:56:14', 'fActWaterLevelMixTank1', '278.033996582031']
['2021-5-4 10:56:14', 'fActWaterLevelMixTank2', '298.079803466797']
['2021-5-4 10:56:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:56:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:56:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:56:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:56:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:56:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:56:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:56:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:56:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:56:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:56:14', 'DoVa_Co2', '0']
['2021-5-4 10:56:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:56:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:56:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:56:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:56:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:57:14', 'fKWhCounter', '3380.84741210938']
['2021-5-4 10:57:14', 'fActPhLevelMixTank1', '5.57432794570923']
['2021-5-4 10:57:14', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 10:57:14', 'fActPhLevelMixTank2', '3.82818078994751']
['2021-5-4 10:57:14', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 10:57:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:57:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:57:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:57:14', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 10:57:14', 'fActCo2ValMemo', '779']
['2021-5-4 10:57:14', 'fActWaterLevelMixTank1', '279.555084228516']
['2021-5-4 10:57:14', 'fActWaterLevelMixTank2', '298.079803466797']
['2021-5-4 10:57:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:57:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:57:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:57:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:57:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:57:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:57:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:57:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:57:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:57:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:57:14', 'DoVa_Co2', '0']
['2021-5-4 10:57:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:57:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:57:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:57:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:57:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:58:14', 'fKWhCounter', '3381.04760742188']
['2021-5-4 10:58:14', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 10:58:14', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 10:58:14', 'fActPhLevelMixTank2', '3.82207703590393']
['2021-5-4 10:58:14', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 10:58:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:58:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:58:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:58:14', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 10:58:14', 'fActCo2ValMemo', '776']
['2021-5-4 10:58:14', 'fActWaterLevelMixTank1', '279.881042480469']
['2021-5-4 10:58:14', 'fActWaterLevelMixTank2', '297.998321533203']
['2021-5-4 10:58:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:58:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:58:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:58:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:58:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:58:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:58:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:58:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:58:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:58:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:58:14', 'DoVa_Co2', '0']
['2021-5-4 10:58:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:58:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:58:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:58:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:58:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 10:59:14', 'fKWhCounter', '3381.14770507813']
['2021-5-4 10:59:14', 'fActPhLevelMixTank1', '5.58409357070923']
['2021-5-4 10:59:14', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 10:59:14', 'fActPhLevelMixTank2', '3.82476282119751']
['2021-5-4 10:59:14', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 10:59:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 10:59:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 10:59:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 10:59:14', 'fActRhValMemo', '51.5']
['2021-5-4 10:59:14', 'fActCo2ValMemo', '780']
['2021-5-4 10:59:14', 'fActWaterLevelMixTank1', '279.337799072266']
['2021-5-4 10:59:14', 'fActWaterLevelMixTank2', '298.1884765625']
['2021-5-4 10:59:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 10:59:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 10:59:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 10:59:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 10:59:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 10:59:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 10:59:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 10:59:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 10:59:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 10:59:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 10:59:14', 'DoVa_Co2', '0']
['2021-5-4 10:59:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 10:59:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 10:59:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 10:59:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_2_Blue', '0']

['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 10:59:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:0:14', 'fKWhCounter', '3381.24780273438']
['2021-5-4 11:0:14', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 11:0:14', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 11:0:14', 'fActPhLevelMixTank2', '3.82573938369751']
['2021-5-4 11:0:14', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 11:0:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:0:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:0:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 11:0:14', 'fActRhValMemo', '52']
['2021-5-4 11:0:14', 'fActCo2ValMemo', '780']
['2021-5-4 11:0:14', 'fActWaterLevelMixTank1', '280.478607177734']
['2021-5-4 11:0:14', 'fActWaterLevelMixTank2', '298.840362548828']
['2021-5-4 11:0:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:0:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:0:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:0:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:0:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:0:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:0:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:0:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:0:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:0:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:0:14', 'DoVa_Co2', '0']
['2021-5-4 11:0:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:0:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:0:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:0:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:0:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:1:14', 'fKWhCounter', '3381.44799804688']
['2021-5-4 11:1:14', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 11:1:14', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 11:1:14', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 11:1:14', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 11:1:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:1:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:1:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 11:1:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 11:1:14', 'fActCo2ValMemo', '776']
['2021-5-4 11:1:14', 'fActWaterLevelMixTank1', '281.130493164063']
['2021-5-4 11:1:14', 'fActWaterLevelMixTank2', '299.220642089844']
['2021-5-4 11:1:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:1:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:1:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:1:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:1:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:1:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:1:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:1:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:1:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:1:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:1:14', 'DoVa_Co2', '0']
['2021-5-4 11:1:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:1:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:1:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:1:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:1:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:2:14', 'fKWhCounter', '3381.54809570313']
['2021-5-4 11:2:14', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 11:2:14', 'fActEcLevelMixTank1', '2014.83203125']
['2021-5-4 11:2:14', 'fActPhLevelMixTank2', '3.83013391494751']
['2021-5-4 11:2:14', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 11:2:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:2:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:2:14', 'fActTempValMemo', '20.2000007629395']
['2021-5-4 11:2:14', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 11:2:14', 'fActCo2ValMemo', '776']
['2021-5-4 11:2:14', 'fActWaterLevelMixTank1', '281.755249023438']
['2021-5-4 11:2:14', 'fActWaterLevelMixTank2', '299.166320800781']
['2021-5-4 11:2:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:2:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:2:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:2:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:2:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:2:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:2:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:2:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:2:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:2:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:2:14', 'DoVa_Co2', '0']
['2021-5-4 11:2:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:2:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:2:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:2:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:2:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:3:14', 'fKWhCounter', '3381.74829101563']
['2021-5-4 11:3:14', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 11:3:14', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 11:3:14', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 11:3:14', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 11:3:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:3:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:3:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 11:3:14', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 11:3:14', 'fActCo2ValMemo', '774']
['2021-5-4 11:3:14', 'fActWaterLevelMixTank1', '281.103332519531']
['2021-5-4 11:3:14', 'fActWaterLevelMixTank2', '299.13916015625']
['2021-5-4 11:3:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:3:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:3:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:3:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:3:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:3:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:3:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:3:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:3:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:3:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:3:14', 'DoVa_Co2', '0']
['2021-5-4 11:3:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:3:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:3:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:3:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:3:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:4:14', 'fKWhCounter', '3381.84838867188']
['2021-5-4 11:4:14', 'fActPhLevelMixTank1', '5.59068584442139']
['2021-5-4 11:4:14', 'fActEcLevelMixTank1', '2017.12084960938']
['2021-5-4 11:4:14', 'fActPhLevelMixTank2', '3.82696008682251']
['2021-5-4 11:4:14', 'fActEcLevelMixTank2', '1040.986328125']
['2021-5-4 11:4:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:4:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:4:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 11:4:14', 'fActRhValMemo', '52']
['2021-5-4 11:4:14', 'fActCo2ValMemo', '773']
['2021-5-4 11:4:14', 'fActWaterLevelMixTank1', '281.429290771484']
['2021-5-4 11:4:14', 'fActWaterLevelMixTank2', '299.111999511719']
['2021-5-4 11:4:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:4:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:4:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:4:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:4:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:4:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:4:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:4:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:4:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:4:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:4:14', 'DoVa_Co2', '0']
['2021-5-4 11:4:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:4:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:4:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:4:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']

['2021-5-4 11:4:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:4:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:5:14', 'fKWhCounter', '3382.04858398438']
['2021-5-4 11:5:14', 'fActPhLevelMixTank1', '5.58995342254639']
['2021-5-4 11:5:14', 'fActEcLevelMixTank1', '2016.96826171875']
['2021-5-4 11:5:14', 'fActPhLevelMixTank2', '3.83159875869751']
['2021-5-4 11:5:14', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 11:5:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:5:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:5:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 11:5:14', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 11:5:14', 'fActCo2ValMemo', '773']
['2021-5-4 11:5:14', 'fActWaterLevelMixTank1', '281.565093994141']
['2021-5-4 11:5:14', 'fActWaterLevelMixTank2', '300.08984375']
['2021-5-4 11:5:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:5:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:5:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:5:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:5:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:5:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:5:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:5:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:5:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:5:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:5:14', 'DoVa_Co2', '0']
['2021-5-4 11:5:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:5:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:5:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:5:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:5:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:6:14', 'fKWhCounter', '3382.14868164063']
['2021-5-4 11:6:14', 'fActPhLevelMixTank1', '5.59825420379639']
['2021-5-4 11:6:14', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 11:6:14', 'fActPhLevelMixTank2', '3.83184289932251']
['2021-5-4 11:6:14', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 11:6:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:6:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:6:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 11:6:14', 'fActRhValMemo', '52']
['2021-5-4 11:6:14', 'fActCo2ValMemo', '773']
['2021-5-4 11:6:14', 'fActWaterLevelMixTank1', '282.352813720703']
['2021-5-4 11:6:14', 'fActWaterLevelMixTank2', '300.117004394531']
['2021-5-4 11:6:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:6:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:6:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:6:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:6:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:6:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:6:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:6:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:6:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:6:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:6:14', 'DoVa_Co2', '0']
['2021-5-4 11:6:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:6:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:6:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:6:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:6:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:7:14', 'fKWhCounter', '3382.24877929688']
['2021-5-4 11:7:14', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 11:7:14', 'fActEcLevelMixTank1', '2017.2734375']
['2021-5-4 11:7:14', 'fActPhLevelMixTank2', '3.83184289932251']
['2021-5-4 11:7:14', 'fActEcLevelMixTank2', '1028.93151855469']
['2021-5-4 11:7:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:7:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:7:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 11:7:14', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 11:7:14', 'fActCo2ValMemo', '771']
['2021-5-4 11:7:14', 'fActWaterLevelMixTank1', '282.9775390625']
['2021-5-4 11:7:14', 'fActWaterLevelMixTank2', '299.736724853516']
['2021-5-4 11:7:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:7:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:7:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:7:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:7:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:7:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:7:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:7:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:7:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:7:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:7:14', 'DoVa_Co2', '0']
['2021-5-4 11:7:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:7:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:7:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:7:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:7:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:8:14', 'fKWhCounter', '3382.44897460938']
['2021-5-4 11:8:14', 'fActPhLevelMixTank1', '5.60606718063354']
['2021-5-4 11:8:14', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 11:8:14', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 11:8:14', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 11:8:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:8:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:8:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 11:8:14', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 11:8:14', 'fActCo2ValMemo', '767']
['2021-5-4 11:8:14', 'fActWaterLevelMixTank1', '282.298492431641']
['2021-5-4 11:8:14', 'fActWaterLevelMixTank2', '299.763885498047']
['2021-5-4 11:8:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:8:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:8:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:8:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:8:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:8:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:8:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:8:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:8:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:8:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:8:14', 'DoVa_Co2', '0']
['2021-5-4 11:8:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:8:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:8:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:8:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:8:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:9:14', 'fKWhCounter', '3382.54907226563']
['2021-5-4 11:9:14', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 11:9:14', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 11:9:14', 'fActPhLevelMixTank2', '3.83867907524109']
['2021-5-4 11:9:14', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 11:9:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:9:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:9:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 11:9:14', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 11:9:14', 'fActCo2ValMemo', '768']
['2021-5-4 11:9:14', 'fActWaterLevelMixTank1', '283.031860351563']
['2021-5-4 11:9:14', 'fActWaterLevelMixTank2', '300.30712890625']
['2021-5-4 11:9:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:9:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:9:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:9:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:9:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:9:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:9:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:9:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:9:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:9:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:9:14', 'DoVa_Co2', '0']
['2021-5-4 11:9:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:9:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:9:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:9:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:9:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:10:14', 'fKWhCounter', '3382.74926757813']
['2021-5-4 11:10:14', 'fActPhLevelMixTank1', '5.60338163375854']
['2021-5-4 11:10:14', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 11:10:14', 'fActPhLevelMixTank2', '3.84112071990967']
['2021-5-4 11:10:14', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 11:10:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:10:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:10:14', 'fActTempValMemo', '20.2999992370605']
['2021-5-4 11:10:14', 'fActRhValMemo', '52']
['2021-5-4 11:10:14', 'fActCo2ValMemo', '771']
['2021-5-4 11:10:14', 'fActWaterLevelMixTank1', '282.787414550781']
['2021-5-4 11:10:14', 'fActWaterLevelMixTank2', '299.981170654297']
['2021-5-4 11:10:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:10:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:10:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:10:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:10:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:10:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:10:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:10:14', 'DoVa_IrrigateLevel_2_MT1', '0']

['2021-5-4 11:10:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:10:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:10:14', 'DoVa_Co2', '0']
['2021-5-4 11:10:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:10:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:10:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:10:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:10:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:11:14', 'fKWhCounter', '3382.84936523438']
['2021-5-4 11:11:14', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 11:11:14', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 11:11:14', 'fActPhLevelMixTank2', '3.83721423149109']
['2021-5-4 11:11:14', 'fActEcLevelMixTank2', '1023.13305664063']
['2021-5-4 11:11:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:11:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:11:14', 'fActTempValMemo', '20.3999996185303']
['2021-5-4 11:11:14', 'fActRhValMemo', '52']
['2021-5-4 11:11:14', 'fActCo2ValMemo', '767']
['2021-5-4 11:11:14', 'fActWaterLevelMixTank1', '281.836730957031']
['2021-5-4 11:11:14', 'fActWaterLevelMixTank2', '300.796051025391']
['2021-5-4 11:11:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:11:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:11:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:11:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:11:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:11:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:11:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:11:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:11:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:11:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:11:14', 'DoVa_Co2', '0']
['2021-5-4 11:11:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:11:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:11:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:11:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:11:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:12:14', 'fKWhCounter', '3382.94946289063']
['2021-5-4 11:12:14', 'fActPhLevelMixTank1', '5.60924100875854']
['2021-5-4 11:12:14', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 11:12:14', 'fActPhLevelMixTank2', '3.83819079399109']
['2021-5-4 11:12:14', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 11:12:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:12:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:12:14', 'fActTempValMemo', '20.3999996185303']
['2021-5-4 11:12:14', 'fActRhValMemo', '58.7000007629395']
['2021-5-4 11:12:14', 'fActCo2ValMemo', '769']
['2021-5-4 11:12:14', 'fActWaterLevelMixTank1', '283.439300537109']
['2021-5-4 11:12:14', 'fActWaterLevelMixTank2', '301.203491210938']
['2021-5-4 11:12:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:12:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:12:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:12:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:12:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:12:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:12:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:12:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:12:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:12:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:12:14', 'DoVa_Co2', '0']
['2021-5-4 11:12:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:12:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:12:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:12:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:12:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:13:14', 'fKWhCounter', '3383.04956054688']
['2021-5-4 11:13:14', 'fActPhLevelMixTank1', '5.60777616500854']
['2021-5-4 11:13:14', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 11:13:14', 'fActPhLevelMixTank2', '3.84209728240967']
['2021-5-4 11:13:14', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 11:13:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:13:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:13:14', 'fActTempValMemo', '20.7000007629395']
['2021-5-4 11:13:14', 'fActRhValMemo', '68.1999969482422']
['2021-5-4 11:13:14', 'fActCo2ValMemo', '771']
['2021-5-4 11:13:14', 'fActWaterLevelMixTank1', '283.7109375']
['2021-5-4 11:13:14', 'fActWaterLevelMixTank2', '301.529449462891']
['2021-5-4 11:13:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:13:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:13:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:13:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:13:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:13:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:13:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:13:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:13:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:13:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:13:14', 'DoVa_Co2', '0']
['2021-5-4 11:13:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:13:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:13:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:13:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:13:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:14:14', 'fKWhCounter', '3383.14965820313']
['2021-5-4 11:14:14', 'fActPhLevelMixTank1', '5.60582304000854']
['2021-5-4 11:14:14', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 11:14:14', 'fActPhLevelMixTank2', '3.84307384490967']
['2021-5-4 11:14:14', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 11:14:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:14:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:14:14', 'fActTempValMemo', '21']
['2021-5-4 11:14:14', 'fActRhValMemo', '71.5999984741211']
['2021-5-4 11:14:14', 'fActCo2ValMemo', '773']
['2021-5-4 11:14:14', 'fActWaterLevelMixTank1', '283.92822265625']
['2021-5-4 11:14:14', 'fActWaterLevelMixTank2', '301.203491210938']
['2021-5-4 11:14:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:14:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:14:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:14:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:14:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:14:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:14:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:14:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:14:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:14:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:14:14', 'DoVa_Co2', '0']
['2021-5-4 11:14:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:14:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:14:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:14:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:14:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:15:14', 'fKWhCounter', '3383.34985351563']
['2021-5-4 11:15:14', 'fActPhLevelMixTank1', '5.61485624313354']
['2021-5-4 11:15:14', 'fActEcLevelMixTank1', '2017.12084960938']
['2021-5-4 11:15:14', 'fActPhLevelMixTank2', '3.83843493461609']
['2021-5-4 11:15:14', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 11:15:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:15:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:15:14', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:15:14', 'fActRhValMemo', '74.1999969482422']
['2021-5-4 11:15:14', 'fActCo2ValMemo', '776']
['2021-5-4 11:15:14', 'fActWaterLevelMixTank1', '282.814575195313']
['2021-5-4 11:15:14', 'fActWaterLevelMixTank2', '301.556610107422']
['2021-5-4 11:15:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:15:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:15:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:15:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:15:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:15:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:15:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:15:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:15:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:15:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:15:14', 'DoVa_Co2', '0']
['2021-5-4 11:15:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:15:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:15:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:15:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_2_White', '0']

['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:15:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:16:14', 'fKWhCounter', '3383.44995117188']
['2021-5-4 11:16:14', 'fActPhLevelMixTank1', '5.61656522750854']
['2021-5-4 11:16:14', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 11:16:14', 'fActPhLevelMixTank2', '3.83843493461609']
['2021-5-4 11:16:14', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 11:16:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:16:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:16:14', 'fActTempValMemo', '21.5']
['2021-5-4 11:16:14', 'fActRhValMemo', '75.4000015258789']
['2021-5-4 11:16:14', 'fActCo2ValMemo', '778']
['2021-5-4 11:16:14', 'fActWaterLevelMixTank1', '284.118347167969']
['2021-5-4 11:16:14', 'fActWaterLevelMixTank2', '301.122009277344']
['2021-5-4 11:16:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:16:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:16:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:16:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:16:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:16:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:16:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:16:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:16:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:16:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:16:14', 'DoVa_Co2', '0']
['2021-5-4 11:16:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:16:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:16:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:16:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:16:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:17:14', 'fKWhCounter', '3383.55004882813']
['2021-5-4 11:17:14', 'fActPhLevelMixTank1', '5.6192512512207']
['2021-5-4 11:17:14', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 11:17:14', 'fActPhLevelMixTank2', '3.84282970428467']
['2021-5-4 11:17:14', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 11:17:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:17:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:17:14', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 11:17:14', 'fActRhValMemo', '74.3000030517578']
['2021-5-4 11:17:14', 'fActCo2ValMemo', '776']
['2021-5-4 11:17:14', 'fActWaterLevelMixTank1', '283.738098144531']
['2021-5-4 11:17:14', 'fActWaterLevelMixTank2', '301.149169921875']
['2021-5-4 11:17:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:17:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:17:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:17:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:17:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:17:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:17:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:17:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:17:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:17:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:17:14', 'DoVa_Co2', '0']
['2021-5-4 11:17:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:17:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:17:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:17:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:17:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:18:14', 'fKWhCounter', '3383.75024414063']
['2021-5-4 11:18:14', 'fActPhLevelMixTank1', '5.6185188293457']
['2021-5-4 11:18:14', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 11:18:14', 'fActPhLevelMixTank2', '3.84698009490967']
['2021-5-4 11:18:14', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 11:18:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:18:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:18:14', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 11:18:14', 'fActRhValMemo', '68.3000030517578']
['2021-5-4 11:18:14', 'fActCo2ValMemo', '774']
['2021-5-4 11:18:14', 'fActWaterLevelMixTank1', '284.254180908203']
['2021-5-4 11:18:14', 'fActWaterLevelMixTank2', '301.013366699219']
['2021-5-4 11:18:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:18:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:18:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:18:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:18:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:18:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:18:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:18:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:18:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:18:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:18:14', 'DoVa_Co2', '0']
['2021-5-4 11:18:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:18:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:18:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:18:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:18:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:19:14', 'fKWhCounter', '3383.85034179688']
['2021-5-4 11:19:14', 'fActPhLevelMixTank1', '5.6204719543457']
['2021-5-4 11:19:14', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 11:19:14', 'fActPhLevelMixTank2', '3.84820103645325']
['2021-5-4 11:19:14', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 11:19:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:19:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:19:14', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 11:19:14', 'fActRhValMemo', '63']
['2021-5-4 11:19:14', 'fActCo2ValMemo', '774']
['2021-5-4 11:19:14', 'fActWaterLevelMixTank1', '284.254180908203']
['2021-5-4 11:19:14', 'fActWaterLevelMixTank2', '301.149169921875']
['2021-5-4 11:19:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:19:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:19:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:19:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:19:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:19:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:19:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:19:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:19:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:19:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:19:14', 'DoVa_Co2', '0']
['2021-5-4 11:19:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:19:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:19:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:19:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:19:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:20:14', 'fKWhCounter', '3384.05053710938']
['2021-5-4 11:20:14', 'fActPhLevelMixTank1', '5.6302375793457']
['2021-5-4 11:20:14', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 11:20:14', 'fActPhLevelMixTank2', '3.85235142707825']
['2021-5-4 11:20:14', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 11:20:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:20:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:20:14', 'fActTempValMemo', '22']
['2021-5-4 11:20:14', 'fActRhValMemo', '60']
['2021-5-4 11:20:14', 'fActCo2ValMemo', '773']
['2021-5-4 11:20:14', 'fActWaterLevelMixTank1', '284.580108642578']
['2021-5-4 11:20:14', 'fActWaterLevelMixTank2', '301.339294433594']
['2021-5-4 11:20:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:20:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:20:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:20:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:20:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:20:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:20:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:20:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:20:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:20:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:20:14', 'DoVa_Co2', '0']
['2021-5-4 11:20:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:20:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:20:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:20:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:20:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:21:14', 'fKWhCounter', '3384.15063476563']

['2021-5-4 11:21:14', 'fActPhLevelMixTank1', '5.63365602493286']
['2021-5-4 11:21:14', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 11:21:14', 'fActPhLevelMixTank2', '3.85186314582825']
['2021-5-4 11:21:14', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 11:21:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:21:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:21:14', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 11:21:14', 'fActRhValMemo', '55.7999992370605']
['2021-5-4 11:21:14', 'fActCo2ValMemo', '773']
['2021-5-4 11:21:14', 'fActWaterLevelMixTank1', '284.036865234375']
['2021-5-4 11:21:14', 'fActWaterLevelMixTank2', '300.388610839844']
['2021-5-4 11:21:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:21:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:21:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:21:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:21:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:21:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:21:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:21:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:21:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:21:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:21:14', 'DoVa_Co2', '0']
['2021-5-4 11:21:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:21:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:21:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:21:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:21:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:22:14', 'fKWhCounter', '3384.35083007813']
['2021-5-4 11:22:14', 'fActPhLevelMixTank1', '5.63463258743286']
['2021-5-4 11:22:14', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 11:22:14', 'fActPhLevelMixTank2', '3.85283970832825']
['2021-5-4 11:22:14', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 11:22:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:22:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:22:14', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 11:22:14', 'fActRhValMemo', '52.5']
['2021-5-4 11:22:14', 'fActCo2ValMemo', '770']
['2021-5-4 11:22:14', 'fActWaterLevelMixTank1', '284.335662841797']
['2021-5-4 11:22:14', 'fActWaterLevelMixTank2', '301.013366699219']
['2021-5-4 11:22:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:22:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:22:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:22:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:22:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:22:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:22:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:22:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:22:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:22:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:22:14', 'DoVa_Co2', '0']
['2021-5-4 11:22:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:22:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:22:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:22:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:22:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:23:14', 'fKWhCounter', '3384.55102539063']
['2021-5-4 11:23:14', 'fActPhLevelMixTank1', '5.63560914993286']
['2021-5-4 11:23:14', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 11:23:14', 'fActPhLevelMixTank2', '3.85332798957825']
['2021-5-4 11:23:14', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 11:23:14', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:23:14', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:23:14', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 11:23:14', 'fActRhValMemo', '53']
['2021-5-4 11:23:14', 'fActCo2ValMemo', '767']
['2021-5-4 11:23:14', 'fActWaterLevelMixTank1', '284.66162109375']
['2021-5-4 11:23:14', 'fActWaterLevelMixTank2', '300.850372314453']
['2021-5-4 11:23:14', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:23:14', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:23:14', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:23:14', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:23:14', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:23:14', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:23:14', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:23:14', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:23:14', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:23:14', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:23:14', 'DoVa_Co2', '0']
['2021-5-4 11:23:14', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:23:14', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:23:14', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:23:14', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:23:14', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:24:15', 'fKWhCounter', '3384.65112304688']
['2021-5-4 11:24:15', 'fActPhLevelMixTank1', '5.63780641555786']
['2021-5-4 11:24:15', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 11:24:15', 'fActPhLevelMixTank2', '3.85235142707825']
['2021-5-4 11:24:15', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 11:24:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:24:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:24:15', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 11:24:15', 'fActRhValMemo', '54.2999992370605']
['2021-5-4 11:24:15', 'fActCo2ValMemo', '769']
['2021-5-4 11:24:15', 'fActWaterLevelMixTank1', '284.227020263672']
['2021-5-4 11:24:15', 'fActWaterLevelMixTank2', '301.04052734375']
['2021-5-4 11:24:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:24:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:24:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:24:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:24:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:24:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:24:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:24:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:24:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:24:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:24:15', 'DoVa_Co2', '0']
['2021-5-4 11:24:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:24:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:24:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:24:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:24:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:25:15', 'fKWhCounter', '3384.85131835938']
['2021-5-4 11:25:15', 'fActPhLevelMixTank1', '5.63682985305786']
['2021-5-4 11:25:15', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 11:25:15', 'fActPhLevelMixTank2', '3.84698009490967']
['2021-5-4 11:25:15', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 11:25:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:25:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:25:15', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 11:25:15', 'fActRhValMemo', '54.5999984741211']
['2021-5-4 11:25:15', 'fActCo2ValMemo', '765']
['2021-5-4 11:25:15', 'fActWaterLevelMixTank1', '285.204864501953']
['2021-5-4 11:25:15', 'fActWaterLevelMixTank2', '301.366455078125']
['2021-5-4 11:25:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:25:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:25:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:25:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:25:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:25:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:25:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:25:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:25:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:25:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:25:15', 'DoVa_Co2', '0']
['2021-5-4 11:25:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:25:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:25:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:25:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']

['2021-5-4 11:25:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:25:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:26:15', 'fKWhCounter', '3384.95141601563']
['2021-5-4 11:26:15', 'fActPhLevelMixTank1', '5.63805055618286']
['2021-5-4 11:26:15', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 11:26:15', 'fActPhLevelMixTank2', '3.84795689582825']
['2021-5-4 11:26:15', 'fActEcLevelMixTank2', '1025.72705078125']
['2021-5-4 11:26:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:26:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:26:15', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 11:26:15', 'fActRhValMemo', '54.7999992370605']
['2021-5-4 11:26:15', 'fActCo2ValMemo', '764']
['2021-5-4 11:26:15', 'fActWaterLevelMixTank1', '284.797424316406']
['2021-5-4 11:26:15', 'fActWaterLevelMixTank2', '300.687408447266']
['2021-5-4 11:26:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:26:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:26:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:26:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:26:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:26:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:26:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:26:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:26:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:26:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:26:15', 'DoVa_Co2', '0']
['2021-5-4 11:26:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:26:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:26:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:26:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:26:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:27:15', 'fKWhCounter', '3385.15161132813']
['2021-5-4 11:27:15', 'fActPhLevelMixTank1', '5.63975954055786']
['2021-5-4 11:27:15', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 11:27:15', 'fActPhLevelMixTank2', '3.85088658332825']
['2021-5-4 11:27:15', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 11:27:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:27:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:27:15', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 11:27:15', 'fActRhValMemo', '54.5999984741211']
['2021-5-4 11:27:15', 'fActCo2ValMemo', '762']
['2021-5-4 11:27:15', 'fActWaterLevelMixTank1', '285.340667724609']
['2021-5-4 11:27:15', 'fActWaterLevelMixTank2', '301.638092041016']
['2021-5-4 11:27:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:27:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:27:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:27:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:27:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:27:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:27:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:27:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:27:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:27:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:27:15', 'DoVa_Co2', '0']
['2021-5-4 11:27:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:27:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:27:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:27:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:27:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:28:15', 'fKWhCounter', '3385.35180664063']
['2021-5-4 11:28:15', 'fActPhLevelMixTank1', '5.64708375930786']
['2021-5-4 11:28:15', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 11:28:15', 'fActPhLevelMixTank2', '3.85259556770325']
['2021-5-4 11:28:15', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 11:28:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:28:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:28:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 11:28:15', 'fActRhValMemo', '54.4000015258789']
['2021-5-4 11:28:15', 'fActCo2ValMemo', '761']
['2021-5-4 11:28:15', 'fActWaterLevelMixTank1', '284.444305419922']
['2021-5-4 11:28:15', 'fActWaterLevelMixTank2', '301.366455078125']
['2021-5-4 11:28:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:28:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:28:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:28:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:28:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:28:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:28:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:28:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:28:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:28:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:28:15', 'DoVa_Co2', '0']
['2021-5-4 11:28:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:28:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:28:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:28:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:28:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:29:15', 'fKWhCounter', '3385.45190429688']
['2021-5-4 11:29:15', 'fActPhLevelMixTank1', '5.63878297805786']
['2021-5-4 11:29:15', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 11:29:15', 'fActPhLevelMixTank2', '3.85723447799683']
['2021-5-4 11:29:15', 'fActEcLevelMixTank2', '1039.00268554688']
['2021-5-4 11:29:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:29:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:29:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 11:29:15', 'fActRhValMemo', '54']
['2021-5-4 11:29:15', 'fActCo2ValMemo', '761']
['2021-5-4 11:29:15', 'fActWaterLevelMixTank1', '285.177703857422']
['2021-5-4 11:29:15', 'fActWaterLevelMixTank2', '301.529449462891']
['2021-5-4 11:29:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:29:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:29:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:29:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:29:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:29:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:29:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:29:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:29:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:29:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:29:15', 'DoVa_Co2', '0']
['2021-5-4 11:29:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:29:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:29:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:29:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:29:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:30:15', 'fKWhCounter', '3385.65209960938']
['2021-5-4 11:30:15', 'fActPhLevelMixTank1', '5.64342164993286']
['2021-5-4 11:30:15', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 11:30:15', 'fActPhLevelMixTank2', '3.85772275924683']
['2021-5-4 11:30:15', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 11:30:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:30:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:30:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 11:30:15', 'fActRhValMemo', '53.7000007629395']
['2021-5-4 11:30:15', 'fActCo2ValMemo', '757']
['2021-5-4 11:30:15', 'fActWaterLevelMixTank1', '285.856750488281']
['2021-5-4 11:30:15', 'fActWaterLevelMixTank2', '301.964050292969']
['2021-5-4 11:30:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:30:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:30:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:30:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:30:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:30:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:30:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:30:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:30:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:30:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:30:15', 'DoVa_Co2', '0']
['2021-5-4 11:30:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:30:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:30:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:30:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']

['2021-5-4 11:30:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:30:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:31:15', 'fKWhCounter', '3385.75219726563']
['2021-5-4 11:31:15', 'fActPhLevelMixTank1', '5.64830446243286']
['2021-5-4 11:31:15', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 11:31:15', 'fActPhLevelMixTank2', '3.86016416549683']
['2021-5-4 11:31:15', 'fActEcLevelMixTank2', '1039.1552734375']
['2021-5-4 11:31:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:31:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:31:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 11:31:15', 'fActRhValMemo', '53.4000015258789']
['2021-5-4 11:31:15', 'fActCo2ValMemo', '758']
['2021-5-4 11:31:15', 'fActWaterLevelMixTank1', '285.09619140625']
['2021-5-4 11:31:15', 'fActWaterLevelMixTank2', '302.072692871094']
['2021-5-4 11:31:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:31:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:31:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:31:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:31:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:31:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:31:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:31:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:31:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:31:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:31:15', 'DoVa_Co2', '0']
['2021-5-4 11:31:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:31:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:31:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:31:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:31:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:32:15', 'fKWhCounter', '3385.95239257813']
['2021-5-4 11:32:15', 'fActPhLevelMixTank1', '5.64635133743286']
['2021-5-4 11:32:15', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 11:32:15', 'fActPhLevelMixTank2', '3.85747861862183']
['2021-5-4 11:32:15', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 11:32:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:32:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:32:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 11:32:15', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 11:32:15', 'fActCo2ValMemo', '760']
['2021-5-4 11:32:15', 'fActWaterLevelMixTank1', '285.585144042969']
['2021-5-4 11:32:15', 'fActWaterLevelMixTank2', '301.773895263672']
['2021-5-4 11:32:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:32:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:32:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:32:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:32:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:32:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:32:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:32:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:32:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:32:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:32:15', 'DoVa_Co2', '0']
['2021-5-4 11:32:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:32:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:32:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:32:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:32:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:33:15', 'fKWhCounter', '3386.15258789063']
['2021-5-4 11:33:15', 'fActPhLevelMixTank1', '5.64659547805786']
['2021-5-4 11:33:15', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 11:33:15', 'fActPhLevelMixTank2', '3.85918760299683']
['2021-5-4 11:33:15', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 11:33:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:33:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:33:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 11:33:15', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 11:33:15', 'fActCo2ValMemo', '760']
['2021-5-4 11:33:15', 'fActWaterLevelMixTank1', '284.906066894531']
['2021-5-4 11:33:15', 'fActWaterLevelMixTank2', '301.964050292969']
['2021-5-4 11:33:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:33:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:33:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:33:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:33:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:33:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:33:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:33:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:33:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:33:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:33:15', 'DoVa_Co2', '0']
['2021-5-4 11:33:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:33:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:33:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:33:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:33:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:34:15', 'fKWhCounter', '3386.25268554688']
['2021-5-4 11:34:15', 'fActPhLevelMixTank1', '5.65147876739502']
['2021-5-4 11:34:15', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 11:34:15', 'fActPhLevelMixTank2', '3.86309385299683']
['2021-5-4 11:34:15', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 11:34:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:34:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:34:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 11:34:15', 'fActRhValMemo', '52.5']
['2021-5-4 11:34:15', 'fActCo2ValMemo', '760']
['2021-5-4 11:34:15', 'fActWaterLevelMixTank1', '284.498626708984']
['2021-5-4 11:34:15', 'fActWaterLevelMixTank2', '301.475128173828']
['2021-5-4 11:34:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:34:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:34:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:34:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:34:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:34:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:34:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:34:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:34:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:34:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:34:15', 'DoVa_Co2', '0']
['2021-5-4 11:34:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:34:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:34:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:34:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:34:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:35:15', 'fKWhCounter', '3386.45288085938']
['2021-5-4 11:35:15', 'fActPhLevelMixTank1', '5.65782642364502']
['2021-5-4 11:35:15', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 11:35:15', 'fActPhLevelMixTank2', '3.85943174362183']
['2021-5-4 11:35:15', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 11:35:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:35:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:35:15', 'fActTempValMemo', '21.5']
['2021-5-4 11:35:15', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 11:35:15', 'fActCo2ValMemo', '759']
['2021-5-4 11:35:15', 'fActWaterLevelMixTank1', '284.987548828125']
['2021-5-4 11:35:15', 'fActWaterLevelMixTank2', '301.746734619141']
['2021-5-4 11:35:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:35:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:35:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:35:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:35:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:35:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:35:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:35:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:35:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:35:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:35:15', 'DoVa_Co2', '0']
['2021-5-4 11:35:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:35:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:35:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:35:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']

['2021-5-4 11:35:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:35:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:36:15', 'fKWhCounter', '3386.55297851563']
['2021-5-4 11:36:15', 'fActPhLevelMixTank1', '5.65245532989502']
['2021-5-4 11:36:15', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 11:36:15', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 11:36:15', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 11:36:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:36:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:36:15', 'fActTempValMemo', '21.5']
['2021-5-4 11:36:15', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 11:36:15', 'fActCo2ValMemo', '760']
['2021-5-4 11:36:15', 'fActWaterLevelMixTank1', '284.87890625']
['2021-5-4 11:36:15', 'fActWaterLevelMixTank2', '301.583770751953']
['2021-5-4 11:36:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:36:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:36:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:36:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:36:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:36:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:36:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:36:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:36:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:36:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:36:15', 'DoVa_Co2', '0']
['2021-5-4 11:36:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:36:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:36:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:36:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:36:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:37:15', 'fKWhCounter', '3386.75317382813']
['2021-5-4 11:37:15', 'fActPhLevelMixTank1', '5.66075611114502']
['2021-5-4 11:37:15', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 11:37:15', 'fActPhLevelMixTank2', '3.85357213020325']
['2021-5-4 11:37:15', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 11:37:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:37:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:37:15', 'fActTempValMemo', '21.5']
['2021-5-4 11:37:15', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 11:37:15', 'fActCo2ValMemo', '758']
['2021-5-4 11:37:15', 'fActWaterLevelMixTank1', '285.204864501953']
['2021-5-4 11:37:15', 'fActWaterLevelMixTank2', '301.9912109375']
['2021-5-4 11:37:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:37:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:37:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:37:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:37:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:37:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:37:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:37:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:37:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:37:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:37:15', 'DoVa_Co2', '0']
['2021-5-4 11:37:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:37:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:37:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:37:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:37:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:38:15', 'fKWhCounter', '3386.95336914063']
['2021-5-4 11:38:15', 'fActPhLevelMixTank1', '5.65904712677002']
['2021-5-4 11:38:15', 'fActEcLevelMixTank1', '2033.90600585938']
['2021-5-4 11:38:15', 'fActPhLevelMixTank2', '3.85381627082825']
['2021-5-4 11:38:15', 'fActEcLevelMixTank2', '1039.00268554688']
['2021-5-4 11:38:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:38:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:38:15', 'fActTempValMemo', '21.5']
['2021-5-4 11:38:15', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 11:38:15', 'fActCo2ValMemo', '759']
['2021-5-4 11:38:15', 'fActWaterLevelMixTank1', '285.585144042969']
['2021-5-4 11:38:15', 'fActWaterLevelMixTank2', '302.20849609375']
['2021-5-4 11:38:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:38:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:38:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:38:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:38:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:38:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:38:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:38:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:38:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:38:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:38:15', 'DoVa_Co2', '0']
['2021-5-4 11:38:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:38:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:38:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:38:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:38:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:39:15', 'fKWhCounter', '3387.05346679688']
['2021-5-4 11:39:15', 'fActPhLevelMixTank1', '5.66148853302002']
['2021-5-4 11:39:15', 'fActEcLevelMixTank1', '2032.53271484375']
['2021-5-4 11:39:15', 'fActPhLevelMixTank2', '3.85381627082825']
['2021-5-4 11:39:15', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 11:39:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:39:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:39:15', 'fActTempValMemo', '21.5']
['2021-5-4 11:39:15', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 11:39:15', 'fActCo2ValMemo', '757']
['2021-5-4 11:39:15', 'fActWaterLevelMixTank1', '286.345672607422']
['2021-5-4 11:39:15', 'fActWaterLevelMixTank2', '302.072692871094']
['2021-5-4 11:39:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:39:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:39:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:39:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:39:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:39:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:39:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:39:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:39:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:39:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:39:15', 'DoVa_Co2', '0']
['2021-5-4 11:39:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:39:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:39:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:39:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:39:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:40:15', 'fKWhCounter', '3387.25366210938']
['2021-5-4 11:40:15', 'fActPhLevelMixTank1', '5.66539525985718']
['2021-5-4 11:40:15', 'fActEcLevelMixTank1', '2030.396484375']
['2021-5-4 11:40:15', 'fActPhLevelMixTank2', '3.85161900520325']
['2021-5-4 11:40:15', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 11:40:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:40:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:40:15', 'fActTempValMemo', '21.5']
['2021-5-4 11:40:15', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 11:40:15', 'fActCo2ValMemo', '756']
['2021-5-4 11:40:15', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 11:40:15', 'fActWaterLevelMixTank2', '301.855377197266']
['2021-5-4 11:40:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:40:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:40:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:40:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:40:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:40:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:40:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:40:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:40:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:40:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:40:15', 'DoVa_Co2', '0']
['2021-5-4 11:40:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:40:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:40:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:40:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:40:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:41:15', 'fKWhCounter', '3387.35375976563']
['2021-5-4 11:41:15', 'fActPhLevelMixTank1', '5.67638158798218']
['2021-5-4 11:41:15', 'fActEcLevelMixTank1', '2032.53271484375']
['2021-5-4 11:41:15', 'fActPhLevelMixTank2', '3.84966588020325']
['2021-5-4 11:41:15', 'fActEcLevelMixTank2', '1040.07080078125']
['2021-5-4 11:41:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:41:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:41:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 11:41:15', 'fActRhValMemo', '51.2999992370605']

['2021-5-4 11:41:15', 'fActCo2ValMemo', '756']
['2021-5-4 11:41:15', 'fActWaterLevelMixTank1', '284.797424316406']
['2021-5-4 11:41:15', 'fActWaterLevelMixTank2', '301.583770751953']
['2021-5-4 11:41:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:41:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:41:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:41:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:41:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:41:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:41:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:41:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:41:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:41:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:41:15', 'DoVa_Co2', '0']
['2021-5-4 11:41:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:41:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:41:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:41:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:41:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:42:15', 'fKWhCounter', '3387.55395507813']
['2021-5-4 11:42:15', 'fActPhLevelMixTank1', '5.67345190048218']
['2021-5-4 11:42:15', 'fActEcLevelMixTank1', '2030.396484375']
['2021-5-4 11:42:15', 'fActPhLevelMixTank2', '3.85454869270325']
['2021-5-4 11:42:15', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 11:42:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:42:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:42:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 11:42:15', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 11:42:15', 'fActCo2ValMemo', '755']
['2021-5-4 11:42:15', 'fActWaterLevelMixTank1', '286.345672607422']
['2021-5-4 11:42:15', 'fActWaterLevelMixTank2', '302.371459960938']
['2021-5-4 11:42:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:42:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:42:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:42:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:42:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:42:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:42:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:42:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:42:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:42:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:42:15', 'DoVa_Co2', '0']
['2021-5-4 11:42:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:42:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:42:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:42:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:42:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:43:15', 'fKWhCounter', '3387.75415039063']
['2021-5-4 11:43:15', 'fActPhLevelMixTank1', '5.68175315856934']
['2021-5-4 11:43:15', 'fActEcLevelMixTank1', '2029.78601074219']
['2021-5-4 11:43:15', 'fActPhLevelMixTank2', '3.85674619674683']
['2021-5-4 11:43:15', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 11:43:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:43:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:43:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 11:43:15', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 11:43:15', 'fActCo2ValMemo', '753']
['2021-5-4 11:43:15', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 11:43:15', 'fActWaterLevelMixTank2', '301.9912109375']
['2021-5-4 11:43:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:43:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:43:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:43:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:43:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:43:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:43:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:43:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:43:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:43:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:43:15', 'DoVa_Co2', '0']
['2021-5-4 11:43:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:43:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:43:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:43:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:43:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:44:15', 'fKWhCounter', '3387.85424804688']
['2021-5-4 11:44:15', 'fActPhLevelMixTank1', '5.68272972106934']
['2021-5-4 11:44:15', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 11:44:15', 'fActPhLevelMixTank2', '3.85772275924683']
['2021-5-4 11:44:15', 'fActEcLevelMixTank2', '1040.3759765625']
['2021-5-4 11:44:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:44:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:44:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 11:44:15', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 11:44:15', 'fActCo2ValMemo', '753']
['2021-5-4 11:44:15', 'fActWaterLevelMixTank1', '286.970397949219']
['2021-5-4 11:44:15', 'fActWaterLevelMixTank2', '302.371459960938']
['2021-5-4 11:44:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:44:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:44:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:44:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:44:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:44:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:44:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:44:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:44:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:44:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:44:15', 'DoVa_Co2', '0']
['2021-5-4 11:44:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:44:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:44:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:44:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:44:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:45:15', 'fKWhCounter', '3388.05444335938']
['2021-5-4 11:45:15', 'fActPhLevelMixTank1', '5.67809057235718']
['2021-5-4 11:45:15', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 11:45:15', 'fActPhLevelMixTank2', '3.85381627082825']
['2021-5-4 11:45:15', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 11:45:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:45:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:45:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 11:45:15', 'fActRhValMemo', '50.5']
['2021-5-4 11:45:15', 'fActCo2ValMemo', '752']
['2021-5-4 11:45:15', 'fActWaterLevelMixTank1', '286.943237304688']
['2021-5-4 11:45:15', 'fActWaterLevelMixTank2', '302.615936279297']
['2021-5-4 11:45:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:45:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:45:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:45:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:45:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:45:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:45:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:45:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:45:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:45:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:45:15', 'DoVa_Co2', '0']
['2021-5-4 11:45:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:45:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:45:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:45:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:45:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:46:15', 'fKWhCounter', '3388.15454101563']
['2021-5-4 11:46:15', 'fActPhLevelMixTank1', '5.69054222106934']
['2021-5-4 11:46:15', 'fActEcLevelMixTank1', '2029.48083496094']
['2021-5-4 11:46:15', 'fActPhLevelMixTank2', '3.84722423553467']
['2021-5-4 11:46:15', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 11:46:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:46:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:46:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 11:46:15', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 11:46:15', 'fActCo2ValMemo', '755']
['2021-5-4 11:46:15', 'fActWaterLevelMixTank1', '286.99755859375']
['2021-5-4 11:46:15', 'fActWaterLevelMixTank2', '302.072692871094']
['2021-5-4 11:46:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:46:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:46:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:46:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:46:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:46:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:46:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:46:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:46:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:46:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:46:15', 'DoVa_Co2', '0']
['2021-5-4 11:46:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:46:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:46:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:46:15', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:46:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:47:15', 'fKWhCounter', '3388.35473632813']
['2021-5-4 11:47:15', 'fActPhLevelMixTank1', '5.68419456481934']
['2021-5-4 11:47:15', 'fActEcLevelMixTank1', '2031.46459960938']
['2021-5-4 11:47:15', 'fActPhLevelMixTank2', '3.85064244270325']
['2021-5-4 11:47:15', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 11:47:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:47:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:47:15', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 11:47:15', 'fActRhValMemo', '50.5']
['2021-5-4 11:47:15', 'fActCo2ValMemo', '751']
['2021-5-4 11:47:15', 'fActWaterLevelMixTank1', '286.019714355469']
['2021-5-4 11:47:15', 'fActWaterLevelMixTank2', '302.099853515625']
['2021-5-4 11:47:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:47:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:47:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:47:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:47:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:47:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:47:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:47:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:47:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:47:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:47:15', 'DoVa_Co2', '0']
['2021-5-4 11:47:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:47:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:47:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:47:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:47:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:48:15', 'fKWhCounter', '3388.55493164063']
['2021-5-4 11:48:15', 'fActPhLevelMixTank1', '5.68004417419434']
['2021-5-4 11:48:15', 'fActEcLevelMixTank1', '2032.53271484375']
['2021-5-4 11:48:15', 'fActPhLevelMixTank2', '3.85454869270325']
['2021-5-4 11:48:15', 'fActEcLevelMixTank2', '1038.69750976563']
['2021-5-4 11:48:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:48:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:48:15', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 11:48:15', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 11:48:15', 'fActCo2ValMemo', '749']
['2021-5-4 11:48:15', 'fActWaterLevelMixTank1', '287.214874267578']
['2021-5-4 11:48:15', 'fActWaterLevelMixTank2', '302.914733886719']
['2021-5-4 11:48:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:48:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:48:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:48:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:48:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:48:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:48:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:48:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:48:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:48:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:48:15', 'DoVa_Co2', '0']
['2021-5-4 11:48:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:48:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:48:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:48:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:48:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:49:15', 'fKWhCounter', '3388.65502929688']
['2021-5-4 11:49:15', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 11:49:15', 'fActEcLevelMixTank1', '2055.42163085938']
['2021-5-4 11:49:15', 'fActPhLevelMixTank2', '3.78545498847961']
['2021-5-4 11:49:15', 'fActEcLevelMixTank2', '1046.78491210938']
['2021-5-4 11:49:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:49:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:49:15', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 11:49:15', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 11:49:15', 'fActCo2ValMemo', '751']
['2021-5-4 11:49:15', 'fActWaterLevelMixTank1', '288.301361083984']
['2021-5-4 11:49:15', 'fActWaterLevelMixTank2', '289.985443115234']
['2021-5-4 11:49:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:49:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:49:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:49:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:49:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:49:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:49:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:49:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:49:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:49:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:49:15', 'DoVa_Co2', '0']
['2021-5-4 11:49:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:49:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:49:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:49:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:49:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:50:15', 'fKWhCounter', '3388.85522460938']
['2021-5-4 11:50:15', 'fActPhLevelMixTank1', '5.56480598449707']
['2021-5-4 11:50:15', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 11:50:15', 'fActPhLevelMixTank2', '3.76299333572388']
['2021-5-4 11:50:15', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 11:50:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:50:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:50:15', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 11:50:15', 'fActRhValMemo', '49.9000015258789']
['2021-5-4 11:50:15', 'fActCo2ValMemo', '761']
['2021-5-4 11:50:15', 'fActWaterLevelMixTank1', '279.337799072266']
['2021-5-4 11:50:15', 'fActWaterLevelMixTank2', '306.065551757813']
['2021-5-4 11:50:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:50:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:50:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:50:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:50:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:50:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:50:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:50:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:50:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:50:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:50:15', 'DoVa_Co2', '0']
['2021-5-4 11:50:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:50:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:50:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:50:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:50:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:51:15', 'fKWhCounter', '3389.05541992188']
['2021-5-4 11:51:15', 'fActPhLevelMixTank1', '5.56358528137207']
['2021-5-4 11:51:15', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 11:51:15', 'fActPhLevelMixTank2', '3.76982951164246']
['2021-5-4 11:51:15', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 11:51:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:51:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:51:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:51:15', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 11:51:15', 'fActCo2ValMemo', '776']
['2021-5-4 11:51:15', 'fActWaterLevelMixTank1', '277.789520263672']
['2021-5-4 11:51:15', 'fActWaterLevelMixTank2', '307.803955078125']
['2021-5-4 11:51:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:51:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:51:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:51:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:51:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:51:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:51:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:51:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:51:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:51:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:51:15', 'DoVa_Co2', '0']
['2021-5-4 11:51:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:51:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:51:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:51:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_4_Blue', '0']

['2021-5-4 11:51:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:51:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:52:15', 'fKWhCounter', '3389.25561523438']
['2021-5-4 11:52:15', 'fActPhLevelMixTank1', '5.56944465637207']
['2021-5-4 11:52:15', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 11:52:15', 'fActPhLevelMixTank2', '3.78032779693604']
['2021-5-4 11:52:15', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 11:52:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:52:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:52:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:52:15', 'fActRhValMemo', '50']
['2021-5-4 11:52:15', 'fActCo2ValMemo', '792']
['2021-5-4 11:52:15', 'fActWaterLevelMixTank1', '274.910308837891']
['2021-5-4 11:52:15', 'fActWaterLevelMixTank2', '311.036254882813']
['2021-5-4 11:52:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:52:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:52:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:52:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:52:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:52:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:52:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:52:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:52:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:52:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:52:15', 'DoVa_Co2', '0']
['2021-5-4 11:52:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:52:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:52:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:52:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:52:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:53:15', 'fKWhCounter', '3389.45581054688']
['2021-5-4 11:53:15', 'fActPhLevelMixTank1', '5.56382942199707']
['2021-5-4 11:53:15', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 11:53:15', 'fActPhLevelMixTank2', '3.78252506256104']
['2021-5-4 11:53:15', 'fActEcLevelMixTank2', '1024.96411132813']
['2021-5-4 11:53:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:53:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:53:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:53:15', 'fActRhValMemo', '50.5']
['2021-5-4 11:53:15', 'fActCo2ValMemo', '808']
['2021-5-4 11:53:15', 'fActWaterLevelMixTank1', '274.258422851563']
['2021-5-4 11:53:15', 'fActWaterLevelMixTank2', '285.150543212891']
['2021-5-4 11:53:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:53:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:53:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:53:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:53:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:53:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:53:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:53:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:53:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:53:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:53:15', 'DoVa_Co2', '0']
['2021-5-4 11:53:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:53:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:53:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:53:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:53:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:54:15', 'fKWhCounter', '3389.65600585938']
['2021-5-4 11:54:15', 'fActPhLevelMixTank1', '5.57164239883423']
['2021-5-4 11:54:15', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 11:54:15', 'fActPhLevelMixTank2', '3.79741811752319']
['2021-5-4 11:54:15', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 11:54:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:54:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:54:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:54:15', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 11:54:15', 'fActCo2ValMemo', '821']
['2021-5-4 11:54:15', 'fActWaterLevelMixTank1', '273.171936035156']
['2021-5-4 11:54:15', 'fActWaterLevelMixTank2', '293.65234375']
['2021-5-4 11:54:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:54:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:54:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:54:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:54:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:54:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:54:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:54:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:54:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:54:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:54:15', 'DoVa_Co2', '0']
['2021-5-4 11:54:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:54:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:54:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:54:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:54:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:55:15', 'fKWhCounter', '3389.75610351563']
['2021-5-4 11:55:15', 'fActPhLevelMixTank1', '5.58433771133423']
['2021-5-4 11:55:15', 'fActEcLevelMixTank1', '2046.26611328125']
['2021-5-4 11:55:15', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 11:55:15', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 11:55:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:55:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:55:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:55:15', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 11:55:15', 'fActCo2ValMemo', '835']
['2021-5-4 11:55:15', 'fActWaterLevelMixTank1', '274.068298339844']
['2021-5-4 11:55:15', 'fActWaterLevelMixTank2', '294.222747802734']
['2021-5-4 11:55:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:55:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:55:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:55:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:55:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:55:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:55:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:55:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:55:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:55:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:55:15', 'DoVa_Co2', '0']
['2021-5-4 11:55:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:55:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:55:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:55:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:55:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:56:15', 'fKWhCounter', '3389.95629882813']
['2021-5-4 11:56:15', 'fActPhLevelMixTank1', '5.57945489883423']
['2021-5-4 11:56:15', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 11:56:15', 'fActPhLevelMixTank2', '3.82818078994751']
['2021-5-4 11:56:15', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 11:56:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:56:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:56:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:56:15', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 11:56:15', 'fActCo2ValMemo', '848']
['2021-5-4 11:56:15', 'fActWaterLevelMixTank1', '273.606536865234']
['2021-5-4 11:56:15', 'fActWaterLevelMixTank2', '293.353576660156']
['2021-5-4 11:56:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:56:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:56:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:56:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:56:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:56:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:56:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:56:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:56:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:56:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:56:15', 'DoVa_Co2', '0']
['2021-5-4 11:56:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:56:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:56:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:56:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_4_Blue', '0']

['2021-5-4 11:56:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:56:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:57:15', 'fKWhCounter', '3390.05639648438']
['2021-5-4 11:57:15', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 11:57:15', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 11:57:15', 'fActPhLevelMixTank2', '3.82525110244751']
['2021-5-4 11:57:15', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 11:57:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:57:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:57:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:57:15', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 11:57:15', 'fActCo2ValMemo', '859']
['2021-5-4 11:57:15', 'fActWaterLevelMixTank1', '273.117614746094']
['2021-5-4 11:57:15', 'fActWaterLevelMixTank2', '293.054779052734']
['2021-5-4 11:57:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:57:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:57:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:57:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:57:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:57:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:57:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:57:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:57:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:57:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:57:15', 'DoVa_Co2', '0']
['2021-5-4 11:57:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:57:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:57:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:57:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:57:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:58:15', 'fKWhCounter', '3390.25659179688']
['2021-5-4 11:58:15', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 11:58:15', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 11:58:15', 'fActPhLevelMixTank2', '3.82256531715393']
['2021-5-4 11:58:15', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 11:58:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:58:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:58:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:58:15', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 11:58:15', 'fActCo2ValMemo', '868']
['2021-5-4 11:58:15', 'fActWaterLevelMixTank1', '273.199096679688']
['2021-5-4 11:58:15', 'fActWaterLevelMixTank2', '293.109100341797']
['2021-5-4 11:58:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:58:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:58:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:58:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:58:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:58:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:58:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:58:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:58:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:58:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:58:15', 'DoVa_Co2', '0']
['2021-5-4 11:58:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:58:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:58:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:58:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:58:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 11:59:15', 'fKWhCounter', '3390.35668945313']
['2021-5-4 11:59:15', 'fActPhLevelMixTank1', '5.58238458633423']
['2021-5-4 11:59:15', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 11:59:15', 'fActPhLevelMixTank2', '3.81450843811035']
['2021-5-4 11:59:15', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 11:59:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 11:59:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 11:59:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 11:59:15', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 11:59:15', 'fActCo2ValMemo', '875']
['2021-5-4 11:59:15', 'fActWaterLevelMixTank1', '273.660858154297']
['2021-5-4 11:59:15', 'fActWaterLevelMixTank2', '292.511535644531']
['2021-5-4 11:59:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 11:59:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 11:59:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 11:59:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 11:59:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 11:59:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 11:59:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 11:59:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 11:59:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 11:59:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 11:59:15', 'DoVa_Co2', '0']
['2021-5-4 11:59:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 11:59:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 11:59:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 11:59:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 11:59:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:0:15', 'fKWhCounter', '3390.55688476563']
['2021-5-4 12:0:15', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 12:0:15', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 12:0:15', 'fActPhLevelMixTank2', '3.81817078590393']
['2021-5-4 12:0:15', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 12:0:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:0:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:0:15', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 12:0:15', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 12:0:15', 'fActCo2ValMemo', '880']
['2021-5-4 12:0:15', 'fActWaterLevelMixTank1', '272.764495849609']
['2021-5-4 12:0:15', 'fActWaterLevelMixTank2', '293.380737304688']
['2021-5-4 12:0:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:0:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:0:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:0:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:0:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:0:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:0:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:0:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:0:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:0:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:0:15', 'DoVa_Co2', '0']
['2021-5-4 12:0:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:0:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:0:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:0:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:0:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:1:15', 'fKWhCounter', '3390.65698242188']
['2021-5-4 12:1:15', 'fActPhLevelMixTank1', '5.57994318008423']
['2021-5-4 12:1:15', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 12:1:15', 'fActPhLevelMixTank2', '3.82061219215393']
['2021-5-4 12:1:15', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 12:1:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:1:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:1:15', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 12:1:15', 'fActRhValMemo', '52']
['2021-5-4 12:1:15', 'fActCo2ValMemo', '886']
['2021-5-4 12:1:15', 'fActWaterLevelMixTank1', '274.557220458984']
['2021-5-4 12:1:15', 'fActWaterLevelMixTank2', '293.788177490234']
['2021-5-4 12:1:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:1:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:1:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:1:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:1:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:1:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:1:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:1:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:1:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:1:15', 'DoVa_IrrigateLevel_2_MT2', '0']

['2021-5-4 12:1:15', 'DoVa_Co2', '0']
['2021-5-4 12:1:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:1:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:1:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:1:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:1:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:2:15', 'fKWhCounter', '3390.85717773438']
['2021-5-4 12:2:15', 'fActPhLevelMixTank1', '5.58409357070923']
['2021-5-4 12:2:15', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 12:2:15', 'fActPhLevelMixTank2', '3.81524085998535']
['2021-5-4 12:2:15', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 12:2:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:2:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:2:15', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 12:2:15', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 12:2:15', 'fActCo2ValMemo', '889']
['2021-5-4 12:2:15', 'fActWaterLevelMixTank1', '274.176940917969']
['2021-5-4 12:2:15', 'fActWaterLevelMixTank2', '292.783142089844']
['2021-5-4 12:2:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:2:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:2:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:2:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:2:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:2:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:2:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:2:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:2:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:2:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:2:15', 'DoVa_Co2', '0']
['2021-5-4 12:2:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:2:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:2:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:2:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:2:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:3:15', 'fKWhCounter', '3390.95727539063']
['2021-5-4 12:3:15', 'fActPhLevelMixTank1', '5.58311700820923']
['2021-5-4 12:3:15', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 12:3:15', 'fActPhLevelMixTank2', '3.81377601623535']
['2021-5-4 12:3:15', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 12:3:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:3:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:3:15', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 12:3:15', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 12:3:15', 'fActCo2ValMemo', '894']
['2021-5-4 12:3:15', 'fActWaterLevelMixTank1', '274.285583496094']
['2021-5-4 12:3:15', 'fActWaterLevelMixTank2', '292.837493896484']
['2021-5-4 12:3:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:3:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:3:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:3:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:3:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:3:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:3:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:3:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:3:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:3:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:3:15', 'DoVa_Co2', '0']
['2021-5-4 12:3:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:3:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:3:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:3:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:3:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:4:15', 'fKWhCounter', '3391.15747070313']
['2021-5-4 12:4:15', 'fActPhLevelMixTank1', '5.57701349258423']
['2021-5-4 12:4:15', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 12:4:15', 'fActPhLevelMixTank2', '3.81524085998535']
['2021-5-4 12:4:15', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 12:4:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:4:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:4:15', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 12:4:15', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 12:4:15', 'fActCo2ValMemo', '901']
['2021-5-4 12:4:15', 'fActWaterLevelMixTank1', '274.910308837891']
['2021-5-4 12:4:15', 'fActWaterLevelMixTank2', '293.733825683594']
['2021-5-4 12:4:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:4:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:4:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:4:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:4:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:4:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:4:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:4:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:4:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:4:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:4:15', 'DoVa_Co2', '0']
['2021-5-4 12:4:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:4:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:4:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:4:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:4:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:5:15', 'fKWhCounter', '3391.25756835938']
['2021-5-4 12:5:15', 'fActPhLevelMixTank1', '5.57945489883423']
['2021-5-4 12:5:15', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 12:5:15', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 12:5:15', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 12:5:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:5:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:5:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:5:15', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 12:5:15', 'fActCo2ValMemo', '901']
['2021-5-4 12:5:15', 'fActWaterLevelMixTank1', '275.073303222656']
['2021-5-4 12:5:15', 'fActWaterLevelMixTank2', '293.462219238281']
['2021-5-4 12:5:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:5:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:5:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:5:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:5:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:5:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:5:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:5:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:5:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:5:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:5:15', 'DoVa_Co2', '0']
['2021-5-4 12:5:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:5:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:5:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:5:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:5:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:6:15', 'fKWhCounter', '3391.45776367188']
['2021-5-4 12:6:15', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 12:6:15', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 12:6:15', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 12:6:15', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 12:6:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:6:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:6:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:6:15', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 12:6:15', 'fActCo2ValMemo', '900']
['2021-5-4 12:6:15', 'fActWaterLevelMixTank1', '275.3720703125']
['2021-5-4 12:6:15', 'fActWaterLevelMixTank2', '293.869659423828']
['2021-5-4 12:6:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:6:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:6:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:6:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:6:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:6:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:6:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:6:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:6:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:6:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:6:15', 'DoVa_Co2', '0']
['2021-5-4 12:6:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:6:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:6:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:6:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_4_Fred', '0']

['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:6:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:7:15', 'fKWhCounter', '3391.55786132813']
['2021-5-4 12:7:15', 'fActPhLevelMixTank1', '5.58238458633423']
['2021-5-4 12:7:15', 'fActEcLevelMixTank1', '2017.2734375']
['2021-5-4 12:7:15', 'fActPhLevelMixTank2', '3.81524085998535']
['2021-5-4 12:7:15', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 12:7:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:7:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:7:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:7:15', 'fActRhValMemo', '52.5']
['2021-5-4 12:7:15', 'fActCo2ValMemo', '902']
['2021-5-4 12:7:15', 'fActWaterLevelMixTank1', '275.073303222656']
['2021-5-4 12:7:15', 'fActWaterLevelMixTank2', '293.760986328125']
['2021-5-4 12:7:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:7:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:7:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:7:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:7:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:7:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:7:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:7:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:7:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:7:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:7:15', 'DoVa_Co2', '0']
['2021-5-4 12:7:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:7:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:7:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:7:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:7:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:8:15', 'fKWhCounter', '3391.75805664063']
['2021-5-4 12:8:15', 'fActPhLevelMixTank1', '5.58995342254639']
['2021-5-4 12:8:15', 'fActEcLevelMixTank1', '2017.12084960938']
['2021-5-4 12:8:15', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 12:8:15', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 12:8:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:8:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:8:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:8:15', 'fActRhValMemo', '52.5']
['2021-5-4 12:8:15', 'fActCo2ValMemo', '900']
['2021-5-4 12:8:15', 'fActWaterLevelMixTank1', '276.349914550781']
['2021-5-4 12:8:15', 'fActWaterLevelMixTank2', '294.331420898438']
['2021-5-4 12:8:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:8:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:8:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:8:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:8:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:8:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:8:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:8:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:8:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:8:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:8:15', 'DoVa_Co2', '0']
['2021-5-4 12:8:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:8:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:8:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:8:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:8:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:9:15', 'fKWhCounter', '3391.85815429688']
['2021-5-4 12:9:15', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 12:9:15', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 12:9:15', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 12:9:15', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 12:9:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:9:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:9:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:9:15', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 12:9:15', 'fActCo2ValMemo', '900']
['2021-5-4 12:9:15', 'fActWaterLevelMixTank1', '276.404235839844']
['2021-5-4 12:9:15', 'fActWaterLevelMixTank2', '294.575866699219']
['2021-5-4 12:9:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:9:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:9:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:9:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:9:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:9:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:9:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:9:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:9:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:9:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:9:15', 'DoVa_Co2', '0']
['2021-5-4 12:9:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:9:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:9:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:9:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:9:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:10:15', 'fKWhCounter', '3392.05834960938']
['2021-5-4 12:10:15', 'fActPhLevelMixTank1', '5.59874248504639']
['2021-5-4 12:10:15', 'fActEcLevelMixTank1', '2016.35791015625']
['2021-5-4 12:10:15', 'fActPhLevelMixTank2', '3.82403016090393']
['2021-5-4 12:10:15', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 12:10:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:10:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:10:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:10:15', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 12:10:15', 'fActCo2ValMemo', '900']
['2021-5-4 12:10:15', 'fActWaterLevelMixTank1', '276.132629394531']
['2021-5-4 12:10:15', 'fActWaterLevelMixTank2', '294.521545410156']
['2021-5-4 12:10:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:10:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:10:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:10:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:10:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:10:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:10:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:10:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:10:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:10:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:10:15', 'DoVa_Co2', '0']
['2021-5-4 12:10:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:10:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:10:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:10:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:10:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:11:15', 'fKWhCounter', '3392.15844726563']
['2021-5-4 12:11:15', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 12:11:15', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 12:11:15', 'fActPhLevelMixTank2', '3.82061219215393']
['2021-5-4 12:11:15', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 12:11:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:11:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:11:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:11:15', 'fActRhValMemo', '53.0999984741211']
['2021-5-4 12:11:15', 'fActCo2ValMemo', '896']
['2021-5-4 12:11:15', 'fActWaterLevelMixTank1', '276.893157958984']
['2021-5-4 12:11:15', 'fActWaterLevelMixTank2', '294.467224121094']
['2021-5-4 12:11:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:11:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:11:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:11:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:11:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:11:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:11:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:11:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:11:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:11:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:11:15', 'DoVa_Co2', '0']
['2021-5-4 12:11:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:11:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:11:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:11:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:11:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:12:15', 'fKWhCounter', '3392.35864257813']
['2021-5-4 12:12:15', 'fActPhLevelMixTank1', '5.60484647750854']
['2021-5-4 12:12:15', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 12:12:15', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 12:12:15', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 12:12:15', 'fTaktCounterUpperLevel', '0']

['2021-5-4 12:12:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:12:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:12:15', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 12:12:15', 'fActCo2ValMemo', '899']
['2021-5-4 12:12:15', 'fActWaterLevelMixTank1', '277.816680908203']
['2021-5-4 12:12:15', 'fActWaterLevelMixTank2', '294.684509277344']
['2021-5-4 12:12:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:12:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:12:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:12:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:12:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:12:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:12:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:12:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:12:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:12:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:12:15', 'DoVa_Co2', '0']
['2021-5-4 12:12:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:12:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:12:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:12:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:12:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:13:15', 'fKWhCounter', '3392.45874023438']
['2021-5-4 12:13:15', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 12:13:15', 'fActEcLevelMixTank1', '2014.83203125']
['2021-5-4 12:13:15', 'fActPhLevelMixTank2', '3.82891321182251']
['2021-5-4 12:13:15', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 12:13:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:13:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:13:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:13:15', 'fActRhValMemo', '53.4000015258789']
['2021-5-4 12:13:15', 'fActCo2ValMemo', '896']
['2021-5-4 12:13:15', 'fActWaterLevelMixTank1', '277.925354003906']
['2021-5-4 12:13:15', 'fActWaterLevelMixTank2', '295.037628173828']
['2021-5-4 12:13:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:13:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:13:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:13:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:13:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:13:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:13:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:13:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:13:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:13:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:13:15', 'DoVa_Co2', '0']
['2021-5-4 12:13:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:13:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:13:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:13:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:13:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:14:15', 'fKWhCounter', '3392.55883789063']
['2021-5-4 12:14:15', 'fActPhLevelMixTank1', '5.61021757125854']
['2021-5-4 12:14:15', 'fActEcLevelMixTank1', '2014.06909179688']
['2021-5-4 12:14:15', 'fActPhLevelMixTank2', '3.82915735244751']
['2021-5-4 12:14:15', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 12:14:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:14:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:14:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:14:15', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 12:14:15', 'fActCo2ValMemo', '900']
['2021-5-4 12:14:15', 'fActWaterLevelMixTank1', '277.300598144531']
['2021-5-4 12:14:15', 'fActWaterLevelMixTank2', '294.820343017578']
['2021-5-4 12:14:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:14:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:14:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:14:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:14:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:14:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:14:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:14:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:14:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:14:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:14:15', 'DoVa_Co2', '0']
['2021-5-4 12:14:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:14:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:14:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:14:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:14:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:15:15', 'fKWhCounter', '3392.75903320313']
['2021-5-4 12:15:15', 'fActPhLevelMixTank1', '5.60728788375854']
['2021-5-4 12:15:15', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 12:15:15', 'fActPhLevelMixTank2', '3.83062219619751']
['2021-5-4 12:15:15', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 12:15:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:15:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:15:15', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 12:15:15', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 12:15:15', 'fActCo2ValMemo', '901']
['2021-5-4 12:15:15', 'fActWaterLevelMixTank1', '276.540069580078']
['2021-5-4 12:15:15', 'fActWaterLevelMixTank2', '295.146270751953']
['2021-5-4 12:15:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:15:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:15:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:15:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:15:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:15:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:15:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:15:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:15:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:15:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:15:15', 'DoVa_Co2', '0']
['2021-5-4 12:15:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:15:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:15:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:15:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:15:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:16:15', 'fKWhCounter', '3392.85913085938']
['2021-5-4 12:16:15', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 12:16:15', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 12:16:15', 'fActPhLevelMixTank2', '3.83111047744751']
['2021-5-4 12:16:15', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 12:16:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:16:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:16:15', 'fActTempValMemo', '21.5']
['2021-5-4 12:16:15', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 12:16:15', 'fActCo2ValMemo', '896']
['2021-5-4 12:16:15', 'fActWaterLevelMixTank1', '277.517913818359']
['2021-5-4 12:16:15', 'fActWaterLevelMixTank2', '295.580871582031']
['2021-5-4 12:16:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:16:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:16:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:16:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:16:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:16:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:16:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:16:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:16:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:16:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:16:15', 'DoVa_Co2', '0']
['2021-5-4 12:16:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:16:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:16:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:16:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:16:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:17:15', 'fKWhCounter', '3393.05932617188']
['2021-5-4 12:17:15', 'fActPhLevelMixTank1', '5.60728788375854']
['2021-5-4 12:17:15', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 12:17:15', 'fActPhLevelMixTank2', '3.83623766899109']
['2021-5-4 12:17:15', 'fActEcLevelMixTank2', '1031.9833984375']

['2021-5-4 12:17:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:17:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:17:15', 'fActTempValMemo', '21.5']
['2021-5-4 12:17:15', 'fActRhValMemo', '52.5']
['2021-5-4 12:17:15', 'fActCo2ValMemo', '898']
['2021-5-4 12:17:15', 'fActWaterLevelMixTank1', '278.332763671875']
['2021-5-4 12:17:15', 'fActWaterLevelMixTank2', '295.526550292969']
['2021-5-4 12:17:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:17:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:17:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:17:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:17:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:17:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:17:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:17:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:17:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:17:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:17:15', 'DoVa_Co2', '0']
['2021-5-4 12:17:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:17:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:17:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:17:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:17:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:18:15', 'fKWhCounter', '3393.15942382813']
['2021-5-4 12:18:15', 'fActPhLevelMixTank1', '5.60679960250854']
['2021-5-4 12:18:15', 'fActEcLevelMixTank1', '2007.35498046875']
['2021-5-4 12:18:15', 'fActPhLevelMixTank2', '3.83477282524109']
['2021-5-4 12:18:15', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 12:18:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:18:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:18:15', 'fActTempValMemo', '21.5']
['2021-5-4 12:18:15', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 12:18:15', 'fActCo2ValMemo', '895']
['2021-5-4 12:18:15', 'fActWaterLevelMixTank1', '279.636566162109']
['2021-5-4 12:18:15', 'fActWaterLevelMixTank2', '295.988311767578']
['2021-5-4 12:18:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:18:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:18:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:18:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:18:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:18:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:18:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:18:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:18:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:18:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:18:15', 'DoVa_Co2', '0']
['2021-5-4 12:18:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:18:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:18:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:18:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:18:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:19:15', 'fKWhCounter', '3393.35961914063']
['2021-5-4 12:19:15', 'fActPhLevelMixTank1', '5.60631132125854']
['2021-5-4 12:19:15', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 12:19:15', 'fActPhLevelMixTank2', '3.83013391494751']
['2021-5-4 12:19:15', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 12:19:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:19:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:19:15', 'fActTempValMemo', '21.5']
['2021-5-4 12:19:15', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 12:19:15', 'fActCo2ValMemo', '896']
['2021-5-4 12:19:15', 'fActWaterLevelMixTank1', '279.120483398438']
['2021-5-4 12:19:15', 'fActWaterLevelMixTank2', '296.205627441406']
['2021-5-4 12:19:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:19:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:19:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:19:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:19:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:19:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:19:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:19:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:19:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:19:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:19:15', 'DoVa_Co2', '0']
['2021-5-4 12:19:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:19:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:19:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:19:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:19:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:20:15', 'fKWhCounter', '3393.45971679688']
['2021-5-4 12:20:15', 'fActPhLevelMixTank1', '5.61094999313354']
['2021-5-4 12:20:15', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 12:20:15', 'fActPhLevelMixTank2', '3.83574938774109']
['2021-5-4 12:20:15', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 12:20:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:20:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:20:15', 'fActTempValMemo', '21.5']
['2021-5-4 12:20:15', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 12:20:15', 'fActCo2ValMemo', '896']
['2021-5-4 12:20:15', 'fActWaterLevelMixTank1', '277.816680908203']
['2021-5-4 12:20:15', 'fActWaterLevelMixTank2', '295.961151123047']
['2021-5-4 12:20:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:20:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:20:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:20:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:20:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:20:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:20:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:20:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:20:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:20:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:20:15', 'DoVa_Co2', '0']
['2021-5-4 12:20:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:20:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:20:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:20:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:20:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:21:15', 'fKWhCounter', '3393.65991210938']
['2021-5-4 12:21:15', 'fActPhLevelMixTank1', '5.61558866500854']
['2021-5-4 12:21:15', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 12:21:15', 'fActPhLevelMixTank2', '3.83819079399109']
['2021-5-4 12:21:15', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 12:21:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:21:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:21:15', 'fActTempValMemo', '21.5']
['2021-5-4 12:21:15', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 12:21:15', 'fActCo2ValMemo', '893']
['2021-5-4 12:21:15', 'fActWaterLevelMixTank1', '278.495758056641']
['2021-5-4 12:21:15', 'fActWaterLevelMixTank2', '296.096954345703']
['2021-5-4 12:21:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:21:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:21:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:21:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:21:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:21:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:21:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:21:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:21:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:21:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:21:15', 'DoVa_Co2', '0']
['2021-5-4 12:21:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:21:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:21:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:21:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_4_Red', '0']

['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:21:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:22:15', 'fKWhCounter', '3393.76000976563']
['2021-5-4 12:22:15', 'fActPhLevelMixTank1', '5.61021757125854']
['2021-5-4 12:22:15', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 12:22:15', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 12:22:15', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 12:22:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:22:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:22:15', 'fActTempValMemo', '21.5']
['2021-5-4 12:22:15', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 12:22:15', 'fActCo2ValMemo', '891']
['2021-5-4 12:22:15', 'fActWaterLevelMixTank1', '278.848876953125']
['2021-5-4 12:22:15', 'fActWaterLevelMixTank2', '295.988311767578']
['2021-5-4 12:22:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:22:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:22:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:22:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:22:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:22:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:22:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:22:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:22:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:22:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:22:15', 'DoVa_Co2', '0']
['2021-5-4 12:22:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:22:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:22:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:22:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:22:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:23:15', 'fKWhCounter', '3393.96020507813']
['2021-5-4 12:23:15', 'fActPhLevelMixTank1', '5.6202278137207']
['2021-5-4 12:23:15', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 12:23:15', 'fActPhLevelMixTank2', '3.83355212211609']
['2021-5-4 12:23:15', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 12:23:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:23:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:23:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:23:15', 'fActRhValMemo', '53.0999984741211']
['2021-5-4 12:23:15', 'fActCo2ValMemo', '893']
['2021-5-4 12:23:15', 'fActWaterLevelMixTank1', '280.016845703125']
['2021-5-4 12:23:15', 'fActWaterLevelMixTank2', '296.015472412109']
['2021-5-4 12:23:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:23:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:23:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:23:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:23:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:23:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:23:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:23:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:23:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:23:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:23:15', 'DoVa_Co2', '0']
['2021-5-4 12:23:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:23:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:23:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:23:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:23:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:24:15', 'fKWhCounter', '3394.06030273438']
['2021-5-4 12:24:15', 'fActPhLevelMixTank1', '5.6182746887207']
['2021-5-4 12:24:15', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 12:24:15', 'fActPhLevelMixTank2', '3.83574938774109']
['2021-5-4 12:24:15', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 12:24:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:24:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:24:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:24:15', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 12:24:15', 'fActCo2ValMemo', '894']
['2021-5-4 12:24:15', 'fActWaterLevelMixTank1', '279.690887451172']
['2021-5-4 12:24:15', 'fActWaterLevelMixTank2', '296.015472412109']
['2021-5-4 12:24:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:24:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:24:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:24:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:24:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:24:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:24:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:24:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:24:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:24:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:24:15', 'DoVa_Co2', '0']
['2021-5-4 12:24:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:24:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:24:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:24:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:24:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:25:15', 'fKWhCounter', '3394.26049804688']
['2021-5-4 12:25:15', 'fActPhLevelMixTank1', '5.6241340637207']
['2021-5-4 12:25:15', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 12:25:15', 'fActPhLevelMixTank2', '3.83721423149109']
['2021-5-4 12:25:15', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 12:25:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:25:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:25:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:25:15', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 12:25:15', 'fActCo2ValMemo', '895']
['2021-5-4 12:25:15', 'fActWaterLevelMixTank1', '279.853881835938']
['2021-5-4 12:25:15', 'fActWaterLevelMixTank2', '296.694549560547']
['2021-5-4 12:25:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:25:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:25:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:25:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:25:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:25:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:25:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:25:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:25:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:25:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:25:15', 'DoVa_Co2', '0']
['2021-5-4 12:25:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:25:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:25:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:25:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:25:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:26:15', 'fKWhCounter', '3394.36059570313']
['2021-5-4 12:26:15', 'fActPhLevelMixTank1', '5.6253547668457']
['2021-5-4 12:26:15', 'fActEcLevelMixTank1', '2015.90014648438']
['2021-5-4 12:26:15', 'fActPhLevelMixTank2', '3.83477282524109']
['2021-5-4 12:26:15', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 12:26:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:26:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:26:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:26:15', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 12:26:15', 'fActCo2ValMemo', '892']
['2021-5-4 12:26:15', 'fActWaterLevelMixTank1', '279.853881835938']
['2021-5-4 12:26:15', 'fActWaterLevelMixTank2', '296.477233886719']
['2021-5-4 12:26:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:26:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:26:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:26:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:26:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:26:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:26:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:26:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:26:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:26:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:26:15', 'DoVa_Co2', '0']
['2021-5-4 12:26:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:26:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:26:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:26:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_1_Red', '0']

['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:26:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:27:15', 'fKWhCounter', '3394.56079101563']
['2021-5-4 12:27:15', 'fActPhLevelMixTank1', '5.6224250793457']
['2021-5-4 12:27:15', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 12:27:15', 'fActPhLevelMixTank2', '3.83623766899109']
['2021-5-4 12:27:15', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 12:27:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:27:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:27:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:27:15', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 12:27:15', 'fActCo2ValMemo', '885']
['2021-5-4 12:27:15', 'fActWaterLevelMixTank1', '280.994689941406']
['2021-5-4 12:27:15', 'fActWaterLevelMixTank2', '296.830352783203']
['2021-5-4 12:27:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:27:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:27:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:27:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:27:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:27:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:27:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:27:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:27:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:27:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:27:15', 'DoVa_Co2', '0']
['2021-5-4 12:27:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:27:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:27:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:27:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:27:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:28:15', 'fKWhCounter', '3394.66088867188']
['2021-5-4 12:28:15', 'fActPhLevelMixTank1', '5.6321907043457']
['2021-5-4 12:28:15', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 12:28:15', 'fActPhLevelMixTank2', '3.83867907524109']
['2021-5-4 12:28:15', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 12:28:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:28:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:28:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:28:15', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 12:28:15', 'fActCo2ValMemo', '884']
['2021-5-4 12:28:15', 'fActWaterLevelMixTank1', '280.261291503906']
['2021-5-4 12:28:15', 'fActWaterLevelMixTank2', '297.264953613281']
['2021-5-4 12:28:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:28:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:28:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:28:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:28:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:28:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:28:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:28:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:28:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:28:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:28:15', 'DoVa_Co2', '0']
['2021-5-4 12:28:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:28:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:28:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:28:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:28:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:29:15', 'fKWhCounter', '3394.86108398438']
['2021-5-4 12:29:15', 'fActPhLevelMixTank1', '5.63316774368286']
['2021-5-4 12:29:15', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 12:29:15', 'fActPhLevelMixTank2', '3.83867907524109']
['2021-5-4 12:29:15', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 12:29:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:29:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:29:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:29:15', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 12:29:15', 'fActCo2ValMemo', '886']
['2021-5-4 12:29:15', 'fActWaterLevelMixTank1', '281.157653808594']
['2021-5-4 12:29:15', 'fActWaterLevelMixTank2', '297.264953613281']
['2021-5-4 12:29:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:29:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:29:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:29:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:29:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:29:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:29:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:29:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:29:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:29:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:29:15', 'DoVa_Co2', '0']
['2021-5-4 12:29:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:29:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:29:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:29:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:29:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:30:15', 'fKWhCounter', '3394.96118164063']
['2021-5-4 12:30:15', 'fActPhLevelMixTank1', '5.64366579055786']
['2021-5-4 12:30:15', 'fActEcLevelMixTank1', '2027.03942871094']
['2021-5-4 12:30:15', 'fActPhLevelMixTank2', '3.83574938774109']
['2021-5-4 12:30:15', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 12:30:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:30:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:30:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:30:15', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 12:30:15', 'fActCo2ValMemo', '885']
['2021-5-4 12:30:15', 'fActWaterLevelMixTank1', '281.483612060547']
['2021-5-4 12:30:15', 'fActWaterLevelMixTank2', '296.803192138672']
['2021-5-4 12:30:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:30:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:30:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:30:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:30:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:30:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:30:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:30:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:30:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:30:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:30:15', 'DoVa_Co2', '0']
['2021-5-4 12:30:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:30:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:30:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:30:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:30:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:31:15', 'fKWhCounter', '3395.16137695313']
['2021-5-4 12:31:15', 'fActPhLevelMixTank1', '5.65099048614502']
['2021-5-4 12:31:15', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 12:31:15', 'fActPhLevelMixTank2', '3.84209728240967']
['2021-5-4 12:31:15', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 12:31:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:31:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:31:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:31:15', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 12:31:15', 'fActCo2ValMemo', '886']
['2021-5-4 12:31:15', 'fActWaterLevelMixTank1', '279.392120361328']
['2021-5-4 12:31:15', 'fActWaterLevelMixTank2', '297.672393798828']
['2021-5-4 12:31:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:31:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:31:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:31:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:31:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:31:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:31:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:31:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:31:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:31:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:31:15', 'DoVa_Co2', '0']
['2021-5-4 12:31:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:31:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:31:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:31:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_2_Blue', '0']

['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:31:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:32:15', 'fKWhCounter', '3395.26147460938']
['2021-5-4 12:32:15', 'fActPhLevelMixTank1', '5.65123462677002']
['2021-5-4 12:32:15', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 12:32:15', 'fActPhLevelMixTank2', '3.84478282928467']
['2021-5-4 12:32:15', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 12:32:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:32:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:32:15', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:32:15', 'fActRhValMemo', '52.5']
['2021-5-4 12:32:15', 'fActCo2ValMemo', '883']
['2021-5-4 12:32:15', 'fActWaterLevelMixTank1', '281.347808837891']
['2021-5-4 12:32:15', 'fActWaterLevelMixTank2', '297.264953613281']
['2021-5-4 12:32:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:32:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:32:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:32:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:32:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:32:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:32:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:32:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:32:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:32:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:32:15', 'DoVa_Co2', '0']
['2021-5-4 12:32:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:32:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:32:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:32:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:32:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:33:15', 'fKWhCounter', '3395.46166992188']
['2021-5-4 12:33:15', 'fActPhLevelMixTank1', '5.65587329864502']
['2021-5-4 12:33:15', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 12:33:15', 'fActPhLevelMixTank2', '3.84136486053467']
['2021-5-4 12:33:15', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 12:33:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:33:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:33:15', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:33:15', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 12:33:15', 'fActCo2ValMemo', '880']
['2021-5-4 12:33:15', 'fActWaterLevelMixTank1', '281.565093994141']
['2021-5-4 12:33:15', 'fActWaterLevelMixTank2', '297.427917480469']
['2021-5-4 12:33:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:33:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:33:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:33:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:33:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:33:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:33:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:33:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:33:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:33:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:33:15', 'DoVa_Co2', '0']
['2021-5-4 12:33:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:33:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:33:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:33:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:33:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:34:15', 'fKWhCounter', '3395.56176757813']
['2021-5-4 12:34:15', 'fActPhLevelMixTank1', '5.65636157989502']
['2021-5-4 12:34:15', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 12:34:15', 'fActPhLevelMixTank2', '3.83941149711609']
['2021-5-4 12:34:15', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 12:34:15', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:34:15', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:34:15', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:34:15', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 12:34:15', 'fActCo2ValMemo', '877']
['2021-5-4 12:34:15', 'fActWaterLevelMixTank1', '281.619415283203']
['2021-5-4 12:34:15', 'fActWaterLevelMixTank2', '297.319274902344']
['2021-5-4 12:34:15', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:34:15', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:34:15', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:34:15', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:34:15', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:34:15', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:34:15', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:34:15', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:34:15', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:34:15', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:34:15', 'DoVa_Co2', '0']
['2021-5-4 12:34:15', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:34:15', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:34:15', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:34:15', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:34:15', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:35:16', 'fKWhCounter', '3395.66186523438']
['2021-5-4 12:35:16', 'fActPhLevelMixTank1', '5.65489673614502']
['2021-5-4 12:35:16', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 12:35:16', 'fActPhLevelMixTank2', '3.84673595428467']
['2021-5-4 12:35:16', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 12:35:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:35:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:35:16', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:35:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 12:35:16', 'fActCo2ValMemo', '880']
['2021-5-4 12:35:16', 'fActWaterLevelMixTank1', '282.162658691406']
['2021-5-4 12:35:16', 'fActWaterLevelMixTank2', '297.482238769531']
['2021-5-4 12:35:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:35:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:35:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:35:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:35:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:35:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:35:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:35:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:35:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:35:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:35:16', 'DoVa_Co2', '0']
['2021-5-4 12:35:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:35:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:35:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:35:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_2_Fred', '0']

['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:35:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:36:16', 'fKWhCounter', '3395.86206054688']
['2021-5-4 12:36:16', 'fActPhLevelMixTank1', '5.66441869735718']
['2021-5-4 12:36:16', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 12:36:16', 'fActPhLevelMixTank2', '3.84502696990967']
['2021-5-4 12:36:16', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 12:36:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:36:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:36:16', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:36:16', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 12:36:16', 'fActCo2ValMemo', '881']
['2021-5-4 12:36:16', 'fActWaterLevelMixTank1', '282.298492431641']
['2021-5-4 12:36:16', 'fActWaterLevelMixTank2', '297.482238769531']
['2021-5-4 12:36:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:36:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:36:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:36:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:36:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:36:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:36:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:36:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:36:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:36:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:36:16', 'DoVa_Co2', '0']
['2021-5-4 12:36:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:36:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:36:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:36:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:36:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:37:16', 'fKWhCounter', '3395.96215820313']
['2021-5-4 12:37:16', 'fActPhLevelMixTank1', '5.66148853302002']
['2021-5-4 12:37:16', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 12:37:16', 'fActPhLevelMixTank2', '3.84185314178467']
['2021-5-4 12:37:16', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 12:37:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:37:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:37:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:37:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 12:37:16', 'fActCo2ValMemo', '878']
['2021-5-4 12:37:16', 'fActWaterLevelMixTank1', '281.673736572266']
['2021-5-4 12:37:16', 'fActWaterLevelMixTank2', '297.753875732422']
['2021-5-4 12:37:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:37:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:37:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:37:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:37:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:37:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:37:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:37:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:37:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:37:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:37:16', 'DoVa_Co2', '0']
['2021-5-4 12:37:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:37:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:37:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:37:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:37:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:38:16', 'fKWhCounter', '3396.16235351563']
['2021-5-4 12:38:16', 'fActPhLevelMixTank1', '5.67125463485718']
['2021-5-4 12:38:16', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 12:38:16', 'fActPhLevelMixTank2', '3.84527111053467']
['2021-5-4 12:38:16', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 12:38:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:38:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:38:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:38:16', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 12:38:16', 'fActCo2ValMemo', '876']
['2021-5-4 12:38:16', 'fActWaterLevelMixTank1', '282.244171142578']
['2021-5-4 12:38:16', 'fActWaterLevelMixTank2', '297.672393798828']
['2021-5-4 12:38:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:38:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:38:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:38:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:38:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:38:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:38:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:38:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:38:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:38:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:38:16', 'DoVa_Co2', '0']
['2021-5-4 12:38:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:38:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:38:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:38:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:38:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:39:16', 'fKWhCounter', '3396.26245117188']
['2021-5-4 12:39:16', 'fActPhLevelMixTank1', '5.66246509552002']
['2021-5-4 12:39:16', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 12:39:16', 'fActPhLevelMixTank2', '3.85064244270325']
['2021-5-4 12:39:16', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 12:39:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:39:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:39:16', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 12:39:16', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 12:39:16', 'fActCo2ValMemo', '877']
['2021-5-4 12:39:16', 'fActWaterLevelMixTank1', '282.597259521484']
['2021-5-4 12:39:16', 'fActWaterLevelMixTank2', '297.781036376953']
['2021-5-4 12:39:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:39:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:39:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:39:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:39:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:39:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:39:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:39:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:39:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:39:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:39:16', 'DoVa_Co2', '0']
['2021-5-4 12:39:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:39:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:39:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:39:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:39:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:40:16', 'fKWhCounter', '3396.46264648438']
['2021-5-4 12:40:16', 'fActPhLevelMixTank1', '5.67223119735718']
['2021-5-4 12:40:16', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 12:40:16', 'fActPhLevelMixTank2', '3.84624767303467']
['2021-5-4 12:40:16', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 12:40:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:40:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:40:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:40:16', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 12:40:16', 'fActCo2ValMemo', '876']
['2021-5-4 12:40:16', 'fActWaterLevelMixTank1', '282.896057128906']
['2021-5-4 12:40:16', 'fActWaterLevelMixTank2', '298.106994628906']
['2021-5-4 12:40:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:40:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:40:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:40:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:40:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:40:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:40:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:40:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:40:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:40:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:40:16', 'DoVa_Co2', '0']
['2021-5-4 12:40:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:40:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:40:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:40:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:40:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']

['2021-5-4 12:40:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:41:16', 'fKWhCounter', '3396.56274414063']
['2021-5-4 12:41:16', 'fActPhLevelMixTank1', '5.67491674423218']
['2021-5-4 12:41:16', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 12:41:16', 'fActPhLevelMixTank2', '3.84575939178467']
['2021-5-4 12:41:16', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 12:41:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:41:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:41:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:41:16', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 12:41:16', 'fActCo2ValMemo', '877']
['2021-5-4 12:41:16', 'fActWaterLevelMixTank1', '282.189819335938']
['2021-5-4 12:41:16', 'fActWaterLevelMixTank2', '297.590881347656']
['2021-5-4 12:41:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:41:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:41:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:41:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:41:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:41:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:41:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:41:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:41:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:41:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:41:16', 'DoVa_Co2', '0']
['2021-5-4 12:41:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:41:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:41:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:41:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:41:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:42:16', 'fKWhCounter', '3396.76293945313']
['2021-5-4 12:42:16', 'fActPhLevelMixTank1', '5.68102073669434']
['2021-5-4 12:42:16', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 12:42:16', 'fActPhLevelMixTank2', '3.84991002082825']
['2021-5-4 12:42:16', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 12:42:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:42:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:42:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:42:16', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 12:42:16', 'fActCo2ValMemo', '878']
['2021-5-4 12:42:16', 'fActWaterLevelMixTank1', '282.705932617188']
['2021-5-4 12:42:16', 'fActWaterLevelMixTank2', '298.215637207031']
['2021-5-4 12:42:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:42:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:42:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:42:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:42:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:42:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:42:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:42:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:42:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:42:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:42:16', 'DoVa_Co2', '0']
['2021-5-4 12:42:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:42:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:42:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:42:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:42:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:43:16', 'fKWhCounter', '3396.86303710938']
['2021-5-4 12:43:16', 'fActPhLevelMixTank1', '5.67613744735718']
['2021-5-4 12:43:16', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 12:43:16', 'fActPhLevelMixTank2', '3.84527111053467']
['2021-5-4 12:43:16', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 12:43:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:43:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:43:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:43:16', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 12:43:16', 'fActCo2ValMemo', '875']
['2021-5-4 12:43:16', 'fActWaterLevelMixTank1', '282.515777587891']
['2021-5-4 12:43:16', 'fActWaterLevelMixTank2', '297.781036376953']
['2021-5-4 12:43:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:43:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:43:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:43:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:43:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:43:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:43:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:43:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:43:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:43:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:43:16', 'DoVa_Co2', '0']
['2021-5-4 12:43:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:43:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:43:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:43:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:43:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:44:16', 'fKWhCounter', '3397.06323242188']
['2021-5-4 12:44:16', 'fActPhLevelMixTank1', '5.67247533798218']
['2021-5-4 12:44:16', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 12:44:16', 'fActPhLevelMixTank2', '3.84282970428467']
['2021-5-4 12:44:16', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 12:44:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:44:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:44:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:44:16', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 12:44:16', 'fActCo2ValMemo', '874']
['2021-5-4 12:44:16', 'fActWaterLevelMixTank1', '282.923217773438']
['2021-5-4 12:44:16', 'fActWaterLevelMixTank2', '298.40576171875']
['2021-5-4 12:44:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:44:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:44:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:44:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:44:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:44:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:44:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:44:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:44:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:44:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:44:16', 'DoVa_Co2', '0']
['2021-5-4 12:44:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:44:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:44:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:44:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:44:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:45:16', 'fKWhCounter', '3397.16333007813']
['2021-5-4 12:45:16', 'fActPhLevelMixTank1', '5.68004417419434']
['2021-5-4 12:45:16', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 12:45:16', 'fActPhLevelMixTank2', '3.84771275520325']
['2021-5-4 12:45:16', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 12:45:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:45:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:45:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:45:16', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 12:45:16', 'fActCo2ValMemo', '872']
['2021-5-4 12:45:16', 'fActWaterLevelMixTank1', '283.819580078125']
['2021-5-4 12:45:16', 'fActWaterLevelMixTank2', '298.731719970703']
['2021-5-4 12:45:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:45:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:45:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:45:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:45:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:45:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:45:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:45:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:45:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:45:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:45:16', 'DoVa_Co2', '0']
['2021-5-4 12:45:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:45:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:45:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:45:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']

['2021-5-4 12:45:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:45:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:46:16', 'fKWhCounter', '3397.26342773438']
['2021-5-4 12:46:16', 'fActPhLevelMixTank1', '5.67589330673218']
['2021-5-4 12:46:16', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 12:46:16', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 12:46:16', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 12:46:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:46:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:46:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:46:16', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 12:46:16', 'fActCo2ValMemo', '874']
['2021-5-4 12:46:16', 'fActWaterLevelMixTank1', '283.738098144531']
['2021-5-4 12:46:16', 'fActWaterLevelMixTank2', '298.731719970703']
['2021-5-4 12:46:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:46:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:46:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:46:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:46:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:46:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:46:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:46:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:46:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:46:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:46:16', 'DoVa_Co2', '0']
['2021-5-4 12:46:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:46:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:46:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:46:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:46:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:47:16', 'fKWhCounter', '3397.46362304688']
['2021-5-4 12:47:16', 'fActPhLevelMixTank1', '5.68565940856934']
['2021-5-4 12:47:16', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 12:47:16', 'fActPhLevelMixTank2', '3.84893345832825']
['2021-5-4 12:47:16', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 12:47:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:47:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:47:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:47:16', 'fActRhValMemo', '51.5']
['2021-5-4 12:47:16', 'fActCo2ValMemo', '874']
['2021-5-4 12:47:16', 'fActWaterLevelMixTank1', '283.955383300781']
['2021-5-4 12:47:16', 'fActWaterLevelMixTank2', '298.786041259766']
['2021-5-4 12:47:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:47:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:47:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:47:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:47:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:47:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:47:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:47:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:47:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:47:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:47:16', 'DoVa_Co2', '0']
['2021-5-4 12:47:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:47:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:47:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:47:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:47:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:48:16', 'fKWhCounter', '3397.56372070313']
['2021-5-4 12:48:16', 'fActPhLevelMixTank1', '5.68224143981934']
['2021-5-4 12:48:16', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 12:48:16', 'fActPhLevelMixTank2', '3.85552549362183']
['2021-5-4 12:48:16', 'fActEcLevelMixTank2', '1039.1552734375']
['2021-5-4 12:48:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:48:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:48:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:48:16', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 12:48:16', 'fActCo2ValMemo', '874']
['2021-5-4 12:48:16', 'fActWaterLevelMixTank1', '282.923217773438']
['2021-5-4 12:48:16', 'fActWaterLevelMixTank2', '298.894683837891']
['2021-5-4 12:48:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:48:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:48:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:48:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:48:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:48:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:48:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:48:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:48:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:48:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:48:16', 'DoVa_Co2', '0']
['2021-5-4 12:48:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:48:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:48:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:48:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:48:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:49:16', 'fKWhCounter', '3397.76391601563']
['2021-5-4 12:49:16', 'fActPhLevelMixTank1', '5.68785667419434']
['2021-5-4 12:49:16', 'fActEcLevelMixTank1', '2032.68530273438']
['2021-5-4 12:49:16', 'fActPhLevelMixTank2', '3.85357213020325']
['2021-5-4 12:49:16', 'fActEcLevelMixTank2', '1040.07080078125']
['2021-5-4 12:49:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:49:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:49:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:49:16', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 12:49:16', 'fActCo2ValMemo', '874']
['2021-5-4 12:49:16', 'fActWaterLevelMixTank1', '282.733093261719']
['2021-5-4 12:49:16', 'fActWaterLevelMixTank2', '299.057678222656']
['2021-5-4 12:49:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:49:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:49:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:49:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:49:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:49:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:49:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:49:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:49:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:49:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:49:16', 'DoVa_Co2', '0']
['2021-5-4 12:49:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:49:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:49:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:49:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:49:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:50:16', 'fKWhCounter', '3397.86401367188']
['2021-5-4 12:50:16', 'fActPhLevelMixTank1', '5.68297386169434']
['2021-5-4 12:50:16', 'fActEcLevelMixTank1', '2029.78601074219']
['2021-5-4 12:50:16', 'fActPhLevelMixTank2', '3.85064244270325']
['2021-5-4 12:50:16', 'fActEcLevelMixTank2', '1038.69750976563']
['2021-5-4 12:50:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:50:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:50:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:50:16', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 12:50:16', 'fActCo2ValMemo', '873']
['2021-5-4 12:50:16', 'fActWaterLevelMixTank1', '283.602264404297']

['2021-5-4 12:50:16', 'fActWaterLevelMixTank2', '298.106994628906']
['2021-5-4 12:50:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:50:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:50:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:50:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:50:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:50:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:50:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:50:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:50:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:50:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:50:16', 'DoVa_Co2', '0']
['2021-5-4 12:50:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:50:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:50:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:50:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:50:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:51:16', 'fKWhCounter', '3398.06420898438']
['2021-5-4 12:51:16', 'fActPhLevelMixTank1', '5.68492698669434']
['2021-5-4 12:51:16', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 12:51:16', 'fActPhLevelMixTank2', '3.85430455207825']
['2021-5-4 12:51:16', 'fActEcLevelMixTank2', '1039.00268554688']
['2021-5-4 12:51:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:51:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:51:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:51:16', 'fActRhValMemo', '52']
['2021-5-4 12:51:16', 'fActCo2ValMemo', '872']
['2021-5-4 12:51:16', 'fActWaterLevelMixTank1', '283.738098144531']
['2021-5-4 12:51:16', 'fActWaterLevelMixTank2', '298.487243652344']
['2021-5-4 12:51:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:51:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:51:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:51:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:51:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:51:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:51:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:51:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:51:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:51:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:51:16', 'DoVa_Co2', '0']
['2021-5-4 12:51:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:51:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:51:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:51:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:51:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:52:16', 'fKWhCounter', '3398.16430664063']
['2021-5-4 12:52:16', 'fActPhLevelMixTank1', '5.68590354919434']
['2021-5-4 12:52:16', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 12:52:16', 'fActPhLevelMixTank2', '3.85454869270325']
['2021-5-4 12:52:16', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 12:52:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:52:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:52:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:52:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 12:52:16', 'fActCo2ValMemo', '870']
['2021-5-4 12:52:16', 'fActWaterLevelMixTank1', '284.145538330078']
['2021-5-4 12:52:16', 'fActWaterLevelMixTank2', '298.623077392578']
['2021-5-4 12:52:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:52:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:52:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:52:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:52:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:52:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:52:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:52:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:52:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:52:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:52:16', 'DoVa_Co2', '0']
['2021-5-4 12:52:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:52:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:52:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:52:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:52:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:53:16', 'fKWhCounter', '3398.36450195313']
['2021-5-4 12:53:16', 'fActPhLevelMixTank1', '5.68785667419434']
['2021-5-4 12:53:16', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 12:53:16', 'fActPhLevelMixTank2', '3.85381627082825']
['2021-5-4 12:53:16', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 12:53:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:53:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:53:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:53:16', 'fActRhValMemo', '52']
['2021-5-4 12:53:16', 'fActCo2ValMemo', '870']
['2021-5-4 12:53:16', 'fActWaterLevelMixTank1', '284.362823486328']
['2021-5-4 12:53:16', 'fActWaterLevelMixTank2', '298.269958496094']
['2021-5-4 12:53:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:53:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:53:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:53:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:53:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:53:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:53:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:53:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:53:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:53:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:53:16', 'DoVa_Co2', '0']
['2021-5-4 12:53:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:53:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:53:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:53:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:53:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:54:16', 'fKWhCounter', '3398.46459960938']
['2021-5-4 12:54:16', 'fActPhLevelMixTank1', '5.61387968063354']
['2021-5-4 12:54:16', 'fActEcLevelMixTank1', '2048.86010742188']
['2021-5-4 12:54:16', 'fActPhLevelMixTank2', '3.77788639068604']
['2021-5-4 12:54:16', 'fActEcLevelMixTank2', '1053.04113769531']
['2021-5-4 12:54:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:54:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:54:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:54:16', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 12:54:16', 'fActCo2ValMemo', '868']
['2021-5-4 12:54:16', 'fActWaterLevelMixTank1', '285.503631591797']
['2021-5-4 12:54:16', 'fActWaterLevelMixTank2', '280.940368652344']
['2021-5-4 12:54:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:54:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:54:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:54:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:54:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:54:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:54:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:54:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:54:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:54:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:54:16', 'DoVa_Co2', '0']
['2021-5-4 12:54:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:54:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:54:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:54:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']

['2021-5-4 12:54:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:54:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:55:16', 'fKWhCounter', '3398.66479492188']
['2021-5-4 12:55:16', 'fActPhLevelMixTank1', '5.56553840637207']
['2021-5-4 12:55:16', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 12:55:16', 'fActPhLevelMixTank2', '3.76641130447388']
['2021-5-4 12:55:16', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 12:55:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:55:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:55:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:55:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 12:55:16', 'fActCo2ValMemo', '870']
['2021-5-4 12:55:16', 'fActWaterLevelMixTank1', '278.658721923828']
['2021-5-4 12:55:16', 'fActWaterLevelMixTank2', '290.012603759766']
['2021-5-4 12:55:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:55:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:55:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:55:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:55:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:55:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:55:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:55:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:55:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:55:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:55:16', 'DoVa_Co2', '0']
['2021-5-4 12:55:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:55:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:55:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:55:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:55:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:56:16', 'fKWhCounter', '3398.86499023438']
['2021-5-4 12:56:16', 'fActPhLevelMixTank1', '5.56968879699707']
['2021-5-4 12:56:16', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 12:56:16', 'fActPhLevelMixTank2', '3.76689958572388']
['2021-5-4 12:56:16', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 12:56:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:56:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:56:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:56:16', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 12:56:16', 'fActCo2ValMemo', '870']
['2021-5-4 12:56:16', 'fActWaterLevelMixTank1', '272.248413085938']
['2021-5-4 12:56:16', 'fActWaterLevelMixTank2', '288.274200439453']
['2021-5-4 12:56:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:56:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:56:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:56:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:56:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:56:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:56:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:56:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:56:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:56:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:56:16', 'DoVa_Co2', '0']
['2021-5-4 12:56:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:56:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:56:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:56:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:56:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:57:16', 'fKWhCounter', '3399.06518554688']
['2021-5-4 12:57:16', 'fActPhLevelMixTank1', '5.56260871887207']
['2021-5-4 12:57:16', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 12:57:16', 'fActPhLevelMixTank2', '3.77397990226746']
['2021-5-4 12:57:16', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 12:57:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:57:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:57:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:57:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 12:57:16', 'fActCo2ValMemo', '870']
['2021-5-4 12:57:16', 'fActWaterLevelMixTank1', '273.416381835938']
['2021-5-4 12:57:16', 'fActWaterLevelMixTank2', '282.407135009766']
['2021-5-4 12:57:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:57:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:57:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:57:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:57:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:57:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:57:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:57:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:57:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:57:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:57:16', 'DoVa_Co2', '0']
['2021-5-4 12:57:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:57:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:57:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:57:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:57:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:58:16', 'fKWhCounter', '3399.16528320313']
['2021-5-4 12:58:16', 'fActPhLevelMixTank1', '5.56675910949707']
['2021-5-4 12:58:16', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 12:58:16', 'fActPhLevelMixTank2', '3.77861881256104']
['2021-5-4 12:58:16', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 12:58:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:58:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:58:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 12:58:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 12:58:16', 'fActCo2ValMemo', '869']
['2021-5-4 12:58:16', 'fActWaterLevelMixTank1', '273.633697509766']
['2021-5-4 12:58:16', 'fActWaterLevelMixTank2', '270.428527832031']
['2021-5-4 12:58:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:58:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:58:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:58:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:58:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:58:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:58:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:58:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:58:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:58:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:58:16', 'DoVa_Co2', '0']
['2021-5-4 12:58:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:58:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:58:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:58:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:58:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 12:59:16', 'fKWhCounter', '3399.36547851563']
['2021-5-4 12:59:16', 'fActPhLevelMixTank1', '5.56773567199707']
['2021-5-4 12:59:16', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 12:59:16', 'fActPhLevelMixTank2', '3.79351186752319']
['2021-5-4 12:59:16', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 12:59:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 12:59:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 12:59:16', 'fActTempValMemo', '21.7000007629395']

['2021-5-4 12:59:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 12:59:16', 'fActCo2ValMemo', '870']
['2021-5-4 12:59:16', 'fActWaterLevelMixTank1', '271.5693359375']
['2021-5-4 12:59:16', 'fActWaterLevelMixTank2', '290.392852783203']
['2021-5-4 12:59:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 12:59:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 12:59:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 12:59:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 12:59:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 12:59:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 12:59:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 12:59:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 12:59:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 12:59:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 12:59:16', 'DoVa_Co2', '0']
['2021-5-4 12:59:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 12:59:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 12:59:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 12:59:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 12:59:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:0:16', 'fKWhCounter', '3399.56567382813']
['2021-5-4 13:0:16', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 13:0:16', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 13:0:16', 'fActPhLevelMixTank2', '3.82964563369751']
['2021-5-4 13:0:16', 'fActEcLevelMixTank2', '1054.41455078125']
['2021-5-4 13:0:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:0:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:0:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 13:0:16', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 13:0:16', 'fActCo2ValMemo', '870']
['2021-5-4 13:0:16', 'fActWaterLevelMixTank1', '270.890289306641']
['2021-5-4 13:0:16', 'fActWaterLevelMixTank2', '289.985443115234']
['2021-5-4 13:0:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:0:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:0:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:0:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:0:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:0:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:0:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:0:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:0:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:0:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:0:16', 'DoVa_Co2', '0']
['2021-5-4 13:0:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:0:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:0:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:0:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:0:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:1:16', 'fKWhCounter', '3399.66577148438']
['2021-5-4 13:1:16', 'fActPhLevelMixTank1', '5.58580255508423']
['2021-5-4 13:1:16', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 13:1:16', 'fActPhLevelMixTank2', '3.82622766494751']
['2021-5-4 13:1:16', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 13:1:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:1:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:1:16', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 13:1:16', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 13:1:16', 'fActCo2ValMemo', '868']
['2021-5-4 13:1:16', 'fActWaterLevelMixTank1', '270.510009765625']
['2021-5-4 13:1:16', 'fActWaterLevelMixTank2', '289.63232421875']
['2021-5-4 13:1:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:1:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:1:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:1:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:1:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:1:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:1:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:1:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:1:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:1:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:1:16', 'DoVa_Co2', '0']
['2021-5-4 13:1:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:1:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:1:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:1:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:1:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:2:16', 'fKWhCounter', '3399.86596679688']
['2021-5-4 13:2:16', 'fActPhLevelMixTank1', '5.58751201629639']
['2021-5-4 13:2:16', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 13:2:16', 'fActPhLevelMixTank2', '3.81841492652893']
['2021-5-4 13:2:16', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 13:2:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:2:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:2:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:2:16', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 13:2:16', 'fActCo2ValMemo', '867']
['2021-5-4 13:2:16', 'fActWaterLevelMixTank1', '270.482849121094']
['2021-5-4 13:2:16', 'fActWaterLevelMixTank2', '289.849609375']
['2021-5-4 13:2:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:2:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:2:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:2:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:2:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:2:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:2:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:2:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:2:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:2:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:2:16', 'DoVa_Co2', '0']
['2021-5-4 13:2:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:2:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:2:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:2:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:2:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:3:16', 'fKWhCounter', '3399.96606445313']
['2021-5-4 13:3:16', 'fActPhLevelMixTank1', '5.58604717254639']
['2021-5-4 13:3:16', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 13:3:16', 'fActPhLevelMixTank2', '3.82012391090393']
['2021-5-4 13:3:16', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 13:3:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:3:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:3:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:3:16', 'fActRhValMemo', '52.5']
['2021-5-4 13:3:16', 'fActCo2ValMemo', '867']
['2021-5-4 13:3:16', 'fActWaterLevelMixTank1', '270.211242675781']
['2021-5-4 13:3:16', 'fActWaterLevelMixTank2', '289.034759521484']
['2021-5-4 13:3:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:3:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:3:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:3:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:3:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:3:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:3:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:3:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:3:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:3:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:3:16', 'DoVa_Co2', '0']
['2021-5-4 13:3:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:3:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:3:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:3:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:3:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:4:16', 'fKWhCounter', '3400.16625976563']
['2021-5-4 13:4:16', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 13:4:16', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 13:4:16', 'fActPhLevelMixTank2', '3.81914734840393']
['2021-5-4 13:4:16', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 13:4:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:4:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:4:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:4:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 13:4:16', 'fActCo2ValMemo', '870']
['2021-5-4 13:4:16', 'fActWaterLevelMixTank1', '270.428527832031']
['2021-5-4 13:4:16', 'fActWaterLevelMixTank2', '288.790283203125']
['2021-5-4 13:4:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:4:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:4:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:4:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:4:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:4:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:4:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:4:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:4:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:4:16', 'DoVa_IrrigateLevel_2_MT2', '0']

['2021-5-4 13:4:16', 'DoVa_Co2', '0']
['2021-5-4 13:4:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:4:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:4:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:4:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:4:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:5:16', 'fKWhCounter', '3400.26635742188']
['2021-5-4 13:5:16', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 13:5:16', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 13:5:16', 'fActPhLevelMixTank2', '3.81011390686035']
['2021-5-4 13:5:16', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 13:5:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:5:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:5:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:5:16', 'fActRhValMemo', '52']
['2021-5-4 13:5:16', 'fActCo2ValMemo', '866']
['2021-5-4 13:5:16', 'fActWaterLevelMixTank1', '270.835968017578']
['2021-5-4 13:5:16', 'fActWaterLevelMixTank2', '288.926086425781']
['2021-5-4 13:5:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:5:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:5:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:5:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:5:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:5:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:5:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:5:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:5:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:5:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:5:16', 'DoVa_Co2', '0']
['2021-5-4 13:5:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:5:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:5:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:5:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:5:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:6:16', 'fKWhCounter', '3400.46655273438']
['2021-5-4 13:6:16', 'fActPhLevelMixTank1', '5.57994318008423']
['2021-5-4 13:6:16', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 13:6:16', 'fActPhLevelMixTank2', '3.81719422340393']
['2021-5-4 13:6:16', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 13:6:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:6:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:6:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:6:16', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 13:6:16', 'fActCo2ValMemo', '863']
['2021-5-4 13:6:16', 'fActWaterLevelMixTank1', '269.070404052734']
['2021-5-4 13:6:16', 'fActWaterLevelMixTank2', '288.844604492188']
['2021-5-4 13:6:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:6:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:6:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:6:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:6:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:6:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:6:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:6:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:6:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:6:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:6:16', 'DoVa_Co2', '0']
['2021-5-4 13:6:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:6:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:6:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:6:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:6:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:7:16', 'fKWhCounter', '3400.56665039063']
['2021-5-4 13:7:16', 'fActPhLevelMixTank1', '5.58311700820923']
['2021-5-4 13:7:16', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 13:7:16', 'fActPhLevelMixTank2', '3.81646180152893']
['2021-5-4 13:7:16', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 13:7:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:7:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:7:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:7:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 13:7:16', 'fActCo2ValMemo', '860']
['2021-5-4 13:7:16', 'fActWaterLevelMixTank1', '271.623657226563']
['2021-5-4 13:7:16', 'fActWaterLevelMixTank2', '289.523681640625']
['2021-5-4 13:7:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:7:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:7:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:7:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:7:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:7:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:7:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:7:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:7:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:7:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:7:16', 'DoVa_Co2', '0']
['2021-5-4 13:7:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:7:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:7:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:7:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:7:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:8:16', 'fKWhCounter', '3400.66674804688']
['2021-5-4 13:8:16', 'fActPhLevelMixTank1', '5.57603693008423']
['2021-5-4 13:8:16', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 13:8:16', 'fActPhLevelMixTank2', '3.81450843811035']
['2021-5-4 13:8:16', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 13:8:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:8:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:8:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:8:16', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 13:8:16', 'fActCo2ValMemo', '860']
['2021-5-4 13:8:16', 'fActWaterLevelMixTank1', '272.900299072266']
['2021-5-4 13:8:16', 'fActWaterLevelMixTank2', '289.170562744141']
['2021-5-4 13:8:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:8:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:8:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:8:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:8:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:8:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:8:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:8:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:8:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:8:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:8:16', 'DoVa_Co2', '0']
['2021-5-4 13:8:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:8:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:8:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:8:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:8:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:9:16', 'fKWhCounter', '3400.86694335938']
['2021-5-4 13:9:16', 'fActPhLevelMixTank1', '5.57994318008423']
['2021-5-4 13:9:16', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 13:9:16', 'fActPhLevelMixTank2', '3.81939148902893']
['2021-5-4 13:9:16', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 13:9:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:9:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:9:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:9:16', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 13:9:16', 'fActCo2ValMemo', '859']
['2021-5-4 13:9:16', 'fActWaterLevelMixTank1', '273.280578613281']
['2021-5-4 13:9:16', 'fActWaterLevelMixTank2', '289.985443115234']
['2021-5-4 13:9:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:9:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:9:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:9:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:9:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:9:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:9:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:9:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:9:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:9:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:9:16', 'DoVa_Co2', '0']
['2021-5-4 13:9:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:9:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:9:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:9:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_3_Blue', '0']

['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:9:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:10:16', 'fKWhCounter', '3400.96704101563']
['2021-5-4 13:10:16', 'fActPhLevelMixTank1', '5.57530450820923']
['2021-5-4 13:10:16', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 13:10:16', 'fActPhLevelMixTank2', '3.81548500061035']
['2021-5-4 13:10:16', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 13:10:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:10:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:10:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:10:16', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 13:10:16', 'fActCo2ValMemo', '863']
['2021-5-4 13:10:16', 'fActWaterLevelMixTank1', '273.226257324219']
['2021-5-4 13:10:16', 'fActWaterLevelMixTank2', '289.578002929688']
['2021-5-4 13:10:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:10:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:10:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:10:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:10:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:10:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:10:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:10:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:10:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:10:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:10:16', 'DoVa_Co2', '0']
['2021-5-4 13:10:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:10:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:10:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:10:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:10:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:11:16', 'fKWhCounter', '3401.16723632813']
['2021-5-4 13:11:16', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 13:11:16', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 13:11:16', 'fActPhLevelMixTank2', '3.81157875061035']
['2021-5-4 13:11:16', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 13:11:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:11:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:11:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:11:16', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 13:11:16', 'fActCo2ValMemo', '861']
['2021-5-4 13:11:16', 'fActWaterLevelMixTank1', '273.008941650391']
['2021-5-4 13:11:16', 'fActWaterLevelMixTank2', '289.659484863281']
['2021-5-4 13:11:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:11:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:11:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:11:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:11:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:11:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:11:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:11:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:11:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:11:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:11:16', 'DoVa_Co2', '0']
['2021-5-4 13:11:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:11:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:11:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:11:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:11:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:12:16', 'fKWhCounter', '3401.26733398438']
['2021-5-4 13:12:16', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 13:12:16', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 13:12:16', 'fActPhLevelMixTank2', '3.82110047340393']
['2021-5-4 13:12:16', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 13:12:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:12:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:12:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:12:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 13:12:16', 'fActCo2ValMemo', '860']
['2021-5-4 13:12:16', 'fActWaterLevelMixTank1', '273.633697509766']
['2021-5-4 13:12:16', 'fActWaterLevelMixTank2', '289.985443115234']
['2021-5-4 13:12:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:12:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:12:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:12:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:12:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:12:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:12:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:12:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:12:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:12:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:12:16', 'DoVa_Co2', '0']
['2021-5-4 13:12:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:12:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:12:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:12:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:12:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:13:16', 'fKWhCounter', '3401.46752929688']
['2021-5-4 13:13:16', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 13:13:16', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 13:13:16', 'fActPhLevelMixTank2', '3.81304359436035']
['2021-5-4 13:13:16', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 13:13:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:13:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:13:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:13:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:13:16', 'fActCo2ValMemo', '861']
['2021-5-4 13:13:16', 'fActWaterLevelMixTank1', '273.497863769531']
['2021-5-4 13:13:16', 'fActWaterLevelMixTank2', '290.365692138672']
['2021-5-4 13:13:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:13:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:13:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:13:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:13:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:13:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:13:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:13:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:13:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:13:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:13:16', 'DoVa_Co2', '0']
['2021-5-4 13:13:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:13:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:13:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:13:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:13:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:14:16', 'fKWhCounter', '3401.56762695313']
['2021-5-4 13:14:16', 'fActPhLevelMixTank1', '5.59044170379639']
['2021-5-4 13:14:16', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 13:14:16', 'fActPhLevelMixTank2', '3.81206703186035']
['2021-5-4 13:14:16', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 13:14:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:14:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:14:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:14:16', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 13:14:16', 'fActCo2ValMemo', '861']
['2021-5-4 13:14:16', 'fActWaterLevelMixTank1', '273.008941650391']
['2021-5-4 13:14:16', 'fActWaterLevelMixTank2', '290.175567626953']
['2021-5-4 13:14:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:14:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:14:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:14:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:14:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:14:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:14:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:14:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:14:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:14:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:14:16', 'DoVa_Co2', '0']
['2021-5-4 13:14:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:14:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:14:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:14:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']

['2021-5-4 13:14:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:14:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:15:16', 'fKWhCounter', '3401.76782226563']
['2021-5-4 13:15:16', 'fActPhLevelMixTank1', '5.59923076629639']
['2021-5-4 13:15:16', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 13:15:16', 'fActPhLevelMixTank2', '3.81743836402893']
['2021-5-4 13:15:16', 'fActEcLevelMixTank2', '1047.39526367188']
['2021-5-4 13:15:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:15:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:15:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:15:16', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 13:15:16', 'fActCo2ValMemo', '860']
['2021-5-4 13:15:16', 'fActWaterLevelMixTank1', '273.660858154297']
['2021-5-4 13:15:16', 'fActWaterLevelMixTank2', '290.827453613281']
['2021-5-4 13:15:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:15:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:15:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:15:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:15:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:15:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:15:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:15:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:15:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:15:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:15:16', 'DoVa_Co2', '0']
['2021-5-4 13:15:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:15:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:15:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:15:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:15:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:16:16', 'fKWhCounter', '3401.86791992188']
['2021-5-4 13:16:16', 'fActPhLevelMixTank1', '5.59361553192139']
['2021-5-4 13:16:16', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 13:16:16', 'fActPhLevelMixTank2', '3.81402015686035']
['2021-5-4 13:16:16', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 13:16:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:16:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:16:16', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 13:16:16', 'fActRhValMemo', '52.5']
['2021-5-4 13:16:16', 'fActCo2ValMemo', '860']
['2021-5-4 13:16:16', 'fActWaterLevelMixTank1', '273.117614746094']
['2021-5-4 13:16:16', 'fActWaterLevelMixTank2', '290.501525878906']
['2021-5-4 13:16:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:16:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:16:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:16:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:16:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:16:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:16:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:16:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:16:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:16:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:16:16', 'DoVa_Co2', '0']
['2021-5-4 13:16:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:16:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:16:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:16:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:16:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:17:16', 'fKWhCounter', '3402.06811523438']
['2021-5-4 13:17:16', 'fActPhLevelMixTank1', '5.60240507125854']
['2021-5-4 13:17:16', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 13:17:16', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 13:17:16', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 13:17:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:17:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:17:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:17:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:17:16', 'fActCo2ValMemo', '858']
['2021-5-4 13:17:16', 'fActWaterLevelMixTank1', '274.747344970703']
['2021-5-4 13:17:16', 'fActWaterLevelMixTank2', '291.044769287109']
['2021-5-4 13:17:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:17:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:17:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:17:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:17:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:17:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:17:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:17:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:17:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:17:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:17:16', 'DoVa_Co2', '0']
['2021-5-4 13:17:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:17:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:17:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:17:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:17:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:18:16', 'fKWhCounter', '3402.16821289063']
['2021-5-4 13:18:16', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 13:18:16', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 13:18:16', 'fActPhLevelMixTank2', '3.82573938369751']
['2021-5-4 13:18:16', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 13:18:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:18:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:18:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:18:16', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 13:18:16', 'fActCo2ValMemo', '855']
['2021-5-4 13:18:16', 'fActWaterLevelMixTank1', '275.399230957031']
['2021-5-4 13:18:16', 'fActWaterLevelMixTank2', '291.044769287109']
['2021-5-4 13:18:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:18:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:18:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:18:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:18:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:18:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:18:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:18:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:18:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:18:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:18:16', 'DoVa_Co2', '0']
['2021-5-4 13:18:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:18:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:18:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:18:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:18:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:19:16', 'fKWhCounter', '3402.36840820313']
['2021-5-4 13:19:16', 'fActPhLevelMixTank1', '5.60924100875854']
['2021-5-4 13:19:16', 'fActEcLevelMixTank1', '2017.12084960938']
['2021-5-4 13:19:16', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 13:19:16', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 13:19:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:19:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:19:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:19:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 13:19:16', 'fActCo2ValMemo', '851']
['2021-5-4 13:19:16', 'fActWaterLevelMixTank1', '275.290588378906']
['2021-5-4 13:19:16', 'fActWaterLevelMixTank2', '291.479370117188']
['2021-5-4 13:19:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:19:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:19:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:19:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:19:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:19:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:19:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:19:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:19:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:19:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:19:16', 'DoVa_Co2', '0']
['2021-5-4 13:19:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:19:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:19:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:19:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']

['2021-5-4 13:19:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:19:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:20:16', 'fKWhCounter', '3402.46850585938']
['2021-5-4 13:20:16', 'fActPhLevelMixTank1', '5.60484647750854']
['2021-5-4 13:20:16', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 13:20:16', 'fActPhLevelMixTank2', '3.82720422744751']
['2021-5-4 13:20:16', 'fActEcLevelMixTank2', '1015.65600585938']
['2021-5-4 13:20:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:20:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:20:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:20:16', 'fActRhValMemo', '52.5']
['2021-5-4 13:20:16', 'fActCo2ValMemo', '853']
['2021-5-4 13:20:16', 'fActWaterLevelMixTank1', '275.317749023438']
['2021-5-4 13:20:16', 'fActWaterLevelMixTank2', '290.908966064453']
['2021-5-4 13:20:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:20:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:20:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:20:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:20:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:20:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:20:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:20:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:20:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:20:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:20:16', 'DoVa_Co2', '0']
['2021-5-4 13:20:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:20:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:20:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:20:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:20:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:21:16', 'fKWhCounter', '3402.66870117188']
['2021-5-4 13:21:16', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 13:21:16', 'fActEcLevelMixTank1', '2011.01721191406']
['2021-5-4 13:21:16', 'fActPhLevelMixTank2', '3.83159875869751']
['2021-5-4 13:21:16', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 13:21:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:21:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:21:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:21:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:21:16', 'fActCo2ValMemo', '848']
['2021-5-4 13:21:16', 'fActWaterLevelMixTank1', '276.051147460938']
['2021-5-4 13:21:16', 'fActWaterLevelMixTank2', '291.234893798828']
['2021-5-4 13:21:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:21:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:21:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:21:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:21:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:21:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:21:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:21:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:21:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:21:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:21:16', 'DoVa_Co2', '0']
['2021-5-4 13:21:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:21:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:21:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:21:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:21:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:22:16', 'fKWhCounter', '3402.76879882813']
['2021-5-4 13:22:16', 'fActPhLevelMixTank1', '5.60386991500854']
['2021-5-4 13:22:16', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 13:22:16', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 13:22:16', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 13:22:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:22:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:22:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:22:16', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 13:22:16', 'fActCo2ValMemo', '850']
['2021-5-4 13:22:16', 'fActWaterLevelMixTank1', '275.806671142578']
['2021-5-4 13:22:16', 'fActWaterLevelMixTank2', '290.5830078125']
['2021-5-4 13:22:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:22:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:22:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:22:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:22:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:22:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:22:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:22:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:22:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:22:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:22:16', 'DoVa_Co2', '0']
['2021-5-4 13:22:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:22:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:22:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:22:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:22:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:23:16', 'fKWhCounter', '3402.96899414063']
['2021-5-4 13:23:16', 'fActPhLevelMixTank1', '5.61192655563354']
['2021-5-4 13:23:16', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 13:23:16', 'fActPhLevelMixTank2', '3.83574938774109']
['2021-5-4 13:23:16', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 13:23:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:23:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:23:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:23:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:23:16', 'fActCo2ValMemo', '851']
['2021-5-4 13:23:16', 'fActWaterLevelMixTank1', '275.915313720703']
['2021-5-4 13:23:16', 'fActWaterLevelMixTank2', '291.452209472656']
['2021-5-4 13:23:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:23:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:23:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:23:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:23:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:23:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:23:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:23:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:23:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:23:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:23:16', 'DoVa_Co2', '0']
['2021-5-4 13:23:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:23:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:23:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:23:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:23:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:24:16', 'fKWhCounter', '3403.06909179688']
['2021-5-4 13:24:16', 'fActPhLevelMixTank1', '5.61314725875854']
['2021-5-4 13:24:16', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 13:24:16', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 13:24:16', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 13:24:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:24:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:24:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:24:16', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 13:24:16', 'fActCo2ValMemo', '849']
['2021-5-4 13:24:16', 'fActWaterLevelMixTank1', '276.458587646484']
['2021-5-4 13:24:16', 'fActWaterLevelMixTank2', '291.370727539063']
['2021-5-4 13:24:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:24:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:24:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:24:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:24:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:24:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:24:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:24:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:24:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:24:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:24:16', 'DoVa_Co2', '0']
['2021-5-4 13:24:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:24:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:24:16', 'DoVa_IrrigateLevel_3_MT2', '0']

['2021-5-4 13:24:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:24:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:25:16', 'fKWhCounter', '3403.26928710938']
['2021-5-4 13:25:16', 'fActPhLevelMixTank1', '5.61387968063354']
['2021-5-4 13:25:16', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 13:25:16', 'fActPhLevelMixTank2', '3.83257555961609']
['2021-5-4 13:25:16', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 13:25:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:25:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:25:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:25:16', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 13:25:16', 'fActCo2ValMemo', '851']
['2021-5-4 13:25:16', 'fActWaterLevelMixTank1', '276.214111328125']
['2021-5-4 13:25:16', 'fActWaterLevelMixTank2', '291.995452880859']
['2021-5-4 13:25:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:25:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:25:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:25:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:25:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:25:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:25:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:25:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:25:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:25:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:25:16', 'DoVa_Co2', '0']
['2021-5-4 13:25:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:25:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:25:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:25:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:25:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:26:16', 'fKWhCounter', '3403.36938476563']
['2021-5-4 13:26:16', 'fActPhLevelMixTank1', '5.61314725875854']
['2021-5-4 13:26:16', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 13:26:16', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 13:26:16', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 13:26:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:26:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:26:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:26:16', 'fActRhValMemo', '52']
['2021-5-4 13:26:16', 'fActCo2ValMemo', '846']
['2021-5-4 13:26:16', 'fActWaterLevelMixTank1', '276.621551513672']
['2021-5-4 13:26:16', 'fActWaterLevelMixTank2', '291.778137207031']
['2021-5-4 13:26:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:26:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:26:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:26:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:26:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:26:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:26:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:26:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:26:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:26:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:26:16', 'DoVa_Co2', '0']
['2021-5-4 13:26:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:26:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:26:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:26:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:26:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:27:16', 'fKWhCounter', '3403.46948242188']
['2021-5-4 13:27:16', 'fActPhLevelMixTank1', '5.6192512512207']
['2021-5-4 13:27:16', 'fActEcLevelMixTank1', '2001.0986328125']
['2021-5-4 13:27:16', 'fActPhLevelMixTank2', '3.83086633682251']
['2021-5-4 13:27:16', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 13:27:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:27:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:27:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:27:16', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 13:27:16', 'fActCo2ValMemo', '848']
['2021-5-4 13:27:16', 'fActWaterLevelMixTank1', '275.15478515625']
['2021-5-4 13:27:16', 'fActWaterLevelMixTank2', '291.941131591797']
['2021-5-4 13:27:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:27:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:27:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:27:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:27:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:27:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:27:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:27:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:27:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:27:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:27:16', 'DoVa_Co2', '0']
['2021-5-4 13:27:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:27:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:27:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:27:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:27:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:28:16', 'fKWhCounter', '3403.66967773438']
['2021-5-4 13:28:16', 'fActPhLevelMixTank1', '5.61656522750854']
['2021-5-4 13:28:16', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 13:28:16', 'fActPhLevelMixTank2', '3.83550524711609']
['2021-5-4 13:28:16', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 13:28:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:28:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:28:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:28:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:28:16', 'fActCo2ValMemo', '842']
['2021-5-4 13:28:16', 'fActWaterLevelMixTank1', '275.996826171875']
['2021-5-4 13:28:16', 'fActWaterLevelMixTank2', '291.696655273438']
['2021-5-4 13:28:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:28:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:28:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:28:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:28:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:28:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:28:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:28:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:28:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:28:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:28:16', 'DoVa_Co2', '0']
['2021-5-4 13:28:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:28:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:28:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:28:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:28:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:29:16', 'fKWhCounter', '3403.76977539063']
['2021-5-4 13:29:16', 'fActPhLevelMixTank1', '5.6309700012207']
['2021-5-4 13:29:16', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 13:29:16', 'fActPhLevelMixTank2', '3.83086633682251']
['2021-5-4 13:29:16', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 13:29:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:29:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:29:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:29:16', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 13:29:16', 'fActCo2ValMemo', '839']
['2021-5-4 13:29:16', 'fActWaterLevelMixTank1', '275.698028564453']
['2021-5-4 13:29:16', 'fActWaterLevelMixTank2', '291.941131591797']
['2021-5-4 13:29:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:29:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:29:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:29:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:29:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:29:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:29:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:29:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:29:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:29:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:29:16', 'DoVa_Co2', '0']
['2021-5-4 13:29:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:29:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:29:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:29:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 13:29:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:29:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:30:16', 'fKWhCounter', '3403.96997070313']
['2021-5-4 13:30:16', 'fActPhLevelMixTank1', '5.6270637512207']
['2021-5-4 13:30:16', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 13:30:16', 'fActPhLevelMixTank2', '3.83281970024109']
['2021-5-4 13:30:16', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 13:30:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:30:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:30:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:30:16', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 13:30:16', 'fActCo2ValMemo', '841']
['2021-5-4 13:30:16', 'fActWaterLevelMixTank1', '276.784515380859']
['2021-5-4 13:30:16', 'fActWaterLevelMixTank2', '291.370727539063']
['2021-5-4 13:30:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:30:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:30:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:30:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:30:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:30:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:30:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:30:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:30:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:30:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:30:16', 'DoVa_Co2', '0']
['2021-5-4 13:30:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:30:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:30:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:30:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:30:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:31:16', 'fKWhCounter', '3404.07006835938']
['2021-5-4 13:31:16', 'fActPhLevelMixTank1', '5.63585329055786']
['2021-5-4 13:31:16', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 13:31:16', 'fActPhLevelMixTank2', '3.83379626274109']
['2021-5-4 13:31:16', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 13:31:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:31:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:31:16', 'fActTempValMemo', '22']
['2021-5-4 13:31:16', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 13:31:16', 'fActCo2ValMemo', '839']
['2021-5-4 13:31:16', 'fActWaterLevelMixTank1', '277.137634277344']
['2021-5-4 13:31:16', 'fActWaterLevelMixTank2', '291.7509765625']
['2021-5-4 13:31:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:31:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:31:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:31:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:31:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:31:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:31:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:31:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:31:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:31:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:31:16', 'DoVa_Co2', '0']
['2021-5-4 13:31:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:31:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:31:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:31:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:31:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:32:16', 'fKWhCounter', '3404.27026367188']
['2021-5-4 13:32:16', 'fActPhLevelMixTank1', '5.63853883743286']
['2021-5-4 13:32:16', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 13:32:16', 'fActPhLevelMixTank2', '3.83111047744751']
['2021-5-4 13:32:16', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 13:32:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:32:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:32:16', 'fActTempValMemo', '22']
['2021-5-4 13:32:16', 'fActRhValMemo', '51.5']
['2021-5-4 13:32:16', 'fActCo2ValMemo', '840']
['2021-5-4 13:32:16', 'fActWaterLevelMixTank1', '275.915313720703']
['2021-5-4 13:32:16', 'fActWaterLevelMixTank2', '291.343536376953']
['2021-5-4 13:32:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:32:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:32:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:32:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:32:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:32:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:32:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:32:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:32:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:32:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:32:16', 'DoVa_Co2', '0']
['2021-5-4 13:32:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:32:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:32:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:32:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:32:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:33:16', 'fKWhCounter', '3404.37036132813']
['2021-5-4 13:33:16', 'fActPhLevelMixTank1', '5.64806032180786']
['2021-5-4 13:33:16', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 13:33:16', 'fActPhLevelMixTank2', '3.83721423149109']
['2021-5-4 13:33:16', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 13:33:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:33:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:33:16', 'fActTempValMemo', '22']
['2021-5-4 13:33:16', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 13:33:16', 'fActCo2ValMemo', '843']
['2021-5-4 13:33:16', 'fActWaterLevelMixTank1', '277.354919433594']
['2021-5-4 13:33:16', 'fActWaterLevelMixTank2', '291.560852050781']
['2021-5-4 13:33:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:33:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:33:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:33:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:33:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:33:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:33:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:33:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:33:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:33:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:33:16', 'DoVa_Co2', '0']
['2021-5-4 13:33:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:33:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:33:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:33:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:33:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:34:16', 'fKWhCounter', '3404.57055664063']
['2021-5-4 13:34:16', 'fActPhLevelMixTank1', '5.65196704864502']
['2021-5-4 13:34:16', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 13:34:16', 'fActPhLevelMixTank2', '3.83745837211609']
['2021-5-4 13:34:16', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 13:34:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:34:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:34:16', 'fActTempValMemo', '22']
['2021-5-4 13:34:16', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 13:34:16', 'fActCo2ValMemo', '841']
['2021-5-4 13:34:16', 'fActWaterLevelMixTank1', '276.567230224609']
['2021-5-4 13:34:16', 'fActWaterLevelMixTank2', '291.832458496094']
['2021-5-4 13:34:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:34:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:34:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:34:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:34:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:34:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:34:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:34:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:34:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:34:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:34:16', 'DoVa_Co2', '0']
['2021-5-4 13:34:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:34:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:34:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:34:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:34:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:35:16', 'fKWhCounter', '3404.67065429688']
['2021-5-4 13:35:16', 'fActPhLevelMixTank1', '5.65611743927002']
['2021-5-4 13:35:16', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 13:35:16', 'fActPhLevelMixTank2', '3.83526110649109']
['2021-5-4 13:35:16', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 13:35:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:35:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:35:16', 'fActTempValMemo', '22']
['2021-5-4 13:35:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:35:16', 'fActCo2ValMemo', '843']
['2021-5-4 13:35:16', 'fActWaterLevelMixTank1', '277.137634277344']
['2021-5-4 13:35:16', 'fActWaterLevelMixTank2', '291.316375732422']
['2021-5-4 13:35:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:35:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:35:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:35:16', 'DoPu_AddAcidMixTank_2', '0']

['2021-5-4 13:35:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:35:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:35:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:35:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:35:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:35:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:35:16', 'DoVa_Co2', '0']
['2021-5-4 13:35:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:35:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:35:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:35:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:35:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:36:16', 'fKWhCounter', '3404.87084960938']
['2021-5-4 13:36:16', 'fActPhLevelMixTank1', '5.65318775177002']
['2021-5-4 13:36:16', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 13:36:16', 'fActPhLevelMixTank2', '3.83721423149109']
['2021-5-4 13:36:16', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 13:36:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:36:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:36:16', 'fActTempValMemo', '22']
['2021-5-4 13:36:16', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 13:36:16', 'fActCo2ValMemo', '842']
['2021-5-4 13:36:16', 'fActWaterLevelMixTank1', '277.191955566406']
['2021-5-4 13:36:16', 'fActWaterLevelMixTank2', '291.7509765625']
['2021-5-4 13:36:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:36:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:36:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:36:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:36:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:36:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:36:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:36:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:36:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:36:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:36:16', 'DoVa_Co2', '0']
['2021-5-4 13:36:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:36:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:36:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:36:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:36:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:37:16', 'fKWhCounter', '3404.97094726563']
['2021-5-4 13:37:16', 'fActPhLevelMixTank1', '5.66197681427002']
['2021-5-4 13:37:16', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 13:37:16', 'fActPhLevelMixTank2', '3.83330798149109']
['2021-5-4 13:37:16', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 13:37:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:37:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:37:16', 'fActTempValMemo', '22']
['2021-5-4 13:37:16', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 13:37:16', 'fActCo2ValMemo', '841']
['2021-5-4 13:37:16', 'fActWaterLevelMixTank1', '277.626556396484']
['2021-5-4 13:37:16', 'fActWaterLevelMixTank2', '291.778137207031']
['2021-5-4 13:37:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:37:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:37:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:37:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:37:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:37:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:37:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:37:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:37:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:37:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:37:16', 'DoVa_Co2', '0']
['2021-5-4 13:37:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:37:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:37:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:37:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:37:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:38:16', 'fKWhCounter', '3405.17114257813']
['2021-5-4 13:38:16', 'fActPhLevelMixTank1', '5.66270923614502']
['2021-5-4 13:38:16', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 13:38:16', 'fActPhLevelMixTank2', '3.83526110649109']
['2021-5-4 13:38:16', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 13:38:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:38:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:38:16', 'fActTempValMemo', '22']
['2021-5-4 13:38:16', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 13:38:16', 'fActCo2ValMemo', '838']
['2021-5-4 13:38:16', 'fActWaterLevelMixTank1', '277.05615234375']
['2021-5-4 13:38:16', 'fActWaterLevelMixTank2', '291.778137207031']
['2021-5-4 13:38:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:38:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:38:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:38:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:38:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:38:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:38:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:38:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:38:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:38:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:38:16', 'DoVa_Co2', '0']
['2021-5-4 13:38:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:38:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:38:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:38:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:38:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:39:16', 'fKWhCounter', '3405.27124023438']
['2021-5-4 13:39:16', 'fActPhLevelMixTank1', '5.66588354110718']
['2021-5-4 13:39:16', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 13:39:16', 'fActPhLevelMixTank2', '3.83770251274109']
['2021-5-4 13:39:16', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 13:39:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:39:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:39:16', 'fActTempValMemo', '22']
['2021-5-4 13:39:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:39:16', 'fActCo2ValMemo', '835']
['2021-5-4 13:39:16', 'fActWaterLevelMixTank1', '278.387115478516']
['2021-5-4 13:39:16', 'fActWaterLevelMixTank2', '291.886810302734']
['2021-5-4 13:39:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:39:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:39:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:39:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:39:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:39:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:39:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:39:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:39:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:39:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:39:16', 'DoVa_Co2', '0']
['2021-5-4 13:39:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:39:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:39:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:39:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:39:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:40:16', 'fKWhCounter', '3405.47143554688']
['2021-5-4 13:40:16', 'fActPhLevelMixTank1', '5.66075611114502']
['2021-5-4 13:40:16', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 13:40:16', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 13:40:16', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 13:40:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:40:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:40:16', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 13:40:16', 'fActRhValMemo', '52.5']
['2021-5-4 13:40:16', 'fActCo2ValMemo', '834']
['2021-5-4 13:40:16', 'fActWaterLevelMixTank1', '278.033996582031']
['2021-5-4 13:40:16', 'fActWaterLevelMixTank2', '291.995452880859']
['2021-5-4 13:40:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:40:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:40:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:40:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:40:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:40:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:40:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:40:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:40:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:40:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:40:16', 'DoVa_Co2', '0']
['2021-5-4 13:40:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:40:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:40:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:40:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_1_Fred', '0']

['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:40:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:41:16', 'fKWhCounter', '3405.57153320313']
['2021-5-4 13:41:16', 'fActPhLevelMixTank1', '5.66759252548218']
['2021-5-4 13:41:16', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 13:41:16', 'fActPhLevelMixTank2', '3.84380626678467']
['2021-5-4 13:41:16', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 13:41:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:41:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:41:16', 'fActTempValMemo', '22']
['2021-5-4 13:41:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:41:16', 'fActCo2ValMemo', '836']
['2021-5-4 13:41:16', 'fActWaterLevelMixTank1', '276.974670410156']
['2021-5-4 13:41:16', 'fActWaterLevelMixTank2', '291.642333984375']
['2021-5-4 13:41:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:41:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:41:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:41:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:41:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:41:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:41:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:41:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:41:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:41:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:41:16', 'DoVa_Co2', '0']
['2021-5-4 13:41:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:41:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:41:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:41:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:41:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:42:16', 'fKWhCounter', '3405.77172851563']
['2021-5-4 13:42:16', 'fActPhLevelMixTank1', '5.66392993927002']
['2021-5-4 13:42:16', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 13:42:16', 'fActPhLevelMixTank2', '3.83867907524109']
['2021-5-4 13:42:16', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 13:42:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:42:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:42:16', 'fActTempValMemo', '22']
['2021-5-4 13:42:16', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 13:42:16', 'fActCo2ValMemo', '837']
['2021-5-4 13:42:16', 'fActWaterLevelMixTank1', '278.22412109375']
['2021-5-4 13:42:16', 'fActWaterLevelMixTank2', '292.511535644531']
['2021-5-4 13:42:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:42:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:42:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:42:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:42:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:42:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:42:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:42:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:42:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:42:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:42:16', 'DoVa_Co2', '0']
['2021-5-4 13:42:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:42:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:42:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:42:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:42:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:43:16', 'fKWhCounter', '3405.87182617188']
['2021-5-4 13:43:16', 'fActPhLevelMixTank1', '5.66734838485718']
['2021-5-4 13:43:16', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 13:43:16', 'fActPhLevelMixTank2', '3.84429454803467']
['2021-5-4 13:43:16', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 13:43:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:43:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:43:16', 'fActTempValMemo', '22']
['2021-5-4 13:43:16', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 13:43:16', 'fActCo2ValMemo', '834']
['2021-5-4 13:43:16', 'fActWaterLevelMixTank1', '277.572235107422']
['2021-5-4 13:43:16', 'fActWaterLevelMixTank2', '292.484375']
['2021-5-4 13:43:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:43:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:43:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:43:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:43:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:43:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:43:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:43:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:43:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:43:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:43:16', 'DoVa_Co2', '0']
['2021-5-4 13:43:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:43:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:43:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:43:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:43:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:44:16', 'fKWhCounter', '3406.07202148438']
['2021-5-4 13:44:16', 'fActPhLevelMixTank1', '5.66588354110718']
['2021-5-4 13:44:16', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 13:44:16', 'fActPhLevelMixTank2', '3.84502696990967']
['2021-5-4 13:44:16', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 13:44:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:44:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:44:16', 'fActTempValMemo', '22']
['2021-5-4 13:44:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:44:16', 'fActCo2ValMemo', '832']
['2021-5-4 13:44:16', 'fActWaterLevelMixTank1', '279.011840820313']
['2021-5-4 13:44:16', 'fActWaterLevelMixTank2', '292.946136474609']
['2021-5-4 13:44:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:44:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:44:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:44:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:44:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:44:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:44:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:44:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:44:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:44:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:44:16', 'DoVa_Co2', '0']
['2021-5-4 13:44:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:44:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:44:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:44:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:44:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:45:16', 'fKWhCounter', '3406.17211914063']
['2021-5-4 13:45:16', 'fActPhLevelMixTank1', '5.66490697860718']
['2021-5-4 13:45:16', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 13:45:16', 'fActPhLevelMixTank2', '3.84478282928467']
['2021-5-4 13:45:16', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 13:45:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:45:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:45:16', 'fActTempValMemo', '22']
['2021-5-4 13:45:16', 'fActRhValMemo', '52.5']
['2021-5-4 13:45:16', 'fActCo2ValMemo', '833']
['2021-5-4 13:45:16', 'fActWaterLevelMixTank1', '278.414276123047']
['2021-5-4 13:45:16', 'fActWaterLevelMixTank2', '292.484375']
['2021-5-4 13:45:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:45:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:45:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:45:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:45:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:45:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:45:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:45:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:45:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:45:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:45:16', 'DoVa_Co2', '0']
['2021-5-4 13:45:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:45:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:45:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:45:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_1_Blue', '0']

['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:45:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:46:16', 'fKWhCounter', '3406.27221679688']
['2021-5-4 13:46:16', 'fActPhLevelMixTank1', '5.67174291610718']
['2021-5-4 13:46:16', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 13:46:16', 'fActPhLevelMixTank2', '3.84502696990967']
['2021-5-4 13:46:16', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 13:46:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:46:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:46:16', 'fActTempValMemo', '22']
['2021-5-4 13:46:16', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:46:16', 'fActCo2ValMemo', '830']
['2021-5-4 13:46:16', 'fActWaterLevelMixTank1', '279.283447265625']
['2021-5-4 13:46:16', 'fActWaterLevelMixTank2', '292.728820800781']
['2021-5-4 13:46:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:46:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:46:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:46:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:46:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:46:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:46:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:46:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:46:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:46:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:46:16', 'DoVa_Co2', '0']
['2021-5-4 13:46:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:46:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:46:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:46:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:46:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:47:16', 'fKWhCounter', '3406.47241210938']
['2021-5-4 13:47:16', 'fActPhLevelMixTank1', '5.67369604110718']
['2021-5-4 13:47:16', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 13:47:16', 'fActPhLevelMixTank2', '3.84063243865967']
['2021-5-4 13:47:16', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 13:47:16', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:47:16', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:47:16', 'fActTempValMemo', '22']
['2021-5-4 13:47:16', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 13:47:16', 'fActCo2ValMemo', '829']
['2021-5-4 13:47:16', 'fActWaterLevelMixTank1', '279.690887451172']
['2021-5-4 13:47:16', 'fActWaterLevelMixTank2', '292.647338867188']
['2021-5-4 13:47:16', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:47:16', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:47:16', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:47:16', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:47:16', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:47:16', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:47:16', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:47:16', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:47:16', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:47:16', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:47:16', 'DoVa_Co2', '0']
['2021-5-4 13:47:16', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:47:16', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:47:16', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:47:16', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:47:16', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:48:17', 'fKWhCounter', '3406.57250976563']
['2021-5-4 13:48:17', 'fActPhLevelMixTank1', '5.67638158798218']
['2021-5-4 13:48:17', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 13:48:17', 'fActPhLevelMixTank2', '3.84331798553467']
['2021-5-4 13:48:17', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 13:48:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:48:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:48:17', 'fActTempValMemo', '22']
['2021-5-4 13:48:17', 'fActRhValMemo', '52.5']
['2021-5-4 13:48:17', 'fActCo2ValMemo', '830']
['2021-5-4 13:48:17', 'fActWaterLevelMixTank1', '279.908203125']
['2021-5-4 13:48:17', 'fActWaterLevelMixTank2', '292.810333251953']
['2021-5-4 13:48:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:48:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:48:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:48:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:48:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:48:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:48:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:48:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:48:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:48:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:48:17', 'DoVa_Co2', '0']
['2021-5-4 13:48:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:48:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:48:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:48:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:48:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:49:17', 'fKWhCounter', '3406.77270507813']
['2021-5-4 13:49:17', 'fActPhLevelMixTank1', '5.67027807235718']
['2021-5-4 13:49:17', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 13:49:17', 'fActPhLevelMixTank2', '3.83745837211609']
['2021-5-4 13:49:17', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 13:49:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:49:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:49:17', 'fActTempValMemo', '22']
['2021-5-4 13:49:17', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 13:49:17', 'fActCo2ValMemo', '830']
['2021-5-4 13:49:17', 'fActWaterLevelMixTank1', '278.604400634766']
['2021-5-4 13:49:17', 'fActWaterLevelMixTank2', '292.267059326172']
['2021-5-4 13:49:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:49:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:49:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:49:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:49:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:49:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:49:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:49:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:49:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:49:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:49:17', 'DoVa_Co2', '0']
['2021-5-4 13:49:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:49:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:49:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:49:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:49:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:50:17', 'fKWhCounter', '3406.87280273438']
['2021-5-4 13:50:17', 'fActPhLevelMixTank1', '5.67906713485718']
['2021-5-4 13:50:17', 'fActEcLevelMixTank1', '2028.87048339844']
['2021-5-4 13:50:17', 'fActPhLevelMixTank2', '3.84405040740967']
['2021-5-4 13:50:17', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 13:50:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:50:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:50:17', 'fActTempValMemo', '22']
['2021-5-4 13:50:17', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 13:50:17', 'fActCo2ValMemo', '828']
['2021-5-4 13:50:17', 'fActWaterLevelMixTank1', '279.853881835938']
['2021-5-4 13:50:17', 'fActWaterLevelMixTank2', '292.810333251953']
['2021-5-4 13:50:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:50:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:50:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:50:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:50:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:50:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:50:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:50:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:50:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:50:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:50:17', 'DoVa_Co2', '0']
['2021-5-4 13:50:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:50:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:50:17', 'DoVa_IrrigateLevel_3_MT2', '0']

['2021-5-4 13:50:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:50:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:51:17', 'fKWhCounter', '3407.07299804688']
['2021-5-4 13:51:17', 'fActPhLevelMixTank1', '5.67735815048218']
['2021-5-4 13:51:17', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 13:51:17', 'fActPhLevelMixTank2', '3.83916735649109']
['2021-5-4 13:51:17', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 13:51:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:51:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:51:17', 'fActTempValMemo', '22']
['2021-5-4 13:51:17', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 13:51:17', 'fActCo2ValMemo', '830']
['2021-5-4 13:51:17', 'fActWaterLevelMixTank1', '280.098327636719']
['2021-5-4 13:51:17', 'fActWaterLevelMixTank2', '293.462219238281']
['2021-5-4 13:51:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:51:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:51:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:51:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:51:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:51:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:51:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:51:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:51:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:51:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:51:17', 'DoVa_Co2', '0']
['2021-5-4 13:51:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:51:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:51:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:51:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:51:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:52:17', 'fKWhCounter', '3407.17309570313']
['2021-5-4 13:52:17', 'fActPhLevelMixTank1', '5.67882299423218']
['2021-5-4 13:52:17', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 13:52:17', 'fActPhLevelMixTank2', '3.84307384490967']
['2021-5-4 13:52:17', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 13:52:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:52:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:52:17', 'fActTempValMemo', '22']
['2021-5-4 13:52:17', 'fActRhValMemo', '53.2999992370605']
['2021-5-4 13:52:17', 'fActCo2ValMemo', '831']
['2021-5-4 13:52:17', 'fActWaterLevelMixTank1', '278.251281738281']
['2021-5-4 13:52:17', 'fActWaterLevelMixTank2', '292.620178222656']
['2021-5-4 13:52:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:52:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:52:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:52:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:52:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:52:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:52:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:52:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:52:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:52:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:52:17', 'DoVa_Co2', '0']
['2021-5-4 13:52:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:52:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:52:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:52:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:52:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:53:17', 'fKWhCounter', '3407.37329101563']
['2021-5-4 13:53:17', 'fActPhLevelMixTank1', '5.68272972106934']
['2021-5-4 13:53:17', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 13:53:17', 'fActPhLevelMixTank2', '3.84868931770325']
['2021-5-4 13:53:17', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 13:53:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:53:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:53:17', 'fActTempValMemo', '22']
['2021-5-4 13:53:17', 'fActRhValMemo', '53.0999984741211']
['2021-5-4 13:53:17', 'fActCo2ValMemo', '828']
['2021-5-4 13:53:17', 'fActWaterLevelMixTank1', '280.016845703125']
['2021-5-4 13:53:17', 'fActWaterLevelMixTank2', '293.163421630859']
['2021-5-4 13:53:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:53:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:53:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:53:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:53:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:53:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:53:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:53:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:53:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:53:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:53:17', 'DoVa_Co2', '0']
['2021-5-4 13:53:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:53:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:53:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:53:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:53:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:54:17', 'fKWhCounter', '3407.47338867188']
['2021-5-4 13:54:17', 'fActPhLevelMixTank1', '5.68126487731934']
['2021-5-4 13:54:17', 'fActEcLevelMixTank1', '2029.78601074219']
['2021-5-4 13:54:17', 'fActPhLevelMixTank2', '3.84698009490967']
['2021-5-4 13:54:17', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 13:54:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:54:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:54:17', 'fActTempValMemo', '22']
['2021-5-4 13:54:17', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 13:54:17', 'fActCo2ValMemo', '825']
['2021-5-4 13:54:17', 'fActWaterLevelMixTank1', '280.505767822266']
['2021-5-4 13:54:17', 'fActWaterLevelMixTank2', '293.543701171875']
['2021-5-4 13:54:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:54:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:54:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:54:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:54:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:54:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:54:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:54:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:54:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:54:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:54:17', 'DoVa_Co2', '0']
['2021-5-4 13:54:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:54:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:54:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:54:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:54:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:55:17', 'fKWhCounter', '3407.67358398438']
['2021-5-4 13:55:17', 'fActPhLevelMixTank1', '5.69176292419434']
['2021-5-4 13:55:17', 'fActEcLevelMixTank1', '2032.38012695313']
['2021-5-4 13:55:17', 'fActPhLevelMixTank2', '3.85064244270325']
['2021-5-4 13:55:17', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 13:55:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:55:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:55:17', 'fActTempValMemo', '22']
['2021-5-4 13:55:17', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 13:55:17', 'fActCo2ValMemo', '824']
['2021-5-4 13:55:17', 'fActWaterLevelMixTank1', '280.85888671875']
['2021-5-4 13:55:17', 'fActWaterLevelMixTank2', '293.788177490234']
['2021-5-4 13:55:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:55:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:55:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:55:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:55:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:55:17', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 13:55:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:55:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:55:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:55:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:55:17', 'DoVa_Co2', '0']
['2021-5-4 13:55:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:55:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:55:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:55:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:55:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:56:17', 'fKWhCounter', '3407.77368164063']
['2021-5-4 13:56:17', 'fActPhLevelMixTank1', '5.69176292419434']
['2021-5-4 13:56:17', 'fActEcLevelMixTank1', '2030.396484375']
['2021-5-4 13:56:17', 'fActPhLevelMixTank2', '3.84429454803467']
['2021-5-4 13:56:17', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 13:56:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:56:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:56:17', 'fActTempValMemo', '22']
['2021-5-4 13:56:17', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 13:56:17', 'fActCo2ValMemo', '824']
['2021-5-4 13:56:17', 'fActWaterLevelMixTank1', '279.745208740234']
['2021-5-4 13:56:17', 'fActWaterLevelMixTank2', '293.054779052734']
['2021-5-4 13:56:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:56:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:56:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:56:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:56:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:56:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:56:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:56:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:56:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:56:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:56:17', 'DoVa_Co2', '0']
['2021-5-4 13:56:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:56:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:56:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:56:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:56:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:57:17', 'fKWhCounter', '3407.97387695313']
['2021-5-4 13:57:17', 'fActPhLevelMixTank1', '5.69518089294434']
['2021-5-4 13:57:17', 'fActEcLevelMixTank1', '2031.46459960938']
['2021-5-4 13:57:17', 'fActPhLevelMixTank2', '3.84966588020325']
['2021-5-4 13:57:17', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 13:57:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:57:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:57:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 13:57:17', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 13:57:17', 'fActCo2ValMemo', '823']
['2021-5-4 13:57:17', 'fActWaterLevelMixTank1', '280.723052978516']
['2021-5-4 13:57:17', 'fActWaterLevelMixTank2', '293.760986328125']
['2021-5-4 13:57:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:57:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:57:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:57:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:57:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:57:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:57:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:57:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:57:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:57:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:57:17', 'DoVa_Co2', '0']
['2021-5-4 13:57:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:57:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:57:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:57:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:57:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:58:17', 'fKWhCounter', '3408.07397460938']
['2021-5-4 13:58:17', 'fActPhLevelMixTank1', '5.69811105728149']
['2021-5-4 13:58:17', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 13:58:17', 'fActPhLevelMixTank2', '3.85552549362183']
['2021-5-4 13:58:17', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 13:58:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:58:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:58:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 13:58:17', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 13:58:17', 'fActCo2ValMemo', '824']
['2021-5-4 13:58:17', 'fActWaterLevelMixTank1', '280.723052978516']
['2021-5-4 13:58:17', 'fActWaterLevelMixTank2', '293.43505859375']
['2021-5-4 13:58:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:58:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:58:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:58:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:58:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:58:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:58:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:58:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:58:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:58:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:58:17', 'DoVa_Co2', '0']
['2021-5-4 13:58:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:58:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:58:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:58:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:58:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 13:59:17', 'fKWhCounter', '3408.27416992188']
['2021-5-4 13:59:17', 'fActPhLevelMixTank1', '5.61290311813354']
['2021-5-4 13:59:17', 'fActEcLevelMixTank1', '2043.97717285156']
['2021-5-4 13:59:17', 'fActPhLevelMixTank2', '3.77007365226746']
['2021-5-4 13:59:17', 'fActEcLevelMixTank2', '1043.12268066406']
['2021-5-4 13:59:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 13:59:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 13:59:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 13:59:17', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 13:59:17', 'fActCo2ValMemo', '822']
['2021-5-4 13:59:17', 'fActWaterLevelMixTank1', '280.397125244141']
['2021-5-4 13:59:17', 'fActWaterLevelMixTank2', '316.930511474609']
['2021-5-4 13:59:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 13:59:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 13:59:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 13:59:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 13:59:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 13:59:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 13:59:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 13:59:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 13:59:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 13:59:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 13:59:17', 'DoVa_Co2', '0']
['2021-5-4 13:59:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 13:59:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 13:59:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 13:59:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 13:59:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 13:59:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:0:17', 'fKWhCounter', '3408.47436523438']
['2021-5-4 14:0:17', 'fActPhLevelMixTank1', '5.55772590637207']
['2021-5-4 14:0:17', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 14:0:17', 'fActPhLevelMixTank2', '3.7612841129303']
['2021-5-4 14:0:17', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 14:0:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:0:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:0:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:0:17', 'fActRhValMemo', '52']
['2021-5-4 14:0:17', 'fActCo2ValMemo', '820']
['2021-5-4 14:0:17', 'fActWaterLevelMixTank1', '278.713043212891']
['2021-5-4 14:0:17', 'fActWaterLevelMixTank2', '303.349304199219']
['2021-5-4 14:0:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:0:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:0:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:0:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:0:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:0:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:0:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:0:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:0:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:0:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:0:17', 'DoVa_Co2', '0']
['2021-5-4 14:0:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:0:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:0:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:0:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:0:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:1:17', 'fKWhCounter', '3408.57446289063']
['2021-5-4 14:1:17', 'fActPhLevelMixTank1', '5.56895637512207']
['2021-5-4 14:1:17', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 14:1:17', 'fActPhLevelMixTank2', '3.76299333572388']
['2021-5-4 14:1:17', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 14:1:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:1:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:1:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:1:17', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 14:1:17', 'fActCo2ValMemo', '818']
['2021-5-4 14:1:17', 'fActWaterLevelMixTank1', '269.803802490234']
['2021-5-4 14:1:17', 'fActWaterLevelMixTank2', '298.215637207031']
['2021-5-4 14:1:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:1:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:1:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:1:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:1:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:1:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:1:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:1:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:1:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:1:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:1:17', 'DoVa_Co2', '0']
['2021-5-4 14:1:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:1:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:1:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:1:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:1:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:2:17', 'fKWhCounter', '3408.77465820313']
['2021-5-4 14:2:17', 'fActPhLevelMixTank1', '5.56456184387207']
['2021-5-4 14:2:17', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 14:2:17', 'fActPhLevelMixTank2', '3.76934099197388']
['2021-5-4 14:2:17', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 14:2:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:2:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:2:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:2:17', 'fActRhValMemo', '52']
['2021-5-4 14:2:17', 'fActCo2ValMemo', '816']
['2021-5-4 14:2:17', 'fActWaterLevelMixTank1', '268.011077880859']
['2021-5-4 14:2:17', 'fActWaterLevelMixTank2', '302.398620605469']
['2021-5-4 14:2:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:2:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:2:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:2:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:2:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:2:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:2:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:2:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:2:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:2:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:2:17', 'DoVa_Co2', '0']
['2021-5-4 14:2:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:2:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:2:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:2:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:2:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:3:17', 'fKWhCounter', '3408.97485351563']
['2021-5-4 14:3:17', 'fActPhLevelMixTank1', '5.56895637512207']
['2021-5-4 14:3:17', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 14:3:17', 'fActPhLevelMixTank2', '3.76519060134888']
['2021-5-4 14:3:17', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 14:3:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:3:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:3:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:3:17', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 14:3:17', 'fActCo2ValMemo', '815']
['2021-5-4 14:3:17', 'fActWaterLevelMixTank1', '270.564331054688']
['2021-5-4 14:3:17', 'fActWaterLevelMixTank2', '264.371307373047']
['2021-5-4 14:3:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:3:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:3:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:3:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:3:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:3:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:3:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:3:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:3:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:3:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:3:17', 'DoVa_Co2', '0']
['2021-5-4 14:3:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:3:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:3:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:3:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:3:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:4:17', 'fKWhCounter', '3409.17504882813']
['2021-5-4 14:4:17', 'fActPhLevelMixTank1', '5.57237482070923']
['2021-5-4 14:4:17', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 14:4:17', 'fActPhLevelMixTank2', '3.79375600814819']
['2021-5-4 14:4:17', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 14:4:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:4:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:4:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:4:17', 'fActRhValMemo', '52.5']
['2021-5-4 14:4:17', 'fActCo2ValMemo', '819']
['2021-5-4 14:4:17', 'fActWaterLevelMixTank1', '269.885284423828']
['2021-5-4 14:4:17', 'fActWaterLevelMixTank2', '285.883911132813']
['2021-5-4 14:4:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:4:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:4:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:4:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:4:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:4:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:4:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:4:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:4:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:4:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:4:17', 'DoVa_Co2', '0']
['2021-5-4 14:4:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:4:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:4:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:4:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:4:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:5:17', 'fKWhCounter', '3409.27514648438']
['2021-5-4 14:5:17', 'fActPhLevelMixTank1', '5.57164239883423']
['2021-5-4 14:5:17', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 14:5:17', 'fActPhLevelMixTank2', '3.81865906715393']
['2021-5-4 14:5:17', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 14:5:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:5:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:5:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:5:17', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 14:5:17', 'fActCo2ValMemo', '820']
['2021-5-4 14:5:17', 'fActWaterLevelMixTank1', '269.016082763672']
['2021-5-4 14:5:17', 'fActWaterLevelMixTank2', '285.422149658203']
['2021-5-4 14:5:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:5:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:5:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:5:17', 'DoPu_AddAcidMixTank_2', '0']

['2021-5-4 14:5:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:5:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:5:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:5:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:5:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:5:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:5:17', 'DoVa_Co2', '0']
['2021-5-4 14:5:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:5:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:5:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:5:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:5:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:6:17', 'fKWhCounter', '3409.47534179688']
['2021-5-4 14:6:17', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 14:6:17', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 14:6:17', 'fActPhLevelMixTank2', '3.81841492652893']
['2021-5-4 14:6:17', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 14:6:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:6:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:6:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:6:17', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 14:6:17', 'fActCo2ValMemo', '820']
['2021-5-4 14:6:17', 'fActWaterLevelMixTank1', '268.228363037109']
['2021-5-4 14:6:17', 'fActWaterLevelMixTank2', '285.123382568359']
['2021-5-4 14:6:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:6:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:6:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:6:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:6:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:6:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:6:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:6:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:6:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:6:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:6:17', 'DoVa_Co2', '0']
['2021-5-4 14:6:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:6:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:6:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:6:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:6:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:7:17', 'fKWhCounter', '3409.57543945313']
['2021-5-4 14:7:17', 'fActPhLevelMixTank1', '5.57530450820923']
['2021-5-4 14:7:17', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 14:7:17', 'fActPhLevelMixTank2', '3.81646180152893']
['2021-5-4 14:7:17', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 14:7:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:7:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:7:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:7:17', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 14:7:17', 'fActCo2ValMemo', '819']
['2021-5-4 14:7:17', 'fActWaterLevelMixTank1', '267.494995117188']
['2021-5-4 14:7:17', 'fActWaterLevelMixTank2', '284.715942382813']
['2021-5-4 14:7:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:7:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:7:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:7:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:7:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:7:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:7:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:7:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:7:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:7:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:7:17', 'DoVa_Co2', '0']
['2021-5-4 14:7:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:7:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:7:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:7:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:7:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:8:17', 'fKWhCounter', '3409.67553710938']
['2021-5-4 14:8:17', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 14:8:17', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 14:8:17', 'fActPhLevelMixTank2', '3.81011390686035']
['2021-5-4 14:8:17', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 14:8:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:8:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:8:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:8:17', 'fActRhValMemo', '51.5']
['2021-5-4 14:8:17', 'fActCo2ValMemo', '820']
['2021-5-4 14:8:17', 'fActWaterLevelMixTank1', '268.28271484375']
['2021-5-4 14:8:17', 'fActWaterLevelMixTank2', '284.389984130859']
['2021-5-4 14:8:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:8:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:8:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:8:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:8:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:8:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:8:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:8:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:8:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:8:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:8:17', 'DoVa_Co2', '0']
['2021-5-4 14:8:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:8:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:8:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:8:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:8:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:9:17', 'fKWhCounter', '3409.87573242188']
['2021-5-4 14:9:17', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 14:9:17', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 14:9:17', 'fActPhLevelMixTank2', '3.81255531311035']
['2021-5-4 14:9:17', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 14:9:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:9:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:9:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:9:17', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 14:9:17', 'fActCo2ValMemo', '820']
['2021-5-4 14:9:17', 'fActWaterLevelMixTank1', '269.260559082031']
['2021-5-4 14:9:17', 'fActWaterLevelMixTank2', '285.041870117188']
['2021-5-4 14:9:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:9:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:9:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:9:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:9:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:9:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:9:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:9:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:9:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:9:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:9:17', 'DoVa_Co2', '0']
['2021-5-4 14:9:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:9:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:9:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:9:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:9:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:10:17', 'fKWhCounter', '3409.97583007813']
['2021-5-4 14:10:17', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 14:10:17', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 14:10:17', 'fActPhLevelMixTank2', '3.80693984031677']
['2021-5-4 14:10:17', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 14:10:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:10:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:10:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:10:17', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 14:10:17', 'fActCo2ValMemo', '817']
['2021-5-4 14:10:17', 'fActWaterLevelMixTank1', '269.532165527344']
['2021-5-4 14:10:17', 'fActWaterLevelMixTank2', '284.797424316406']
['2021-5-4 14:10:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:10:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:10:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:10:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:10:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:10:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:10:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:10:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:10:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:10:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:10:17', 'DoVa_Co2', '0']
['2021-5-4 14:10:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:10:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:10:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:10:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_3_Blue', '0']

['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:10:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:11:17', 'fKWhCounter', '3410.17602539063']
['2021-5-4 14:11:17', 'fActPhLevelMixTank1', '5.57506036758423']
['2021-5-4 14:11:17', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 14:11:17', 'fActPhLevelMixTank2', '3.80816054344177']
['2021-5-4 14:11:17', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 14:11:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:11:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:11:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:11:17', 'fActRhValMemo', '51.5']
['2021-5-4 14:11:17', 'fActCo2ValMemo', '817']
['2021-5-4 14:11:17', 'fActWaterLevelMixTank1', '268.445678710938']
['2021-5-4 14:11:17', 'fActWaterLevelMixTank2', '284.824584960938']
['2021-5-4 14:11:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:11:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:11:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:11:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:11:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:11:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:11:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:11:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:11:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:11:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:11:17', 'DoVa_Co2', '0']
['2021-5-4 14:11:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:11:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:11:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:11:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:11:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:12:17', 'fKWhCounter', '3410.27612304688']
['2021-5-4 14:12:17', 'fActPhLevelMixTank1', '5.57530450820923']
['2021-5-4 14:12:17', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 14:12:17', 'fActPhLevelMixTank2', '3.80449843406677']
['2021-5-4 14:12:17', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 14:12:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:12:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:12:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:12:17', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 14:12:17', 'fActCo2ValMemo', '814']
['2021-5-4 14:12:17', 'fActWaterLevelMixTank1', '269.776641845703']
['2021-5-4 14:12:17', 'fActWaterLevelMixTank2', '285.123382568359']
['2021-5-4 14:12:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:12:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:12:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:12:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:12:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:12:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:12:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:12:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:12:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:12:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:12:17', 'DoVa_Co2', '0']
['2021-5-4 14:12:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:12:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:12:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:12:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:12:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:13:17', 'fKWhCounter', '3410.47631835938']
['2021-5-4 14:13:17', 'fActPhLevelMixTank1', '5.57823419570923']
['2021-5-4 14:13:17', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 14:13:17', 'fActPhLevelMixTank2', '3.80986976623535']
['2021-5-4 14:13:17', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 14:13:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:13:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:13:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:13:17', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 14:13:17', 'fActCo2ValMemo', '813']
['2021-5-4 14:13:17', 'fActWaterLevelMixTank1', '270.156890869141']
['2021-5-4 14:13:17', 'fActWaterLevelMixTank2', '285.150543212891']
['2021-5-4 14:13:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:13:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:13:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:13:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:13:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:13:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:13:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:13:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:13:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:13:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:13:17', 'DoVa_Co2', '0']
['2021-5-4 14:13:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:13:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:13:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:13:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:13:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:14:17', 'fKWhCounter', '3410.57641601563']
['2021-5-4 14:14:17', 'fActPhLevelMixTank1', '5.57603693008423']
['2021-5-4 14:14:17', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 14:14:17', 'fActPhLevelMixTank2', '3.81109046936035']
['2021-5-4 14:14:17', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 14:14:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:14:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:14:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:14:17', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 14:14:17', 'fActCo2ValMemo', '811']
['2021-5-4 14:14:17', 'fActWaterLevelMixTank1', '269.016082763672']
['2021-5-4 14:14:17', 'fActWaterLevelMixTank2', '285.014709472656']
['2021-5-4 14:14:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:14:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:14:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:14:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:14:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:14:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:14:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:14:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:14:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:14:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:14:17', 'DoVa_Co2', '0']
['2021-5-4 14:14:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:14:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:14:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:14:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:14:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:15:17', 'fKWhCounter', '3410.77661132813']
['2021-5-4 14:15:17', 'fActPhLevelMixTank1', '5.58018732070923']
['2021-5-4 14:15:17', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 14:15:17', 'fActPhLevelMixTank2', '3.81255531311035']
['2021-5-4 14:15:17', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 14:15:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:15:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:15:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:15:17', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 14:15:17', 'fActCo2ValMemo', '814']
['2021-5-4 14:15:17', 'fActWaterLevelMixTank1', '269.477844238281']
['2021-5-4 14:15:17', 'fActWaterLevelMixTank2', '285.232025146484']
['2021-5-4 14:15:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:15:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:15:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:15:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:15:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:15:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:15:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:15:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:15:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:15:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:15:17', 'DoVa_Co2', '0']
['2021-5-4 14:15:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:15:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:15:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:15:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:15:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']

['2021-5-4 14:16:17', 'fKWhCounter', '3410.87670898438']
['2021-5-4 14:16:17', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 14:16:17', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 14:16:17', 'fActPhLevelMixTank2', '3.81060218811035']
['2021-5-4 14:16:17', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 14:16:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:16:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:16:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:16:17', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 14:16:17', 'fActCo2ValMemo', '810']
['2021-5-4 14:16:17', 'fActWaterLevelMixTank1', '271.324890136719']
['2021-5-4 14:16:17', 'fActWaterLevelMixTank2', '285.449310302734']
['2021-5-4 14:16:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:16:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:16:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:16:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:16:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:16:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:16:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:16:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:16:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:16:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:16:17', 'DoVa_Co2', '0']
['2021-5-4 14:16:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:16:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:16:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:16:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:16:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:17:17', 'fKWhCounter', '3411.07690429688']
['2021-5-4 14:17:17', 'fActPhLevelMixTank1', '5.58555841445923']
['2021-5-4 14:17:17', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 14:17:17', 'fActPhLevelMixTank2', '3.80498671531677']
['2021-5-4 14:17:17', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 14:17:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:17:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:17:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:17:17', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 14:17:17', 'fActCo2ValMemo', '813']
['2021-5-4 14:17:17', 'fActWaterLevelMixTank1', '270.319885253906']
['2021-5-4 14:17:17', 'fActWaterLevelMixTank2', '285.259185791016']
['2021-5-4 14:17:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:17:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:17:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:17:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:17:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:17:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:17:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:17:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:17:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:17:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:17:17', 'DoVa_Co2', '0']
['2021-5-4 14:17:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:17:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:17:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:17:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:17:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:18:17', 'fKWhCounter', '3411.17700195313']
['2021-5-4 14:18:17', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 14:18:17', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 14:18:17', 'fActPhLevelMixTank2', '3.81475257873535']
['2021-5-4 14:18:17', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 14:18:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:18:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:18:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:18:17', 'fActRhValMemo', '51.5']
['2021-5-4 14:18:17', 'fActCo2ValMemo', '810']
['2021-5-4 14:18:17', 'fActWaterLevelMixTank1', '272.357055664063']
['2021-5-4 14:18:17', 'fActWaterLevelMixTank2', '285.666625976563']
['2021-5-4 14:18:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:18:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:18:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:18:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:18:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:18:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:18:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:18:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:18:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:18:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:18:17', 'DoVa_Co2', '0']
['2021-5-4 14:18:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:18:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:18:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:18:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:18:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:19:17', 'fKWhCounter', '3411.37719726563']
['2021-5-4 14:19:17', 'fActPhLevelMixTank1', '5.58848857879639']
['2021-5-4 14:19:17', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 14:19:17', 'fActPhLevelMixTank2', '3.80889320373535']
['2021-5-4 14:19:17', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 14:19:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:19:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:19:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:19:17', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 14:19:17', 'fActCo2ValMemo', '811']
['2021-5-4 14:19:17', 'fActWaterLevelMixTank1', '272.275573730469']
['2021-5-4 14:19:17', 'fActWaterLevelMixTank2', '285.775268554688']
['2021-5-4 14:19:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:19:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:19:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:19:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:19:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:19:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:19:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:19:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:19:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:19:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:19:17', 'DoVa_Co2', '0']
['2021-5-4 14:19:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:19:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:19:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:19:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:19:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:20:17', 'fKWhCounter', '3411.47729492188']
['2021-5-4 14:20:17', 'fActPhLevelMixTank1', '5.60118389129639']
['2021-5-4 14:20:17', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 14:20:17', 'fActPhLevelMixTank2', '3.81304359436035']
['2021-5-4 14:20:17', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 14:20:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:20:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:20:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:20:17', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 14:20:17', 'fActCo2ValMemo', '813']
['2021-5-4 14:20:17', 'fActWaterLevelMixTank1', '270.727325439453']
['2021-5-4 14:20:17', 'fActWaterLevelMixTank2', '286.291351318359']
['2021-5-4 14:20:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:20:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:20:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:20:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:20:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:20:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:20:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:20:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:20:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:20:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:20:17', 'DoVa_Co2', '0']
['2021-5-4 14:20:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:20:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:20:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:20:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:20:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:21:17', 'fKWhCounter', '3411.67749023438']
['2021-5-4 14:21:17', 'fActPhLevelMixTank1', '5.60240507125854']
['2021-5-4 14:21:17', 'fActEcLevelMixTank1', '2015.74755859375']
['2021-5-4 14:21:17', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 14:21:17', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 14:21:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:21:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:21:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:21:17', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 14:21:17', 'fActCo2ValMemo', '812']
['2021-5-4 14:21:17', 'fActWaterLevelMixTank1', '271.976776123047']
['2021-5-4 14:21:17', 'fActWaterLevelMixTank2', '286.209869384766']
['2021-5-4 14:21:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:21:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:21:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:21:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:21:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:21:17', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 14:21:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:21:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:21:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:21:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:21:17', 'DoVa_Co2', '0']
['2021-5-4 14:21:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:21:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:21:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:21:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:21:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:22:17', 'fKWhCounter', '3411.77758789063']
['2021-5-4 14:22:17', 'fActPhLevelMixTank1', '5.60509061813354']
['2021-5-4 14:22:17', 'fActEcLevelMixTank1', '2016.51049804688']
['2021-5-4 14:22:17', 'fActPhLevelMixTank2', '3.82012391090393']
['2021-5-4 14:22:17', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 14:22:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:22:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:22:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:22:17', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 14:22:17', 'fActCo2ValMemo', '809']
['2021-5-4 14:22:17', 'fActWaterLevelMixTank1', '271.650848388672']
['2021-5-4 14:22:17', 'fActWaterLevelMixTank2', '286.264190673828']
['2021-5-4 14:22:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:22:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:22:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:22:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:22:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:22:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:22:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:22:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:22:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:22:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:22:17', 'DoVa_Co2', '0']
['2021-5-4 14:22:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:22:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:22:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:22:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:22:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:23:17', 'fKWhCounter', '3411.87768554688']
['2021-5-4 14:23:17', 'fActPhLevelMixTank1', '5.60289335250854']
['2021-5-4 14:23:17', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 14:23:17', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 14:23:17', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 14:23:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:23:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:23:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:23:17', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 14:23:17', 'fActCo2ValMemo', '810']
['2021-5-4 14:23:17', 'fActWaterLevelMixTank1', '272.492858886719']
['2021-5-4 14:23:17', 'fActWaterLevelMixTank2', '286.399993896484']
['2021-5-4 14:23:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:23:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:23:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:23:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:23:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:23:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:23:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:23:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:23:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:23:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:23:17', 'DoVa_Co2', '0']
['2021-5-4 14:23:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:23:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:23:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:23:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:23:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:24:17', 'fKWhCounter', '3412.07788085938']
['2021-5-4 14:24:17', 'fActPhLevelMixTank1', '5.61094999313354']
['2021-5-4 14:24:17', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 14:24:17', 'fActPhLevelMixTank2', '3.82158875465393']
['2021-5-4 14:24:17', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 14:24:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:24:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:24:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:24:17', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 14:24:17', 'fActCo2ValMemo', '808']
['2021-5-4 14:24:17', 'fActWaterLevelMixTank1', '273.552185058594']
['2021-5-4 14:24:17', 'fActWaterLevelMixTank2', '286.427154541016']
['2021-5-4 14:24:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:24:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:24:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:24:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:24:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:24:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:24:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:24:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:24:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:24:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:24:17', 'DoVa_Co2', '0']
['2021-5-4 14:24:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:24:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:24:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:24:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:24:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:25:17', 'fKWhCounter', '3412.17797851563']
['2021-5-4 14:25:17', 'fActPhLevelMixTank1', '5.60899686813354']
['2021-5-4 14:25:17', 'fActEcLevelMixTank1', '2013.45861816406']
['2021-5-4 14:25:17', 'fActPhLevelMixTank2', '3.81841492652893']
['2021-5-4 14:25:17', 'fActEcLevelMixTank2', '1028.01599121094']
['2021-5-4 14:25:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:25:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:25:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:25:17', 'fActRhValMemo', '51.5']
['2021-5-4 14:25:17', 'fActCo2ValMemo', '807']
['2021-5-4 14:25:17', 'fActWaterLevelMixTank1', '273.850982666016']
['2021-5-4 14:25:17', 'fActWaterLevelMixTank2', '286.99755859375']
['2021-5-4 14:25:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:25:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:25:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:25:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:25:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:25:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:25:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:25:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:25:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:25:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:25:17', 'DoVa_Co2', '0']
['2021-5-4 14:25:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:25:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:25:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:25:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:25:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:26:17', 'fKWhCounter', '3412.37817382813']
['2021-5-4 14:26:17', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 14:26:17', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 14:26:17', 'fActPhLevelMixTank2', '3.82671594619751']
['2021-5-4 14:26:17', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 14:26:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:26:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:26:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:26:17', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 14:26:17', 'fActCo2ValMemo', '809']
['2021-5-4 14:26:17', 'fActWaterLevelMixTank1', '274.122619628906']
['2021-5-4 14:26:17', 'fActWaterLevelMixTank2', '287.133392333984']
['2021-5-4 14:26:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:26:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:26:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:26:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:26:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:26:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:26:17', 'DoVa_IrrigateLevel_1_MT1', '0']

['2021-5-4 14:26:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:26:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:26:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:26:17', 'DoVa_Co2', '0']
['2021-5-4 14:26:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:26:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:26:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:26:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:26:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:27:17', 'fKWhCounter', '3412.47827148438']
['2021-5-4 14:27:17', 'fActPhLevelMixTank1', '5.60386991500854']
['2021-5-4 14:27:17', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 14:27:17', 'fActPhLevelMixTank2', '3.81939148902893']
['2021-5-4 14:27:17', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 14:27:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:27:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:27:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:27:17', 'fActRhValMemo', '51.5']
['2021-5-4 14:27:17', 'fActCo2ValMemo', '812']
['2021-5-4 14:27:17', 'fActWaterLevelMixTank1', '274.747344970703']
['2021-5-4 14:27:17', 'fActWaterLevelMixTank2', '287.242034912109']
['2021-5-4 14:27:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:27:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:27:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:27:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:27:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:27:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:27:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:27:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:27:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:27:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:27:17', 'DoVa_Co2', '0']
['2021-5-4 14:27:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:27:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:27:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:27:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:27:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:28:17', 'fKWhCounter', '3412.67846679688']
['2021-5-4 14:28:17', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 14:28:17', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 14:28:17', 'fActPhLevelMixTank2', '3.82964563369751']
['2021-5-4 14:28:17', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 14:28:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:28:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:28:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:28:17', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 14:28:17', 'fActCo2ValMemo', '810']
['2021-5-4 14:28:17', 'fActWaterLevelMixTank1', '274.693023681641']
['2021-5-4 14:28:17', 'fActWaterLevelMixTank2', '287.676635742188']
['2021-5-4 14:28:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:28:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:28:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:28:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:28:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:28:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:28:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:28:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:28:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:28:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:28:17', 'DoVa_Co2', '0']
['2021-5-4 14:28:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:28:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:28:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:28:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:28:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:29:17', 'fKWhCounter', '3412.77856445313']
['2021-5-4 14:29:17', 'fActPhLevelMixTank1', '5.60679960250854']
['2021-5-4 14:29:17', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 14:29:17', 'fActPhLevelMixTank2', '3.82891321182251']
['2021-5-4 14:29:17', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 14:29:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:29:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:29:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:29:17', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 14:29:17', 'fActCo2ValMemo', '809']
['2021-5-4 14:29:17', 'fActWaterLevelMixTank1', '274.964630126953']
['2021-5-4 14:29:17', 'fActWaterLevelMixTank2', '288.111236572266']
['2021-5-4 14:29:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:29:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:29:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:29:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:29:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:29:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:29:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:29:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:29:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:29:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:29:17', 'DoVa_Co2', '0']
['2021-5-4 14:29:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:29:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:29:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:29:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:29:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:30:17', 'fKWhCounter', '3412.97875976563']
['2021-5-4 14:30:17', 'fActPhLevelMixTank1', '5.60045146942139']
['2021-5-4 14:30:17', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 14:30:17', 'fActPhLevelMixTank2', '3.82427453994751']
['2021-5-4 14:30:17', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 14:30:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:30:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:30:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:30:17', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 14:30:17', 'fActCo2ValMemo', '805']
['2021-5-4 14:30:17', 'fActWaterLevelMixTank1', '275.616546630859']
['2021-5-4 14:30:17', 'fActWaterLevelMixTank2', '288.002593994141']
['2021-5-4 14:30:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:30:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:30:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:30:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:30:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:30:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:30:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:30:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:30:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:30:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:30:17', 'DoVa_Co2', '0']
['2021-5-4 14:30:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:30:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:30:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:30:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:30:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:31:17', 'fKWhCounter', '3413.07885742188']
['2021-5-4 14:31:17', 'fActPhLevelMixTank1', '5.61168241500854']
['2021-5-4 14:31:17', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 14:31:17', 'fActPhLevelMixTank2', '3.82964563369751']
['2021-5-4 14:31:17', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 14:31:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:31:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:31:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:31:17', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 14:31:17', 'fActCo2ValMemo', '804']
['2021-5-4 14:31:17', 'fActWaterLevelMixTank1', '275.589385986328']
['2021-5-4 14:31:17', 'fActWaterLevelMixTank2', '287.486480712891']
['2021-5-4 14:31:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:31:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:31:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:31:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:31:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:31:17', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 14:31:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:31:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:31:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:31:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:31:17', 'DoVa_Co2', '0']
['2021-5-4 14:31:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:31:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:31:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:31:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:31:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:32:17', 'fKWhCounter', '3413.27905273438']
['2021-5-4 14:32:17', 'fActPhLevelMixTank1', '5.60728788375854']
['2021-5-4 14:32:17', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 14:32:17', 'fActPhLevelMixTank2', '3.82329773902893']
['2021-5-4 14:32:17', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 14:32:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:32:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:32:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:32:17', 'fActRhValMemo', '52']
['2021-5-4 14:32:17', 'fActCo2ValMemo', '804']
['2021-5-4 14:32:17', 'fActWaterLevelMixTank1', '275.698028564453']
['2021-5-4 14:32:17', 'fActWaterLevelMixTank2', '287.866760253906']
['2021-5-4 14:32:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:32:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:32:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:32:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:32:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:32:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:32:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:32:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:32:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:32:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:32:17', 'DoVa_Co2', '0']
['2021-5-4 14:32:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:32:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:32:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:32:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:32:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:33:17', 'fKWhCounter', '3413.37915039063']
['2021-5-4 14:33:17', 'fActPhLevelMixTank1', '5.60777616500854']
['2021-5-4 14:33:17', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 14:33:17', 'fActPhLevelMixTank2', '3.83355212211609']
['2021-5-4 14:33:17', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 14:33:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:33:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:33:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:33:17', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 14:33:17', 'fActCo2ValMemo', '802']
['2021-5-4 14:33:17', 'fActWaterLevelMixTank1', '275.833831787109']
['2021-5-4 14:33:17', 'fActWaterLevelMixTank2', '287.893920898438']
['2021-5-4 14:33:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:33:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:33:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:33:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:33:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:33:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:33:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:33:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:33:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:33:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:33:17', 'DoVa_Co2', '0']
['2021-5-4 14:33:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:33:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:33:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:33:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:33:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:34:17', 'fKWhCounter', '3413.57934570313']
['2021-5-4 14:34:17', 'fActPhLevelMixTank1', '5.61070585250854']
['2021-5-4 14:34:17', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 14:34:17', 'fActPhLevelMixTank2', '3.82818078994751']
['2021-5-4 14:34:17', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 14:34:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:34:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:34:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:34:17', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 14:34:17', 'fActCo2ValMemo', '801']
['2021-5-4 14:34:17', 'fActWaterLevelMixTank1', '276.214111328125']
['2021-5-4 14:34:17', 'fActWaterLevelMixTank2', '288.219879150391']
['2021-5-4 14:34:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:34:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:34:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:34:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:34:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:34:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:34:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:34:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:34:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:34:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:34:17', 'DoVa_Co2', '0']
['2021-5-4 14:34:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:34:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:34:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:34:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:34:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:35:17', 'fKWhCounter', '3413.67944335938']
['2021-5-4 14:35:17', 'fActPhLevelMixTank1', '5.60631132125854']
['2021-5-4 14:35:17', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 14:35:17', 'fActPhLevelMixTank2', '3.83330798149109']
['2021-5-4 14:35:17', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 14:35:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:35:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:35:17', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 14:35:17', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 14:35:17', 'fActCo2ValMemo', '802']
['2021-5-4 14:35:17', 'fActWaterLevelMixTank1', '275.833831787109']
['2021-5-4 14:35:17', 'fActWaterLevelMixTank2', '288.301361083984']
['2021-5-4 14:35:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:35:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:35:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:35:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:35:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:35:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:35:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:35:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:35:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:35:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:35:17', 'DoVa_Co2', '0']
['2021-5-4 14:35:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:35:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:35:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:35:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:35:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:36:17', 'fKWhCounter', '3413.87963867188']
['2021-5-4 14:36:17', 'fActPhLevelMixTank1', '5.6172981262207']
['2021-5-4 14:36:17', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 14:36:17', 'fActPhLevelMixTank2', '3.82720422744751']
['2021-5-4 14:36:17', 'fActEcLevelMixTank2', '1032.13598632813']

['2021-5-4 14:36:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:36:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:36:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:36:17', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 14:36:17', 'fActCo2ValMemo', '799']
['2021-5-4 14:36:17', 'fActWaterLevelMixTank1', '276.32275390625']
['2021-5-4 14:36:17', 'fActWaterLevelMixTank2', '288.382843017578']
['2021-5-4 14:36:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:36:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:36:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:36:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:36:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:36:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:36:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:36:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:36:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:36:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:36:17', 'DoVa_Co2', '0']
['2021-5-4 14:36:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:36:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:36:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:36:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:36:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:37:17', 'fKWhCounter', '3413.97973632813']
['2021-5-4 14:37:17', 'fActPhLevelMixTank1', '5.60728788375854']
['2021-5-4 14:37:17', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 14:37:17', 'fActPhLevelMixTank2', '3.82915735244751']
['2021-5-4 14:37:17', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 14:37:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:37:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:37:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:37:17', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 14:37:17', 'fActCo2ValMemo', '801']
['2021-5-4 14:37:17', 'fActWaterLevelMixTank1', '276.675872802734']
['2021-5-4 14:37:17', 'fActWaterLevelMixTank2', '288.165557861328']
['2021-5-4 14:37:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:37:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:37:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:37:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:37:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:37:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:37:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:37:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:37:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:37:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:37:17', 'DoVa_Co2', '0']
['2021-5-4 14:37:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:37:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:37:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:37:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:37:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:38:17', 'fKWhCounter', '3414.17993164063']
['2021-5-4 14:38:17', 'fActPhLevelMixTank1', '5.6182746887207']
['2021-5-4 14:38:17', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 14:38:17', 'fActPhLevelMixTank2', '3.82671594619751']
['2021-5-4 14:38:17', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 14:38:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:38:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:38:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:38:17', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 14:38:17', 'fActCo2ValMemo', '803']
['2021-5-4 14:38:17', 'fActWaterLevelMixTank1', '276.268432617188']
['2021-5-4 14:38:17', 'fActWaterLevelMixTank2', '288.572998046875']
['2021-5-4 14:38:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:38:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:38:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:38:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:38:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:38:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:38:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:38:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:38:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:38:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:38:17', 'DoVa_Co2', '0']
['2021-5-4 14:38:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:38:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:38:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:38:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:38:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:39:17', 'fKWhCounter', '3414.28002929688']
['2021-5-4 14:39:17', 'fActPhLevelMixTank1', '5.6236457824707']
['2021-5-4 14:39:17', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 14:39:17', 'fActPhLevelMixTank2', '3.83281970024109']
['2021-5-4 14:39:17', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 14:39:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:39:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:39:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:39:17', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 14:39:17', 'fActCo2ValMemo', '802']
['2021-5-4 14:39:17', 'fActWaterLevelMixTank1', '276.974670410156']
['2021-5-4 14:39:17', 'fActWaterLevelMixTank2', '289.061920166016']
['2021-5-4 14:39:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:39:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:39:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:39:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:39:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:39:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:39:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:39:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:39:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:39:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:39:17', 'DoVa_Co2', '0']
['2021-5-4 14:39:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:39:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:39:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:39:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:39:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:40:17', 'fKWhCounter', '3414.48022460938']
['2021-5-4 14:40:17', 'fActPhLevelMixTank1', '5.6260871887207']
['2021-5-4 14:40:17', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 14:40:17', 'fActPhLevelMixTank2', '3.83111047744751']
['2021-5-4 14:40:17', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 14:40:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:40:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:40:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:40:17', 'fActRhValMemo', '52.5']
['2021-5-4 14:40:17', 'fActCo2ValMemo', '804']
['2021-5-4 14:40:17', 'fActWaterLevelMixTank1', '277.409271240234']
['2021-5-4 14:40:17', 'fActWaterLevelMixTank2', '288.708801269531']
['2021-5-4 14:40:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:40:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:40:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:40:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:40:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:40:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:40:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:40:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:40:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:40:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:40:17', 'DoVa_Co2', '0']
['2021-5-4 14:40:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:40:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:40:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:40:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:40:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:41:17', 'fKWhCounter', '3414.58032226563']
['2021-5-4 14:41:17', 'fActPhLevelMixTank1', '5.63585329055786']
['2021-5-4 14:41:17', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 14:41:17', 'fActPhLevelMixTank2', '3.83428454399109']
['2021-5-4 14:41:17', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 14:41:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:41:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:41:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:41:17', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 14:41:17', 'fActCo2ValMemo', '805']
['2021-5-4 14:41:17', 'fActWaterLevelMixTank1', '276.214111328125']
['2021-5-4 14:41:17', 'fActWaterLevelMixTank2', '288.953277587891']
['2021-5-4 14:41:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:41:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:41:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:41:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:41:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:41:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:41:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:41:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:41:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:41:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:41:17', 'DoVa_Co2', '0']
['2021-5-4 14:41:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:41:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:41:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:41:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_2_Red', '0']

['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:41:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:42:17', 'fKWhCounter', '3414.78051757813']
['2021-5-4 14:42:17', 'fActPhLevelMixTank1', '5.63390016555786']
['2021-5-4 14:42:17', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 14:42:17', 'fActPhLevelMixTank2', '3.83086633682251']
['2021-5-4 14:42:17', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 14:42:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:42:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:42:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:42:17', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 14:42:17', 'fActCo2ValMemo', '803']
['2021-5-4 14:42:17', 'fActWaterLevelMixTank1', '277.028991699219']
['2021-5-4 14:42:17', 'fActWaterLevelMixTank2', '288.681640625']
['2021-5-4 14:42:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:42:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:42:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:42:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:42:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:42:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:42:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:42:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:42:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:42:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:42:17', 'DoVa_Co2', '0']
['2021-5-4 14:42:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:42:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:42:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:42:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:42:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:43:17', 'fKWhCounter', '3414.88061523438']
['2021-5-4 14:43:17', 'fActPhLevelMixTank1', '5.64000368118286']
['2021-5-4 14:43:17', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 14:43:17', 'fActPhLevelMixTank2', '3.83086633682251']
['2021-5-4 14:43:17', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 14:43:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:43:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:43:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:43:17', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 14:43:17', 'fActCo2ValMemo', '802']
['2021-5-4 14:43:17', 'fActWaterLevelMixTank1', '277.191955566406']
['2021-5-4 14:43:17', 'fActWaterLevelMixTank2', '288.790283203125']
['2021-5-4 14:43:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:43:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:43:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:43:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:43:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:43:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:43:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:43:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:43:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:43:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:43:17', 'DoVa_Co2', '0']
['2021-5-4 14:43:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:43:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:43:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:43:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:43:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:44:17', 'fKWhCounter', '3414.98071289063']
['2021-5-4 14:44:17', 'fActPhLevelMixTank1', '5.63463258743286']
['2021-5-4 14:44:17', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 14:44:17', 'fActPhLevelMixTank2', '3.83819079399109']
['2021-5-4 14:44:17', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 14:44:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:44:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:44:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:44:17', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 14:44:17', 'fActCo2ValMemo', '801']
['2021-5-4 14:44:17', 'fActWaterLevelMixTank1', '277.762359619141']
['2021-5-4 14:44:17', 'fActWaterLevelMixTank2', '289.170562744141']
['2021-5-4 14:44:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:44:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:44:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:44:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:44:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:44:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:44:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:44:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:44:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:44:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:44:17', 'DoVa_Co2', '0']
['2021-5-4 14:44:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:44:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:44:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:44:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:44:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:45:17', 'fKWhCounter', '3415.18090820313']
['2021-5-4 14:45:17', 'fActPhLevelMixTank1', '5.63707399368286']
['2021-5-4 14:45:17', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 14:45:17', 'fActPhLevelMixTank2', '3.83721423149109']
['2021-5-4 14:45:17', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 14:45:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:45:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:45:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:45:17', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 14:45:17', 'fActCo2ValMemo', '802']
['2021-5-4 14:45:17', 'fActWaterLevelMixTank1', '276.132629394531']
['2021-5-4 14:45:17', 'fActWaterLevelMixTank2', '288.600158691406']
['2021-5-4 14:45:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:45:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:45:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:45:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:45:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:45:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:45:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:45:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:45:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:45:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:45:17', 'DoVa_Co2', '0']
['2021-5-4 14:45:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:45:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:45:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:45:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:45:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:46:17', 'fKWhCounter', '3415.28100585938']
['2021-5-4 14:46:17', 'fActPhLevelMixTank1', '5.64708375930786']
['2021-5-4 14:46:17', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 14:46:17', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 14:46:17', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 14:46:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:46:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:46:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:46:17', 'fActRhValMemo', '52.5']
['2021-5-4 14:46:17', 'fActCo2ValMemo', '800']
['2021-5-4 14:46:17', 'fActWaterLevelMixTank1', '277.925354003906']
['2021-5-4 14:46:17', 'fActWaterLevelMixTank2', '288.464324951172']
['2021-5-4 14:46:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:46:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:46:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:46:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:46:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:46:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:46:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:46:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:46:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:46:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:46:17', 'DoVa_Co2', '0']
['2021-5-4 14:46:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:46:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:46:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:46:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:46:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:47:17', 'fKWhCounter', '3415.48120117188']

['2021-5-4 14:47:17', 'fActPhLevelMixTank1', '5.64366579055786']
['2021-5-4 14:47:17', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 14:47:17', 'fActPhLevelMixTank2', '3.84185314178467']
['2021-5-4 14:47:17', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 14:47:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:47:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:47:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:47:17', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 14:47:17', 'fActCo2ValMemo', '800']
['2021-5-4 14:47:17', 'fActWaterLevelMixTank1', '277.871002197266']
['2021-5-4 14:47:17', 'fActWaterLevelMixTank2', '288.382843017578']
['2021-5-4 14:47:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:47:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:47:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:47:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:47:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:47:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:47:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:47:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:47:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:47:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:47:17', 'DoVa_Co2', '0']
['2021-5-4 14:47:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:47:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:47:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:47:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:47:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:48:17', 'fKWhCounter', '3415.58129882813']
['2021-5-4 14:48:17', 'fActPhLevelMixTank1', '5.64366579055786']
['2021-5-4 14:48:17', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 14:48:17', 'fActPhLevelMixTank2', '3.83745837211609']
['2021-5-4 14:48:17', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 14:48:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:48:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:48:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:48:17', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 14:48:17', 'fActCo2ValMemo', '798']
['2021-5-4 14:48:17', 'fActWaterLevelMixTank1', '277.979675292969']
['2021-5-4 14:48:17', 'fActWaterLevelMixTank2', '288.165557861328']
['2021-5-4 14:48:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:48:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:48:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:48:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:48:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:48:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:48:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:48:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:48:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:48:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:48:17', 'DoVa_Co2', '0']
['2021-5-4 14:48:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:48:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:48:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:48:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:48:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:49:17', 'fKWhCounter', '3415.78149414063']
['2021-5-4 14:49:17', 'fActPhLevelMixTank1', '5.64537477493286']
['2021-5-4 14:49:17', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 14:49:17', 'fActPhLevelMixTank2', '3.83623766899109']
['2021-5-4 14:49:17', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 14:49:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:49:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:49:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:49:17', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 14:49:17', 'fActCo2ValMemo', '798']
['2021-5-4 14:49:17', 'fActWaterLevelMixTank1', '278.0068359375']
['2021-5-4 14:49:17', 'fActWaterLevelMixTank2', '289.061920166016']
['2021-5-4 14:49:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:49:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:49:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:49:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:49:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:49:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:49:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:49:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:49:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:49:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:49:17', 'DoVa_Co2', '0']
['2021-5-4 14:49:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:49:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:49:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:49:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:49:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:50:17', 'fKWhCounter', '3415.88159179688']
['2021-5-4 14:50:17', 'fActPhLevelMixTank1', '5.64293336868286']
['2021-5-4 14:50:17', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 14:50:17', 'fActPhLevelMixTank2', '3.84185314178467']
['2021-5-4 14:50:17', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 14:50:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:50:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:50:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:50:17', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 14:50:17', 'fActCo2ValMemo', '797']
['2021-5-4 14:50:17', 'fActWaterLevelMixTank1', '278.848876953125']
['2021-5-4 14:50:17', 'fActWaterLevelMixTank2', '289.252044677734']
['2021-5-4 14:50:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:50:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:50:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:50:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:50:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:50:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:50:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:50:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:50:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:50:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:50:17', 'DoVa_Co2', '0']
['2021-5-4 14:50:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:50:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:50:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:50:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:50:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:51:17', 'fKWhCounter', '3416.08178710938']
['2021-5-4 14:51:17', 'fActPhLevelMixTank1', '5.64708375930786']
['2021-5-4 14:51:17', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 14:51:17', 'fActPhLevelMixTank2', '3.84209728240967']
['2021-5-4 14:51:17', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 14:51:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:51:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:51:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:51:17', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 14:51:17', 'fActCo2ValMemo', '796']
['2021-5-4 14:51:17', 'fActWaterLevelMixTank1', '277.2734375']
['2021-5-4 14:51:17', 'fActWaterLevelMixTank2', '289.061920166016']
['2021-5-4 14:51:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:51:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:51:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:51:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:51:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:51:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:51:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:51:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:51:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:51:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:51:17', 'DoVa_Co2', '0']
['2021-5-4 14:51:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:51:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:51:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:51:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:51:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:52:17', 'fKWhCounter', '3416.18188476563']
['2021-5-4 14:52:17', 'fActPhLevelMixTank1', '5.64537477493286']
['2021-5-4 14:52:17', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 14:52:17', 'fActPhLevelMixTank2', '3.84380626678467']
['2021-5-4 14:52:17', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 14:52:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:52:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:52:17', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 14:52:17', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 14:52:17', 'fActCo2ValMemo', '797']
['2021-5-4 14:52:17', 'fActWaterLevelMixTank1', '278.522918701172']
['2021-5-4 14:52:17', 'fActWaterLevelMixTank2', '289.007598876953']
['2021-5-4 14:52:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:52:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:52:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:52:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:52:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:52:17', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 14:52:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:52:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:52:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:52:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:52:17', 'DoVa_Co2', '0']
['2021-5-4 14:52:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:52:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:52:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:52:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:52:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:53:17', 'fKWhCounter', '3416.38208007813']
['2021-5-4 14:53:17', 'fActPhLevelMixTank1', '5.65245532989502']
['2021-5-4 14:53:17', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 14:53:17', 'fActPhLevelMixTank2', '3.83941149711609']
['2021-5-4 14:53:17', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 14:53:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:53:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:53:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:53:17', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 14:53:17', 'fActCo2ValMemo', '799']
['2021-5-4 14:53:17', 'fActWaterLevelMixTank1', '278.767364501953']
['2021-5-4 14:53:17', 'fActWaterLevelMixTank2', '289.578002929688']
['2021-5-4 14:53:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:53:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:53:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:53:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:53:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:53:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:53:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:53:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:53:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:53:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:53:17', 'DoVa_Co2', '0']
['2021-5-4 14:53:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:53:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:53:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:53:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:53:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:54:17', 'fKWhCounter', '3416.48217773438']
['2021-5-4 14:54:17', 'fActPhLevelMixTank1', '5.65489673614502']
['2021-5-4 14:54:17', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 14:54:17', 'fActPhLevelMixTank2', '3.84307384490967']
['2021-5-4 14:54:17', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 14:54:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:54:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:54:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:54:17', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 14:54:17', 'fActCo2ValMemo', '799']
['2021-5-4 14:54:17', 'fActWaterLevelMixTank1', '278.930358886719']
['2021-5-4 14:54:17', 'fActWaterLevelMixTank2', '289.143402099609']
['2021-5-4 14:54:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:54:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:54:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:54:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:54:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:54:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:54:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:54:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:54:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:54:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:54:17', 'DoVa_Co2', '0']
['2021-5-4 14:54:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:54:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:54:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:54:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:54:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:55:17', 'fKWhCounter', '3416.68237304688']
['2021-5-4 14:55:17', 'fActPhLevelMixTank1', '5.64806032180786']
['2021-5-4 14:55:17', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 14:55:17', 'fActPhLevelMixTank2', '3.84380626678467']
['2021-5-4 14:55:17', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 14:55:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:55:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:55:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:55:17', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 14:55:17', 'fActCo2ValMemo', '799']
['2021-5-4 14:55:17', 'fActWaterLevelMixTank1', '279.582244873047']
['2021-5-4 14:55:17', 'fActWaterLevelMixTank2', '289.985443115234']
['2021-5-4 14:55:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:55:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:55:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:55:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:55:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:55:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:55:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:55:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:55:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:55:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:55:17', 'DoVa_Co2', '0']
['2021-5-4 14:55:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:55:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:55:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:55:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:55:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:56:17', 'fKWhCounter', '3416.78247070313']
['2021-5-4 14:56:17', 'fActPhLevelMixTank1', '5.65636157989502']
['2021-5-4 14:56:17', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 14:56:17', 'fActPhLevelMixTank2', '3.84917759895325']
['2021-5-4 14:56:17', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 14:56:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:56:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:56:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:56:17', 'fActRhValMemo', '52.9000015258789']
['2021-5-4 14:56:17', 'fActCo2ValMemo', '799']
['2021-5-4 14:56:17', 'fActWaterLevelMixTank1', '278.658721923828']
['2021-5-4 14:56:17', 'fActWaterLevelMixTank2', '289.170562744141']
['2021-5-4 14:56:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:56:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:56:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:56:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:56:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:56:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:56:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:56:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:56:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:56:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:56:17', 'DoVa_Co2', '0']
['2021-5-4 14:56:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:56:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:56:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:56:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:56:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:57:17', 'fKWhCounter', '3416.98266601563']
['2021-5-4 14:57:17', 'fActPhLevelMixTank1', '5.64854907989502']
['2021-5-4 14:57:17', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 14:57:17', 'fActPhLevelMixTank2', '3.83916735649109']
['2021-5-4 14:57:17', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 14:57:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:57:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:57:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:57:17', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 14:57:17', 'fActCo2ValMemo', '796']
['2021-5-4 14:57:17', 'fActWaterLevelMixTank1', '278.631561279297']
['2021-5-4 14:57:17', 'fActWaterLevelMixTank2', '288.410003662109']
['2021-5-4 14:57:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:57:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:57:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:57:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:57:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:57:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:57:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:57:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:57:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:57:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:57:17', 'DoVa_Co2', '0']
['2021-5-4 14:57:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:57:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:57:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:57:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_1_White', '0']

['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:57:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:58:17', 'fKWhCounter', '3417.08276367188']
['2021-5-4 14:58:17', 'fActPhLevelMixTank1', '5.65147876739502']
['2021-5-4 14:58:17', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 14:58:17', 'fActPhLevelMixTank2', '3.84502696990967']
['2021-5-4 14:58:17', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 14:58:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:58:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:58:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:58:17', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 14:58:17', 'fActCo2ValMemo', '797']
['2021-5-4 14:58:17', 'fActWaterLevelMixTank1', '277.599395751953']
['2021-5-4 14:58:17', 'fActWaterLevelMixTank2', '289.63232421875']
['2021-5-4 14:58:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:58:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:58:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:58:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:58:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:58:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:58:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:58:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:58:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:58:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:58:17', 'DoVa_Co2', '0']
['2021-5-4 14:58:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:58:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:58:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:58:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:58:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 14:59:17', 'fKWhCounter', '3417.28295898438']
['2021-5-4 14:59:17', 'fActPhLevelMixTank1', '5.64732789993286']
['2021-5-4 14:59:17', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 14:59:17', 'fActPhLevelMixTank2', '3.83965563774109']
['2021-5-4 14:59:17', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 14:59:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 14:59:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 14:59:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 14:59:17', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 14:59:17', 'fActCo2ValMemo', '795']
['2021-5-4 14:59:17', 'fActWaterLevelMixTank1', '278.95751953125']
['2021-5-4 14:59:17', 'fActWaterLevelMixTank2', '289.550842285156']
['2021-5-4 14:59:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 14:59:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 14:59:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 14:59:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 14:59:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 14:59:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 14:59:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 14:59:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 14:59:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 14:59:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 14:59:17', 'DoVa_Co2', '0']
['2021-5-4 14:59:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 14:59:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 14:59:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 14:59:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 14:59:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:0:18', 'fKWhCounter', '3417.38305664063']
['2021-5-4 15:0:18', 'fActPhLevelMixTank1', '5.65025806427002']
['2021-5-4 15:0:18', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 15:0:18', 'fActPhLevelMixTank2', '3.84917759895325']
['2021-5-4 15:0:18', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 15:0:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:0:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:0:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:0:18', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 15:0:18', 'fActCo2ValMemo', '796']
['2021-5-4 15:0:18', 'fActWaterLevelMixTank1', '279.473602294922']
['2021-5-4 15:0:18', 'fActWaterLevelMixTank2', '289.550842285156']
['2021-5-4 15:0:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:0:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:0:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:0:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:0:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:0:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:0:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:0:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:0:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:0:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:0:18', 'DoVa_Co2', '0']
['2021-5-4 15:0:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:0:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:0:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:0:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:0:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:1:17', 'fKWhCounter', '3417.58325195313']
['2021-5-4 15:1:17', 'fActPhLevelMixTank1', '5.65587329864502']
['2021-5-4 15:1:17', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 15:1:17', 'fActPhLevelMixTank2', '3.84917759895325']
['2021-5-4 15:1:17', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 15:1:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:1:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:1:17', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:1:17', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 15:1:17', 'fActCo2ValMemo', '795']
['2021-5-4 15:1:17', 'fActWaterLevelMixTank1', '279.364959716797']
['2021-5-4 15:1:17', 'fActWaterLevelMixTank2', '289.306365966797']
['2021-5-4 15:1:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:1:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:1:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:1:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:1:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:1:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:1:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:1:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:1:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:1:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:1:17', 'DoVa_Co2', '0']
['2021-5-4 15:1:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:1:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:1:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:1:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:1:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:2:17', 'fKWhCounter', '3417.68334960938']
['2021-5-4 15:2:17', 'fActPhLevelMixTank1', '5.65782642364502']
['2021-5-4 15:2:17', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 15:2:17', 'fActPhLevelMixTank2', '3.85674619674683']
['2021-5-4 15:2:17', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 15:2:17', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:2:17', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:2:17', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:2:17', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 15:2:17', 'fActCo2ValMemo', '793']
['2021-5-4 15:2:17', 'fActWaterLevelMixTank1', '279.663726806641']
['2021-5-4 15:2:17', 'fActWaterLevelMixTank2', '289.876770019531']
['2021-5-4 15:2:17', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:2:17', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:2:17', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:2:17', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:2:17', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:2:17', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:2:17', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:2:17', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:2:17', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:2:17', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:2:17', 'DoVa_Co2', '0']
['2021-5-4 15:2:17', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:2:17', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:2:17', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:2:17', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_3_Red', '0']

['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:2:17', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:3:18', 'fKWhCounter', '3417.88354492188']
['2021-5-4 15:3:18', 'fActPhLevelMixTank1', '5.66075611114502']
['2021-5-4 15:3:18', 'fActEcLevelMixTank1', '2028.56530761719']
['2021-5-4 15:3:18', 'fActPhLevelMixTank2', '3.85064244270325']
['2021-5-4 15:3:18', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 15:3:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:3:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:3:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:3:18', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 15:3:18', 'fActCo2ValMemo', '792']
['2021-5-4 15:3:18', 'fActWaterLevelMixTank1', '279.337799072266']
['2021-5-4 15:3:18', 'fActWaterLevelMixTank2', '289.007598876953']
['2021-5-4 15:3:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:3:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:3:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:3:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:3:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:3:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:3:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:3:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:3:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:3:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:3:18', 'DoVa_Co2', '0']
['2021-5-4 15:3:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:3:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:3:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:3:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:3:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:4:18', 'fKWhCounter', '3417.98364257813']
['2021-5-4 15:4:18', 'fActPhLevelMixTank1', '5.58946514129639']
['2021-5-4 15:4:18', 'fActEcLevelMixTank1', '2038.48388671875']
['2021-5-4 15:4:18', 'fActPhLevelMixTank2', '3.76738786697388']
['2021-5-4 15:4:18', 'fActEcLevelMixTank2', '1042.05456542969']
['2021-5-4 15:4:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:4:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:4:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:4:18', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 15:4:18', 'fActCo2ValMemo', '794']
['2021-5-4 15:4:18', 'fActWaterLevelMixTank1', '278.142639160156']
['2021-5-4 15:4:18', 'fActWaterLevelMixTank2', '278.848876953125']
['2021-5-4 15:4:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:4:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:4:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:4:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:4:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:4:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:4:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:4:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:4:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:4:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:4:18', 'DoVa_Co2', '0']
['2021-5-4 15:4:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:4:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:4:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:4:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:4:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:5:18', 'fKWhCounter', '3418.18383789063']
['2021-5-4 15:5:18', 'fActPhLevelMixTank1', '5.55919075012207']
['2021-5-4 15:5:18', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 15:5:18', 'fActPhLevelMixTank2', '3.75029754638672']
['2021-5-4 15:5:18', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 15:5:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:5:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:5:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:5:18', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 15:5:18', 'fActCo2ValMemo', '795']
['2021-5-4 15:5:18', 'fActWaterLevelMixTank1', '274.122619628906']
['2021-5-4 15:5:18', 'fActWaterLevelMixTank2', '265.023223876953']
['2021-5-4 15:5:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:5:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:5:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:5:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:5:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:5:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:5:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:5:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:5:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:5:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:5:18', 'DoVa_Co2', '0']
['2021-5-4 15:5:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:5:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:5:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:5:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:5:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:6:18', 'fKWhCounter', '3418.38403320313']
['2021-5-4 15:6:18', 'fActPhLevelMixTank1', '5.56602668762207']
['2021-5-4 15:6:18', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 15:6:18', 'fActPhLevelMixTank2', '3.76348161697388']
['2021-5-4 15:6:18', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 15:6:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:6:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:6:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:6:18', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 15:6:18', 'fActCo2ValMemo', '794']
['2021-5-4 15:6:18', 'fActWaterLevelMixTank1', '271.134735107422']
['2021-5-4 15:6:18', 'fActWaterLevelMixTank2', '302.317138671875']
['2021-5-4 15:6:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:6:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:6:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:6:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:6:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:6:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:6:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:6:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:6:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:6:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:6:18', 'DoVa_Co2', '0']
['2021-5-4 15:6:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:6:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:6:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:6:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:6:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:7:18', 'fKWhCounter', '3418.58422851563']
['2021-5-4 15:7:18', 'fActPhLevelMixTank1', '5.57042169570923']
['2021-5-4 15:7:18', 'fActEcLevelMixTank1', '2014.06909179688']
['2021-5-4 15:7:18', 'fActPhLevelMixTank2', '3.76592302322388']
['2021-5-4 15:7:18', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 15:7:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:7:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:7:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:7:18', 'fActRhValMemo', '52.5']
['2021-5-4 15:7:18', 'fActCo2ValMemo', '794']
['2021-5-4 15:7:18', 'fActWaterLevelMixTank1', '268.907440185547']
['2021-5-4 15:7:18', 'fActWaterLevelMixTank2', '297.129119873047']
['2021-5-4 15:7:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:7:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:7:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:7:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:7:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:7:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:7:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:7:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:7:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:7:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:7:18', 'DoVa_Co2', '0']
['2021-5-4 15:7:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:7:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:7:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:7:18', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:7:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:8:18', 'fKWhCounter', '3418.68432617188']
['2021-5-4 15:8:18', 'fActPhLevelMixTank1', '5.56260871887207']
['2021-5-4 15:8:18', 'fActEcLevelMixTank1', '2036.95788574219']
['2021-5-4 15:8:18', 'fActPhLevelMixTank2', '3.76641130447388']
['2021-5-4 15:8:18', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 15:8:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:8:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:8:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:8:18', 'fActRhValMemo', '52.5']
['2021-5-4 15:8:18', 'fActCo2ValMemo', '792']
['2021-5-4 15:8:18', 'fActWaterLevelMixTank1', '266.571472167969']
['2021-5-4 15:8:18', 'fActWaterLevelMixTank2', '266.001068115234']
['2021-5-4 15:8:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:8:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:8:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:8:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:8:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:8:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:8:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:8:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:8:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:8:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:8:18', 'DoVa_Co2', '0']
['2021-5-4 15:8:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:8:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:8:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:8:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:8:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:9:18', 'fKWhCounter', '3418.88452148438']
['2021-5-4 15:9:18', 'fActPhLevelMixTank1', '5.57139825820923']
['2021-5-4 15:9:18', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 15:9:18', 'fActPhLevelMixTank2', '3.78594326972961']
['2021-5-4 15:9:18', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 15:9:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:9:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:9:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:9:18', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 15:9:18', 'fActCo2ValMemo', '791']
['2021-5-4 15:9:18', 'fActWaterLevelMixTank1', '266.870269775391']
['2021-5-4 15:9:18', 'fActWaterLevelMixTank2', '281.103332519531']
['2021-5-4 15:9:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:9:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:9:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:9:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:9:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:9:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:9:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:9:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:9:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:9:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:9:18', 'DoVa_Co2', '0']
['2021-5-4 15:9:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:9:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:9:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:9:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:9:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:10:18', 'fKWhCounter', '3419.08471679688']
['2021-5-4 15:10:18', 'fActPhLevelMixTank1', '5.57164239883423']
['2021-5-4 15:10:18', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 15:10:18', 'fActPhLevelMixTank2', '3.82598352432251']
['2021-5-4 15:10:18', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 15:10:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:10:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:10:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:10:18', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 15:10:18', 'fActCo2ValMemo', '789']
['2021-5-4 15:10:18', 'fActWaterLevelMixTank1', '267.141876220703']
['2021-5-4 15:10:18', 'fActWaterLevelMixTank2', '280.804565429688']
['2021-5-4 15:10:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:10:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:10:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:10:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:10:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:10:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:10:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:10:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:10:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:10:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:10:18', 'DoVa_Co2', '0']
['2021-5-4 15:10:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:10:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:10:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:10:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:10:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:11:18', 'fKWhCounter', '3419.18481445313']
['2021-5-4 15:11:18', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 15:11:18', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 15:11:18', 'fActPhLevelMixTank2', '3.81206703186035']
['2021-5-4 15:11:18', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 15:11:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:11:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:11:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:11:18', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 15:11:18', 'fActCo2ValMemo', '790']
['2021-5-4 15:11:18', 'fActWaterLevelMixTank1', '266.191192626953']
['2021-5-4 15:11:18', 'fActWaterLevelMixTank2', '280.152648925781']
['2021-5-4 15:11:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:11:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:11:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:11:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:11:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:11:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:11:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:11:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:11:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:11:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:11:18', 'DoVa_Co2', '0']
['2021-5-4 15:11:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:11:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:11:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:11:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:11:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:12:18', 'fKWhCounter', '3419.38500976563']
['2021-5-4 15:12:18', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 15:12:18', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 15:12:18', 'fActPhLevelMixTank2', '3.81402015686035']
['2021-5-4 15:12:18', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 15:12:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:12:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:12:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:12:18', 'fActRhValMemo', '53']
['2021-5-4 15:12:18', 'fActCo2ValMemo', '788']
['2021-5-4 15:12:18', 'fActWaterLevelMixTank1', '266.707275390625']
['2021-5-4 15:12:18', 'fActWaterLevelMixTank2', '280.804565429688']
['2021-5-4 15:12:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:12:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:12:18', 'DoPu_AddEcBMixTank_1', '0']

['2021-5-4 15:12:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:12:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:12:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:12:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:12:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:12:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:12:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:12:18', 'DoVa_Co2', '0']
['2021-5-4 15:12:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:12:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:12:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:12:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:12:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:13:18', 'fKWhCounter', '3419.48510742188']
['2021-5-4 15:13:18', 'fActPhLevelMixTank1', '5.57652521133423']
['2021-5-4 15:13:18', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 15:13:18', 'fActPhLevelMixTank2', '3.80547499656677']
['2021-5-4 15:13:18', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 15:13:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:13:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:13:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:13:18', 'fActRhValMemo', '53.2999992370605']
['2021-5-4 15:13:18', 'fActCo2ValMemo', '789']
['2021-5-4 15:13:18', 'fActWaterLevelMixTank1', '267.060394287109']
['2021-5-4 15:13:18', 'fActWaterLevelMixTank2', '279.772369384766']
['2021-5-4 15:13:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:13:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:13:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:13:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:13:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:13:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:13:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:13:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:13:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:13:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:13:18', 'DoVa_Co2', '0']
['2021-5-4 15:13:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:13:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:13:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:13:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:13:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:14:18', 'fKWhCounter', '3419.68530273438']
['2021-5-4 15:14:18', 'fActPhLevelMixTank1', '5.57945489883423']
['2021-5-4 15:14:18', 'fActEcLevelMixTank1', '2046.41870117188']
['2021-5-4 15:14:18', 'fActPhLevelMixTank2', '3.81060218811035']
['2021-5-4 15:14:18', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 15:14:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:14:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:14:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:14:18', 'fActRhValMemo', '53']
['2021-5-4 15:14:18', 'fActCo2ValMemo', '788']
['2021-5-4 15:14:18', 'fActWaterLevelMixTank1', '267.440673828125']
['2021-5-4 15:14:18', 'fActWaterLevelMixTank2', '280.397125244141']
['2021-5-4 15:14:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:14:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:14:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:14:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:14:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:14:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:14:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:14:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:14:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:14:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:14:18', 'DoVa_Co2', '0']
['2021-5-4 15:14:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:14:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:14:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:14:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:14:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:15:18', 'fKWhCounter', '3419.78540039063']
['2021-5-4 15:15:18', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 15:15:18', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 15:15:18', 'fActPhLevelMixTank2', '3.80767226219177']
['2021-5-4 15:15:18', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 15:15:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:15:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:15:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:15:18', 'fActRhValMemo', '53.4000015258789']
['2021-5-4 15:15:18', 'fActCo2ValMemo', '785']
['2021-5-4 15:15:18', 'fActWaterLevelMixTank1', '268.092559814453']
['2021-5-4 15:15:18', 'fActWaterLevelMixTank2', '280.369964599609']
['2021-5-4 15:15:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:15:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:15:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:15:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:15:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:15:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:15:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:15:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:15:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:15:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:15:18', 'DoVa_Co2', '0']
['2021-5-4 15:15:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:15:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:15:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:15:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:15:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:16:18', 'fKWhCounter', '3419.98559570313']
['2021-5-4 15:16:18', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 15:16:18', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 15:16:18', 'fActPhLevelMixTank2', '3.80962562561035']
['2021-5-4 15:16:18', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 15:16:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:16:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:16:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:16:18', 'fActRhValMemo', '53.4000015258789']
['2021-5-4 15:16:18', 'fActCo2ValMemo', '785']
['2021-5-4 15:16:18', 'fActWaterLevelMixTank1', '267.440673828125']
['2021-5-4 15:16:18', 'fActWaterLevelMixTank2', '280.179809570313']
['2021-5-4 15:16:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:16:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:16:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:16:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:16:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:16:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:16:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:16:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:16:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:16:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:16:18', 'DoVa_Co2', '0']
['2021-5-4 15:16:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:16:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:16:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:16:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:16:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:17:18', 'fKWhCounter', '3420.08569335938']
['2021-5-4 15:17:18', 'fActPhLevelMixTank1', '5.57945489883423']
['2021-5-4 15:17:18', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 15:17:18', 'fActPhLevelMixTank2', '3.80327773094177']
['2021-5-4 15:17:18', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 15:17:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:17:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:17:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:17:18', 'fActRhValMemo', '53.2999992370605']
['2021-5-4 15:17:18', 'fActCo2ValMemo', '786']
['2021-5-4 15:17:18', 'fActWaterLevelMixTank1', '266.843109130859']
['2021-5-4 15:17:18', 'fActWaterLevelMixTank2', '280.261291503906']
['2021-5-4 15:17:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:17:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:17:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:17:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:17:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:17:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:17:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:17:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:17:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:17:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:17:18', 'DoVa_Co2', '0']
['2021-5-4 15:17:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:17:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:17:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:17:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_2_Fred', '0']

['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:17:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:18:18', 'fKWhCounter', '3420.28588867188']
['2021-5-4 15:18:18', 'fActPhLevelMixTank1', '5.57750177383423']
['2021-5-4 15:18:18', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 15:18:18', 'fActPhLevelMixTank2', '3.80547499656677']
['2021-5-4 15:18:18', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 15:18:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:18:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:18:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:18:18', 'fActRhValMemo', '53.0999984741211']
['2021-5-4 15:18:18', 'fActCo2ValMemo', '787']
['2021-5-4 15:18:18', 'fActWaterLevelMixTank1', '268.608642578125']
['2021-5-4 15:18:18', 'fActWaterLevelMixTank2', '280.478607177734']
['2021-5-4 15:18:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:18:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:18:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:18:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:18:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:18:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:18:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:18:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:18:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:18:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:18:18', 'DoVa_Co2', '0']
['2021-5-4 15:18:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:18:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:18:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:18:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:18:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:19:18', 'fKWhCounter', '3420.38598632813']
['2021-5-4 15:19:18', 'fActPhLevelMixTank1', '5.57799005508423']
['2021-5-4 15:19:18', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 15:19:18', 'fActPhLevelMixTank2', '3.80718398094177']
['2021-5-4 15:19:18', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 15:19:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:19:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:19:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:19:18', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 15:19:18', 'fActCo2ValMemo', '787']
['2021-5-4 15:19:18', 'fActWaterLevelMixTank1', '269.016082763672']
['2021-5-4 15:19:18', 'fActWaterLevelMixTank2', '280.505767822266']
['2021-5-4 15:19:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:19:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:19:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:19:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:19:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:19:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:19:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:19:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:19:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:19:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:19:18', 'DoVa_Co2', '0']
['2021-5-4 15:19:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:19:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:19:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:19:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:19:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:20:18', 'fKWhCounter', '3420.48608398438']
['2021-5-4 15:20:18', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 15:20:18', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 15:20:18', 'fActPhLevelMixTank2', '3.80913734436035']
['2021-5-4 15:20:18', 'fActEcLevelMixTank2', '1020.99670410156']
['2021-5-4 15:20:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:20:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:20:18', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 15:20:18', 'fActRhValMemo', '52.7999992370605']
['2021-5-4 15:20:18', 'fActCo2ValMemo', '785']
['2021-5-4 15:20:18', 'fActWaterLevelMixTank1', '269.559326171875']
['2021-5-4 15:20:18', 'fActWaterLevelMixTank2', '280.940368652344']
['2021-5-4 15:20:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:20:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:20:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:20:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:20:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:20:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:20:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:20:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:20:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:20:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:20:18', 'DoVa_Co2', '0']
['2021-5-4 15:20:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:20:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:20:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:20:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:20:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:21:18', 'fKWhCounter', '3420.68627929688']
['2021-5-4 15:21:18', 'fActPhLevelMixTank1', '5.57628107070923']
['2021-5-4 15:21:18', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 15:21:18', 'fActPhLevelMixTank2', '3.80254530906677']
['2021-5-4 15:21:18', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 15:21:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:21:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:21:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:21:18', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 15:21:18', 'fActCo2ValMemo', '782']
['2021-5-4 15:21:18', 'fActWaterLevelMixTank1', '269.993927001953']
['2021-5-4 15:21:18', 'fActWaterLevelMixTank2', '280.750213623047']
['2021-5-4 15:21:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:21:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:21:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:21:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:21:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:21:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:21:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:21:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:21:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:21:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:21:18', 'DoVa_Co2', '0']
['2021-5-4 15:21:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:21:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:21:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:21:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:21:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:22:18', 'fKWhCounter', '3420.78637695313']
['2021-5-4 15:22:18', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 15:22:18', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 15:22:18', 'fActPhLevelMixTank2', '3.80718398094177']
['2021-5-4 15:22:18', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 15:22:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:22:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:22:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:22:18', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 15:22:18', 'fActCo2ValMemo', '777']
['2021-5-4 15:22:18', 'fActWaterLevelMixTank1', '268.798797607422']
['2021-5-4 15:22:18', 'fActWaterLevelMixTank2', '281.021850585938']
['2021-5-4 15:22:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:22:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:22:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:22:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:22:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:22:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:22:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:22:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:22:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:22:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:22:18', 'DoVa_Co2', '0']

['2021-5-4 15:22:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:22:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:22:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:22:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:22:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:23:18', 'fKWhCounter', '3420.98657226563']
['2021-5-4 15:23:18', 'fActPhLevelMixTank1', '5.58604717254639']
['2021-5-4 15:23:18', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 15:23:18', 'fActPhLevelMixTank2', '3.81060218811035']
['2021-5-4 15:23:18', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 15:23:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:23:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:23:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:23:18', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 15:23:18', 'fActCo2ValMemo', '780']
['2021-5-4 15:23:18', 'fActWaterLevelMixTank1', '270.591491699219']
['2021-5-4 15:23:18', 'fActWaterLevelMixTank2', '281.782409667969']
['2021-5-4 15:23:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:23:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:23:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:23:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:23:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:23:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:23:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:23:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:23:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:23:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:23:18', 'DoVa_Co2', '0']
['2021-5-4 15:23:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:23:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:23:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:23:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:23:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:24:18', 'fKWhCounter', '3421.08666992188']
['2021-5-4 15:24:18', 'fActPhLevelMixTank1', '5.59092998504639']
['2021-5-4 15:24:18', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 15:24:18', 'fActPhLevelMixTank2', '3.81060218811035']
['2021-5-4 15:24:18', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 15:24:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:24:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:24:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:24:18', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 15:24:18', 'fActCo2ValMemo', '779']
['2021-5-4 15:24:18', 'fActWaterLevelMixTank1', '270.944610595703']
['2021-5-4 15:24:18', 'fActWaterLevelMixTank2', '281.456451416016']
['2021-5-4 15:24:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:24:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:24:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:24:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:24:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:24:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:24:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:24:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:24:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:24:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:24:18', 'DoVa_Co2', '0']
['2021-5-4 15:24:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:24:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:24:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:24:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:24:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:25:18', 'fKWhCounter', '3421.28686523438']
['2021-5-4 15:25:18', 'fActPhLevelMixTank1', '5.59825420379639']
['2021-5-4 15:25:18', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 15:25:18', 'fActPhLevelMixTank2', '3.81646180152893']
['2021-5-4 15:25:18', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 15:25:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:25:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:25:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:25:18', 'fActRhValMemo', '52.5']
['2021-5-4 15:25:18', 'fActCo2ValMemo', '778']
['2021-5-4 15:25:18', 'fActWaterLevelMixTank1', '271.053253173828']
['2021-5-4 15:25:18', 'fActWaterLevelMixTank2', '281.130493164063']
['2021-5-4 15:25:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:25:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:25:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:25:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:25:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:25:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:25:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:25:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:25:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:25:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:25:18', 'DoVa_Co2', '0']
['2021-5-4 15:25:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:25:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:25:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:25:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:25:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:26:18', 'fKWhCounter', '3421.38696289063']
['2021-5-4 15:26:18', 'fActPhLevelMixTank1', '5.59630107879639']
['2021-5-4 15:26:18', 'fActEcLevelMixTank1', '2017.73120117188']
['2021-5-4 15:26:18', 'fActPhLevelMixTank2', '3.81109046936035']
['2021-5-4 15:26:18', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 15:26:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:26:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:26:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:26:18', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 15:26:18', 'fActCo2ValMemo', '778']
['2021-5-4 15:26:18', 'fActWaterLevelMixTank1', '271.5693359375']
['2021-5-4 15:26:18', 'fActWaterLevelMixTank2', '282.054016113281']
['2021-5-4 15:26:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:26:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:26:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:26:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:26:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:26:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:26:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:26:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:26:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:26:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:26:18', 'DoVa_Co2', '0']
['2021-5-4 15:26:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:26:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:26:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:26:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:26:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:27:18', 'fKWhCounter', '3421.58715820313']
['2021-5-4 15:27:18', 'fActPhLevelMixTank1', '5.59947490692139']
['2021-5-4 15:27:18', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 15:27:18', 'fActPhLevelMixTank2', '3.81572914123535']
['2021-5-4 15:27:18', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 15:27:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:27:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:27:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:27:18', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 15:27:18', 'fActCo2ValMemo', '778']
['2021-5-4 15:27:18', 'fActWaterLevelMixTank1', '270.591491699219']
['2021-5-4 15:27:18', 'fActWaterLevelMixTank2', '281.972534179688']
['2021-5-4 15:27:18', 'DoPu_AddAcidMixTank_1', '0']

['2021-5-4 15:27:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:27:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:27:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:27:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:27:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:27:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:27:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:27:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:27:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:27:18', 'DoVa_Co2', '0']
['2021-5-4 15:27:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:27:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:27:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:27:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:27:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:28:18', 'fKWhCounter', '3421.68725585938']
['2021-5-4 15:28:18', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 15:28:18', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 15:28:18', 'fActPhLevelMixTank2', '3.81353187561035']
['2021-5-4 15:28:18', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 15:28:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:28:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:28:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:28:18', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 15:28:18', 'fActCo2ValMemo', '780']
['2021-5-4 15:28:18', 'fActWaterLevelMixTank1', '272.574340820313']
['2021-5-4 15:28:18', 'fActWaterLevelMixTank2', '282.434295654297']
['2021-5-4 15:28:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:28:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:28:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:28:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:28:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:28:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:28:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:28:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:28:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:28:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:28:18', 'DoVa_Co2', '0']
['2021-5-4 15:28:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:28:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:28:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:28:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:28:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:29:18', 'fKWhCounter', '3421.88745117188']
['2021-5-4 15:29:18', 'fActPhLevelMixTank1', '5.59654521942139']
['2021-5-4 15:29:18', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 15:29:18', 'fActPhLevelMixTank2', '3.82134461402893']
['2021-5-4 15:29:18', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 15:29:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:29:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:29:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:29:18', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 15:29:18', 'fActCo2ValMemo', '778']
['2021-5-4 15:29:18', 'fActWaterLevelMixTank1', '272.791656494141']
['2021-5-4 15:29:18', 'fActWaterLevelMixTank2', '282.162658691406']
['2021-5-4 15:29:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:29:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:29:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:29:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:29:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:29:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:29:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:29:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:29:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:29:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:29:18', 'DoVa_Co2', '0']
['2021-5-4 15:29:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:29:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:29:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:29:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:29:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:30:18', 'fKWhCounter', '3421.98754882813']
['2021-5-4 15:30:18', 'fActPhLevelMixTank1', '5.60582304000854']
['2021-5-4 15:30:18', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 15:30:18', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 15:30:18', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 15:30:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:30:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:30:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:30:18', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 15:30:18', 'fActCo2ValMemo', '779']
['2021-5-4 15:30:18', 'fActWaterLevelMixTank1', '272.357055664063']
['2021-5-4 15:30:18', 'fActWaterLevelMixTank2', '282.434295654297']
['2021-5-4 15:30:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:30:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:30:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:30:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:30:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:30:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:30:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:30:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:30:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:30:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:30:18', 'DoVa_Co2', '0']
['2021-5-4 15:30:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:30:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:30:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:30:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:30:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:31:18', 'fKWhCounter', '3422.18774414063']
['2021-5-4 15:31:18', 'fActPhLevelMixTank1', '5.59678936004639']
['2021-5-4 15:31:18', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 15:31:18', 'fActPhLevelMixTank2', '3.82403016090393']
['2021-5-4 15:31:18', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 15:31:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:31:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:31:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:31:18', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 15:31:18', 'fActCo2ValMemo', '776']
['2021-5-4 15:31:18', 'fActWaterLevelMixTank1', '272.764495849609']
['2021-5-4 15:31:18', 'fActWaterLevelMixTank2', '282.597259521484']
['2021-5-4 15:31:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:31:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:31:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:31:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:31:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:31:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:31:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:31:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:31:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:31:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:31:18', 'DoVa_Co2', '0']
['2021-5-4 15:31:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:31:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:31:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:31:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:31:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']

['2021-5-4 15:31:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:32:18', 'fKWhCounter', '3422.28784179688']
['2021-5-4 15:32:18', 'fActPhLevelMixTank1', '5.59776592254639']
['2021-5-4 15:32:18', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 15:32:18', 'fActPhLevelMixTank2', '3.82207703590393']
['2021-5-4 15:32:18', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 15:32:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:32:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:32:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:32:18', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 15:32:18', 'fActCo2ValMemo', '774']
['2021-5-4 15:32:18', 'fActWaterLevelMixTank1', '271.515014648438']
['2021-5-4 15:32:18', 'fActWaterLevelMixTank2', '282.678741455078']
['2021-5-4 15:32:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:32:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:32:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:32:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:32:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:32:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:32:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:32:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:32:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:32:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:32:18', 'DoVa_Co2', '0']
['2021-5-4 15:32:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:32:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:32:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:32:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:32:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:33:18', 'fKWhCounter', '3422.48803710938']
['2021-5-4 15:33:18', 'fActPhLevelMixTank1', '5.60484647750854']
['2021-5-4 15:33:18', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 15:33:18', 'fActPhLevelMixTank2', '3.82891321182251']
['2021-5-4 15:33:18', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 15:33:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:33:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:33:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:33:18', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 15:33:18', 'fActCo2ValMemo', '775']
['2021-5-4 15:33:18', 'fActWaterLevelMixTank1', '270.998931884766']
['2021-5-4 15:33:18', 'fActWaterLevelMixTank2', '282.678741455078']
['2021-5-4 15:33:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:33:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:33:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:33:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:33:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:33:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:33:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:33:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:33:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:33:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:33:18', 'DoVa_Co2', '0']
['2021-5-4 15:33:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:33:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:33:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:33:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:33:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:34:18', 'fKWhCounter', '3422.58813476563']
['2021-5-4 15:34:18', 'fActPhLevelMixTank1', '5.59825420379639']
['2021-5-4 15:34:18', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 15:34:18', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 15:34:18', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 15:34:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:34:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:34:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:34:18', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 15:34:18', 'fActCo2ValMemo', '776']
['2021-5-4 15:34:18', 'fActWaterLevelMixTank1', '273.008941650391']
['2021-5-4 15:34:18', 'fActWaterLevelMixTank2', '282.705932617188']
['2021-5-4 15:34:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:34:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:34:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:34:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:34:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:34:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:34:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:34:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:34:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:34:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:34:18', 'DoVa_Co2', '0']
['2021-5-4 15:34:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:34:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:34:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:34:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:34:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:35:18', 'fKWhCounter', '3422.78833007813']
['2021-5-4 15:35:18', 'fActPhLevelMixTank1', '5.60386991500854']
['2021-5-4 15:35:18', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 15:35:18', 'fActPhLevelMixTank2', '3.82988977432251']
['2021-5-4 15:35:18', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 15:35:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:35:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:35:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:35:18', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 15:35:18', 'fActCo2ValMemo', '773']
['2021-5-4 15:35:18', 'fActWaterLevelMixTank1', '273.497863769531']
['2021-5-4 15:35:18', 'fActWaterLevelMixTank2', '282.434295654297']
['2021-5-4 15:35:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:35:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:35:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:35:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:35:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:35:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:35:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:35:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:35:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:35:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:35:18', 'DoVa_Co2', '0']
['2021-5-4 15:35:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:35:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:35:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:35:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:35:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:36:18', 'fKWhCounter', '3422.88842773438']
['2021-5-4 15:36:18', 'fActPhLevelMixTank1', '5.60826444625854']
['2021-5-4 15:36:18', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 15:36:18', 'fActPhLevelMixTank2', '3.82500696182251']
['2021-5-4 15:36:18', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 15:36:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:36:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:36:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:36:18', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 15:36:18', 'fActCo2ValMemo', '769']
['2021-5-4 15:36:18', 'fActWaterLevelMixTank1', '273.715179443359']
['2021-5-4 15:36:18', 'fActWaterLevelMixTank2', '282.488616943359']
['2021-5-4 15:36:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:36:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:36:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:36:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:36:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:36:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:36:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:36:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:36:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:36:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:36:18', 'DoVa_Co2', '0']
['2021-5-4 15:36:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:36:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:36:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:36:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_1_Red', '0']

['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:36:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:37:18', 'fKWhCounter', '3423.08862304688']
['2021-5-4 15:37:18', 'fActPhLevelMixTank1', '5.60093975067139']
['2021-5-4 15:37:18', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 15:37:18', 'fActPhLevelMixTank2', '3.83086633682251']
['2021-5-4 15:37:18', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 15:37:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:37:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:37:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:37:18', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 15:37:18', 'fActCo2ValMemo', '768']
['2021-5-4 15:37:18', 'fActWaterLevelMixTank1', '273.660858154297']
['2021-5-4 15:37:18', 'fActWaterLevelMixTank2', '282.678741455078']
['2021-5-4 15:37:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:37:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:37:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:37:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:37:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:37:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:37:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:37:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:37:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:37:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:37:18', 'DoVa_Co2', '0']
['2021-5-4 15:37:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:37:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:37:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:37:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:37:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:38:18', 'fKWhCounter', '3423.18872070313']
['2021-5-4 15:38:18', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 15:38:18', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 15:38:18', 'fActPhLevelMixTank2', '3.82403016090393']
['2021-5-4 15:38:18', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 15:38:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:38:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:38:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:38:18', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 15:38:18', 'fActCo2ValMemo', '768']
['2021-5-4 15:38:18', 'fActWaterLevelMixTank1', '273.389221191406']
['2021-5-4 15:38:18', 'fActWaterLevelMixTank2', '283.059020996094']
['2021-5-4 15:38:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:38:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:38:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:38:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:38:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:38:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:38:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:38:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:38:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:38:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:38:18', 'DoVa_Co2', '0']
['2021-5-4 15:38:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:38:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:38:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:38:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:38:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:39:18', 'fKWhCounter', '3423.28881835938']
['2021-5-4 15:39:18', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 15:39:18', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 15:39:18', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 15:39:18', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 15:39:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:39:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:39:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:39:18', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 15:39:18', 'fActCo2ValMemo', '769']
['2021-5-4 15:39:18', 'fActWaterLevelMixTank1', '274.530059814453']
['2021-5-4 15:39:18', 'fActWaterLevelMixTank2', '283.738098144531']
['2021-5-4 15:39:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:39:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:39:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:39:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:39:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:39:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:39:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:39:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:39:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:39:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:39:18', 'DoVa_Co2', '0']
['2021-5-4 15:39:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:39:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:39:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:39:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:39:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:40:18', 'fKWhCounter', '3423.48901367188']
['2021-5-4 15:40:18', 'fActPhLevelMixTank1', '5.60802030563354']
['2021-5-4 15:40:18', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 15:40:18', 'fActPhLevelMixTank2', '3.82866907119751']
['2021-5-4 15:40:18', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 15:40:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:40:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:40:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:40:18', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 15:40:18', 'fActCo2ValMemo', '764']
['2021-5-4 15:40:18', 'fActWaterLevelMixTank1', '275.290588378906']
['2021-5-4 15:40:18', 'fActWaterLevelMixTank2', '283.738098144531']
['2021-5-4 15:40:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:40:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:40:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:40:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:40:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:40:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:40:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:40:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:40:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:40:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:40:18', 'DoVa_Co2', '0']
['2021-5-4 15:40:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:40:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:40:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:40:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:40:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:41:18', 'fKWhCounter', '3423.58911132813']
['2021-5-4 15:41:18', 'fActPhLevelMixTank1', '5.61656522750854']
['2021-5-4 15:41:18', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 15:41:18', 'fActPhLevelMixTank2', '3.83355212211609']
['2021-5-4 15:41:18', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 15:41:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:41:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:41:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:41:18', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 15:41:18', 'fActCo2ValMemo', '764']
['2021-5-4 15:41:18', 'fActWaterLevelMixTank1', '274.665863037109']
['2021-5-4 15:41:18', 'fActWaterLevelMixTank2', '283.547943115234']
['2021-5-4 15:41:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:41:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:41:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:41:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:41:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:41:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:41:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:41:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:41:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:41:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:41:18', 'DoVa_Co2', '0']
['2021-5-4 15:41:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:41:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:41:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:41:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 15:41:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:41:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:42:18', 'fKWhCounter', '3423.78930664063']
['2021-5-4 15:42:18', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 15:42:18', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 15:42:18', 'fActPhLevelMixTank2', '3.82598352432251']
['2021-5-4 15:42:18', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 15:42:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:42:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:42:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:42:18', 'fActRhValMemo', '52.7000007629395']
['2021-5-4 15:42:18', 'fActCo2ValMemo', '767']
['2021-5-4 15:42:18', 'fActWaterLevelMixTank1', '274.774505615234']
['2021-5-4 15:42:18', 'fActWaterLevelMixTank2', '283.846740722656']
['2021-5-4 15:42:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:42:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:42:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:42:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:42:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:42:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:42:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:42:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:42:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:42:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:42:18', 'DoVa_Co2', '0']
['2021-5-4 15:42:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:42:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:42:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:42:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:42:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:43:18', 'fKWhCounter', '3423.88940429688']
['2021-5-4 15:43:18', 'fActPhLevelMixTank1', '5.6214485168457']
['2021-5-4 15:43:18', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 15:43:18', 'fActPhLevelMixTank2', '3.82818078994751']
['2021-5-4 15:43:18', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 15:43:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:43:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:43:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:43:18', 'fActRhValMemo', '53.2000007629395']
['2021-5-4 15:43:18', 'fActCo2ValMemo', '769']
['2021-5-4 15:43:18', 'fActWaterLevelMixTank1', '274.339904785156']
['2021-5-4 15:43:18', 'fActWaterLevelMixTank2', '284.009704589844']
['2021-5-4 15:43:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:43:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:43:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:43:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:43:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:43:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:43:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:43:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:43:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:43:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:43:18', 'DoVa_Co2', '0']
['2021-5-4 15:43:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:43:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:43:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:43:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:43:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:44:18', 'fKWhCounter', '3424.08959960938']
['2021-5-4 15:44:18', 'fActPhLevelMixTank1', '5.6309700012207']
['2021-5-4 15:44:18', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 15:44:18', 'fActPhLevelMixTank2', '3.82915735244751']
['2021-5-4 15:44:18', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 15:44:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:44:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:44:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 15:44:18', 'fActRhValMemo', '54.0999984741211']
['2021-5-4 15:44:18', 'fActCo2ValMemo', '772']
['2021-5-4 15:44:18', 'fActWaterLevelMixTank1', '273.334899902344']
['2021-5-4 15:44:18', 'fActWaterLevelMixTank2', '284.254180908203']
['2021-5-4 15:44:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:44:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:44:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:44:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:44:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:44:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:44:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:44:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:44:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:44:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:44:18', 'DoVa_Co2', '0']
['2021-5-4 15:44:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:44:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:44:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:44:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:44:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:45:18', 'fKWhCounter', '3424.18969726563']
['2021-5-4 15:45:18', 'fActPhLevelMixTank1', '5.6307258605957']
['2021-5-4 15:45:18', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 15:45:18', 'fActPhLevelMixTank2', '3.83159875869751']
['2021-5-4 15:45:18', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 15:45:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:45:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:45:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:45:18', 'fActRhValMemo', '54.9000015258789']
['2021-5-4 15:45:18', 'fActCo2ValMemo', '783']
['2021-5-4 15:45:18', 'fActWaterLevelMixTank1', '274.068298339844']
['2021-5-4 15:45:18', 'fActWaterLevelMixTank2', '283.873901367188']
['2021-5-4 15:45:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:45:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:45:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:45:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:45:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:45:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:45:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:45:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:45:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:45:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:45:18', 'DoVa_Co2', '0']
['2021-5-4 15:45:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:45:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:45:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:45:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:45:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:46:19', 'fKWhCounter', '3424.38989257813']
['2021-5-4 15:46:19', 'fActPhLevelMixTank1', '5.63658571243286']
['2021-5-4 15:46:19', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 15:46:19', 'fActPhLevelMixTank2', '3.83355212211609']
['2021-5-4 15:46:19', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 15:46:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:46:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:46:19', 'fActTempValMemo', '22.5']
['2021-5-4 15:46:19', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 15:46:19', 'fActCo2ValMemo', '797']
['2021-5-4 15:46:19', 'fActWaterLevelMixTank1', '275.833831787109']
['2021-5-4 15:46:19', 'fActWaterLevelMixTank2', '284.281341552734']
['2021-5-4 15:46:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:46:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:46:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:46:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:46:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:46:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:46:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:46:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:46:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:46:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:46:19', 'DoVa_Co2', '0']
['2021-5-4 15:46:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:46:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:46:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:46:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:46:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:47:18', 'fKWhCounter', '3424.48999023438']
['2021-5-4 15:47:18', 'fActPhLevelMixTank1', '5.64439821243286']
['2021-5-4 15:47:18', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 15:47:18', 'fActPhLevelMixTank2', '3.83062219619751']
['2021-5-4 15:47:18', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 15:47:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:47:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:47:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:47:18', 'fActRhValMemo', '52.5']
['2021-5-4 15:47:18', 'fActCo2ValMemo', '806']
['2021-5-4 15:47:18', 'fActWaterLevelMixTank1', '276.051147460938']
['2021-5-4 15:47:18', 'fActWaterLevelMixTank2', '284.172698974609']
['2021-5-4 15:47:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:47:18', 'DoPu_AddEcAMixTank_1', '0']

['2021-5-4 15:47:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:47:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:47:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:47:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:47:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:47:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:47:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:47:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:47:18', 'DoVa_Co2', '0']
['2021-5-4 15:47:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:47:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:47:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:47:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:47:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:48:19', 'fKWhCounter', '3424.69018554688']
['2021-5-4 15:48:19', 'fActPhLevelMixTank1', '5.64000368118286']
['2021-5-4 15:48:19', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 15:48:19', 'fActPhLevelMixTank2', '3.83574938774109']
['2021-5-4 15:48:19', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 15:48:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:48:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:48:19', 'fActTempValMemo', '22.5']
['2021-5-4 15:48:19', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 15:48:19', 'fActCo2ValMemo', '812']
['2021-5-4 15:48:19', 'fActWaterLevelMixTank1', '274.394226074219']
['2021-5-4 15:48:19', 'fActWaterLevelMixTank2', '283.982543945313']
['2021-5-4 15:48:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:48:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:48:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:48:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:48:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:48:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:48:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:48:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:48:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:48:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:48:19', 'DoVa_Co2', '0']
['2021-5-4 15:48:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:48:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:48:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:48:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:48:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:49:18', 'fKWhCounter', '3424.79028320313']
['2021-5-4 15:49:18', 'fActPhLevelMixTank1', '5.65050220489502']
['2021-5-4 15:49:18', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 15:49:18', 'fActPhLevelMixTank2', '3.83330798149109']
['2021-5-4 15:49:18', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 15:49:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:49:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:49:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:49:18', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 15:49:18', 'fActCo2ValMemo', '817']
['2021-5-4 15:49:18', 'fActWaterLevelMixTank1', '275.888153076172']
['2021-5-4 15:49:18', 'fActWaterLevelMixTank2', '284.389984130859']
['2021-5-4 15:49:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:49:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:49:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:49:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:49:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:49:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:49:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:49:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:49:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:49:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:49:18', 'DoVa_Co2', '0']
['2021-5-4 15:49:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:49:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:49:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:49:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:49:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:50:19', 'fKWhCounter', '3424.99047851563']
['2021-5-4 15:50:19', 'fActPhLevelMixTank1', '5.64928150177002']
['2021-5-4 15:50:19', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 15:50:19', 'fActPhLevelMixTank2', '3.83623766899109']
['2021-5-4 15:50:19', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 15:50:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:50:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:50:19', 'fActTempValMemo', '22.5']
['2021-5-4 15:50:19', 'fActRhValMemo', '52.4000015258789']
['2021-5-4 15:50:19', 'fActCo2ValMemo', '820']
['2021-5-4 15:50:19', 'fActWaterLevelMixTank1', '276.023986816406']
['2021-5-4 15:50:19', 'fActWaterLevelMixTank2', '283.846740722656']
['2021-5-4 15:50:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:50:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:50:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:50:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:50:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:50:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:50:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:50:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:50:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:50:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:50:19', 'DoVa_Co2', '0']
['2021-5-4 15:50:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:50:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:50:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:50:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:50:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:51:18', 'fKWhCounter', '3425.09057617188']
['2021-5-4 15:51:18', 'fActPhLevelMixTank1', '5.64854907989502']
['2021-5-4 15:51:18', 'fActEcLevelMixTank1', '2027.03942871094']
['2021-5-4 15:51:18', 'fActPhLevelMixTank2', '3.82891321182251']
['2021-5-4 15:51:18', 'fActEcLevelMixTank2', '1038.544921875']
['2021-5-4 15:51:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:51:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:51:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:51:18', 'fActRhValMemo', '52.5']
['2021-5-4 15:51:18', 'fActCo2ValMemo', '818']
['2021-5-4 15:51:18', 'fActWaterLevelMixTank1', '276.023986816406']
['2021-5-4 15:51:18', 'fActWaterLevelMixTank2', '283.846740722656']
['2021-5-4 15:51:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:51:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:51:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:51:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:51:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:51:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:51:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:51:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:51:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:51:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:51:18', 'DoVa_Co2', '0']
['2021-5-4 15:51:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:51:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:51:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:51:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:51:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:52:19', 'fKWhCounter', '3425.29077148438']
['2021-5-4 15:52:19', 'fActPhLevelMixTank1', '5.65294361114502']
['2021-5-4 15:52:19', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 15:52:19', 'fActPhLevelMixTank2', '3.83916735649109']
['2021-5-4 15:52:19', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 15:52:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:52:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:52:19', 'fActTempValMemo', '22.5']
['2021-5-4 15:52:19', 'fActRhValMemo', '52.5']
['2021-5-4 15:52:19', 'fActCo2ValMemo', '820']
['2021-5-4 15:52:19', 'fActWaterLevelMixTank1', '276.32275390625']
['2021-5-4 15:52:19', 'fActWaterLevelMixTank2', '284.688781738281']
['2021-5-4 15:52:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:52:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:52:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:52:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:52:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:52:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:52:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:52:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:52:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:52:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:52:19', 'DoVa_Co2', '0']
['2021-5-4 15:52:19', 'DoVa_IrrigateLevel_3_MT1', '0']

['2021-5-4 15:52:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:52:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:52:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:52:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:53:18', 'fKWhCounter', '3425.39086914063']
['2021-5-4 15:53:18', 'fActPhLevelMixTank1', '5.65709400177002']
['2021-5-4 15:53:18', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 15:53:18', 'fActPhLevelMixTank2', '3.83477282524109']
['2021-5-4 15:53:18', 'fActEcLevelMixTank2', '1038.69750976563']
['2021-5-4 15:53:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:53:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:53:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:53:18', 'fActRhValMemo', '52.5']
['2021-5-4 15:53:18', 'fActCo2ValMemo', '821']
['2021-5-4 15:53:18', 'fActWaterLevelMixTank1', '275.426391601563']
['2021-5-4 15:53:18', 'fActWaterLevelMixTank2', '284.362823486328']
['2021-5-4 15:53:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:53:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:53:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:53:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:53:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:53:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:53:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:53:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:53:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:53:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:53:18', 'DoVa_Co2', '0']
['2021-5-4 15:53:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:53:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:53:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:53:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:53:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:54:19', 'fKWhCounter', '3425.59106445313']
['2021-5-4 15:54:19', 'fActPhLevelMixTank1', '5.65099048614502']
['2021-5-4 15:54:19', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 15:54:19', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 15:54:19', 'fActEcLevelMixTank2', '1016.26635742188']
['2021-5-4 15:54:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:54:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:54:19', 'fActTempValMemo', '22.5']
['2021-5-4 15:54:19', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 15:54:19', 'fActCo2ValMemo', '820']
['2021-5-4 15:54:19', 'fActWaterLevelMixTank1', '276.838836669922']
['2021-5-4 15:54:19', 'fActWaterLevelMixTank2', '284.525787353516']
['2021-5-4 15:54:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:54:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:54:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:54:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:54:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:54:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:54:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:54:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:54:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:54:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:54:19', 'DoVa_Co2', '0']
['2021-5-4 15:54:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:54:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:54:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:54:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:54:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:55:18', 'fKWhCounter', '3425.69116210938']
['2021-5-4 15:55:18', 'fActPhLevelMixTank1', '5.65953540802002']
['2021-5-4 15:55:18', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 15:55:18', 'fActPhLevelMixTank2', '3.83184289932251']
['2021-5-4 15:55:18', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 15:55:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:55:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:55:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:55:18', 'fActRhValMemo', '52']
['2021-5-4 15:55:18', 'fActCo2ValMemo', '820']
['2021-5-4 15:55:18', 'fActWaterLevelMixTank1', '276.865997314453']
['2021-5-4 15:55:18', 'fActWaterLevelMixTank2', '284.607269287109']
['2021-5-4 15:55:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:55:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:55:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:55:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:55:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:55:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:55:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:55:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:55:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:55:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:55:18', 'DoVa_Co2', '0']
['2021-5-4 15:55:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:55:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:55:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:55:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:55:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:56:18', 'fKWhCounter', '3425.89135742188']
['2021-5-4 15:56:18', 'fActPhLevelMixTank1', '5.65099048614502']
['2021-5-4 15:56:18', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 15:56:18', 'fActPhLevelMixTank2', '3.84063243865967']
['2021-5-4 15:56:18', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 15:56:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:56:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:56:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:56:18', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 15:56:18', 'fActCo2ValMemo', '820']
['2021-5-4 15:56:18', 'fActWaterLevelMixTank1', '275.100463867188']
['2021-5-4 15:56:18', 'fActWaterLevelMixTank2', '284.172698974609']
['2021-5-4 15:56:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:56:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:56:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:56:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:56:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:56:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:56:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:56:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:56:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:56:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:56:18', 'DoVa_Co2', '0']
['2021-5-4 15:56:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:56:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:56:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:56:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:56:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:57:18', 'fKWhCounter', '3425.99145507813']
['2021-5-4 15:57:18', 'fActPhLevelMixTank1', '5.65245532989502']
['2021-5-4 15:57:18', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 15:57:18', 'fActPhLevelMixTank2', '3.84185314178467']
['2021-5-4 15:57:18', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 15:57:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:57:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:57:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:57:18', 'fActRhValMemo', '51.5']
['2021-5-4 15:57:18', 'fActCo2ValMemo', '815']
['2021-5-4 15:57:18', 'fActWaterLevelMixTank1', '275.507904052734']
['2021-5-4 15:57:18', 'fActWaterLevelMixTank2', '284.118347167969']
['2021-5-4 15:57:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:57:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:57:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:57:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:57:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:57:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:57:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:57:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:57:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:57:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:57:18', 'DoVa_Co2', '0']
['2021-5-4 15:57:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:57:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:57:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:57:18', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:57:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:58:18', 'fKWhCounter', '3426.09155273438']
['2021-5-4 15:58:18', 'fActPhLevelMixTank1', '5.65709400177002']
['2021-5-4 15:58:18', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 15:58:18', 'fActPhLevelMixTank2', '3.83721423149109']
['2021-5-4 15:58:18', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 15:58:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:58:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:58:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:58:18', 'fActRhValMemo', '51.5']
['2021-5-4 15:58:18', 'fActCo2ValMemo', '815']
['2021-5-4 15:58:18', 'fActWaterLevelMixTank1', '276.947509765625']
['2021-5-4 15:58:18', 'fActWaterLevelMixTank2', '284.308502197266']
['2021-5-4 15:58:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:58:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:58:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:58:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:58:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:58:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:58:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:58:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:58:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:58:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:58:18', 'DoVa_Co2', '0']
['2021-5-4 15:58:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:58:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:58:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:58:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:58:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 15:59:18', 'fKWhCounter', '3426.29174804688']
['2021-5-4 15:59:18', 'fActPhLevelMixTank1', '5.65025806427002']
['2021-5-4 15:59:18', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 15:59:18', 'fActPhLevelMixTank2', '3.83770251274109']
['2021-5-4 15:59:18', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 15:59:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 15:59:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 15:59:18', 'fActTempValMemo', '22.5']
['2021-5-4 15:59:18', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 15:59:18', 'fActCo2ValMemo', '814']
['2021-5-4 15:59:18', 'fActWaterLevelMixTank1', '275.888153076172']
['2021-5-4 15:59:18', 'fActWaterLevelMixTank2', '284.471466064453']
['2021-5-4 15:59:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 15:59:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 15:59:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 15:59:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 15:59:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 15:59:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 15:59:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 15:59:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 15:59:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 15:59:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 15:59:18', 'DoVa_Co2', '0']
['2021-5-4 15:59:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 15:59:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 15:59:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 15:59:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 15:59:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:0:19', 'fKWhCounter', '3426.39184570313']
['2021-5-4 16:0:19', 'fActPhLevelMixTank1', '5.65245532989502']
['2021-5-4 16:0:19', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 16:0:19', 'fActPhLevelMixTank2', '3.83574938774109']
['2021-5-4 16:0:19', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 16:0:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:0:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:0:19', 'fActTempValMemo', '22.5']
['2021-5-4 16:0:19', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 16:0:19', 'fActCo2ValMemo', '812']
['2021-5-4 16:0:19', 'fActWaterLevelMixTank1', '277.490753173828']
['2021-5-4 16:0:19', 'fActWaterLevelMixTank2', '285.014709472656']
['2021-5-4 16:0:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:0:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:0:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:0:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:0:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:0:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:0:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:0:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:0:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:0:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:0:19', 'DoVa_Co2', '0']
['2021-5-4 16:0:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:0:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:0:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:0:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:0:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:1:18', 'fKWhCounter', '3426.59204101563']
['2021-5-4 16:1:18', 'fActPhLevelMixTank1', '5.66075611114502']
['2021-5-4 16:1:18', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 16:1:18', 'fActPhLevelMixTank2', '3.84136486053467']
['2021-5-4 16:1:18', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 16:1:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:1:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:1:18', 'fActTempValMemo', '22.5']
['2021-5-4 16:1:18', 'fActRhValMemo', '51.5']
['2021-5-4 16:1:18', 'fActCo2ValMemo', '812']
['2021-5-4 16:1:18', 'fActWaterLevelMixTank1', '277.762359619141']
['2021-5-4 16:1:18', 'fActWaterLevelMixTank2', '284.824584960938']
['2021-5-4 16:1:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:1:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:1:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:1:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:1:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:1:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:1:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:1:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:1:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:1:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:1:18', 'DoVa_Co2', '0']
['2021-5-4 16:1:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:1:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:1:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:1:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']

['2021-5-4 16:1:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:1:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:2:19', 'fKWhCounter', '3426.69213867188']
['2021-5-4 16:2:19', 'fActPhLevelMixTank1', '5.64757204055786']
['2021-5-4 16:2:19', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 16:2:19', 'fActPhLevelMixTank2', '3.83452868461609']
['2021-5-4 16:2:19', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 16:2:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:2:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:2:19', 'fActTempValMemo', '22.5']
['2021-5-4 16:2:19', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 16:2:19', 'fActCo2ValMemo', '813']
['2021-5-4 16:2:19', 'fActWaterLevelMixTank1', '278.22412109375']
['2021-5-4 16:2:19', 'fActWaterLevelMixTank2', '284.906066894531']
['2021-5-4 16:2:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:2:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:2:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:2:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:2:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:2:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:2:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:2:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:2:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:2:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:2:19', 'DoVa_Co2', '0']
['2021-5-4 16:2:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:2:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:2:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:2:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:2:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:3:18', 'fKWhCounter', '3426.89233398438']
['2021-5-4 16:3:18', 'fActPhLevelMixTank1', '5.65538501739502']
['2021-5-4 16:3:18', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 16:3:18', 'fActPhLevelMixTank2', '3.84185314178467']
['2021-5-4 16:3:18', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 16:3:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:3:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:3:18', 'fActTempValMemo', '22.5']
['2021-5-4 16:3:18', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 16:3:18', 'fActCo2ValMemo', '813']
['2021-5-4 16:3:18', 'fActWaterLevelMixTank1', '278.033996582031']
['2021-5-4 16:3:18', 'fActWaterLevelMixTank2', '285.639465332031']
['2021-5-4 16:3:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:3:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:3:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:3:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:3:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:3:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:3:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:3:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:3:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:3:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:3:18', 'DoVa_Co2', '0']
['2021-5-4 16:3:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:3:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:3:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:3:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:3:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:4:19', 'fKWhCounter', '3426.99243164063']
['2021-5-4 16:4:19', 'fActPhLevelMixTank1', '5.66441869735718']
['2021-5-4 16:4:19', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 16:4:19', 'fActPhLevelMixTank2', '3.83721423149109']
['2021-5-4 16:4:19', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 16:4:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:4:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:4:19', 'fActTempValMemo', '22.5']
['2021-5-4 16:4:19', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 16:4:19', 'fActCo2ValMemo', '812']
['2021-5-4 16:4:19', 'fActWaterLevelMixTank1', '278.332763671875']
['2021-5-4 16:4:19', 'fActWaterLevelMixTank2', '285.856750488281']
['2021-5-4 16:4:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:4:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:4:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:4:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:4:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:4:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:4:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:4:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:4:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:4:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:4:19', 'DoVa_Co2', '0']
['2021-5-4 16:4:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:4:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:4:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:4:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:4:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:5:18', 'fKWhCounter', '3427.19262695313']
['2021-5-4 16:5:18', 'fActPhLevelMixTank1', '5.66051197052002']
['2021-5-4 16:5:18', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 16:5:18', 'fActPhLevelMixTank2', '3.83965563774109']
['2021-5-4 16:5:18', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 16:5:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:5:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:5:18', 'fActTempValMemo', '22.5']
['2021-5-4 16:5:18', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 16:5:18', 'fActCo2ValMemo', '810']
['2021-5-4 16:5:18', 'fActWaterLevelMixTank1', '278.522918701172']
['2021-5-4 16:5:18', 'fActWaterLevelMixTank2', '285.041870117188']
['2021-5-4 16:5:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:5:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:5:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:5:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:5:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:5:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:5:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:5:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:5:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:5:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:5:18', 'DoVa_Co2', '0']
['2021-5-4 16:5:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:5:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:5:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:5:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:5:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:6:19', 'fKWhCounter', '3427.29272460938']
['2021-5-4 16:6:19', 'fActPhLevelMixTank1', '5.65807056427002']
['2021-5-4 16:6:19', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 16:6:19', 'fActPhLevelMixTank2', '3.84136486053467']
['2021-5-4 16:6:19', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 16:6:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:6:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:6:19', 'fActTempValMemo', '22.5']
['2021-5-4 16:6:19', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 16:6:19', 'fActCo2ValMemo', '805']
['2021-5-4 16:6:19', 'fActWaterLevelMixTank1', '278.713043212891']
['2021-5-4 16:6:19', 'fActWaterLevelMixTank2', '286.046875']
['2021-5-4 16:6:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:6:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:6:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:6:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:6:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:6:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:6:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:6:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:6:19', 'DoVa_IrrigateLevel_1_MT2', '0']

['2021-5-4 16:6:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:6:19', 'DoVa_Co2', '0']
['2021-5-4 16:6:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:6:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:6:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:6:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:6:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:7:18', 'fKWhCounter', '3427.49291992188']
['2021-5-4 16:7:18', 'fActPhLevelMixTank1', '5.66978979110718']
['2021-5-4 16:7:18', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 16:7:18', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 16:7:18', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 16:7:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:7:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:7:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 16:7:18', 'fActRhValMemo', '51']
['2021-5-4 16:7:18', 'fActCo2ValMemo', '804']
['2021-5-4 16:7:18', 'fActWaterLevelMixTank1', '277.409271240234']
['2021-5-4 16:7:18', 'fActWaterLevelMixTank2', '285.557952880859']
['2021-5-4 16:7:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:7:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:7:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:7:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:7:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:7:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:7:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:7:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:7:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:7:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:7:18', 'DoVa_Co2', '0']
['2021-5-4 16:7:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:7:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:7:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:7:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:7:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:8:19', 'fKWhCounter', '3427.59301757813']
['2021-5-4 16:8:19', 'fActPhLevelMixTank1', '5.66441869735718']
['2021-5-4 16:8:19', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 16:8:19', 'fActPhLevelMixTank2', '3.84282970428467']
['2021-5-4 16:8:19', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 16:8:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:8:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:8:19', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 16:8:19', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 16:8:19', 'fActCo2ValMemo', '804']
['2021-5-4 16:8:19', 'fActWaterLevelMixTank1', '278.196960449219']
['2021-5-4 16:8:19', 'fActWaterLevelMixTank2', '285.422149658203']
['2021-5-4 16:8:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:8:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:8:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:8:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:8:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:8:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:8:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:8:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:8:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:8:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:8:19', 'DoVa_Co2', '0']
['2021-5-4 16:8:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:8:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:8:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:8:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:8:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:9:18', 'fKWhCounter', '3427.69311523438']
['2021-5-4 16:9:18', 'fActPhLevelMixTank1', '5.59654521942139']
['2021-5-4 16:9:18', 'fActEcLevelMixTank1', '2036.04235839844']
['2021-5-4 16:9:18', 'fActPhLevelMixTank2', '3.7573778629303']
['2021-5-4 16:9:18', 'fActEcLevelMixTank2', '1038.69750976563']
['2021-5-4 16:9:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:9:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:9:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 16:9:18', 'fActRhValMemo', '51']
['2021-5-4 16:9:18', 'fActCo2ValMemo', '802']
['2021-5-4 16:9:18', 'fActWaterLevelMixTank1', '281.320648193359']
['2021-5-4 16:9:18', 'fActWaterLevelMixTank2', '264.805908203125']
['2021-5-4 16:9:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:9:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:9:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:9:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:9:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:9:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:9:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:9:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:9:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:9:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:9:18', 'DoVa_Co2', '0']
['2021-5-4 16:9:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:9:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:9:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:9:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:9:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:10:19', 'fKWhCounter', '3427.89331054688']
['2021-5-4 16:10:19', 'fActPhLevelMixTank1', '5.56089973449707']
['2021-5-4 16:10:19', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 16:10:19', 'fActPhLevelMixTank2', '3.75127410888672']
['2021-5-4 16:10:19', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 16:10:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:10:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:10:19', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 16:10:19', 'fActRhValMemo', '51']
['2021-5-4 16:10:19', 'fActCo2ValMemo', '800']
['2021-5-4 16:10:19', 'fActWaterLevelMixTank1', '276.268432617188']
['2021-5-4 16:10:19', 'fActWaterLevelMixTank2', '284.091186523438']
['2021-5-4 16:10:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:10:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:10:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:10:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:10:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:10:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:10:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:10:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:10:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:10:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:10:19', 'DoVa_Co2', '0']
['2021-5-4 16:10:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:10:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:10:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:10:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:10:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:11:18', 'fKWhCounter', '3428.09350585938']
['2021-5-4 16:11:18', 'fActPhLevelMixTank1', '5.56163215637207']
['2021-5-4 16:11:18', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 16:11:18', 'fActPhLevelMixTank2', '3.75200653076172']
['2021-5-4 16:11:18', 'fActEcLevelMixTank2', '1044.19079589844']

['2021-5-4 16:11:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:11:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:11:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 16:11:18', 'fActRhValMemo', '51']
['2021-5-4 16:11:18', 'fActCo2ValMemo', '803']
['2021-5-4 16:11:18', 'fActWaterLevelMixTank1', '275.915313720703']
['2021-5-4 16:11:18', 'fActWaterLevelMixTank2', '271.433532714844']
['2021-5-4 16:11:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:11:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:11:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:11:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:11:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:11:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:11:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:11:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:11:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:11:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:11:18', 'DoVa_Co2', '0']
['2021-5-4 16:11:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:11:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:11:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:11:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:11:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:12:19', 'fKWhCounter', '3428.29370117188']
['2021-5-4 16:12:19', 'fActPhLevelMixTank1', '5.56797981262207']
['2021-5-4 16:12:19', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 16:12:19', 'fActPhLevelMixTank2', '3.7607958316803']
['2021-5-4 16:12:19', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 16:12:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:12:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:12:19', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 16:12:19', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 16:12:19', 'fActCo2ValMemo', '803']
['2021-5-4 16:12:19', 'fActWaterLevelMixTank1', '267.793792724609']
['2021-5-4 16:12:19', 'fActWaterLevelMixTank2', '284.824584960938']
['2021-5-4 16:12:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:12:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:12:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:12:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:12:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:12:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:12:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:12:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:12:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:12:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:12:19', 'DoVa_Co2', '0']
['2021-5-4 16:12:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:12:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:12:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:12:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:12:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:13:18', 'fKWhCounter', '3428.49389648438']
['2021-5-4 16:13:18', 'fActPhLevelMixTank1', '5.56895637512207']
['2021-5-4 16:13:18', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 16:13:18', 'fActPhLevelMixTank2', '3.76396989822388']
['2021-5-4 16:13:18', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 16:13:18', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:13:18', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:13:18', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 16:13:18', 'fActRhValMemo', '51']
['2021-5-4 16:13:18', 'fActCo2ValMemo', '803']
['2021-5-4 16:13:18', 'fActWaterLevelMixTank1', '269.260559082031']
['2021-5-4 16:13:18', 'fActWaterLevelMixTank2', '296.694549560547']
['2021-5-4 16:13:18', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:13:18', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:13:18', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:13:18', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:13:18', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:13:18', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:13:18', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:13:18', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:13:18', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:13:18', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:13:18', 'DoVa_Co2', '0']
['2021-5-4 16:13:18', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:13:18', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:13:18', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:13:18', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:13:18', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:14:19', 'fKWhCounter', '3428.59399414063']
['2021-5-4 16:14:19', 'fActPhLevelMixTank1', '5.56700325012207']
['2021-5-4 16:14:19', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 16:14:19', 'fActPhLevelMixTank2', '3.78496646881104']
['2021-5-4 16:14:19', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 16:14:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:14:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:14:19', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 16:14:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 16:14:19', 'fActCo2ValMemo', '802']
['2021-5-4 16:14:19', 'fActWaterLevelMixTank1', '268.527160644531']
['2021-5-4 16:14:19', 'fActWaterLevelMixTank2', '278.196960449219']
['2021-5-4 16:14:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:14:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:14:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:14:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:14:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:14:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:14:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:14:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:14:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:14:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:14:19', 'DoVa_Co2', '0']
['2021-5-4 16:14:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:14:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:14:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:14:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:14:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:15:19', 'fKWhCounter', '3428.79418945313']
['2021-5-4 16:15:19', 'fActPhLevelMixTank1', '5.58043146133423']
['2021-5-4 16:15:19', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 16:15:19', 'fActPhLevelMixTank2', '3.82256531715393']
['2021-5-4 16:15:19', 'fActEcLevelMixTank2', '1039.765625']
['2021-5-4 16:15:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:15:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:15:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:15:19', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 16:15:19', 'fActCo2ValMemo', '801']
['2021-5-4 16:15:19', 'fActWaterLevelMixTank1', '268.119720458984']
['2021-5-4 16:15:19', 'fActWaterLevelMixTank2', '277.871002197266']
['2021-5-4 16:15:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:15:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:15:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:15:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:15:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:15:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:15:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:15:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:15:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:15:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:15:19', 'DoVa_Co2', '0']
['2021-5-4 16:15:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:15:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:15:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:15:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:15:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:16:19', 'fKWhCounter', '3428.89428710938']
['2021-5-4 16:16:19', 'fActPhLevelMixTank1', '5.57799005508423']
['2021-5-4 16:16:19', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 16:16:19', 'fActPhLevelMixTank2', '3.81279945373535']
['2021-5-4 16:16:19', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 16:16:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:16:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:16:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:16:19', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 16:16:19', 'fActCo2ValMemo', '798']
['2021-5-4 16:16:19', 'fActWaterLevelMixTank1', '267.902435302734']
['2021-5-4 16:16:19', 'fActWaterLevelMixTank2', '277.898193359375']
['2021-5-4 16:16:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:16:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:16:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:16:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:16:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:16:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:16:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:16:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:16:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:16:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:16:19', 'DoVa_Co2', '0']
['2021-5-4 16:16:19', 'DoVa_IrrigateLevel_3_MT1', '0']

['2021-5-4 16:16:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:16:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:16:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:16:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:17:19', 'fKWhCounter', '3429.09448242188']
['2021-5-4 16:17:19', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 16:17:19', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 16:17:19', 'fActPhLevelMixTank2', '3.80816054344177']
['2021-5-4 16:17:19', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 16:17:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:17:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:17:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:17:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 16:17:19', 'fActCo2ValMemo', '795']
['2021-5-4 16:17:19', 'fActWaterLevelMixTank1', '268.174041748047']
['2021-5-4 16:17:19', 'fActWaterLevelMixTank2', '278.088317871094']
['2021-5-4 16:17:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:17:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:17:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:17:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:17:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:17:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:17:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:17:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:17:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:17:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:17:19', 'DoVa_Co2', '0']
['2021-5-4 16:17:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:17:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:17:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:17:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:17:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:18:19', 'fKWhCounter', '3429.19458007813']
['2021-5-4 16:18:19', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 16:18:19', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 16:18:19', 'fActPhLevelMixTank2', '3.80816054344177']
['2021-5-4 16:18:19', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 16:18:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:18:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:18:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:18:19', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 16:18:19', 'fActCo2ValMemo', '796']
['2021-5-4 16:18:19', 'fActWaterLevelMixTank1', '268.065399169922']
['2021-5-4 16:18:19', 'fActWaterLevelMixTank2', '277.517913818359']
['2021-5-4 16:18:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:18:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:18:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:18:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:18:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:18:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:18:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:18:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:18:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:18:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:18:19', 'DoVa_Co2', '0']
['2021-5-4 16:18:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:18:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:18:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:18:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:18:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:19:19', 'fKWhCounter', '3429.39477539063']
['2021-5-4 16:19:19', 'fActPhLevelMixTank1', '5.57750177383423']
['2021-5-4 16:19:19', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 16:19:19', 'fActPhLevelMixTank2', '3.80864906311035']
['2021-5-4 16:19:19', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 16:19:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:19:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:19:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:19:19', 'fActRhValMemo', '51']
['2021-5-4 16:19:19', 'fActCo2ValMemo', '796']
['2021-5-4 16:19:19', 'fActWaterLevelMixTank1', '268.608642578125']
['2021-5-4 16:19:19', 'fActWaterLevelMixTank2', '277.735198974609']
['2021-5-4 16:19:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:19:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:19:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:19:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:19:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:19:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:19:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:19:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:19:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:19:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:19:19', 'DoVa_Co2', '0']
['2021-5-4 16:19:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:19:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:19:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:19:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:19:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:20:19', 'fKWhCounter', '3429.49487304688']
['2021-5-4 16:20:19', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 16:20:19', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 16:20:19', 'fActPhLevelMixTank2', '3.80889320373535']
['2021-5-4 16:20:19', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 16:20:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:20:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:20:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:20:19', 'fActRhValMemo', '51']
['2021-5-4 16:20:19', 'fActCo2ValMemo', '795']
['2021-5-4 16:20:19', 'fActWaterLevelMixTank1', '268.961761474609']
['2021-5-4 16:20:19', 'fActWaterLevelMixTank2', '278.196960449219']
['2021-5-4 16:20:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:20:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:20:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:20:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:20:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:20:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:20:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:20:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:20:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:20:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:20:19', 'DoVa_Co2', '0']
['2021-5-4 16:20:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:20:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:20:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:20:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:20:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:21:19', 'fKWhCounter', '3429.59497070313']
['2021-5-4 16:21:19', 'fActPhLevelMixTank1', '5.57628107070923']
['2021-5-4 16:21:19', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 16:21:19', 'fActPhLevelMixTank2', '3.80401015281677']
['2021-5-4 16:21:19', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 16:21:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:21:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:21:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:21:19', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 16:21:19', 'fActCo2ValMemo', '793']
['2021-5-4 16:21:19', 'fActWaterLevelMixTank1', '268.635803222656']
['2021-5-4 16:21:19', 'fActWaterLevelMixTank2', '277.952514648438']
['2021-5-4 16:21:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:21:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:21:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:21:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:21:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:21:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:21:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:21:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:21:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:21:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:21:19', 'DoVa_Co2', '0']
['2021-5-4 16:21:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:21:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:21:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:21:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_2_Blue', '0']

['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:21:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:22:19', 'fKWhCounter', '3429.79516601563']
['2021-5-4 16:22:19', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 16:22:19', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 16:22:19', 'fActPhLevelMixTank2', '3.80303359031677']
['2021-5-4 16:22:19', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 16:22:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:22:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:22:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:22:19', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 16:22:19', 'fActCo2ValMemo', '791']
['2021-5-4 16:22:19', 'fActWaterLevelMixTank1', '269.124725341797']
['2021-5-4 16:22:19', 'fActWaterLevelMixTank2', '277.952514648438']
['2021-5-4 16:22:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:22:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:22:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:22:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:22:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:22:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:22:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:22:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:22:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:22:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:22:19', 'DoVa_Co2', '0']
['2021-5-4 16:22:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:22:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:22:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:22:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:22:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:23:19', 'fKWhCounter', '3429.89526367188']
['2021-5-4 16:23:19', 'fActPhLevelMixTank1', '5.57335138320923']
['2021-5-4 16:23:19', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 16:23:19', 'fActPhLevelMixTank2', '3.80449843406677']
['2021-5-4 16:23:19', 'fActEcLevelMixTank2', '1023.43823242188']
['2021-5-4 16:23:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:23:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:23:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:23:19', 'fActRhValMemo', '51']
['2021-5-4 16:23:19', 'fActCo2ValMemo', '794']
['2021-5-4 16:23:19', 'fActWaterLevelMixTank1', '267.603637695313']
['2021-5-4 16:23:19', 'fActWaterLevelMixTank2', '277.545074462891']
['2021-5-4 16:23:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:23:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:23:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:23:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:23:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:23:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:23:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:23:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:23:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:23:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:23:19', 'DoVa_Co2', '0']
['2021-5-4 16:23:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:23:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:23:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:23:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:23:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:24:19', 'fKWhCounter', '3430.09545898438']
['2021-5-4 16:24:19', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 16:24:19', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 16:24:19', 'fActPhLevelMixTank2', '3.80230116844177']
['2021-5-4 16:24:19', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 16:24:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:24:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:24:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:24:19', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 16:24:19', 'fActCo2ValMemo', '793']
['2021-5-4 16:24:19', 'fActWaterLevelMixTank1', '269.586486816406']
['2021-5-4 16:24:19', 'fActWaterLevelMixTank2', '277.952514648438']
['2021-5-4 16:24:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:24:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:24:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:24:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:24:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:24:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:24:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:24:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:24:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:24:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:24:19', 'DoVa_Co2', '0']
['2021-5-4 16:24:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:24:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:24:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:24:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:24:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:25:19', 'fKWhCounter', '3430.19555664063']

['2021-5-4 16:25:19', 'fActPhLevelMixTank1', '5.57823419570923']
['2021-5-4 16:25:19', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 16:25:19', 'fActPhLevelMixTank2', '3.80010366439819']
['2021-5-4 16:25:19', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 16:25:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:25:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:25:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:25:19', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 16:25:19', 'fActCo2ValMemo', '793']
['2021-5-4 16:25:19', 'fActWaterLevelMixTank1', '269.993927001953']
['2021-5-4 16:25:19', 'fActWaterLevelMixTank2', '277.789520263672']
['2021-5-4 16:25:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:25:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:25:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:25:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:25:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:25:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:25:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:25:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:25:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:25:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:25:19', 'DoVa_Co2', '0']
['2021-5-4 16:25:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:25:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:25:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:25:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:25:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:26:19', 'fKWhCounter', '3430.39575195313']
['2021-5-4 16:26:19', 'fActPhLevelMixTank1', '5.57335138320923']
['2021-5-4 16:26:19', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 16:26:19', 'fActPhLevelMixTank2', '3.80767226219177']
['2021-5-4 16:26:19', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 16:26:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:26:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:26:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:26:19', 'fActRhValMemo', '51']
['2021-5-4 16:26:19', 'fActCo2ValMemo', '791']
['2021-5-4 16:26:19', 'fActWaterLevelMixTank1', '270.890289306641']
['2021-5-4 16:26:19', 'fActWaterLevelMixTank2', '278.604400634766']
['2021-5-4 16:26:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:26:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:26:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:26:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:26:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:26:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:26:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:26:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:26:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:26:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:26:19', 'DoVa_Co2', '0']
['2021-5-4 16:26:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:26:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:26:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:26:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:26:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:27:19', 'fKWhCounter', '3430.49584960938']
['2021-5-4 16:27:19', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 16:27:19', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 16:27:19', 'fActPhLevelMixTank2', '3.80108046531677']
['2021-5-4 16:27:19', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 16:27:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:27:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:27:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:27:19', 'fActRhValMemo', '51']
['2021-5-4 16:27:19', 'fActCo2ValMemo', '790']
['2021-5-4 16:27:19', 'fActWaterLevelMixTank1', '269.640808105469']
['2021-5-4 16:27:19', 'fActWaterLevelMixTank2', '278.821685791016']
['2021-5-4 16:27:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:27:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:27:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:27:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:27:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:27:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:27:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:27:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:27:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:27:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:27:19', 'DoVa_Co2', '0']
['2021-5-4 16:27:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:27:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:27:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:27:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:27:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:28:19', 'fKWhCounter', '3430.69604492188']
['2021-5-4 16:28:19', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 16:28:19', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 16:28:19', 'fActPhLevelMixTank2', '3.80791640281677']
['2021-5-4 16:28:19', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 16:28:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:28:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:28:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:28:19', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 16:28:19', 'fActCo2ValMemo', '789']
['2021-5-4 16:28:19', 'fActWaterLevelMixTank1', '271.161926269531']
['2021-5-4 16:28:19', 'fActWaterLevelMixTank2', '278.713043212891']
['2021-5-4 16:28:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:28:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:28:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:28:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:28:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:28:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:28:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:28:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:28:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:28:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:28:19', 'DoVa_Co2', '0']
['2021-5-4 16:28:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:28:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:28:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:28:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:28:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:29:19', 'fKWhCounter', '3430.79614257813']
['2021-5-4 16:29:19', 'fActPhLevelMixTank1', '5.58580255508423']
['2021-5-4 16:29:19', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 16:29:19', 'fActPhLevelMixTank2', '3.80303359031677']
['2021-5-4 16:29:19', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 16:29:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:29:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:29:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:29:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 16:29:19', 'fActCo2ValMemo', '791']
['2021-5-4 16:29:19', 'fActWaterLevelMixTank1', '271.107574462891']
['2021-5-4 16:29:19', 'fActWaterLevelMixTank2', '278.604400634766']
['2021-5-4 16:29:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:29:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:29:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:29:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:29:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:29:19', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 16:29:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:29:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:29:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:29:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:29:19', 'DoVa_Co2', '0']
['2021-5-4 16:29:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:29:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:29:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:29:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:29:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:30:19', 'fKWhCounter', '3430.89624023438']
['2021-5-4 16:30:19', 'fActPhLevelMixTank1', '5.59044170379639']
['2021-5-4 16:30:19', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 16:30:19', 'fActPhLevelMixTank2', '3.80767226219177']
['2021-5-4 16:30:19', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 16:30:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:30:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:30:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:30:19', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 16:30:19', 'fActCo2ValMemo', '791']
['2021-5-4 16:30:19', 'fActWaterLevelMixTank1', '270.102569580078']
['2021-5-4 16:30:19', 'fActWaterLevelMixTank2', '278.414276123047']
['2021-5-4 16:30:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:30:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:30:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:30:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:30:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:30:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:30:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:30:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:30:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:30:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:30:19', 'DoVa_Co2', '0']
['2021-5-4 16:30:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:30:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:30:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:30:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:30:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:31:19', 'fKWhCounter', '3431.09643554688']
['2021-5-4 16:31:19', 'fActPhLevelMixTank1', '5.59190654754639']
['2021-5-4 16:31:19', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 16:31:19', 'fActPhLevelMixTank2', '3.80669569969177']
['2021-5-4 16:31:19', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 16:31:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:31:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:31:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:31:19', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 16:31:19', 'fActCo2ValMemo', '790']
['2021-5-4 16:31:19', 'fActWaterLevelMixTank1', '271.840972900391']
['2021-5-4 16:31:19', 'fActWaterLevelMixTank2', '279.636566162109']
['2021-5-4 16:31:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:31:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:31:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:31:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:31:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:31:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:31:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:31:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:31:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:31:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:31:19', 'DoVa_Co2', '0']
['2021-5-4 16:31:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:31:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:31:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:31:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:31:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:32:19', 'fKWhCounter', '3431.19653320313']
['2021-5-4 16:32:19', 'fActPhLevelMixTank1', '5.59727764129639']
['2021-5-4 16:32:19', 'fActEcLevelMixTank1', '2015.28979492188']
['2021-5-4 16:32:19', 'fActPhLevelMixTank2', '3.80693984031677']
['2021-5-4 16:32:19', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 16:32:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:32:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:32:19', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 16:32:19', 'fActRhValMemo', '50.5']
['2021-5-4 16:32:19', 'fActCo2ValMemo', '787']
['2021-5-4 16:32:19', 'fActWaterLevelMixTank1', '271.840972900391']
['2021-5-4 16:32:19', 'fActWaterLevelMixTank2', '279.419281005859']
['2021-5-4 16:32:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:32:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:32:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:32:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:32:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:32:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:32:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:32:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:32:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:32:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:32:19', 'DoVa_Co2', '0']
['2021-5-4 16:32:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:32:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:32:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:32:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:32:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:33:19', 'fKWhCounter', '3431.39672851563']
['2021-5-4 16:33:19', 'fActPhLevelMixTank1', '5.59532451629639']
['2021-5-4 16:33:19', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 16:33:19', 'fActPhLevelMixTank2', '3.81572914123535']
['2021-5-4 16:33:19', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 16:33:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:33:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:33:19', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 16:33:19', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 16:33:19', 'fActCo2ValMemo', '787']
['2021-5-4 16:33:19', 'fActWaterLevelMixTank1', '270.673004150391']
['2021-5-4 16:33:19', 'fActWaterLevelMixTank2', '279.527923583984']
['2021-5-4 16:33:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:33:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:33:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:33:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:33:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:33:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:33:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:33:19', 'DoVa_IrrigateLevel_2_MT1', '0']

['2021-5-4 16:33:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:33:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:33:19', 'DoVa_Co2', '0']
['2021-5-4 16:33:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:33:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:33:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:33:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:33:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:34:19', 'fKWhCounter', '3431.49682617188']
['2021-5-4 16:34:19', 'fActPhLevelMixTank1', '5.60118389129639']
['2021-5-4 16:34:19', 'fActEcLevelMixTank1', '2016.6630859375']
['2021-5-4 16:34:19', 'fActPhLevelMixTank2', '3.81157875061035']
['2021-5-4 16:34:19', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 16:34:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:34:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:34:19', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 16:34:19', 'fActRhValMemo', '50.5']
['2021-5-4 16:34:19', 'fActCo2ValMemo', '785']
['2021-5-4 16:34:19', 'fActWaterLevelMixTank1', '270.781646728516']
['2021-5-4 16:34:19', 'fActWaterLevelMixTank2', '279.337799072266']
['2021-5-4 16:34:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:34:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:34:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:34:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:34:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:34:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:34:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:34:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:34:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:34:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:34:19', 'DoVa_Co2', '0']
['2021-5-4 16:34:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:34:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:34:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:34:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:34:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:35:19', 'fKWhCounter', '3431.69702148438']
['2021-5-4 16:35:19', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 16:35:19', 'fActEcLevelMixTank1', '2016.052734375']
['2021-5-4 16:35:19', 'fActPhLevelMixTank2', '3.81475257873535']
['2021-5-4 16:35:19', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 16:35:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:35:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:35:19', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 16:35:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 16:35:19', 'fActCo2ValMemo', '788']
['2021-5-4 16:35:19', 'fActWaterLevelMixTank1', '272.981781005859']
['2021-5-4 16:35:19', 'fActWaterLevelMixTank2', '280.071166992188']
['2021-5-4 16:35:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:35:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:35:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:35:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:35:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:35:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:35:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:35:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:35:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:35:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:35:19', 'DoVa_Co2', '0']
['2021-5-4 16:35:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:35:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:35:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:35:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:35:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:36:19', 'fKWhCounter', '3431.79711914063']
['2021-5-4 16:36:19', 'fActPhLevelMixTank1', '5.59141826629639']
['2021-5-4 16:36:19', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 16:36:19', 'fActPhLevelMixTank2', '3.81524085998535']
['2021-5-4 16:36:19', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 16:36:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:36:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:36:19', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 16:36:19', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 16:36:19', 'fActCo2ValMemo', '783']
['2021-5-4 16:36:19', 'fActWaterLevelMixTank1', '273.525024414063']
['2021-5-4 16:36:19', 'fActWaterLevelMixTank2', '280.044006347656']
['2021-5-4 16:36:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:36:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:36:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:36:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:36:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:36:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:36:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:36:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:36:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:36:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:36:19', 'DoVa_Co2', '0']
['2021-5-4 16:36:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:36:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:36:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:36:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:36:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:37:19', 'fKWhCounter', '3431.99731445313']
['2021-5-4 16:37:19', 'fActPhLevelMixTank1', '5.60411405563354']
['2021-5-4 16:37:19', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 16:37:19', 'fActPhLevelMixTank2', '3.81963562965393']
['2021-5-4 16:37:19', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 16:37:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:37:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:37:19', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 16:37:19', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 16:37:19', 'fActCo2ValMemo', '781']
['2021-5-4 16:37:19', 'fActWaterLevelMixTank1', '273.796661376953']
['2021-5-4 16:37:19', 'fActWaterLevelMixTank2', '280.397125244141']
['2021-5-4 16:37:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:37:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:37:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:37:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:37:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:37:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:37:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:37:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:37:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:37:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:37:19', 'DoVa_Co2', '0']
['2021-5-4 16:37:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:37:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:37:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:37:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:37:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:38:19', 'fKWhCounter', '3432.09741210938']
['2021-5-4 16:38:19', 'fActPhLevelMixTank1', '5.60484647750854']
['2021-5-4 16:38:19', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 16:38:19', 'fActPhLevelMixTank2', '3.82232117652893']
['2021-5-4 16:38:19', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 16:38:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:38:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:38:19', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 16:38:19', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 16:38:19', 'fActCo2ValMemo', '780']
['2021-5-4 16:38:19', 'fActWaterLevelMixTank1', '273.334899902344']
['2021-5-4 16:38:19', 'fActWaterLevelMixTank2', '279.989685058594']
['2021-5-4 16:38:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:38:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:38:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:38:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:38:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:38:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:38:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:38:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:38:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:38:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:38:19', 'DoVa_Co2', '0']
['2021-5-4 16:38:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:38:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:38:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:38:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_4_Red', '0']

['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:38:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:39:19', 'fKWhCounter', '3432.19750976563']
['2021-5-4 16:39:19', 'fActPhLevelMixTank1', '5.59678936004639']
['2021-5-4 16:39:19', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 16:39:19', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 16:39:19', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 16:39:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:39:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:39:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:39:19', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 16:39:19', 'fActCo2ValMemo', '780']
['2021-5-4 16:39:19', 'fActWaterLevelMixTank1', '274.122619628906']
['2021-5-4 16:39:19', 'fActWaterLevelMixTank2', '280.994689941406']
['2021-5-4 16:39:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:39:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:39:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:39:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:39:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:39:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:39:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:39:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:39:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:39:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:39:19', 'DoVa_Co2', '0']
['2021-5-4 16:39:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:39:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:39:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:39:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:39:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:40:19', 'fKWhCounter', '3432.39770507813']
['2021-5-4 16:40:19', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 16:40:19', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 16:40:19', 'fActPhLevelMixTank2', '3.82378602027893']
['2021-5-4 16:40:19', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 16:40:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:40:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:40:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:40:19', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 16:40:19', 'fActCo2ValMemo', '779']
['2021-5-4 16:40:19', 'fActWaterLevelMixTank1', '274.530059814453']
['2021-5-4 16:40:19', 'fActWaterLevelMixTank2', '280.695892333984']
['2021-5-4 16:40:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:40:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:40:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:40:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:40:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:40:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:40:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:40:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:40:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:40:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:40:19', 'DoVa_Co2', '0']
['2021-5-4 16:40:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:40:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:40:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:40:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:40:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:41:19', 'fKWhCounter', '3432.49780273438']
['2021-5-4 16:41:19', 'fActPhLevelMixTank1', '5.59849834442139']
['2021-5-4 16:41:19', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 16:41:19', 'fActPhLevelMixTank2', '3.81670594215393']
['2021-5-4 16:41:19', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 16:41:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:41:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:41:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:41:19', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 16:41:19', 'fActCo2ValMemo', '779']
['2021-5-4 16:41:19', 'fActWaterLevelMixTank1', '274.747344970703']
['2021-5-4 16:41:19', 'fActWaterLevelMixTank2', '281.537933349609']
['2021-5-4 16:41:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:41:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:41:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:41:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:41:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:41:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:41:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:41:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:41:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:41:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:41:19', 'DoVa_Co2', '0']
['2021-5-4 16:41:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:41:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:41:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:41:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:41:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:42:19', 'fKWhCounter', '3432.69799804688']
['2021-5-4 16:42:19', 'fActPhLevelMixTank1', '5.60045146942139']
['2021-5-4 16:42:19', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 16:42:19', 'fActPhLevelMixTank2', '3.81963562965393']
['2021-5-4 16:42:19', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 16:42:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:42:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:42:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:42:19', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 16:42:19', 'fActCo2ValMemo', '777']
['2021-5-4 16:42:19', 'fActWaterLevelMixTank1', '274.991790771484']
['2021-5-4 16:42:19', 'fActWaterLevelMixTank2', '281.239135742188']
['2021-5-4 16:42:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:42:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:42:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:42:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:42:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:42:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:42:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:42:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:42:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:42:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:42:19', 'DoVa_Co2', '0']
['2021-5-4 16:42:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:42:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:42:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:42:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:42:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:43:19', 'fKWhCounter', '3432.79809570313']
['2021-5-4 16:43:19', 'fActPhLevelMixTank1', '5.60142803192139']
['2021-5-4 16:43:19', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 16:43:19', 'fActPhLevelMixTank2', '3.81914734840393']
['2021-5-4 16:43:19', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 16:43:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:43:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:43:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:43:19', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 16:43:19', 'fActCo2ValMemo', '776']
['2021-5-4 16:43:19', 'fActWaterLevelMixTank1', '275.779510498047']
['2021-5-4 16:43:19', 'fActWaterLevelMixTank2', '281.592254638672']
['2021-5-4 16:43:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:43:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:43:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:43:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:43:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:43:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:43:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:43:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:43:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:43:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:43:19', 'DoVa_Co2', '0']
['2021-5-4 16:43:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:43:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:43:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:43:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_3_Fred', '0']

['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:43:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:44:19', 'fKWhCounter', '3432.99829101563']
['2021-5-4 16:44:19', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 16:44:19', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 16:44:19', 'fActPhLevelMixTank2', '3.82158875465393']
['2021-5-4 16:44:19', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 16:44:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:44:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:44:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:44:19', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 16:44:19', 'fActCo2ValMemo', '772']
['2021-5-4 16:44:19', 'fActWaterLevelMixTank1', '274.176940917969']
['2021-5-4 16:44:19', 'fActWaterLevelMixTank2', '281.646575927734']
['2021-5-4 16:44:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:44:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:44:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:44:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:44:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:44:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:44:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:44:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:44:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:44:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:44:19', 'DoVa_Co2', '0']
['2021-5-4 16:44:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:44:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:44:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:44:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:44:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:45:19', 'fKWhCounter', '3433.09838867188']
['2021-5-4 16:45:19', 'fActPhLevelMixTank1', '5.60142803192139']
['2021-5-4 16:45:19', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 16:45:19', 'fActPhLevelMixTank2', '3.82573938369751']
['2021-5-4 16:45:19', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 16:45:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:45:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:45:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:45:19', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 16:45:19', 'fActCo2ValMemo', '771']
['2021-5-4 16:45:19', 'fActWaterLevelMixTank1', '276.32275390625']
['2021-5-4 16:45:19', 'fActWaterLevelMixTank2', '282.108337402344']
['2021-5-4 16:45:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:45:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:45:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:45:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:45:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:45:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:45:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:45:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:45:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:45:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:45:19', 'DoVa_Co2', '0']
['2021-5-4 16:45:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:45:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:45:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:45:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:45:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:46:19', 'fKWhCounter', '3433.19848632813']
['2021-5-4 16:46:19', 'fActPhLevelMixTank1', '5.60509061813354']
['2021-5-4 16:46:19', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 16:46:19', 'fActPhLevelMixTank2', '3.81865906715393']
['2021-5-4 16:46:19', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 16:46:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:46:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:46:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:46:19', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 16:46:19', 'fActCo2ValMemo', '770']
['2021-5-4 16:46:19', 'fActWaterLevelMixTank1', '274.801666259766']
['2021-5-4 16:46:19', 'fActWaterLevelMixTank2', '282.515777587891']
['2021-5-4 16:46:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:46:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:46:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:46:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:46:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:46:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:46:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:46:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:46:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:46:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:46:19', 'DoVa_Co2', '0']
['2021-5-4 16:46:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:46:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:46:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:46:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:46:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:47:19', 'fKWhCounter', '3433.39868164063']
['2021-5-4 16:47:19', 'fActPhLevelMixTank1', '5.61314725875854']
['2021-5-4 16:47:19', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 16:47:19', 'fActPhLevelMixTank2', '3.82525110244751']
['2021-5-4 16:47:19', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 16:47:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:47:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:47:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:47:19', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 16:47:19', 'fActCo2ValMemo', '768']
['2021-5-4 16:47:19', 'fActWaterLevelMixTank1', '276.159790039063']
['2021-5-4 16:47:19', 'fActWaterLevelMixTank2', '282.298492431641']
['2021-5-4 16:47:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:47:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:47:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:47:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:47:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:47:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:47:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:47:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:47:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:47:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:47:19', 'DoVa_Co2', '0']
['2021-5-4 16:47:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:47:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:47:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:47:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:47:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:48:19', 'fKWhCounter', '3433.49877929688']
['2021-5-4 16:48:19', 'fActPhLevelMixTank1', '5.61021757125854']
['2021-5-4 16:48:19', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 16:48:19', 'fActPhLevelMixTank2', '3.81865906715393']
['2021-5-4 16:48:19', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 16:48:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:48:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:48:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:48:19', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 16:48:19', 'fActCo2ValMemo', '768']
['2021-5-4 16:48:19', 'fActWaterLevelMixTank1', '274.883148193359']
['2021-5-4 16:48:19', 'fActWaterLevelMixTank2', '281.863891601563']
['2021-5-4 16:48:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:48:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:48:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:48:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:48:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:48:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:48:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:48:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:48:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:48:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:48:19', 'DoVa_Co2', '0']
['2021-5-4 16:48:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:48:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:48:19', 'DoVa_IrrigateLevel_3_MT2', '0']

['2021-5-4 16:48:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:48:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:49:19', 'fKWhCounter', '3433.69897460938']
['2021-5-4 16:49:19', 'fActPhLevelMixTank1', '5.60875272750854']
['2021-5-4 16:49:19', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 16:49:19', 'fActPhLevelMixTank2', '3.82476282119751']
['2021-5-4 16:49:19', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 16:49:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:49:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:49:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:49:19', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 16:49:19', 'fActCo2ValMemo', '771']
['2021-5-4 16:49:19', 'fActWaterLevelMixTank1', '276.32275390625']
['2021-5-4 16:49:19', 'fActWaterLevelMixTank2', '281.972534179688']
['2021-5-4 16:49:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:49:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:49:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:49:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:49:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:49:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:49:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:49:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:49:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:49:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:49:19', 'DoVa_Co2', '0']
['2021-5-4 16:49:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:49:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:49:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:49:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:49:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:50:19', 'fKWhCounter', '3433.79907226563']
['2021-5-4 16:50:19', 'fActPhLevelMixTank1', '5.61363554000854']
['2021-5-4 16:50:19', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 16:50:19', 'fActPhLevelMixTank2', '3.82525110244751']
['2021-5-4 16:50:19', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 16:50:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:50:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:50:19', 'fActTempValMemo', '22.1000003814697']
['2021-5-4 16:50:19', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 16:50:19', 'fActCo2ValMemo', '768']
['2021-5-4 16:50:19', 'fActWaterLevelMixTank1', '276.865997314453']
['2021-5-4 16:50:19', 'fActWaterLevelMixTank2', '282.678741455078']
['2021-5-4 16:50:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:50:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:50:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:50:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:50:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:50:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:50:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:50:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:50:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:50:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:50:19', 'DoVa_Co2', '0']
['2021-5-4 16:50:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:50:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:50:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:50:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:50:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:51:19', 'fKWhCounter', '3433.99926757813']
['2021-5-4 16:51:19', 'fActPhLevelMixTank1', '5.61583280563354']
['2021-5-4 16:51:19', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 16:51:19', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 16:51:19', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 16:51:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:51:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:51:19', 'fActTempValMemo', '22']
['2021-5-4 16:51:19', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 16:51:19', 'fActCo2ValMemo', '767']
['2021-5-4 16:51:19', 'fActWaterLevelMixTank1', '276.023986816406']
['2021-5-4 16:51:19', 'fActWaterLevelMixTank2', '283.330657958984']
['2021-5-4 16:51:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:51:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:51:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:51:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:51:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:51:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:51:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:51:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:51:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:51:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:51:19', 'DoVa_Co2', '0']
['2021-5-4 16:51:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:51:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:51:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:51:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:51:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:52:19', 'fKWhCounter', '3434.09936523438']
['2021-5-4 16:52:19', 'fActPhLevelMixTank1', '5.61363554000854']
['2021-5-4 16:52:19', 'fActEcLevelMixTank1', '2003.23498535156']
['2021-5-4 16:52:19', 'fActPhLevelMixTank2', '3.82427453994751']
['2021-5-4 16:52:19', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 16:52:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:52:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:52:19', 'fActTempValMemo', '22']
['2021-5-4 16:52:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 16:52:19', 'fActCo2ValMemo', '765']
['2021-5-4 16:52:19', 'fActWaterLevelMixTank1', '278.088317871094']
['2021-5-4 16:52:19', 'fActWaterLevelMixTank2', '283.439300537109']
['2021-5-4 16:52:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:52:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:52:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:52:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:52:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:52:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:52:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:52:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:52:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:52:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:52:19', 'DoVa_Co2', '0']
['2021-5-4 16:52:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:52:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:52:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:52:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:52:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:53:19', 'fKWhCounter', '3434.29956054688']
['2021-5-4 16:53:19', 'fActPhLevelMixTank1', '5.6214485168457']
['2021-5-4 16:53:19', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 16:53:19', 'fActPhLevelMixTank2', '3.81865906715393']
['2021-5-4 16:53:19', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 16:53:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:53:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:53:19', 'fActTempValMemo', '22']
['2021-5-4 16:53:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 16:53:19', 'fActCo2ValMemo', '761']

['2021-5-4 16:53:19', 'fActWaterLevelMixTank1', '278.495758056641']
['2021-5-4 16:53:19', 'fActWaterLevelMixTank2', '283.792419433594']
['2021-5-4 16:53:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:53:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:53:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:53:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:53:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:53:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:53:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:53:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:53:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:53:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:53:19', 'DoVa_Co2', '0']
['2021-5-4 16:53:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:53:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:53:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:53:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:53:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:54:19', 'fKWhCounter', '3434.39965820313']
['2021-5-4 16:54:19', 'fActPhLevelMixTank1', '5.6263313293457']
['2021-5-4 16:54:19', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 16:54:19', 'fActPhLevelMixTank2', '3.82525110244751']
['2021-5-4 16:54:19', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 16:54:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:54:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:54:19', 'fActTempValMemo', '22']
['2021-5-4 16:54:19', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 16:54:19', 'fActCo2ValMemo', '759']
['2021-5-4 16:54:19', 'fActWaterLevelMixTank1', '278.658721923828']
['2021-5-4 16:54:19', 'fActWaterLevelMixTank2', '284.172698974609']
['2021-5-4 16:54:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:54:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:54:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:54:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:54:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:54:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:54:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:54:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:54:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:54:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:54:19', 'DoVa_Co2', '0']
['2021-5-4 16:54:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:54:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:54:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:54:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:54:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:55:19', 'fKWhCounter', '3434.49975585938']
['2021-5-4 16:55:19', 'fActPhLevelMixTank1', '5.6231575012207']
['2021-5-4 16:55:19', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 16:55:19', 'fActPhLevelMixTank2', '3.82476282119751']
['2021-5-4 16:55:19', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 16:55:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:55:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:55:19', 'fActTempValMemo', '22']
['2021-5-4 16:55:19', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 16:55:19', 'fActCo2ValMemo', '760']
['2021-5-4 16:55:19', 'fActWaterLevelMixTank1', '279.364959716797']
['2021-5-4 16:55:19', 'fActWaterLevelMixTank2', '283.955383300781']
['2021-5-4 16:55:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:55:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:55:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:55:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:55:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:55:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:55:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:55:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:55:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:55:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:55:19', 'DoVa_Co2', '0']
['2021-5-4 16:55:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:55:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:55:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:55:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:55:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:56:19', 'fKWhCounter', '3434.69995117188']
['2021-5-4 16:56:19', 'fActPhLevelMixTank1', '5.6307258605957']
['2021-5-4 16:56:19', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 16:56:19', 'fActPhLevelMixTank2', '3.82866907119751']
['2021-5-4 16:56:19', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 16:56:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:56:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:56:19', 'fActTempValMemo', '22']
['2021-5-4 16:56:19', 'fActRhValMemo', '50.5']
['2021-5-4 16:56:19', 'fActCo2ValMemo', '758']
['2021-5-4 16:56:19', 'fActWaterLevelMixTank1', '278.522918701172']
['2021-5-4 16:56:19', 'fActWaterLevelMixTank2', '284.362823486328']
['2021-5-4 16:56:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:56:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:56:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:56:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:56:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:56:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:56:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:56:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:56:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:56:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:56:19', 'DoVa_Co2', '0']
['2021-5-4 16:56:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:56:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:56:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:56:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:56:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:57:19', 'fKWhCounter', '3434.80004882813']
['2021-5-4 16:57:19', 'fActPhLevelMixTank1', '5.6255989074707']
['2021-5-4 16:57:19', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 16:57:19', 'fActPhLevelMixTank2', '3.82134461402893']
['2021-5-4 16:57:19', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 16:57:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:57:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:57:19', 'fActTempValMemo', '22']
['2021-5-4 16:57:19', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 16:57:19', 'fActCo2ValMemo', '757']
['2021-5-4 16:57:19', 'fActWaterLevelMixTank1', '279.881042480469']
['2021-5-4 16:57:19', 'fActWaterLevelMixTank2', '284.389984130859']
['2021-5-4 16:57:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:57:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:57:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:57:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:57:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:57:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:57:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:57:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:57:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:57:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:57:19', 'DoVa_Co2', '0']
['2021-5-4 16:57:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:57:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:57:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:57:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_1_Blue', '0']

['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:57:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:58:19', 'fKWhCounter', '3435.00024414063']
['2021-5-4 16:58:19', 'fActPhLevelMixTank1', '5.6260871887207']
['2021-5-4 16:58:19', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 16:58:19', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 16:58:19', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 16:58:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:58:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:58:19', 'fActTempValMemo', '22']
['2021-5-4 16:58:19', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 16:58:19', 'fActCo2ValMemo', '757']
['2021-5-4 16:58:19', 'fActWaterLevelMixTank1', '279.500762939453']
['2021-5-4 16:58:19', 'fActWaterLevelMixTank2', '284.525787353516']
['2021-5-4 16:58:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:58:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:58:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:58:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:58:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:58:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:58:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:58:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:58:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:58:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:58:19', 'DoVa_Co2', '0']
['2021-5-4 16:58:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:58:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:58:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:58:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:58:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 16:59:19', 'fKWhCounter', '3435.10034179688']
['2021-5-4 16:59:19', 'fActPhLevelMixTank1', '5.6319465637207']
['2021-5-4 16:59:19', 'fActEcLevelMixTank1', '2027.03942871094']
['2021-5-4 16:59:19', 'fActPhLevelMixTank2', '3.82964563369751']
['2021-5-4 16:59:19', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 16:59:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 16:59:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 16:59:19', 'fActTempValMemo', '22']
['2021-5-4 16:59:19', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 16:59:19', 'fActCo2ValMemo', '754']
['2021-5-4 16:59:19', 'fActWaterLevelMixTank1', '278.713043212891']
['2021-5-4 16:59:19', 'fActWaterLevelMixTank2', '284.634460449219']
['2021-5-4 16:59:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 16:59:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 16:59:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 16:59:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 16:59:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 16:59:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 16:59:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 16:59:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 16:59:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 16:59:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 16:59:19', 'DoVa_Co2', '0']
['2021-5-4 16:59:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 16:59:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 16:59:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 16:59:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 16:59:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:0:19', 'fKWhCounter', '3435.30053710938']
['2021-5-4 17:0:19', 'fActPhLevelMixTank1', '5.6275520324707']
['2021-5-4 17:0:19', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 17:0:19', 'fActPhLevelMixTank2', '3.82988977432251']
['2021-5-4 17:0:19', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 17:0:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:0:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:0:19', 'fActTempValMemo', '22']
['2021-5-4 17:0:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:0:19', 'fActCo2ValMemo', '754']
['2021-5-4 17:0:19', 'fActWaterLevelMixTank1', '278.414276123047']
['2021-5-4 17:0:19', 'fActWaterLevelMixTank2', '284.471466064453']
['2021-5-4 17:0:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:0:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:0:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:0:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:0:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:0:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:0:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:0:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:0:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:0:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:0:19', 'DoVa_Co2', '0']
['2021-5-4 17:0:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:0:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:0:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:0:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:0:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:1:19', 'fKWhCounter', '3435.40063476563']
['2021-5-4 17:1:19', 'fActPhLevelMixTank1', '5.63390016555786']
['2021-5-4 17:1:19', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 17:1:19', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 17:1:19', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 17:1:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:1:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:1:19', 'fActTempValMemo', '22']
['2021-5-4 17:1:19', 'fActRhValMemo', '50.5']
['2021-5-4 17:1:19', 'fActCo2ValMemo', '755']
['2021-5-4 17:1:19', 'fActWaterLevelMixTank1', '279.066162109375']
['2021-5-4 17:1:19', 'fActWaterLevelMixTank2', '285.150543212891']
['2021-5-4 17:1:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:1:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:1:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:1:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:1:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:1:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:1:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:1:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:1:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:1:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:1:19', 'DoVa_Co2', '0']
['2021-5-4 17:1:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:1:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:1:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:1:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:1:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:2:19', 'fKWhCounter', '3435.60083007813']
['2021-5-4 17:2:19', 'fActPhLevelMixTank1', '5.63512086868286']
['2021-5-4 17:2:19', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 17:2:19', 'fActPhLevelMixTank2', '3.82891321182251']
['2021-5-4 17:2:19', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 17:2:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:2:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:2:19', 'fActTempValMemo', '22']
['2021-5-4 17:2:19', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 17:2:19', 'fActCo2ValMemo', '754']
['2021-5-4 17:2:19', 'fActWaterLevelMixTank1', '280.532928466797']
['2021-5-4 17:2:19', 'fActWaterLevelMixTank2', '285.204864501953']
['2021-5-4 17:2:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:2:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:2:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:2:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:2:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:2:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:2:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:2:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:2:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:2:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:2:19', 'DoVa_Co2', '0']
['2021-5-4 17:2:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:2:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:2:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:2:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']

['2021-5-4 17:2:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:2:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:3:19', 'fKWhCounter', '3435.70092773438']
['2021-5-4 17:3:19', 'fActPhLevelMixTank1', '5.63902711868286']
['2021-5-4 17:3:19', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 17:3:19', 'fActPhLevelMixTank2', '3.83330798149109']
['2021-5-4 17:3:19', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 17:3:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:3:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:3:19', 'fActTempValMemo', '22']
['2021-5-4 17:3:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:3:19', 'fActCo2ValMemo', '753']
['2021-5-4 17:3:19', 'fActWaterLevelMixTank1', '278.848876953125']
['2021-5-4 17:3:19', 'fActWaterLevelMixTank2', '285.014709472656']
['2021-5-4 17:3:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:3:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:3:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:3:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:3:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:3:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:3:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:3:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:3:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:3:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:3:19', 'DoVa_Co2', '0']
['2021-5-4 17:3:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:3:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:3:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:3:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:3:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:4:19', 'fKWhCounter', '3435.80102539063']
['2021-5-4 17:4:19', 'fActPhLevelMixTank1', '5.63707399368286']
['2021-5-4 17:4:19', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 17:4:19', 'fActPhLevelMixTank2', '3.82964563369751']
['2021-5-4 17:4:19', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 17:4:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:4:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:4:19', 'fActTempValMemo', '22']
['2021-5-4 17:4:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:4:19', 'fActCo2ValMemo', '754']
['2021-5-4 17:4:19', 'fActWaterLevelMixTank1', '280.098327636719']
['2021-5-4 17:4:19', 'fActWaterLevelMixTank2', '284.389984130859']
['2021-5-4 17:4:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:4:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:4:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:4:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:4:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:4:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:4:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:4:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:4:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:4:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:4:19', 'DoVa_Co2', '0']
['2021-5-4 17:4:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:4:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:4:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:4:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:4:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:5:19', 'fKWhCounter', '3436.00122070313']
['2021-5-4 17:5:19', 'fActPhLevelMixTank1', '5.64171266555786']
['2021-5-4 17:5:19', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 17:5:19', 'fActPhLevelMixTank2', '3.82964563369751']
['2021-5-4 17:5:19', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 17:5:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:5:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:5:19', 'fActTempValMemo', '22']
['2021-5-4 17:5:19', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 17:5:19', 'fActCo2ValMemo', '752']
['2021-5-4 17:5:19', 'fActWaterLevelMixTank1', '280.288452148438']
['2021-5-4 17:5:19', 'fActWaterLevelMixTank2', '285.123382568359']
['2021-5-4 17:5:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:5:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:5:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:5:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:5:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:5:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:5:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:5:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:5:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:5:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:5:19', 'DoVa_Co2', '0']
['2021-5-4 17:5:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:5:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:5:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:5:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:5:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:6:19', 'fKWhCounter', '3436.10131835938']
['2021-5-4 17:6:19', 'fActPhLevelMixTank1', '5.64390993118286']
['2021-5-4 17:6:19', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 17:6:19', 'fActPhLevelMixTank2', '3.82671594619751']
['2021-5-4 17:6:19', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 17:6:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:6:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:6:19', 'fActTempValMemo', '22']
['2021-5-4 17:6:19', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:6:19', 'fActCo2ValMemo', '747']
['2021-5-4 17:6:19', 'fActWaterLevelMixTank1', '280.804565429688']
['2021-5-4 17:6:19', 'fActWaterLevelMixTank2', '285.422149658203']
['2021-5-4 17:6:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:6:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:6:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:6:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:6:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:6:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:6:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:6:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:6:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:6:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:6:19', 'DoVa_Co2', '0']
['2021-5-4 17:6:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:6:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:6:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:6:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:6:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:7:19', 'fKWhCounter', '3436.30151367188']
['2021-5-4 17:7:19', 'fActPhLevelMixTank1', '5.64366579055786']
['2021-5-4 17:7:19', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 17:7:19', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 17:7:19', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 17:7:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:7:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:7:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:7:19', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 17:7:19', 'fActCo2ValMemo', '748']
['2021-5-4 17:7:19', 'fActWaterLevelMixTank1', '278.848876953125']
['2021-5-4 17:7:19', 'fActWaterLevelMixTank2', '285.150543212891']
['2021-5-4 17:7:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:7:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:7:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:7:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:7:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:7:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:7:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:7:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:7:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:7:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:7:19', 'DoVa_Co2', '0']
['2021-5-4 17:7:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:7:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:7:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:7:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:7:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:8:19', 'fKWhCounter', '3436.40161132813']
['2021-5-4 17:8:19', 'fActPhLevelMixTank1', '5.64635133743286']
['2021-5-4 17:8:19', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 17:8:19', 'fActPhLevelMixTank2', '3.83233141899109']
['2021-5-4 17:8:19', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 17:8:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:8:19', 'fTaktCounterLowerLevel', '0']

['2021-5-4 17:8:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:8:19', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 17:8:19', 'fActCo2ValMemo', '750']
['2021-5-4 17:8:19', 'fActWaterLevelMixTank1', '280.723052978516']
['2021-5-4 17:8:19', 'fActWaterLevelMixTank2', '285.367828369141']
['2021-5-4 17:8:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:8:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:8:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:8:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:8:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:8:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:8:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:8:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:8:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:8:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:8:19', 'DoVa_Co2', '0']
['2021-5-4 17:8:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:8:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:8:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:8:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:8:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:9:19', 'fKWhCounter', '3436.60180664063']
['2021-5-4 17:9:19', 'fActPhLevelMixTank1', '5.65318775177002']
['2021-5-4 17:9:19', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 17:9:19', 'fActPhLevelMixTank2', '3.82720422744751']
['2021-5-4 17:9:19', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 17:9:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:9:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:9:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:9:19', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 17:9:19', 'fActCo2ValMemo', '767']
['2021-5-4 17:9:19', 'fActWaterLevelMixTank1', '280.695892333984']
['2021-5-4 17:9:19', 'fActWaterLevelMixTank2', '285.422149658203']
['2021-5-4 17:9:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:9:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:9:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:9:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:9:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:9:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:9:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:9:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:9:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:9:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:9:19', 'DoVa_Co2', '0']
['2021-5-4 17:9:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:9:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:9:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:9:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:9:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:10:19', 'fKWhCounter', '3436.70190429688']
['2021-5-4 17:10:19', 'fActPhLevelMixTank1', '5.65001392364502']
['2021-5-4 17:10:19', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 17:10:19', 'fActPhLevelMixTank2', '3.82720422744751']
['2021-5-4 17:10:19', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 17:10:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:10:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:10:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:10:19', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 17:10:19', 'fActCo2ValMemo', '783']
['2021-5-4 17:10:19', 'fActWaterLevelMixTank1', '281.347808837891']
['2021-5-4 17:10:19', 'fActWaterLevelMixTank2', '285.938232421875']
['2021-5-4 17:10:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:10:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:10:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:10:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:10:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:10:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:10:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:10:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:10:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:10:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:10:19', 'DoVa_Co2', '0']
['2021-5-4 17:10:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:10:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:10:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:10:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:10:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:11:19', 'fKWhCounter', '3436.80200195313']
['2021-5-4 17:11:19', 'fActPhLevelMixTank1', '5.65001392364502']
['2021-5-4 17:11:19', 'fActEcLevelMixTank1', '2029.78601074219']
['2021-5-4 17:11:19', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 17:11:19', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 17:11:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:11:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:11:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:11:19', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:11:19', 'fActCo2ValMemo', '810']
['2021-5-4 17:11:19', 'fActWaterLevelMixTank1', '281.374969482422']
['2021-5-4 17:11:19', 'fActWaterLevelMixTank2', '285.557952880859']
['2021-5-4 17:11:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:11:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:11:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:11:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:11:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:11:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:11:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:11:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:11:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:11:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:11:19', 'DoVa_Co2', '0']
['2021-5-4 17:11:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:11:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:11:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:11:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:11:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:12:19', 'fKWhCounter', '3437.00219726563']
['2021-5-4 17:12:19', 'fActPhLevelMixTank1', '5.65196704864502']
['2021-5-4 17:12:19', 'fActEcLevelMixTank1', '2033.14306640625']
['2021-5-4 17:12:19', 'fActPhLevelMixTank2', '3.83013391494751']
['2021-5-4 17:12:19', 'fActEcLevelMixTank2', '1039.00268554688']
['2021-5-4 17:12:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:12:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:12:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:12:19', 'fActRhValMemo', '50']
['2021-5-4 17:12:19', 'fActCo2ValMemo', '837']
['2021-5-4 17:12:19', 'fActWaterLevelMixTank1', '281.320648193359']
['2021-5-4 17:12:19', 'fActWaterLevelMixTank2', '286.182708740234']
['2021-5-4 17:12:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:12:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:12:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:12:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:12:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:12:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:12:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:12:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:12:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:12:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:12:19', 'DoVa_Co2', '0']
['2021-5-4 17:12:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:12:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:12:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:12:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:12:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']

['2021-5-4 17:13:19', 'fKWhCounter', '3437.10229492188']
['2021-5-4 17:13:19', 'fActPhLevelMixTank1', '5.65099048614502']
['2021-5-4 17:13:19', 'fActEcLevelMixTank1', '2028.56530761719']
['2021-5-4 17:13:19', 'fActPhLevelMixTank2', '3.82964563369751']
['2021-5-4 17:13:19', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 17:13:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:13:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:13:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:13:19', 'fActRhValMemo', '50.5']
['2021-5-4 17:13:19', 'fActCo2ValMemo', '864']
['2021-5-4 17:13:19', 'fActWaterLevelMixTank1', '282.108337402344']
['2021-5-4 17:13:19', 'fActWaterLevelMixTank2', '286.046875']
['2021-5-4 17:13:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:13:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:13:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:13:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:13:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:13:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:13:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:13:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:13:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:13:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:13:19', 'DoVa_Co2', '0']
['2021-5-4 17:13:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:13:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:13:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:13:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:13:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:14:19', 'fKWhCounter', '3437.30249023438']
['2021-5-4 17:14:19', 'fActPhLevelMixTank1', '5.58775615692139']
['2021-5-4 17:14:19', 'fActEcLevelMixTank1', '2033.75341796875']
['2021-5-4 17:14:19', 'fActPhLevelMixTank2', '3.74687957763672']
['2021-5-4 17:14:19', 'fActEcLevelMixTank2', '1039.00268554688']
['2021-5-4 17:14:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:14:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:14:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:14:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:14:19', 'fActCo2ValMemo', '887']
['2021-5-4 17:14:19', 'fActWaterLevelMixTank1', '283.982543945313']
['2021-5-4 17:14:19', 'fActWaterLevelMixTank2', '261.6279296875']
['2021-5-4 17:14:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:14:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:14:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:14:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:14:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:14:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:14:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:14:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:14:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:14:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:14:19', 'DoVa_Co2', '0']
['2021-5-4 17:14:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:14:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:14:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:14:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:14:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:15:19', 'fKWhCounter', '3437.50268554688']
['2021-5-4 17:15:19', 'fActPhLevelMixTank1', '5.56773567199707']
['2021-5-4 17:15:19', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 17:15:19', 'fActPhLevelMixTank2', '3.74443793296814']
['2021-5-4 17:15:19', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 17:15:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:15:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:15:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:15:19', 'fActRhValMemo', '50.5']
['2021-5-4 17:15:19', 'fActCo2ValMemo', '907']
['2021-5-4 17:15:19', 'fActWaterLevelMixTank1', '275.018981933594']
['2021-5-4 17:15:19', 'fActWaterLevelMixTank2', '296.015472412109']
['2021-5-4 17:15:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:15:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:15:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:15:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:15:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:15:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:15:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:15:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:15:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:15:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:15:19', 'DoVa_Co2', '0']
['2021-5-4 17:15:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:15:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:15:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:15:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:15:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:16:19', 'fKWhCounter', '3437.60278320313']
['2021-5-4 17:16:19', 'fActPhLevelMixTank1', '5.56163215637207']
['2021-5-4 17:16:19', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 17:16:19', 'fActPhLevelMixTank2', '3.75078582763672']
['2021-5-4 17:16:19', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 17:16:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:16:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:16:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:16:19', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 17:16:19', 'fActCo2ValMemo', '923']
['2021-5-4 17:16:19', 'fActWaterLevelMixTank1', '271.922454833984']
['2021-5-4 17:16:19', 'fActWaterLevelMixTank2', '296.368591308594']
['2021-5-4 17:16:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:16:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:16:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:16:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:16:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:16:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:16:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:16:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:16:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:16:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:16:19', 'DoVa_Co2', '0']
['2021-5-4 17:16:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:16:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:16:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:16:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:16:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:17:19', 'fKWhCounter', '3437.80297851563']
['2021-5-4 17:17:19', 'fActPhLevelMixTank1', '5.56895637512207']
['2021-5-4 17:17:19', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 17:17:19', 'fActPhLevelMixTank2', '3.75102996826172']
['2021-5-4 17:17:19', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 17:17:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:17:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:17:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:17:19', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 17:17:19', 'fActCo2ValMemo', '939']
['2021-5-4 17:17:19', 'fActWaterLevelMixTank1', '270.319885253906']
['2021-5-4 17:17:19', 'fActWaterLevelMixTank2', '280.750213623047']
['2021-5-4 17:17:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:17:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:17:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:17:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:17:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:17:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:17:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:17:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:17:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:17:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:17:19', 'DoVa_Co2', '0']
['2021-5-4 17:17:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:17:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:17:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:17:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_3_Fred', '0']

['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:17:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:18:19', 'fKWhCounter', '3438.00317382813']
['2021-5-4 17:18:19', 'fActPhLevelMixTank1', '5.57213068008423']
['2021-5-4 17:18:19', 'fActEcLevelMixTank1', '2027.03942871094']
['2021-5-4 17:18:19', 'fActPhLevelMixTank2', '3.74736785888672']
['2021-5-4 17:18:19', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 17:18:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:18:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:18:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:18:19', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 17:18:19', 'fActCo2ValMemo', '950']
['2021-5-4 17:18:19', 'fActWaterLevelMixTank1', '271.433532714844']
['2021-5-4 17:18:19', 'fActWaterLevelMixTank2', '276.784515380859']
['2021-5-4 17:18:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:18:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:18:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:18:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:18:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:18:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:18:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:18:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:18:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:18:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:18:19', 'DoVa_Co2', '0']
['2021-5-4 17:18:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:18:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:18:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:18:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:18:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:19:19', 'fKWhCounter', '3438.20336914063']
['2021-5-4 17:19:19', 'fActPhLevelMixTank1', '5.57115411758423']
['2021-5-4 17:19:19', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 17:19:19', 'fActPhLevelMixTank2', '3.78301334381104']
['2021-5-4 17:19:19', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 17:19:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:19:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:19:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:19:19', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 17:19:19', 'fActCo2ValMemo', '956']
['2021-5-4 17:19:19', 'fActWaterLevelMixTank1', '271.324890136719']
['2021-5-4 17:19:19', 'fActWaterLevelMixTank2', '278.903198242188']
['2021-5-4 17:19:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:19:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:19:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:19:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:19:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:19:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:19:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:19:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:19:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:19:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:19:19', 'DoVa_Co2', '0']
['2021-5-4 17:19:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:19:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:19:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:19:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:19:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:20:19', 'fKWhCounter', '3438.30346679688']
['2021-5-4 17:20:19', 'fActPhLevelMixTank1', '5.57506036758423']
['2021-5-4 17:20:19', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 17:20:19', 'fActPhLevelMixTank2', '3.80547499656677']
['2021-5-4 17:20:19', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 17:20:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:20:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:20:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:20:19', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 17:20:19', 'fActCo2ValMemo', '960']
['2021-5-4 17:20:19', 'fActWaterLevelMixTank1', '271.026092529297']
['2021-5-4 17:20:19', 'fActWaterLevelMixTank2', '278.604400634766']
['2021-5-4 17:20:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:20:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:20:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:20:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:20:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:20:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:20:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:20:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:20:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:20:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:20:19', 'DoVa_Co2', '0']
['2021-5-4 17:20:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:20:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:20:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:20:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:20:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:21:19', 'fKWhCounter', '3438.40356445313']
['2021-5-4 17:21:19', 'fActPhLevelMixTank1', '5.58018732070923']
['2021-5-4 17:21:19', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 17:21:19', 'fActPhLevelMixTank2', '3.80205702781677']
['2021-5-4 17:21:19', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 17:21:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:21:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:21:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:21:19', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 17:21:19', 'fActCo2ValMemo', '964']
['2021-5-4 17:21:19', 'fActWaterLevelMixTank1', '270.184051513672']
['2021-5-4 17:21:19', 'fActWaterLevelMixTank2', '278.278442382813']
['2021-5-4 17:21:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:21:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:21:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:21:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:21:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:21:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:21:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:21:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:21:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:21:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:21:19', 'DoVa_Co2', '0']
['2021-5-4 17:21:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:21:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:21:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:21:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:21:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:22:19', 'fKWhCounter', '3438.60375976563']
['2021-5-4 17:22:19', 'fActPhLevelMixTank1', '5.57896661758423']
['2021-5-4 17:22:19', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 17:22:19', 'fActPhLevelMixTank2', '3.79937124252319']
['2021-5-4 17:22:19', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 17:22:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:22:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:22:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:22:19', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 17:22:19', 'fActCo2ValMemo', '968']
['2021-5-4 17:22:19', 'fActWaterLevelMixTank1', '270.319885253906']
['2021-5-4 17:22:19', 'fActWaterLevelMixTank2', '278.414276123047']
['2021-5-4 17:22:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:22:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:22:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:22:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:22:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:22:19', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 17:22:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:22:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:22:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:22:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:22:19', 'DoVa_Co2', '0']
['2021-5-4 17:22:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:22:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:22:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:22:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:22:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:23:19', 'fKWhCounter', '3438.70385742188']
['2021-5-4 17:23:19', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 17:23:19', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 17:23:19', 'fActPhLevelMixTank2', '3.80156874656677']
['2021-5-4 17:23:19', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 17:23:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:23:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:23:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:23:19', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 17:23:19', 'fActCo2ValMemo', '973']
['2021-5-4 17:23:19', 'fActWaterLevelMixTank1', '270.564331054688']
['2021-5-4 17:23:19', 'fActWaterLevelMixTank2', '277.789520263672']
['2021-5-4 17:23:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:23:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:23:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:23:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:23:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:23:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:23:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:23:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:23:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:23:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:23:19', 'DoVa_Co2', '0']
['2021-5-4 17:23:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:23:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:23:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:23:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:23:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:24:19', 'fKWhCounter', '3438.90405273438']
['2021-5-4 17:24:19', 'fActPhLevelMixTank1', '5.58018732070923']
['2021-5-4 17:24:19', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 17:24:19', 'fActPhLevelMixTank2', '3.79497671127319']
['2021-5-4 17:24:19', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 17:24:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:24:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:24:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:24:19', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 17:24:19', 'fActCo2ValMemo', '974']
['2021-5-4 17:24:19', 'fActWaterLevelMixTank1', '270.835968017578']
['2021-5-4 17:24:19', 'fActWaterLevelMixTank2', '277.843841552734']
['2021-5-4 17:24:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:24:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:24:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:24:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:24:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:24:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:24:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:24:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:24:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:24:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:24:19', 'DoVa_Co2', '0']
['2021-5-4 17:24:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:24:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:24:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:24:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:24:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:25:19', 'fKWhCounter', '3439.00415039063']
['2021-5-4 17:25:19', 'fActPhLevelMixTank1', '5.57799005508423']
['2021-5-4 17:25:19', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 17:25:19', 'fActPhLevelMixTank2', '3.79570913314819']
['2021-5-4 17:25:19', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 17:25:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:25:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:25:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:25:19', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 17:25:19', 'fActCo2ValMemo', '975']
['2021-5-4 17:25:19', 'fActWaterLevelMixTank1', '271.759490966797']
['2021-5-4 17:25:19', 'fActWaterLevelMixTank2', '278.685882568359']
['2021-5-4 17:25:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:25:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:25:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:25:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:25:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:25:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:25:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:25:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:25:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:25:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:25:19', 'DoVa_Co2', '0']
['2021-5-4 17:25:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:25:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:25:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:25:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:25:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:26:19', 'fKWhCounter', '3439.20434570313']
['2021-5-4 17:26:19', 'fActPhLevelMixTank1', '5.57799005508423']
['2021-5-4 17:26:19', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 17:26:19', 'fActPhLevelMixTank2', '3.79277920722961']
['2021-5-4 17:26:19', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 17:26:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:26:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:26:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:26:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:26:19', 'fActCo2ValMemo', '978']
['2021-5-4 17:26:19', 'fActWaterLevelMixTank1', '272.058258056641']
['2021-5-4 17:26:19', 'fActWaterLevelMixTank2', '278.848876953125']
['2021-5-4 17:26:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:26:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:26:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:26:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:26:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:26:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:26:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:26:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:26:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:26:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:26:19', 'DoVa_Co2', '0']
['2021-5-4 17:26:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:26:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:26:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:26:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:26:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:27:19', 'fKWhCounter', '3439.30444335938']
['2021-5-4 17:27:19', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 17:27:19', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 17:27:19', 'fActPhLevelMixTank2', '3.79692983627319']
['2021-5-4 17:27:19', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 17:27:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:27:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:27:19', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:27:19', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 17:27:19', 'fActCo2ValMemo', '978']
['2021-5-4 17:27:19', 'fActWaterLevelMixTank1', '273.117614746094']
['2021-5-4 17:27:19', 'fActWaterLevelMixTank2', '279.039001464844']
['2021-5-4 17:27:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:27:19', 'DoPu_AddEcAMixTank_1', '0']

['2021-5-4 17:27:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:27:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:27:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:27:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:27:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:27:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:27:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:27:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:27:19', 'DoVa_Co2', '0']
['2021-5-4 17:27:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:27:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:27:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:27:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:27:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:28:20', 'fKWhCounter', '3439.50463867188']
['2021-5-4 17:28:20', 'fActPhLevelMixTank1', '5.57994318008423']
['2021-5-4 17:28:20', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 17:28:20', 'fActPhLevelMixTank2', '3.79815053939819']
['2021-5-4 17:28:20', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 17:28:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:28:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:28:20', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 17:28:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:28:20', 'fActCo2ValMemo', '984']
['2021-5-4 17:28:20', 'fActWaterLevelMixTank1', '273.606536865234']
['2021-5-4 17:28:20', 'fActWaterLevelMixTank2', '279.419281005859']
['2021-5-4 17:28:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:28:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:28:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:28:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:28:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:28:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:28:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:28:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:28:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:28:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:28:20', 'DoVa_Co2', '0']
['2021-5-4 17:28:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:28:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:28:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:28:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:28:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:29:19', 'fKWhCounter', '3439.60473632813']
['2021-5-4 17:29:19', 'fActPhLevelMixTank1', '5.57725763320923']
['2021-5-4 17:29:19', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 17:29:19', 'fActPhLevelMixTank2', '3.79400014877319']
['2021-5-4 17:29:19', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 17:29:19', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:29:19', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:29:19', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 17:29:19', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:29:19', 'fActCo2ValMemo', '982']
['2021-5-4 17:29:19', 'fActWaterLevelMixTank1', '272.574340820313']
['2021-5-4 17:29:19', 'fActWaterLevelMixTank2', '278.821685791016']
['2021-5-4 17:29:19', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:29:19', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:29:19', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:29:19', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:29:19', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:29:19', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:29:19', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:29:19', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:29:19', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:29:19', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:29:19', 'DoVa_Co2', '0']
['2021-5-4 17:29:19', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:29:19', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:29:19', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:29:19', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:29:19', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:30:20', 'fKWhCounter', '3439.70483398438']
['2021-5-4 17:30:20', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 17:30:20', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 17:30:20', 'fActPhLevelMixTank2', '3.79692983627319']
['2021-5-4 17:30:20', 'fActEcLevelMixTank2', '1030.15234375']
['2021-5-4 17:30:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:30:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:30:20', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 17:30:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:30:20', 'fActCo2ValMemo', '983']
['2021-5-4 17:30:20', 'fActWaterLevelMixTank1', '273.280578613281']
['2021-5-4 17:30:20', 'fActWaterLevelMixTank2', '279.636566162109']
['2021-5-4 17:30:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:30:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:30:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:30:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:30:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:30:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:30:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:30:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:30:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:30:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:30:20', 'DoVa_Co2', '0']
['2021-5-4 17:30:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:30:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:30:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:30:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:30:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:31:20', 'fKWhCounter', '3439.90502929688']
['2021-5-4 17:31:20', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 17:31:20', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 17:31:20', 'fActPhLevelMixTank2', '3.79277920722961']
['2021-5-4 17:31:20', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 17:31:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:31:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:31:20', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 17:31:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:31:20', 'fActCo2ValMemo', '984']
['2021-5-4 17:31:20', 'fActWaterLevelMixTank1', '273.334899902344']
['2021-5-4 17:31:20', 'fActWaterLevelMixTank2', '280.098327636719']
['2021-5-4 17:31:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:31:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:31:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:31:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:31:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:31:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:31:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:31:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:31:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:31:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:31:20', 'DoVa_Co2', '0']
['2021-5-4 17:31:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:31:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:31:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:31:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:31:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:32:20', 'fKWhCounter', '3440.00512695313']
['2021-5-4 17:32:20', 'fActPhLevelMixTank1', '5.57823419570923']
['2021-5-4 17:32:20', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 17:32:20', 'fActPhLevelMixTank2', '3.80108046531677']
['2021-5-4 17:32:20', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 17:32:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:32:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:32:20', 'fActTempValMemo', '21.7999992370605']

['2021-5-4 17:32:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:32:20', 'fActCo2ValMemo', '984']
['2021-5-4 17:32:20', 'fActWaterLevelMixTank1', '273.715179443359']
['2021-5-4 17:32:20', 'fActWaterLevelMixTank2', '280.044006347656']
['2021-5-4 17:32:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:32:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:32:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:32:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:32:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:32:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:32:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:32:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:32:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:32:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:32:20', 'DoVa_Co2', '0']
['2021-5-4 17:32:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:32:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:32:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:32:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:32:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:33:20', 'fKWhCounter', '3440.20532226563']
['2021-5-4 17:33:20', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 17:33:20', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 17:33:20', 'fActPhLevelMixTank2', '3.79302358627319']
['2021-5-4 17:33:20', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 17:33:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:33:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:33:20', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 17:33:20', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 17:33:20', 'fActCo2ValMemo', '986']
['2021-5-4 17:33:20', 'fActWaterLevelMixTank1', '274.475708007813']
['2021-5-4 17:33:20', 'fActWaterLevelMixTank2', '280.424285888672']
['2021-5-4 17:33:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:33:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:33:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:33:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:33:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:33:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:33:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:33:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:33:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:33:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:33:20', 'DoVa_Co2', '0']
['2021-5-4 17:33:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:33:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:33:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:33:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:33:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:34:20', 'fKWhCounter', '3440.30541992188']
['2021-5-4 17:34:20', 'fActPhLevelMixTank1', '5.59044170379639']
['2021-5-4 17:34:20', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 17:34:20', 'fActPhLevelMixTank2', '3.79912710189819']
['2021-5-4 17:34:20', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 17:34:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:34:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:34:20', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 17:34:20', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 17:34:20', 'fActCo2ValMemo', '983']
['2021-5-4 17:34:20', 'fActWaterLevelMixTank1', '274.068298339844']
['2021-5-4 17:34:20', 'fActWaterLevelMixTank2', '280.369964599609']
['2021-5-4 17:34:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:34:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:34:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:34:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:34:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:34:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:34:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:34:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:34:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:34:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:34:20', 'DoVa_Co2', '0']
['2021-5-4 17:34:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:34:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:34:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:34:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:34:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:35:20', 'fKWhCounter', '3440.40551757813']
['2021-5-4 17:35:20', 'fActPhLevelMixTank1', '5.58946514129639']
['2021-5-4 17:35:20', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 17:35:20', 'fActPhLevelMixTank2', '3.79668569564819']
['2021-5-4 17:35:20', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 17:35:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:35:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:35:20', 'fActTempValMemo', '21.7999992370605']
['2021-5-4 17:35:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:35:20', 'fActCo2ValMemo', '984']
['2021-5-4 17:35:20', 'fActWaterLevelMixTank1', '274.122619628906']
['2021-5-4 17:35:20', 'fActWaterLevelMixTank2', '280.315643310547']
['2021-5-4 17:35:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:35:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:35:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:35:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:35:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:35:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:35:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:35:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:35:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:35:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:35:20', 'DoVa_Co2', '0']
['2021-5-4 17:35:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:35:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:35:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:35:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:35:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:36:20', 'fKWhCounter', '3440.60571289063']
['2021-5-4 17:36:20', 'fActPhLevelMixTank1', '5.60386991500854']
['2021-5-4 17:36:20', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 17:36:20', 'fActPhLevelMixTank2', '3.80693984031677']
['2021-5-4 17:36:20', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 17:36:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:36:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:36:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:36:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:36:20', 'fActCo2ValMemo', '983']
['2021-5-4 17:36:20', 'fActWaterLevelMixTank1', '274.285583496094']
['2021-5-4 17:36:20', 'fActWaterLevelMixTank2', '280.315643310547']
['2021-5-4 17:36:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:36:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:36:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:36:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:36:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:36:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:36:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:36:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:36:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:36:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:36:20', 'DoVa_Co2', '0']
['2021-5-4 17:36:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:36:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:36:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:36:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']

['2021-5-4 17:36:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:36:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:37:20', 'fKWhCounter', '3440.70581054688']
['2021-5-4 17:37:20', 'fActPhLevelMixTank1', '5.59678936004639']
['2021-5-4 17:37:20', 'fActEcLevelMixTank1', '2017.57861328125']
['2021-5-4 17:37:20', 'fActPhLevelMixTank2', '3.80034780502319']
['2021-5-4 17:37:20', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 17:37:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:37:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:37:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:37:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:37:20', 'fActCo2ValMemo', '977']
['2021-5-4 17:37:20', 'fActWaterLevelMixTank1', '272.791656494141']
['2021-5-4 17:37:20', 'fActWaterLevelMixTank2', '279.989685058594']
['2021-5-4 17:37:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:37:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:37:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:37:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:37:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:37:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:37:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:37:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:37:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:37:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:37:20', 'DoVa_Co2', '0']
['2021-5-4 17:37:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:37:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:37:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:37:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:37:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:38:20', 'fKWhCounter', '3440.90600585938']
['2021-5-4 17:38:20', 'fActPhLevelMixTank1', '5.59947490692139']
['2021-5-4 17:38:20', 'fActEcLevelMixTank1', '2017.2734375']
['2021-5-4 17:38:20', 'fActPhLevelMixTank2', '3.80669569969177']
['2021-5-4 17:38:20', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 17:38:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:38:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:38:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:38:20', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 17:38:20', 'fActCo2ValMemo', '971']
['2021-5-4 17:38:20', 'fActWaterLevelMixTank1', '275.073303222656']
['2021-5-4 17:38:20', 'fActWaterLevelMixTank2', '280.098327636719']
['2021-5-4 17:38:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:38:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:38:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:38:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:38:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:38:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:38:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:38:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:38:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:38:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:38:20', 'DoVa_Co2', '0']
['2021-5-4 17:38:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:38:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:38:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:38:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:38:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:39:20', 'fKWhCounter', '3441.00610351563']
['2021-5-4 17:39:20', 'fActPhLevelMixTank1', '5.60582304000854']
['2021-5-4 17:39:20', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 17:39:20', 'fActPhLevelMixTank2', '3.80498671531677']
['2021-5-4 17:39:20', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 17:39:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:39:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:39:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:39:20', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 17:39:20', 'fActCo2ValMemo', '974']
['2021-5-4 17:39:20', 'fActWaterLevelMixTank1', '274.991790771484']
['2021-5-4 17:39:20', 'fActWaterLevelMixTank2', '280.152648925781']
['2021-5-4 17:39:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:39:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:39:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:39:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:39:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:39:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:39:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:39:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:39:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:39:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:39:20', 'DoVa_Co2', '0']
['2021-5-4 17:39:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:39:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:39:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:39:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:39:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:40:20', 'fKWhCounter', '3441.20629882813']
['2021-5-4 17:40:20', 'fActPhLevelMixTank1', '5.60045146942139']
['2021-5-4 17:40:20', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 17:40:20', 'fActPhLevelMixTank2', '3.81353187561035']
['2021-5-4 17:40:20', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 17:40:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:40:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:40:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:40:20', 'fActRhValMemo', '50']
['2021-5-4 17:40:20', 'fActCo2ValMemo', '972']
['2021-5-4 17:40:20', 'fActWaterLevelMixTank1', '275.806671142578']
['2021-5-4 17:40:20', 'fActWaterLevelMixTank2', '280.641571044922']
['2021-5-4 17:40:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:40:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:40:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:40:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:40:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:40:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:40:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:40:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:40:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:40:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:40:20', 'DoVa_Co2', '0']
['2021-5-4 17:40:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:40:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:40:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:40:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:40:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:41:20', 'fKWhCounter', '3441.30639648438']
['2021-5-4 17:41:20', 'fActPhLevelMixTank1', '5.59874248504639']
['2021-5-4 17:41:20', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 17:41:20', 'fActPhLevelMixTank2', '3.81157875061035']
['2021-5-4 17:41:20', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 17:41:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:41:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:41:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:41:20', 'fActRhValMemo', '50']
['2021-5-4 17:41:20', 'fActCo2ValMemo', '971']
['2021-5-4 17:41:20', 'fActWaterLevelMixTank1', '275.399230957031']
['2021-5-4 17:41:20', 'fActWaterLevelMixTank2', '280.831726074219']
['2021-5-4 17:41:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:41:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:41:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:41:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:41:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:41:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:41:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:41:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:41:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:41:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:41:20', 'DoVa_Co2', '0']
['2021-5-4 17:41:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:41:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:41:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:41:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_1_Blue', '0']

['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:41:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:42:20', 'fKWhCounter', '3441.40649414063']
['2021-5-4 17:42:20', 'fActPhLevelMixTank1', '5.60972929000854']
['2021-5-4 17:42:20', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 17:42:20', 'fActPhLevelMixTank2', '3.81255531311035']
['2021-5-4 17:42:20', 'fActEcLevelMixTank2', '1029.69445800781']
['2021-5-4 17:42:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:42:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:42:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:42:20', 'fActRhValMemo', '49.5999984741211']
['2021-5-4 17:42:20', 'fActCo2ValMemo', '970']
['2021-5-4 17:42:20', 'fActWaterLevelMixTank1', '275.698028564453']
['2021-5-4 17:42:20', 'fActWaterLevelMixTank2', '280.695892333984']
['2021-5-4 17:42:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:42:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:42:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:42:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:42:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:42:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:42:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:42:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:42:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:42:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:42:20', 'DoVa_Co2', '0']
['2021-5-4 17:42:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:42:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:42:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:42:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:42:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:43:20', 'fKWhCounter', '3441.60668945313']
['2021-5-4 17:43:20', 'fActPhLevelMixTank1', '5.60142803192139']
['2021-5-4 17:43:20', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 17:43:20', 'fActPhLevelMixTank2', '3.81011390686035']
['2021-5-4 17:43:20', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 17:43:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:43:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:43:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:43:20', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 17:43:20', 'fActCo2ValMemo', '970']
['2021-5-4 17:43:20', 'fActWaterLevelMixTank1', '276.214111328125']
['2021-5-4 17:43:20', 'fActWaterLevelMixTank2', '281.374969482422']
['2021-5-4 17:43:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:43:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:43:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:43:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:43:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:43:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:43:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:43:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:43:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:43:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:43:20', 'DoVa_Co2', '0']
['2021-5-4 17:43:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:43:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:43:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:43:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:43:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:44:20', 'fKWhCounter', '3441.70678710938']
['2021-5-4 17:44:20', 'fActPhLevelMixTank1', '5.59947490692139']
['2021-5-4 17:44:20', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 17:44:20', 'fActPhLevelMixTank2', '3.80864906311035']
['2021-5-4 17:44:20', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 17:44:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:44:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:44:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:44:20', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 17:44:20', 'fActCo2ValMemo', '968']
['2021-5-4 17:44:20', 'fActWaterLevelMixTank1', '276.730194091797']
['2021-5-4 17:44:20', 'fActWaterLevelMixTank2', '281.456451416016']
['2021-5-4 17:44:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:44:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:44:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:44:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:44:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:44:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:44:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:44:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:44:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:44:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:44:20', 'DoVa_Co2', '0']
['2021-5-4 17:44:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:44:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:44:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:44:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:44:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:45:20', 'fKWhCounter', '3441.90698242188']
['2021-5-4 17:45:20', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 17:45:20', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 17:45:20', 'fActPhLevelMixTank2', '3.81817078590393']
['2021-5-4 17:45:20', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 17:45:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:45:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:45:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:45:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:45:20', 'fActCo2ValMemo', '966']
['2021-5-4 17:45:20', 'fActWaterLevelMixTank1', '277.490753173828']
['2021-5-4 17:45:20', 'fActWaterLevelMixTank2', '282.054016113281']
['2021-5-4 17:45:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:45:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:45:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:45:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:45:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:45:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:45:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:45:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:45:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:45:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:45:20', 'DoVa_Co2', '0']
['2021-5-4 17:45:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:45:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:45:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:45:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:45:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:46:20', 'fKWhCounter', '3442.00708007813']
['2021-5-4 17:46:20', 'fActPhLevelMixTank1', '5.60045146942139']
['2021-5-4 17:46:20', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 17:46:20', 'fActPhLevelMixTank2', '3.81353187561035']
['2021-5-4 17:46:20', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 17:46:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:46:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:46:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:46:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:46:20', 'fActCo2ValMemo', '968']
['2021-5-4 17:46:20', 'fActWaterLevelMixTank1', '277.979675292969']
['2021-5-4 17:46:20', 'fActWaterLevelMixTank2', '282.217010498047']
['2021-5-4 17:46:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:46:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:46:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:46:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:46:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:46:20', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 17:46:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:46:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:46:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:46:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:46:20', 'DoVa_Co2', '0']
['2021-5-4 17:46:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:46:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:46:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:46:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:46:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:47:20', 'fKWhCounter', '3442.20727539063']
['2021-5-4 17:47:20', 'fActPhLevelMixTank1', '5.60728788375854']
['2021-5-4 17:47:20', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 17:47:20', 'fActPhLevelMixTank2', '3.81377601623535']
['2021-5-4 17:47:20', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 17:47:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:47:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:47:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:47:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:47:20', 'fActCo2ValMemo', '965']
['2021-5-4 17:47:20', 'fActWaterLevelMixTank1', '277.708038330078']
['2021-5-4 17:47:20', 'fActWaterLevelMixTank2', '282.515777587891']
['2021-5-4 17:47:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:47:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:47:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:47:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:47:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:47:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:47:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:47:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:47:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:47:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:47:20', 'DoVa_Co2', '0']
['2021-5-4 17:47:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:47:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:47:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:47:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:47:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:48:20', 'fKWhCounter', '3442.30737304688']
['2021-5-4 17:48:20', 'fActPhLevelMixTank1', '5.60802030563354']
['2021-5-4 17:48:20', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 17:48:20', 'fActPhLevelMixTank2', '3.81157875061035']
['2021-5-4 17:48:20', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 17:48:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:48:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:48:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:48:20', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 17:48:20', 'fActCo2ValMemo', '961']
['2021-5-4 17:48:20', 'fActWaterLevelMixTank1', '277.463592529297']
['2021-5-4 17:48:20', 'fActWaterLevelMixTank2', '282.597259521484']
['2021-5-4 17:48:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:48:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:48:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:48:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:48:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:48:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:48:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:48:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:48:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:48:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:48:20', 'DoVa_Co2', '0']
['2021-5-4 17:48:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:48:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:48:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:48:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:48:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:49:20', 'fKWhCounter', '3442.40747070313']
['2021-5-4 17:49:20', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 17:49:20', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 17:49:20', 'fActPhLevelMixTank2', '3.81743836402893']
['2021-5-4 17:49:20', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 17:49:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:49:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:49:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:49:20', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 17:49:20', 'fActCo2ValMemo', '960']
['2021-5-4 17:49:20', 'fActWaterLevelMixTank1', '277.925354003906']
['2021-5-4 17:49:20', 'fActWaterLevelMixTank2', '282.189819335938']
['2021-5-4 17:49:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:49:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:49:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:49:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:49:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:49:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:49:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:49:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:49:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:49:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:49:20', 'DoVa_Co2', '0']
['2021-5-4 17:49:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:49:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:49:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:49:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:49:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:50:20', 'fKWhCounter', '3442.60766601563']
['2021-5-4 17:50:20', 'fActPhLevelMixTank1', '5.61094999313354']
['2021-5-4 17:50:20', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 17:50:20', 'fActPhLevelMixTank2', '3.81402015686035']
['2021-5-4 17:50:20', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 17:50:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:50:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:50:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:50:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:50:20', 'fActCo2ValMemo', '959']
['2021-5-4 17:50:20', 'fActWaterLevelMixTank1', '278.848876953125']
['2021-5-4 17:50:20', 'fActWaterLevelMixTank2', '283.357818603516']
['2021-5-4 17:50:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:50:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:50:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:50:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:50:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:50:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:50:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:50:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:50:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:50:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:50:20', 'DoVa_Co2', '0']
['2021-5-4 17:50:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:50:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:50:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:50:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:50:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:51:20', 'fKWhCounter', '3442.70776367188']
['2021-5-4 17:51:20', 'fActPhLevelMixTank1', '5.61314725875854']
['2021-5-4 17:51:20', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 17:51:20', 'fActPhLevelMixTank2', '3.82012391090393']
['2021-5-4 17:51:20', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 17:51:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:51:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:51:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:51:20', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 17:51:20', 'fActCo2ValMemo', '955']
['2021-5-4 17:51:20', 'fActWaterLevelMixTank1', '278.767364501953']
['2021-5-4 17:51:20', 'fActWaterLevelMixTank2', '283.357818603516']
['2021-5-4 17:51:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:51:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:51:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:51:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:51:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:51:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:51:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:51:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:51:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:51:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:51:20', 'DoVa_Co2', '0']
['2021-5-4 17:51:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:51:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:51:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:51:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_3_White', '0']

['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:51:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:52:20', 'fKWhCounter', '3442.90795898438']
['2021-5-4 17:52:20', 'fActPhLevelMixTank1', '5.60997343063354']
['2021-5-4 17:52:20', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 17:52:20', 'fActPhLevelMixTank2', '3.81279945373535']
['2021-5-4 17:52:20', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 17:52:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:52:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:52:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:52:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:52:20', 'fActCo2ValMemo', '953']
['2021-5-4 17:52:20', 'fActWaterLevelMixTank1', '278.767364501953']
['2021-5-4 17:52:20', 'fActWaterLevelMixTank2', '283.575103759766']
['2021-5-4 17:52:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:52:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:52:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:52:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:52:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:52:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:52:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:52:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:52:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:52:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:52:20', 'DoVa_Co2', '0']
['2021-5-4 17:52:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:52:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:52:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:52:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:52:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:53:20', 'fKWhCounter', '3443.00805664063']
['2021-5-4 17:53:20', 'fActPhLevelMixTank1', '5.6246223449707']
['2021-5-4 17:53:20', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 17:53:20', 'fActPhLevelMixTank2', '3.82036805152893']
['2021-5-4 17:53:20', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 17:53:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:53:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:53:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:53:20', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 17:53:20', 'fActCo2ValMemo', '954']
['2021-5-4 17:53:20', 'fActWaterLevelMixTank1', '278.115478515625']
['2021-5-4 17:53:20', 'fActWaterLevelMixTank2', '283.031860351563']
['2021-5-4 17:53:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:53:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:53:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:53:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:53:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:53:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:53:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:53:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:53:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:53:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:53:20', 'DoVa_Co2', '0']
['2021-5-4 17:53:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:53:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:53:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:53:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:53:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:54:20', 'fKWhCounter', '3443.20825195313']
['2021-5-4 17:54:20', 'fActPhLevelMixTank1', '5.6321907043457']
['2021-5-4 17:54:20', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 17:54:20', 'fActPhLevelMixTank2', '3.81865906715393']
['2021-5-4 17:54:20', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 17:54:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:54:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:54:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:54:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:54:20', 'fActCo2ValMemo', '955']
['2021-5-4 17:54:20', 'fActWaterLevelMixTank1', '278.033996582031']
['2021-5-4 17:54:20', 'fActWaterLevelMixTank2', '283.738098144531']
['2021-5-4 17:54:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:54:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:54:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:54:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:54:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:54:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:54:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:54:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:54:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:54:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:54:20', 'DoVa_Co2', '0']
['2021-5-4 17:54:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:54:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:54:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:54:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:54:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:55:20', 'fKWhCounter', '3443.30834960938']
['2021-5-4 17:55:20', 'fActPhLevelMixTank1', '5.6265754699707']
['2021-5-4 17:55:20', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 17:55:20', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 17:55:20', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 17:55:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:55:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:55:20', 'fActTempValMemo', '21.7000007629395']
['2021-5-4 17:55:20', 'fActRhValMemo', '50.5']
['2021-5-4 17:55:20', 'fActCo2ValMemo', '953']
['2021-5-4 17:55:20', 'fActWaterLevelMixTank1', '279.392120361328']
['2021-5-4 17:55:20', 'fActWaterLevelMixTank2', '283.520782470703']
['2021-5-4 17:55:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:55:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:55:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:55:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:55:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:55:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:55:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:55:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:55:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:55:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:55:20', 'DoVa_Co2', '0']
['2021-5-4 17:55:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:55:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:55:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:55:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:55:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:56:20', 'fKWhCounter', '3443.40844726563']
['2021-5-4 17:56:20', 'fActPhLevelMixTank1', '5.63414430618286']
['2021-5-4 17:56:20', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 17:56:20', 'fActPhLevelMixTank2', '3.81572914123535']
['2021-5-4 17:56:20', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 17:56:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:56:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:56:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 17:56:20', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 17:56:20', 'fActCo2ValMemo', '947']
['2021-5-4 17:56:20', 'fActWaterLevelMixTank1', '279.853881835938']
['2021-5-4 17:56:20', 'fActWaterLevelMixTank2', '283.846740722656']
['2021-5-4 17:56:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:56:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:56:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:56:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:56:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:56:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:56:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:56:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:56:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:56:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:56:20', 'DoVa_Co2', '0']
['2021-5-4 17:56:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:56:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:56:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:56:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:56:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']

['2021-5-4 17:57:20', 'fKWhCounter', '3443.60864257813']
['2021-5-4 17:57:20', 'fActPhLevelMixTank1', '5.6297492980957']
['2021-5-4 17:57:20', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 17:57:20', 'fActPhLevelMixTank2', '3.82207703590393']
['2021-5-4 17:57:20', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 17:57:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:57:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:57:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 17:57:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:57:20', 'fActCo2ValMemo', '949']
['2021-5-4 17:57:20', 'fActWaterLevelMixTank1', '278.033996582031']
['2021-5-4 17:57:20', 'fActWaterLevelMixTank2', '284.118347167969']
['2021-5-4 17:57:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:57:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:57:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:57:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:57:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:57:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:57:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:57:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:57:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:57:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:57:20', 'DoVa_Co2', '0']
['2021-5-4 17:57:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:57:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:57:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:57:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:57:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:58:20', 'fKWhCounter', '3443.70874023438']
['2021-5-4 17:58:20', 'fActPhLevelMixTank1', '5.63463258743286']
['2021-5-4 17:58:20', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 17:58:20', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 17:58:20', 'fActEcLevelMixTank2', '1044.34338378906']
['2021-5-4 17:58:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:58:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:58:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 17:58:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 17:58:20', 'fActCo2ValMemo', '949']
['2021-5-4 17:58:20', 'fActWaterLevelMixTank1', '279.989685058594']
['2021-5-4 17:58:20', 'fActWaterLevelMixTank2', '283.792419433594']
['2021-5-4 17:58:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:58:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:58:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:58:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:58:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:58:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:58:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:58:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:58:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:58:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:58:20', 'DoVa_Co2', '0']
['2021-5-4 17:58:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:58:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:58:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:58:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:58:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 17:59:20', 'fKWhCounter', '3443.90893554688']
['2021-5-4 17:59:20', 'fActPhLevelMixTank1', '5.64171266555786']
['2021-5-4 17:59:20', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 17:59:20', 'fActPhLevelMixTank2', '3.82427453994751']
['2021-5-4 17:59:20', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 17:59:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 17:59:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 17:59:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 17:59:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 17:59:20', 'fActCo2ValMemo', '951']
['2021-5-4 17:59:20', 'fActWaterLevelMixTank1', '279.663726806641']
['2021-5-4 17:59:20', 'fActWaterLevelMixTank2', '283.982543945313']
['2021-5-4 17:59:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 17:59:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 17:59:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 17:59:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 17:59:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 17:59:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 17:59:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 17:59:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 17:59:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 17:59:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 17:59:20', 'DoVa_Co2', '0']
['2021-5-4 17:59:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 17:59:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 17:59:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 17:59:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 17:59:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:0:20', 'fKWhCounter', '3444.00903320313']
['2021-5-4 18:0:20', 'fActPhLevelMixTank1', '5.63658571243286']
['2021-5-4 18:0:20', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 18:0:20', 'fActPhLevelMixTank2', '3.81719422340393']
['2021-5-4 18:0:20', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 18:0:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:0:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:0:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 18:0:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:0:20', 'fActCo2ValMemo', '948']
['2021-5-4 18:0:20', 'fActWaterLevelMixTank1', '280.641571044922']
['2021-5-4 18:0:20', 'fActWaterLevelMixTank2', '284.362823486328']
['2021-5-4 18:0:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:0:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:0:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:0:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:0:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:0:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:0:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:0:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:0:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:0:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:0:20', 'DoVa_Co2', '0']
['2021-5-4 18:0:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:0:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:0:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:0:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:0:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:1:20', 'fKWhCounter', '3444.20922851563']
['2021-5-4 18:1:20', 'fActPhLevelMixTank1', '5.63805055618286']
['2021-5-4 18:1:20', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 18:1:20', 'fActPhLevelMixTank2', '3.82158875465393']
['2021-5-4 18:1:20', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 18:1:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:1:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:1:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 18:1:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:1:20', 'fActCo2ValMemo', '948']
['2021-5-4 18:1:20', 'fActWaterLevelMixTank1', '280.994689941406']
['2021-5-4 18:1:20', 'fActWaterLevelMixTank2', '284.417144775391']
['2021-5-4 18:1:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:1:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:1:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:1:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:1:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:1:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:1:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:1:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:1:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:1:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:1:20', 'DoVa_Co2', '0']
['2021-5-4 18:1:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:1:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:1:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:1:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']

['2021-5-4 18:1:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:1:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:2:20', 'fKWhCounter', '3444.30932617188']
['2021-5-4 18:2:20', 'fActPhLevelMixTank1', '5.64244508743286']
['2021-5-4 18:2:20', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 18:2:20', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 18:2:20', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 18:2:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:2:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:2:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 18:2:20', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 18:2:20', 'fActCo2ValMemo', '944']
['2021-5-4 18:2:20', 'fActWaterLevelMixTank1', '279.745208740234']
['2021-5-4 18:2:20', 'fActWaterLevelMixTank2', '284.797424316406']
['2021-5-4 18:2:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:2:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:2:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:2:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:2:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:2:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:2:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:2:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:2:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:2:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:2:20', 'DoVa_Co2', '0']
['2021-5-4 18:2:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:2:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:2:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:2:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:2:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:3:20', 'fKWhCounter', '3444.50952148438']
['2021-5-4 18:3:20', 'fActPhLevelMixTank1', '5.63951539993286']
['2021-5-4 18:3:20', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 18:3:20', 'fActPhLevelMixTank2', '3.82378602027893']
['2021-5-4 18:3:20', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 18:3:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:3:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:3:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 18:3:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:3:20', 'fActCo2ValMemo', '943']
['2021-5-4 18:3:20', 'fActWaterLevelMixTank1', '280.071166992188']
['2021-5-4 18:3:20', 'fActWaterLevelMixTank2', '285.09619140625']
['2021-5-4 18:3:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:3:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:3:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:3:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:3:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:3:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:3:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:3:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:3:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:3:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:3:20', 'DoVa_Co2', '0']
['2021-5-4 18:3:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:3:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:3:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:3:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:3:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:4:20', 'fKWhCounter', '3444.60961914063']
['2021-5-4 18:4:20', 'fActPhLevelMixTank1', '5.64366579055786']
['2021-5-4 18:4:20', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 18:4:20', 'fActPhLevelMixTank2', '3.82110047340393']
['2021-5-4 18:4:20', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 18:4:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:4:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:4:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 18:4:20', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 18:4:20', 'fActCo2ValMemo', '941']
['2021-5-4 18:4:20', 'fActWaterLevelMixTank1', '279.690887451172']
['2021-5-4 18:4:20', 'fActWaterLevelMixTank2', '284.525787353516']
['2021-5-4 18:4:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:4:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:4:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:4:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:4:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:4:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:4:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:4:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:4:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:4:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:4:20', 'DoVa_Co2', '0']
['2021-5-4 18:4:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:4:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:4:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:4:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:4:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:5:20', 'fKWhCounter', '3444.70971679688']
['2021-5-4 18:5:20', 'fActPhLevelMixTank1', '5.63975954055786']
['2021-5-4 18:5:20', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 18:5:20', 'fActPhLevelMixTank2', '3.82573938369751']
['2021-5-4 18:5:20', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 18:5:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:5:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:5:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 18:5:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:5:20', 'fActCo2ValMemo', '941']
['2021-5-4 18:5:20', 'fActWaterLevelMixTank1', '281.483612060547']
['2021-5-4 18:5:20', 'fActWaterLevelMixTank2', '284.715942382813']
['2021-5-4 18:5:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:5:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:5:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:5:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:5:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:5:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:5:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:5:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:5:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:5:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:5:20', 'DoVa_Co2', '0']
['2021-5-4 18:5:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:5:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:5:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:5:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:5:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:6:20', 'fKWhCounter', '3444.90991210938']
['2021-5-4 18:6:20', 'fActPhLevelMixTank1', '5.64195680618286']
['2021-5-4 18:6:20', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 18:6:20', 'fActPhLevelMixTank2', '3.81865906715393']
['2021-5-4 18:6:20', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 18:6:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:6:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:6:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 18:6:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:6:20', 'fActCo2ValMemo', '939']
['2021-5-4 18:6:20', 'fActWaterLevelMixTank1', '281.456451416016']
['2021-5-4 18:6:20', 'fActWaterLevelMixTank2', '284.933227539063']
['2021-5-4 18:6:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:6:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:6:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:6:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:6:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:6:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:6:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:6:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:6:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:6:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:6:20', 'DoVa_Co2', '0']
['2021-5-4 18:6:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:6:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:6:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:6:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']

['2021-5-4 18:6:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:6:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:7:20', 'fKWhCounter', '3445.01000976563']
['2021-5-4 18:7:20', 'fActPhLevelMixTank1', '5.64171266555786']
['2021-5-4 18:7:20', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 18:7:20', 'fActPhLevelMixTank2', '3.82476282119751']
['2021-5-4 18:7:20', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 18:7:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:7:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:7:20', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 18:7:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:7:20', 'fActCo2ValMemo', '940']
['2021-5-4 18:7:20', 'fActWaterLevelMixTank1', '282.081176757813']
['2021-5-4 18:7:20', 'fActWaterLevelMixTank2', '285.041870117188']
['2021-5-4 18:7:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:7:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:7:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:7:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:7:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:7:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:7:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:7:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:7:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:7:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:7:20', 'DoVa_Co2', '0']
['2021-5-4 18:7:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:7:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:7:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:7:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:7:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:8:20', 'fKWhCounter', '3445.21020507813']
['2021-5-4 18:8:20', 'fActPhLevelMixTank1', '5.64293336868286']
['2021-5-4 18:8:20', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 18:8:20', 'fActPhLevelMixTank2', '3.82427453994751']
['2021-5-4 18:8:20', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 18:8:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:8:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:8:20', 'fActTempValMemo', '21.5']
['2021-5-4 18:8:20', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 18:8:20', 'fActCo2ValMemo', '938']
['2021-5-4 18:8:20', 'fActWaterLevelMixTank1', '282.515777587891']
['2021-5-4 18:8:20', 'fActWaterLevelMixTank2', '285.748107910156']
['2021-5-4 18:8:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:8:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:8:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:8:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:8:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:8:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:8:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:8:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:8:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:8:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:8:20', 'DoVa_Co2', '0']
['2021-5-4 18:8:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:8:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:8:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:8:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:8:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:9:20', 'fKWhCounter', '3445.31030273438']
['2021-5-4 18:9:20', 'fActPhLevelMixTank1', '5.64659547805786']
['2021-5-4 18:9:20', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 18:9:20', 'fActPhLevelMixTank2', '3.82256531715393']
['2021-5-4 18:9:20', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 18:9:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:9:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:9:20', 'fActTempValMemo', '21.5']
['2021-5-4 18:9:20', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 18:9:20', 'fActCo2ValMemo', '937']
['2021-5-4 18:9:20', 'fActWaterLevelMixTank1', '282.081176757813']
['2021-5-4 18:9:20', 'fActWaterLevelMixTank2', '285.476470947266']
['2021-5-4 18:9:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:9:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:9:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:9:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:9:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:9:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:9:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:9:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:9:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:9:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:9:20', 'DoVa_Co2', '0']
['2021-5-4 18:9:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:9:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:9:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:9:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:9:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:10:20', 'fKWhCounter', '3445.41040039063']
['2021-5-4 18:10:20', 'fActPhLevelMixTank1', '5.64293336868286']
['2021-5-4 18:10:20', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 18:10:20', 'fActPhLevelMixTank2', '3.81939148902893']
['2021-5-4 18:10:20', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 18:10:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:10:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:10:20', 'fActTempValMemo', '21.5']
['2021-5-4 18:10:20', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 18:10:20', 'fActCo2ValMemo', '933']
['2021-5-4 18:10:20', 'fActWaterLevelMixTank1', '281.891052246094']
['2021-5-4 18:10:20', 'fActWaterLevelMixTank2', '285.557952880859']
['2021-5-4 18:10:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:10:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:10:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:10:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:10:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:10:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:10:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:10:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:10:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:10:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:10:20', 'DoVa_Co2', '0']
['2021-5-4 18:10:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:10:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:10:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:10:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:10:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:11:20', 'fKWhCounter', '3445.61059570313']
['2021-5-4 18:11:20', 'fActPhLevelMixTank1', '5.64293336868286']
['2021-5-4 18:11:20', 'fActEcLevelMixTank1', '2031.0068359375']
['2021-5-4 18:11:20', 'fActPhLevelMixTank2', '3.82329773902893']
['2021-5-4 18:11:20', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 18:11:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:11:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:11:20', 'fActTempValMemo', '21.5']
['2021-5-4 18:11:20', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 18:11:20', 'fActCo2ValMemo', '931']
['2021-5-4 18:11:20', 'fActWaterLevelMixTank1', '282.162658691406']
['2021-5-4 18:11:20', 'fActWaterLevelMixTank2', '285.367828369141']
['2021-5-4 18:11:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:11:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:11:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:11:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:11:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:11:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:11:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:11:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:11:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:11:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:11:20', 'DoVa_Co2', '0']
['2021-5-4 18:11:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:11:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:11:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:11:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_1_Red', '0']

['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:11:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:12:20', 'fKWhCounter', '3445.71069335938']
['2021-5-4 18:12:20', 'fActPhLevelMixTank1', '5.65318775177002']
['2021-5-4 18:12:20', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 18:12:20', 'fActPhLevelMixTank2', '3.81865906715393']
['2021-5-4 18:12:20', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 18:12:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:12:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:12:20', 'fActTempValMemo', '21.5']
['2021-5-4 18:12:20', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 18:12:20', 'fActCo2ValMemo', '927']
['2021-5-4 18:12:20', 'fActWaterLevelMixTank1', '282.678741455078']
['2021-5-4 18:12:20', 'fActWaterLevelMixTank2', '286.046875']
['2021-5-4 18:12:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:12:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:12:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:12:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:12:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:12:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:12:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:12:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:12:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:12:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:12:20', 'DoVa_Co2', '0']
['2021-5-4 18:12:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:12:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:12:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:12:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:12:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:13:20', 'fKWhCounter', '3445.91088867188']
['2021-5-4 18:13:20', 'fActPhLevelMixTank1', '5.64659547805786']
['2021-5-4 18:13:20', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 18:13:20', 'fActPhLevelMixTank2', '3.82378602027893']
['2021-5-4 18:13:20', 'fActEcLevelMixTank2', '1040.986328125']
['2021-5-4 18:13:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:13:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:13:20', 'fActTempValMemo', '21.5']
['2021-5-4 18:13:20', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 18:13:20', 'fActCo2ValMemo', '922']
['2021-5-4 18:13:20', 'fActWaterLevelMixTank1', '282.9775390625']
['2021-5-4 18:13:20', 'fActWaterLevelMixTank2', '286.807434082031']
['2021-5-4 18:13:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:13:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:13:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:13:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:13:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:13:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:13:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:13:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:13:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:13:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:13:20', 'DoVa_Co2', '0']
['2021-5-4 18:13:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:13:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:13:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:13:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:13:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:14:20', 'fKWhCounter', '3446.01098632813']
['2021-5-4 18:14:20', 'fActPhLevelMixTank1', '5.65099048614502']
['2021-5-4 18:14:20', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 18:14:20', 'fActPhLevelMixTank2', '3.81914734840393']
['2021-5-4 18:14:20', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 18:14:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:14:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:14:20', 'fActTempValMemo', '21.5']
['2021-5-4 18:14:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:14:20', 'fActCo2ValMemo', '922']
['2021-5-4 18:14:20', 'fActWaterLevelMixTank1', '282.896057128906']
['2021-5-4 18:14:20', 'fActWaterLevelMixTank2', '286.046875']
['2021-5-4 18:14:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:14:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:14:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:14:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:14:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:14:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:14:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:14:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:14:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:14:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:14:20', 'DoVa_Co2', '0']
['2021-5-4 18:14:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:14:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:14:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:14:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:14:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:15:20', 'fKWhCounter', '3446.21118164063']
['2021-5-4 18:15:20', 'fActPhLevelMixTank1', '5.65440845489502']
['2021-5-4 18:15:20', 'fActEcLevelMixTank1', '2029.48083496094']
['2021-5-4 18:15:20', 'fActPhLevelMixTank2', '3.82866907119751']
['2021-5-4 18:15:20', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 18:15:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:15:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:15:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:15:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:15:20', 'fActCo2ValMemo', '920']
['2021-5-4 18:15:20', 'fActWaterLevelMixTank1', '282.678741455078']
['2021-5-4 18:15:20', 'fActWaterLevelMixTank2', '286.481475830078']
['2021-5-4 18:15:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:15:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:15:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:15:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:15:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:15:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:15:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:15:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:15:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:15:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:15:20', 'DoVa_Co2', '0']
['2021-5-4 18:15:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:15:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:15:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:15:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:15:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:16:20', 'fKWhCounter', '3446.31127929688']
['2021-5-4 18:16:20', 'fActPhLevelMixTank1', '5.65416431427002']
['2021-5-4 18:16:20', 'fActEcLevelMixTank1', '2032.38012695313']
['2021-5-4 18:16:20', 'fActPhLevelMixTank2', '3.82476282119751']
['2021-5-4 18:16:20', 'fActEcLevelMixTank2', '1039.1552734375']
['2021-5-4 18:16:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:16:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:16:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:16:20', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 18:16:20', 'fActCo2ValMemo', '920']
['2021-5-4 18:16:20', 'fActWaterLevelMixTank1', '283.031860351563']
['2021-5-4 18:16:20', 'fActWaterLevelMixTank2', '287.024719238281']
['2021-5-4 18:16:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:16:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:16:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:16:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:16:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:16:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:16:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:16:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:16:20', 'DoVa_IrrigateLevel_1_MT2', '0']

['2021-5-4 18:16:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:16:20', 'DoVa_Co2', '0']
['2021-5-4 18:16:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:16:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:16:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:16:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:16:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:17:20', 'fKWhCounter', '3446.41137695313']
['2021-5-4 18:17:20', 'fActPhLevelMixTank1', '5.65538501739502']
['2021-5-4 18:17:20', 'fActEcLevelMixTank1', '2031.92236328125']
['2021-5-4 18:17:20', 'fActPhLevelMixTank2', '3.82158875465393']
['2021-5-4 18:17:20', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 18:17:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:17:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:17:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:17:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:17:20', 'fActCo2ValMemo', '920']
['2021-5-4 18:17:20', 'fActWaterLevelMixTank1', '283.819580078125']
['2021-5-4 18:17:20', 'fActWaterLevelMixTank2', '286.535797119141']
['2021-5-4 18:17:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:17:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:17:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:17:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:17:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:17:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:17:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:17:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:17:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:17:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:17:20', 'DoVa_Co2', '0']
['2021-5-4 18:17:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:17:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:17:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:17:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:17:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:18:20', 'fKWhCounter', '3446.61157226563']
['2021-5-4 18:18:20', 'fActPhLevelMixTank1', '5.65636157989502']
['2021-5-4 18:18:20', 'fActEcLevelMixTank1', '2032.53271484375']
['2021-5-4 18:18:20', 'fActPhLevelMixTank2', '3.82573938369751']
['2021-5-4 18:18:20', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 18:18:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:18:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:18:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:18:20', 'fActRhValMemo', '50']
['2021-5-4 18:18:20', 'fActCo2ValMemo', '919']
['2021-5-4 18:18:20', 'fActWaterLevelMixTank1', '282.488616943359']
['2021-5-4 18:18:20', 'fActWaterLevelMixTank2', '286.916076660156']
['2021-5-4 18:18:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:18:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:18:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:18:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:18:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:18:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:18:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:18:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:18:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:18:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:18:20', 'DoVa_Co2', '0']
['2021-5-4 18:18:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:18:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:18:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:18:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:18:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:19:20', 'fKWhCounter', '3446.71166992188']
['2021-5-4 18:19:20', 'fActPhLevelMixTank1', '5.59239482879639']
['2021-5-4 18:19:20', 'fActEcLevelMixTank1', '2033.90600585938']
['2021-5-4 18:19:20', 'fActPhLevelMixTank2', '3.74346137046814']
['2021-5-4 18:19:20', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 18:19:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:19:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:19:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:19:20', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 18:19:20', 'fActCo2ValMemo', '915']
['2021-5-4 18:19:20', 'fActWaterLevelMixTank1', '283.656585693359']
['2021-5-4 18:19:20', 'fActWaterLevelMixTank2', '271.786651611328']
['2021-5-4 18:19:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:19:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:19:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:19:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:19:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:19:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:19:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:19:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:19:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:19:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:19:20', 'DoVa_Co2', '0']
['2021-5-4 18:19:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:19:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:19:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:19:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:19:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:20:20', 'fKWhCounter', '3446.91186523438']
['2021-5-4 18:20:20', 'fActPhLevelMixTank1', '5.56456184387207']
['2021-5-4 18:20:20', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 18:20:20', 'fActPhLevelMixTank2', '3.74077582359314']
['2021-5-4 18:20:20', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 18:20:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:20:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:20:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:20:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:20:20', 'fActCo2ValMemo', '916']
['2021-5-4 18:20:20', 'fActWaterLevelMixTank1', '272.683013916016']
['2021-5-4 18:20:20', 'fActWaterLevelMixTank2', '306.608795166016']
['2021-5-4 18:20:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:20:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:20:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:20:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:20:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:20:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:20:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:20:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:20:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:20:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:20:20', 'DoVa_Co2', '0']
['2021-5-4 18:20:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:20:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:20:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:20:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:20:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:21:20', 'fKWhCounter', '3447.11206054688']
['2021-5-4 18:21:20', 'fActPhLevelMixTank1', '5.56553840637207']
['2021-5-4 18:21:20', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 18:21:20', 'fActPhLevelMixTank2', '3.74150824546814']
['2021-5-4 18:21:20', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 18:21:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:21:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:21:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:21:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:21:20', 'fActCo2ValMemo', '914']
['2021-5-4 18:21:20', 'fActWaterLevelMixTank1', '278.522918701172']
['2021-5-4 18:21:20', 'fActWaterLevelMixTank2', '298.324279785156']
['2021-5-4 18:21:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:21:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:21:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:21:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:21:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:21:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:21:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:21:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:21:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:21:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:21:20', 'DoVa_Co2', '0']
['2021-5-4 18:21:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:21:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:21:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:21:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_1_White', '0']

['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:21:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:22:20', 'fKWhCounter', '3447.31225585938']
['2021-5-4 18:22:20', 'fActPhLevelMixTank1', '5.56505012512207']
['2021-5-4 18:22:20', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 18:22:20', 'fActPhLevelMixTank2', '3.74810028076172']
['2021-5-4 18:22:20', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 18:22:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:22:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:22:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:22:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:22:20', 'fActCo2ValMemo', '916']
['2021-5-4 18:22:20', 'fActWaterLevelMixTank1', '271.542175292969']
['2021-5-4 18:22:20', 'fActWaterLevelMixTank2', '296.151275634766']
['2021-5-4 18:22:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:22:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:22:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:22:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:22:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:22:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:22:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:22:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:22:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:22:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:22:20', 'DoVa_Co2', '0']
['2021-5-4 18:22:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:22:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:22:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:22:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:22:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:23:20', 'fKWhCounter', '3447.41235351563']
['2021-5-4 18:23:20', 'fActPhLevelMixTank1', '5.56382942199707']
['2021-5-4 18:23:20', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 18:23:20', 'fActPhLevelMixTank2', '3.74639129638672']
['2021-5-4 18:23:20', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 18:23:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:23:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:23:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:23:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:23:20', 'fActCo2ValMemo', '917']
['2021-5-4 18:23:20', 'fActWaterLevelMixTank1', '272.655853271484']
['2021-5-4 18:23:20', 'fActWaterLevelMixTank2', '282.081176757813']
['2021-5-4 18:23:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:23:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:23:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:23:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:23:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:23:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:23:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:23:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:23:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:23:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:23:20', 'DoVa_Co2', '0']
['2021-5-4 18:23:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:23:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:23:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:23:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:23:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:24:20', 'fKWhCounter', '3447.61254882813']
['2021-5-4 18:24:20', 'fActPhLevelMixTank1', '5.56602668762207']
['2021-5-4 18:24:20', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 18:24:20', 'fActPhLevelMixTank2', '3.77739810943604']
['2021-5-4 18:24:20', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 18:24:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:24:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:24:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:24:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:24:20', 'fActCo2ValMemo', '915']
['2021-5-4 18:24:20', 'fActWaterLevelMixTank1', '273.036102294922']
['2021-5-4 18:24:20', 'fActWaterLevelMixTank2', '279.962524414063']
['2021-5-4 18:24:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:24:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:24:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:24:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:24:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:24:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:24:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:24:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:24:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:24:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:24:20', 'DoVa_Co2', '0']
['2021-5-4 18:24:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:24:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:24:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:24:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:24:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:25:20', 'fKWhCounter', '3447.71264648438']
['2021-5-4 18:25:20', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 18:25:20', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 18:25:20', 'fActPhLevelMixTank2', '3.79937124252319']
['2021-5-4 18:25:20', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 18:25:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:25:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:25:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:25:20', 'fActRhValMemo', '51']
['2021-5-4 18:25:20', 'fActCo2ValMemo', '917']
['2021-5-4 18:25:20', 'fActWaterLevelMixTank1', '272.981781005859']
['2021-5-4 18:25:20', 'fActWaterLevelMixTank2', '280.071166992188']
['2021-5-4 18:25:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:25:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:25:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:25:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:25:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:25:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:25:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:25:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:25:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:25:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:25:20', 'DoVa_Co2', '0']
['2021-5-4 18:25:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:25:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:25:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:25:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:25:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:26:20', 'fKWhCounter', '3447.91284179688']
['2021-5-4 18:26:20', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 18:26:20', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 18:26:20', 'fActPhLevelMixTank2', '3.80205702781677']
['2021-5-4 18:26:20', 'fActEcLevelMixTank2', '1041.29150390625']
['2021-5-4 18:26:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:26:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:26:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:26:20', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 18:26:20', 'fActCo2ValMemo', '916']
['2021-5-4 18:26:20', 'fActWaterLevelMixTank1', '272.384216308594']
['2021-5-4 18:26:20', 'fActWaterLevelMixTank2', '279.690887451172']
['2021-5-4 18:26:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:26:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:26:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:26:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:26:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:26:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:26:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:26:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:26:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:26:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:26:20', 'DoVa_Co2', '0']
['2021-5-4 18:26:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:26:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:26:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:26:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']

['2021-5-4 18:26:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:26:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:27:20', 'fKWhCounter', '3448.01293945313']
['2021-5-4 18:27:20', 'fActPhLevelMixTank1', '5.58433771133423']
['2021-5-4 18:27:20', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 18:27:20', 'fActPhLevelMixTank2', '3.79692983627319']
['2021-5-4 18:27:20', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 18:27:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:27:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:27:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:27:20', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 18:27:20', 'fActCo2ValMemo', '915']
['2021-5-4 18:27:20', 'fActWaterLevelMixTank1', '270.428527832031']
['2021-5-4 18:27:20', 'fActWaterLevelMixTank2', '279.066162109375']
['2021-5-4 18:27:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:27:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:27:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:27:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:27:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:27:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:27:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:27:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:27:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:27:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:27:20', 'DoVa_Co2', '0']
['2021-5-4 18:27:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:27:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:27:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:27:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:27:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:28:20', 'fKWhCounter', '3448.21313476563']
['2021-5-4 18:28:20', 'fActPhLevelMixTank1', '5.58043146133423']
['2021-5-4 18:28:20', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 18:28:20', 'fActPhLevelMixTank2', '3.79107022285461']
['2021-5-4 18:28:20', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 18:28:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:28:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:28:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:28:20', 'fActRhValMemo', '51']
['2021-5-4 18:28:20', 'fActCo2ValMemo', '914']
['2021-5-4 18:28:20', 'fActWaterLevelMixTank1', '271.053253173828']
['2021-5-4 18:28:20', 'fActWaterLevelMixTank2', '278.930358886719']
['2021-5-4 18:28:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:28:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:28:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:28:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:28:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:28:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:28:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:28:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:28:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:28:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:28:20', 'DoVa_Co2', '0']
['2021-5-4 18:28:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:28:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:28:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:28:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:28:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:29:20', 'fKWhCounter', '3448.31323242188']
['2021-5-4 18:29:20', 'fActPhLevelMixTank1', '5.58287286758423']
['2021-5-4 18:29:20', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 18:29:20', 'fActPhLevelMixTank2', '3.78887295722961']
['2021-5-4 18:29:20', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 18:29:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:29:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:29:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:29:20', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 18:29:20', 'fActCo2ValMemo', '917']
['2021-5-4 18:29:20', 'fActWaterLevelMixTank1', '272.194091796875']
['2021-5-4 18:29:20', 'fActWaterLevelMixTank2', '279.066162109375']
['2021-5-4 18:29:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:29:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:29:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:29:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:29:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:29:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:29:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:29:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:29:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:29:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:29:20', 'DoVa_Co2', '0']
['2021-5-4 18:29:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:29:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:29:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:29:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:29:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:30:20', 'fKWhCounter', '3448.51342773438']
['2021-5-4 18:30:20', 'fActPhLevelMixTank1', '5.57994318008423']
['2021-5-4 18:30:20', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 18:30:20', 'fActPhLevelMixTank2', '3.78984951972961']
['2021-5-4 18:30:20', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 18:30:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:30:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:30:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:30:20', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 18:30:20', 'fActCo2ValMemo', '917']
['2021-5-4 18:30:20', 'fActWaterLevelMixTank1', '272.248413085938']
['2021-5-4 18:30:20', 'fActWaterLevelMixTank2', '278.95751953125']
['2021-5-4 18:30:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:30:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:30:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:30:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:30:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:30:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:30:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:30:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:30:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:30:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:30:20', 'DoVa_Co2', '0']
['2021-5-4 18:30:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:30:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:30:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:30:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:30:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:31:20', 'fKWhCounter', '3448.61352539063']
['2021-5-4 18:31:20', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 18:31:20', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 18:31:20', 'fActPhLevelMixTank2', '3.79448843002319']
['2021-5-4 18:31:20', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 18:31:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:31:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:31:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:31:20', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 18:31:20', 'fActCo2ValMemo', '915']
['2021-5-4 18:31:20', 'fActWaterLevelMixTank1', '272.655853271484']
['2021-5-4 18:31:20', 'fActWaterLevelMixTank2', '279.473602294922']
['2021-5-4 18:31:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:31:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:31:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:31:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:31:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:31:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:31:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:31:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:31:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:31:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:31:20', 'DoVa_Co2', '0']
['2021-5-4 18:31:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:31:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:31:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:31:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:31:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']

['2021-5-4 18:32:20', 'fKWhCounter', '3448.71362304688']
['2021-5-4 18:32:20', 'fActPhLevelMixTank1', '5.58311700820923']
['2021-5-4 18:32:20', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 18:32:20', 'fActPhLevelMixTank2', '3.79253506660461']
['2021-5-4 18:32:20', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 18:32:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:32:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:32:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:32:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:32:20', 'fActCo2ValMemo', '912']
['2021-5-4 18:32:20', 'fActWaterLevelMixTank1', '273.905303955078']
['2021-5-4 18:32:20', 'fActWaterLevelMixTank2', '279.310607910156']
['2021-5-4 18:32:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:32:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:32:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:32:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:32:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:32:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:32:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:32:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:32:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:32:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:32:20', 'DoVa_Co2', '0']
['2021-5-4 18:32:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:32:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:32:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:32:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:32:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:33:20', 'fKWhCounter', '3448.91381835938']
['2021-5-4 18:33:20', 'fActPhLevelMixTank1', '5.57628107070923']
['2021-5-4 18:33:20', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 18:33:20', 'fActPhLevelMixTank2', '3.79375600814819']
['2021-5-4 18:33:20', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 18:33:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:33:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:33:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:33:20', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:33:20', 'fActCo2ValMemo', '909']
['2021-5-4 18:33:20', 'fActWaterLevelMixTank1', '272.791656494141']
['2021-5-4 18:33:20', 'fActWaterLevelMixTank2', '279.337799072266']
['2021-5-4 18:33:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:33:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:33:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:33:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:33:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:33:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:33:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:33:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:33:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:33:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:33:20', 'DoVa_Co2', '0']
['2021-5-4 18:33:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:33:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:33:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:33:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:33:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:34:20', 'fKWhCounter', '3449.01391601563']
['2021-5-4 18:34:20', 'fActPhLevelMixTank1', '5.58384943008423']
['2021-5-4 18:34:20', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 18:34:20', 'fActPhLevelMixTank2', '3.78838467597961']
['2021-5-4 18:34:20', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 18:34:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:34:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:34:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:34:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:34:20', 'fActCo2ValMemo', '909']
['2021-5-4 18:34:20', 'fActWaterLevelMixTank1', '273.633697509766']
['2021-5-4 18:34:20', 'fActWaterLevelMixTank2', '280.044006347656']
['2021-5-4 18:34:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:34:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:34:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:34:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:34:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:34:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:34:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:34:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:34:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:34:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:34:20', 'DoVa_Co2', '0']
['2021-5-4 18:34:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:34:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:34:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:34:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:34:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:35:20', 'fKWhCounter', '3449.21411132813']
['2021-5-4 18:35:20', 'fActPhLevelMixTank1', '5.57310724258423']
['2021-5-4 18:35:20', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 18:35:20', 'fActPhLevelMixTank2', '3.79277920722961']
['2021-5-4 18:35:20', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 18:35:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:35:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:35:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:35:20', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 18:35:20', 'fActCo2ValMemo', '907']
['2021-5-4 18:35:20', 'fActWaterLevelMixTank1', '275.535064697266']
['2021-5-4 18:35:20', 'fActWaterLevelMixTank2', '280.750213623047']
['2021-5-4 18:35:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:35:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:35:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:35:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:35:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:35:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:35:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:35:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:35:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:35:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:35:20', 'DoVa_Co2', '0']
['2021-5-4 18:35:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:35:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:35:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:35:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:35:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:36:20', 'fKWhCounter', '3449.31420898438']
['2021-5-4 18:36:20', 'fActPhLevelMixTank1', '5.57603693008423']
['2021-5-4 18:36:20', 'fActEcLevelMixTank1', '1999.8779296875']
['2021-5-4 18:36:20', 'fActPhLevelMixTank2', '3.78691983222961']
['2021-5-4 18:36:20', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 18:36:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:36:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:36:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:36:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:36:20', 'fActCo2ValMemo', '911']
['2021-5-4 18:36:20', 'fActWaterLevelMixTank1', '275.806671142578']
['2021-5-4 18:36:20', 'fActWaterLevelMixTank2', '280.804565429688']
['2021-5-4 18:36:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:36:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:36:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:36:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:36:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:36:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:36:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:36:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:36:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:36:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:36:20', 'DoVa_Co2', '0']
['2021-5-4 18:36:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:36:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:36:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:36:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']

['2021-5-4 18:36:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:36:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:37:21', 'fKWhCounter', '3449.51440429688']
['2021-5-4 18:37:21', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 18:37:21', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 18:37:21', 'fActPhLevelMixTank2', '3.79644155502319']
['2021-5-4 18:37:21', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 18:37:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:37:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:37:21', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:37:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:37:21', 'fActCo2ValMemo', '909']
['2021-5-4 18:37:21', 'fActWaterLevelMixTank1', '275.589385986328']
['2021-5-4 18:37:21', 'fActWaterLevelMixTank2', '281.103332519531']
['2021-5-4 18:37:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:37:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:37:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:37:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:37:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:37:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:37:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:37:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:37:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:37:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:37:21', 'DoVa_Co2', '0']
['2021-5-4 18:37:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:37:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:37:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:37:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:37:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:38:20', 'fKWhCounter', '3449.61450195313']
['2021-5-4 18:38:20', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 18:38:20', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 18:38:20', 'fActPhLevelMixTank2', '3.79497671127319']
['2021-5-4 18:38:20', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 18:38:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:38:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:38:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:38:20', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 18:38:20', 'fActCo2ValMemo', '910']
['2021-5-4 18:38:20', 'fActWaterLevelMixTank1', '275.698028564453']
['2021-5-4 18:38:20', 'fActWaterLevelMixTank2', '281.347808837891']
['2021-5-4 18:38:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:38:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:38:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:38:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:38:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:38:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:38:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:38:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:38:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:38:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:38:20', 'DoVa_Co2', '0']
['2021-5-4 18:38:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:38:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:38:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:38:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:38:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:39:20', 'fKWhCounter', '3449.71459960938']
['2021-5-4 18:39:20', 'fActPhLevelMixTank1', '5.58677959442139']
['2021-5-4 18:39:20', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 18:39:20', 'fActPhLevelMixTank2', '3.79155850410461']
['2021-5-4 18:39:20', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 18:39:20', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:39:20', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:39:20', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:39:20', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:39:20', 'fActCo2ValMemo', '908']
['2021-5-4 18:39:20', 'fActWaterLevelMixTank1', '276.540069580078']
['2021-5-4 18:39:20', 'fActWaterLevelMixTank2', '281.049011230469']
['2021-5-4 18:39:20', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:39:20', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:39:20', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:39:20', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:39:20', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:39:20', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:39:20', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:39:20', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:39:20', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:39:20', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:39:20', 'DoVa_Co2', '0']
['2021-5-4 18:39:20', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:39:20', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:39:20', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:39:20', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:39:20', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:40:21', 'fKWhCounter', '3449.91479492188']
['2021-5-4 18:40:21', 'fActPhLevelMixTank1', '5.58775615692139']
['2021-5-4 18:40:21', 'fActEcLevelMixTank1', '1997.28381347656']
['2021-5-4 18:40:21', 'fActPhLevelMixTank2', '3.79741811752319']
['2021-5-4 18:40:21', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 18:40:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:40:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:40:21', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:40:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:40:21', 'fActCo2ValMemo', '904']
['2021-5-4 18:40:21', 'fActWaterLevelMixTank1', '274.855987548828']
['2021-5-4 18:40:21', 'fActWaterLevelMixTank2', '281.103332519531']
['2021-5-4 18:40:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:40:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:40:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:40:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:40:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:40:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:40:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:40:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:40:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:40:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:40:21', 'DoVa_Co2', '0']
['2021-5-4 18:40:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:40:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:40:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:40:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:40:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:41:21', 'fKWhCounter', '3450.01489257813']
['2021-5-4 18:41:21', 'fActPhLevelMixTank1', '5.59825420379639']
['2021-5-4 18:41:21', 'fActEcLevelMixTank1', '2015.13720703125']
['2021-5-4 18:41:21', 'fActPhLevelMixTank2', '3.79644155502319']
['2021-5-4 18:41:21', 'fActEcLevelMixTank2', '1028.32116699219']
['2021-5-4 18:41:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:41:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:41:21', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 18:41:21', 'fActRhValMemo', '51']
['2021-5-4 18:41:21', 'fActCo2ValMemo', '905']
['2021-5-4 18:41:21', 'fActWaterLevelMixTank1', '276.947509765625']
['2021-5-4 18:41:21', 'fActWaterLevelMixTank2', '281.537933349609']
['2021-5-4 18:41:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:41:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:41:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:41:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:41:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:41:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:41:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:41:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:41:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:41:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:41:21', 'DoVa_Co2', '0']
['2021-5-4 18:41:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:41:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:41:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:41:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_1_Fred', '0']

['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:41:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:42:21', 'fKWhCounter', '3450.21508789063']
['2021-5-4 18:42:21', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 18:42:21', 'fActEcLevelMixTank1', '2014.52685546875']
['2021-5-4 18:42:21', 'fActPhLevelMixTank2', '3.79839468002319']
['2021-5-4 18:42:21', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 18:42:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:42:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:42:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:42:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:42:21', 'fActCo2ValMemo', '898']
['2021-5-4 18:42:21', 'fActWaterLevelMixTank1', '277.246276855469']
['2021-5-4 18:42:21', 'fActWaterLevelMixTank2', '281.673736572266']
['2021-5-4 18:42:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:42:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:42:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:42:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:42:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:42:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:42:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:42:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:42:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:42:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:42:21', 'DoVa_Co2', '0']
['2021-5-4 18:42:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:42:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:42:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:42:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:42:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:43:21', 'fKWhCounter', '3450.31518554688']
['2021-5-4 18:43:21', 'fActPhLevelMixTank1', '5.59630107879639']
['2021-5-4 18:43:21', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 18:43:21', 'fActPhLevelMixTank2', '3.79839468002319']
['2021-5-4 18:43:21', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 18:43:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:43:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:43:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:43:21', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 18:43:21', 'fActCo2ValMemo', '897']
['2021-5-4 18:43:21', 'fActWaterLevelMixTank1', '275.725189208984']
['2021-5-4 18:43:21', 'fActWaterLevelMixTank2', '282.271331787109']
['2021-5-4 18:43:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:43:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:43:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:43:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:43:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:43:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:43:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:43:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:43:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:43:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:43:21', 'DoVa_Co2', '0']
['2021-5-4 18:43:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:43:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:43:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:43:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:43:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:44:21', 'fKWhCounter', '3450.51538085938']
['2021-5-4 18:44:21', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 18:44:21', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 18:44:21', 'fActPhLevelMixTank2', '3.80449843406677']
['2021-5-4 18:44:21', 'fActEcLevelMixTank2', '1029.23669433594']
['2021-5-4 18:44:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:44:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:44:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:44:21', 'fActRhValMemo', '50.5']
['2021-5-4 18:44:21', 'fActCo2ValMemo', '896']
['2021-5-4 18:44:21', 'fActWaterLevelMixTank1', '276.540069580078']
['2021-5-4 18:44:21', 'fActWaterLevelMixTank2', '281.999694824219']
['2021-5-4 18:44:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:44:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:44:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:44:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:44:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:44:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:44:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:44:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:44:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:44:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:44:21', 'DoVa_Co2', '0']
['2021-5-4 18:44:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:44:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:44:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:44:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:44:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:45:21', 'fKWhCounter', '3450.61547851563']
['2021-5-4 18:45:21', 'fActPhLevelMixTank1', '5.59947490692139']
['2021-5-4 18:45:21', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 18:45:21', 'fActPhLevelMixTank2', '3.80156874656677']
['2021-5-4 18:45:21', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 18:45:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:45:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:45:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:45:21', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 18:45:21', 'fActCo2ValMemo', '892']
['2021-5-4 18:45:21', 'fActWaterLevelMixTank1', '278.658721923828']
['2021-5-4 18:45:21', 'fActWaterLevelMixTank2', '282.298492431641']
['2021-5-4 18:45:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:45:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:45:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:45:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:45:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:45:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:45:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:45:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:45:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:45:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:45:21', 'DoVa_Co2', '0']
['2021-5-4 18:45:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:45:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:45:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:45:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:45:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:46:21', 'fKWhCounter', '3450.71557617188']
['2021-5-4 18:46:21', 'fActPhLevelMixTank1', '5.60533475875854']
['2021-5-4 18:46:21', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 18:46:21', 'fActPhLevelMixTank2', '3.80864906311035']
['2021-5-4 18:46:21', 'fActEcLevelMixTank2', '1040.68115234375']
['2021-5-4 18:46:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:46:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:46:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:46:21', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 18:46:21', 'fActCo2ValMemo', '890']
['2021-5-4 18:46:21', 'fActWaterLevelMixTank1', '277.871002197266']
['2021-5-4 18:46:21', 'fActWaterLevelMixTank2', '282.814575195313']
['2021-5-4 18:46:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:46:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:46:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:46:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:46:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:46:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:46:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:46:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:46:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:46:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:46:21', 'DoVa_Co2', '0']
['2021-5-4 18:46:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:46:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:46:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:46:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_2_Fred', '0']

['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:46:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:47:21', 'fKWhCounter', '3450.91577148438']
['2021-5-4 18:47:21', 'fActPhLevelMixTank1', '5.59556865692139']
['2021-5-4 18:47:21', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 18:47:21', 'fActPhLevelMixTank2', '3.80596327781677']
['2021-5-4 18:47:21', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 18:47:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:47:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:47:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:47:21', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:47:21', 'fActCo2ValMemo', '890']
['2021-5-4 18:47:21', 'fActWaterLevelMixTank1', '278.22412109375']
['2021-5-4 18:47:21', 'fActWaterLevelMixTank2', '282.298492431641']
['2021-5-4 18:47:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:47:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:47:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:47:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:47:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:47:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:47:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:47:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:47:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:47:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:47:21', 'DoVa_Co2', '0']
['2021-5-4 18:47:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:47:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:47:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:47:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:47:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:48:21', 'fKWhCounter', '3451.01586914063']
['2021-5-4 18:48:21', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 18:48:21', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 18:48:21', 'fActPhLevelMixTank2', '3.80449843406677']
['2021-5-4 18:48:21', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 18:48:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:48:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:48:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:48:21', 'fActRhValMemo', '50.5']
['2021-5-4 18:48:21', 'fActCo2ValMemo', '892']
['2021-5-4 18:48:21', 'fActWaterLevelMixTank1', '278.522918701172']
['2021-5-4 18:48:21', 'fActWaterLevelMixTank2', '282.950378417969']
['2021-5-4 18:48:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:48:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:48:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:48:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:48:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:48:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:48:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:48:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:48:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:48:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:48:21', 'DoVa_Co2', '0']
['2021-5-4 18:48:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:48:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:48:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:48:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:48:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:49:21', 'fKWhCounter', '3451.21606445313']
['2021-5-4 18:49:21', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 18:49:21', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 18:49:21', 'fActPhLevelMixTank2', '3.80352187156677']
['2021-5-4 18:49:21', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 18:49:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:49:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:49:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:49:21', 'fActRhValMemo', '50.5']
['2021-5-4 18:49:21', 'fActCo2ValMemo', '893']
['2021-5-4 18:49:21', 'fActWaterLevelMixTank1', '279.147644042969']
['2021-5-4 18:49:21', 'fActWaterLevelMixTank2', '283.140502929688']
['2021-5-4 18:49:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:49:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:49:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:49:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:49:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:49:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:49:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:49:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:49:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:49:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:49:21', 'DoVa_Co2', '0']
['2021-5-4 18:49:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:49:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:49:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:49:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:49:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:50:21', 'fKWhCounter', '3451.31616210938']
['2021-5-4 18:50:21', 'fActPhLevelMixTank1', '5.59263896942139']
['2021-5-4 18:50:21', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 18:50:21', 'fActPhLevelMixTank2', '3.80767226219177']
['2021-5-4 18:50:21', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 18:50:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:50:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:50:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:50:21', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 18:50:21', 'fActCo2ValMemo', '888']
['2021-5-4 18:50:21', 'fActWaterLevelMixTank1', '279.690887451172']
['2021-5-4 18:50:21', 'fActWaterLevelMixTank2', '283.629425048828']
['2021-5-4 18:50:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:50:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:50:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:50:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:50:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:50:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:50:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:50:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:50:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:50:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:50:21', 'DoVa_Co2', '0']
['2021-5-4 18:50:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:50:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:50:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:50:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:50:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:51:21', 'fKWhCounter', '3451.51635742188']
['2021-5-4 18:51:21', 'fActPhLevelMixTank1', '5.60509061813354']
['2021-5-4 18:51:21', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 18:51:21', 'fActPhLevelMixTank2', '3.81279945373535']
['2021-5-4 18:51:21', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 18:51:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:51:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:51:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:51:21', 'fActRhValMemo', '50.5']
['2021-5-4 18:51:21', 'fActCo2ValMemo', '886']
['2021-5-4 18:51:21', 'fActWaterLevelMixTank1', '279.555084228516']
['2021-5-4 18:51:21', 'fActWaterLevelMixTank2', '283.792419433594']
['2021-5-4 18:51:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:51:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:51:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:51:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:51:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:51:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:51:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:51:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:51:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:51:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:51:21', 'DoVa_Co2', '0']
['2021-5-4 18:51:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:51:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:51:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:51:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:51:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:52:21', 'fKWhCounter', '3451.61645507813']
['2021-5-4 18:52:21', 'fActPhLevelMixTank1', '5.59727764129639']
['2021-5-4 18:52:21', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 18:52:21', 'fActPhLevelMixTank2', '3.80791640281677']
['2021-5-4 18:52:21', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 18:52:21', 'fTaktCounterUpperLevel', '0']

['2021-5-4 18:52:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:52:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:52:21', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 18:52:21', 'fActCo2ValMemo', '889']
['2021-5-4 18:52:21', 'fActWaterLevelMixTank1', '279.853881835938']
['2021-5-4 18:52:21', 'fActWaterLevelMixTank2', '283.738098144531']
['2021-5-4 18:52:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:52:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:52:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:52:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:52:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:52:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:52:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:52:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:52:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:52:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:52:21', 'DoVa_Co2', '0']
['2021-5-4 18:52:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:52:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:52:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:52:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:52:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:53:21', 'fKWhCounter', '3451.71655273438']
['2021-5-4 18:53:21', 'fActPhLevelMixTank1', '5.60240507125854']
['2021-5-4 18:53:21', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 18:53:21', 'fActPhLevelMixTank2', '3.81182289123535']
['2021-5-4 18:53:21', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 18:53:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:53:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:53:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:53:21', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 18:53:21', 'fActCo2ValMemo', '889']
['2021-5-4 18:53:21', 'fActWaterLevelMixTank1', '278.95751953125']
['2021-5-4 18:53:21', 'fActWaterLevelMixTank2', '283.982543945313']
['2021-5-4 18:53:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:53:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:53:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:53:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:53:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:53:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:53:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:53:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:53:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:53:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:53:21', 'DoVa_Co2', '0']
['2021-5-4 18:53:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:53:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:53:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:53:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:53:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:54:21', 'fKWhCounter', '3451.91674804688']
['2021-5-4 18:54:21', 'fActPhLevelMixTank1', '5.59752178192139']
['2021-5-4 18:54:21', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 18:54:21', 'fActPhLevelMixTank2', '3.80986976623535']
['2021-5-4 18:54:21', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 18:54:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:54:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:54:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:54:21', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 18:54:21', 'fActCo2ValMemo', '884']
['2021-5-4 18:54:21', 'fActWaterLevelMixTank1', '280.12548828125']
['2021-5-4 18:54:21', 'fActWaterLevelMixTank2', '283.738098144531']
['2021-5-4 18:54:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:54:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:54:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:54:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:54:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:54:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:54:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:54:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:54:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:54:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:54:21', 'DoVa_Co2', '0']
['2021-5-4 18:54:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:54:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:54:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:54:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:54:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:55:21', 'fKWhCounter', '3452.01684570313']
['2021-5-4 18:55:21', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 18:55:21', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 18:55:21', 'fActPhLevelMixTank2', '3.80962562561035']
['2021-5-4 18:55:21', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 18:55:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:55:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:55:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:55:21', 'fActRhValMemo', '50.5']
['2021-5-4 18:55:21', 'fActCo2ValMemo', '881']
['2021-5-4 18:55:21', 'fActWaterLevelMixTank1', '281.320648193359']
['2021-5-4 18:55:21', 'fActWaterLevelMixTank2', '285.041870117188']
['2021-5-4 18:55:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:55:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:55:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:55:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:55:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:55:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:55:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:55:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:55:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:55:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:55:21', 'DoVa_Co2', '0']
['2021-5-4 18:55:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:55:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:55:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:55:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:55:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:56:21', 'fKWhCounter', '3452.21704101563']
['2021-5-4 18:56:21', 'fActPhLevelMixTank1', '5.60118389129639']
['2021-5-4 18:56:21', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 18:56:21', 'fActPhLevelMixTank2', '3.81646180152893']
['2021-5-4 18:56:21', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 18:56:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:56:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:56:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:56:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 18:56:21', 'fActCo2ValMemo', '880']
['2021-5-4 18:56:21', 'fActWaterLevelMixTank1', '279.663726806641']
['2021-5-4 18:56:21', 'fActWaterLevelMixTank2', '284.389984130859']
['2021-5-4 18:56:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:56:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:56:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:56:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:56:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:56:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:56:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:56:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:56:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:56:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:56:21', 'DoVa_Co2', '0']
['2021-5-4 18:56:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:56:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:56:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:56:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:56:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:57:21', 'fKWhCounter', '3452.31713867188']
['2021-5-4 18:57:21', 'fActPhLevelMixTank1', '5.59849834442139']
['2021-5-4 18:57:21', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 18:57:21', 'fActPhLevelMixTank2', '3.80986976623535']
['2021-5-4 18:57:21', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 18:57:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:57:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:57:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 18:57:21', 'fActRhValMemo', '50.5']
['2021-5-4 18:57:21', 'fActCo2ValMemo', '880']
['2021-5-4 18:57:21', 'fActWaterLevelMixTank1', '281.483612060547']
['2021-5-4 18:57:21', 'fActWaterLevelMixTank2', '284.389984130859']
['2021-5-4 18:57:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:57:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:57:21', 'DoPu_AddEcBMixTank_1', '0']

['2021-5-4 18:57:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:57:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:57:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:57:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:57:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:57:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:57:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:57:21', 'DoVa_Co2', '0']
['2021-5-4 18:57:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:57:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:57:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:57:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:57:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:58:21', 'fKWhCounter', '3452.51733398438']
['2021-5-4 18:58:21', 'fActPhLevelMixTank1', '5.60875272750854']
['2021-5-4 18:58:21', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 18:58:21', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 18:58:21', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 18:58:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:58:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:58:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 18:58:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 18:58:21', 'fActCo2ValMemo', '880']
['2021-5-4 18:58:21', 'fActWaterLevelMixTank1', '280.261291503906']
['2021-5-4 18:58:21', 'fActWaterLevelMixTank2', '284.933227539063']
['2021-5-4 18:58:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:58:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:58:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:58:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:58:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:58:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:58:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:58:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:58:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:58:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:58:21', 'DoVa_Co2', '0']
['2021-5-4 18:58:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:58:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:58:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:58:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:58:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 18:59:21', 'fKWhCounter', '3452.61743164063']
['2021-5-4 18:59:21', 'fActPhLevelMixTank1', '5.60338163375854']
['2021-5-4 18:59:21', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 18:59:21', 'fActPhLevelMixTank2', '3.81060218811035']
['2021-5-4 18:59:21', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 18:59:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 18:59:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 18:59:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 18:59:21', 'fActRhValMemo', '50.5']
['2021-5-4 18:59:21', 'fActCo2ValMemo', '882']
['2021-5-4 18:59:21', 'fActWaterLevelMixTank1', '281.320648193359']
['2021-5-4 18:59:21', 'fActWaterLevelMixTank2', '285.150543212891']
['2021-5-4 18:59:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 18:59:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 18:59:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 18:59:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 18:59:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 18:59:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 18:59:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 18:59:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 18:59:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 18:59:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 18:59:21', 'DoVa_Co2', '0']
['2021-5-4 18:59:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 18:59:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 18:59:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 18:59:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 18:59:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:0:21', 'fKWhCounter', '3452.71752929688']
['2021-5-4 19:0:21', 'fActPhLevelMixTank1', '5.61070585250854']
['2021-5-4 19:0:21', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 19:0:21', 'fActPhLevelMixTank2', '3.81865906715393']
['2021-5-4 19:0:21', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 19:0:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:0:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:0:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:0:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 19:0:21', 'fActCo2ValMemo', '883']
['2021-5-4 19:0:21', 'fActWaterLevelMixTank1', '281.320648193359']
['2021-5-4 19:0:21', 'fActWaterLevelMixTank2', '285.123382568359']
['2021-5-4 19:0:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:0:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:0:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:0:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:0:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:0:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:0:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:0:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:0:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:0:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:0:21', 'DoVa_Co2', '0']
['2021-5-4 19:0:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:0:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:0:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:0:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:0:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:1:21', 'fKWhCounter', '3452.91772460938']
['2021-5-4 19:1:21', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 19:1:21', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 19:1:21', 'fActPhLevelMixTank2', '3.81304359436035']
['2021-5-4 19:1:21', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 19:1:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:1:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:1:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:1:21', 'fActRhValMemo', '51']
['2021-5-4 19:1:21', 'fActCo2ValMemo', '882']
['2021-5-4 19:1:21', 'fActWaterLevelMixTank1', '281.565093994141']
['2021-5-4 19:1:21', 'fActWaterLevelMixTank2', '285.666625976563']
['2021-5-4 19:1:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:1:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:1:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:1:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:1:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:1:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:1:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:1:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:1:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:1:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:1:21', 'DoVa_Co2', '0']
['2021-5-4 19:1:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:1:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:1:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:1:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:1:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:2:21', 'fKWhCounter', '3453.01782226563']
['2021-5-4 19:2:21', 'fActPhLevelMixTank1', '5.61265897750854']
['2021-5-4 19:2:21', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 19:2:21', 'fActPhLevelMixTank2', '3.81255531311035']
['2021-5-4 19:2:21', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 19:2:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:2:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:2:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:2:21', 'fActRhValMemo', '51']
['2021-5-4 19:2:21', 'fActCo2ValMemo', '883']
['2021-5-4 19:2:21', 'fActWaterLevelMixTank1', '282.678741455078']
['2021-5-4 19:2:21', 'fActWaterLevelMixTank2', '286.074066162109']
['2021-5-4 19:2:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:2:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:2:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:2:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:2:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:2:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:2:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:2:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:2:21', 'DoVa_IrrigateLevel_1_MT2', '0']

['2021-5-4 19:2:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:2:21', 'DoVa_Co2', '0']
['2021-5-4 19:2:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:2:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:2:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:2:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:2:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:3:21', 'fKWhCounter', '3453.21801757813']
['2021-5-4 19:3:21', 'fActPhLevelMixTank1', '5.61534452438354']
['2021-5-4 19:3:21', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 19:3:21', 'fActPhLevelMixTank2', '3.81255531311035']
['2021-5-4 19:3:21', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 19:3:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:3:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:3:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:3:21', 'fActRhValMemo', '51']
['2021-5-4 19:3:21', 'fActCo2ValMemo', '881']
['2021-5-4 19:3:21', 'fActWaterLevelMixTank1', '283.031860351563']
['2021-5-4 19:3:21', 'fActWaterLevelMixTank2', '286.209869384766']
['2021-5-4 19:3:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:3:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:3:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:3:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:3:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:3:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:3:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:3:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:3:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:3:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:3:21', 'DoVa_Co2', '0']
['2021-5-4 19:3:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:3:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:3:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:3:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:3:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:4:21', 'fKWhCounter', '3453.31811523438']
['2021-5-4 19:4:21', 'fActPhLevelMixTank1', '5.60875272750854']
['2021-5-4 19:4:21', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 19:4:21', 'fActPhLevelMixTank2', '3.81377601623535']
['2021-5-4 19:4:21', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 19:4:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:4:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:4:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:4:21', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 19:4:21', 'fActCo2ValMemo', '876']
['2021-5-4 19:4:21', 'fActWaterLevelMixTank1', '282.733093261719']
['2021-5-4 19:4:21', 'fActWaterLevelMixTank2', '286.916076660156']
['2021-5-4 19:4:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:4:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:4:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:4:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:4:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:4:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:4:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:4:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:4:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:4:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:4:21', 'DoVa_Co2', '0']
['2021-5-4 19:4:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:4:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:4:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:4:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:4:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:5:21', 'fKWhCounter', '3453.51831054688']
['2021-5-4 19:5:21', 'fActPhLevelMixTank1', '5.6175422668457']
['2021-5-4 19:5:21', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 19:5:21', 'fActPhLevelMixTank2', '3.82012391090393']
['2021-5-4 19:5:21', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 19:5:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:5:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:5:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:5:21', 'fActRhValMemo', '51']
['2021-5-4 19:5:21', 'fActCo2ValMemo', '877']
['2021-5-4 19:5:21', 'fActWaterLevelMixTank1', '282.081176757813']
['2021-5-4 19:5:21', 'fActWaterLevelMixTank2', '287.133392333984']
['2021-5-4 19:5:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:5:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:5:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:5:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:5:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:5:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:5:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:5:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:5:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:5:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:5:21', 'DoVa_Co2', '0']
['2021-5-4 19:5:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:5:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:5:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:5:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:5:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:6:21', 'fKWhCounter', '3453.61840820313']
['2021-5-4 19:6:21', 'fActPhLevelMixTank1', '5.6182746887207']
['2021-5-4 19:6:21', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 19:6:21', 'fActPhLevelMixTank2', '3.81450843811035']
['2021-5-4 19:6:21', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 19:6:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:6:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:6:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:6:21', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 19:6:21', 'fActCo2ValMemo', '873']
['2021-5-4 19:6:21', 'fActWaterLevelMixTank1', '282.624420166016']
['2021-5-4 19:6:21', 'fActWaterLevelMixTank2', '287.242034912109']
['2021-5-4 19:6:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:6:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:6:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:6:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:6:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:6:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:6:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:6:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:6:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:6:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:6:21', 'DoVa_Co2', '0']
['2021-5-4 19:6:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:6:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:6:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:6:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:6:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:7:21', 'fKWhCounter', '3453.71850585938']
['2021-5-4 19:7:21', 'fActPhLevelMixTank1', '5.6197395324707']
['2021-5-4 19:7:21', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 19:7:21', 'fActPhLevelMixTank2', '3.82256531715393']
['2021-5-4 19:7:21', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 19:7:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:7:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:7:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:7:21', 'fActRhValMemo', '51']
['2021-5-4 19:7:21', 'fActCo2ValMemo', '869']
['2021-5-4 19:7:21', 'fActWaterLevelMixTank1', '283.92822265625']
['2021-5-4 19:7:21', 'fActWaterLevelMixTank2', '287.269195556641']
['2021-5-4 19:7:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:7:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:7:21', 'DoPu_AddEcBMixTank_1', '0']

['2021-5-4 19:7:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:7:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:7:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:7:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:7:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:7:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:7:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:7:21', 'DoVa_Co2', '0']
['2021-5-4 19:7:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:7:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:7:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:7:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:7:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:8:21', 'fKWhCounter', '3453.91870117188']
['2021-5-4 19:8:21', 'fActPhLevelMixTank1', '5.6177864074707']
['2021-5-4 19:8:21', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 19:8:21', 'fActPhLevelMixTank2', '3.81914734840393']
['2021-5-4 19:8:21', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 19:8:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:8:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:8:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:8:21', 'fActRhValMemo', '51']
['2021-5-4 19:8:21', 'fActCo2ValMemo', '867']
['2021-5-4 19:8:21', 'fActWaterLevelMixTank1', '284.281341552734']
['2021-5-4 19:8:21', 'fActWaterLevelMixTank2', '287.540832519531']
['2021-5-4 19:8:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:8:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:8:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:8:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:8:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:8:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:8:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:8:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:8:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:8:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:8:21', 'DoVa_Co2', '0']
['2021-5-4 19:8:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:8:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:8:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:8:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:8:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:9:21', 'fKWhCounter', '3454.01879882813']
['2021-5-4 19:9:21', 'fActPhLevelMixTank1', '5.6285285949707']
['2021-5-4 19:9:21', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 19:9:21', 'fActPhLevelMixTank2', '3.81572914123535']
['2021-5-4 19:9:21', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 19:9:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:9:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:9:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:9:21', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 19:9:21', 'fActCo2ValMemo', '865']
['2021-5-4 19:9:21', 'fActWaterLevelMixTank1', '284.552947998047']
['2021-5-4 19:9:21', 'fActWaterLevelMixTank2', '288.192718505859']
['2021-5-4 19:9:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:9:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:9:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:9:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:9:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:9:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:9:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:9:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:9:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:9:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:9:21', 'DoVa_Co2', '0']
['2021-5-4 19:9:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:9:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:9:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:9:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:9:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:10:21', 'fKWhCounter', '3454.21899414063']
['2021-5-4 19:10:21', 'fActPhLevelMixTank1', '5.6290168762207']
['2021-5-4 19:10:21', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 19:10:21', 'fActPhLevelMixTank2', '3.82036805152893']
['2021-5-4 19:10:21', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 19:10:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:10:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:10:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:10:21', 'fActRhValMemo', '51']
['2021-5-4 19:10:21', 'fActCo2ValMemo', '863']
['2021-5-4 19:10:21', 'fActWaterLevelMixTank1', '284.471466064453']
['2021-5-4 19:10:21', 'fActWaterLevelMixTank2', '287.839599609375']
['2021-5-4 19:10:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:10:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:10:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:10:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:10:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:10:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:10:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:10:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:10:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:10:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:10:21', 'DoVa_Co2', '0']
['2021-5-4 19:10:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:10:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:10:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:10:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:10:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:11:21', 'fKWhCounter', '3454.31909179688']
['2021-5-4 19:11:21', 'fActPhLevelMixTank1', '5.6280403137207']
['2021-5-4 19:11:21', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 19:11:21', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 19:11:21', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 19:11:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:11:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:11:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:11:21', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 19:11:21', 'fActCo2ValMemo', '864']
['2021-5-4 19:11:21', 'fActWaterLevelMixTank1', '285.069030761719']
['2021-5-4 19:11:21', 'fActWaterLevelMixTank2', '288.382843017578']
['2021-5-4 19:11:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:11:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:11:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:11:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:11:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:11:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:11:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:11:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:11:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:11:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:11:21', 'DoVa_Co2', '0']
['2021-5-4 19:11:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:11:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:11:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:11:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']

['2021-5-4 19:11:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:11:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:12:21', 'fKWhCounter', '3454.51928710938']
['2021-5-4 19:12:21', 'fActPhLevelMixTank1', '5.6299934387207']
['2021-5-4 19:12:21', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 19:12:21', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 19:12:21', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 19:12:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:12:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:12:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:12:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 19:12:21', 'fActCo2ValMemo', '862']
['2021-5-4 19:12:21', 'fActWaterLevelMixTank1', '284.118347167969']
['2021-5-4 19:12:21', 'fActWaterLevelMixTank2', '288.681640625']
['2021-5-4 19:12:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:12:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:12:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:12:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:12:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:12:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:12:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:12:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:12:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:12:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:12:21', 'DoVa_Co2', '0']
['2021-5-4 19:12:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:12:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:12:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:12:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:12:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:13:21', 'fKWhCounter', '3454.61938476563']
['2021-5-4 19:13:21', 'fActPhLevelMixTank1', '5.63316774368286']
['2021-5-4 19:13:21', 'fActEcLevelMixTank1', '2031.92236328125']
['2021-5-4 19:13:21', 'fActPhLevelMixTank2', '3.82378602027893']
['2021-5-4 19:13:21', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 19:13:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:13:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:13:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:13:21', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 19:13:21', 'fActCo2ValMemo', '862']
['2021-5-4 19:13:21', 'fActWaterLevelMixTank1', '285.286346435547']
['2021-5-4 19:13:21', 'fActWaterLevelMixTank2', '288.89892578125']
['2021-5-4 19:13:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:13:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:13:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:13:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:13:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:13:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:13:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:13:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:13:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:13:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:13:21', 'DoVa_Co2', '0']
['2021-5-4 19:13:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:13:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:13:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:13:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:13:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:14:21', 'fKWhCounter', '3454.71948242188']
['2021-5-4 19:14:21', 'fActPhLevelMixTank1', '5.63756227493286']
['2021-5-4 19:14:21', 'fActEcLevelMixTank1', '2031.0068359375']
['2021-5-4 19:14:21', 'fActPhLevelMixTank2', '3.82256531715393']
['2021-5-4 19:14:21', 'fActEcLevelMixTank2', '1039.765625']
['2021-5-4 19:14:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:14:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:14:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:14:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 19:14:21', 'fActCo2ValMemo', '862']
['2021-5-4 19:14:21', 'fActWaterLevelMixTank1', '285.123382568359']
['2021-5-4 19:14:21', 'fActWaterLevelMixTank2', '288.491516113281']
['2021-5-4 19:14:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:14:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:14:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:14:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:14:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:14:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:14:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:14:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:14:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:14:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:14:21', 'DoVa_Co2', '0']
['2021-5-4 19:14:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:14:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:14:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:14:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:14:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:15:21', 'fKWhCounter', '3454.91967773438']
['2021-5-4 19:15:21', 'fActPhLevelMixTank1', '5.6302375793457']
['2021-5-4 19:15:21', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 19:15:21', 'fActPhLevelMixTank2', '3.82378602027893']
['2021-5-4 19:15:21', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 19:15:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:15:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:15:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:15:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 19:15:21', 'fActCo2ValMemo', '859']
['2021-5-4 19:15:21', 'fActWaterLevelMixTank1', '285.204864501953']
['2021-5-4 19:15:21', 'fActWaterLevelMixTank2', '289.170562744141']
['2021-5-4 19:15:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:15:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:15:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:15:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:15:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:15:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:15:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:15:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:15:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:15:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:15:21', 'DoVa_Co2', '0']
['2021-5-4 19:15:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:15:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:15:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:15:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:15:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:16:21', 'fKWhCounter', '3455.01977539063']
['2021-5-4 19:16:21', 'fActPhLevelMixTank1', '5.63805055618286']
['2021-5-4 19:16:21', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 19:16:21', 'fActPhLevelMixTank2', '3.81450843811035']
['2021-5-4 19:16:21', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 19:16:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:16:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:16:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:16:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 19:16:21', 'fActCo2ValMemo', '859']
['2021-5-4 19:16:21', 'fActWaterLevelMixTank1', '285.720947265625']
['2021-5-4 19:16:21', 'fActWaterLevelMixTank2', '289.116241455078']
['2021-5-4 19:16:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:16:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:16:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:16:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:16:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:16:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:16:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:16:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:16:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:16:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:16:21', 'DoVa_Co2', '0']

['2021-5-4 19:16:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:16:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:16:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:16:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:16:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:17:21', 'fKWhCounter', '3455.21997070313']
['2021-5-4 19:17:21', 'fActPhLevelMixTank1', '5.63707399368286']
['2021-5-4 19:17:21', 'fActEcLevelMixTank1', '2032.53271484375']
['2021-5-4 19:17:21', 'fActPhLevelMixTank2', '3.82036805152893']
['2021-5-4 19:17:21', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 19:17:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:17:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:17:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:17:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 19:17:21', 'fActCo2ValMemo', '860']
['2021-5-4 19:17:21', 'fActWaterLevelMixTank1', '286.427154541016']
['2021-5-4 19:17:21', 'fActWaterLevelMixTank2', '289.224884033203']
['2021-5-4 19:17:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:17:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:17:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:17:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:17:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:17:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:17:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:17:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:17:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:17:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:17:21', 'DoVa_Co2', '0']
['2021-5-4 19:17:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:17:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:17:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:17:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:17:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:18:21', 'fKWhCounter', '3455.32006835938']
['2021-5-4 19:18:21', 'fActPhLevelMixTank1', '5.63878297805786']
['2021-5-4 19:18:21', 'fActEcLevelMixTank1', '2031.92236328125']
['2021-5-4 19:18:21', 'fActPhLevelMixTank2', '3.81255531311035']
['2021-5-4 19:18:21', 'fActEcLevelMixTank2', '1038.544921875']
['2021-5-4 19:18:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:18:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:18:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:18:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 19:18:21', 'fActCo2ValMemo', '858']
['2021-5-4 19:18:21', 'fActWaterLevelMixTank1', '286.454315185547']
['2021-5-4 19:18:21', 'fActWaterLevelMixTank2', '289.469360351563']
['2021-5-4 19:18:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:18:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:18:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:18:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:18:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:18:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:18:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:18:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:18:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:18:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:18:21', 'DoVa_Co2', '0']
['2021-5-4 19:18:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:18:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:18:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:18:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:18:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:19:21', 'fKWhCounter', '3455.52026367188']
['2021-5-4 19:19:21', 'fActPhLevelMixTank1', '5.63756227493286']
['2021-5-4 19:19:21', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 19:19:21', 'fActPhLevelMixTank2', '3.81548500061035']
['2021-5-4 19:19:21', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 19:19:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:19:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:19:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:19:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 19:19:21', 'fActCo2ValMemo', '857']
['2021-5-4 19:19:21', 'fActWaterLevelMixTank1', '286.345672607422']
['2021-5-4 19:19:21', 'fActWaterLevelMixTank2', '290.202728271484']
['2021-5-4 19:19:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:19:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:19:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:19:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:19:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:19:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:19:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:19:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:19:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:19:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:19:21', 'DoVa_Co2', '0']
['2021-5-4 19:19:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:19:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:19:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:19:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:19:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:20:21', 'fKWhCounter', '3455.62036132813']
['2021-5-4 19:20:21', 'fActPhLevelMixTank1', '5.63975954055786']
['2021-5-4 19:20:21', 'fActEcLevelMixTank1', '2030.24389648438']
['2021-5-4 19:20:21', 'fActPhLevelMixTank2', '3.81548500061035']
['2021-5-4 19:20:21', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 19:20:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:20:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:20:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:20:21', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 19:20:21', 'fActCo2ValMemo', '858']
['2021-5-4 19:20:21', 'fActWaterLevelMixTank1', '286.345672607422']
['2021-5-4 19:20:21', 'fActWaterLevelMixTank2', '289.523681640625']
['2021-5-4 19:20:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:20:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:20:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:20:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:20:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:20:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:20:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:20:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:20:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:20:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:20:21', 'DoVa_Co2', '0']
['2021-5-4 19:20:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:20:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:20:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:20:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:20:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:21:21', 'fKWhCounter', '3455.82055664063']
['2021-5-4 19:21:21', 'fActPhLevelMixTank1', '5.64342164993286']
['2021-5-4 19:21:21', 'fActEcLevelMixTank1', '2030.396484375']
['2021-5-4 19:21:21', 'fActPhLevelMixTank2', '3.81572914123535']
['2021-5-4 19:21:21', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 19:21:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:21:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:21:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:21:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 19:21:21', 'fActCo2ValMemo', '856']
['2021-5-4 19:21:21', 'fActWaterLevelMixTank1', '286.753112792969']
['2021-5-4 19:21:21', 'fActWaterLevelMixTank2', '289.958282470703']
['2021-5-4 19:21:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:21:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:21:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:21:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:21:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:21:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:21:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:21:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:21:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:21:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:21:21', 'DoVa_Co2', '0']
['2021-5-4 19:21:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:21:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:21:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:21:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_4_Blue', '0']

['2021-5-4 19:21:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:21:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:22:21', 'fKWhCounter', '3455.92065429688']
['2021-5-4 19:22:21', 'fActPhLevelMixTank1', '5.64610719680786']
['2021-5-4 19:22:21', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 19:22:21', 'fActPhLevelMixTank2', '3.82329773902893']
['2021-5-4 19:22:21', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 19:22:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:22:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:22:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:22:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 19:22:21', 'fActCo2ValMemo', '854']
['2021-5-4 19:22:21', 'fActWaterLevelMixTank1', '286.99755859375']
['2021-5-4 19:22:21', 'fActWaterLevelMixTank2', '290.501525878906']
['2021-5-4 19:22:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:22:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:22:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:22:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:22:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:22:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:22:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:22:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:22:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:22:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:22:21', 'DoVa_Co2', '0']
['2021-5-4 19:22:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:22:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:22:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:22:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:22:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:23:21', 'fKWhCounter', '3456.02075195313']
['2021-5-4 19:23:21', 'fActPhLevelMixTank1', '5.64903736114502']
['2021-5-4 19:23:21', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 19:23:21', 'fActPhLevelMixTank2', '3.81841492652893']
['2021-5-4 19:23:21', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 19:23:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:23:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:23:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:23:21', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 19:23:21', 'fActCo2ValMemo', '854']
['2021-5-4 19:23:21', 'fActWaterLevelMixTank1', '287.350677490234']
['2021-5-4 19:23:21', 'fActWaterLevelMixTank2', '290.5830078125']
['2021-5-4 19:23:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:23:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:23:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:23:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:23:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:23:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:23:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:23:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:23:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:23:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:23:21', 'DoVa_Co2', '0']
['2021-5-4 19:23:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:23:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:23:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:23:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:23:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:24:21', 'fKWhCounter', '3456.22094726563']
['2021-5-4 19:24:21', 'fActPhLevelMixTank1', '5.58384943008423']
['2021-5-4 19:24:21', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 19:24:21', 'fActPhLevelMixTank2', '3.74321722984314']
['2021-5-4 19:24:21', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 19:24:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:24:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:24:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:24:21', 'fActRhValMemo', '50.5']
['2021-5-4 19:24:21', 'fActCo2ValMemo', '853']
['2021-5-4 19:24:21', 'fActWaterLevelMixTank1', '290.121246337891']
['2021-5-4 19:24:21', 'fActWaterLevelMixTank2', '277.680877685547']
['2021-5-4 19:24:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:24:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:24:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:24:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:24:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:24:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:24:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:24:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:24:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:24:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:24:21', 'DoVa_Co2', '0']
['2021-5-4 19:24:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:24:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:24:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:24:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:24:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:25:21', 'fKWhCounter', '3456.42114257813']
['2021-5-4 19:25:21', 'fActPhLevelMixTank1', '5.56651496887207']
['2021-5-4 19:25:21', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 19:25:21', 'fActPhLevelMixTank2', '3.73686933517456']
['2021-5-4 19:25:21', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 19:25:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:25:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:25:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:25:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 19:25:21', 'fActCo2ValMemo', '851']
['2021-5-4 19:25:21', 'fActWaterLevelMixTank1', '277.979675292969']
['2021-5-4 19:25:21', 'fActWaterLevelMixTank2', '298.623077392578']
['2021-5-4 19:25:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:25:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:25:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:25:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:25:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:25:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:25:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:25:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:25:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:25:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:25:21', 'DoVa_Co2', '0']
['2021-5-4 19:25:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:25:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:25:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:25:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:25:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:26:21', 'fKWhCounter', '3456.52124023438']
['2021-5-4 19:26:21', 'fActPhLevelMixTank1', '5.56382942199707']
['2021-5-4 19:26:21', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 19:26:21', 'fActPhLevelMixTank2', '3.73955512046814']
['2021-5-4 19:26:21', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 19:26:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:26:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:26:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:26:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 19:26:21', 'fActCo2ValMemo', '850']
['2021-5-4 19:26:21', 'fActWaterLevelMixTank1', '283.113342285156']
['2021-5-4 19:26:21', 'fActWaterLevelMixTank2', '273.878143310547']
['2021-5-4 19:26:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:26:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:26:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:26:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:26:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:26:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:26:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:26:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:26:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:26:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:26:21', 'DoVa_Co2', '0']
['2021-5-4 19:26:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:26:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:26:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:26:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:26:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:27:21', 'fKWhCounter', '3456.72143554688']
['2021-5-4 19:27:21', 'fActPhLevelMixTank1', '5.57164239883423']
['2021-5-4 19:27:21', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 19:27:21', 'fActPhLevelMixTank2', '3.74712371826172']
['2021-5-4 19:27:21', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 19:27:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:27:21', 'fTaktCounterLowerLevel', '0']

['2021-5-4 19:27:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:27:21', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 19:27:21', 'fActCo2ValMemo', '847']
['2021-5-4 19:27:21', 'fActWaterLevelMixTank1', '276.349914550781']
['2021-5-4 19:27:21', 'fActWaterLevelMixTank2', '291.642333984375']
['2021-5-4 19:27:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:27:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:27:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:27:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:27:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:27:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:27:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:27:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:27:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:27:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:27:21', 'DoVa_Co2', '0']
['2021-5-4 19:27:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:27:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:27:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:27:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:27:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:28:21', 'fKWhCounter', '3456.92163085938']
['2021-5-4 19:28:21', 'fActPhLevelMixTank1', '5.56505012512207']
['2021-5-4 19:28:21', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 19:28:21', 'fActPhLevelMixTank2', '3.74224066734314']
['2021-5-4 19:28:21', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 19:28:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:28:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:28:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:28:21', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 19:28:21', 'fActCo2ValMemo', '847']
['2021-5-4 19:28:21', 'fActWaterLevelMixTank1', '281.266326904297']
['2021-5-4 19:28:21', 'fActWaterLevelMixTank2', '262.986053466797']
['2021-5-4 19:28:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:28:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:28:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:28:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:28:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:28:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:28:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:28:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:28:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:28:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:28:21', 'DoVa_Co2', '0']
['2021-5-4 19:28:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:28:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:28:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:28:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:28:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:29:21', 'fKWhCounter', '3457.12182617188']
['2021-5-4 19:29:21', 'fActPhLevelMixTank1', '5.57506036758423']
['2021-5-4 19:29:21', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 19:29:21', 'fActPhLevelMixTank2', '3.77373576164246']
['2021-5-4 19:29:21', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 19:29:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:29:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:29:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:29:21', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 19:29:21', 'fActCo2ValMemo', '847']
['2021-5-4 19:29:21', 'fActWaterLevelMixTank1', '275.942474365234']
['2021-5-4 19:29:21', 'fActWaterLevelMixTank2', '282.407135009766']
['2021-5-4 19:29:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:29:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:29:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:29:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:29:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:29:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:29:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:29:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:29:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:29:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:29:21', 'DoVa_Co2', '0']
['2021-5-4 19:29:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:29:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:29:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:29:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:29:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:30:21', 'fKWhCounter', '3457.22192382813']
['2021-5-4 19:30:21', 'fActPhLevelMixTank1', '5.57725763320923']
['2021-5-4 19:30:21', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 19:30:21', 'fActPhLevelMixTank2', '3.79473257064819']
['2021-5-4 19:30:21', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 19:30:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:30:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:30:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:30:21', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 19:30:21', 'fActCo2ValMemo', '847']
['2021-5-4 19:30:21', 'fActWaterLevelMixTank1', '275.317749023438']
['2021-5-4 19:30:21', 'fActWaterLevelMixTank2', '282.325653076172']
['2021-5-4 19:30:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:30:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:30:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:30:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:30:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:30:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:30:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:30:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:30:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:30:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:30:21', 'DoVa_Co2', '0']
['2021-5-4 19:30:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:30:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:30:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:30:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:30:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:31:21', 'fKWhCounter', '3457.42211914063']
['2021-5-4 19:31:21', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 19:31:21', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 19:31:21', 'fActPhLevelMixTank2', '3.79082608222961']
['2021-5-4 19:31:21', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 19:31:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:31:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:31:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:31:21', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 19:31:21', 'fActCo2ValMemo', '846']
['2021-5-4 19:31:21', 'fActWaterLevelMixTank1', '275.209106445313']
['2021-5-4 19:31:21', 'fActWaterLevelMixTank2', '282.108337402344']
['2021-5-4 19:31:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:31:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:31:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:31:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:31:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:31:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:31:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:31:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:31:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:31:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:31:21', 'DoVa_Co2', '0']
['2021-5-4 19:31:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:31:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:31:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:31:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:31:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:32:21', 'fKWhCounter', '3457.52221679688']
['2021-5-4 19:32:21', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 19:32:21', 'fActEcLevelMixTank1', '2023.52978515625']

['2021-5-4 19:32:21', 'fActPhLevelMixTank2', '3.79668569564819']
['2021-5-4 19:32:21', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 19:32:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:32:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:32:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:32:21', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 19:32:21', 'fActCo2ValMemo', '846']
['2021-5-4 19:32:21', 'fActWaterLevelMixTank1', '274.774505615234']
['2021-5-4 19:32:21', 'fActWaterLevelMixTank2', '282.325653076172']
['2021-5-4 19:32:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:32:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:32:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:32:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:32:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:32:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:32:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:32:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:32:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:32:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:32:21', 'DoVa_Co2', '0']
['2021-5-4 19:32:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:32:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:32:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:32:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:32:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:33:21', 'fKWhCounter', '3457.62231445313']
['2021-5-4 19:33:21', 'fActPhLevelMixTank1', '5.57945489883423']
['2021-5-4 19:33:21', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 19:33:21', 'fActPhLevelMixTank2', '3.78594326972961']
['2021-5-4 19:33:21', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 19:33:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:33:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:33:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:33:21', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 19:33:21', 'fActCo2ValMemo', '844']
['2021-5-4 19:33:21', 'fActWaterLevelMixTank1', '275.15478515625']
['2021-5-4 19:33:21', 'fActWaterLevelMixTank2', '282.298492431641']
['2021-5-4 19:33:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:33:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:33:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:33:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:33:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:33:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:33:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:33:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:33:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:33:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:33:21', 'DoVa_Co2', '0']
['2021-5-4 19:33:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:33:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:33:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:33:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:33:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:34:21', 'fKWhCounter', '3457.82250976563']
['2021-5-4 19:34:21', 'fActPhLevelMixTank1', '5.58043146133423']
['2021-5-4 19:34:21', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 19:34:21', 'fActPhLevelMixTank2', '3.79009366035461']
['2021-5-4 19:34:21', 'fActEcLevelMixTank2', '1027.86340332031']
['2021-5-4 19:34:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:34:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:34:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:34:21', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 19:34:21', 'fActCo2ValMemo', '841']
['2021-5-4 19:34:21', 'fActWaterLevelMixTank1', '275.263427734375']
['2021-5-4 19:34:21', 'fActWaterLevelMixTank2', '281.782409667969']
['2021-5-4 19:34:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:34:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:34:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:34:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:34:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:34:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:34:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:34:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:34:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:34:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:34:21', 'DoVa_Co2', '0']
['2021-5-4 19:34:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:34:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:34:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:34:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:34:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:35:21', 'fKWhCounter', '3457.92260742188']
['2021-5-4 19:35:21', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 19:35:21', 'fActEcLevelMixTank1', '2028.87048339844']
['2021-5-4 19:35:21', 'fActPhLevelMixTank2', '3.79155850410461']
['2021-5-4 19:35:21', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 19:35:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:35:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:35:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:35:21', 'fActRhValMemo', '51.5']
['2021-5-4 19:35:21', 'fActCo2ValMemo', '838']
['2021-5-4 19:35:21', 'fActWaterLevelMixTank1', '275.507904052734']
['2021-5-4 19:35:21', 'fActWaterLevelMixTank2', '282.434295654297']
['2021-5-4 19:35:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:35:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:35:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:35:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:35:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:35:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:35:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:35:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:35:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:35:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:35:21', 'DoVa_Co2', '0']
['2021-5-4 19:35:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:35:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:35:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:35:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:35:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:36:21', 'fKWhCounter', '3458.12280273438']
['2021-5-4 19:36:21', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 19:36:21', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 19:36:21', 'fActPhLevelMixTank2', '3.78496646881104']
['2021-5-4 19:36:21', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 19:36:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:36:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:36:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:36:21', 'fActRhValMemo', '51.5']
['2021-5-4 19:36:21', 'fActCo2ValMemo', '836']
['2021-5-4 19:36:21', 'fActWaterLevelMixTank1', '276.404235839844']
['2021-5-4 19:36:21', 'fActWaterLevelMixTank2', '281.999694824219']
['2021-5-4 19:36:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:36:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:36:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:36:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:36:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:36:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:36:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:36:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:36:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:36:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:36:21', 'DoVa_Co2', '0']
['2021-5-4 19:36:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:36:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:36:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:36:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:36:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:37:21', 'fKWhCounter', '3458.22290039063']
['2021-5-4 19:37:21', 'fActPhLevelMixTank1', '5.57799005508423']
['2021-5-4 19:37:21', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 19:37:21', 'fActPhLevelMixTank2', '3.78984951972961']
['2021-5-4 19:37:21', 'fActEcLevelMixTank2', '1030.91528320313']

['2021-5-4 19:37:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:37:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:37:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:37:21', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 19:37:21', 'fActCo2ValMemo', '836']
['2021-5-4 19:37:21', 'fActWaterLevelMixTank1', '276.431396484375']
['2021-5-4 19:37:21', 'fActWaterLevelMixTank2', '282.407135009766']
['2021-5-4 19:37:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:37:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:37:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:37:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:37:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:37:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:37:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:37:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:37:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:37:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:37:21', 'DoVa_Co2', '0']
['2021-5-4 19:37:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:37:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:37:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:37:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:37:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:38:21', 'fKWhCounter', '3458.42309570313']
['2021-5-4 19:38:21', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 19:38:21', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 19:38:21', 'fActPhLevelMixTank2', '3.78838467597961']
['2021-5-4 19:38:21', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 19:38:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:38:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:38:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:38:21', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 19:38:21', 'fActCo2ValMemo', '838']
['2021-5-4 19:38:21', 'fActWaterLevelMixTank1', '276.675872802734']
['2021-5-4 19:38:21', 'fActWaterLevelMixTank2', '282.325653076172']
['2021-5-4 19:38:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:38:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:38:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:38:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:38:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:38:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:38:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:38:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:38:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:38:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:38:21', 'DoVa_Co2', '0']
['2021-5-4 19:38:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:38:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:38:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:38:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:38:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:39:21', 'fKWhCounter', '3458.52319335938']
['2021-5-4 19:39:21', 'fActPhLevelMixTank1', '5.57896661758423']
['2021-5-4 19:39:21', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 19:39:21', 'fActPhLevelMixTank2', '3.78594326972961']
['2021-5-4 19:39:21', 'fActEcLevelMixTank2', '1038.544921875']
['2021-5-4 19:39:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:39:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:39:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:39:21', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 19:39:21', 'fActCo2ValMemo', '842']
['2021-5-4 19:39:21', 'fActWaterLevelMixTank1', '277.382080078125']
['2021-5-4 19:39:21', 'fActWaterLevelMixTank2', '283.412139892578']
['2021-5-4 19:39:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:39:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:39:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:39:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:39:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:39:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:39:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:39:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:39:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:39:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:39:21', 'DoVa_Co2', '0']
['2021-5-4 19:39:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:39:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:39:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:39:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:39:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:40:21', 'fKWhCounter', '3458.62329101563']
['2021-5-4 19:40:21', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 19:40:21', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 19:40:21', 'fActPhLevelMixTank2', '3.78960537910461']
['2021-5-4 19:40:21', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 19:40:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:40:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:40:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:40:21', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 19:40:21', 'fActCo2ValMemo', '843']
['2021-5-4 19:40:21', 'fActWaterLevelMixTank1', '278.522918701172']
['2021-5-4 19:40:21', 'fActWaterLevelMixTank2', '283.982543945313']
['2021-5-4 19:40:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:40:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:40:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:40:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:40:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:40:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:40:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:40:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:40:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:40:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:40:21', 'DoVa_Co2', '0']
['2021-5-4 19:40:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:40:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:40:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:40:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:40:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:41:21', 'fKWhCounter', '3458.82348632813']
['2021-5-4 19:41:21', 'fActPhLevelMixTank1', '5.57603693008423']
['2021-5-4 19:41:21', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 19:41:21', 'fActPhLevelMixTank2', '3.78447818756104']
['2021-5-4 19:41:21', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 19:41:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:41:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:41:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:41:21', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 19:41:21', 'fActCo2ValMemo', '838']
['2021-5-4 19:41:21', 'fActWaterLevelMixTank1', '276.023986816406']
['2021-5-4 19:41:21', 'fActWaterLevelMixTank2', '284.064025878906']
['2021-5-4 19:41:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:41:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:41:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:41:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:41:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:41:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:41:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:41:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:41:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:41:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:41:21', 'DoVa_Co2', '0']
['2021-5-4 19:41:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:41:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:41:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:41:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelLayer_4_White', '0']

['2021-5-4 19:41:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:41:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:42:21', 'fKWhCounter', '3458.92358398438']
['2021-5-4 19:42:21', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 19:42:21', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 19:42:21', 'fActPhLevelMixTank2', '3.78740811347961']
['2021-5-4 19:42:21', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 19:42:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:42:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:42:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:42:21', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 19:42:21', 'fActCo2ValMemo', '836']
['2021-5-4 19:42:21', 'fActWaterLevelMixTank1', '278.658721923828']
['2021-5-4 19:42:21', 'fActWaterLevelMixTank2', '284.118347167969']
['2021-5-4 19:42:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:42:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:42:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:42:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:42:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:42:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:42:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:42:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:42:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:42:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:42:21', 'DoVa_Co2', '0']
['2021-5-4 19:42:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:42:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:42:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:42:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:42:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:43:21', 'fKWhCounter', '3459.12377929688']
['2021-5-4 19:43:21', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 19:43:21', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 19:43:21', 'fActPhLevelMixTank2', '3.78740811347961']
['2021-5-4 19:43:21', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 19:43:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:43:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:43:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:43:21', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 19:43:21', 'fActCo2ValMemo', '833']
['2021-5-4 19:43:21', 'fActWaterLevelMixTank1', '277.083312988281']
['2021-5-4 19:43:21', 'fActWaterLevelMixTank2', '284.580108642578']
['2021-5-4 19:43:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:43:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:43:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:43:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:43:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:43:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:43:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:43:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:43:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:43:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:43:21', 'DoVa_Co2', '0']
['2021-5-4 19:43:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:43:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:43:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:43:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:43:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:44:21', 'fKWhCounter', '3459.22387695313']
['2021-5-4 19:44:21', 'fActPhLevelMixTank1', '5.59190654754639']
['2021-5-4 19:44:21', 'fActEcLevelMixTank1', '2019.56237792969']
['2021-5-4 19:44:21', 'fActPhLevelMixTank2', '3.79009366035461']
['2021-5-4 19:44:21', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 19:44:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:44:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:44:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:44:21', 'fActRhValMemo', '51']
['2021-5-4 19:44:21', 'fActCo2ValMemo', '832']
['2021-5-4 19:44:21', 'fActWaterLevelMixTank1', '278.876037597656']
['2021-5-4 19:44:21', 'fActWaterLevelMixTank2', '284.362823486328']
['2021-5-4 19:44:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:44:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:44:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:44:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:44:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:44:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:44:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:44:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:44:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:44:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:44:21', 'DoVa_Co2', '0']
['2021-5-4 19:44:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:44:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:44:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:44:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:44:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:45:21', 'fKWhCounter', '3459.42407226563']
['2021-5-4 19:45:21', 'fActPhLevelMixTank1', '5.58873271942139']
['2021-5-4 19:45:21', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 19:45:21', 'fActPhLevelMixTank2', '3.79692983627319']
['2021-5-4 19:45:21', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 19:45:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:45:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:45:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:45:21', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 19:45:21', 'fActCo2ValMemo', '832']
['2021-5-4 19:45:21', 'fActWaterLevelMixTank1', '280.016845703125']
['2021-5-4 19:45:21', 'fActWaterLevelMixTank2', '285.232025146484']
['2021-5-4 19:45:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:45:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:45:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:45:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:45:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:45:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:45:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:45:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:45:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:45:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:45:21', 'DoVa_Co2', '0']
['2021-5-4 19:45:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:45:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:45:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:45:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:45:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:46:21', 'fKWhCounter', '3459.52416992188']
['2021-5-4 19:46:21', 'fActPhLevelMixTank1', '5.59483623504639']
['2021-5-4 19:46:21', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 19:46:21', 'fActPhLevelMixTank2', '3.79448843002319']
['2021-5-4 19:46:21', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 19:46:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:46:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:46:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:46:21', 'fActRhValMemo', '51']
['2021-5-4 19:46:21', 'fActCo2ValMemo', '831']
['2021-5-4 19:46:21', 'fActWaterLevelMixTank1', '280.179809570313']
['2021-5-4 19:46:21', 'fActWaterLevelMixTank2', '285.313507080078']
['2021-5-4 19:46:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:46:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:46:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:46:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:46:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:46:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:46:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:46:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:46:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:46:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:46:21', 'DoVa_Co2', '0']
['2021-5-4 19:46:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:46:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:46:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:46:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:46:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:47:21', 'fKWhCounter', '3459.72436523438']
['2021-5-4 19:47:21', 'fActPhLevelMixTank1', '5.59581279754639']
['2021-5-4 19:47:21', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 19:47:21', 'fActPhLevelMixTank2', '3.79912710189819']
['2021-5-4 19:47:21', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 19:47:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:47:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:47:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:47:21', 'fActRhValMemo', '50.5']
['2021-5-4 19:47:21', 'fActCo2ValMemo', '829']
['2021-5-4 19:47:21', 'fActWaterLevelMixTank1', '280.723052978516']
['2021-5-4 19:47:21', 'fActWaterLevelMixTank2', '285.856750488281']
['2021-5-4 19:47:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:47:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:47:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:47:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:47:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:47:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:47:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:47:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:47:21', 'DoVa_IrrigateLevel_1_MT2', '0']

['2021-5-4 19:47:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:47:21', 'DoVa_Co2', '0']
['2021-5-4 19:47:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:47:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:47:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:47:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:47:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:48:21', 'fKWhCounter', '3459.82446289063']
['2021-5-4 19:48:21', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 19:48:21', 'fActEcLevelMixTank1', '2021.08825683594']
['2021-5-4 19:48:21', 'fActPhLevelMixTank2', '3.79912710189819']
['2021-5-4 19:48:21', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 19:48:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:48:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:48:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:48:21', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 19:48:21', 'fActCo2ValMemo', '828']
['2021-5-4 19:48:21', 'fActWaterLevelMixTank1', '280.994689941406']
['2021-5-4 19:48:21', 'fActWaterLevelMixTank2', '286.074066162109']
['2021-5-4 19:48:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:48:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:48:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:48:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:48:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:48:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:48:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:48:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:48:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:48:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:48:21', 'DoVa_Co2', '0']
['2021-5-4 19:48:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:48:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:48:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:48:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:48:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:49:21', 'fKWhCounter', '3459.92456054688']
['2021-5-4 19:49:21', 'fActPhLevelMixTank1', '5.59288311004639']
['2021-5-4 19:49:21', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 19:49:21', 'fActPhLevelMixTank2', '3.79595327377319']
['2021-5-4 19:49:21', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 19:49:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:49:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:49:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:49:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 19:49:21', 'fActCo2ValMemo', '829']
['2021-5-4 19:49:21', 'fActWaterLevelMixTank1', '281.619415283203']
['2021-5-4 19:49:21', 'fActWaterLevelMixTank2', '286.590148925781']
['2021-5-4 19:49:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:49:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:49:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:49:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:49:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:49:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:49:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:49:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:49:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:49:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:49:21', 'DoVa_Co2', '0']
['2021-5-4 19:49:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:49:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:49:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:49:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:49:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:50:21', 'fKWhCounter', '3460.12475585938']
['2021-5-4 19:50:21', 'fActPhLevelMixTank1', '5.59776592254639']
['2021-5-4 19:50:21', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 19:50:21', 'fActPhLevelMixTank2', '3.80547499656677']
['2021-5-4 19:50:21', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 19:50:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:50:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:50:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:50:21', 'fActRhValMemo', '51']
['2021-5-4 19:50:21', 'fActCo2ValMemo', '828']
['2021-5-4 19:50:21', 'fActWaterLevelMixTank1', '281.429290771484']
['2021-5-4 19:50:21', 'fActWaterLevelMixTank2', '286.318511962891']
['2021-5-4 19:50:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:50:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:50:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:50:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:50:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:50:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:50:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:50:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:50:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:50:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:50:21', 'DoVa_Co2', '0']
['2021-5-4 19:50:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:50:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:50:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:50:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:50:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:51:21', 'fKWhCounter', '3460.22485351563']
['2021-5-4 19:51:21', 'fActPhLevelMixTank1', '5.59874248504639']
['2021-5-4 19:51:21', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 19:51:21', 'fActPhLevelMixTank2', '3.80034780502319']
['2021-5-4 19:51:21', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 19:51:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:51:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:51:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:51:21', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 19:51:21', 'fActCo2ValMemo', '824']
['2021-5-4 19:51:21', 'fActWaterLevelMixTank1', '281.673736572266']
['2021-5-4 19:51:21', 'fActWaterLevelMixTank2', '287.350677490234']
['2021-5-4 19:51:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:51:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:51:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:51:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:51:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:51:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:51:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:51:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:51:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:51:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:51:21', 'DoVa_Co2', '0']
['2021-5-4 19:51:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:51:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:51:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:51:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:51:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:52:21', 'fKWhCounter', '3460.42504882813']
['2021-5-4 19:52:21', 'fActPhLevelMixTank1', '5.60386991500854']
['2021-5-4 19:52:21', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 19:52:21', 'fActPhLevelMixTank2', '3.79815053939819']
['2021-5-4 19:52:21', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 19:52:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:52:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:52:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:52:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 19:52:21', 'fActCo2ValMemo', '826']
['2021-5-4 19:52:21', 'fActWaterLevelMixTank1', '281.646575927734']
['2021-5-4 19:52:21', 'fActWaterLevelMixTank2', '286.916076660156']
['2021-5-4 19:52:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:52:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:52:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:52:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:52:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:52:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:52:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:52:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:52:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:52:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:52:21', 'DoVa_Co2', '0']
['2021-5-4 19:52:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:52:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:52:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:52:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']

['2021-5-4 19:52:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:52:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:53:21', 'fKWhCounter', '3460.52514648438']
['2021-5-4 19:53:21', 'fActPhLevelMixTank1', '5.60045146942139']
['2021-5-4 19:53:21', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 19:53:21', 'fActPhLevelMixTank2', '3.80620741844177']
['2021-5-4 19:53:21', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 19:53:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:53:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:53:21', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 19:53:21', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 19:53:21', 'fActCo2ValMemo', '825']
['2021-5-4 19:53:21', 'fActWaterLevelMixTank1', '282.352813720703']
['2021-5-4 19:53:21', 'fActWaterLevelMixTank2', '287.214874267578']
['2021-5-4 19:53:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:53:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:53:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:53:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:53:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:53:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:53:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:53:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:53:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:53:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:53:21', 'DoVa_Co2', '0']
['2021-5-4 19:53:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:53:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:53:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:53:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:53:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:54:21', 'fKWhCounter', '3460.72534179688']
['2021-5-4 19:54:21', 'fActPhLevelMixTank1', '5.60289335250854']
['2021-5-4 19:54:21', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 19:54:21', 'fActPhLevelMixTank2', '3.80034780502319']
['2021-5-4 19:54:21', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 19:54:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:54:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:54:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:54:21', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 19:54:21', 'fActCo2ValMemo', '825']
['2021-5-4 19:54:21', 'fActWaterLevelMixTank1', '282.271331787109']
['2021-5-4 19:54:21', 'fActWaterLevelMixTank2', '287.214874267578']
['2021-5-4 19:54:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:54:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:54:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:54:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:54:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:54:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:54:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:54:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:54:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:54:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:54:21', 'DoVa_Co2', '0']
['2021-5-4 19:54:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:54:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:54:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:54:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:54:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:55:21', 'fKWhCounter', '3460.82543945313']
['2021-5-4 19:55:21', 'fActPhLevelMixTank1', '5.60093975067139']
['2021-5-4 19:55:21', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 19:55:21', 'fActPhLevelMixTank2', '3.80547499656677']
['2021-5-4 19:55:21', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 19:55:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:55:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:55:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:55:21', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 19:55:21', 'fActCo2ValMemo', '825']
['2021-5-4 19:55:21', 'fActWaterLevelMixTank1', '283.222015380859']
['2021-5-4 19:55:21', 'fActWaterLevelMixTank2', '287.459320068359']
['2021-5-4 19:55:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:55:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:55:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:55:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:55:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:55:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:55:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:55:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:55:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:55:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:55:21', 'DoVa_Co2', '0']
['2021-5-4 19:55:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:55:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:55:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:55:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:55:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:56:21', 'fKWhCounter', '3460.92553710938']
['2021-5-4 19:56:21', 'fActPhLevelMixTank1', '5.60728788375854']
['2021-5-4 19:56:21', 'fActEcLevelMixTank1', '2020.47790527344']
['2021-5-4 19:56:21', 'fActPhLevelMixTank2', '3.80791640281677']
['2021-5-4 19:56:21', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 19:56:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:56:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:56:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:56:21', 'fActRhValMemo', '50.0999984741211']
['2021-5-4 19:56:21', 'fActCo2ValMemo', '826']
['2021-5-4 19:56:21', 'fActWaterLevelMixTank1', '282.787414550781']
['2021-5-4 19:56:21', 'fActWaterLevelMixTank2', '287.214874267578']
['2021-5-4 19:56:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:56:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:56:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:56:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:56:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:56:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:56:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:56:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:56:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:56:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:56:21', 'DoVa_Co2', '0']
['2021-5-4 19:56:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:56:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:56:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:56:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:56:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:57:21', 'fKWhCounter', '3461.12573242188']
['2021-5-4 19:57:21', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 19:57:21', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 19:57:21', 'fActPhLevelMixTank2', '3.80303359031677']
['2021-5-4 19:57:21', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 19:57:21', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:57:21', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:57:21', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:57:21', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 19:57:21', 'fActCo2ValMemo', '827']
['2021-5-4 19:57:21', 'fActWaterLevelMixTank1', '282.244171142578']
['2021-5-4 19:57:21', 'fActWaterLevelMixTank2', '287.975402832031']
['2021-5-4 19:57:21', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:57:21', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:57:21', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:57:21', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:57:21', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:57:21', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:57:21', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:57:21', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:57:21', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:57:21', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:57:21', 'DoVa_Co2', '0']
['2021-5-4 19:57:21', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:57:21', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:57:21', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:57:21', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:57:21', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:58:22', 'fKWhCounter', '3461.22583007813']
['2021-5-4 19:58:22', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 19:58:22', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 19:58:22', 'fActPhLevelMixTank2', '3.81109046936035']
['2021-5-4 19:58:22', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 19:58:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:58:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:58:22', 'fActTempValMemo', '21.2000007629395']

['2021-5-4 19:58:22', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 19:58:22', 'fActCo2ValMemo', '824']
['2021-5-4 19:58:22', 'fActWaterLevelMixTank1', '283.629425048828']
['2021-5-4 19:58:22', 'fActWaterLevelMixTank2', '288.301361083984']
['2021-5-4 19:58:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:58:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:58:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:58:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:58:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:58:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:58:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:58:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:58:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:58:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:58:22', 'DoVa_Co2', '0']
['2021-5-4 19:58:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:58:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:58:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:58:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:58:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 19:59:22', 'fKWhCounter', '3461.42602539063']
['2021-5-4 19:59:22', 'fActPhLevelMixTank1', '5.61094999313354']
['2021-5-4 19:59:22', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 19:59:22', 'fActPhLevelMixTank2', '3.80889320373535']
['2021-5-4 19:59:22', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 19:59:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 19:59:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 19:59:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 19:59:22', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 19:59:22', 'fActCo2ValMemo', '820']
['2021-5-4 19:59:22', 'fActWaterLevelMixTank1', '282.515777587891']
['2021-5-4 19:59:22', 'fActWaterLevelMixTank2', '288.817443847656']
['2021-5-4 19:59:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 19:59:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 19:59:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 19:59:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 19:59:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 19:59:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 19:59:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 19:59:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 19:59:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 19:59:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 19:59:22', 'DoVa_Co2', '0']
['2021-5-4 19:59:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 19:59:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 19:59:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 19:59:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 19:59:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:0:22', 'fKWhCounter', '3461.52612304688']
['2021-5-4 20:0:22', 'fActPhLevelMixTank1', '5.61363554000854']
['2021-5-4 20:0:22', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 20:0:22', 'fActPhLevelMixTank2', '3.80254530906677']
['2021-5-4 20:0:22', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 20:0:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:0:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:0:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:0:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:0:22', 'fActCo2ValMemo', '819']
['2021-5-4 20:0:22', 'fActWaterLevelMixTank1', '284.145538330078']
['2021-5-4 20:0:22', 'fActWaterLevelMixTank2', '289.034759521484']
['2021-5-4 20:0:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:0:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:0:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:0:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:0:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:0:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:0:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:0:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:0:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:0:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:0:22', 'DoVa_Co2', '0']
['2021-5-4 20:0:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:0:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:0:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:0:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:0:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:1:22', 'fKWhCounter', '3461.72631835938']
['2021-5-4 20:1:22', 'fActPhLevelMixTank1', '5.60972929000854']
['2021-5-4 20:1:22', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 20:1:22', 'fActPhLevelMixTank2', '3.80669569969177']
['2021-5-4 20:1:22', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 20:1:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:1:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:1:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:1:22', 'fActRhValMemo', '51']
['2021-5-4 20:1:22', 'fActCo2ValMemo', '821']
['2021-5-4 20:1:22', 'fActWaterLevelMixTank1', '284.987548828125']
['2021-5-4 20:1:22', 'fActWaterLevelMixTank2', '289.306365966797']
['2021-5-4 20:1:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:1:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:1:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:1:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:1:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:1:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:1:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:1:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:1:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:1:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:1:22', 'DoVa_Co2', '0']
['2021-5-4 20:1:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:1:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:1:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:1:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:1:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:2:22', 'fKWhCounter', '3461.82641601563']
['2021-5-4 20:2:22', 'fActPhLevelMixTank1', '5.61168241500854']
['2021-5-4 20:2:22', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 20:2:22', 'fActPhLevelMixTank2', '3.80401015281677']
['2021-5-4 20:2:22', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 20:2:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:2:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:2:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:2:22', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 20:2:22', 'fActCo2ValMemo', '818']
['2021-5-4 20:2:22', 'fActWaterLevelMixTank1', '285.394989013672']
['2021-5-4 20:2:22', 'fActWaterLevelMixTank2', '289.523681640625']
['2021-5-4 20:2:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:2:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:2:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:2:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:2:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:2:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:2:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:2:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:2:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:2:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:2:22', 'DoVa_Co2', '0']
['2021-5-4 20:2:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:2:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:2:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:2:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:2:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:3:22', 'fKWhCounter', '3461.92651367188']
['2021-5-4 20:3:22', 'fActPhLevelMixTank1', '5.61583280563354']
['2021-5-4 20:3:22', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 20:3:22', 'fActPhLevelMixTank2', '3.80401015281677']
['2021-5-4 20:3:22', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 20:3:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:3:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:3:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:3:22', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 20:3:22', 'fActCo2ValMemo', '819']
['2021-5-4 20:3:22', 'fActWaterLevelMixTank1', '284.987548828125']
['2021-5-4 20:3:22', 'fActWaterLevelMixTank2', '289.550842285156']
['2021-5-4 20:3:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:3:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:3:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:3:22', 'DoPu_AddAcidMixTank_2', '0']

['2021-5-4 20:3:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:3:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:3:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:3:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:3:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:3:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:3:22', 'DoVa_Co2', '0']
['2021-5-4 20:3:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:3:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:3:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:3:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:3:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:4:22', 'fKWhCounter', '3462.12670898438']
['2021-5-4 20:4:22', 'fActPhLevelMixTank1', '5.61461210250854']
['2021-5-4 20:4:22', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 20:4:22', 'fActPhLevelMixTank2', '3.80816054344177']
['2021-5-4 20:4:22', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 20:4:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:4:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:4:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:4:22', 'fActRhValMemo', '51']
['2021-5-4 20:4:22', 'fActCo2ValMemo', '819']
['2021-5-4 20:4:22', 'fActWaterLevelMixTank1', '286.046875']
['2021-5-4 20:4:22', 'fActWaterLevelMixTank2', '290.202728271484']
['2021-5-4 20:4:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:4:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:4:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:4:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:4:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:4:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:4:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:4:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:4:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:4:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:4:22', 'DoVa_Co2', '0']
['2021-5-4 20:4:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:4:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:4:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:4:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:4:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:5:22', 'fKWhCounter', '3462.22680664063']
['2021-5-4 20:5:22', 'fActPhLevelMixTank1', '5.6236457824707']
['2021-5-4 20:5:22', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 20:5:22', 'fActPhLevelMixTank2', '3.80669569969177']
['2021-5-4 20:5:22', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 20:5:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:5:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:5:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:5:22', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 20:5:22', 'fActCo2ValMemo', '821']
['2021-5-4 20:5:22', 'fActWaterLevelMixTank1', '285.585144042969']
['2021-5-4 20:5:22', 'fActWaterLevelMixTank2', '289.903930664063']
['2021-5-4 20:5:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:5:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:5:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:5:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:5:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:5:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:5:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:5:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:5:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:5:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:5:22', 'DoVa_Co2', '0']
['2021-5-4 20:5:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:5:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:5:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:5:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:5:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:6:22', 'fKWhCounter', '3462.42700195313']
['2021-5-4 20:6:22', 'fActPhLevelMixTank1', '5.6192512512207']
['2021-5-4 20:6:22', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 20:6:22', 'fActPhLevelMixTank2', '3.81109046936035']
['2021-5-4 20:6:22', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 20:6:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:6:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:6:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:6:22', 'fActRhValMemo', '51']
['2021-5-4 20:6:22', 'fActCo2ValMemo', '817']
['2021-5-4 20:6:22', 'fActWaterLevelMixTank1', '284.036865234375']
['2021-5-4 20:6:22', 'fActWaterLevelMixTank2', '289.795288085938']
['2021-5-4 20:6:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:6:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:6:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:6:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:6:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:6:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:6:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:6:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:6:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:6:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:6:22', 'DoVa_Co2', '0']
['2021-5-4 20:6:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:6:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:6:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:6:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:6:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:7:22', 'fKWhCounter', '3462.52709960938']
['2021-5-4 20:7:22', 'fActPhLevelMixTank1', '5.6214485168457']
['2021-5-4 20:7:22', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 20:7:22', 'fActPhLevelMixTank2', '3.81206703186035']
['2021-5-4 20:7:22', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 20:7:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:7:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:7:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:7:22', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 20:7:22', 'fActCo2ValMemo', '816']
['2021-5-4 20:7:22', 'fActWaterLevelMixTank1', '286.345672607422']
['2021-5-4 20:7:22', 'fActWaterLevelMixTank2', '290.392852783203']
['2021-5-4 20:7:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:7:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:7:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:7:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:7:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:7:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:7:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:7:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:7:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:7:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:7:22', 'DoVa_Co2', '0']
['2021-5-4 20:7:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:7:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:7:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:7:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:7:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:8:22', 'fKWhCounter', '3462.72729492188']
['2021-5-4 20:8:22', 'fActPhLevelMixTank1', '5.6290168762207']
['2021-5-4 20:8:22', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 20:8:22', 'fActPhLevelMixTank2', '3.81084632873535']
['2021-5-4 20:8:22', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 20:8:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:8:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:8:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:8:22', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 20:8:22', 'fActCo2ValMemo', '816']
['2021-5-4 20:8:22', 'fActWaterLevelMixTank1', '286.209869384766']
['2021-5-4 20:8:22', 'fActWaterLevelMixTank2', '290.5830078125']

['2021-5-4 20:8:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:8:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:8:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:8:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:8:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:8:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:8:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:8:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:8:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:8:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:8:22', 'DoVa_Co2', '0']
['2021-5-4 20:8:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:8:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:8:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:8:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:8:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:9:22', 'fKWhCounter', '3462.82739257813']
['2021-5-4 20:9:22', 'fActPhLevelMixTank1', '5.6302375793457']
['2021-5-4 20:9:22', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 20:9:22', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 20:9:22', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 20:9:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:9:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:9:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:9:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:9:22', 'fActCo2ValMemo', '814']
['2021-5-4 20:9:22', 'fActWaterLevelMixTank1', '285.177703857422']
['2021-5-4 20:9:22', 'fActWaterLevelMixTank2', '290.392852783203']
['2021-5-4 20:9:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:9:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:9:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:9:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:9:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:9:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:9:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:9:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:9:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:9:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:9:22', 'DoVa_Co2', '0']
['2021-5-4 20:9:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:9:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:9:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:9:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:9:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:10:22', 'fKWhCounter', '3463.02758789063']
['2021-5-4 20:10:22', 'fActPhLevelMixTank1', '5.6253547668457']
['2021-5-4 20:10:22', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 20:10:22', 'fActPhLevelMixTank2', '3.81304359436035']
['2021-5-4 20:10:22', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 20:10:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:10:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:10:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:10:22', 'fActRhValMemo', '51']
['2021-5-4 20:10:22', 'fActCo2ValMemo', '816']
['2021-5-4 20:10:22', 'fActWaterLevelMixTank1', '286.345672607422']
['2021-5-4 20:10:22', 'fActWaterLevelMixTank2', '290.5830078125']
['2021-5-4 20:10:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:10:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:10:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:10:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:10:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:10:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:10:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:10:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:10:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:10:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:10:22', 'DoVa_Co2', '0']
['2021-5-4 20:10:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:10:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:10:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:10:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:10:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:11:22', 'fKWhCounter', '3463.12768554688']
['2021-5-4 20:11:22', 'fActPhLevelMixTank1', '5.63560914993286']
['2021-5-4 20:11:22', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 20:11:22', 'fActPhLevelMixTank2', '3.81865906715393']
['2021-5-4 20:11:22', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 20:11:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:11:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:11:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:11:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:11:22', 'fActCo2ValMemo', '813']
['2021-5-4 20:11:22', 'fActWaterLevelMixTank1', '286.318511962891']
['2021-5-4 20:11:22', 'fActWaterLevelMixTank2', '291.370727539063']
['2021-5-4 20:11:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:11:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:11:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:11:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:11:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:11:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:11:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:11:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:11:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:11:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:11:22', 'DoVa_Co2', '0']
['2021-5-4 20:11:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:11:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:11:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:11:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:11:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:12:22', 'fKWhCounter', '3463.22778320313']
['2021-5-4 20:12:22', 'fActPhLevelMixTank1', '5.6216926574707']
['2021-5-4 20:12:22', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 20:12:22', 'fActPhLevelMixTank2', '3.81719422340393']
['2021-5-4 20:12:22', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 20:12:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:12:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:12:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:12:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:12:22', 'fActCo2ValMemo', '814']
['2021-5-4 20:12:22', 'fActWaterLevelMixTank1', '286.834594726563']
['2021-5-4 20:12:22', 'fActWaterLevelMixTank2', '291.207733154297']
['2021-5-4 20:12:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:12:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:12:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:12:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:12:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:12:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:12:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:12:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:12:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:12:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:12:22', 'DoVa_Co2', '0']
['2021-5-4 20:12:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:12:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:12:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:12:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:12:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:13:22', 'fKWhCounter', '3463.42797851563']
['2021-5-4 20:13:22', 'fActPhLevelMixTank1', '5.63658571243286']

['2021-5-4 20:13:22', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 20:13:22', 'fActPhLevelMixTank2', '3.81084632873535']
['2021-5-4 20:13:22', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 20:13:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:13:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:13:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:13:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:13:22', 'fActCo2ValMemo', '814']
['2021-5-4 20:13:22', 'fActWaterLevelMixTank1', '286.725952148438']
['2021-5-4 20:13:22', 'fActWaterLevelMixTank2', '291.234893798828']
['2021-5-4 20:13:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:13:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:13:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:13:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:13:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:13:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:13:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:13:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:13:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:13:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:13:22', 'DoVa_Co2', '0']
['2021-5-4 20:13:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:13:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:13:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:13:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:13:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:14:22', 'fKWhCounter', '3463.52807617188']
['2021-5-4 20:14:22', 'fActPhLevelMixTank1', '5.63585329055786']
['2021-5-4 20:14:22', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 20:14:22', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 20:14:22', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 20:14:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:14:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:14:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:14:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:14:22', 'fActCo2ValMemo', '815']
['2021-5-4 20:14:22', 'fActWaterLevelMixTank1', '287.567993164063']
['2021-5-4 20:14:22', 'fActWaterLevelMixTank2', '291.886810302734']
['2021-5-4 20:14:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:14:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:14:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:14:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:14:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:14:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:14:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:14:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:14:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:14:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:14:22', 'DoVa_Co2', '0']
['2021-5-4 20:14:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:14:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:14:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:14:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:14:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:15:22', 'fKWhCounter', '3463.72827148438']
['2021-5-4 20:15:22', 'fActPhLevelMixTank1', '5.64098024368286']
['2021-5-4 20:15:22', 'fActEcLevelMixTank1', '2030.396484375']
['2021-5-4 20:15:22', 'fActPhLevelMixTank2', '3.81255531311035']
['2021-5-4 20:15:22', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 20:15:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:15:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:15:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:15:22', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 20:15:22', 'fActCo2ValMemo', '811']
['2021-5-4 20:15:22', 'fActWaterLevelMixTank1', '287.404998779297']
['2021-5-4 20:15:22', 'fActWaterLevelMixTank2', '291.642333984375']
['2021-5-4 20:15:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:15:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:15:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:15:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:15:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:15:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:15:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:15:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:15:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:15:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:15:22', 'DoVa_Co2', '0']
['2021-5-4 20:15:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:15:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:15:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:15:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:15:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:16:22', 'fKWhCounter', '3463.82836914063']
['2021-5-4 20:16:22', 'fActPhLevelMixTank1', '5.63463258743286']
['2021-5-4 20:16:22', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 20:16:22', 'fActPhLevelMixTank2', '3.81060218811035']
['2021-5-4 20:16:22', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 20:16:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:16:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:16:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:16:22', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 20:16:22', 'fActCo2ValMemo', '810']
['2021-5-4 20:16:22', 'fActWaterLevelMixTank1', '287.051910400391']
['2021-5-4 20:16:22', 'fActWaterLevelMixTank2', '292.402893066406']
['2021-5-4 20:16:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:16:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:16:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:16:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:16:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:16:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:16:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:16:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:16:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:16:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:16:22', 'DoVa_Co2', '0']
['2021-5-4 20:16:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:16:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:16:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:16:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:16:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:17:22', 'fKWhCounter', '3464.02856445313']
['2021-5-4 20:17:22', 'fActPhLevelMixTank1', '5.64439821243286']
['2021-5-4 20:17:22', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 20:17:22', 'fActPhLevelMixTank2', '3.81719422340393']
['2021-5-4 20:17:22', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 20:17:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:17:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:17:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:17:22', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 20:17:22', 'fActCo2ValMemo', '807']
['2021-5-4 20:17:22', 'fActWaterLevelMixTank1', '288.084075927734']
['2021-5-4 20:17:22', 'fActWaterLevelMixTank2', '292.158416748047']
['2021-5-4 20:17:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:17:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:17:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:17:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:17:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:17:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:17:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:17:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:17:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:17:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:17:22', 'DoVa_Co2', '0']
['2021-5-4 20:17:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:17:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:17:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:17:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_2_Red', '0']

['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:17:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:18:22', 'fKWhCounter', '3464.12866210938']
['2021-5-4 20:18:22', 'fActPhLevelMixTank1', '5.64390993118286']
['2021-5-4 20:18:22', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 20:18:22', 'fActPhLevelMixTank2', '3.81963562965393']
['2021-5-4 20:18:22', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 20:18:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:18:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:18:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:18:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:18:22', 'fActCo2ValMemo', '803']
['2021-5-4 20:18:22', 'fActWaterLevelMixTank1', '287.377838134766']
['2021-5-4 20:18:22', 'fActWaterLevelMixTank2', '292.402893066406']
['2021-5-4 20:18:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:18:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:18:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:18:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:18:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:18:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:18:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:18:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:18:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:18:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:18:22', 'DoVa_Co2', '0']
['2021-5-4 20:18:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:18:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:18:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:18:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:18:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:19:22', 'fKWhCounter', '3464.22875976563']
['2021-5-4 20:19:22', 'fActPhLevelMixTank1', '5.64708375930786']
['2021-5-4 20:19:22', 'fActEcLevelMixTank1', '2031.76977539063']
['2021-5-4 20:19:22', 'fActPhLevelMixTank2', '3.81353187561035']
['2021-5-4 20:19:22', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 20:19:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:19:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:19:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:19:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:19:22', 'fActCo2ValMemo', '804']
['2021-5-4 20:19:22', 'fActWaterLevelMixTank1', '288.084075927734']
['2021-5-4 20:19:22', 'fActWaterLevelMixTank2', '292.375732421875']
['2021-5-4 20:19:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:19:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:19:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:19:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:19:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:19:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:19:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:19:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:19:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:19:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:19:22', 'DoVa_Co2', '0']
['2021-5-4 20:19:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:19:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:19:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:19:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:19:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:20:22', 'fKWhCounter', '3464.42895507813']
['2021-5-4 20:20:22', 'fActPhLevelMixTank1', '5.63975954055786']
['2021-5-4 20:20:22', 'fActEcLevelMixTank1', '2033.14306640625']
['2021-5-4 20:20:22', 'fActPhLevelMixTank2', '3.82012391090393']
['2021-5-4 20:20:22', 'fActEcLevelMixTank2', '1039.765625']
['2021-5-4 20:20:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:20:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:20:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:20:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:20:22', 'fActCo2ValMemo', '805']
['2021-5-4 20:20:22', 'fActWaterLevelMixTank1', '288.735961914063']
['2021-5-4 20:20:22', 'fActWaterLevelMixTank2', '292.946136474609']
['2021-5-4 20:20:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:20:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:20:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:20:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:20:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:20:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:20:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:20:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:20:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:20:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:20:22', 'DoVa_Co2', '0']
['2021-5-4 20:20:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:20:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:20:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:20:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:20:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:21:22', 'fKWhCounter', '3464.52905273438']
['2021-5-4 20:21:22', 'fActPhLevelMixTank1', '5.64635133743286']
['2021-5-4 20:21:22', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 20:21:22', 'fActPhLevelMixTank2', '3.81548500061035']
['2021-5-4 20:21:22', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 20:21:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:21:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:21:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:21:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:21:22', 'fActCo2ValMemo', '806']
['2021-5-4 20:21:22', 'fActWaterLevelMixTank1', '288.219879150391']
['2021-5-4 20:21:22', 'fActWaterLevelMixTank2', '293.027618408203']
['2021-5-4 20:21:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:21:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:21:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:21:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:21:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:21:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:21:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:21:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:21:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:21:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:21:22', 'DoVa_Co2', '0']
['2021-5-4 20:21:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:21:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:21:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:21:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:21:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:22:22', 'fKWhCounter', '3464.72924804688']
['2021-5-4 20:22:22', 'fActPhLevelMixTank1', '5.64098024368286']
['2021-5-4 20:22:22', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 20:22:22', 'fActPhLevelMixTank2', '3.81743836402893']
['2021-5-4 20:22:22', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 20:22:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:22:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:22:22', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 20:22:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:22:22', 'fActCo2ValMemo', '806']
['2021-5-4 20:22:22', 'fActWaterLevelMixTank1', '288.192718505859']
['2021-5-4 20:22:22', 'fActWaterLevelMixTank2', '292.946136474609']
['2021-5-4 20:22:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:22:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:22:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:22:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:22:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:22:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:22:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:22:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:22:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:22:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:22:22', 'DoVa_Co2', '0']
['2021-5-4 20:22:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:22:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:22:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:22:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:22:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:23:22', 'fKWhCounter', '3464.82934570313']
['2021-5-4 20:23:22', 'fActPhLevelMixTank1', '5.64903736114502']
['2021-5-4 20:23:22', 'fActEcLevelMixTank1', '2032.38012695313']
['2021-5-4 20:23:22', 'fActPhLevelMixTank2', '3.81963562965393']
['2021-5-4 20:23:22', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 20:23:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:23:22', 'fTaktCounterLowerLevel', '0']

['2021-5-4 20:23:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:23:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:23:22', 'fActCo2ValMemo', '801']
['2021-5-4 20:23:22', 'fActWaterLevelMixTank1', '288.708801269531']
['2021-5-4 20:23:22', 'fActWaterLevelMixTank2', '293.136260986328']
['2021-5-4 20:23:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:23:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:23:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:23:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:23:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:23:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:23:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:23:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:23:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:23:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:23:22', 'DoVa_Co2', '0']
['2021-5-4 20:23:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:23:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:23:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:23:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:23:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:24:22', 'fKWhCounter', '3465.02954101563']
['2021-5-4 20:24:22', 'fActPhLevelMixTank1', '5.64854907989502']
['2021-5-4 20:24:22', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 20:24:22', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 20:24:22', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 20:24:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:24:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:24:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:24:22', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 20:24:22', 'fActCo2ValMemo', '805']
['2021-5-4 20:24:22', 'fActWaterLevelMixTank1', '288.518676757813']
['2021-5-4 20:24:22', 'fActWaterLevelMixTank2', '293.570861816406']
['2021-5-4 20:24:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:24:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:24:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:24:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:24:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:24:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:24:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:24:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:24:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:24:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:24:22', 'DoVa_Co2', '0']
['2021-5-4 20:24:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:24:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:24:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:24:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:24:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:25:22', 'fKWhCounter', '3465.12963867188']
['2021-5-4 20:25:22', 'fActPhLevelMixTank1', '5.65025806427002']
['2021-5-4 20:25:22', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 20:25:22', 'fActPhLevelMixTank2', '3.82403016090393']
['2021-5-4 20:25:22', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 20:25:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:25:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:25:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:25:22', 'fActRhValMemo', '50.2000007629395']
['2021-5-4 20:25:22', 'fActCo2ValMemo', '803']
['2021-5-4 20:25:22', 'fActWaterLevelMixTank1', '288.029754638672']
['2021-5-4 20:25:22', 'fActWaterLevelMixTank2', '293.842498779297']
['2021-5-4 20:25:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:25:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:25:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:25:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:25:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:25:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:25:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:25:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:25:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:25:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:25:22', 'DoVa_Co2', '0']
['2021-5-4 20:25:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:25:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:25:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:25:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:25:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:26:22', 'fKWhCounter', '3465.22973632813']
['2021-5-4 20:26:22', 'fActPhLevelMixTank1', '5.64757204055786']
['2021-5-4 20:26:22', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 20:26:22', 'fActPhLevelMixTank2', '3.82134461402893']
['2021-5-4 20:26:22', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 20:26:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:26:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:26:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:26:22', 'fActRhValMemo', '50']
['2021-5-4 20:26:22', 'fActCo2ValMemo', '798']
['2021-5-4 20:26:22', 'fActWaterLevelMixTank1', '289.442199707031']
['2021-5-4 20:26:22', 'fActWaterLevelMixTank2', '293.733825683594']
['2021-5-4 20:26:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:26:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:26:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:26:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:26:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:26:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:26:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:26:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:26:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:26:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:26:22', 'DoVa_Co2', '0']
['2021-5-4 20:26:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:26:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:26:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:26:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:26:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:27:22', 'fKWhCounter', '3465.42993164063']
['2021-5-4 20:27:22', 'fActPhLevelMixTank1', '5.65587329864502']
['2021-5-4 20:27:22', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 20:27:22', 'fActPhLevelMixTank2', '3.81743836402893']
['2021-5-4 20:27:22', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 20:27:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:27:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:27:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:27:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:27:22', 'fActCo2ValMemo', '795']
['2021-5-4 20:27:22', 'fActWaterLevelMixTank1', '288.084075927734']
['2021-5-4 20:27:22', 'fActWaterLevelMixTank2', '294.494384765625']
['2021-5-4 20:27:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:27:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:27:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:27:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:27:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:27:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:27:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:27:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:27:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:27:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:27:22', 'DoVa_Co2', '0']
['2021-5-4 20:27:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:27:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:27:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:27:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:27:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:28:22', 'fKWhCounter', '3465.53002929688']
['2021-5-4 20:28:22', 'fActPhLevelMixTank1', '5.65147876739502']
['2021-5-4 20:28:22', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 20:28:22', 'fActPhLevelMixTank2', '3.82329773902893']
['2021-5-4 20:28:22', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 20:28:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:28:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:28:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:28:22', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 20:28:22', 'fActCo2ValMemo', '793']
['2021-5-4 20:28:22', 'fActWaterLevelMixTank1', '289.768127441406']
['2021-5-4 20:28:22', 'fActWaterLevelMixTank2', '294.304260253906']
['2021-5-4 20:28:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:28:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:28:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:28:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:28:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:28:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:28:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:28:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:28:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:28:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:28:22', 'DoVa_Co2', '0']
['2021-5-4 20:28:22', 'DoVa_IrrigateLevel_3_MT1', '0']

['2021-5-4 20:28:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:28:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:28:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:28:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:29:22', 'fKWhCounter', '3465.73022460938']
['2021-5-4 20:29:22', 'fActPhLevelMixTank1', '5.59263896942139']
['2021-5-4 20:29:22', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 20:29:22', 'fActPhLevelMixTank2', '3.73320722579956']
['2021-5-4 20:29:22', 'fActEcLevelMixTank2', '1039.1552734375']
['2021-5-4 20:29:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:29:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:29:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:29:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:29:22', 'fActCo2ValMemo', '793']
['2021-5-4 20:29:22', 'fActWaterLevelMixTank1', '288.192718505859']
['2021-5-4 20:29:22', 'fActWaterLevelMixTank2', '316.495910644531']
['2021-5-4 20:29:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:29:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:29:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:29:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:29:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:29:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:29:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:29:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:29:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:29:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:29:22', 'DoVa_Co2', '0']
['2021-5-4 20:29:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:29:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:29:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:29:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:29:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:30:22', 'fKWhCounter', '3465.93041992188']
['2021-5-4 20:30:22', 'fActPhLevelMixTank1', '5.56187629699707']
['2021-5-4 20:30:22', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 20:30:22', 'fActPhLevelMixTank2', '3.72808003425598']
['2021-5-4 20:30:22', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 20:30:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:30:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:30:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:30:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:30:22', 'fActCo2ValMemo', '794']
['2021-5-4 20:30:22', 'fActWaterLevelMixTank1', '288.844604492188']
['2021-5-4 20:30:22', 'fActWaterLevelMixTank2', '279.799530029297']
['2021-5-4 20:30:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:30:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:30:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:30:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:30:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:30:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:30:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:30:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:30:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:30:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:30:22', 'DoVa_Co2', '0']
['2021-5-4 20:30:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:30:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:30:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:30:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:30:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:31:22', 'fKWhCounter', '3466.03051757813']
['2021-5-4 20:31:22', 'fActPhLevelMixTank1', '5.57335138320923']
['2021-5-4 20:31:22', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 20:31:22', 'fActPhLevelMixTank2', '3.74224066734314']
['2021-5-4 20:31:22', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 20:31:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:31:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:31:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:31:22', 'fActRhValMemo', '51']
['2021-5-4 20:31:22', 'fActCo2ValMemo', '796']
['2021-5-4 20:31:22', 'fActWaterLevelMixTank1', '287.921081542969']
['2021-5-4 20:31:22', 'fActWaterLevelMixTank2', '303.566619873047']
['2021-5-4 20:31:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:31:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:31:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:31:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:31:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:31:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:31:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:31:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:31:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:31:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:31:22', 'DoVa_Co2', '0']
['2021-5-4 20:31:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:31:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:31:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:31:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:31:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:32:22', 'fKWhCounter', '3466.23071289063']
['2021-5-4 20:32:22', 'fActPhLevelMixTank1', '5.56797981262207']
['2021-5-4 20:32:22', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 20:32:22', 'fActPhLevelMixTank2', '3.73760175704956']
['2021-5-4 20:32:22', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 20:32:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:32:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:32:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:32:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:32:22', 'fActCo2ValMemo', '791']
['2021-5-4 20:32:22', 'fActWaterLevelMixTank1', '280.940368652344']
['2021-5-4 20:32:22', 'fActWaterLevelMixTank2', '301.2578125']
['2021-5-4 20:32:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:32:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:32:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:32:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:32:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:32:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:32:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:32:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:32:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:32:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:32:22', 'DoVa_Co2', '0']
['2021-5-4 20:32:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:32:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:32:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:32:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:32:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:33:22', 'fKWhCounter', '3466.43090820313']
['2021-5-4 20:33:22', 'fActPhLevelMixTank1', '5.57628107070923']
['2021-5-4 20:33:22', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 20:33:22', 'fActPhLevelMixTank2', '3.74126410484314']
['2021-5-4 20:33:22', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 20:33:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:33:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:33:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:33:22', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 20:33:22', 'fActCo2ValMemo', '792']
['2021-5-4 20:33:22', 'fActWaterLevelMixTank1', '281.320648193359']
['2021-5-4 20:33:22', 'fActWaterLevelMixTank2', '295.146270751953']
['2021-5-4 20:33:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:33:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:33:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:33:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:33:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:33:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:33:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:33:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:33:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:33:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:33:22', 'DoVa_Co2', '0']
['2021-5-4 20:33:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:33:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:33:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:33:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_1_White', '0']

['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:33:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:34:22', 'fKWhCounter', '3466.53100585938']
['2021-5-4 20:34:22', 'fActPhLevelMixTank1', '5.56993293762207']
['2021-5-4 20:34:22', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 20:34:22', 'fActPhLevelMixTank2', '3.77202677726746']
['2021-5-4 20:34:22', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 20:34:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:34:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:34:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:34:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:34:22', 'fActCo2ValMemo', '790']
['2021-5-4 20:34:22', 'fActWaterLevelMixTank1', '277.762359619141']
['2021-5-4 20:34:22', 'fActWaterLevelMixTank2', '285.938232421875']
['2021-5-4 20:34:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:34:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:34:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:34:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:34:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:34:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:34:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:34:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:34:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:34:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:34:22', 'DoVa_Co2', '0']
['2021-5-4 20:34:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:34:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:34:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:34:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:34:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:35:22', 'fKWhCounter', '3466.73120117188']
['2021-5-4 20:35:22', 'fActPhLevelMixTank1', '5.57823419570923']
['2021-5-4 20:35:22', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 20:35:22', 'fActPhLevelMixTank2', '3.78960537910461']
['2021-5-4 20:35:22', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 20:35:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:35:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:35:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:35:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:35:22', 'fActCo2ValMemo', '793']
['2021-5-4 20:35:22', 'fActWaterLevelMixTank1', '277.708038330078']
['2021-5-4 20:35:22', 'fActWaterLevelMixTank2', '285.992553710938']
['2021-5-4 20:35:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:35:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:35:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:35:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:35:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:35:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:35:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:35:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:35:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:35:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:35:22', 'DoVa_Co2', '0']
['2021-5-4 20:35:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:35:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:35:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:35:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:35:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:36:22', 'fKWhCounter', '3466.83129882813']
['2021-5-4 20:36:22', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 20:36:22', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 20:36:22', 'fActPhLevelMixTank2', '3.79277920722961']
['2021-5-4 20:36:22', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 20:36:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:36:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:36:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:36:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:36:22', 'fActCo2ValMemo', '793']
['2021-5-4 20:36:22', 'fActWaterLevelMixTank1', '275.888153076172']
['2021-5-4 20:36:22', 'fActWaterLevelMixTank2', '285.639465332031']
['2021-5-4 20:36:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:36:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:36:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:36:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:36:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:36:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:36:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:36:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:36:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:36:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:36:22', 'DoVa_Co2', '0']
['2021-5-4 20:36:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:36:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:36:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:36:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:36:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:37:22', 'fKWhCounter', '3467.03149414063']
['2021-5-4 20:37:22', 'fActPhLevelMixTank1', '5.58604717254639']
['2021-5-4 20:37:22', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 20:37:22', 'fActPhLevelMixTank2', '3.79180264472961']
['2021-5-4 20:37:22', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 20:37:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:37:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:37:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:37:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:37:22', 'fActCo2ValMemo', '787']
['2021-5-4 20:37:22', 'fActWaterLevelMixTank1', '277.300598144531']
['2021-5-4 20:37:22', 'fActWaterLevelMixTank2', '285.557952880859']
['2021-5-4 20:37:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:37:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:37:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:37:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:37:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:37:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:37:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:37:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:37:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:37:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:37:22', 'DoVa_Co2', '0']
['2021-5-4 20:37:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:37:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:37:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:37:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:37:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:38:22', 'fKWhCounter', '3467.13159179688']
['2021-5-4 20:38:22', 'fActPhLevelMixTank1', '5.58091974258423']
['2021-5-4 20:38:22', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 20:38:22', 'fActPhLevelMixTank2', '3.78350162506104']
['2021-5-4 20:38:22', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 20:38:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:38:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:38:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:38:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:38:22', 'fActCo2ValMemo', '786']
['2021-5-4 20:38:22', 'fActWaterLevelMixTank1', '277.137634277344']
['2021-5-4 20:38:22', 'fActWaterLevelMixTank2', '285.693786621094']
['2021-5-4 20:38:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:38:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:38:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:38:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:38:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:38:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:38:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:38:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:38:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:38:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:38:22', 'DoVa_Co2', '0']
['2021-5-4 20:38:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:38:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:38:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:38:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_1_Blue', '0']

['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:38:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:39:22', 'fKWhCounter', '3467.33178710938']
['2021-5-4 20:39:22', 'fActPhLevelMixTank1', '5.58384943008423']
['2021-5-4 20:39:22', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 20:39:22', 'fActPhLevelMixTank2', '3.78691983222961']
['2021-5-4 20:39:22', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 20:39:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:39:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:39:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:39:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:39:22', 'fActCo2ValMemo', '789']
['2021-5-4 20:39:22', 'fActWaterLevelMixTank1', '276.838836669922']
['2021-5-4 20:39:22', 'fActWaterLevelMixTank2', '285.476470947266']
['2021-5-4 20:39:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:39:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:39:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:39:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:39:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:39:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:39:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:39:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:39:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:39:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:39:22', 'DoVa_Co2', '0']
['2021-5-4 20:39:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:39:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:39:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:39:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:39:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:40:22', 'fKWhCounter', '3467.43188476563']
['2021-5-4 20:40:22', 'fActPhLevelMixTank1', '5.57921075820923']
['2021-5-4 20:40:22', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 20:40:22', 'fActPhLevelMixTank2', '3.78423404693604']
['2021-5-4 20:40:22', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 20:40:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:40:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:40:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:40:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:40:22', 'fActCo2ValMemo', '788']
['2021-5-4 20:40:22', 'fActWaterLevelMixTank1', '276.349914550781']
['2021-5-4 20:40:22', 'fActWaterLevelMixTank2', '285.557952880859']
['2021-5-4 20:40:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:40:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:40:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:40:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:40:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:40:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:40:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:40:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:40:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:40:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:40:22', 'DoVa_Co2', '0']
['2021-5-4 20:40:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:40:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:40:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:40:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:40:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:41:22', 'fKWhCounter', '3467.53198242188']
['2021-5-4 20:41:22', 'fActPhLevelMixTank1', '5.58238458633423']
['2021-5-4 20:41:22', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 20:41:22', 'fActPhLevelMixTank2', '3.77935123443604']
['2021-5-4 20:41:22', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 20:41:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:41:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:41:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:41:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:41:22', 'fActCo2ValMemo', '786']
['2021-5-4 20:41:22', 'fActWaterLevelMixTank1', '276.865997314453']
['2021-5-4 20:41:22', 'fActWaterLevelMixTank2', '286.074066162109']
['2021-5-4 20:41:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:41:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:41:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:41:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:41:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:41:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:41:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:41:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:41:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:41:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:41:22', 'DoVa_Co2', '0']
['2021-5-4 20:41:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:41:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:41:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:41:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:41:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:42:22', 'fKWhCounter', '3467.73217773438']
['2021-5-4 20:42:22', 'fActPhLevelMixTank1', '5.57847833633423']
['2021-5-4 20:42:22', 'fActEcLevelMixTank1', '2023.07202148438']
['2021-5-4 20:42:22', 'fActPhLevelMixTank2', '3.78350162506104']
['2021-5-4 20:42:22', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 20:42:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:42:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:42:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:42:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:42:22', 'fActCo2ValMemo', '782']
['2021-5-4 20:42:22', 'fActWaterLevelMixTank1', '277.083312988281']
['2021-5-4 20:42:22', 'fActWaterLevelMixTank2', '285.938232421875']
['2021-5-4 20:42:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:42:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:42:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:42:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:42:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:42:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:42:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:42:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:42:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:42:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:42:22', 'DoVa_Co2', '0']
['2021-5-4 20:42:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:42:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:42:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:42:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:42:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:43:22', 'fKWhCounter', '3467.83227539063']
['2021-5-4 20:43:22', 'fActPhLevelMixTank1', '5.58702373504639']
['2021-5-4 20:43:22', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 20:43:22', 'fActPhLevelMixTank2', '3.77959537506104']
['2021-5-4 20:43:22', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 20:43:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:43:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:43:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 20:43:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:43:22', 'fActCo2ValMemo', '782']
['2021-5-4 20:43:22', 'fActWaterLevelMixTank1', '278.332763671875']
['2021-5-4 20:43:22', 'fActWaterLevelMixTank2', '286.318511962891']
['2021-5-4 20:43:22', 'DoPu_AddAcidMixTank_1', '0']

['2021-5-4 20:43:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:43:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:43:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:43:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:43:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:43:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:43:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:43:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:43:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:43:22', 'DoVa_Co2', '0']
['2021-5-4 20:43:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:43:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:43:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:43:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:43:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:44:22', 'fKWhCounter', '3468.03247070313']
['2021-5-4 20:44:22', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 20:44:22', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 20:44:22', 'fActPhLevelMixTank2', '3.77593302726746']
['2021-5-4 20:44:22', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 20:44:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:44:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:44:22', 'fActTempValMemo', '21']
['2021-5-4 20:44:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:44:22', 'fActCo2ValMemo', '782']
['2021-5-4 20:44:22', 'fActWaterLevelMixTank1', '279.229125976563']
['2021-5-4 20:44:22', 'fActWaterLevelMixTank2', '286.698791503906']
['2021-5-4 20:44:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:44:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:44:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:44:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:44:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:44:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:44:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:44:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:44:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:44:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:44:22', 'DoVa_Co2', '0']
['2021-5-4 20:44:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:44:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:44:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:44:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:44:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:45:22', 'fKWhCounter', '3468.13256835938']
['2021-5-4 20:45:22', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 20:45:22', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 20:45:22', 'fActPhLevelMixTank2', '3.77886295318604']
['2021-5-4 20:45:22', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 20:45:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:45:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:45:22', 'fActTempValMemo', '21']
['2021-5-4 20:45:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:45:22', 'fActCo2ValMemo', '781']
['2021-5-4 20:45:22', 'fActWaterLevelMixTank1', '279.989685058594']
['2021-5-4 20:45:22', 'fActWaterLevelMixTank2', '287.459320068359']
['2021-5-4 20:45:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:45:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:45:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:45:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:45:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:45:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:45:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:45:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:45:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:45:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:45:22', 'DoVa_Co2', '0']
['2021-5-4 20:45:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:45:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:45:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:45:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:45:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:46:22', 'fKWhCounter', '3468.33276367188']
['2021-5-4 20:46:22', 'fActPhLevelMixTank1', '5.57457208633423']
['2021-5-4 20:46:22', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 20:46:22', 'fActPhLevelMixTank2', '3.77959537506104']
['2021-5-4 20:46:22', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 20:46:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:46:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:46:22', 'fActTempValMemo', '21']
['2021-5-4 20:46:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:46:22', 'fActCo2ValMemo', '780']
['2021-5-4 20:46:22', 'fActWaterLevelMixTank1', '279.989685058594']
['2021-5-4 20:46:22', 'fActWaterLevelMixTank2', '287.024719238281']
['2021-5-4 20:46:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:46:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:46:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:46:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:46:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:46:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:46:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:46:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:46:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:46:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:46:22', 'DoVa_Co2', '0']
['2021-5-4 20:46:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:46:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:46:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:46:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:46:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:47:22', 'fKWhCounter', '3468.43286132813']
['2021-5-4 20:47:22', 'fActPhLevelMixTank1', '5.58409357070923']
['2021-5-4 20:47:22', 'fActEcLevelMixTank1', '2016.35791015625']
['2021-5-4 20:47:22', 'fActPhLevelMixTank2', '3.77666544914246']
['2021-5-4 20:47:22', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 20:47:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:47:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:47:22', 'fActTempValMemo', '21']
['2021-5-4 20:47:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:47:22', 'fActCo2ValMemo', '777']
['2021-5-4 20:47:22', 'fActWaterLevelMixTank1', '279.745208740234']
['2021-5-4 20:47:22', 'fActWaterLevelMixTank2', '287.323516845703']
['2021-5-4 20:47:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:47:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:47:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:47:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:47:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:47:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:47:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:47:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:47:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:47:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:47:22', 'DoVa_Co2', '0']
['2021-5-4 20:47:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:47:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:47:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:47:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:47:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:48:22', 'fKWhCounter', '3468.53295898438']
['2021-5-4 20:48:22', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 20:48:22', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 20:48:22', 'fActPhLevelMixTank2', '3.78301334381104']
['2021-5-4 20:48:22', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 20:48:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:48:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:48:22', 'fActTempValMemo', '21']
['2021-5-4 20:48:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:48:22', 'fActCo2ValMemo', '778']
['2021-5-4 20:48:22', 'fActWaterLevelMixTank1', '280.478607177734']
['2021-5-4 20:48:22', 'fActWaterLevelMixTank2', '287.540832519531']
['2021-5-4 20:48:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:48:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:48:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:48:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:48:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:48:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:48:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:48:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:48:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:48:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:48:22', 'DoVa_Co2', '0']
['2021-5-4 20:48:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:48:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:48:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:48:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_2_White', '0']

['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:48:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:49:22', 'fKWhCounter', '3468.73315429688']
['2021-5-4 20:49:22', 'fActPhLevelMixTank1', '5.58946514129639']
['2021-5-4 20:49:22', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 20:49:22', 'fActPhLevelMixTank2', '3.77886295318604']
['2021-5-4 20:49:22', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 20:49:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:49:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:49:22', 'fActTempValMemo', '21']
['2021-5-4 20:49:22', 'fActRhValMemo', '50.5']
['2021-5-4 20:49:22', 'fActCo2ValMemo', '778']
['2021-5-4 20:49:22', 'fActWaterLevelMixTank1', '280.723052978516']
['2021-5-4 20:49:22', 'fActWaterLevelMixTank2', '287.893920898438']
['2021-5-4 20:49:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:49:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:49:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:49:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:49:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:49:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:49:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:49:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:49:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:49:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:49:22', 'DoVa_Co2', '0']
['2021-5-4 20:49:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:49:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:49:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:49:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:49:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:50:22', 'fKWhCounter', '3468.83325195313']
['2021-5-4 20:50:22', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 20:50:22', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 20:50:22', 'fActPhLevelMixTank2', '3.78203678131104']
['2021-5-4 20:50:22', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 20:50:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:50:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:50:22', 'fActTempValMemo', '21']
['2021-5-4 20:50:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:50:22', 'fActCo2ValMemo', '776']
['2021-5-4 20:50:22', 'fActWaterLevelMixTank1', '281.157653808594']
['2021-5-4 20:50:22', 'fActWaterLevelMixTank2', '287.9482421875']
['2021-5-4 20:50:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:50:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:50:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:50:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:50:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:50:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:50:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:50:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:50:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:50:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:50:22', 'DoVa_Co2', '0']
['2021-5-4 20:50:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:50:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:50:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:50:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:50:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:51:22', 'fKWhCounter', '3469.03344726563']
['2021-5-4 20:51:22', 'fActPhLevelMixTank1', '5.59141826629639']
['2021-5-4 20:51:22', 'fActEcLevelMixTank1', '2023.224609375']
['2021-5-4 20:51:22', 'fActPhLevelMixTank2', '3.79058194160461']
['2021-5-4 20:51:22', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 20:51:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:51:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:51:22', 'fActTempValMemo', '21']
['2021-5-4 20:51:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:51:22', 'fActCo2ValMemo', '777']
['2021-5-4 20:51:22', 'fActWaterLevelMixTank1', '281.266326904297']
['2021-5-4 20:51:22', 'fActWaterLevelMixTank2', '288.301361083984']
['2021-5-4 20:51:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:51:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:51:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:51:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:51:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:51:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:51:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:51:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:51:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:51:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:51:22', 'DoVa_Co2', '0']
['2021-5-4 20:51:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:51:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:51:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:51:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:51:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:52:22', 'fKWhCounter', '3469.13354492188']
['2021-5-4 20:52:22', 'fActPhLevelMixTank1', '5.59678936004639']
['2021-5-4 20:52:22', 'fActEcLevelMixTank1', '2024.14013671875']
['2021-5-4 20:52:22', 'fActPhLevelMixTank2', '3.78887295722961']
['2021-5-4 20:52:22', 'fActEcLevelMixTank2', '1029.54187011719']
['2021-5-4 20:52:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:52:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:52:22', 'fActTempValMemo', '21']
['2021-5-4 20:52:22', 'fActRhValMemo', '51']
['2021-5-4 20:52:22', 'fActCo2ValMemo', '778']
['2021-5-4 20:52:22', 'fActWaterLevelMixTank1', '281.782409667969']
['2021-5-4 20:52:22', 'fActWaterLevelMixTank2', '288.735961914063']
['2021-5-4 20:52:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:52:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:52:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:52:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:52:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:52:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:52:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:52:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:52:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:52:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:52:22', 'DoVa_Co2', '0']
['2021-5-4 20:52:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:52:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:52:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:52:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:52:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:53:22', 'fKWhCounter', '3469.33374023438']
['2021-5-4 20:53:22', 'fActPhLevelMixTank1', '5.60020732879639']
['2021-5-4 20:53:22', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 20:53:22', 'fActPhLevelMixTank2', '3.78789639472961']
['2021-5-4 20:53:22', 'fActEcLevelMixTank2', '1029.08410644531']
['2021-5-4 20:53:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:53:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:53:22', 'fActTempValMemo', '21']
['2021-5-4 20:53:22', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 20:53:22', 'fActCo2ValMemo', '777']
['2021-5-4 20:53:22', 'fActWaterLevelMixTank1', '282.244171142578']
['2021-5-4 20:53:22', 'fActWaterLevelMixTank2', '289.007598876953']
['2021-5-4 20:53:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:53:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:53:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:53:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:53:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:53:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:53:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:53:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:53:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:53:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:53:22', 'DoVa_Co2', '0']
['2021-5-4 20:53:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:53:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:53:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:53:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']

['2021-5-4 20:53:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:53:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:54:22', 'fKWhCounter', '3469.43383789063']
['2021-5-4 20:54:22', 'fActPhLevelMixTank1', '5.59727764129639']
['2021-5-4 20:54:22', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 20:54:22', 'fActPhLevelMixTank2', '3.79253506660461']
['2021-5-4 20:54:22', 'fActEcLevelMixTank2', '1029.84704589844']
['2021-5-4 20:54:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:54:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:54:22', 'fActTempValMemo', '21']
['2021-5-4 20:54:22', 'fActRhValMemo', '51']
['2021-5-4 20:54:22', 'fActCo2ValMemo', '776']
['2021-5-4 20:54:22', 'fActWaterLevelMixTank1', '282.054016113281']
['2021-5-4 20:54:22', 'fActWaterLevelMixTank2', '289.007598876953']
['2021-5-4 20:54:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:54:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:54:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:54:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:54:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:54:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:54:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:54:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:54:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:54:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:54:22', 'DoVa_Co2', '0']
['2021-5-4 20:54:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:54:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:54:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:54:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:54:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:55:22', 'fKWhCounter', '3469.63403320313']
['2021-5-4 20:55:22', 'fActPhLevelMixTank1', '5.60045146942139']
['2021-5-4 20:55:22', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 20:55:22', 'fActPhLevelMixTank2', '3.78838467597961']
['2021-5-4 20:55:22', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 20:55:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:55:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:55:22', 'fActTempValMemo', '21']
['2021-5-4 20:55:22', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 20:55:22', 'fActCo2ValMemo', '778']
['2021-5-4 20:55:22', 'fActWaterLevelMixTank1', '282.814575195313']
['2021-5-4 20:55:22', 'fActWaterLevelMixTank2', '289.252044677734']
['2021-5-4 20:55:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:55:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:55:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:55:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:55:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:55:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:55:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:55:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:55:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:55:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:55:22', 'DoVa_Co2', '0']
['2021-5-4 20:55:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:55:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:55:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:55:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:55:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:56:22', 'fKWhCounter', '3469.73413085938']
['2021-5-4 20:56:22', 'fActPhLevelMixTank1', '5.59776592254639']
['2021-5-4 20:56:22', 'fActEcLevelMixTank1', '2020.63049316406']
['2021-5-4 20:56:22', 'fActPhLevelMixTank2', '3.79497671127319']
['2021-5-4 20:56:22', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 20:56:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:56:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:56:22', 'fActTempValMemo', '21']
['2021-5-4 20:56:22', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 20:56:22', 'fActCo2ValMemo', '778']
['2021-5-4 20:56:22', 'fActWaterLevelMixTank1', '281.619415283203']
['2021-5-4 20:56:22', 'fActWaterLevelMixTank2', '289.143402099609']
['2021-5-4 20:56:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:56:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:56:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:56:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:56:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:56:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:56:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:56:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:56:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:56:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:56:22', 'DoVa_Co2', '0']
['2021-5-4 20:56:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:56:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:56:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:56:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:56:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:57:22', 'fKWhCounter', '3469.83422851563']
['2021-5-4 20:57:22', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 20:57:22', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 20:57:22', 'fActPhLevelMixTank2', '3.80010366439819']
['2021-5-4 20:57:22', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 20:57:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:57:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:57:22', 'fActTempValMemo', '21']
['2021-5-4 20:57:22', 'fActRhValMemo', '51']
['2021-5-4 20:57:22', 'fActCo2ValMemo', '780']
['2021-5-4 20:57:22', 'fActWaterLevelMixTank1', '283.140502929688']
['2021-5-4 20:57:22', 'fActWaterLevelMixTank2', '289.550842285156']
['2021-5-4 20:57:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:57:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:57:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:57:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:57:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:57:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:57:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:57:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:57:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:57:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:57:22', 'DoVa_Co2', '0']
['2021-5-4 20:57:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:57:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:57:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:57:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:57:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 20:58:22', 'fKWhCounter', '3470.03442382813']
['2021-5-4 20:58:22', 'fActPhLevelMixTank1', '5.59971904754639']
['2021-5-4 20:58:22', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 20:58:22', 'fActPhLevelMixTank2', '3.79692983627319']
['2021-5-4 20:58:22', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 20:58:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:58:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:58:22', 'fActTempValMemo', '21']
['2021-5-4 20:58:22', 'fActRhValMemo', '51']
['2021-5-4 20:58:22', 'fActCo2ValMemo', '779']
['2021-5-4 20:58:22', 'fActWaterLevelMixTank1', '283.520782470703']
['2021-5-4 20:58:22', 'fActWaterLevelMixTank2', '289.659484863281']
['2021-5-4 20:58:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:58:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:58:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:58:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:58:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:58:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:58:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:58:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:58:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:58:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:58:22', 'DoVa_Co2', '0']
['2021-5-4 20:58:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:58:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:58:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:58:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:58:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']

['2021-5-4 20:59:22', 'fKWhCounter', '3470.13452148438']
['2021-5-4 20:59:22', 'fActPhLevelMixTank1', '5.60679960250854']
['2021-5-4 20:59:22', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 20:59:22', 'fActPhLevelMixTank2', '3.80205702781677']
['2021-5-4 20:59:22', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 20:59:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 20:59:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 20:59:22', 'fActTempValMemo', '21']
['2021-5-4 20:59:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 20:59:22', 'fActCo2ValMemo', '778']
['2021-5-4 20:59:22', 'fActWaterLevelMixTank1', '282.678741455078']
['2021-5-4 20:59:22', 'fActWaterLevelMixTank2', '289.578002929688']
['2021-5-4 20:59:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 20:59:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 20:59:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 20:59:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 20:59:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 20:59:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 20:59:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 20:59:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 20:59:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 20:59:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 20:59:22', 'DoVa_Co2', '0']
['2021-5-4 20:59:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 20:59:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 20:59:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 20:59:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 20:59:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:0:22', 'fKWhCounter', '3470.33471679688']
['2021-5-4 21:0:22', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 21:0:22', 'fActEcLevelMixTank1', '2018.18908691406']
['2021-5-4 21:0:22', 'fActPhLevelMixTank2', '3.80254530906677']
['2021-5-4 21:0:22', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 21:0:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:0:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:0:22', 'fActTempValMemo', '21']
['2021-5-4 21:0:22', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 21:0:22', 'fActCo2ValMemo', '775']
['2021-5-4 21:0:22', 'fActWaterLevelMixTank1', '282.271331787109']
['2021-5-4 21:0:22', 'fActWaterLevelMixTank2', '289.442199707031']
['2021-5-4 21:0:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:0:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:0:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:0:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:0:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:0:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:0:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:0:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:0:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:0:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:0:22', 'DoVa_Co2', '0']
['2021-5-4 21:0:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:0:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:0:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:0:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:0:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:1:22', 'fKWhCounter', '3470.43481445313']
['2021-5-4 21:1:22', 'fActPhLevelMixTank1', '5.60582304000854']
['2021-5-4 21:1:22', 'fActEcLevelMixTank1', '2018.49426269531']
['2021-5-4 21:1:22', 'fActPhLevelMixTank2', '3.79912710189819']
['2021-5-4 21:1:22', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 21:1:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:1:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:1:22', 'fActTempValMemo', '21']
['2021-5-4 21:1:22', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 21:1:22', 'fActCo2ValMemo', '773']
['2021-5-4 21:1:22', 'fActWaterLevelMixTank1', '284.389984130859']
['2021-5-4 21:1:22', 'fActWaterLevelMixTank2', '290.148406982422']
['2021-5-4 21:1:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:1:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:1:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:1:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:1:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:1:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:1:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:1:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:1:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:1:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:1:22', 'DoVa_Co2', '0']
['2021-5-4 21:1:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:1:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:1:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:1:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:1:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:2:22', 'fKWhCounter', '3470.63500976563']
['2021-5-4 21:2:22', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 21:2:22', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 21:2:22', 'fActPhLevelMixTank2', '3.80523085594177']
['2021-5-4 21:2:22', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 21:2:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:2:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:2:22', 'fActTempValMemo', '21']
['2021-5-4 21:2:22', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 21:2:22', 'fActCo2ValMemo', '774']
['2021-5-4 21:2:22', 'fActWaterLevelMixTank1', '284.444305419922']
['2021-5-4 21:2:22', 'fActWaterLevelMixTank2', '290.392852783203']
['2021-5-4 21:2:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:2:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:2:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:2:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:2:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:2:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:2:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:2:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:2:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:2:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:2:22', 'DoVa_Co2', '0']
['2021-5-4 21:2:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:2:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:2:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:2:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:2:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:3:22', 'fKWhCounter', '3470.73510742188']
['2021-5-4 21:3:22', 'fActPhLevelMixTank1', '5.60533475875854']
['2021-5-4 21:3:22', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 21:3:22', 'fActPhLevelMixTank2', '3.80425429344177']
['2021-5-4 21:3:22', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 21:3:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:3:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:3:22', 'fActTempValMemo', '21']
['2021-5-4 21:3:22', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 21:3:22', 'fActCo2ValMemo', '771']
['2021-5-4 21:3:22', 'fActWaterLevelMixTank1', '284.281341552734']
['2021-5-4 21:3:22', 'fActWaterLevelMixTank2', '291.017608642578']
['2021-5-4 21:3:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:3:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:3:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:3:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:3:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:3:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:3:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:3:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:3:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:3:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:3:22', 'DoVa_Co2', '0']
['2021-5-4 21:3:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:3:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:3:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:3:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_4_Fred', '0']

['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:3:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:4:22', 'fKWhCounter', '3470.83520507813']
['2021-5-4 21:4:22', 'fActPhLevelMixTank1', '5.60802030563354']
['2021-5-4 21:4:22', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 21:4:22', 'fActPhLevelMixTank2', '3.79863882064819']
['2021-5-4 21:4:22', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 21:4:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:4:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:4:22', 'fActTempValMemo', '21']
['2021-5-4 21:4:22', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 21:4:22', 'fActCo2ValMemo', '768']
['2021-5-4 21:4:22', 'fActWaterLevelMixTank1', '284.118347167969']
['2021-5-4 21:4:22', 'fActWaterLevelMixTank2', '290.637329101563']
['2021-5-4 21:4:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:4:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:4:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:4:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:4:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:4:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:4:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:4:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:4:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:4:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:4:22', 'DoVa_Co2', '0']
['2021-5-4 21:4:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:4:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:4:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:4:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:4:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:5:22', 'fKWhCounter', '3471.03540039063']
['2021-5-4 21:5:22', 'fActPhLevelMixTank1', '5.60826444625854']
['2021-5-4 21:5:22', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 21:5:22', 'fActPhLevelMixTank2', '3.80669569969177']
['2021-5-4 21:5:22', 'fActEcLevelMixTank2', '1033.05151367188']
['2021-5-4 21:5:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:5:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:5:22', 'fActTempValMemo', '21']
['2021-5-4 21:5:22', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 21:5:22', 'fActCo2ValMemo', '768']
['2021-5-4 21:5:22', 'fActWaterLevelMixTank1', '284.851745605469']
['2021-5-4 21:5:22', 'fActWaterLevelMixTank2', '290.936126708984']
['2021-5-4 21:5:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:5:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:5:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:5:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:5:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:5:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:5:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:5:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:5:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:5:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:5:22', 'DoVa_Co2', '0']
['2021-5-4 21:5:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:5:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:5:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:5:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:5:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:6:22', 'fKWhCounter', '3471.13549804688']
['2021-5-4 21:6:22', 'fActPhLevelMixTank1', '5.60411405563354']
['2021-5-4 21:6:22', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 21:6:22', 'fActPhLevelMixTank2', '3.80425429344177']
['2021-5-4 21:6:22', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 21:6:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:6:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:6:22', 'fActTempValMemo', '21']
['2021-5-4 21:6:22', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 21:6:22', 'fActCo2ValMemo', '767']
['2021-5-4 21:6:22', 'fActWaterLevelMixTank1', '285.313507080078']
['2021-5-4 21:6:22', 'fActWaterLevelMixTank2', '291.696655273438']
['2021-5-4 21:6:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:6:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:6:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:6:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:6:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:6:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:6:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:6:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:6:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:6:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:6:22', 'DoVa_Co2', '0']
['2021-5-4 21:6:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:6:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:6:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:6:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:6:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:7:22', 'fKWhCounter', '3471.33569335938']
['2021-5-4 21:7:22', 'fActPhLevelMixTank1', '5.60020732879639']
['2021-5-4 21:7:22', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 21:7:22', 'fActPhLevelMixTank2', '3.80156874656677']
['2021-5-4 21:7:22', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 21:7:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:7:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:7:22', 'fActTempValMemo', '21']
['2021-5-4 21:7:22', 'fActRhValMemo', '51']
['2021-5-4 21:7:22', 'fActCo2ValMemo', '767']
['2021-5-4 21:7:22', 'fActWaterLevelMixTank1', '286.101226806641']
['2021-5-4 21:7:22', 'fActWaterLevelMixTank2', '292.538696289063']
['2021-5-4 21:7:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:7:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:7:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:7:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:7:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:7:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:7:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:7:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:7:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:7:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:7:22', 'DoVa_Co2', '0']
['2021-5-4 21:7:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:7:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:7:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:7:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:7:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:8:22', 'fKWhCounter', '3471.43579101563']
['2021-5-4 21:8:22', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 21:8:22', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 21:8:22', 'fActPhLevelMixTank2', '3.80816054344177']
['2021-5-4 21:8:22', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 21:8:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:8:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:8:22', 'fActTempValMemo', '21']
['2021-5-4 21:8:22', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 21:8:22', 'fActCo2ValMemo', '768']
['2021-5-4 21:8:22', 'fActWaterLevelMixTank1', '285.6123046875']
['2021-5-4 21:8:22', 'fActWaterLevelMixTank2', '291.425048828125']
['2021-5-4 21:8:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:8:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:8:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:8:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:8:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:8:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:8:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:8:22', 'DoVa_IrrigateLevel_2_MT1', '0']

['2021-5-4 21:8:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:8:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:8:22', 'DoVa_Co2', '0']
['2021-5-4 21:8:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:8:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:8:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:8:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:8:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:9:22', 'fKWhCounter', '3471.63598632813']
['2021-5-4 21:9:22', 'fActPhLevelMixTank1', '5.60533475875854']
['2021-5-4 21:9:22', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 21:9:22', 'fActPhLevelMixTank2', '3.80767226219177']
['2021-5-4 21:9:22', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 21:9:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:9:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:9:22', 'fActTempValMemo', '21']
['2021-5-4 21:9:22', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 21:9:22', 'fActCo2ValMemo', '765']
['2021-5-4 21:9:22', 'fActWaterLevelMixTank1', '286.046875']
['2021-5-4 21:9:22', 'fActWaterLevelMixTank2', '292.267059326172']
['2021-5-4 21:9:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:9:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:9:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:9:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:9:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:9:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:9:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:9:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:9:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:9:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:9:22', 'DoVa_Co2', '0']
['2021-5-4 21:9:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:9:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:9:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:9:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:9:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:10:22', 'fKWhCounter', '3471.73608398438']
['2021-5-4 21:10:22', 'fActPhLevelMixTank1', '5.60924100875854']
['2021-5-4 21:10:22', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 21:10:22', 'fActPhLevelMixTank2', '3.80303359031677']
['2021-5-4 21:10:22', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 21:10:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:10:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:10:22', 'fActTempValMemo', '21']
['2021-5-4 21:10:22', 'fActRhValMemo', '51']
['2021-5-4 21:10:22', 'fActCo2ValMemo', '763']
['2021-5-4 21:10:22', 'fActWaterLevelMixTank1', '286.671630859375']
['2021-5-4 21:10:22', 'fActWaterLevelMixTank2', '292.593017578125']
['2021-5-4 21:10:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:10:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:10:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:10:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:10:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:10:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:10:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:10:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:10:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:10:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:10:22', 'DoVa_Co2', '0']
['2021-5-4 21:10:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:10:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:10:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:10:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:10:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:11:22', 'fKWhCounter', '3471.93627929688']
['2021-5-4 21:11:22', 'fActPhLevelMixTank1', '5.60484647750854']
['2021-5-4 21:11:22', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 21:11:22', 'fActPhLevelMixTank2', '3.80254530906677']
['2021-5-4 21:11:22', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 21:11:22', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:11:22', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:11:22', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:11:22', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 21:11:22', 'fActCo2ValMemo', '763']
['2021-5-4 21:11:22', 'fActWaterLevelMixTank1', '285.422149658203']
['2021-5-4 21:11:22', 'fActWaterLevelMixTank2', '292.810333251953']
['2021-5-4 21:11:22', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:11:22', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:11:22', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:11:22', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:11:22', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:11:22', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:11:22', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:11:22', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:11:22', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:11:22', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:11:22', 'DoVa_Co2', '0']
['2021-5-4 21:11:22', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:11:22', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:11:22', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:11:22', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:11:22', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:12:23', 'fKWhCounter', '3472.03637695313']
['2021-5-4 21:12:23', 'fActPhLevelMixTank1', '5.60875272750854']
['2021-5-4 21:12:23', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 21:12:23', 'fActPhLevelMixTank2', '3.80791640281677']
['2021-5-4 21:12:23', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 21:12:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:12:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:12:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:12:23', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 21:12:23', 'fActCo2ValMemo', '762']
['2021-5-4 21:12:23', 'fActWaterLevelMixTank1', '286.454315185547']
['2021-5-4 21:12:23', 'fActWaterLevelMixTank2', '292.946136474609']
['2021-5-4 21:12:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:12:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:12:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:12:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:12:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:12:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:12:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:12:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:12:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:12:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:12:23', 'DoVa_Co2', '0']
['2021-5-4 21:12:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:12:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:12:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:12:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_3_White', '0']

['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:12:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:13:23', 'fKWhCounter', '3472.13647460938']
['2021-5-4 21:13:23', 'fActPhLevelMixTank1', '5.60631132125854']
['2021-5-4 21:13:23', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 21:13:23', 'fActPhLevelMixTank2', '3.80523085594177']
['2021-5-4 21:13:23', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 21:13:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:13:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:13:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:13:23', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 21:13:23', 'fActCo2ValMemo', '757']
['2021-5-4 21:13:23', 'fActWaterLevelMixTank1', '287.187713623047']
['2021-5-4 21:13:23', 'fActWaterLevelMixTank2', '293.543701171875']
['2021-5-4 21:13:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:13:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:13:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:13:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:13:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:13:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:13:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:13:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:13:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:13:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:13:23', 'DoVa_Co2', '0']
['2021-5-4 21:13:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:13:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:13:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:13:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:13:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:14:23', 'fKWhCounter', '3472.33666992188']
['2021-5-4 21:14:23', 'fActPhLevelMixTank1', '5.61412382125854']
['2021-5-4 21:14:23', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 21:14:23', 'fActPhLevelMixTank2', '3.80620741844177']
['2021-5-4 21:14:23', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 21:14:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:14:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:14:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:14:23', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 21:14:23', 'fActCo2ValMemo', '757']
['2021-5-4 21:14:23', 'fActWaterLevelMixTank1', '287.187713623047']
['2021-5-4 21:14:23', 'fActWaterLevelMixTank2', '293.353576660156']
['2021-5-4 21:14:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:14:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:14:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:14:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:14:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:14:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:14:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:14:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:14:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:14:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:14:23', 'DoVa_Co2', '0']
['2021-5-4 21:14:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:14:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:14:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:14:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:14:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:15:23', 'fKWhCounter', '3472.43676757813']
['2021-5-4 21:15:23', 'fActPhLevelMixTank1', '5.61217069625854']
['2021-5-4 21:15:23', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 21:15:23', 'fActPhLevelMixTank2', '3.80913734436035']
['2021-5-4 21:15:23', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 21:15:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:15:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:15:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:15:23', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 21:15:23', 'fActCo2ValMemo', '756']
['2021-5-4 21:15:23', 'fActWaterLevelMixTank1', '286.99755859375']
['2021-5-4 21:15:23', 'fActWaterLevelMixTank2', '293.760986328125']
['2021-5-4 21:15:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:15:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:15:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:15:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:15:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:15:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:15:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:15:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:15:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:15:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:15:23', 'DoVa_Co2', '0']
['2021-5-4 21:15:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:15:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:15:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:15:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:15:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:16:23', 'fKWhCounter', '3472.63696289063']
['2021-5-4 21:16:23', 'fActPhLevelMixTank1', '5.6216926574707']
['2021-5-4 21:16:23', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 21:16:23', 'fActPhLevelMixTank2', '3.80693984031677']
['2021-5-4 21:16:23', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 21:16:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:16:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:16:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:16:23', 'fActRhValMemo', '52']
['2021-5-4 21:16:23', 'fActCo2ValMemo', '756']
['2021-5-4 21:16:23', 'fActWaterLevelMixTank1', '287.350677490234']
['2021-5-4 21:16:23', 'fActWaterLevelMixTank2', '293.625183105469']
['2021-5-4 21:16:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:16:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:16:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:16:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:16:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:16:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:16:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:16:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:16:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:16:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:16:23', 'DoVa_Co2', '0']
['2021-5-4 21:16:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:16:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:16:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:16:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:16:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:17:23', 'fKWhCounter', '3472.73706054688']
['2021-5-4 21:17:23', 'fActPhLevelMixTank1', '5.6202278137207']
['2021-5-4 21:17:23', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 21:17:23', 'fActPhLevelMixTank2', '3.81084632873535']
['2021-5-4 21:17:23', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 21:17:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:17:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:17:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:17:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:17:23', 'fActCo2ValMemo', '755']
['2021-5-4 21:17:23', 'fActWaterLevelMixTank1', '288.084075927734']
['2021-5-4 21:17:23', 'fActWaterLevelMixTank2', '293.760986328125']
['2021-5-4 21:17:23', 'DoPu_AddAcidMixTank_1', '0']

['2021-5-4 21:17:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:17:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:17:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:17:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:17:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:17:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:17:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:17:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:17:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:17:23', 'DoVa_Co2', '0']
['2021-5-4 21:17:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:17:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:17:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:17:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:17:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:18:23', 'fKWhCounter', '3472.93725585938']
['2021-5-4 21:18:23', 'fActPhLevelMixTank1', '5.6216926574707']
['2021-5-4 21:18:23', 'fActEcLevelMixTank1', '2045.04528808594']
['2021-5-4 21:18:23', 'fActPhLevelMixTank2', '3.81524085998535']
['2021-5-4 21:18:23', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 21:18:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:18:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:18:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:18:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:18:23', 'fActCo2ValMemo', '752']
['2021-5-4 21:18:23', 'fActWaterLevelMixTank1', '286.753112792969']
['2021-5-4 21:18:23', 'fActWaterLevelMixTank2', '294.114105224609']
['2021-5-4 21:18:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:18:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:18:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:18:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:18:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:18:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:18:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:18:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:18:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:18:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:18:23', 'DoVa_Co2', '0']
['2021-5-4 21:18:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:18:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:18:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:18:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:18:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:19:23', 'fKWhCounter', '3473.03735351563']
['2021-5-4 21:19:23', 'fActPhLevelMixTank1', '5.6319465637207']
['2021-5-4 21:19:23', 'fActEcLevelMixTank1', '2032.68530273438']
['2021-5-4 21:19:23', 'fActPhLevelMixTank2', '3.81548500061035']
['2021-5-4 21:19:23', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 21:19:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:19:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:19:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:19:23', 'fActRhValMemo', '52']
['2021-5-4 21:19:23', 'fActCo2ValMemo', '750']
['2021-5-4 21:19:23', 'fActWaterLevelMixTank1', '288.464324951172']
['2021-5-4 21:19:23', 'fActWaterLevelMixTank2', '294.711669921875']
['2021-5-4 21:19:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:19:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:19:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:19:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:19:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:19:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:19:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:19:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:19:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:19:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:19:23', 'DoVa_Co2', '0']
['2021-5-4 21:19:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:19:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:19:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:19:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:19:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:20:23', 'fKWhCounter', '3473.23754882813']
['2021-5-4 21:20:23', 'fActPhLevelMixTank1', '5.6309700012207']
['2021-5-4 21:20:23', 'fActEcLevelMixTank1', '2032.38012695313']
['2021-5-4 21:20:23', 'fActPhLevelMixTank2', '3.80693984031677']
['2021-5-4 21:20:23', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 21:20:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:20:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:20:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:20:23', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 21:20:23', 'fActCo2ValMemo', '748']
['2021-5-4 21:20:23', 'fActWaterLevelMixTank1', '288.926086425781']
['2021-5-4 21:20:23', 'fActWaterLevelMixTank2', '294.277099609375']
['2021-5-4 21:20:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:20:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:20:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:20:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:20:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:20:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:20:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:20:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:20:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:20:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:20:23', 'DoVa_Co2', '0']
['2021-5-4 21:20:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:20:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:20:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:20:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:20:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:21:23', 'fKWhCounter', '3473.33764648438']
['2021-5-4 21:21:23', 'fActPhLevelMixTank1', '5.63658571243286']
['2021-5-4 21:21:23', 'fActEcLevelMixTank1', '2029.78601074219']
['2021-5-4 21:21:23', 'fActPhLevelMixTank2', '3.81109046936035']
['2021-5-4 21:21:23', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 21:21:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:21:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:21:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:21:23', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 21:21:23', 'fActCo2ValMemo', '748']
['2021-5-4 21:21:23', 'fActWaterLevelMixTank1', '288.355682373047']
['2021-5-4 21:21:23', 'fActWaterLevelMixTank2', '294.467224121094']
['2021-5-4 21:21:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:21:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:21:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:21:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:21:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:21:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:21:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:21:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:21:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:21:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:21:23', 'DoVa_Co2', '0']
['2021-5-4 21:21:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:21:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:21:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:21:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:21:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:22:23', 'fKWhCounter', '3473.53784179688']
['2021-5-4 21:22:23', 'fActPhLevelMixTank1', '5.63780641555786']
['2021-5-4 21:22:23', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 21:22:23', 'fActPhLevelMixTank2', '3.80303359031677']

['2021-5-4 21:22:23', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 21:22:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:22:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:22:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:22:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:22:23', 'fActCo2ValMemo', '754']
['2021-5-4 21:22:23', 'fActWaterLevelMixTank1', '286.753112792969']
['2021-5-4 21:22:23', 'fActWaterLevelMixTank2', '295.064788818359']
['2021-5-4 21:22:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:22:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:22:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:22:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:22:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:22:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:22:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:22:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:22:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:22:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:22:23', 'DoVa_Co2', '0']
['2021-5-4 21:22:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:22:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:22:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:22:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:22:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:23:23', 'fKWhCounter', '3473.63793945313']
['2021-5-4 21:23:23', 'fActPhLevelMixTank1', '5.63975954055786']
['2021-5-4 21:23:23', 'fActEcLevelMixTank1', '2030.09130859375']
['2021-5-4 21:23:23', 'fActPhLevelMixTank2', '3.80816054344177']
['2021-5-4 21:23:23', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 21:23:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:23:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:23:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:23:23', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 21:23:23', 'fActCo2ValMemo', '766']
['2021-5-4 21:23:23', 'fActWaterLevelMixTank1', '288.708801269531']
['2021-5-4 21:23:23', 'fActWaterLevelMixTank2', '295.173431396484']
['2021-5-4 21:23:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:23:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:23:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:23:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:23:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:23:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:23:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:23:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:23:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:23:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:23:23', 'DoVa_Co2', '0']
['2021-5-4 21:23:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:23:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:23:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:23:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:23:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:24:23', 'fKWhCounter', '3473.83813476563']
['2021-5-4 21:24:23', 'fActPhLevelMixTank1', '5.63756227493286']
['2021-5-4 21:24:23', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 21:24:23', 'fActPhLevelMixTank2', '3.81279945373535']
['2021-5-4 21:24:23', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 21:24:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:24:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:24:23', 'fActTempValMemo', '21.1000003814697']
['2021-5-4 21:24:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:24:23', 'fActCo2ValMemo', '785']
['2021-5-4 21:24:23', 'fActWaterLevelMixTank1', '288.926086425781']
['2021-5-4 21:24:23', 'fActWaterLevelMixTank2', '294.820343017578']
['2021-5-4 21:24:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:24:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:24:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:24:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:24:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:24:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:24:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:24:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:24:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:24:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:24:23', 'DoVa_Co2', '0']
['2021-5-4 21:24:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:24:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:24:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:24:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:24:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:25:23', 'fKWhCounter', '3473.93823242188']
['2021-5-4 21:25:23', 'fActPhLevelMixTank1', '5.64561891555786']
['2021-5-4 21:25:23', 'fActEcLevelMixTank1', '2033.60083007813']
['2021-5-4 21:25:23', 'fActPhLevelMixTank2', '3.81475257873535']
['2021-5-4 21:25:23', 'fActEcLevelMixTank2', '1039.30786132813']
['2021-5-4 21:25:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:25:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:25:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:25:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:25:23', 'fActCo2ValMemo', '807']
['2021-5-4 21:25:23', 'fActWaterLevelMixTank1', '289.469360351563']
['2021-5-4 21:25:23', 'fActWaterLevelMixTank2', '295.689544677734']
['2021-5-4 21:25:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:25:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:25:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:25:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:25:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:25:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:25:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:25:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:25:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:25:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:25:23', 'DoVa_Co2', '0']
['2021-5-4 21:25:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:25:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:25:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:25:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:25:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:26:23', 'fKWhCounter', '3474.03833007813']
['2021-5-4 21:26:23', 'fActPhLevelMixTank1', '5.64342164993286']
['2021-5-4 21:26:23', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 21:26:23', 'fActPhLevelMixTank2', '3.81377601623535']
['2021-5-4 21:26:23', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 21:26:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:26:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:26:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:26:23', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 21:26:23', 'fActCo2ValMemo', '829']
['2021-5-4 21:26:23', 'fActWaterLevelMixTank1', '289.197723388672']
['2021-5-4 21:26:23', 'fActWaterLevelMixTank2', '295.743865966797']
['2021-5-4 21:26:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:26:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:26:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:26:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:26:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:26:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:26:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:26:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:26:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:26:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:26:23', 'DoVa_Co2', '0']
['2021-5-4 21:26:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:26:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:26:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:26:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']

['2021-5-4 21:26:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:26:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:27:23', 'fKWhCounter', '3474.23852539063']
['2021-5-4 21:27:23', 'fActPhLevelMixTank1', '5.64903736114502']
['2021-5-4 21:27:23', 'fActEcLevelMixTank1', '2033.90600585938']
['2021-5-4 21:27:23', 'fActPhLevelMixTank2', '3.81670594215393']
['2021-5-4 21:27:23', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 21:27:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:27:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:27:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:27:23', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 21:27:23', 'fActCo2ValMemo', '847']
['2021-5-4 21:27:23', 'fActWaterLevelMixTank1', '290.202728271484']
['2021-5-4 21:27:23', 'fActWaterLevelMixTank2', '296.069793701172']
['2021-5-4 21:27:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:27:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:27:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:27:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:27:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:27:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:27:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:27:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:27:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:27:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:27:23', 'DoVa_Co2', '0']
['2021-5-4 21:27:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:27:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:27:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:27:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:27:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:28:23', 'fKWhCounter', '3474.33862304688']
['2021-5-4 21:28:23', 'fActPhLevelMixTank1', '5.65050220489502']
['2021-5-4 21:28:23', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 21:28:23', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 21:28:23', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 21:28:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:28:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:28:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:28:23', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 21:28:23', 'fActCo2ValMemo', '867']
['2021-5-4 21:28:23', 'fActWaterLevelMixTank1', '289.686645507813']
['2021-5-4 21:28:23', 'fActWaterLevelMixTank2', '295.852508544922']
['2021-5-4 21:28:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:28:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:28:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:28:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:28:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:28:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:28:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:28:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:28:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:28:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:28:23', 'DoVa_Co2', '0']
['2021-5-4 21:28:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:28:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:28:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:28:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:28:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:29:23', 'fKWhCounter', '3474.53881835938']
['2021-5-4 21:29:23', 'fActPhLevelMixTank1', '5.64610719680786']
['2021-5-4 21:29:23', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 21:29:23', 'fActPhLevelMixTank2', '3.81279945373535']
['2021-5-4 21:29:23', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 21:29:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:29:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:29:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:29:23', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 21:29:23', 'fActCo2ValMemo', '886']
['2021-5-4 21:29:23', 'fActWaterLevelMixTank1', '289.768127441406']
['2021-5-4 21:29:23', 'fActWaterLevelMixTank2', '296.178466796875']
['2021-5-4 21:29:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:29:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:29:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:29:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:29:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:29:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:29:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:29:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:29:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:29:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:29:23', 'DoVa_Co2', '0']
['2021-5-4 21:29:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:29:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:29:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:29:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:29:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:30:23', 'fKWhCounter', '3474.63891601563']
['2021-5-4 21:30:23', 'fActPhLevelMixTank1', '5.64928150177002']
['2021-5-4 21:30:23', 'fActEcLevelMixTank1', '2030.396484375']
['2021-5-4 21:30:23', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 21:30:23', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 21:30:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:30:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:30:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:30:23', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 21:30:23', 'fActCo2ValMemo', '901']
['2021-5-4 21:30:23', 'fActWaterLevelMixTank1', '290.284210205078']
['2021-5-4 21:30:23', 'fActWaterLevelMixTank2', '296.531555175781']
['2021-5-4 21:30:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:30:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:30:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:30:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:30:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:30:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:30:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:30:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:30:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:30:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:30:23', 'DoVa_Co2', '0']
['2021-5-4 21:30:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:30:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:30:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:30:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:30:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:31:23', 'fKWhCounter', '3474.83911132813']
['2021-5-4 21:31:23', 'fActPhLevelMixTank1', '5.65440845489502']
['2021-5-4 21:31:23', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 21:31:23', 'fActPhLevelMixTank2', '3.81621742248535']
['2021-5-4 21:31:23', 'fActEcLevelMixTank2', '1040.22338867188']
['2021-5-4 21:31:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:31:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:31:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:31:23', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 21:31:23', 'fActCo2ValMemo', '914']
['2021-5-4 21:31:23', 'fActWaterLevelMixTank1', '290.501525878906']
['2021-5-4 21:31:23', 'fActWaterLevelMixTank2', '296.422912597656']
['2021-5-4 21:31:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:31:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:31:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:31:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:31:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:31:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:31:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:31:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:31:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:31:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:31:23', 'DoVa_Co2', '0']
['2021-5-4 21:31:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:31:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:31:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:31:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:31:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']

['2021-5-4 21:31:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:32:23', 'fKWhCounter', '3474.93920898438']
['2021-5-4 21:32:23', 'fActPhLevelMixTank1', '5.65416431427002']
['2021-5-4 21:32:23', 'fActEcLevelMixTank1', '2030.70166015625']
['2021-5-4 21:32:23', 'fActPhLevelMixTank2', '3.81719422340393']
['2021-5-4 21:32:23', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 21:32:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:32:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:32:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:32:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:32:23', 'fActCo2ValMemo', '925']
['2021-5-4 21:32:23', 'fActWaterLevelMixTank1', '290.392852783203']
['2021-5-4 21:32:23', 'fActWaterLevelMixTank2', '296.803192138672']
['2021-5-4 21:32:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:32:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:32:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:32:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:32:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:32:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:32:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:32:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:32:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:32:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:32:23', 'DoVa_Co2', '0']
['2021-5-4 21:32:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:32:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:32:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:32:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:32:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:33:23', 'fKWhCounter', '3475.13940429688']
['2021-5-4 21:33:23', 'fActPhLevelMixTank1', '5.66295337677002']
['2021-5-4 21:33:23', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 21:33:23', 'fActPhLevelMixTank2', '3.82061219215393']
['2021-5-4 21:33:23', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 21:33:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:33:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:33:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:33:23', 'fActRhValMemo', '52']
['2021-5-4 21:33:23', 'fActCo2ValMemo', '933']
['2021-5-4 21:33:23', 'fActWaterLevelMixTank1', '290.175567626953']
['2021-5-4 21:33:23', 'fActWaterLevelMixTank2', '296.151275634766']
['2021-5-4 21:33:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:33:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:33:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:33:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:33:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:33:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:33:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:33:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:33:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:33:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:33:23', 'DoVa_Co2', '0']
['2021-5-4 21:33:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:33:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:33:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:33:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:33:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:34:23', 'fKWhCounter', '3475.23950195313']
['2021-5-4 21:34:23', 'fActPhLevelMixTank1', '5.59581279754639']
['2021-5-4 21:34:23', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 21:34:23', 'fActPhLevelMixTank2', '3.73491621017456']
['2021-5-4 21:34:23', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 21:34:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:34:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:34:23', 'fActTempValMemo', '21.2000007629395']
['2021-5-4 21:34:23', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 21:34:23', 'fActCo2ValMemo', '938']
['2021-5-4 21:34:23', 'fActWaterLevelMixTank1', '288.926086425781']
['2021-5-4 21:34:23', 'fActWaterLevelMixTank2', '304.924743652344']
['2021-5-4 21:34:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:34:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:34:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:34:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:34:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:34:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:34:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:34:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:34:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:34:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:34:23', 'DoVa_Co2', '0']
['2021-5-4 21:34:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:34:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:34:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:34:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:34:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:35:23', 'fKWhCounter', '3475.43969726563']
['2021-5-4 21:35:23', 'fActPhLevelMixTank1', '5.56700325012207']
['2021-5-4 21:35:23', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 21:35:23', 'fActPhLevelMixTank2', '3.72734761238098']
['2021-5-4 21:35:23', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 21:35:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:35:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:35:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:35:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:35:23', 'fActCo2ValMemo', '943']
['2021-5-4 21:35:23', 'fActWaterLevelMixTank1', '281.619415283203']
['2021-5-4 21:35:23', 'fActWaterLevelMixTank2', '312.095611572266']
['2021-5-4 21:35:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:35:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:35:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:35:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:35:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:35:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:35:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:35:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:35:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:35:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:35:23', 'DoVa_Co2', '0']
['2021-5-4 21:35:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:35:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:35:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:35:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:35:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:36:23', 'fKWhCounter', '3475.63989257813']
['2021-5-4 21:36:23', 'fActPhLevelMixTank1', '5.56944465637207']
['2021-5-4 21:36:23', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 21:36:23', 'fActPhLevelMixTank2', '3.74028754234314']
['2021-5-4 21:36:23', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 21:36:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:36:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:36:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:36:23', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 21:36:23', 'fActCo2ValMemo', '942']
['2021-5-4 21:36:23', 'fActWaterLevelMixTank1', '282.271331787109']
['2021-5-4 21:36:23', 'fActWaterLevelMixTank2', '271.35205078125']
['2021-5-4 21:36:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:36:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:36:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:36:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:36:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:36:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:36:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:36:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:36:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:36:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:36:23', 'DoVa_Co2', '0']
['2021-5-4 21:36:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:36:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:36:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:36:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_2_Red', '0']

['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:36:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:37:23', 'fKWhCounter', '3475.84008789063']
['2021-5-4 21:37:23', 'fActPhLevelMixTank1', '5.56944465637207']
['2021-5-4 21:37:23', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 21:37:23', 'fActPhLevelMixTank2', '3.74077582359314']
['2021-5-4 21:37:23', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 21:37:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:37:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:37:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:37:23', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 21:37:23', 'fActCo2ValMemo', '946']
['2021-5-4 21:37:23', 'fActWaterLevelMixTank1', '279.881042480469']
['2021-5-4 21:37:23', 'fActWaterLevelMixTank2', '276.485748291016']
['2021-5-4 21:37:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:37:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:37:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:37:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:37:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:37:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:37:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:37:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:37:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:37:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:37:23', 'DoVa_Co2', '0']
['2021-5-4 21:37:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:37:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:37:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:37:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:37:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:38:23', 'fKWhCounter', '3475.94018554688']
['2021-5-4 21:38:23', 'fActPhLevelMixTank1', '5.57701349258423']
['2021-5-4 21:38:23', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 21:38:23', 'fActPhLevelMixTank2', '3.73735761642456']
['2021-5-4 21:38:23', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 21:38:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:38:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:38:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:38:23', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 21:38:23', 'fActCo2ValMemo', '949']
['2021-5-4 21:38:23', 'fActWaterLevelMixTank1', '279.473602294922']
['2021-5-4 21:38:23', 'fActWaterLevelMixTank2', '266.299835205078']
['2021-5-4 21:38:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:38:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:38:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:38:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:38:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:38:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:38:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:38:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:38:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:38:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:38:23', 'DoVa_Co2', '0']
['2021-5-4 21:38:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:38:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:38:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:38:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:38:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:39:23', 'fKWhCounter', '3476.14038085938']
['2021-5-4 21:39:23', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 21:39:23', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 21:39:23', 'fActPhLevelMixTank2', '3.76641130447388']
['2021-5-4 21:39:23', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 21:39:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:39:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:39:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:39:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:39:23', 'fActCo2ValMemo', '949']
['2021-5-4 21:39:23', 'fActWaterLevelMixTank1', '278.495758056641']
['2021-5-4 21:39:23', 'fActWaterLevelMixTank2', '288.382843017578']
['2021-5-4 21:39:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:39:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:39:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:39:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:39:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:39:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:39:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:39:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:39:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:39:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:39:23', 'DoVa_Co2', '0']
['2021-5-4 21:39:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:39:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:39:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:39:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:39:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:40:23', 'fKWhCounter', '3476.34057617188']
['2021-5-4 21:40:23', 'fActPhLevelMixTank1', '5.58287286758423']
['2021-5-4 21:40:23', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 21:40:23', 'fActPhLevelMixTank2', '3.78960537910461']
['2021-5-4 21:40:23', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 21:40:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:40:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:40:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:40:23', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 21:40:23', 'fActCo2ValMemo', '951']
['2021-5-4 21:40:23', 'fActWaterLevelMixTank1', '278.550079345703']
['2021-5-4 21:40:23', 'fActWaterLevelMixTank2', '289.034759521484']
['2021-5-4 21:40:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:40:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:40:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:40:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:40:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:40:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:40:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:40:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:40:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:40:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:40:23', 'DoVa_Co2', '0']
['2021-5-4 21:40:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:40:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:40:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:40:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:40:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:41:23', 'fKWhCounter', '3476.44067382813']
['2021-5-4 21:41:23', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 21:41:23', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 21:41:23', 'fActPhLevelMixTank2', '3.78325748443604']
['2021-5-4 21:41:23', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 21:41:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:41:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:41:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:41:23', 'fActRhValMemo', '52']
['2021-5-4 21:41:23', 'fActCo2ValMemo', '950']
['2021-5-4 21:41:23', 'fActWaterLevelMixTank1', '278.441436767578']
['2021-5-4 21:41:23', 'fActWaterLevelMixTank2', '288.301361083984']
['2021-5-4 21:41:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:41:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:41:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:41:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:41:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:41:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:41:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:41:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:41:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:41:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:41:23', 'DoVa_Co2', '0']
['2021-5-4 21:41:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:41:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:41:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:41:23', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:41:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:42:23', 'fKWhCounter', '3476.54077148438']
['2021-5-4 21:42:23', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 21:42:23', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 21:42:23', 'fActPhLevelMixTank2', '3.78057193756104']
['2021-5-4 21:42:23', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 21:42:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:42:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:42:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:42:23', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 21:42:23', 'fActCo2ValMemo', '950']
['2021-5-4 21:42:23', 'fActWaterLevelMixTank1', '278.088317871094']
['2021-5-4 21:42:23', 'fActWaterLevelMixTank2', '288.165557861328']
['2021-5-4 21:42:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:42:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:42:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:42:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:42:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:42:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:42:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:42:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:42:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:42:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:42:23', 'DoVa_Co2', '0']
['2021-5-4 21:42:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:42:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:42:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:42:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:42:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:43:23', 'fKWhCounter', '3476.74096679688']
['2021-5-4 21:43:23', 'fActPhLevelMixTank1', '5.58287286758423']
['2021-5-4 21:43:23', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 21:43:23', 'fActPhLevelMixTank2', '3.78057193756104']
['2021-5-4 21:43:23', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 21:43:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:43:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:43:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:43:23', 'fActRhValMemo', '52']
['2021-5-4 21:43:23', 'fActCo2ValMemo', '949']
['2021-5-4 21:43:23', 'fActWaterLevelMixTank1', '278.441436767578']
['2021-5-4 21:43:23', 'fActWaterLevelMixTank2', '288.301361083984']
['2021-5-4 21:43:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:43:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:43:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:43:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:43:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:43:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:43:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:43:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:43:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:43:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:43:23', 'DoVa_Co2', '0']
['2021-5-4 21:43:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:43:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:43:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:43:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:43:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:44:23', 'fKWhCounter', '3476.84106445313']
['2021-5-4 21:44:23', 'fActPhLevelMixTank1', '5.58970928192139']
['2021-5-4 21:44:23', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 21:44:23', 'fActPhLevelMixTank2', '3.77593302726746']
['2021-5-4 21:44:23', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 21:44:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:44:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:44:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:44:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:44:23', 'fActCo2ValMemo', '943']
['2021-5-4 21:44:23', 'fActWaterLevelMixTank1', '278.305603027344']
['2021-5-4 21:44:23', 'fActWaterLevelMixTank2', '288.274200439453']
['2021-5-4 21:44:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:44:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:44:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:44:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:44:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:44:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:44:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:44:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:44:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:44:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:44:23', 'DoVa_Co2', '0']
['2021-5-4 21:44:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:44:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:44:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:44:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:44:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:45:23', 'fKWhCounter', '3477.04125976563']
['2021-5-4 21:45:23', 'fActPhLevelMixTank1', '5.58287286758423']
['2021-5-4 21:45:23', 'fActEcLevelMixTank1', '2029.48083496094']
['2021-5-4 21:45:23', 'fActPhLevelMixTank2', '3.77764225006104']
['2021-5-4 21:45:23', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 21:45:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:45:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:45:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:45:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 21:45:23', 'fActCo2ValMemo', '941']
['2021-5-4 21:45:23', 'fActWaterLevelMixTank1', '278.658721923828']
['2021-5-4 21:45:23', 'fActWaterLevelMixTank2', '288.572998046875']
['2021-5-4 21:45:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:45:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:45:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:45:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:45:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:45:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:45:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:45:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:45:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:45:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:45:23', 'DoVa_Co2', '0']
['2021-5-4 21:45:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:45:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:45:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:45:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_4_Fred', '0']

['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:45:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:46:23', 'fKWhCounter', '3477.14135742188']
['2021-5-4 21:46:23', 'fActPhLevelMixTank1', '5.58800029754639']
['2021-5-4 21:46:23', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 21:46:23', 'fActPhLevelMixTank2', '3.77935123443604']
['2021-5-4 21:46:23', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 21:46:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:46:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:46:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:46:23', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 21:46:23', 'fActCo2ValMemo', '943']
['2021-5-4 21:46:23', 'fActWaterLevelMixTank1', '278.0068359375']
['2021-5-4 21:46:23', 'fActWaterLevelMixTank2', '288.219879150391']
['2021-5-4 21:46:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:46:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:46:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:46:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:46:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:46:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:46:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:46:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:46:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:46:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:46:23', 'DoVa_Co2', '0']
['2021-5-4 21:46:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:46:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:46:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:46:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:46:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:47:23', 'fKWhCounter', '3477.34155273438']
['2021-5-4 21:47:23', 'fActPhLevelMixTank1', '5.58043146133423']
['2021-5-4 21:47:23', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 21:47:23', 'fActPhLevelMixTank2', '3.77690958976746']
['2021-5-4 21:47:23', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 21:47:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:47:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:47:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:47:23', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 21:47:23', 'fActCo2ValMemo', '941']
['2021-5-4 21:47:23', 'fActWaterLevelMixTank1', '277.572235107422']
['2021-5-4 21:47:23', 'fActWaterLevelMixTank2', '288.056915283203']
['2021-5-4 21:47:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:47:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:47:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:47:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:47:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:47:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:47:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:47:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:47:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:47:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:47:23', 'DoVa_Co2', '0']
['2021-5-4 21:47:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:47:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:47:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:47:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:47:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:48:23', 'fKWhCounter', '3477.44165039063']
['2021-5-4 21:48:23', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 21:48:23', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 21:48:23', 'fActPhLevelMixTank2', '3.78130435943604']
['2021-5-4 21:48:23', 'fActEcLevelMixTank2', '1030.30493164063']
['2021-5-4 21:48:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:48:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:48:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:48:23', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 21:48:23', 'fActCo2ValMemo', '941']
['2021-5-4 21:48:23', 'fActWaterLevelMixTank1', '279.283447265625']
['2021-5-4 21:48:23', 'fActWaterLevelMixTank2', '288.111236572266']
['2021-5-4 21:48:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:48:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:48:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:48:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:48:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:48:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:48:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:48:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:48:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:48:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:48:23', 'DoVa_Co2', '0']
['2021-5-4 21:48:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:48:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:48:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:48:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:48:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:49:23', 'fKWhCounter', '3477.64184570313']
['2021-5-4 21:49:23', 'fActPhLevelMixTank1', '5.57799005508423']
['2021-5-4 21:49:23', 'fActEcLevelMixTank1', '2019.86755371094']
['2021-5-4 21:49:23', 'fActPhLevelMixTank2', '3.77959537506104']
['2021-5-4 21:49:23', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 21:49:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:49:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:49:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:49:23', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 21:49:23', 'fActCo2ValMemo', '938']
['2021-5-4 21:49:23', 'fActWaterLevelMixTank1', '279.881042480469']
['2021-5-4 21:49:23', 'fActWaterLevelMixTank2', '288.926086425781']
['2021-5-4 21:49:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:49:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:49:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:49:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:49:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:49:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:49:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:49:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:49:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:49:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:49:23', 'DoVa_Co2', '0']
['2021-5-4 21:49:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:49:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:49:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:49:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:49:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:50:23', 'fKWhCounter', '3477.74194335938']
['2021-5-4 21:50:23', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 21:50:23', 'fActEcLevelMixTank1', '2020.78308105469']
['2021-5-4 21:50:23', 'fActPhLevelMixTank2', '3.77739810943604']
['2021-5-4 21:50:23', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 21:50:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:50:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:50:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:50:23', 'fActRhValMemo', '51']
['2021-5-4 21:50:23', 'fActCo2ValMemo', '938']
['2021-5-4 21:50:23', 'fActWaterLevelMixTank1', '278.713043212891']
['2021-5-4 21:50:23', 'fActWaterLevelMixTank2', '288.790283203125']
['2021-5-4 21:50:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:50:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:50:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:50:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:50:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:50:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:50:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:50:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:50:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:50:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:50:23', 'DoVa_Co2', '0']
['2021-5-4 21:50:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:50:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:50:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:50:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_3_Red', '0']

['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:50:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:51:23', 'fKWhCounter', '3477.84204101563']
['2021-5-4 21:51:23', 'fActPhLevelMixTank1', '5.58848857879639']
['2021-5-4 21:51:23', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 21:51:23', 'fActPhLevelMixTank2', '3.78057193756104']
['2021-5-4 21:51:23', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 21:51:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:51:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:51:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:51:23', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 21:51:23', 'fActCo2ValMemo', '938']
['2021-5-4 21:51:23', 'fActWaterLevelMixTank1', '279.337799072266']
['2021-5-4 21:51:23', 'fActWaterLevelMixTank2', '289.007598876953']
['2021-5-4 21:51:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:51:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:51:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:51:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:51:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:51:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:51:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:51:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:51:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:51:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:51:23', 'DoVa_Co2', '0']
['2021-5-4 21:51:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:51:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:51:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:51:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:51:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:52:23', 'fKWhCounter', '3478.04223632813']
['2021-5-4 21:52:23', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 21:52:23', 'fActEcLevelMixTank1', '2019.40979003906']
['2021-5-4 21:52:23', 'fActPhLevelMixTank2', '3.78325748443604']
['2021-5-4 21:52:23', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 21:52:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:52:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:52:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:52:23', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 21:52:23', 'fActCo2ValMemo', '937']
['2021-5-4 21:52:23', 'fActWaterLevelMixTank1', '278.848876953125']
['2021-5-4 21:52:23', 'fActWaterLevelMixTank2', '289.252044677734']
['2021-5-4 21:52:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:52:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:52:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:52:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:52:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:52:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:52:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:52:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:52:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:52:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:52:23', 'DoVa_Co2', '0']
['2021-5-4 21:52:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:52:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:52:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:52:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:52:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:53:23', 'fKWhCounter', '3478.14233398438']
['2021-5-4 21:53:23', 'fActPhLevelMixTank1', '5.58800029754639']
['2021-5-4 21:53:23', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 21:53:23', 'fActPhLevelMixTank2', '3.77959537506104']
['2021-5-4 21:53:23', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 21:53:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:53:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:53:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:53:23', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 21:53:23', 'fActCo2ValMemo', '937']
['2021-5-4 21:53:23', 'fActWaterLevelMixTank1', '279.337799072266']
['2021-5-4 21:53:23', 'fActWaterLevelMixTank2', '290.094085693359']
['2021-5-4 21:53:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:53:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:53:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:53:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:53:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:53:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:53:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:53:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:53:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:53:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:53:23', 'DoVa_Co2', '0']
['2021-5-4 21:53:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:53:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:53:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:53:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:53:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:54:23', 'fKWhCounter', '3478.34252929688']
['2021-5-4 21:54:23', 'fActPhLevelMixTank1', '5.58604717254639']
['2021-5-4 21:54:23', 'fActEcLevelMixTank1', '2018.34167480469']
['2021-5-4 21:54:23', 'fActPhLevelMixTank2', '3.78203678131104']
['2021-5-4 21:54:23', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 21:54:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:54:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:54:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:54:23', 'fActRhValMemo', '51']
['2021-5-4 21:54:23', 'fActCo2ValMemo', '936']
['2021-5-4 21:54:23', 'fActWaterLevelMixTank1', '281.320648193359']
['2021-5-4 21:54:23', 'fActWaterLevelMixTank2', '290.392852783203']
['2021-5-4 21:54:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:54:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:54:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:54:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:54:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:54:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:54:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:54:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:54:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:54:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:54:23', 'DoVa_Co2', '0']
['2021-5-4 21:54:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:54:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:54:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:54:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:54:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:55:23', 'fKWhCounter', '3478.44262695313']
['2021-5-4 21:55:23', 'fActPhLevelMixTank1', '5.59776592254639']
['2021-5-4 21:55:23', 'fActEcLevelMixTank1', '2017.2734375']
['2021-5-4 21:55:23', 'fActPhLevelMixTank2', '3.79009366035461']
['2021-5-4 21:55:23', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 21:55:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:55:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:55:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:55:23', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 21:55:23', 'fActCo2ValMemo', '937']
['2021-5-4 21:55:23', 'fActWaterLevelMixTank1', '282.162658691406']
['2021-5-4 21:55:23', 'fActWaterLevelMixTank2', '290.474365234375']
['2021-5-4 21:55:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:55:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:55:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:55:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:55:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:55:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:55:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:55:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:55:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:55:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:55:23', 'DoVa_Co2', '0']
['2021-5-4 21:55:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:55:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:55:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:55:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:55:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:56:23', 'fKWhCounter', '3478.64282226563']
['2021-5-4 21:56:23', 'fActPhLevelMixTank1', '5.59727764129639']
['2021-5-4 21:56:23', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 21:56:23', 'fActPhLevelMixTank2', '3.78521084785461']
['2021-5-4 21:56:23', 'fActEcLevelMixTank2', '1031.52563476563']
['2021-5-4 21:56:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:56:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:56:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:56:23', 'fActRhValMemo', '51.2000007629395']

['2021-5-4 21:56:23', 'fActCo2ValMemo', '935']
['2021-5-4 21:56:23', 'fActWaterLevelMixTank1', '282.054016113281']
['2021-5-4 21:56:23', 'fActWaterLevelMixTank2', '290.528686523438']
['2021-5-4 21:56:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:56:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:56:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:56:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:56:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:56:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:56:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:56:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:56:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:56:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:56:23', 'DoVa_Co2', '0']
['2021-5-4 21:56:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:56:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:56:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:56:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:56:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:57:23', 'fKWhCounter', '3478.74291992188']
['2021-5-4 21:57:23', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 21:57:23', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 21:57:23', 'fActPhLevelMixTank2', '3.79107022285461']
['2021-5-4 21:57:23', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 21:57:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:57:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:57:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:57:23', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 21:57:23', 'fActCo2ValMemo', '933']
['2021-5-4 21:57:23', 'fActWaterLevelMixTank1', '281.945373535156']
['2021-5-4 21:57:23', 'fActWaterLevelMixTank2', '291.017608642578']
['2021-5-4 21:57:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:57:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:57:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:57:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:57:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:57:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:57:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:57:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:57:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:57:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:57:23', 'DoVa_Co2', '0']
['2021-5-4 21:57:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:57:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:57:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:57:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:57:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:58:23', 'fKWhCounter', '3478.94311523438']
['2021-5-4 21:58:23', 'fActPhLevelMixTank1', '5.60386991500854']
['2021-5-4 21:58:23', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 21:58:23', 'fActPhLevelMixTank2', '3.79546499252319']
['2021-5-4 21:58:23', 'fActEcLevelMixTank2', '1030.91528320313']
['2021-5-4 21:58:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:58:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:58:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:58:23', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 21:58:23', 'fActCo2ValMemo', '932']
['2021-5-4 21:58:23', 'fActWaterLevelMixTank1', '280.641571044922']
['2021-5-4 21:58:23', 'fActWaterLevelMixTank2', '291.832458496094']
['2021-5-4 21:58:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:58:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:58:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:58:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:58:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:58:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:58:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:58:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:58:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:58:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:58:23', 'DoVa_Co2', '0']
['2021-5-4 21:58:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:58:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:58:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:58:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:58:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 21:59:23', 'fKWhCounter', '3479.04321289063']
['2021-5-4 21:59:23', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 21:59:23', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 21:59:23', 'fActPhLevelMixTank2', '3.79546499252319']
['2021-5-4 21:59:23', 'fActEcLevelMixTank2', '1031.373046875']
['2021-5-4 21:59:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 21:59:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 21:59:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 21:59:23', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 21:59:23', 'fActCo2ValMemo', '931']
['2021-5-4 21:59:23', 'fActWaterLevelMixTank1', '283.031860351563']
['2021-5-4 21:59:23', 'fActWaterLevelMixTank2', '291.53369140625']
['2021-5-4 21:59:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 21:59:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 21:59:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 21:59:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 21:59:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 21:59:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 21:59:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 21:59:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 21:59:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 21:59:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 21:59:23', 'DoVa_Co2', '0']
['2021-5-4 21:59:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 21:59:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 21:59:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 21:59:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 21:59:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:0:23', 'fKWhCounter', '3479.14331054688']
['2021-5-4 22:0:23', 'fActPhLevelMixTank1', '5.60509061813354']
['2021-5-4 22:0:23', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 22:0:23', 'fActPhLevelMixTank2', '3.79155850410461']
['2021-5-4 22:0:23', 'fActEcLevelMixTank2', '1031.9833984375']
['2021-5-4 22:0:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:0:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:0:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 22:0:23', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:0:23', 'fActCo2ValMemo', '932']
['2021-5-4 22:0:23', 'fActWaterLevelMixTank1', '283.113342285156']
['2021-5-4 22:0:23', 'fActWaterLevelMixTank2', '291.941131591797']
['2021-5-4 22:0:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:0:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:0:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:0:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:0:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:0:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:0:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:0:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:0:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:0:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:0:23', 'DoVa_Co2', '0']
['2021-5-4 22:0:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:0:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:0:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:0:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:0:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:1:23', 'fKWhCounter', '3479.34350585938']
['2021-5-4 22:1:23', 'fActPhLevelMixTank1', '5.60313749313354']
['2021-5-4 22:1:23', 'fActEcLevelMixTank1', '2024.29272460938']
['2021-5-4 22:1:23', 'fActPhLevelMixTank2', '3.79839468002319']
['2021-5-4 22:1:23', 'fActEcLevelMixTank2', '1022.52264404297']
['2021-5-4 22:1:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:1:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:1:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 22:1:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 22:1:23', 'fActCo2ValMemo', '936']
['2021-5-4 22:1:23', 'fActWaterLevelMixTank1', '283.602264404297']
['2021-5-4 22:1:23', 'fActWaterLevelMixTank2', '292.104095458984']
['2021-5-4 22:1:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:1:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:1:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:1:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:1:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:1:23', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 22:1:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:1:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:1:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:1:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:1:23', 'DoVa_Co2', '0']
['2021-5-4 22:1:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:1:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:1:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:1:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:1:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:2:23', 'fKWhCounter', '3479.44360351563']
['2021-5-4 22:2:23', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 22:2:23', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 22:2:23', 'fActPhLevelMixTank2', '3.79912710189819']
['2021-5-4 22:2:23', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 22:2:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:2:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:2:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 22:2:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 22:2:23', 'fActCo2ValMemo', '933']
['2021-5-4 22:2:23', 'fActWaterLevelMixTank1', '284.335662841797']
['2021-5-4 22:2:23', 'fActWaterLevelMixTank2', '292.620178222656']
['2021-5-4 22:2:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:2:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:2:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:2:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:2:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:2:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:2:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:2:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:2:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:2:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:2:23', 'DoVa_Co2', '0']
['2021-5-4 22:2:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:2:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:2:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:2:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:2:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:3:23', 'fKWhCounter', '3479.64379882813']
['2021-5-4 22:3:23', 'fActPhLevelMixTank1', '5.60411405563354']
['2021-5-4 22:3:23', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 22:3:23', 'fActPhLevelMixTank2', '3.79595327377319']
['2021-5-4 22:3:23', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 22:3:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:3:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:3:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 22:3:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 22:3:23', 'fActCo2ValMemo', '928']
['2021-5-4 22:3:23', 'fActWaterLevelMixTank1', '282.515777587891']
['2021-5-4 22:3:23', 'fActWaterLevelMixTank2', '292.049774169922']
['2021-5-4 22:3:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:3:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:3:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:3:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:3:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:3:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:3:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:3:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:3:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:3:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:3:23', 'DoVa_Co2', '0']
['2021-5-4 22:3:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:3:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:3:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:3:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:3:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:4:23', 'fKWhCounter', '3479.74389648438']
['2021-5-4 22:4:23', 'fActPhLevelMixTank1', '5.60533475875854']
['2021-5-4 22:4:23', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 22:4:23', 'fActPhLevelMixTank2', '3.80230116844177']
['2021-5-4 22:4:23', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 22:4:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:4:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:4:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 22:4:23', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 22:4:23', 'fActCo2ValMemo', '926']
['2021-5-4 22:4:23', 'fActWaterLevelMixTank1', '284.444305419922']
['2021-5-4 22:4:23', 'fActWaterLevelMixTank2', '293.000457763672']
['2021-5-4 22:4:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:4:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:4:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:4:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:4:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:4:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:4:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:4:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:4:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:4:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:4:23', 'DoVa_Co2', '0']
['2021-5-4 22:4:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:4:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:4:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:4:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:4:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:5:23', 'fKWhCounter', '3479.94409179688']
['2021-5-4 22:5:23', 'fActPhLevelMixTank1', '5.60020732879639']
['2021-5-4 22:5:23', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 22:5:23', 'fActPhLevelMixTank2', '3.80156874656677']
['2021-5-4 22:5:23', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 22:5:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:5:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:5:23', 'fActTempValMemo', '21.2999992370605']
['2021-5-4 22:5:23', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:5:23', 'fActCo2ValMemo', '923']
['2021-5-4 22:5:23', 'fActWaterLevelMixTank1', '284.607269287109']
['2021-5-4 22:5:23', 'fActWaterLevelMixTank2', '292.810333251953']
['2021-5-4 22:5:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:5:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:5:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:5:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:5:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:5:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:5:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:5:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:5:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:5:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:5:23', 'DoVa_Co2', '0']
['2021-5-4 22:5:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:5:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:5:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:5:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:5:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:6:23', 'fKWhCounter', '3480.04418945313']
['2021-5-4 22:6:23', 'fActPhLevelMixTank1', '5.60704374313354']
['2021-5-4 22:6:23', 'fActEcLevelMixTank1', '2022.6142578125']
['2021-5-4 22:6:23', 'fActPhLevelMixTank2', '3.79668569564819']
['2021-5-4 22:6:23', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 22:6:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:6:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:6:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:6:23', 'fActRhValMemo', '51.5']
['2021-5-4 22:6:23', 'fActCo2ValMemo', '921']
['2021-5-4 22:6:23', 'fActWaterLevelMixTank1', '284.87890625']
['2021-5-4 22:6:23', 'fActWaterLevelMixTank2', '292.837493896484']
['2021-5-4 22:6:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:6:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:6:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:6:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:6:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:6:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:6:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:6:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:6:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:6:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:6:23', 'DoVa_Co2', '0']

['2021-5-4 22:6:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:6:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:6:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:6:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:6:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:7:23', 'fKWhCounter', '3480.24438476563']
['2021-5-4 22:7:23', 'fActPhLevelMixTank1', '5.60289335250854']
['2021-5-4 22:7:23', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 22:7:23', 'fActPhLevelMixTank2', '3.80303359031677']
['2021-5-4 22:7:23', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 22:7:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:7:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:7:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:7:23', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 22:7:23', 'fActCo2ValMemo', '923']
['2021-5-4 22:7:23', 'fActWaterLevelMixTank1', '285.232025146484']
['2021-5-4 22:7:23', 'fActWaterLevelMixTank2', '293.000457763672']
['2021-5-4 22:7:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:7:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:7:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:7:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:7:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:7:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:7:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:7:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:7:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:7:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:7:23', 'DoVa_Co2', '0']
['2021-5-4 22:7:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:7:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:7:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:7:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:7:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:8:23', 'fKWhCounter', '3480.34448242188']
['2021-5-4 22:8:23', 'fActPhLevelMixTank1', '5.61314725875854']
['2021-5-4 22:8:23', 'fActEcLevelMixTank1', '2026.12390136719']
['2021-5-4 22:8:23', 'fActPhLevelMixTank2', '3.80303359031677']
['2021-5-4 22:8:23', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 22:8:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:8:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:8:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:8:23', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 22:8:23', 'fActCo2ValMemo', '919']
['2021-5-4 22:8:23', 'fActWaterLevelMixTank1', '284.580108642578']
['2021-5-4 22:8:23', 'fActWaterLevelMixTank2', '293.244903564453']
['2021-5-4 22:8:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:8:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:8:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:8:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:8:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:8:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:8:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:8:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:8:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:8:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:8:23', 'DoVa_Co2', '0']
['2021-5-4 22:8:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:8:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:8:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:8:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:8:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:9:23', 'fKWhCounter', '3480.54467773438']
['2021-5-4 22:9:23', 'fActPhLevelMixTank1', '5.61021757125854']
['2021-5-4 22:9:23', 'fActEcLevelMixTank1', '2027.03942871094']
['2021-5-4 22:9:23', 'fActPhLevelMixTank2', '3.79839468002319']
['2021-5-4 22:9:23', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 22:9:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:9:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:9:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:9:23', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 22:9:23', 'fActCo2ValMemo', '915']
['2021-5-4 22:9:23', 'fActWaterLevelMixTank1', '285.422149658203']
['2021-5-4 22:9:23', 'fActWaterLevelMixTank2', '293.625183105469']
['2021-5-4 22:9:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:9:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:9:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:9:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:9:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:9:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:9:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:9:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:9:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:9:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:9:23', 'DoVa_Co2', '0']
['2021-5-4 22:9:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:9:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:9:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:9:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:9:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:10:23', 'fKWhCounter', '3480.64477539063']
['2021-5-4 22:10:23', 'fActPhLevelMixTank1', '5.61680936813354']
['2021-5-4 22:10:23', 'fActEcLevelMixTank1', '2027.03942871094']
['2021-5-4 22:10:23', 'fActPhLevelMixTank2', '3.80523085594177']
['2021-5-4 22:10:23', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 22:10:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:10:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:10:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:10:23', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 22:10:23', 'fActCo2ValMemo', '914']
['2021-5-4 22:10:23', 'fActWaterLevelMixTank1', '285.177703857422']
['2021-5-4 22:10:23', 'fActWaterLevelMixTank2', '293.462219238281']
['2021-5-4 22:10:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:10:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:10:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:10:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:10:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:10:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:10:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:10:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:10:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:10:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:10:23', 'DoVa_Co2', '0']
['2021-5-4 22:10:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:10:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:10:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:10:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:10:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:11:23', 'fKWhCounter', '3480.84497070313']
['2021-5-4 22:11:23', 'fActPhLevelMixTank1', '5.6187629699707']
['2021-5-4 22:11:23', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 22:11:23', 'fActPhLevelMixTank2', '3.80327773094177']
['2021-5-4 22:11:23', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 22:11:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:11:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:11:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:11:23', 'fActRhValMemo', '51.5']
['2021-5-4 22:11:23', 'fActCo2ValMemo', '911']
['2021-5-4 22:11:23', 'fActWaterLevelMixTank1', '284.906066894531']
['2021-5-4 22:11:23', 'fActWaterLevelMixTank2', '293.570861816406']
['2021-5-4 22:11:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:11:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:11:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:11:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:11:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:11:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:11:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:11:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:11:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:11:23', 'DoVa_IrrigateLevel_2_MT2', '0']

['2021-5-4 22:11:23', 'DoVa_Co2', '0']
['2021-5-4 22:11:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:11:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:11:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:11:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:11:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:12:23', 'fKWhCounter', '3480.94506835938']
['2021-5-4 22:12:23', 'fActPhLevelMixTank1', '5.61656522750854']
['2021-5-4 22:12:23', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 22:12:23', 'fActPhLevelMixTank2', '3.80205702781677']
['2021-5-4 22:12:23', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 22:12:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:12:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:12:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:12:23', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 22:12:23', 'fActCo2ValMemo', '911']
['2021-5-4 22:12:23', 'fActWaterLevelMixTank1', '284.66162109375']
['2021-5-4 22:12:23', 'fActWaterLevelMixTank2', '293.353576660156']
['2021-5-4 22:12:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:12:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:12:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:12:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:12:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:12:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:12:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:12:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:12:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:12:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:12:23', 'DoVa_Co2', '0']
['2021-5-4 22:12:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:12:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:12:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:12:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:12:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:13:23', 'fKWhCounter', '3481.14526367188']
['2021-5-4 22:13:23', 'fActPhLevelMixTank1', '5.6251106262207']
['2021-5-4 22:13:23', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 22:13:23', 'fActPhLevelMixTank2', '3.80010366439819']
['2021-5-4 22:13:23', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 22:13:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:13:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:13:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:13:23', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 22:13:23', 'fActCo2ValMemo', '908']
['2021-5-4 22:13:23', 'fActWaterLevelMixTank1', '285.585144042969']
['2021-5-4 22:13:23', 'fActWaterLevelMixTank2', '293.896820068359']
['2021-5-4 22:13:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:13:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:13:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:13:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:13:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:13:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:13:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:13:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:13:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:13:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:13:23', 'DoVa_Co2', '0']
['2021-5-4 22:13:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:13:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:13:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:13:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:13:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:14:23', 'fKWhCounter', '3481.24536132813']
['2021-5-4 22:14:23', 'fActPhLevelMixTank1', '5.6212043762207']
['2021-5-4 22:14:23', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 22:14:23', 'fActPhLevelMixTank2', '3.80669569969177']
['2021-5-4 22:14:23', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 22:14:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:14:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:14:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:14:23', 'fActRhValMemo', '52']
['2021-5-4 22:14:23', 'fActCo2ValMemo', '907']
['2021-5-4 22:14:23', 'fActWaterLevelMixTank1', '285.585144042969']
['2021-5-4 22:14:23', 'fActWaterLevelMixTank2', '293.65234375']
['2021-5-4 22:14:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:14:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:14:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:14:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:14:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:14:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:14:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:14:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:14:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:14:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:14:23', 'DoVa_Co2', '0']
['2021-5-4 22:14:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:14:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:14:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:14:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:14:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:15:23', 'fKWhCounter', '3481.34545898438']
['2021-5-4 22:15:23', 'fActPhLevelMixTank1', '5.6309700012207']
['2021-5-4 22:15:23', 'fActEcLevelMixTank1', '2038.94165039063']
['2021-5-4 22:15:23', 'fActPhLevelMixTank2', '3.79937124252319']
['2021-5-4 22:15:23', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 22:15:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:15:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:15:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:15:23', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 22:15:23', 'fActCo2ValMemo', '907']
['2021-5-4 22:15:23', 'fActWaterLevelMixTank1', '285.09619140625']
['2021-5-4 22:15:23', 'fActWaterLevelMixTank2', '294.412902832031']
['2021-5-4 22:15:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:15:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:15:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:15:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:15:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:15:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:15:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:15:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:15:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:15:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:15:23', 'DoVa_Co2', '0']
['2021-5-4 22:15:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:15:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:15:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:15:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:15:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:16:23', 'fKWhCounter', '3481.54565429688']
['2021-5-4 22:16:23', 'fActPhLevelMixTank1', '5.6253547668457']
['2021-5-4 22:16:23', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 22:16:23', 'fActPhLevelMixTank2', '3.79815053939819']
['2021-5-4 22:16:23', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 22:16:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:16:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:16:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:16:23', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:16:23', 'fActCo2ValMemo', '908']
['2021-5-4 22:16:23', 'fActWaterLevelMixTank1', '284.715942382813']
['2021-5-4 22:16:23', 'fActWaterLevelMixTank2', '294.630187988281']

['2021-5-4 22:16:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:16:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:16:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:16:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:16:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:16:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:16:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:16:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:16:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:16:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:16:23', 'DoVa_Co2', '0']
['2021-5-4 22:16:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:16:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:16:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:16:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:16:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:17:23', 'fKWhCounter', '3481.64575195313']
['2021-5-4 22:17:23', 'fActPhLevelMixTank1', '5.6319465637207']
['2021-5-4 22:17:23', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 22:17:23', 'fActPhLevelMixTank2', '3.80596327781677']
['2021-5-4 22:17:23', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 22:17:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:17:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:17:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:17:23', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:17:23', 'fActCo2ValMemo', '910']
['2021-5-4 22:17:23', 'fActWaterLevelMixTank1', '285.693786621094']
['2021-5-4 22:17:23', 'fActWaterLevelMixTank2', '294.684509277344']
['2021-5-4 22:17:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:17:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:17:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:17:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:17:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:17:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:17:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:17:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:17:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:17:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:17:23', 'DoVa_Co2', '0']
['2021-5-4 22:17:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:17:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:17:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:17:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:17:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:18:23', 'fKWhCounter', '3481.84594726563']
['2021-5-4 22:18:23', 'fActPhLevelMixTank1', '5.6265754699707']
['2021-5-4 22:18:23', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 22:18:23', 'fActPhLevelMixTank2', '3.80108046531677']
['2021-5-4 22:18:23', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 22:18:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:18:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:18:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:18:23', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:18:23', 'fActCo2ValMemo', '910']
['2021-5-4 22:18:23', 'fActWaterLevelMixTank1', '286.99755859375']
['2021-5-4 22:18:23', 'fActWaterLevelMixTank2', '294.928985595703']
['2021-5-4 22:18:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:18:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:18:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:18:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:18:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:18:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:18:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:18:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:18:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:18:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:18:23', 'DoVa_Co2', '0']
['2021-5-4 22:18:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:18:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:18:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:18:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:18:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:19:23', 'fKWhCounter', '3481.94604492188']
['2021-5-4 22:19:23', 'fActPhLevelMixTank1', '5.63707399368286']
['2021-5-4 22:19:23', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 22:19:23', 'fActPhLevelMixTank2', '3.80156874656677']
['2021-5-4 22:19:23', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 22:19:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:19:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:19:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:19:23', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:19:23', 'fActCo2ValMemo', '910']
['2021-5-4 22:19:23', 'fActWaterLevelMixTank1', '287.513671875']
['2021-5-4 22:19:23', 'fActWaterLevelMixTank2', '295.363586425781']
['2021-5-4 22:19:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:19:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:19:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:19:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:19:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:19:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:19:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:19:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:19:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:19:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:19:23', 'DoVa_Co2', '0']
['2021-5-4 22:19:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:19:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:19:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:19:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:19:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:20:23', 'fKWhCounter', '3482.14624023438']
['2021-5-4 22:20:23', 'fActPhLevelMixTank1', '5.63951539993286']
['2021-5-4 22:20:23', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 22:20:23', 'fActPhLevelMixTank2', '3.80864906311035']
['2021-5-4 22:20:23', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 22:20:23', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:20:23', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:20:23', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:20:23', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 22:20:23', 'fActCo2ValMemo', '909']
['2021-5-4 22:20:23', 'fActWaterLevelMixTank1', '287.595153808594']
['2021-5-4 22:20:23', 'fActWaterLevelMixTank2', '294.956146240234']
['2021-5-4 22:20:23', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:20:23', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:20:23', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:20:23', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:20:23', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:20:23', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:20:23', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:20:23', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:20:23', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:20:23', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:20:23', 'DoVa_Co2', '0']
['2021-5-4 22:20:23', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:20:23', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:20:23', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:20:23', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:20:23', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:21:24', 'fKWhCounter', '3482.24633789063']
['2021-5-4 22:21:24', 'fActPhLevelMixTank1', '5.64366579055786']
['2021-5-4 22:21:24', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 22:21:24', 'fActPhLevelMixTank2', '3.80352187156677']
['2021-5-4 22:21:24', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 22:21:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:21:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:21:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:21:24', 'fActRhValMemo', '52']
['2021-5-4 22:21:24', 'fActCo2ValMemo', '906']
['2021-5-4 22:21:24', 'fActWaterLevelMixTank1', '286.345672607422']
['2021-5-4 22:21:24', 'fActWaterLevelMixTank2', '295.445068359375']
['2021-5-4 22:21:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:21:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:21:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:21:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:21:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:21:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:21:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:21:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:21:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:21:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:21:24', 'DoVa_Co2', '0']
['2021-5-4 22:21:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:21:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:21:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:21:24', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:21:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:22:24', 'fKWhCounter', '3482.44653320313']
['2021-5-4 22:22:24', 'fActPhLevelMixTank1', '5.64171266555786']
['2021-5-4 22:22:24', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 22:22:24', 'fActPhLevelMixTank2', '3.80498671531677']
['2021-5-4 22:22:24', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 22:22:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:22:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:22:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:22:24', 'fActRhValMemo', '52']
['2021-5-4 22:22:24', 'fActCo2ValMemo', '904']
['2021-5-4 22:22:24', 'fActWaterLevelMixTank1', '287.893920898438']
['2021-5-4 22:22:24', 'fActWaterLevelMixTank2', '295.580871582031']
['2021-5-4 22:22:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:22:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:22:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:22:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:22:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:22:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:22:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:22:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:22:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:22:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:22:24', 'DoVa_Co2', '0']
['2021-5-4 22:22:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:22:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:22:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:22:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:22:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:23:24', 'fKWhCounter', '3482.54663085938']
['2021-5-4 22:23:24', 'fActPhLevelMixTank1', '5.63756227493286']
['2021-5-4 22:23:24', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 22:23:24', 'fActPhLevelMixTank2', '3.80889320373535']
['2021-5-4 22:23:24', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 22:23:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:23:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:23:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:23:24', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 22:23:24', 'fActCo2ValMemo', '904']
['2021-5-4 22:23:24', 'fActWaterLevelMixTank1', '288.328521728516']
['2021-5-4 22:23:24', 'fActWaterLevelMixTank2', '295.961151123047']
['2021-5-4 22:23:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:23:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:23:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:23:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:23:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:23:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:23:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:23:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:23:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:23:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:23:24', 'DoVa_Co2', '0']
['2021-5-4 22:23:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:23:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:23:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:23:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:23:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:24:24', 'fKWhCounter', '3482.74682617188']
['2021-5-4 22:24:24', 'fActPhLevelMixTank1', '5.64342164993286']
['2021-5-4 22:24:24', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 22:24:24', 'fActPhLevelMixTank2', '3.80303359031677']
['2021-5-4 22:24:24', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 22:24:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:24:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:24:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:24:24', 'fActRhValMemo', '52.2999992370605']
['2021-5-4 22:24:24', 'fActCo2ValMemo', '902']
['2021-5-4 22:24:24', 'fActWaterLevelMixTank1', '286.888916015625']
['2021-5-4 22:24:24', 'fActWaterLevelMixTank2', '295.662353515625']
['2021-5-4 22:24:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:24:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:24:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:24:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:24:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:24:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:24:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:24:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:24:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:24:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:24:24', 'DoVa_Co2', '0']
['2021-5-4 22:24:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:24:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:24:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:24:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:24:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:25:24', 'fKWhCounter', '3482.84692382813']
['2021-5-4 22:25:24', 'fActPhLevelMixTank1', '5.64366579055786']
['2021-5-4 22:25:24', 'fActEcLevelMixTank1', '2031.0068359375']
['2021-5-4 22:25:24', 'fActPhLevelMixTank2', '3.80596327781677']
['2021-5-4 22:25:24', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 22:25:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:25:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:25:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:25:24', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 22:25:24', 'fActCo2ValMemo', '900']
['2021-5-4 22:25:24', 'fActWaterLevelMixTank1', '288.627319335938']
['2021-5-4 22:25:24', 'fActWaterLevelMixTank2', '296.178466796875']
['2021-5-4 22:25:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:25:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:25:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:25:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:25:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:25:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:25:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:25:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:25:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:25:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:25:24', 'DoVa_Co2', '0']
['2021-5-4 22:25:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:25:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:25:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:25:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:25:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:26:24', 'fKWhCounter', '3483.04711914063']
['2021-5-4 22:26:24', 'fActPhLevelMixTank1', '5.65294361114502']
['2021-5-4 22:26:24', 'fActEcLevelMixTank1', '2028.41271972656']
['2021-5-4 22:26:24', 'fActPhLevelMixTank2', '3.80986976623535']
['2021-5-4 22:26:24', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 22:26:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:26:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:26:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:26:24', 'fActRhValMemo', '52']
['2021-5-4 22:26:24', 'fActCo2ValMemo', '900']
['2021-5-4 22:26:24', 'fActWaterLevelMixTank1', '286.725952148438']
['2021-5-4 22:26:24', 'fActWaterLevelMixTank2', '296.096954345703']
['2021-5-4 22:26:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:26:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:26:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:26:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:26:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:26:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:26:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:26:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:26:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:26:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:26:24', 'DoVa_Co2', '0']
['2021-5-4 22:26:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:26:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:26:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:26:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']

['2021-5-4 22:26:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:26:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:27:24', 'fKWhCounter', '3483.14721679688']
['2021-5-4 22:27:24', 'fActPhLevelMixTank1', '5.64537477493286']
['2021-5-4 22:27:24', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 22:27:24', 'fActPhLevelMixTank2', '3.81206703186035']
['2021-5-4 22:27:24', 'fActEcLevelMixTank2', '1037.17150878906']
['2021-5-4 22:27:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:27:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:27:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 22:27:24', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 22:27:24', 'fActCo2ValMemo', '901']
['2021-5-4 22:27:24', 'fActWaterLevelMixTank1', '288.518676757813']
['2021-5-4 22:27:24', 'fActWaterLevelMixTank2', '296.911834716797']
['2021-5-4 22:27:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:27:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:27:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:27:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:27:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:27:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:27:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:27:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:27:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:27:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:27:24', 'DoVa_Co2', '0']
['2021-5-4 22:27:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:27:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:27:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:27:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:27:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:28:24', 'fKWhCounter', '3483.24731445313']
['2021-5-4 22:28:24', 'fActPhLevelMixTank1', '5.65392017364502']
['2021-5-4 22:28:24', 'fActEcLevelMixTank1', '2029.02307128906']
['2021-5-4 22:28:24', 'fActPhLevelMixTank2', '3.80889320373535']
['2021-5-4 22:28:24', 'fActEcLevelMixTank2', '1039.30786132813']
['2021-5-4 22:28:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:28:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:28:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:28:24', 'fActRhValMemo', '52']
['2021-5-4 22:28:24', 'fActCo2ValMemo', '899']
['2021-5-4 22:28:24', 'fActWaterLevelMixTank1', '288.545837402344']
['2021-5-4 22:28:24', 'fActWaterLevelMixTank2', '296.748870849609']
['2021-5-4 22:28:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:28:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:28:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:28:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:28:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:28:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:28:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:28:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:28:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:28:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:28:24', 'DoVa_Co2', '0']
['2021-5-4 22:28:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:28:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:28:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:28:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:28:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:29:24', 'fKWhCounter', '3483.44750976563']
['2021-5-4 22:29:24', 'fActPhLevelMixTank1', '5.64806032180786']
['2021-5-4 22:29:24', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 22:29:24', 'fActPhLevelMixTank2', '3.81377601623535']
['2021-5-4 22:29:24', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 22:29:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:29:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:29:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:29:24', 'fActRhValMemo', '52']
['2021-5-4 22:29:24', 'fActCo2ValMemo', '898']
['2021-5-4 22:29:24', 'fActWaterLevelMixTank1', '287.622314453125']
['2021-5-4 22:29:24', 'fActWaterLevelMixTank2', '296.857513427734']
['2021-5-4 22:29:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:29:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:29:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:29:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:29:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:29:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:29:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:29:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:29:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:29:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:29:24', 'DoVa_Co2', '0']
['2021-5-4 22:29:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:29:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:29:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:29:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:29:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:30:24', 'fKWhCounter', '3483.54760742188']
['2021-5-4 22:30:24', 'fActPhLevelMixTank1', '5.65709400177002']
['2021-5-4 22:30:24', 'fActEcLevelMixTank1', '2036.04235839844']
['2021-5-4 22:30:24', 'fActPhLevelMixTank2', '3.81157875061035']
['2021-5-4 22:30:24', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 22:30:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:30:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:30:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:30:24', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 22:30:24', 'fActCo2ValMemo', '897']
['2021-5-4 22:30:24', 'fActWaterLevelMixTank1', '288.627319335938']
['2021-5-4 22:30:24', 'fActWaterLevelMixTank2', '296.830352783203']
['2021-5-4 22:30:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:30:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:30:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:30:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:30:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:30:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:30:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:30:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:30:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:30:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:30:24', 'DoVa_Co2', '0']
['2021-5-4 22:30:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:30:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:30:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:30:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:30:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:31:24', 'fKWhCounter', '3483.74780273438']
['2021-5-4 22:31:24', 'fActPhLevelMixTank1', '5.65221118927002']
['2021-5-4 22:31:24', 'fActEcLevelMixTank1', '2036.95788574219']
['2021-5-4 22:31:24', 'fActPhLevelMixTank2', '3.81304359436035']
['2021-5-4 22:31:24', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 22:31:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:31:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:31:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:31:24', 'fActRhValMemo', '52']
['2021-5-4 22:31:24', 'fActCo2ValMemo', '895']
['2021-5-4 22:31:24', 'fActWaterLevelMixTank1', '287.595153808594']
['2021-5-4 22:31:24', 'fActWaterLevelMixTank2', '297.101959228516']
['2021-5-4 22:31:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:31:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:31:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:31:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:31:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:31:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:31:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:31:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:31:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:31:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:31:24', 'DoVa_Co2', '0']
['2021-5-4 22:31:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:31:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:31:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:31:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:31:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:32:24', 'fKWhCounter', '3483.84790039063']
['2021-5-4 22:32:24', 'fActPhLevelMixTank1', '5.65831470489502']
['2021-5-4 22:32:24', 'fActEcLevelMixTank1', '2031.76977539063']
['2021-5-4 22:32:24', 'fActPhLevelMixTank2', '3.81524085998535']
['2021-5-4 22:32:24', 'fActEcLevelMixTank2', '1038.39233398438']
['2021-5-4 22:32:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:32:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:32:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:32:24', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 22:32:24', 'fActCo2ValMemo', '892']
['2021-5-4 22:32:24', 'fActWaterLevelMixTank1', '288.219879150391']
['2021-5-4 22:32:24', 'fActWaterLevelMixTank2', '297.482238769531']
['2021-5-4 22:32:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:32:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:32:24', 'DoPu_AddEcBMixTank_1', '0']

['2021-5-4 22:32:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:32:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:32:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:32:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:32:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:32:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:32:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:32:24', 'DoVa_Co2', '0']
['2021-5-4 22:32:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:32:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:32:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:32:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:32:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:33:24', 'fKWhCounter', '3484.04809570313']
['2021-5-4 22:33:24', 'fActPhLevelMixTank1', '5.65245532989502']
['2021-5-4 22:33:24', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 22:33:24', 'fActPhLevelMixTank2', '3.81353187561035']
['2021-5-4 22:33:24', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 22:33:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:33:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:33:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:33:24', 'fActRhValMemo', '52']
['2021-5-4 22:33:24', 'fActCo2ValMemo', '893']
['2021-5-4 22:33:24', 'fActWaterLevelMixTank1', '289.442199707031']
['2021-5-4 22:33:24', 'fActWaterLevelMixTank2', '297.427917480469']
['2021-5-4 22:33:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:33:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:33:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:33:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:33:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:33:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:33:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:33:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:33:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:33:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:33:24', 'DoVa_Co2', '0']
['2021-5-4 22:33:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:33:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:33:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:33:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:33:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:34:24', 'fKWhCounter', '3484.14819335938']
['2021-5-4 22:34:24', 'fActPhLevelMixTank1', '5.66002368927002']
['2021-5-4 22:34:24', 'fActEcLevelMixTank1', '2030.396484375']
['2021-5-4 22:34:24', 'fActPhLevelMixTank2', '3.81524085998535']
['2021-5-4 22:34:24', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 22:34:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:34:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:34:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:34:24', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 22:34:24', 'fActCo2ValMemo', '891']
['2021-5-4 22:34:24', 'fActWaterLevelMixTank1', '289.605163574219']
['2021-5-4 22:34:24', 'fActWaterLevelMixTank2', '297.944000244141']
['2021-5-4 22:34:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:34:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:34:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:34:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:34:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:34:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:34:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:34:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:34:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:34:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:34:24', 'DoVa_Co2', '0']
['2021-5-4 22:34:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:34:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:34:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:34:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:34:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:35:24', 'fKWhCounter', '3484.34838867188']
['2021-5-4 22:35:24', 'fActPhLevelMixTank1', '5.65538501739502']
['2021-5-4 22:35:24', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 22:35:24', 'fActPhLevelMixTank2', '3.81646180152893']
['2021-5-4 22:35:24', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 22:35:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:35:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:35:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:35:24', 'fActRhValMemo', '51.7999992370605']
['2021-5-4 22:35:24', 'fActCo2ValMemo', '889']
['2021-5-4 22:35:24', 'fActWaterLevelMixTank1', '288.572998046875']
['2021-5-4 22:35:24', 'fActWaterLevelMixTank2', '298.324279785156']
['2021-5-4 22:35:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:35:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:35:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:35:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:35:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:35:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:35:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:35:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:35:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:35:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:35:24', 'DoVa_Co2', '0']
['2021-5-4 22:35:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:35:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:35:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:35:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:35:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:36:24', 'fKWhCounter', '3484.44848632813']
['2021-5-4 22:36:24', 'fActPhLevelMixTank1', '5.66368579864502']
['2021-5-4 22:36:24', 'fActEcLevelMixTank1', '2032.07495117188']
['2021-5-4 22:36:24', 'fActPhLevelMixTank2', '3.81719422340393']
['2021-5-4 22:36:24', 'fActEcLevelMixTank2', '1038.69750976563']
['2021-5-4 22:36:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:36:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:36:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:36:24', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 22:36:24', 'fActCo2ValMemo', '891']
['2021-5-4 22:36:24', 'fActWaterLevelMixTank1', '290.284210205078']
['2021-5-4 22:36:24', 'fActWaterLevelMixTank2', '297.944000244141']
['2021-5-4 22:36:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:36:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:36:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:36:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:36:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:36:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:36:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:36:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:36:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:36:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:36:24', 'DoVa_Co2', '0']
['2021-5-4 22:36:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:36:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:36:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:36:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:36:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:37:24', 'fKWhCounter', '3484.64868164063']
['2021-5-4 22:37:24', 'fActPhLevelMixTank1', '5.66734838485718']
['2021-5-4 22:37:24', 'fActEcLevelMixTank1', '2031.46459960938']
['2021-5-4 22:37:24', 'fActPhLevelMixTank2', '3.81011390686035']
['2021-5-4 22:37:24', 'fActEcLevelMixTank2', '1039.765625']
['2021-5-4 22:37:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:37:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:37:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:37:24', 'fActRhValMemo', '51.9000015258789']
['2021-5-4 22:37:24', 'fActCo2ValMemo', '892']
['2021-5-4 22:37:24', 'fActWaterLevelMixTank1', '290.311370849609']
['2021-5-4 22:37:24', 'fActWaterLevelMixTank2', '298.297119140625']
['2021-5-4 22:37:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:37:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:37:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:37:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:37:24', 'DoPu_AddEcAMixTank_2', '0']

['2021-5-4 22:37:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:37:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:37:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:37:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:37:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:37:24', 'DoVa_Co2', '0']
['2021-5-4 22:37:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:37:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:37:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:37:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:37:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:38:24', 'fKWhCounter', '3484.74877929688']
['2021-5-4 22:38:24', 'fActPhLevelMixTank1', '5.67149877548218']
['2021-5-4 22:38:24', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 22:38:24', 'fActPhLevelMixTank2', '3.81768250465393']
['2021-5-4 22:38:24', 'fActEcLevelMixTank2', '1039.30786132813']
['2021-5-4 22:38:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:38:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:38:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:38:24', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 22:38:24', 'fActCo2ValMemo', '892']
['2021-5-4 22:38:24', 'fActWaterLevelMixTank1', '290.392852783203']
['2021-5-4 22:38:24', 'fActWaterLevelMixTank2', '298.106994628906']
['2021-5-4 22:38:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:38:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:38:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:38:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:38:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:38:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:38:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:38:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:38:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:38:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:38:24', 'DoVa_Co2', '0']
['2021-5-4 22:38:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:38:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:38:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:38:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:38:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:39:24', 'fKWhCounter', '3484.94897460938']
['2021-5-4 22:39:24', 'fActPhLevelMixTank1', '5.59556865692139']
['2021-5-4 22:39:24', 'fActEcLevelMixTank1', '2032.53271484375']
['2021-5-4 22:39:24', 'fActPhLevelMixTank2', '3.72808003425598']
['2021-5-4 22:39:24', 'fActEcLevelMixTank2', '1037.78186035156']
['2021-5-4 22:39:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:39:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:39:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:39:24', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 22:39:24', 'fActCo2ValMemo', '888']
['2021-5-4 22:39:24', 'fActWaterLevelMixTank1', '287.296356201172']
['2021-5-4 22:39:24', 'fActWaterLevelMixTank2', '294.222747802734']
['2021-5-4 22:39:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:39:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:39:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:39:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:39:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:39:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:39:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:39:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:39:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:39:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:39:24', 'DoVa_Co2', '0']
['2021-5-4 22:39:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:39:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:39:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:39:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:39:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:40:24', 'fKWhCounter', '3485.04907226563']
['2021-5-4 22:40:24', 'fActPhLevelMixTank1', '5.57506036758423']
['2021-5-4 22:40:24', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 22:40:24', 'fActPhLevelMixTank2', '3.72637104988098']
['2021-5-4 22:40:24', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 22:40:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:40:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:40:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:40:24', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 22:40:24', 'fActCo2ValMemo', '886']
['2021-5-4 22:40:24', 'fActWaterLevelMixTank1', '283.004699707031']
['2021-5-4 22:40:24', 'fActWaterLevelMixTank2', '298.731719970703']
['2021-5-4 22:40:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:40:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:40:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:40:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:40:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:40:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:40:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:40:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:40:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:40:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:40:24', 'DoVa_Co2', '0']
['2021-5-4 22:40:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:40:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:40:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:40:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:40:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:41:24', 'fKWhCounter', '3485.24926757813']
['2021-5-4 22:41:24', 'fActPhLevelMixTank1', '5.56773567199707']
['2021-5-4 22:41:24', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 22:41:24', 'fActPhLevelMixTank2', '3.73516035079956']
['2021-5-4 22:41:24', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 22:41:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:41:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:41:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:41:24', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:41:24', 'fActCo2ValMemo', '888']
['2021-5-4 22:41:24', 'fActWaterLevelMixTank1', '282.162658691406']
['2021-5-4 22:41:24', 'fActWaterLevelMixTank2', '269.66796875']
['2021-5-4 22:41:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:41:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:41:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:41:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:41:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:41:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:41:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:41:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:41:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:41:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:41:24', 'DoVa_Co2', '0']
['2021-5-4 22:41:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:41:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:41:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:41:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:41:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:42:24', 'fKWhCounter', '3485.44946289063']
['2021-5-4 22:42:24', 'fActPhLevelMixTank1', '5.57310724258423']
['2021-5-4 22:42:24', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 22:42:24', 'fActPhLevelMixTank2', '3.73223066329956']
['2021-5-4 22:42:24', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 22:42:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:42:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:42:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:42:24', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 22:42:24', 'fActCo2ValMemo', '888']
['2021-5-4 22:42:24', 'fActWaterLevelMixTank1', '282.9775390625']
['2021-5-4 22:42:24', 'fActWaterLevelMixTank2', '281.592254638672']
['2021-5-4 22:42:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:42:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:42:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:42:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:42:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:42:24', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 22:42:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:42:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:42:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:42:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:42:24', 'DoVa_Co2', '0']
['2021-5-4 22:42:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:42:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:42:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:42:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:42:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:43:24', 'fKWhCounter', '3485.64965820313']
['2021-5-4 22:43:24', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 22:43:24', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 22:43:24', 'fActPhLevelMixTank2', '3.73369550704956']
['2021-5-4 22:43:24', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 22:43:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:43:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:43:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:43:24', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:43:24', 'fActCo2ValMemo', '883']
['2021-5-4 22:43:24', 'fActWaterLevelMixTank1', '277.463592529297']
['2021-5-4 22:43:24', 'fActWaterLevelMixTank2', '300.171325683594']
['2021-5-4 22:43:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:43:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:43:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:43:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:43:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:43:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:43:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:43:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:43:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:43:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:43:24', 'DoVa_Co2', '0']
['2021-5-4 22:43:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:43:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:43:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:43:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:43:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:44:24', 'fKWhCounter', '3485.74975585938']
['2021-5-4 22:44:24', 'fActPhLevelMixTank1', '5.57554864883423']
['2021-5-4 22:44:24', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 22:44:24', 'fActPhLevelMixTank2', '3.77007365226746']
['2021-5-4 22:44:24', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 22:44:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:44:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:44:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:44:24', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:44:24', 'fActCo2ValMemo', '881']
['2021-5-4 22:44:24', 'fActWaterLevelMixTank1', '277.382080078125']
['2021-5-4 22:44:24', 'fActWaterLevelMixTank2', '290.284210205078']
['2021-5-4 22:44:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:44:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:44:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:44:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:44:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:44:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:44:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:44:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:44:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:44:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:44:24', 'DoVa_Co2', '0']
['2021-5-4 22:44:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:44:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:44:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:44:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:44:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:45:24', 'fKWhCounter', '3485.94995117188']
['2021-5-4 22:45:24', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 22:45:24', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 22:45:24', 'fActPhLevelMixTank2', '3.78203678131104']
['2021-5-4 22:45:24', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 22:45:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:45:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:45:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:45:24', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:45:24', 'fActCo2ValMemo', '882']
['2021-5-4 22:45:24', 'fActWaterLevelMixTank1', '277.409271240234']
['2021-5-4 22:45:24', 'fActWaterLevelMixTank2', '289.876770019531']
['2021-5-4 22:45:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:45:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:45:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:45:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:45:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:45:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:45:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:45:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:45:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:45:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:45:24', 'DoVa_Co2', '0']
['2021-5-4 22:45:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:45:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:45:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:45:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:45:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:46:24', 'fKWhCounter', '3486.05004882813']
['2021-5-4 22:46:24', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 22:46:24', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 22:46:24', 'fActPhLevelMixTank2', '3.78325748443604']
['2021-5-4 22:46:24', 'fActEcLevelMixTank2', '1035.03527832031']
['2021-5-4 22:46:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:46:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:46:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:46:24', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:46:24', 'fActCo2ValMemo', '877']
['2021-5-4 22:46:24', 'fActWaterLevelMixTank1', '276.349914550781']
['2021-5-4 22:46:24', 'fActWaterLevelMixTank2', '290.094085693359']
['2021-5-4 22:46:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:46:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:46:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:46:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:46:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:46:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:46:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:46:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:46:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:46:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:46:24', 'DoVa_Co2', '0']
['2021-5-4 22:46:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:46:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:46:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:46:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:46:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:47:24', 'fKWhCounter', '3486.25024414063']
['2021-5-4 22:47:24', 'fActPhLevelMixTank1', '5.58384943008423']
['2021-5-4 22:47:24', 'fActEcLevelMixTank1', '2046.11352539063']
['2021-5-4 22:47:24', 'fActPhLevelMixTank2', '3.78325748443604']
['2021-5-4 22:47:24', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 22:47:24', 'fTaktCounterUpperLevel', '0']

['2021-5-4 22:47:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:47:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:47:24', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:47:24', 'fActCo2ValMemo', '876']
['2021-5-4 22:47:24', 'fActWaterLevelMixTank1', '277.191955566406']
['2021-5-4 22:47:24', 'fActWaterLevelMixTank2', '289.659484863281']
['2021-5-4 22:47:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:47:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:47:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:47:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:47:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:47:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:47:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:47:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:47:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:47:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:47:24', 'DoVa_Co2', '0']
['2021-5-4 22:47:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:47:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:47:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:47:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:47:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:48:24', 'fKWhCounter', '3486.35034179688']
['2021-5-4 22:48:24', 'fActPhLevelMixTank1', '5.58433771133423']
['2021-5-4 22:48:24', 'fActEcLevelMixTank1', '2031.31201171875']
['2021-5-4 22:48:24', 'fActPhLevelMixTank2', '3.77471232414246']
['2021-5-4 22:48:24', 'fActEcLevelMixTank2', '1037.32409667969']
['2021-5-4 22:48:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:48:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:48:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:48:24', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 22:48:24', 'fActCo2ValMemo', '875']
['2021-5-4 22:48:24', 'fActWaterLevelMixTank1', '277.816680908203']
['2021-5-4 22:48:24', 'fActWaterLevelMixTank2', '289.415008544922']
['2021-5-4 22:48:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:48:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:48:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:48:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:48:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:48:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:48:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:48:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:48:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:48:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:48:24', 'DoVa_Co2', '0']
['2021-5-4 22:48:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:48:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:48:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:48:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:48:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:49:24', 'fKWhCounter', '3486.55053710938']
['2021-5-4 22:49:24', 'fActPhLevelMixTank1', '5.58946514129639']
['2021-5-4 22:49:24', 'fActEcLevelMixTank1', '2029.63342285156']
['2021-5-4 22:49:24', 'fActPhLevelMixTank2', '3.77837467193604']
['2021-5-4 22:49:24', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 22:49:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:49:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:49:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:49:24', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 22:49:24', 'fActCo2ValMemo', '876']
['2021-5-4 22:49:24', 'fActWaterLevelMixTank1', '278.332763671875']
['2021-5-4 22:49:24', 'fActWaterLevelMixTank2', '289.63232421875']
['2021-5-4 22:49:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:49:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:49:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:49:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:49:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:49:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:49:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:49:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:49:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:49:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:49:24', 'DoVa_Co2', '0']
['2021-5-4 22:49:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:49:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:49:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:49:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:49:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:50:24', 'fKWhCounter', '3486.65063476563']
['2021-5-4 22:50:24', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 22:50:24', 'fActEcLevelMixTank1', '2025.36083984375']
['2021-5-4 22:50:24', 'fActPhLevelMixTank2', '3.78154850006104']
['2021-5-4 22:50:24', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 22:50:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:50:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:50:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:50:24', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 22:50:24', 'fActCo2ValMemo', '877']
['2021-5-4 22:50:24', 'fActWaterLevelMixTank1', '278.196960449219']
['2021-5-4 22:50:24', 'fActWaterLevelMixTank2', '289.686645507813']
['2021-5-4 22:50:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:50:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:50:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:50:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:50:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:50:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:50:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:50:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:50:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:50:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:50:24', 'DoVa_Co2', '0']
['2021-5-4 22:50:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:50:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:50:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:50:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:50:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:51:24', 'fKWhCounter', '3486.85083007813']
['2021-5-4 22:51:24', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 22:51:24', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 22:51:24', 'fActPhLevelMixTank2', '3.77935123443604']
['2021-5-4 22:51:24', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 22:51:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:51:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:51:24', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 22:51:24', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 22:51:24', 'fActCo2ValMemo', '875']
['2021-5-4 22:51:24', 'fActWaterLevelMixTank1', '278.550079345703']
['2021-5-4 22:51:24', 'fActWaterLevelMixTank2', '289.903930664063']
['2021-5-4 22:51:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:51:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:51:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:51:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:51:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:51:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:51:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:51:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:51:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:51:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:51:24', 'DoVa_Co2', '0']
['2021-5-4 22:51:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:51:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:51:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:51:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:51:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:52:24', 'fKWhCounter', '3486.95092773438']
['2021-5-4 22:52:24', 'fActPhLevelMixTank1', '5.58116388320923']

['2021-5-4 22:52:24', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 22:52:24', 'fActPhLevelMixTank2', '3.78106021881104']
['2021-5-4 22:52:24', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 22:52:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:52:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:52:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:52:24', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:52:24', 'fActCo2ValMemo', '878']
['2021-5-4 22:52:24', 'fActWaterLevelMixTank1', '277.680877685547']
['2021-5-4 22:52:24', 'fActWaterLevelMixTank2', '290.148406982422']
['2021-5-4 22:52:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:52:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:52:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:52:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:52:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:52:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:52:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:52:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:52:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:52:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:52:24', 'DoVa_Co2', '0']
['2021-5-4 22:52:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:52:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:52:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:52:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:52:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:53:24', 'fKWhCounter', '3487.15112304688']
['2021-5-4 22:53:24', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 22:53:24', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 22:53:24', 'fActPhLevelMixTank2', '3.78106021881104']
['2021-5-4 22:53:24', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 22:53:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:53:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:53:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:53:24', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 22:53:24', 'fActCo2ValMemo', '878']
['2021-5-4 22:53:24', 'fActWaterLevelMixTank1', '279.500762939453']
['2021-5-4 22:53:24', 'fActWaterLevelMixTank2', '289.958282470703']
['2021-5-4 22:53:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:53:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:53:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:53:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:53:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:53:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:53:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:53:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:53:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:53:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:53:24', 'DoVa_Co2', '0']
['2021-5-4 22:53:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:53:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:53:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:53:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:53:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:54:24', 'fKWhCounter', '3487.25122070313']
['2021-5-4 22:54:24', 'fActPhLevelMixTank1', '5.58140802383423']
['2021-5-4 22:54:24', 'fActEcLevelMixTank1', '2021.69860839844']
['2021-5-4 22:54:24', 'fActPhLevelMixTank2', '3.77764225006104']
['2021-5-4 22:54:24', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 22:54:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:54:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:54:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:54:24', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 22:54:24', 'fActCo2ValMemo', '876']
['2021-5-4 22:54:24', 'fActWaterLevelMixTank1', '279.256286621094']
['2021-5-4 22:54:24', 'fActWaterLevelMixTank2', '290.148406982422']
['2021-5-4 22:54:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:54:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:54:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:54:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:54:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:54:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:54:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:54:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:54:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:54:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:54:24', 'DoVa_Co2', '0']
['2021-5-4 22:54:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:54:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:54:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:54:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:54:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:55:24', 'fKWhCounter', '3487.35131835938']
['2021-5-4 22:55:24', 'fActPhLevelMixTank1', '5.58751201629639']
['2021-5-4 22:55:24', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 22:55:24', 'fActPhLevelMixTank2', '3.78228092193604']
['2021-5-4 22:55:24', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 22:55:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:55:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:55:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:55:24', 'fActRhValMemo', '51.7000007629395']
['2021-5-4 22:55:24', 'fActCo2ValMemo', '871']
['2021-5-4 22:55:24', 'fActWaterLevelMixTank1', '280.016845703125']
['2021-5-4 22:55:24', 'fActWaterLevelMixTank2', '290.528686523438']
['2021-5-4 22:55:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:55:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:55:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:55:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:55:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:55:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:55:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:55:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:55:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:55:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:55:24', 'DoVa_Co2', '0']
['2021-5-4 22:55:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:55:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:55:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:55:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:55:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:56:24', 'fKWhCounter', '3487.55151367188']
['2021-5-4 22:56:24', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 22:56:24', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 22:56:24', 'fActPhLevelMixTank2', '3.78106021881104']
['2021-5-4 22:56:24', 'fActEcLevelMixTank2', '1032.59375']
['2021-5-4 22:56:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:56:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:56:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:56:24', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 22:56:24', 'fActCo2ValMemo', '867']
['2021-5-4 22:56:24', 'fActWaterLevelMixTank1', '280.016845703125']
['2021-5-4 22:56:24', 'fActWaterLevelMixTank2', '290.827453613281']
['2021-5-4 22:56:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:56:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:56:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:56:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:56:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:56:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:56:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:56:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:56:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:56:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:56:24', 'DoVa_Co2', '0']
['2021-5-4 22:56:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:56:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:56:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:56:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:56:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:57:24', 'fKWhCounter', '3487.65161132813']
['2021-5-4 22:57:24', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 22:57:24', 'fActEcLevelMixTank1', '2019.10461425781']
['2021-5-4 22:57:24', 'fActPhLevelMixTank2', '3.77642130851746']
['2021-5-4 22:57:24', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 22:57:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:57:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:57:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:57:24', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 22:57:24', 'fActCo2ValMemo', '866']
['2021-5-4 22:57:24', 'fActWaterLevelMixTank1', '280.315643310547']
['2021-5-4 22:57:24', 'fActWaterLevelMixTank2', '291.207733154297']
['2021-5-4 22:57:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:57:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:57:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:57:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:57:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:57:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:57:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:57:24', 'DoVa_IrrigateLevel_2_MT1', '0']

['2021-5-4 22:57:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:57:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:57:24', 'DoVa_Co2', '0']
['2021-5-4 22:57:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:57:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:57:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:57:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:57:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:58:24', 'fKWhCounter', '3487.85180664063']
['2021-5-4 22:58:24', 'fActPhLevelMixTank1', '5.58384943008423']
['2021-5-4 22:58:24', 'fActEcLevelMixTank1', '2018.95202636719']
['2021-5-4 22:58:24', 'fActPhLevelMixTank2', '3.78252506256104']
['2021-5-4 22:58:24', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 22:58:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:58:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:58:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:58:24', 'fActRhValMemo', '51.5999984741211']
['2021-5-4 22:58:24', 'fActCo2ValMemo', '865']
['2021-5-4 22:58:24', 'fActWaterLevelMixTank1', '280.587249755859']
['2021-5-4 22:58:24', 'fActWaterLevelMixTank2', '290.827453613281']
['2021-5-4 22:58:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:58:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:58:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:58:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:58:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:58:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:58:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:58:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:58:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:58:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:58:24', 'DoVa_Co2', '0']
['2021-5-4 22:58:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:58:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:58:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:58:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:58:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 22:59:24', 'fKWhCounter', '3487.95190429688']
['2021-5-4 22:59:24', 'fActPhLevelMixTank1', '5.59044170379639']
['2021-5-4 22:59:24', 'fActEcLevelMixTank1', '2040.16235351563']
['2021-5-4 22:59:24', 'fActPhLevelMixTank2', '3.78130435943604']
['2021-5-4 22:59:24', 'fActEcLevelMixTank2', '1032.13598632813']
['2021-5-4 22:59:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 22:59:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 22:59:24', 'fActTempValMemo', '21.5']
['2021-5-4 22:59:24', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 22:59:24', 'fActCo2ValMemo', '865']
['2021-5-4 22:59:24', 'fActWaterLevelMixTank1', '279.1748046875']
['2021-5-4 22:59:24', 'fActWaterLevelMixTank2', '291.669494628906']
['2021-5-4 22:59:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 22:59:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 22:59:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 22:59:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 22:59:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 22:59:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 22:59:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 22:59:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 22:59:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 22:59:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 22:59:24', 'DoVa_Co2', '0']
['2021-5-4 22:59:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 22:59:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 22:59:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 22:59:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 22:59:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:0:24', 'fKWhCounter', '3488.15209960938']
['2021-5-4 23:0:24', 'fActPhLevelMixTank1', '5.59190654754639']
['2021-5-4 23:0:24', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 23:0:24', 'fActPhLevelMixTank2', '3.77666544914246']
['2021-5-4 23:0:24', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 23:0:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:0:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:0:24', 'fActTempValMemo', '21.5']
['2021-5-4 23:0:24', 'fActRhValMemo', '51']
['2021-5-4 23:0:24', 'fActCo2ValMemo', '864']
['2021-5-4 23:0:24', 'fActWaterLevelMixTank1', '281.565093994141']
['2021-5-4 23:0:24', 'fActWaterLevelMixTank2', '291.941131591797']
['2021-5-4 23:0:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:0:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:0:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:0:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:0:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:0:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:0:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:0:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:0:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:0:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:0:24', 'DoVa_Co2', '0']
['2021-5-4 23:0:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:0:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:0:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:0:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:0:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:1:24', 'fKWhCounter', '3488.25219726563']
['2021-5-4 23:1:24', 'fActPhLevelMixTank1', '5.58873271942139']
['2021-5-4 23:1:24', 'fActEcLevelMixTank1', '2020.02014160156']
['2021-5-4 23:1:24', 'fActPhLevelMixTank2', '3.78325748443604']
['2021-5-4 23:1:24', 'fActEcLevelMixTank2', '1030.7626953125']
['2021-5-4 23:1:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:1:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:1:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:1:24', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 23:1:24', 'fActCo2ValMemo', '861']
['2021-5-4 23:1:24', 'fActWaterLevelMixTank1', '281.374969482422']
['2021-5-4 23:1:24', 'fActWaterLevelMixTank2', '292.104095458984']
['2021-5-4 23:1:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:1:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:1:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:1:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:1:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:1:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:1:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:1:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:1:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:1:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:1:24', 'DoVa_Co2', '0']
['2021-5-4 23:1:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:1:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:1:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:1:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:1:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:2:24', 'fKWhCounter', '3488.45239257813']
['2021-5-4 23:2:24', 'fActPhLevelMixTank1', '5.59239482879639']
['2021-5-4 23:2:24', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 23:2:24', 'fActPhLevelMixTank2', '3.78496646881104']
['2021-5-4 23:2:24', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 23:2:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:2:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:2:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:2:24', 'fActRhValMemo', '51']
['2021-5-4 23:2:24', 'fActCo2ValMemo', '858']
['2021-5-4 23:2:24', 'fActWaterLevelMixTank1', '282.081176757813']
['2021-5-4 23:2:24', 'fActWaterLevelMixTank2', '291.968292236328']
['2021-5-4 23:2:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:2:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:2:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:2:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:2:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:2:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:2:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:2:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:2:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:2:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:2:24', 'DoVa_Co2', '0']
['2021-5-4 23:2:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:2:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:2:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:2:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_3_White', '0']

['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:2:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:3:24', 'fKWhCounter', '3488.55249023438']
['2021-5-4 23:3:24', 'fActPhLevelMixTank1', '5.60118389129639']
['2021-5-4 23:3:24', 'fActEcLevelMixTank1', '2022.91943359375']
['2021-5-4 23:3:24', 'fActPhLevelMixTank2', '3.78325748443604']
['2021-5-4 23:3:24', 'fActEcLevelMixTank2', '1030.45751953125']
['2021-5-4 23:3:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:3:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:3:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:3:24', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 23:3:24', 'fActCo2ValMemo', '859']
['2021-5-4 23:3:24', 'fActWaterLevelMixTank1', '282.597259521484']
['2021-5-4 23:3:24', 'fActWaterLevelMixTank2', '292.511535644531']
['2021-5-4 23:3:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:3:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:3:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:3:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:3:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:3:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:3:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:3:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:3:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:3:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:3:24', 'DoVa_Co2', '0']
['2021-5-4 23:3:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:3:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:3:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:3:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:3:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:4:24', 'fKWhCounter', '3488.65258789063']
['2021-5-4 23:4:24', 'fActPhLevelMixTank1', '5.61070585250854']
['2021-5-4 23:4:24', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 23:4:24', 'fActPhLevelMixTank2', '3.78984951972961']
['2021-5-4 23:4:24', 'fActEcLevelMixTank2', '1031.67822265625']
['2021-5-4 23:4:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:4:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:4:24', 'fActTempValMemo', '21.5']
['2021-5-4 23:4:24', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 23:4:24', 'fActCo2ValMemo', '857']
['2021-5-4 23:4:24', 'fActWaterLevelMixTank1', '281.891052246094']
['2021-5-4 23:4:24', 'fActWaterLevelMixTank2', '291.425048828125']
['2021-5-4 23:4:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:4:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:4:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:4:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:4:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:4:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:4:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:4:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:4:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:4:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:4:24', 'DoVa_Co2', '0']
['2021-5-4 23:4:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:4:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:4:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:4:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:4:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:5:24', 'fKWhCounter', '3488.85278320313']
['2021-5-4 23:5:24', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 23:5:24', 'fActEcLevelMixTank1', '2023.68237304688']
['2021-5-4 23:5:24', 'fActPhLevelMixTank2', '3.79204678535461']
['2021-5-4 23:5:24', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 23:5:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:5:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:5:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:5:24', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 23:5:24', 'fActCo2ValMemo', '856']
['2021-5-4 23:5:24', 'fActWaterLevelMixTank1', '282.298492431641']
['2021-5-4 23:5:24', 'fActWaterLevelMixTank2', '292.511535644531']
['2021-5-4 23:5:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:5:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:5:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:5:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:5:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:5:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:5:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:5:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:5:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:5:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:5:24', 'DoVa_Co2', '0']
['2021-5-4 23:5:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:5:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:5:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:5:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:5:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:6:24', 'fKWhCounter', '3488.95288085938']
['2021-5-4 23:6:24', 'fActPhLevelMixTank1', '5.60997343063354']
['2021-5-4 23:6:24', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 23:6:24', 'fActPhLevelMixTank2', '3.78911709785461']
['2021-5-4 23:6:24', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 23:6:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:6:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:6:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:6:24', 'fActRhValMemo', '51.0999984741211']
['2021-5-4 23:6:24', 'fActCo2ValMemo', '856']
['2021-5-4 23:6:24', 'fActWaterLevelMixTank1', '280.85888671875']
['2021-5-4 23:6:24', 'fActWaterLevelMixTank2', '293.109100341797']
['2021-5-4 23:6:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:6:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:6:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:6:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:6:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:6:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:6:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:6:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:6:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:6:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:6:24', 'DoVa_Co2', '0']
['2021-5-4 23:6:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:6:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:6:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:6:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:6:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:7:25', 'fKWhCounter', '3489.15307617188']
['2021-5-4 23:7:25', 'fActPhLevelMixTank1', '5.60289335250854']
['2021-5-4 23:7:25', 'fActEcLevelMixTank1', '2020.17272949219']
['2021-5-4 23:7:25', 'fActPhLevelMixTank2', '3.79497671127319']
['2021-5-4 23:7:25', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 23:7:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:7:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:7:25', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:7:25', 'fActRhValMemo', '50.7999992370605']
['2021-5-4 23:7:25', 'fActCo2ValMemo', '855']
['2021-5-4 23:7:25', 'fActWaterLevelMixTank1', '282.624420166016']
['2021-5-4 23:7:25', 'fActWaterLevelMixTank2', '293.000457763672']
['2021-5-4 23:7:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:7:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:7:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:7:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:7:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:7:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:7:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:7:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:7:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:7:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:7:25', 'DoVa_Co2', '0']
['2021-5-4 23:7:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:7:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:7:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:7:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']

['2021-5-4 23:7:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:7:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:8:24', 'fKWhCounter', '3489.25317382813']
['2021-5-4 23:8:24', 'fActPhLevelMixTank1', '5.60875272750854']
['2021-5-4 23:8:24', 'fActEcLevelMixTank1', '2021.85119628906']
['2021-5-4 23:8:24', 'fActPhLevelMixTank2', '3.79644155502319']
['2021-5-4 23:8:24', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 23:8:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:8:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:8:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:8:24', 'fActRhValMemo', '51.2000007629395']
['2021-5-4 23:8:24', 'fActCo2ValMemo', '855']
['2021-5-4 23:8:24', 'fActWaterLevelMixTank1', '283.222015380859']
['2021-5-4 23:8:24', 'fActWaterLevelMixTank2', '293.000457763672']
['2021-5-4 23:8:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:8:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:8:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:8:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:8:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:8:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:8:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:8:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:8:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:8:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:8:24', 'DoVa_Co2', '0']
['2021-5-4 23:8:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:8:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:8:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:8:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:8:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:9:24', 'fKWhCounter', '3489.45336914063']
['2021-5-4 23:9:24', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 23:9:24', 'fActEcLevelMixTank1', '2018.79943847656']
['2021-5-4 23:9:24', 'fActPhLevelMixTank2', '3.79400014877319']
['2021-5-4 23:9:24', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 23:9:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:9:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:9:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:9:25', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 23:9:25', 'fActCo2ValMemo', '853']
['2021-5-4 23:9:25', 'fActWaterLevelMixTank1', '283.222015380859']
['2021-5-4 23:9:25', 'fActWaterLevelMixTank2', '292.891815185547']
['2021-5-4 23:9:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:9:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:9:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:9:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:9:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:9:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:9:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:9:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:9:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:9:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:9:25', 'DoVa_Co2', '0']
['2021-5-4 23:9:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:9:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:9:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:9:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:9:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:10:24', 'fKWhCounter', '3489.55346679688']
['2021-5-4 23:10:24', 'fActPhLevelMixTank1', '5.60972929000854']
['2021-5-4 23:10:24', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 23:10:24', 'fActPhLevelMixTank2', '3.79766225814819']
['2021-5-4 23:10:24', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 23:10:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:10:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:10:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:10:24', 'fActRhValMemo', '50.7000007629395']
['2021-5-4 23:10:24', 'fActCo2ValMemo', '855']
['2021-5-4 23:10:24', 'fActWaterLevelMixTank1', '282.705932617188']
['2021-5-4 23:10:24', 'fActWaterLevelMixTank2', '292.918975830078']
['2021-5-4 23:10:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:10:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:10:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:10:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:10:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:10:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:10:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:10:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:10:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:10:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:10:24', 'DoVa_Co2', '0']
['2021-5-4 23:10:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:10:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:10:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:10:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:10:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:11:25', 'fKWhCounter', '3489.75366210938']
['2021-5-4 23:11:25', 'fActPhLevelMixTank1', '5.60191679000854']
['2021-5-4 23:11:25', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 23:11:25', 'fActPhLevelMixTank2', '3.79448843002319']
['2021-5-4 23:11:25', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 23:11:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:11:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:11:25', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:11:25', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 23:11:25', 'fActCo2ValMemo', '855']
['2021-5-4 23:11:25', 'fActWaterLevelMixTank1', '283.439300537109']
['2021-5-4 23:11:25', 'fActWaterLevelMixTank2', '293.000457763672']
['2021-5-4 23:11:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:11:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:11:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:11:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:11:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:11:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:11:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:11:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:11:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:11:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:11:25', 'DoVa_Co2', '0']
['2021-5-4 23:11:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:11:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:11:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:11:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:11:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:12:24', 'fKWhCounter', '3489.85375976563']
['2021-5-4 23:12:24', 'fActPhLevelMixTank1', '5.60606718063354']
['2021-5-4 23:12:24', 'fActEcLevelMixTank1', '2015.90014648438']
['2021-5-4 23:12:24', 'fActPhLevelMixTank2', '3.79937124252319']
['2021-5-4 23:12:24', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 23:12:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:12:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:12:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:12:24', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 23:12:24', 'fActCo2ValMemo', '854']
['2021-5-4 23:12:24', 'fActWaterLevelMixTank1', '282.733093261719']
['2021-5-4 23:12:24', 'fActWaterLevelMixTank2', '293.543701171875']
['2021-5-4 23:12:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:12:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:12:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:12:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:12:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:12:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:12:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:12:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:12:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:12:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:12:24', 'DoVa_Co2', '0']
['2021-5-4 23:12:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:12:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:12:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:12:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_4_Blue', '0']

['2021-5-4 23:12:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:12:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:13:24', 'fKWhCounter', '3489.95385742188']
['2021-5-4 23:13:24', 'fActPhLevelMixTank1', '5.59923076629639']
['2021-5-4 23:13:24', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 23:13:24', 'fActPhLevelMixTank2', '3.79937124252319']
['2021-5-4 23:13:24', 'fActEcLevelMixTank2', '1032.44116210938']
['2021-5-4 23:13:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:13:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:13:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:13:24', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 23:13:24', 'fActCo2ValMemo', '853']
['2021-5-4 23:13:24', 'fActWaterLevelMixTank1', '282.923217773438']
['2021-5-4 23:13:24', 'fActWaterLevelMixTank2', '293.842498779297']
['2021-5-4 23:13:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:13:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:13:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:13:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:13:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:13:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:13:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:13:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:13:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:13:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:13:24', 'DoVa_Co2', '0']
['2021-5-4 23:13:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:13:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:13:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:13:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:13:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:14:24', 'fKWhCounter', '3490.15405273438']
['2021-5-4 23:14:24', 'fActPhLevelMixTank1', '5.60899686813354']
['2021-5-4 23:14:24', 'fActEcLevelMixTank1', '2051.75927734375']
['2021-5-4 23:14:24', 'fActPhLevelMixTank2', '3.79351186752319']
['2021-5-4 23:14:24', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 23:14:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:14:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:14:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:14:24', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 23:14:24', 'fActCo2ValMemo', '851']
['2021-5-4 23:14:24', 'fActWaterLevelMixTank1', '283.357818603516']
['2021-5-4 23:14:24', 'fActWaterLevelMixTank2', '293.380737304688']
['2021-5-4 23:14:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:14:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:14:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:14:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:14:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:14:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:14:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:14:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:14:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:14:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:14:24', 'DoVa_Co2', '0']
['2021-5-4 23:14:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:14:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:14:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:14:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:14:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:15:24', 'fKWhCounter', '3490.25415039063']
['2021-5-4 23:15:24', 'fActPhLevelMixTank1', '5.60435819625854']
['2021-5-4 23:15:24', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 23:15:24', 'fActPhLevelMixTank2', '3.79302358627319']
['2021-5-4 23:15:24', 'fActEcLevelMixTank2', '1032.74633789063']
['2021-5-4 23:15:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:15:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:15:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:15:24', 'fActRhValMemo', '50.2999992370605']
['2021-5-4 23:15:24', 'fActCo2ValMemo', '850']
['2021-5-4 23:15:24', 'fActWaterLevelMixTank1', '283.738098144531']
['2021-5-4 23:15:24', 'fActWaterLevelMixTank2', '293.733825683594']
['2021-5-4 23:15:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:15:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:15:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:15:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:15:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:15:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:15:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:15:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:15:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:15:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:15:24', 'DoVa_Co2', '0']
['2021-5-4 23:15:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:15:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:15:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:15:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:15:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:16:24', 'fKWhCounter', '3490.35424804688']
['2021-5-4 23:16:24', 'fActPhLevelMixTank1', '5.61094999313354']
['2021-5-4 23:16:24', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 23:16:24', 'fActPhLevelMixTank2', '3.79570913314819']
['2021-5-4 23:16:24', 'fActEcLevelMixTank2', '1033.96704101563']
['2021-5-4 23:16:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:16:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:16:24', 'fActTempValMemo', '21.3999996185303']
['2021-5-4 23:16:24', 'fActRhValMemo', '52.5999984741211']
['2021-5-4 23:16:24', 'fActCo2ValMemo', '849']
['2021-5-4 23:16:24', 'fActWaterLevelMixTank1', '284.064025878906']
['2021-5-4 23:16:24', 'fActWaterLevelMixTank2', '293.760986328125']
['2021-5-4 23:16:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:16:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:16:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:16:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:16:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:16:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:16:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:16:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:16:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:16:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:16:24', 'DoVa_Co2', '0']
['2021-5-4 23:16:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:16:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:16:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:16:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:16:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:17:25', 'fKWhCounter', '3490.45434570313']
['2021-5-4 23:17:25', 'fActPhLevelMixTank1', '5.60411405563354']
['2021-5-4 23:17:25', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 23:17:25', 'fActPhLevelMixTank2', '3.79277920722961']
['2021-5-4 23:17:25', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 23:17:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:17:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:17:25', 'fActTempValMemo', '21.6000003814697']
['2021-5-4 23:17:25', 'fActRhValMemo', '63.0999984741211']
['2021-5-4 23:17:25', 'fActCo2ValMemo', '850']
['2021-5-4 23:17:25', 'fActWaterLevelMixTank1', '284.498626708984']
['2021-5-4 23:17:25', 'fActWaterLevelMixTank2', '293.543701171875']
['2021-5-4 23:17:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:17:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:17:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:17:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:17:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:17:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:17:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:17:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:17:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:17:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:17:25', 'DoVa_Co2', '0']
['2021-5-4 23:17:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:17:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:17:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:17:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_1_Fred', '0']

['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:17:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:18:24', 'fKWhCounter', '3490.55444335938']
['2021-5-4 23:18:24', 'fActPhLevelMixTank1', '5.61119413375854']
['2021-5-4 23:18:24', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 23:18:24', 'fActPhLevelMixTank2', '3.79863882064819']
['2021-5-4 23:18:24', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 23:18:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:18:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:18:24', 'fActTempValMemo', '21.8999996185303']
['2021-5-4 23:18:24', 'fActRhValMemo', '68.1999969482422']
['2021-5-4 23:18:24', 'fActCo2ValMemo', '850']
['2021-5-4 23:18:24', 'fActWaterLevelMixTank1', '282.814575195313']
['2021-5-4 23:18:24', 'fActWaterLevelMixTank2', '293.978302001953']
['2021-5-4 23:18:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:18:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:18:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:18:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:18:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:18:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:18:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:18:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:18:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:18:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:18:24', 'DoVa_Co2', '0']
['2021-5-4 23:18:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:18:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:18:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:18:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:18:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:19:25', 'fKWhCounter', '3490.75463867188']
['2021-5-4 23:19:25', 'fActPhLevelMixTank1', '5.60679960250854']
['2021-5-4 23:19:25', 'fActEcLevelMixTank1', '2027.19201660156']
['2021-5-4 23:19:25', 'fActPhLevelMixTank2', '3.79937124252319']
['2021-5-4 23:19:25', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 23:19:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:19:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:19:25', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 23:19:25', 'fActRhValMemo', '71.5999984741211']
['2021-5-4 23:19:25', 'fActCo2ValMemo', '850']
['2021-5-4 23:19:25', 'fActWaterLevelMixTank1', '284.036865234375']
['2021-5-4 23:19:25', 'fActWaterLevelMixTank2', '293.380737304688']
['2021-5-4 23:19:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:19:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:19:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:19:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:19:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:19:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:19:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:19:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:19:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:19:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:19:25', 'DoVa_Co2', '0']
['2021-5-4 23:19:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:19:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:19:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:19:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:19:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:20:24', 'fKWhCounter', '3490.85473632813']
['2021-5-4 23:20:24', 'fActPhLevelMixTank1', '5.61387968063354']
['2021-5-4 23:20:24', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 23:20:24', 'fActPhLevelMixTank2', '3.79815053939819']
['2021-5-4 23:20:24', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 23:20:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:20:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:20:24', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 23:20:24', 'fActRhValMemo', '73.4000015258789']
['2021-5-4 23:20:24', 'fActCo2ValMemo', '848']
['2021-5-4 23:20:24', 'fActWaterLevelMixTank1', '284.118347167969']
['2021-5-4 23:20:24', 'fActWaterLevelMixTank2', '293.65234375']
['2021-5-4 23:20:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:20:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:20:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:20:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:20:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:20:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:20:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:20:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:20:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:20:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:20:24', 'DoVa_Co2', '0']
['2021-5-4 23:20:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:20:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:20:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:20:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:20:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:21:25', 'fKWhCounter', '3490.95483398438']
['2021-5-4 23:21:25', 'fActPhLevelMixTank1', '5.61412382125854']
['2021-5-4 23:21:25', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 23:21:25', 'fActPhLevelMixTank2', '3.80864906311035']
['2021-5-4 23:21:25', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 23:21:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:21:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:21:25', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:21:25', 'fActRhValMemo', '73.5999984741211']
['2021-5-4 23:21:25', 'fActCo2ValMemo', '850']
['2021-5-4 23:21:25', 'fActWaterLevelMixTank1', '284.471466064453']
['2021-5-4 23:21:25', 'fActWaterLevelMixTank2', '293.788177490234']
['2021-5-4 23:21:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:21:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:21:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:21:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:21:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:21:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:21:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:21:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:21:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:21:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:21:25', 'DoVa_Co2', '0']
['2021-5-4 23:21:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:21:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:21:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:21:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:21:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:22:24', 'fKWhCounter', '3491.15502929688']
['2021-5-4 23:22:24', 'fActPhLevelMixTank1', '5.6202278137207']
['2021-5-4 23:22:24', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 23:22:24', 'fActPhLevelMixTank2', '3.81255531311035']
['2021-5-4 23:22:24', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 23:22:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:22:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:22:24', 'fActTempValMemo', '22.7999992370605']
['2021-5-4 23:22:24', 'fActRhValMemo', '68.6999969482422']
['2021-5-4 23:22:24', 'fActCo2ValMemo', '849']
['2021-5-4 23:22:24', 'fActWaterLevelMixTank1', '284.607269287109']
['2021-5-4 23:22:24', 'fActWaterLevelMixTank2', '293.43505859375']
['2021-5-4 23:22:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:22:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:22:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:22:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:22:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:22:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:22:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:22:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:22:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:22:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:22:24', 'DoVa_Co2', '0']
['2021-5-4 23:22:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:22:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:22:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:22:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_2_White', '0']

['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:22:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:23:24', 'fKWhCounter', '3491.25512695313']
['2021-5-4 23:23:24', 'fActPhLevelMixTank1', '5.6214485168457']
['2021-5-4 23:23:24', 'fActEcLevelMixTank1', '2023.52978515625']
['2021-5-4 23:23:24', 'fActPhLevelMixTank2', '3.81304359436035']
['2021-5-4 23:23:24', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 23:23:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:23:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:23:24', 'fActTempValMemo', '22.7999992370605']
['2021-5-4 23:23:24', 'fActRhValMemo', '62.9000015258789']
['2021-5-4 23:23:24', 'fActCo2ValMemo', '847']
['2021-5-4 23:23:24', 'fActWaterLevelMixTank1', '283.982543945313']
['2021-5-4 23:23:24', 'fActWaterLevelMixTank2', '294.3857421875']
['2021-5-4 23:23:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:23:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:23:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:23:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:23:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:23:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:23:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:23:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:23:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:23:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:23:24', 'DoVa_Co2', '0']
['2021-5-4 23:23:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:23:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:23:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:23:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:23:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:24:24', 'fKWhCounter', '3491.45532226563']
['2021-5-4 23:24:24', 'fActPhLevelMixTank1', '5.63316774368286']
['2021-5-4 23:24:24', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 23:24:24', 'fActPhLevelMixTank2', '3.82061219215393']
['2021-5-4 23:24:24', 'fActEcLevelMixTank2', '1036.56115722656']
['2021-5-4 23:24:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:24:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:24:24', 'fActTempValMemo', '22.7999992370605']
['2021-5-4 23:24:24', 'fActRhValMemo', '60.0999984741211']
['2021-5-4 23:24:24', 'fActCo2ValMemo', '843']
['2021-5-4 23:24:24', 'fActWaterLevelMixTank1', '284.335662841797']
['2021-5-4 23:24:24', 'fActWaterLevelMixTank2', '294.60302734375']
['2021-5-4 23:24:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:24:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:24:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:24:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:24:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:24:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:24:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:24:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:24:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:24:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:24:24', 'DoVa_Co2', '0']
['2021-5-4 23:24:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:24:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:24:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:24:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:24:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:25:25', 'fKWhCounter', '3491.55541992188']
['2021-5-4 23:25:25', 'fActPhLevelMixTank1', '5.63780641555786']
['2021-5-4 23:25:25', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 23:25:25', 'fActPhLevelMixTank2', '3.81841492652893']
['2021-5-4 23:25:25', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 23:25:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:25:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:25:25', 'fActTempValMemo', '22.7999992370605']
['2021-5-4 23:25:25', 'fActRhValMemo', '56.5999984741211']
['2021-5-4 23:25:25', 'fActCo2ValMemo', '842']
['2021-5-4 23:25:25', 'fActWaterLevelMixTank1', '283.031860351563']
['2021-5-4 23:25:25', 'fActWaterLevelMixTank2', '293.978302001953']
['2021-5-4 23:25:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:25:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:25:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:25:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:25:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:25:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:25:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:25:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:25:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:25:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:25:25', 'DoVa_Co2', '0']
['2021-5-4 23:25:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:25:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:25:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:25:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:25:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:26:24', 'fKWhCounter', '3491.75561523438']
['2021-5-4 23:26:24', 'fActPhLevelMixTank1', '5.64513063430786']
['2021-5-4 23:26:24', 'fActEcLevelMixTank1', '2024.4453125']
['2021-5-4 23:26:24', 'fActPhLevelMixTank2', '3.82598352432251']
['2021-5-4 23:26:24', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 23:26:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:26:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:26:24', 'fActTempValMemo', '22.7999992370605']
['2021-5-4 23:26:24', 'fActRhValMemo', '53.7000007629395']
['2021-5-4 23:26:24', 'fActCo2ValMemo', '842']
['2021-5-4 23:26:24', 'fActWaterLevelMixTank1', '283.493621826172']
['2021-5-4 23:26:24', 'fActWaterLevelMixTank2', '294.467224121094']
['2021-5-4 23:26:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:26:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:26:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:26:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:26:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:26:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:26:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:26:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:26:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:26:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:26:24', 'DoVa_Co2', '0']
['2021-5-4 23:26:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:26:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:26:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:26:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:26:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:27:24', 'fKWhCounter', '3491.85571289063']
['2021-5-4 23:27:24', 'fActPhLevelMixTank1', '5.64293336868286']
['2021-5-4 23:27:24', 'fActEcLevelMixTank1', '2025.0556640625']
['2021-5-4 23:27:24', 'fActPhLevelMixTank2', '3.82207703590393']
['2021-5-4 23:27:24', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 23:27:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:27:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:27:24', 'fActTempValMemo', '22.7999992370605']
['2021-5-4 23:27:24', 'fActRhValMemo', '52.5']
['2021-5-4 23:27:24', 'fActCo2ValMemo', '842']
['2021-5-4 23:27:24', 'fActWaterLevelMixTank1', '284.906066894531']
['2021-5-4 23:27:24', 'fActWaterLevelMixTank2', '294.222747802734']
['2021-5-4 23:27:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:27:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:27:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:27:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:27:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:27:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:27:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:27:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:27:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:27:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:27:24', 'DoVa_Co2', '0']
['2021-5-4 23:27:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:27:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:27:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:27:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:27:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:28:24', 'fKWhCounter', '3492.05590820313']
['2021-5-4 23:28:24', 'fActPhLevelMixTank1', '5.65343189239502']
['2021-5-4 23:28:24', 'fActEcLevelMixTank1', '2025.97119140625']
['2021-5-4 23:28:24', 'fActPhLevelMixTank2', '3.82500696182251']
['2021-5-4 23:28:24', 'fActEcLevelMixTank2', '1037.78186035156']

['2021-5-4 23:28:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:28:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:28:24', 'fActTempValMemo', '22.7000007629395']
['2021-5-4 23:28:24', 'fActRhValMemo', '54.4000015258789']
['2021-5-4 23:28:24', 'fActCo2ValMemo', '843']
['2021-5-4 23:28:24', 'fActWaterLevelMixTank1', '285.123382568359']
['2021-5-4 23:28:24', 'fActWaterLevelMixTank2', '294.222747802734']
['2021-5-4 23:28:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:28:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:28:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:28:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:28:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:28:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:28:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:28:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:28:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:28:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:28:24', 'DoVa_Co2', '0']
['2021-5-4 23:28:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:28:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:28:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:28:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:28:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:29:25', 'fKWhCounter', '3492.15600585938']
['2021-5-4 23:29:25', 'fActPhLevelMixTank1', '5.65050220489502']
['2021-5-4 23:29:25', 'fActEcLevelMixTank1', '2025.51342773438']
['2021-5-4 23:29:25', 'fActPhLevelMixTank2', '3.81963562965393']
['2021-5-4 23:29:25', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 23:29:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:29:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:29:25', 'fActTempValMemo', '22.7000007629395']
['2021-5-4 23:29:25', 'fActRhValMemo', '55.0999984741211']
['2021-5-4 23:29:25', 'fActCo2ValMemo', '838']
['2021-5-4 23:29:25', 'fActWaterLevelMixTank1', '285.394989013672']
['2021-5-4 23:29:25', 'fActWaterLevelMixTank2', '294.820343017578']
['2021-5-4 23:29:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:29:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:29:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:29:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:29:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:29:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:29:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:29:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:29:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:29:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:29:25', 'DoVa_Co2', '0']
['2021-5-4 23:29:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:29:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:29:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:29:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:29:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:30:24', 'fKWhCounter', '3492.35620117188']
['2021-5-4 23:30:24', 'fActPhLevelMixTank1', '5.66563940048218']
['2021-5-4 23:30:24', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 23:30:24', 'fActPhLevelMixTank2', '3.81572914123535']
['2021-5-4 23:30:24', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 23:30:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:30:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:30:24', 'fActTempValMemo', '22.7000007629395']
['2021-5-4 23:30:24', 'fActRhValMemo', '55.5']
['2021-5-4 23:30:24', 'fActCo2ValMemo', '835']
['2021-5-4 23:30:24', 'fActWaterLevelMixTank1', '285.204864501953']
['2021-5-4 23:30:24', 'fActWaterLevelMixTank2', '294.331420898438']
['2021-5-4 23:30:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:30:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:30:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:30:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:30:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:30:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:30:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:30:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:30:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:30:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:30:24', 'DoVa_Co2', '0']
['2021-5-4 23:30:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:30:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:30:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:30:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:30:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:31:25', 'fKWhCounter', '3492.45629882813']
['2021-5-4 23:31:25', 'fActPhLevelMixTank1', '5.65782642364502']
['2021-5-4 23:31:25', 'fActEcLevelMixTank1', '2026.58166503906']
['2021-5-4 23:31:25', 'fActPhLevelMixTank2', '3.82207703590393']
['2021-5-4 23:31:25', 'fActEcLevelMixTank2', '1036.10339355469']
['2021-5-4 23:31:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:31:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:31:25', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:31:25', 'fActRhValMemo', '55.7000007629395']
['2021-5-4 23:31:25', 'fActCo2ValMemo', '831']
['2021-5-4 23:31:25', 'fActWaterLevelMixTank1', '286.128387451172']
['2021-5-4 23:31:25', 'fActWaterLevelMixTank2', '294.630187988281']
['2021-5-4 23:31:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:31:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:31:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:31:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:31:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:31:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:31:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:31:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:31:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:31:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:31:25', 'DoVa_Co2', '0']
['2021-5-4 23:31:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:31:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:31:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:31:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:31:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:32:24', 'fKWhCounter', '3492.55639648438']
['2021-5-4 23:32:24', 'fActPhLevelMixTank1', '5.66686010360718']
['2021-5-4 23:32:24', 'fActEcLevelMixTank1', '2026.42907714844']
['2021-5-4 23:32:24', 'fActPhLevelMixTank2', '3.82305359840393']
['2021-5-4 23:32:24', 'fActEcLevelMixTank2', '1035.95080566406']
['2021-5-4 23:32:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:32:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:32:24', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:32:24', 'fActRhValMemo', '55.5']
['2021-5-4 23:32:24', 'fActCo2ValMemo', '829']
['2021-5-4 23:32:24', 'fActWaterLevelMixTank1', '284.064025878906']
['2021-5-4 23:32:24', 'fActWaterLevelMixTank2', '295.119110107422']
['2021-5-4 23:32:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:32:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:32:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:32:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:32:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:32:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:32:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:32:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:32:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:32:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:32:24', 'DoVa_Co2', '0']
['2021-5-4 23:32:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:32:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:32:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:32:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:32:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:33:25', 'fKWhCounter', '3492.75659179688']
['2021-5-4 23:33:25', 'fActPhLevelMixTank1', '5.66270923614502']
['2021-5-4 23:33:25', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 23:33:25', 'fActPhLevelMixTank2', '3.82793664932251']
['2021-5-4 23:33:25', 'fActEcLevelMixTank2', '1037.93444824219']
['2021-5-4 23:33:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:33:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:33:25', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:33:25', 'fActRhValMemo', '55.2000007629395']
['2021-5-4 23:33:25', 'fActCo2ValMemo', '827']
['2021-5-4 23:33:25', 'fActWaterLevelMixTank1', '286.019714355469']
['2021-5-4 23:33:25', 'fActWaterLevelMixTank2', '295.254943847656']
['2021-5-4 23:33:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:33:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:33:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:33:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:33:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:33:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:33:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:33:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:33:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:33:25', 'DoVa_IrrigateLevel_2_MT2', '0']

['2021-5-4 23:33:25', 'DoVa_Co2', '0']
['2021-5-4 23:33:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:33:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:33:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:33:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:33:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:34:24', 'fKWhCounter', '3492.85668945313']
['2021-5-4 23:34:24', 'fActPhLevelMixTank1', '5.67418432235718']
['2021-5-4 23:34:24', 'fActEcLevelMixTank1', '2027.80236816406']
['2021-5-4 23:34:24', 'fActPhLevelMixTank2', '3.82598352432251']
['2021-5-4 23:34:24', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 23:34:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:34:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:34:24', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:34:24', 'fActRhValMemo', '54.5999984741211']
['2021-5-4 23:34:24', 'fActCo2ValMemo', '828']
['2021-5-4 23:34:24', 'fActWaterLevelMixTank1', '285.286346435547']
['2021-5-4 23:34:24', 'fActWaterLevelMixTank2', '295.037628173828']
['2021-5-4 23:34:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:34:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:34:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:34:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:34:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:34:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:34:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:34:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:34:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:34:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:34:24', 'DoVa_Co2', '0']
['2021-5-4 23:34:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:34:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:34:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:34:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:34:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:35:25', 'fKWhCounter', '3493.05688476563']
['2021-5-4 23:35:25', 'fActPhLevelMixTank1', '5.67223119735718']
['2021-5-4 23:35:25', 'fActEcLevelMixTank1', '2029.48083496094']
['2021-5-4 23:35:25', 'fActPhLevelMixTank2', '3.82866907119751']
['2021-5-4 23:35:25', 'fActEcLevelMixTank2', '1038.69750976563']
['2021-5-4 23:35:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:35:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:35:25', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:35:25', 'fActRhValMemo', '53.7000007629395']
['2021-5-4 23:35:25', 'fActCo2ValMemo', '827']
['2021-5-4 23:35:25', 'fActWaterLevelMixTank1', '286.209869384766']
['2021-5-4 23:35:25', 'fActWaterLevelMixTank2', '295.010467529297']
['2021-5-4 23:35:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:35:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:35:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:35:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:35:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:35:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:35:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:35:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:35:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:35:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:35:25', 'DoVa_Co2', '0']
['2021-5-4 23:35:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:35:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:35:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:35:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:35:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:36:24', 'fKWhCounter', '3493.15698242188']
['2021-5-4 23:36:24', 'fActPhLevelMixTank1', '5.66954565048218']
['2021-5-4 23:36:24', 'fActEcLevelMixTank1', '2032.99047851563']
['2021-5-4 23:36:24', 'fActPhLevelMixTank2', '3.82720422744751']
['2021-5-4 23:36:24', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 23:36:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:36:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:36:24', 'fActTempValMemo', '22.7000007629395']
['2021-5-4 23:36:24', 'fActRhValMemo', '53.5999984741211']
['2021-5-4 23:36:24', 'fActCo2ValMemo', '827']
['2021-5-4 23:36:24', 'fActWaterLevelMixTank1', '286.644470214844']
['2021-5-4 23:36:24', 'fActWaterLevelMixTank2', '295.227783203125']
['2021-5-4 23:36:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:36:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:36:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:36:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:36:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:36:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:36:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:36:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:36:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:36:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:36:24', 'DoVa_Co2', '0']
['2021-5-4 23:36:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:36:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:36:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:36:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:36:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:37:25', 'fKWhCounter', '3493.35717773438']
['2021-5-4 23:37:25', 'fActPhLevelMixTank1', '5.67247533798218']
['2021-5-4 23:37:25', 'fActEcLevelMixTank1', '2030.85424804688']
['2021-5-4 23:37:25', 'fActPhLevelMixTank2', '3.82671594619751']
['2021-5-4 23:37:25', 'fActEcLevelMixTank2', '1036.86633300781']
['2021-5-4 23:37:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:37:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:37:25', 'fActTempValMemo', '22.7000007629395']
['2021-5-4 23:37:25', 'fActRhValMemo', '53']
['2021-5-4 23:37:25', 'fActCo2ValMemo', '824']
['2021-5-4 23:37:25', 'fActWaterLevelMixTank1', '286.454315185547']
['2021-5-4 23:37:25', 'fActWaterLevelMixTank2', '295.662353515625']
['2021-5-4 23:37:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:37:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:37:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:37:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:37:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:37:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:37:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:37:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:37:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:37:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:37:25', 'DoVa_Co2', '0']
['2021-5-4 23:37:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:37:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:37:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:37:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:37:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:38:24', 'fKWhCounter', '3493.45727539063']
['2021-5-4 23:38:24', 'fActPhLevelMixTank1', '5.67540502548218']
['2021-5-4 23:38:24', 'fActEcLevelMixTank1', '2031.0068359375']
['2021-5-4 23:38:24', 'fActPhLevelMixTank2', '3.83672595024109']
['2021-5-4 23:38:24', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 23:38:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:38:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:38:24', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:38:24', 'fActRhValMemo', '52.5']
['2021-5-4 23:38:24', 'fActCo2ValMemo', '821']
['2021-5-4 23:38:24', 'fActWaterLevelMixTank1', '286.725952148438']
['2021-5-4 23:38:24', 'fActWaterLevelMixTank2', '295.254943847656']
['2021-5-4 23:38:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:38:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:38:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:38:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:38:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:38:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:38:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:38:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:38:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:38:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:38:24', 'DoVa_Co2', '0']
['2021-5-4 23:38:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:38:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:38:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:38:24', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:38:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:39:25', 'fKWhCounter', '3493.65747070313']
['2021-5-4 23:39:25', 'fActPhLevelMixTank1', '5.67980003356934']
['2021-5-4 23:39:25', 'fActEcLevelMixTank1', '2032.68530273438']
['2021-5-4 23:39:25', 'fActPhLevelMixTank2', '3.83257555961609']
['2021-5-4 23:39:25', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 23:39:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:39:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:39:25', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:39:25', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 23:39:25', 'fActCo2ValMemo', '821']
['2021-5-4 23:39:25', 'fActWaterLevelMixTank1', '285.911071777344']
['2021-5-4 23:39:25', 'fActWaterLevelMixTank2', '295.445068359375']
['2021-5-4 23:39:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:39:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:39:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:39:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:39:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:39:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:39:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:39:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:39:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:39:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:39:25', 'DoVa_Co2', '0']
['2021-5-4 23:39:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:39:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:39:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:39:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:39:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:40:24', 'fKWhCounter', '3493.75756835938']
['2021-5-4 23:40:24', 'fActPhLevelMixTank1', '5.67125463485718']
['2021-5-4 23:40:24', 'fActEcLevelMixTank1', '2031.0068359375']
['2021-5-4 23:40:24', 'fActPhLevelMixTank2', '3.84112071990967']
['2021-5-4 23:40:24', 'fActEcLevelMixTank2', '1036.71374511719']
['2021-5-4 23:40:24', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:40:24', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:40:24', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:40:24', 'fActRhValMemo', '52.2000007629395']
['2021-5-4 23:40:24', 'fActCo2ValMemo', '821']
['2021-5-4 23:40:24', 'fActWaterLevelMixTank1', '286.454315185547']
['2021-5-4 23:40:24', 'fActWaterLevelMixTank2', '295.879669189453']
['2021-5-4 23:40:24', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:40:24', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:40:24', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:40:24', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:40:24', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:40:24', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:40:24', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:40:24', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:40:24', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:40:24', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:40:24', 'DoVa_Co2', '0']
['2021-5-4 23:40:24', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:40:24', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:40:24', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:40:24', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:40:24', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:41:25', 'fKWhCounter', '3493.85766601563']
['2021-5-4 23:41:25', 'fActPhLevelMixTank1', '5.68102073669434']
['2021-5-4 23:41:25', 'fActEcLevelMixTank1', '2033.90600585938']
['2021-5-4 23:41:25', 'fActPhLevelMixTank2', '3.83477282524109']
['2021-5-4 23:41:25', 'fActEcLevelMixTank2', '1039.00268554688']
['2021-5-4 23:41:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:41:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:41:25', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:41:25', 'fActRhValMemo', '52.0999984741211']
['2021-5-4 23:41:25', 'fActCo2ValMemo', '822']
['2021-5-4 23:41:25', 'fActWaterLevelMixTank1', '286.888916015625']
['2021-5-4 23:41:25', 'fActWaterLevelMixTank2', '296.368591308594']
['2021-5-4 23:41:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:41:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:41:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:41:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:41:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:41:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:41:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:41:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:41:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:41:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:41:25', 'DoVa_Co2', '0']
['2021-5-4 23:41:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:41:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:41:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:41:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:41:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:42:25', 'fKWhCounter', '3494.05786132813']
['2021-5-4 23:42:25', 'fActPhLevelMixTank1', '5.68102073669434']
['2021-5-4 23:42:25', 'fActEcLevelMixTank1', '2034.51647949219']
['2021-5-4 23:42:25', 'fActPhLevelMixTank2', '3.84209728240967']
['2021-5-4 23:42:25', 'fActEcLevelMixTank2', '1040.83374023438']
['2021-5-4 23:42:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:42:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:42:25', 'fActTempValMemo', '22.5']
['2021-5-4 23:42:25', 'fActRhValMemo', '51.4000015258789']
['2021-5-4 23:42:25', 'fActCo2ValMemo', '820']
['2021-5-4 23:42:25', 'fActWaterLevelMixTank1', '286.535797119141']
['2021-5-4 23:42:25', 'fActWaterLevelMixTank2', '296.205627441406']
['2021-5-4 23:42:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:42:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:42:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:42:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:42:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:42:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:42:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:42:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:42:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:42:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:42:25', 'DoVa_Co2', '0']
['2021-5-4 23:42:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:42:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:42:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:42:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:42:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:43:25', 'fKWhCounter', '3494.15795898438']
['2021-5-4 23:43:25', 'fActPhLevelMixTank1', '5.68028831481934']
['2021-5-4 23:43:25', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 23:43:25', 'fActPhLevelMixTank2', '3.83867907524109']
['2021-5-4 23:43:25', 'fActEcLevelMixTank2', '1038.08715820313']
['2021-5-4 23:43:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:43:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:43:25', 'fActTempValMemo', '22.5']
['2021-5-4 23:43:25', 'fActRhValMemo', '51.2999992370605']
['2021-5-4 23:43:25', 'fActCo2ValMemo', '822']
['2021-5-4 23:43:25', 'fActWaterLevelMixTank1', '286.454315185547']
['2021-5-4 23:43:25', 'fActWaterLevelMixTank2', '295.988311767578']
['2021-5-4 23:43:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:43:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:43:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:43:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:43:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:43:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:43:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:43:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:43:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:43:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:43:25', 'DoVa_Co2', '0']
['2021-5-4 23:43:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:43:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:43:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:43:25', 'DoVa_IrrigateLevel_4_MT2', '0']

['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:43:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:44:25', 'fKWhCounter', '3494.35815429688']
['2021-5-4 23:44:25', 'fActPhLevelMixTank1', '5.59483623504639']
['2021-5-4 23:44:25', 'fActEcLevelMixTank1', '2023.8349609375']
['2021-5-4 23:44:25', 'fActPhLevelMixTank2', '3.73564863204956']
['2021-5-4 23:44:25', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 23:44:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:44:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:44:25', 'fActTempValMemo', '22.5']
['2021-5-4 23:44:25', 'fActRhValMemo', '51']
['2021-5-4 23:44:25', 'fActCo2ValMemo', '824']
['2021-5-4 23:44:25', 'fActWaterLevelMixTank1', '286.888916015625']
['2021-5-4 23:44:25', 'fActWaterLevelMixTank2', '304.10986328125']
['2021-5-4 23:44:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:44:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:44:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:44:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:44:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:44:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:44:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:44:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:44:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:44:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:44:25', 'DoVa_Co2', '0']
['2021-5-4 23:44:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:44:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:44:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:44:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:44:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:45:25', 'fKWhCounter', '3494.55834960938']
['2021-5-4 23:45:25', 'fActPhLevelMixTank1', '5.57432794570923']
['2021-5-4 23:45:25', 'fActEcLevelMixTank1', '2025.81860351563']
['2021-5-4 23:45:25', 'fActPhLevelMixTank2', '3.72905659675598']
['2021-5-4 23:45:25', 'fActEcLevelMixTank2', '1035.64562988281']
['2021-5-4 23:45:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:45:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:45:25', 'fActTempValMemo', '22.5']
['2021-5-4 23:45:25', 'fActRhValMemo', '50.9000015258789']
['2021-5-4 23:45:25', 'fActCo2ValMemo', '821']
['2021-5-4 23:45:25', 'fActWaterLevelMixTank1', '281.021850585938']
['2021-5-4 23:45:25', 'fActWaterLevelMixTank2', '286.074066162109']
['2021-5-4 23:45:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:45:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:45:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:45:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:45:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:45:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:45:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:45:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:45:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:45:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:45:25', 'DoVa_Co2', '0']
['2021-5-4 23:45:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:45:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:45:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:45:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:45:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:46:25', 'fKWhCounter', '3494.65844726563']
['2021-5-4 23:46:25', 'fActPhLevelMixTank1', '5.57799005508423']
['2021-5-4 23:46:25', 'fActEcLevelMixTank1', '2028.26013183594']
['2021-5-4 23:46:25', 'fActPhLevelMixTank2', '3.73833441734314']
['2021-5-4 23:46:25', 'fActEcLevelMixTank2', '1033.35668945313']
['2021-5-4 23:46:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:46:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:46:25', 'fActTempValMemo', '22.5']
['2021-5-4 23:46:25', 'fActRhValMemo', '50.5999984741211']
['2021-5-4 23:46:25', 'fActCo2ValMemo', '819']
['2021-5-4 23:46:25', 'fActWaterLevelMixTank1', '278.305603027344']
['2021-5-4 23:46:25', 'fActWaterLevelMixTank2', '277.517913818359']
['2021-5-4 23:46:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:46:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:46:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:46:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:46:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:46:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:46:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:46:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:46:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:46:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:46:25', 'DoVa_Co2', '0']
['2021-5-4 23:46:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:46:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:46:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:46:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:46:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:47:25', 'fKWhCounter', '3494.85864257813']
['2021-5-4 23:47:25', 'fActPhLevelMixTank1', '5.56993293762207']
['2021-5-4 23:47:25', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 23:47:25', 'fActPhLevelMixTank2', '3.73467206954956']
['2021-5-4 23:47:25', 'fActEcLevelMixTank2', '1033.814453125']
['2021-5-4 23:47:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:47:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:47:25', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 23:47:25', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 23:47:25', 'fActCo2ValMemo', '816']
['2021-5-4 23:47:25', 'fActWaterLevelMixTank1', '277.409271240234']
['2021-5-4 23:47:25', 'fActWaterLevelMixTank2', '299.437927246094']
['2021-5-4 23:47:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:47:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:47:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:47:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:47:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:47:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:47:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:47:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:47:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:47:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:47:25', 'DoVa_Co2', '0']
['2021-5-4 23:47:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:47:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:47:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:47:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:47:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:48:25', 'fKWhCounter', '3495.05883789063']
['2021-5-4 23:48:25', 'fActPhLevelMixTank1', '5.58116388320923']
['2021-5-4 23:48:25', 'fActEcLevelMixTank1', '2021.24084472656']
['2021-5-4 23:48:25', 'fActPhLevelMixTank2', '3.73857855796814']
['2021-5-4 23:48:25', 'fActEcLevelMixTank2', '1034.42492675781']
['2021-5-4 23:48:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:48:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:48:25', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 23:48:25', 'fActRhValMemo', '50.4000015258789']
['2021-5-4 23:48:25', 'fActCo2ValMemo', '814']
['2021-5-4 23:48:25', 'fActWaterLevelMixTank1', '275.942474365234']
['2021-5-4 23:48:25', 'fActWaterLevelMixTank2', '281.266326904297']
['2021-5-4 23:48:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:48:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:48:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:48:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:48:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:48:25', 'DoPu_AddEcBMixTank_2', '0']

['2021-5-4 23:48:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:48:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:48:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:48:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:48:25', 'DoVa_Co2', '0']
['2021-5-4 23:48:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:48:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:48:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:48:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:48:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:49:25', 'fKWhCounter', '3495.25903320313']
['2021-5-4 23:49:25', 'fActPhLevelMixTank1', '5.57945489883423']
['2021-5-4 23:49:25', 'fActEcLevelMixTank1', '2021.39343261719']
['2021-5-4 23:49:25', 'fActPhLevelMixTank2', '3.77080607414246']
['2021-5-4 23:49:25', 'fActEcLevelMixTank2', '1034.57751464844']
['2021-5-4 23:49:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:49:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:49:25', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 23:49:25', 'fActRhValMemo', '50']
['2021-5-4 23:49:25', 'fActCo2ValMemo', '814']
['2021-5-4 23:49:25', 'fActWaterLevelMixTank1', '275.263427734375']
['2021-5-4 23:49:25', 'fActWaterLevelMixTank2', '288.681640625']
['2021-5-4 23:49:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:49:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:49:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:49:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:49:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:49:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:49:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:49:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:49:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:49:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:49:25', 'DoVa_Co2', '0']
['2021-5-4 23:49:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:49:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:49:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:49:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:49:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:50:25', 'fKWhCounter', '3495.35913085938']
['2021-5-4 23:50:25', 'fActPhLevelMixTank1', '5.58507013320923']
['2021-5-4 23:50:25', 'fActEcLevelMixTank1', '2026.73425292969']
['2021-5-4 23:50:25', 'fActPhLevelMixTank2', '3.78960537910461']
['2021-5-4 23:50:25', 'fActEcLevelMixTank2', '1036.25598144531']
['2021-5-4 23:50:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:50:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:50:25', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 23:50:25', 'fActRhValMemo', '49.5999984741211']
['2021-5-4 23:50:25', 'fActCo2ValMemo', '814']
['2021-5-4 23:50:25', 'fActWaterLevelMixTank1', '275.643707275391']
['2021-5-4 23:50:25', 'fActWaterLevelMixTank2', '288.301361083984']
['2021-5-4 23:50:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:50:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:50:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:50:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:50:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:50:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:50:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:50:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:50:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:50:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:50:25', 'DoVa_Co2', '0']
['2021-5-4 23:50:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:50:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:50:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:50:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:50:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:51:25', 'fKWhCounter', '3495.55932617188']
['2021-5-4 23:51:25', 'fActPhLevelMixTank1', '5.58409357070923']
['2021-5-4 23:51:25', 'fActEcLevelMixTank1', '2027.95495605469']
['2021-5-4 23:51:25', 'fActPhLevelMixTank2', '3.78398990631104']
['2021-5-4 23:51:25', 'fActEcLevelMixTank2', '1035.18786621094']
['2021-5-4 23:51:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:51:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:51:25', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 23:51:25', 'fActRhValMemo', '49.5']
['2021-5-4 23:51:25', 'fActCo2ValMemo', '813']
['2021-5-4 23:51:25', 'fActWaterLevelMixTank1', '275.15478515625']
['2021-5-4 23:51:25', 'fActWaterLevelMixTank2', '288.002593994141']
['2021-5-4 23:51:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:51:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:51:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:51:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:51:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:51:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:51:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:51:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:51:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:51:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:51:25', 'DoVa_Co2', '0']
['2021-5-4 23:51:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:51:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:51:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:51:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:51:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:52:25', 'fKWhCounter', '3495.65942382813']
['2021-5-4 23:52:25', 'fActPhLevelMixTank1', '5.58409357070923']
['2021-5-4 23:52:25', 'fActEcLevelMixTank1', '2027.64978027344']
['2021-5-4 23:52:25', 'fActPhLevelMixTank2', '3.78814053535461']
['2021-5-4 23:52:25', 'fActEcLevelMixTank2', '1037.47668457031']
['2021-5-4 23:52:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:52:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:52:25', 'fActTempValMemo', '22.2000007629395']
['2021-5-4 23:52:25', 'fActRhValMemo', '48.5999984741211']
['2021-5-4 23:52:25', 'fActCo2ValMemo', '814']
['2021-5-4 23:52:25', 'fActWaterLevelMixTank1', '274.638702392578']
['2021-5-4 23:52:25', 'fActWaterLevelMixTank2', '287.9482421875']
['2021-5-4 23:52:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:52:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:52:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:52:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:52:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:52:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:52:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:52:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:52:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:52:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:52:25', 'DoVa_Co2', '0']
['2021-5-4 23:52:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:52:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:52:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:52:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:52:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:53:25', 'fKWhCounter', '3495.75952148438']
['2021-5-4 23:53:25', 'fActPhLevelMixTank1', '5.59141826629639']
['2021-5-4 23:53:25', 'fActEcLevelMixTank1', '2029.17565917969']
['2021-5-4 23:53:25', 'fActPhLevelMixTank2', '3.78032779693604']
['2021-5-4 23:53:25', 'fActEcLevelMixTank2', '1034.88269042969']
['2021-5-4 23:53:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:53:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:53:25', 'fActTempValMemo', '22.2999992370605']
['2021-5-4 23:53:25', 'fActRhValMemo', '48']
['2021-5-4 23:53:25', 'fActCo2ValMemo', '814']
['2021-5-4 23:53:25', 'fActWaterLevelMixTank1', '275.263427734375']
['2021-5-4 23:53:25', 'fActWaterLevelMixTank2', '287.975402832031']
['2021-5-4 23:53:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:53:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:53:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:53:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:53:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:53:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:53:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:53:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:53:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:53:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:53:25', 'DoVa_Co2', '0']
['2021-5-4 23:53:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:53:25', 'DoVa_IrrigateLevel_4_MT1', '0']

['2021-5-4 23:53:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:53:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:53:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:54:25', 'fKWhCounter', '3495.95971679688']
['2021-5-4 23:54:25', 'fActPhLevelMixTank1', '5.58189630508423']
['2021-5-4 23:54:25', 'fActEcLevelMixTank1', '2027.34460449219']
['2021-5-4 23:54:25', 'fActPhLevelMixTank2', '3.78228092193604']
['2021-5-4 23:54:25', 'fActEcLevelMixTank2', '1035.49304199219']
['2021-5-4 23:54:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:54:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:54:25', 'fActTempValMemo', '22.3999996185303']
['2021-5-4 23:54:25', 'fActRhValMemo', '47.2999992370605']
['2021-5-4 23:54:25', 'fActCo2ValMemo', '817']
['2021-5-4 23:54:25', 'fActWaterLevelMixTank1', '274.013946533203']
['2021-5-4 23:54:25', 'fActWaterLevelMixTank2', '287.540832519531']
['2021-5-4 23:54:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:54:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:54:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:54:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:54:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:54:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:54:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:54:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:54:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:54:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:54:25', 'DoVa_Co2', '0']
['2021-5-4 23:54:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:54:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:54:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:54:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:54:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:55:25', 'fKWhCounter', '3496.05981445313']
['2021-5-4 23:55:25', 'fActPhLevelMixTank1', '5.58873271942139']
['2021-5-4 23:55:25', 'fActEcLevelMixTank1', '2024.90307617188']
['2021-5-4 23:55:25', 'fActPhLevelMixTank2', '3.78057193756104']
['2021-5-4 23:55:25', 'fActEcLevelMixTank2', '1033.66186523438']
['2021-5-4 23:55:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:55:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:55:25', 'fActTempValMemo', '22.5']
['2021-5-4 23:55:25', 'fActRhValMemo', '47.2000007629395']
['2021-5-4 23:55:25', 'fActCo2ValMemo', '816']
['2021-5-4 23:55:25', 'fActWaterLevelMixTank1', '274.041137695313']
['2021-5-4 23:55:25', 'fActWaterLevelMixTank2', '287.486480712891']
['2021-5-4 23:55:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:55:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:55:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:55:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:55:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:55:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:55:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:55:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:55:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:55:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:55:25', 'DoVa_Co2', '0']
['2021-5-4 23:55:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:55:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:55:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:55:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:55:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:56:25', 'fKWhCounter', '3496.26000976563']
['2021-5-4 23:56:25', 'fActPhLevelMixTank1', '5.58604717254639']
['2021-5-4 23:56:25', 'fActEcLevelMixTank1', '2024.75048828125']
['2021-5-4 23:56:25', 'fActPhLevelMixTank2', '3.78203678131104']
['2021-5-4 23:56:25', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 23:56:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:56:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:56:25', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:56:25', 'fActRhValMemo', '47']
['2021-5-4 23:56:25', 'fActCo2ValMemo', '812']
['2021-5-4 23:56:25', 'fActWaterLevelMixTank1', '275.290588378906']
['2021-5-4 23:56:25', 'fActWaterLevelMixTank2', '287.785278320313']
['2021-5-4 23:56:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:56:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:56:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:56:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:56:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:56:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:56:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:56:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:56:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:56:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:56:25', 'DoVa_Co2', '0']
['2021-5-4 23:56:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:56:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:56:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:56:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:56:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:57:25', 'fKWhCounter', '3496.36010742188']
['2021-5-4 23:57:25', 'fActPhLevelMixTank1', '5.58214044570923']
['2021-5-4 23:57:25', 'fActEcLevelMixTank1', '2022.46166992188']
['2021-5-4 23:57:25', 'fActPhLevelMixTank2', '3.77690958976746']
['2021-5-4 23:57:25', 'fActEcLevelMixTank2', '1033.2041015625']
['2021-5-4 23:57:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:57:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:57:25', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:57:25', 'fActRhValMemo', '46.5999984741211']
['2021-5-4 23:57:25', 'fActCo2ValMemo', '810']
['2021-5-4 23:57:25', 'fActWaterLevelMixTank1', '274.122619628906']
['2021-5-4 23:57:25', 'fActWaterLevelMixTank2', '288.274200439453']
['2021-5-4 23:57:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:57:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:57:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:57:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:57:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:57:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:57:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:57:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:57:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:57:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:57:25', 'DoVa_Co2', '0']
['2021-5-4 23:57:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:57:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:57:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:57:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:57:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:58:25', 'fKWhCounter', '3496.56030273438']
['2021-5-4 23:58:25', 'fActPhLevelMixTank1', '5.58482599258423']
['2021-5-4 23:58:25', 'fActEcLevelMixTank1', '2022.30908203125']
['2021-5-4 23:58:25', 'fActPhLevelMixTank2', '3.77568888664246']
['2021-5-4 23:58:25', 'fActEcLevelMixTank2', '1031.06787109375']
['2021-5-4 23:58:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:58:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:58:25', 'fActTempValMemo', '22.6000003814697']
['2021-5-4 23:58:25', 'fActRhValMemo', '46.2999992370605']
['2021-5-4 23:58:25', 'fActCo2ValMemo', '809']
['2021-5-4 23:58:25', 'fActWaterLevelMixTank1', '276.132629394531']
['2021-5-4 23:58:25', 'fActWaterLevelMixTank2', '287.540832519531']
['2021-5-4 23:58:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:58:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:58:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:58:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:58:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:58:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:58:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:58:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:58:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:58:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:58:25', 'DoVa_Co2', '0']
['2021-5-4 23:58:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:58:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:58:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:58:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_3_Blue', '0']

['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:58:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']
['2021-5-4 23:59:25', 'fKWhCounter', '3496.66040039063']
['2021-5-4 23:59:25', 'fActPhLevelMixTank1', '5.58336114883423']
['2021-5-4 23:59:25', 'fActEcLevelMixTank1', '2022.00390625']
['2021-5-4 23:59:25', 'fActPhLevelMixTank2', '3.77495646476746']
['2021-5-4 23:59:25', 'fActEcLevelMixTank2', '1034.27233886719']
['2021-5-4 23:59:25', 'fTaktCounterUpperLevel', '0']
['2021-5-4 23:59:25', 'fTaktCounterLowerLevel', '0']
['2021-5-4 23:59:25', 'fActTempValMemo', '22.5']
['2021-5-4 23:59:25', 'fActRhValMemo', '46.5']
['2021-5-4 23:59:25', 'fActCo2ValMemo', '808']
['2021-5-4 23:59:25', 'fActWaterLevelMixTank1', '275.915313720703']
['2021-5-4 23:59:25', 'fActWaterLevelMixTank2', '287.73095703125']
['2021-5-4 23:59:25', 'DoPu_AddAcidMixTank_1', '0']
['2021-5-4 23:59:25', 'DoPu_AddEcAMixTank_1', '0']
['2021-5-4 23:59:25', 'DoPu_AddEcBMixTank_1', '0']
['2021-5-4 23:59:25', 'DoPu_AddAcidMixTank_2', '0']
['2021-5-4 23:59:25', 'DoPu_AddEcAMixTank_2', '0']
['2021-5-4 23:59:25', 'DoPu_AddEcBMixTank_2', '0']
['2021-5-4 23:59:25', 'DoVa_IrrigateLevel_1_MT1', '0']
['2021-5-4 23:59:25', 'DoVa_IrrigateLevel_2_MT1', '0']
['2021-5-4 23:59:25', 'DoVa_IrrigateLevel_1_MT2', '0']
['2021-5-4 23:59:25', 'DoVa_IrrigateLevel_2_MT2', '0']
['2021-5-4 23:59:25', 'DoVa_Co2', '0']
['2021-5-4 23:59:25', 'DoVa_IrrigateLevel_3_MT1', '0']
['2021-5-4 23:59:25', 'DoVa_IrrigateLevel_4_MT1', '0']
['2021-5-4 23:59:25', 'DoVa_IrrigateLevel_3_MT2', '0']
['2021-5-4 23:59:25', 'DoVa_IrrigateLevel_4_MT2', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_1_Red', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_1_Fred', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_1_Blue', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_1_White', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_2_Red', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_2_Fred', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_2_Blue', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_2_White', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_3_Red', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_3_Fred', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_3_Blue', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_3_White', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_4_Red', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_4_Fred', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_4_Blue', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelLayer_4_White', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelSeedLayer_1_Red', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelSeedLayer_1_Fred', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelSeedLayer_1_Blue', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelSeedLayer_1_White', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelSeedLayer_2_Red', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelSeedLayer_2_Fred', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelSeedLayer_2_Blue', '0']
['2021-5-4 23:59:25', 'Ao_SetLightLevelSeedLayer_2_White', '0']

In [89]:
print(df)

                Date                           Variable Value
0  2021-5-4 23:59:25  Ao_SetLightLevelSeedLayer_2_White     0

In [87]:
df.to_csv('./output.csv')